/* Spring curve generator — Opus 5 concept workspace
 *
 * WHY THIS EXISTS
 * ---------------
 * cubic-bezier can overshoot exactly once and can never oscillate. Real spring
 * motion settles through several decaying bounces, and that settle is most of
 * what separates motion that feels physical from motion that merely eases. CSS
 * linear() removes the limitation: sample a real spring and hand the samples
 * over as an easing curve.
 *
 * The constants are not invented. PMConcept7 declares per-family spring
 * stiffness and damping for its pointer-magnet engine (--pm8-stiff / --pm8-damp,
 * lines 8336-8343). Reading them as a damped harmonic oscillator with unit mass
 * gives a damping ratio per theme family that lands exactly on the four
 * personalities the themes already claim:
 *
 *   retro     k=340 c=30  -> zeta 0.81  tight, barely overshoots, mechanical
 *   basic     k=210 c=26  -> zeta 0.90  near-critical, one restrained settle
 *   glass     k=110 c=15  -> zeta 0.72  loose and slow, gentle oscillation
 *   friendly  k=150 c=14  -> zeta 0.57  pronounced, bouncy, several settles
 *
 * The workspace has no runtime build step and must run from file://, so this
 * script does NOT run in the browser. It prints CSS that is committed into
 * tokens.css by hand, which keeps the numbers reproducible without adding a
 * dependency to the thing being demonstrated.
 *
 * Run:  node tools/build-springs.mjs
 */

/* Closed-form position of a unit-mass damped harmonic oscillator released from
 * x = 1 with zero velocity, settling to x = 0. Returned inverted so 0 -> 1
 * matches the direction CSS easing expects. */
function springProgress(t, stiffness, damping, mass = 1) {
  const w0 = Math.sqrt(stiffness / mass);
  const zeta = damping / (2 * Math.sqrt(stiffness * mass));

  if (zeta < 1) {
    /* Underdamped: oscillates. This is the case we actually want everywhere —
     * all four families sit below 1. */
    const wd = w0 * Math.sqrt(1 - zeta * zeta);
    return 1 - Math.exp(-zeta * w0 * t) * (Math.cos(wd * t) + ((zeta * w0) / wd) * Math.sin(wd * t));
  }
  if (zeta === 1) {
    /* Critically damped: fastest approach with no overshoot. */
    return 1 - Math.exp(-w0 * t) * (1 + w0 * t);
  }
  /* Overdamped: two decaying exponentials, no overshoot. */
  const r = Math.sqrt(zeta * zeta - 1);
  const a = -zeta * w0 + w0 * r;
  const b = -zeta * w0 - w0 * r;
  const A = b / (b - a);
  const B = a / (a - b);
  return 1 - (A * Math.exp(a * t) + B * Math.exp(b * t));
}

/* Time at which the spring has settled inside `epsilon` and stays there. The
 * curve is normalised against this so the CSS duration means "the whole
 * motion", not "the first bounce". */
function settleTime(stiffness, damping, epsilon = 0.001, max = 10) {
  const step = 1 / 240;
  let last = 0;
  for (let t = 0; t <= max; t += step) {
    if (Math.abs(1 - springProgress(t, stiffness, damping)) > epsilon) last = t;
  }
  return last + step;
}

/* Sample into linear() points. Uniform sampling is wasteful at the tail where
 * nothing happens, so points are dropped when three in a row are collinear
 * within a tight tolerance — same curve, far fewer numbers. */
function toLinear(stiffness, damping, samples = 90) {
  const end = settleTime(stiffness, damping);
  const raw = [];
  for (let i = 0; i <= samples; i++) {
    const p = i / samples;
    raw.push({ p, v: springProgress(p * end, stiffness, damping) });
  }
  raw[0].v = 0;
  raw[raw.length - 1].v = 1;

  const kept = [raw[0]];
  for (let i = 1; i < raw.length - 1; i++) {
    const a = kept[kept.length - 1], b = raw[i], c = raw[i + 1];
    const span = c.p - a.p;
    const interpolated = span === 0 ? b.v : a.v + ((b.p - a.p) / span) * (c.v - a.v);
    if (Math.abs(interpolated - b.v) > 0.0012) kept.push(b);
  }
  kept.push(raw[raw.length - 1]);

  return 'linear(' + kept
    .map(pt => `${round(pt.v)} ${round(pt.p * 100)}%`)
    .join(', ') + ')';
}

function round(n) {
  return String(Math.round(n * 1000) / 1000);
}

const FAMILIES = [
  { name: 'retro',    stiffness: 340, damping: 30 },
  { name: 'basic',    stiffness: 210, damping: 26 },
  { name: 'glass',    stiffness: 110, damping: 15 },
  { name: 'friendly', stiffness: 150, damping: 14 }
];

console.log('/* Generated by tools/build-springs.mjs — do not hand-edit the curves. */\n');

for (const f of FAMILIES) {
  const zeta = f.damping / (2 * Math.sqrt(f.stiffness));
  const settle = settleTime(f.stiffness, f.damping);
  const curve = toLinear(f.stiffness, f.damping);
  const points = curve.split(',').length;
  console.log(`/* ${f.name}: k=${f.stiffness} c=${f.damping} zeta=${zeta.toFixed(3)} ` +
              `settles in ${settle.toFixed(3)}s, ${points} points */`);
  console.log(`[data-theme^="${f.name}"] {`);
  console.log(`  --pmx-stiff: ${f.stiffness};`);
  console.log(`  --pmx-damp: ${f.damping};`);
  console.log(`  --ease-spring-real: ${curve};`);
  console.log('}\n');
}
