/* PMX report generator — Opus 5
 *
 * Writes TEST_REPORT.md from `interaction-test-report.json` and `demo-trigger-report.json`.
 *
 * WHY THIS EXISTS
 * ---------------
 * TEST_REPORT.md already opened with the sentence "Generated from the runs recorded in
 * interaction-test-report.json and demo-trigger-report.json. Nothing in this file is asserted by
 * hand." That was not true. The file was written by hand, and so were the two JSON reports it cited
 * — transcribed out of `window.__pmxTestExit` and a console sweep. Nothing mechanically coupled a
 * claim to a measurement.
 *
 * The cost of that was visible before anyone went looking for it: the reports described a 23-suite,
 * 93-event build while the tree held 26 suites and 113 distinct behaviours, and the two suites they
 * did not list were the two that could not run, because they had been pasted inside another suite's
 * body where the runner's snapshot could never reach them. A hand-written report cannot notice that.
 * A generated one cannot state it.
 *
 * So: `drive.mjs` measures and writes the JSON; this reads the JSON and writes the prose. Neither
 * invents a number. If a section is missing from the JSON this says so in the output rather than
 * carrying the previous run's figure forward, because a stale number that looks current is worse
 * than an admitted gap.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

function readJson(name) {
  const path = join(ROOT, name);
  if (!existsSync(path)) return { __missing: `${name} does not exist` };
  try {
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch (err) {
    /* Refuse to guess. A corrupt report is a measurement failure and must read as one. */
    return { __missing: `${name} is not valid JSON: ${err.message}` };
  }
}

const it = readJson('interaction-test-report.json');
const dt = readJson('demo-trigger-report.json');

const lines = [];
const say = (s = '') => lines.push(s);

say('# Test Report — Opus 5 Assistant Chat concept workspace');
say();
say('**This file is generated by `tools/report.mjs` from `interaction-test-report.json` and');
say('`demo-trigger-report.json`, which are themselves written by `tools/drive.mjs` from a real');
say('headless run. No number below is typed by hand. Regenerate with:**');
say();
say('```bash');
say('node tools/drive.mjs scan && node tools/drive.mjs suite && node tools/drive.mjs matrix \\');
say('  && node tools/drive.mjs triggers && node tools/drive.mjs activity \\');
say('  && node tools/drive.mjs paging && node tools/report.mjs');
say('```');
say();
say('Every command that writes a section is in that line. It used to omit `paging` and `scan`, so');
say('following it exactly regenerated a report whose question-paging table was the previous run\'s and');
say('whose folder gate had not been run at all.');
say();

/* ---------------------------------------------------------------- suite */
say('## 1. Interaction suite');
say();
const s = it.interactionSuite;
if (!s) {
  say(`> Not measured. ${it.__missing || 'the interactionSuite section is absent'}.`);
} else {
  say(`| | |`);
  say(`|---|---|`);
  say(`| Suites | ${s.suites} |`);
  say(`| Assertions | ${s.assertions} |`);
  say(`| Passed | ${s.passed} |`);
  say(`| Failed | **${s.failed}** |`);
  say(`| Page console errors | ${s.pageConsoleErrorCount} |`);
  say(`| Page console warnings | ${s.pageConsoleWarningCount} |`);
  say(`| Viewport | ${s.viewport ? `${s.viewport.width}x${s.viewport.height}` : 'n/a'} |`);
  say(`| Duration | ${s.durationMs} ms |`);
  say();
  say(`Suites, in registration order: ${(s.suiteNames || []).map((n) => `\`${n}\``).join(', ')}.`);
  say();
  if (s.failed) {
    say('Failures:');
    say();
    for (const f of s.failures || []) say(`- \`${f.suite}\` — ${f.msg}`);
  } else {
    say('No failures, and the run is clean of console errors AND warnings. The suite fails on either,');
    say('because a warning is how a missing icon key or an unbound service announces itself here.');
  }
}
say();

/* ---------------------------------------------------------------- matrix */
say('## 2. Pairing and width matrix');
say();
if (!it.matrix) {
  say('> Not measured in the recorded run.');
} else {
  const m = it.matrix;
  say(`**${m.runs} runs, ${m.assertions} assertions, ${m.failed} failed.**`);
  if (m.durationMs) say(` Duration ${m.durationMs} ms.`);
}
say();

/* ---------------------------------------------------------------- triggers */
say('## 3. Demo director');
say();
if (dt.__missing || !dt.vocabulary) {
  say(`> Not measured. ${dt.__missing || 'no vocabulary section'}.`);
} else {
  const v = dt.vocabulary;
  say('Two counts are reported, and the difference between them matters.');
  say();
  say(`- **${v.familyKeys} family keys** over **${v.distinctFamilies} distinct families**.`);
  say(`  \`subagent\` is an alias of \`agent\`: the contract names the family one way and this harness`);
  say('  named it another, and both resolve so either vocabulary works.');
  say(`- **${v.eventsAcrossFamilyKeys} events across family keys** — the raw number, inflated, because`);
  say('  the alias family is counted a second time and several event names are second names bound to');
  say(`  one function — versus **${v.distinctBehaviours} distinct behaviours**, which is the number of`);
  say('  things the Director can actually do.');
  say();
  const raw = dt.totalsRaw || {};
  const dis = dt.totalsDistinct || {};
  say('| | fired | ok | failed | changed the store | changed the DOM | inert |');
  say('|---|---|---|---|---|---|---|');
  say(`| raw | ${raw.fired} | ${raw.ok} | **${raw.failed}** | ${raw.storeChanged} | ${raw.domChangedAfterFrame} | ${raw.inertNeitherStoreNorDom} |`);
  say(`| distinct | ${dis.fired} | ${dis.ok} | **${dis.failed}** | ${dis.storeChanged} | ${dis.domChangedAfterFrame} | ${dis.inertNeitherStoreNorDom} |`);
  say();
  say('"Inert" is not a failure. Some triggers restore a state that is already current, and a trigger');
  say('that honestly does nothing is better than one that reports a change it did not make.');
  say();

  /* The packet asks for fourteen NAMED states, and nine of the fourteen happen to be family names.
   * Reporting only the family list therefore answers nine fourteenths of the question and leaves the
   * other five looking absent. */
  const ps = dt.packetStates;
  if (!ps) {
    say('> The packet-state coverage map was not measured in this run — re-run `drive.mjs triggers`.');
  } else {
    say('### The fourteen states the packet names');
    say();
    say('Nine of the fourteen are also family names here; five are not, and those five are the reason');
    say('this table exists. The mapping is declared in `tools/drive.mjs` and then checked against the');
    say('sweep, so a state counts as covered only when one of its events actually fired.');
    say();
    say(`**${ps.covered} of ${ps.required} covered.**` + (ps.uncovered.length ? ` Uncovered: ${ps.uncovered.join(', ')}.` : ''));
    say();
    say('| packet state | events fired ok / named | where it lives here |');
    say('|---|---|---|');
    for (const s of ps.byState || []) {
      const where = s.note || `the \`${s.events[0].split('.')[0]}\` family`;
      say(`| ${s.covered ? '' : '**'}${s.state}${s.covered ? '' : '**'} | ${s.firedOk} / ${s.named} | ${where} |`);
    }
    if ((ps.staleStateEvents || []).length) {
      say();
      say('Events named in the map that the Director no longer has (the map is drifting):');
      say();
      for (const s of ps.staleStateEvents) say(`- \`${s.state}\` — ${s.notInVocabulary.map((e) => `\`${e}\``).join(', ')}`);
    }
  }
}
say();

/* ---------------------------------------------------------------- activity */
say('## 4. Activity flow — the pixel probe');
say();
say('This is the section the packet\'s correction exists for. `03_compact_execution_activity.mov` is');
say('reproduced as behaviour in all eight thread concepts, and the probe asserts the RENDERED result');
say('at each beat rather than counting dispatches — the specific failure mode that let a previous');
say('build report motion the DOM never performed.');
say();
if (!it.activity || !it.activity.concepts) {
  say('> Not measured in the recorded run.');
} else {
  const cs = it.activity.concepts;
  /* Every verdict key the probe recorded becomes a column. Naming the columns by hand is how the
   * first draft of this table came to omit the ONE dimension that was failing, so it read all-yes
   * directly above a list of failures. A generated report must not be able to leave a measurement
   * out of the summary it draws from. */
  const keys = [];
  for (const c of cs) for (const k of Object.keys(c.verdict || {})) if (!keys.includes(k)) keys.push(k);
  const human = (k) => k.replace(/([A-Z])/g, ' $1').toLowerCase();
  /* Booleans read yes/NO; a count reads as itself. A verdict is not always a pass/fail — some of
   * these are "how many did I actually observe", and printing those as n/a hid whether the probe
   * had exercised anything at all. */
  const mark = (v) => {
    if (v === true) return 'yes';
    if (v === false) return '**NO**';
    if (typeof v === 'number') return String(v);
    /* A list or a string is data too. Printing them as n/a is how the `sentence row via` and
     * `handover beats` columns came to be three tables of the word "n/a" — present, measured, and
     * rendered as absent. */
    if (Array.isArray(v)) return v.length ? '`' + v.join('`, `') + '`' : '—';
    if (typeof v === 'string') return '`' + v + '`';
    return 'n/a';
  };
  /* The gate list comes from the measurement, not from this file. Deciding here which dimensions
   * count as failures is how a report starts disagreeing with the exit code it summarises. */
  const gated = it.activity.gatedVerdictKeys || keys;
  const recorded = it.activity.recordedVerdictKeys || {};
  say(`| concept | capsule | ${keys.map((k) => (gated.includes(k) ? '**' + human(k) + '**' : human(k))).join(' | ')} |`);
  say(`|---|---|${keys.map(() => '---').join('|')}|`);
  for (const c of cs) {
    const v = c.verdict || {};
    say(`| ${c.concept} | \`${c.capsuleClass || 'n/a'}\` | ${keys.map((k) => mark(v[k])).join(' | ')} |`);
  }
  say();
  say('Bold column headings are the EXIT GATE — a `NO` there is a defect. The rest are recorded and');
  say('deliberately not gated, because a concept whose layout differs from one reference geometry has');
  say('made a choice, and scoring the choice as a failure would be measuring conformity rather than');
  say('the product. The distinction comes from the measurement itself (`gatedVerdictKeys`), so this');
  say('summary cannot drift from the exit code it describes.');
  say();
  const failing = cs.filter((c) => gated.some((k) => c.verdict && c.verdict[k] === false));
  const diverging = cs.filter((c) => Object.keys(recorded).some((k) => c.verdict && c.verdict[k] === false));
  if (failing.length) {
    say('Concepts failing a GATED verdict:');
    say();
    for (const c of failing) {
      const bad = gated.filter((k) => c.verdict[k] === false);
      say(`- **${c.concept}** — ${bad.join(', ')}`);
    }
  } else if (diverging.length) {
    say('All eight pass every gated verdict. Recorded, non-gating differences, with the reason each is');
    say('recorded rather than failed:');
    say();
    for (const c of diverging) {
      for (const k of Object.keys(recorded)) {
        if (c.verdict[k] === false) say(`- **${c.concept}**, \`${k}\` — ${recorded[k]}`);
      }
    }
  } else {
    say('All eight pass every verdict. "Header held still" is measured as the y-coordinate of the');
    say('capsule header before and after a count tick, sampled both mid-animation and once settled:');
    say('the count is rewritten in place, which is the claim frames 208 through 338 make.');
  }
  say();
  say(`Evidence: PNGs in \`evidence/\`, named \`activity-t{N}-{NN}-{beat}.png\`, clipped to the run`);
  say('capsule where one exists.');
}
say();

/* ---------------------------------------------------------------- question paging */
say('## 5. Question paging');
say();
say('`02_stable_paged_questionnaire.mov` is a REVIEWABLE questionnaire: you page back, the answer is');
say('still there, and the card does not replay its entrance. Its card also only looks stable because');
say('every one of its pages carries four option rows — ours genuinely differ, so the card resizes');
say('instead, using the bounce from PMConcept7\'s own model picker.');
say();
if (!it.questionPaging || !it.questionPaging.concepts) {
  say('> Not measured in the recorded run.');
} else {
  const cs = it.questionPaging.concepts;
  const mark = (v) => (v === true ? 'yes' : v === false ? '**NO**' : 'n/a');
  say('| concept | root | forward | back | same root throughout | entrance replayed going back | answer still shown | heights |');
  say('|---|---|---|---|---|---|---|---|');
  for (const c of cs) {
    const v = c.verdict || {};
    const h = (v.heights || []).map((n) => Math.round(n)).join(' / ');
    /* "entrance replayed" is the one column where NO is the good answer, so it is stated as the
     * behaviour rather than as a bare boolean the reader has to invert. */
    say(`| ${c.concept} | \`${c.rootSelector}\` | ${c.pagesForward} | ${c.pagesBack} | ${mark(v.rootIdentityHeldEveryStep)} | ${v.entranceReplayedOnBackwardStep ? '**replayed**' : 'no'} | ${mark(v.answerStillShownAfterPagingBack)} | ${h} |`);
  }
  say();
  say('The height column is the evidence that the bounce has something to animate: a card whose height');
  say('never changed would be a resize primitive wired to nothing, which is the failure this workspace');
  say('has produced three times and now tests for.');
}
say();

/* ---------------------------------------------------------------- provenance */
say('## 6. Provenance');
say();
if (it.provenance) {
  for (const [k, v] of Object.entries(it.provenance)) {
    say(`- \`${k}\` (interaction-test-report.json): ${typeof v === 'object' ? JSON.stringify(v) : v}`);
  }
} else {
  say('- No provenance block in the recorded run.');
}
/* The Director section comes from the OTHER file, and reading only the first file's provenance made
 * it look carried over when it had in fact just been measured. Each section is stamped by whichever
 * file actually holds it. */
if (dt.generatedAt) {
  say(`- \`director\` (demo-trigger-report.json): {"measuredAt":"${dt.generatedAt}","by":"${dt.generatedBy}"}`);
}
say();
say('The folder scan (`node tools/drive.mjs scan`) is a separate gate and is not summarised here. It');
say('checks four things and exits non-zero on any hit: no source file carries a NUL byte or fails');
say('UTF-8 decode; no forbidden provider-acquisition phrase appears anywhere in the folder; no emoji');
say('or pictograph appears in any file, comments and strings included; and every `cmd.*` id named in');
say('surface source, in `candidate-wiring-delta.json` or in `plan-owner-delta.md` is recorded in');
say('`candidate-command-delta.json`, so no surface can print a command the catalog owner has not been');
say('shown.');
say();

writeFileSync(join(ROOT, 'TEST_REPORT.md'), lines.join('\n'));
console.log(`report: TEST_REPORT.md written, ${lines.length} lines`);
