#!/usr/bin/env python3
"""Regenerate versions/v0-baseline.js from Concepts/PMConcept7.html.

Run from Concepts/:   python3 panel-bakeoff/tools/extract_baseline.py

v0 is the CONTROL, not a candidate. It carries today's markup verbatim and
registers with fixes:false so it opts out of the shared [data-pm-fixes="on"]
repairs. The fit checker must report R4 (sub-24px hit target) failures on it in
all 8 themes -- that is how the checker proves it detects a known-true defect
before anyone trusts its verdict on a redesign.

Panel spans are found by walking <div> depth from each .side-panel-view opener,
so they survive edits to PMConcept7.html rather than depending on line numbers.
The extractor asserts the markup contains no backtick and no ${, then emits the
HTML as JSON string literals -- so a template-literal hazard can never reach the
generated file even if the source later grows one.
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)                          # panel-bakeoff/
SRC = os.path.join(os.path.dirname(ROOT), 'PMConcept7.html')

# panel element id -> key used by the harness
PANELS = [
    ('panel-search',      'search'),
    ('panel-source',      'source'),
    ('panel-git',         'git'),
    ('panel-docker',      'docker'),
    ('pm6-panel-testing', 'tests'),
    ('pm6-panel-agents',  'agents'),
    ('panel-artifacts',   'artifacts'),
    ('panel-files',       'files'),
]

OPEN = re.compile(r'<div\b', re.I)
CLOSE = re.compile(r'</div\s*>', re.I)


def find_start(lines, pid):
    pat = 'id="%s"' % pid
    for i, l in enumerate(lines, 1):
        if 'side-panel-view' in l and pat in l:
            return i
    sys.exit('panel not found in PMConcept7.html: ' + pid)


def span(lines, start):
    """(first_inner, last_inner) 1-indexed, by <div> depth from the opener."""
    depth = 0
    for i in range(start, len(lines) + 1):
        depth += len(OPEN.findall(lines[i - 1])) - len(CLOSE.findall(lines[i - 1]))
        if i > start and depth <= 0:
            return start + 1, i - 1
    sys.exit('unbalanced <div> from line %d' % start)


def dedent(text):
    ls = [x.rstrip('\n') for x in text.split('\n')]
    ind = [len(x) - len(x.lstrip()) for x in ls if x.strip()]
    cut = min(ind) if ind else 0
    return '\n'.join((x[cut:] if len(x) >= cut else x) for x in ls).strip('\n')


def main():
    if not os.path.isfile(SRC):
        sys.exit('PMConcept7.html not found at ' + SRC)
    lines = open(SRC).readlines()
    panels, ranges = {}, {}
    for pid, key in PANELS:
        s = find_start(lines, pid)
        a, b = span(lines, s)
        inner = dedent(''.join(lines[a - 1:b]))
        if '`' in inner or '${' in inner:
            sys.exit('template-literal hazard in %s -- emit strategy must stay JSON' % pid)
        panels[key] = inner
        ranges[key] = (s, b + 1)

    spans = '\n'.join('     %-9s PMConcept7.html:%d-%d' % (k, ranges[k][0], ranges[k][1])
                      for _, k in PANELS)
    body = ',\n'.join('    %s: %s' % (k, json.dumps(panels[k])) for _, k in PANELS)

    out = '''/* PANEL BAKEOFF - v0 BASELINE (the control)
   =====================================================================
   Today's markup, VERBATIM from Concepts/PMConcept7.html.
   GENERATED by tools/extract_baseline.py - do not hand-edit; re-extract.

   Source line ranges (inner HTML of each .side-panel-view):
%s

   This version exists to be MEASURED, not admired. It registers with
   fixes:false, opting out of the shared [data-pm-fixes="on"] repairs, so it
   keeps the real defects:

     - sub-24px hit targets in all 8 themes (.pm6-sp-row ~22.5-23.6px,
       .pm6-sp-btn ~23.5px, .pm6-sp-minibtn ~19.5px, .pm6-sp-iconbtn ~21px)
     - .pm6-sp-card-head at var(--display-font) 10px -> Orbitron under retro
     - native <select> in Search (scope) and Source Control (branch)
     - .pm6-kv space-between rows whose value collapses
     - kind-chip + label + status-chip rows that truncate the label to nothing

   The fit checker MUST report R4 failures here in all 8 themes. That is not a
   harness bug - it is the checker's self-validation.
   ===================================================================== */
PM_BAKEOFF.register('v0', {
  name: 'Baseline (today)',
  blurb: 'PMConcept7 as it ships. The control, not a candidate.',
  fixes: false,
  panels: {
%s
  }
});
''' % (spans, body)
    dest = os.path.join(ROOT, 'versions', 'v0-baseline.js')
    open(dest, 'w').write(out)
    print('wrote versions/v0-baseline.js')
    for _, k in PANELS:
        print('  %-10s %6d bytes  (PM7:%d-%d)' % (k, len(panels[k]), ranges[k][0], ranges[k][1]))


if __name__ == '__main__':
    main()
