#!/usr/bin/env python3
"""Regenerate the bakeoff's extracted CSS from Concepts/pm6-build/parts/.

Run from Concepts/:   python3 panel-bakeoff/tools/extract_shell.py

Emits (overwriting):
  panel-bakeoff/_pm-tokens.css       root contract + the 8 theme blocks, verbatim
  panel-bakeoff/_pm-primitives.css   the whole shared side-panel primitive layer, verbatim
  panel-bakeoff/_extracted.css       theme-aware supporting rules, verbatim, by selector

_pm-shell.css is NOT regenerated: it is hand-authored around _extracted.css.
Re-run this after any change to the parts tree, then diff _extracted.css.

Design note: rules nested inside @media are excluded by construction. The
tokenizer treats "@media ... {" as an unmatched selector and skips the entire
block, which is what we want -- the app keys panel width to viewport width, and
in the harness width is an input rather than a consequence.
"""
import re, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)                      # panel-bakeoff/
P    = os.path.join(os.path.dirname(ROOT), 'pm6-build', 'parts') + os.sep

SUPPORT_PATTERNS = [
    r'\.files-panel-header', r'\.file-tree', r'\.wizard-input', r'\.wizard-select',
    r'\.sc-accordion', r'\.sc-wt-', r'\.context-menu-mock', r'\.ctx-item', r'\.ctx-sep',
    r'\.panel-content', r'\.git-status', r'\.search-result-item', r'\.search-match',
    r'\.chat-toggle-btn', r'\.remote-badge', r'\.wt-status-pill', r'\.wt-create',
    r'\.side-panel-slot', r'\.side-panel-view', r'\.resizer-col', r'\.left-panel',
    r'\.activity-bar', r'\.pm6-ab-', r'\.pm-ab-', r'@keyframes slideInLeft',
]
SUPPORT_SOURCES = [
    '05-css-shell.part.html', '06-css-components-a.part.html',
    '07-css-components-b.part.html', '09-css-bento-themes.part.html',
    '10x-pm6-css-global.part.html', '03-css-glass-a.part.html',
    '04-css-glass-b.part.html',
]


def slice_lines(fn, a, b):
    with open(P + fn) as f:
        return ''.join(f.readlines()[a - 1:b])


def walk_rules(fn):
    """Yield (line, selector, body) for every TOP-LEVEL rule. @media blocks are skipped whole."""
    txt = open(P + fn).read()
    i, n = 0, len(txt)
    while i < n:
        b = txt.find('{', i)
        if b < 0:
            return
        head = txt[i:b]
        cut = max(head.rfind('}'), head.rfind('*/'))
        sel = (head[cut + 1:] if cut >= 0 else head).strip()
        depth, j = 0, b
        while j < n:
            if txt[j] == '{':
                depth += 1
            elif txt[j] == '}':
                depth -= 1
                if depth == 0:
                    break
            j += 1
        yield txt[:i + cut + 1].count('\n') + 1, sel, txt[b:j + 1]
        i = j + 1


def banner(t):
    return '\n/* ' + '=' * 72 + '\n   ' + t + '\n   ' + '=' * 72 + ' */\n'


def main():
    if not os.path.isdir(P):
        sys.exit('parts tree not found at ' + P)

    # ---- tokens -------------------------------------------------------------
    out = ["""/* PANEL BAKEOFF -- token layer.  GENERATED by tools/extract_shell.py; do not hand-edit.

   VERBATIM from parts/02-css-tokens.part.html.

   Why the harness needs no iframes: every theme selector in the source is a
   bare attribute selector ([data-theme="x"] { ... }), never html[data-theme]
   or :root[data-theme] -- 0 root-anchored selectors across 1055 sites. So
   data-theme on any <div> themes that subtree verbatim, and all 8 themes can
   render as siblings in one document with full DOM access for the fit checker. */
"""]
    out.append(banner('ROOT TOKEN CONTRACT  (parts/02-css-tokens.part.html:25-135)'))
    out.append(slice_lines('02-css-tokens.part.html', 25, 135))
    out.append(banner('THE 8 THEMES  (parts/02-css-tokens.part.html:137-552)'))
    out.append(slice_lines('02-css-tokens.part.html', 137, 552))
    open(os.path.join(ROOT, '_pm-tokens.css'), 'w').write(''.join(out))

    # ---- primitives ---------------------------------------------------------
    prim = open(P + '10x-pm6-css-panels.part.html').read()
    prim = prim.split('\n', 1)[1].rsplit('</style>', 1)[0]
    open(os.path.join(ROOT, '_pm-primitives.css'), 'w').write(
        '/* PANEL BAKEOFF -- shared side-panel primitives.  GENERATED; do not hand-edit.\n'
        '   VERBATIM from parts/10x-pm6-css-panels.part.html (whole file, style tags stripped).\n'
        '   v0-baseline must keep these unmodified so the fit checker can detect their\n'
        '   known defects (sub-24px hit targets; display font at 10px). Fixes live in\n'
        '   _pm-shell.css under [data-pm-fixes="on"], which v0 opts out of. */\n' + prim)

    # ---- supporting rules ---------------------------------------------------
    seen, chunks, count = set(), [], 0
    for fn in SUPPORT_SOURCES:
        got = []
        for ln, sel, body in walk_rules(fn):
            if not sel or sel.startswith('<') or sel.startswith('@media'):
                continue
            if not any(re.search(p, sel) for p in SUPPORT_PATTERNS):
                continue
            rule = sel + ' ' + body.strip()
            key = rule[:120]
            if key in seen:
                continue
            seen.add(key)
            got.append('    ' + rule)
        if got:
            chunks.append('\n/* ---- from parts/%s ---- */\n' % fn)
            chunks.extend(r + '\n' for r in got)
            count += len(got)
    open(os.path.join(ROOT, '_extracted.css'), 'w').write(
        '/* PANEL BAKEOFF -- theme-aware supporting rules.  GENERATED; do not hand-edit.\n'
        '   Pulled by selector from the parts tree. @media-nested rules excluded by\n'
        '   construction: in the harness, panel width is an input, not a consequence. */\n'
        + ''.join(chunks))
    print('wrote _pm-tokens.css, _pm-primitives.css, _extracted.css (%d rules)' % count)


if __name__ == '__main__':
    main()
