import { chromium } from '/home/sittingmongoose/.npm/_npx/9833c18b2d85bc59/node_modules/playwright-core/index.mjs';
const theme = process.env.THEME || 'friendly-dark';
const out = process.env.OUT || 'shots/ob';
const browser = await chromium.launch({ executablePath: '/usr/bin/google-chrome', headless: true, args: ['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--allow-file-access-from-files'] });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
const errs=[]; page.on('pageerror', e => errs.push(e.message)); page.on('console', m=>{ if(m.type()==='error'||m.type()==='warning') errs.push(m.type()+': '+m.text().slice(0,300)); });
await page.addInitScript((t)=>{ try{ localStorage.clear(); localStorage.setItem('pm.theme', t);}catch(e){} }, theme);
await page.goto('file:///mnt/Cursor/PuppetMaster/Concepts/TestFablePMConcpet.html', { waitUntil: 'load', timeout: 60000 });
await page.waitForTimeout(2400);
const shot = async (name)=>{ await page.screenshot({ path: `${out}_${name}.png` }); };
const st = async ()=> page.evaluate(()=>({open:window.PMF_ONBOARDING.state.open, screen:window.PMF_ONBOARDING.state.screen, motion:document.getElementById('pmf-onboarding').dataset.motion}));
const click = async (sel)=>{ const ok = await page.evaluate(s=>{const el=document.querySelector(s); if(!el||el.disabled||el.getAttribute('aria-disabled')==='true') return false; el.click(); return true;}, sel); if(!ok) console.log('CLICK FAILED', sel); await page.waitForTimeout(650); return ok; };
const next = async ()=> click('#pmf-onboarding .pmf-foot .pmf-btn.is-primary');
console.log('state', JSON.stringify(await st()));
await shot('01_welcome');
await next(); console.log(JSON.stringify(await st())); await page.waitForTimeout(1200); await shot('02_where');
await next(); console.log(JSON.stringify(await st())); await shot('03_begin');
await click('#pmf-onboarding [data-group="mode"][data-arg="new"]'); await shot('03b_begin_new');
await next(); console.log(JSON.stringify(await st()));
await page.type('#pmf-name', 'Book club website', {delay: 30}); await page.waitForTimeout(400); await shot('04_name');
await next(); console.log(JSON.stringify(await st())); await shot('05_history');
await click('#pmf-onboarding [data-act="online-toggle"]'); await page.waitForTimeout(600); await shot('05b_history_online');
await click('#pmf-onboarding [data-act="host-signin"]'); await page.waitForTimeout(800); await shot('05c_signin_wait');
await page.waitForTimeout(2200); await shot('05d_signin_done');
await click('#pmf-onboarding [data-act="signin-done"]'); await page.waitForTimeout(500); await shot('05e_history_signed');
await next(); console.log(JSON.stringify(await st())); await shot('06_review');
await next(); console.log(JSON.stringify(await st())); await page.waitForTimeout(1200); await shot('07_commit_running');
await page.waitForTimeout(4200); await shot('07b_commit_done');
await next(); console.log(JSON.stringify(await st())); await page.waitForTimeout(1600); await shot('08_power');
await click('#pmf-onboarding [data-act="prov-signin"][data-arg="cursor"]'); await page.waitForTimeout(700); await shot('08b_power_signin');
await page.waitForTimeout(2200); await click('#pmf-onboarding [data-act="prov-done"]'); await page.waitForTimeout(500); await shot('08c_power_ready');
await next(); console.log(JSON.stringify(await st())); await shot('09_free');
await click('#pmf-onboarding [data-act="free-done"]'); console.log(JSON.stringify(await st())); await shot('10_done');
console.log('errors', JSON.stringify(errs.slice(0,12)));
console.log('receipts', await page.evaluate(()=>window.PMF_ONBOARDING.receipts.map(r=>r.kind+':'+r.status).join(', ')));
await browser.close();
