/* Injected test driver, NOT shipped as an application module. All mutations call
 * the actual application owners/handlers. Named faults replace actual seams. */
window.B15_CASES=(()=>{
 const C=()=>PM56_EXT.ctx(),G=PM56_GOAL,P=PM56_PLANS,T=PM56_TODOS,S=PM56_SCHED,W=PM56_ORDER_EXPORT,R=PM56_RUNTIME,D=PM56_DATA;
 const clone=x=>JSON.parse(JSON.stringify(x)),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),sleep=ms=>new Promise(r=>setTimeout(r,ms));
 const act=(a,d={})=>PM56_EXT.run(a,{dataset:d},new Event('click'));
 function seed(flow='simple'){act('b15-start',{flow});document.querySelector('[data-action="send"]').click();return W.snapshot();}
 const plan=()=>P.current(C().thread.id),goal=()=>G.get(),work=()=>W.get(W.snapshot().id);
 const build=()=>P.build({plan_id:plan().plan_id,execution_topology:'goal_driven',expected:P.admissionSnapshot(plan().plan_id)});
 function state(){G.get('query');return clone({goals:R.goals,indices:R.boundGoals,plans:P.all(),runs:P.runs(),todos:R.todos,schedules:S.list(),artifacts:D.artifacts,messages:C().thread.messages});}
 function input(key,val){const e=document.querySelector('[data-sched-input="'+key+'"]');if(!e)throw Error('missing input '+key);e.value=val;e.dispatchEvent(new Event('change',{bubbles:true}));}
 function schedule(recurring=false){const r=plan();act('pd-build-at',{id:r.plan_id});act('sched-set-build-kind',{value:recurring?'recurring_window':'one_time'});input('build-topology','goal_driven');act('sched-create-build',{planId:r.plan_id,planVersion:String(r.version)});const b=S.list().builds.find(b=>b.target_id===r.plan_id);if(!b)throw Error('schedule admission failed: '+document.querySelector('.sched-form-error')?.textContent);return b;}
 const cases={};
 cases.explicit_only=async ck=>{act('b15-start',{flow:'simple'});ck('Seeding creates no Goal, Plan, work or To-Dos',!goal()&&!plan()&&!W.snapshot()&&!T.get());const out=G.create({threadId:C().thread.id,objective:'Not requested',explicitRequest:false});ck('No implicit Goal',!out.ok&&!goal());document.querySelector('[data-action="send"]').click();ck('Ordinary Send created one simple Goal',goal()?.revision===1&&!goal().binding);ck('One shared Todo list',T.get().length===3&&work().todoIds.every(id=>T.get().some(t=>t.todo_id===id)));ck('No phases, budgets, children or Goal transcript card',!('phases'in goal())&&!('children'in goal())&&!C().thread.messages.some(m=>m.type==='goal-card'));act('goal-cancel');};
 cases.objective_authority=async ck=>{seed();act('goal-pause');const g=goal(),old=clone(g),token=G.capture(g);ck('Empty and 4001-character edits refused',!G.edit(token,'').ok&&!G.edit(token,'x'.repeat(4001)).ok);ck('Silent writer refused',!G.edit(token,'Agent secretly changed this','agent_silent').ok&&g.objective===old.objective);ck('4000 characters accepted',G.edit(token,'x'.repeat(4000)).ok&&g.revision===old.revision+1);ck('Earlier edit token is stale',!G.edit(token,'stale').ok);const direct=G.edit(G.capture(g),'Export the same supplied orders and preserve exact cents.');ck('Direct user edit advances one revision',direct.ok&&g.status==='paused');const prior=g.objective;ck('Unrequested proposal refused',!G.propose(G.capture(g),'Unrequested',{explicit:false,text:'none'}).ok);let q=G.propose(G.capture(g),'Keep the order source unchanged and export exact cents.',{explicit:true,text:'Please propose this replacement.'});ck('Proposal never changes objective before approval',q.ok&&g.objective===prior);ck('Cancel proposal preserves objective',G.deny(q.approval.id).ok&&g.objective===prior);q=G.propose(G.capture(g),'Export and independently parse the supplied CSV.',{explicit:true,text:'Please propose this replacement.'});const rev=g.revision;ck('Explicit approval commits once',G.approve(q.approval.id).ok&&g.revision===rev+1&&!G.approve(q.approval.id).ok);ck('Approval cannot resume paused work',g.status==='paused');};
 cases.approval_cas=async ck=>{seed();act('goal-pause');const g=goal();let q=G.propose(G.capture(g),'Proposal before an edit',{explicit:true,text:'Change it'});G.edit(G.capture(g),'A newer accepted edit');ck('Stale proposal refused',!G.approve(q.approval.id).ok&&g.objective==='A newer accepted edit');q=G.propose(G.capture(g),'Expired proposal',{explicit:true,text:'Change it'});R.goals.proposals[q.approval.id].expiresAt=Date.now()-1;ck('Expired proposal refuses without write',!G.approve(q.approval.id).ok&&g.objective==='A newer accepted edit');q=G.propose(G.capture(g),'Wrong project',{explicit:true,text:'Change it'});const project=C().thread.projectId;C().thread.projectId='foreign-project';ck('Project-rebound approval fails closed',!G.approve(q.approval.id).ok);C().thread.projectId=project;};
 cases.epoch_fenced=async ck=>{seed();const g=goal(),before=clone(T.get()),t=G.evaluate(g.id);ck('Evaluation alone has no work effects',same(before,T.get()));act('goal-pause');ck('Delayed pre-pause dispatch rejected',!G.dispatch(t.ticket.id).ok);await sleep(1150);ck('Timer did not mutate paused work',same(before,T.get()));const epoch=g.stopEpoch;act('goal-resume');ck('Explicit resume advances fence',g.status==='active'&&g.stopEpoch>epoch);act('goal-pause');const q=G.evaluate(g.id);act('goal-cancel');ck('Cancelled projection removed and receipt retained',!goal()&&!!G.cancellation(g.id));ck('Cancel rejects pending callback and explicit late resume',!G.dispatch(q.ticket.id).ok&&!G.lifecycle(G.capture(g),'active').ok);};
 cases.scope_and_work_fence=async ck=>{seed();const g=goal(),t=G.evaluate(g.id),a=D.artifacts.find(a=>a.id===work().source.id);a.content+=' ';ck('Source mutation after evaluation rejects dispatch',!G.dispatch(t.ticket.id).ok);ck('Source mutation cannot be completion',!W.inspect(work().id,g).complete);act('goal-pause');const tok=G.capture(g),before=clone(g),wt=C().thread.worktreeId;C().thread.worktreeId='foreign';ck('Worktree change refuses mutation',!G.edit(tok,'Wrong worktree').ok&&g.objective===before.objective);C().thread.worktreeId=wt;const alpha=C().thread.id;C().switchThread('query');ck('Cross-thread edit refused, not retargeted',!G.edit(G.capture(g),'Wrong focused thread').ok);C().switchThread(alpha);};
 cases.tickets_exactly_once=async ck=>{seed();const g=goal();const t=G.evaluate(g.id);const first=G.dispatch(t.ticket.id),before=clone(T.get()),again=G.dispatch(t.ticket.id);ck('Same accepted continuation never repeats work',first.ok&&again.replayed&&same(before,T.get()));act('goal-pause');};
 cases.outcome_rejection=async ck=>{seed();act('goal-pause');const r=work(),g=goal(),item=T.get()[0],base={todo_id:item.todo_id,expected_revision:item.revision,run_id:item.run_id,run_epoch:item.run_epoch,work_binding:r.id+':normalize:attempt1'};ck('Provider final cannot complete an unstarted Todo',!T.applyTransition(r.threadId,{...base,to_status:'completed',cause_kind:'provider_final',cause_ref:'fake'}).ok);ck('Unapproved skip refused',!T.applyTransition(r.threadId,{...base,to_status:'skipped'}).ok);ck('Wrong run cannot start work',!T.applyTransition(r.threadId,{...base,to_status:'in_progress',run_id:'foreign'}).ok);ck('No synthetic completion from all-pending list',!W.inspect(r.id,g).complete);const saved=R.todos.byThread[r.threadId].items;R.todos.byThread[r.threadId].items=saved.slice(1);ck('Deleted required item is not implicitly skipped',!W.inspect(r.id,g).eligible&&!T.outcomeSummary(r.threadId,r.todoIds).ok);R.todos.byThread[r.threadId].items=saved;};
 cases.work_effect_rollback=async ck=>{seed();act('goal-pause');const r=work(),g=goal();ck('Actual work admission accepted',W.advance(r.id,g).ok);const before=state(),orig=T.applyTransition;T.applyTransition=(...args)=>{const out=orig(...args);return out.ok?{ok:false,error:'injected_after_actual_todo_write'}:out;};const result=W.advance(r.id,g);T.applyTransition=orig;ck('Injected failure rejected committed outcome',!result.ok&&result.rollback.complete);ck('Output, evidence and actual Todo writes rolled back',same(before,state()));};
 for(const seam of ['materializeForPlan','createBound','commitRun','bindRun','invalidateForExecution'])cases['atomic_'+seam]=async ck=>{seed('plan');schedule();act('sched-close-dialog');const before=state(),owner=seam==='materializeForPlan'?T:seam==='createBound'?G:seam==='invalidateForExecution'?S:P,orig=owner[seam];owner[seam]=(...args)=>{orig(...args);return {ok:false,error:'injected_after_'+seam};};const out=build();owner[seam]=orig;ck('Actual seam failure refuses admission',!out.ok);ck('Journal reports complete rollback',out.rollback?.complete);ck('No orphan Goal, run, binding, To-Dos, schedule writes or transcript receipt',same(before,state()));await sleep(1500);ck('Rolled-back admission starts no delayed timer',same(before,state()));};
 cases.admission_preserves_intervening_source=async ck=>{seed('plan');const r=plan(),beforeTodo=clone(T.get()),orig=P.commitRun;P.commitRun=(...args)=>{const x=orig(...args);r.revisions[r.version].push({t:'paragraph',text:'Newer source written during admission'});return x;};const out=build();P.commitRun=orig;ck('Mid-admission source change refuses atomic build',!out.ok);ck('Newer source is preserved',P.markdown(r.plan_id).includes('Newer source written during admission'));ck('No Goal/run/To-Dos leak',!goal()&&Object.keys(P.runs()).length===0&&same(beforeTodo,T.get())&&r.status==='ready');};
 cases.bound_lifecycle=async ck=>{seed('plan');const r=plan(),doc=P.markdown(r.plan_id),out=build(),g=goal(),items=T.get(),run=P.runs()[out.plan_run_id];ck('All three exact bindings committed',out.ok&&g.binding===r.goalBinding&&g.binding.plan_run_id===run.plan_run_id);ck('Shared identities not copied',g.binding.todo_list_ref==='todos:'+r.thread_id&&r.requiredTodoIds.every(id=>items.some(t=>t.todo_id===id)));ck('Regular backend unchanged',r.backend==='direct'&&!r.ledger&&!r.planunits&&!r.unitsMaterialized);const again=build();ck('Duplicate returns original Goal/run',again.replayed&&again.goal_id===g.id&&Object.keys(P.runs()).length===1&&T.get().length===3);act('goal-pause');ck('Pause keeps Building and an exact secondary reason',r.status==='building'&&r.attention.kind==='paused'&&g.status==='paused');act('goal-resume');ck('Resume continues same run',g.status==='active'&&r.approved.plan_run_id===out.plan_run_id);act('goal-pause');G.edit(G.capture(g),'A material change: do not export this Plan.');ck('Goal edit does not rewrite approved Plan',P.markdown(r.plan_id)===doc&&r.status==='building'&&g.status==='blocked'&&r.attention.reason.includes('mismatch'));ck('Conflict blocks resume',!G.lifecycle(G.capture(g),'active').ok);act('pd-cancel',{id:r.plan_id});ck('Plan cancel also removes bound Goal and cancels run',r.status==='canceled'&&!goal()&&run.state==='canceled');};
 cases.preconditions=async ck=>{seed('plan');const r=plan(),ex=P.admissionSnapshot(r.plan_id);ck('Wrong version refused',!P.build({plan_id:r.plan_id,execution_topology:'goal_driven',expected:{...ex,version:99}}).ok);ck('Wrong hash refused',!P.build({plan_id:r.plan_id,execution_topology:'goal_driven',expected:{...ex,hash:'changed'}}).ok);ck('Wrong project refused',!P.build({plan_id:r.plan_id,execution_topology:'goal_driven',expected:{...ex,project_id:'foreign'}}).ok);ck('Wrong worktree refused',!P.build({plan_id:r.plan_id,execution_topology:'goal_driven',expected:{...ex,worktree:'foreign'}}).ok);ck('Wrong permissions refused',!P.build({plan_id:r.plan_id,execution_topology:'goal_driven',expected:{...ex,permissions:'foreign'}}).ok);const m=D.models.find(m=>m.id===ex.route.modelId),status=m.status;m.status='sign-in-required';ck('Unavailable frozen provider fails closed',!build().ok);m.status=status;ck('Refusals leave no Goal or Todo',!goal()&&!T.get());};
 cases.scheduled_admission=async ck=>{seed('scheduled');const r=plan(),b=schedule(),due=Date.parse(b.scheduled_at_utc);ck('Schedule commits goal topology without a Goal/run/Todos',b.execution_topology==='goal_driven'&&!goal()&&!T.get()&&!r.approved&&!b.runtime_created);ck('Early timer refused',!S.dispatchBuildAt(b.schedule_id,due-1,b.revision,b.user_stop_epoch).ok);const o=S.dispatchBuildAt(b.schedule_id,due,b.revision,b.user_stop_epoch);ck('Admitted dispatch creates exactly one bound Goal/run',o.ok&&b.runtime_created&&!!goal()&&b.goal_id===goal().id&&r.approved.plan_run_id===b.plan_run_id);const again=S.dispatchBuildAt(b.schedule_id,due);ck('Duplicate timer returns same identities',again.ok&&again.duplicate&&again.receipt.goal_id===o.receipt.goal_id&&Object.keys(P.runs()).length===1);act('goal-cancel');};
 cases.scheduled_stop_epoch=async ck=>{seed('scheduled');const b=schedule(),old=b.user_stop_epoch,due=Date.parse(b.scheduled_at_utc);S.latchStop('Test explicit stop between evaluation and dispatch');ck('Stopped schedule cannot admit a Goal',!S.dispatchBuildAt(b.schedule_id,due,b.revision,old).ok&&!goal());act('sched-clear-stop');ck('Old evaluated delivery stays fenced after explicit resume',!S.dispatchBuildAt(b.schedule_id,due,b.revision,old).ok&&!goal());ck('Fresh explicit schedule epoch can admit',S.dispatchBuildAt(b.schedule_id,due,b.revision,b.user_stop_epoch).ok&&!!goal());act('goal-cancel');};
 cases.scheduled_outer_rollback=async ck=>{seed('scheduled');const b=schedule(),before=state(),orig=P.admitScheduled;P.admitScheduled=(...a)=>{const x=orig(...a);return x.ok?{ok:false,error:'injected_after_actual_nested_admission'}:x;};const out=S.dispatchBuildAt(b.schedule_id,Date.parse(b.scheduled_at_utc),b.revision,b.user_stop_epoch);P.admitScheduled=orig;ck('Outer dispatch failure rolls back nested admission',!out.ok&&out.rollback.complete&&same(before,state()));await sleep(1500);ck('No delayed dispatch side effects survive rollback',same(before,state()));};
 cases.immediate_invalidates_only_target=async ck=>{seed('scheduled');const r=plan(),b=schedule(),messages=clone(S.list().messages),other=clone(S.list().builds.filter(x=>x!==b)),out=build();ck('Immediate Build invalidates pending exact-version schedule',out.ok&&b.state==='invalidated');ck('Unrelated schedules/messages unchanged',same(messages,S.list().messages)&&same(other,S.list().builds.filter(x=>x!==b)));ck('Invalidated timer cannot create second Goal',!S.dispatchBuildAt(b.schedule_id,Date.parse(b.scheduled_at_utc),b.revision,b.user_stop_epoch).ok&&Object.keys(P.runs()).length===1);act('goal-cancel');};
 cases.recurring_reuses_run=async ck=>{seed('scheduled');const r=plan(),b=schedule(true);const o=S.dispatchBuildAt(b.schedule_id,Date.parse(b.next_occurrence_at),b.revision,b.user_stop_epoch);ck('Recurring first occurrence admitted',o.ok&&b.state==='active');const id=b.plan_run_id;act('sched-advance-window',{id:b.schedule_id});ck('Window closes at shared safe pause',r.status==='building'&&r.attention?.kind==='paused');act('sched-advance-window',{id:b.schedule_id});ck('Next window resumes same run and Goal',r.status==='building'&&!r.attention&&b.plan_run_id===id&&Object.keys(P.runs()).length===1);act('goal-pause');act('sched-advance-window',{id:b.schedule_id});ck('Window cannot resume manually paused Goal',goal().status==='paused');act('goal-cancel');};
 cases.restore_branch=async ck=>{seed();act('goal-pause');G.edit(G.capture(goal()),'A saved accepted objective');const original=clone(goal()),tid=C().thread.id;act('create-restore-point',{id:tid});const card=C().thread.messages.find(m=>m.type==='threadops-restore-point');ck('Actual restore point exists',!!card);G.edit(G.capture(goal()),'A later accepted objective');act('branch-from-restore',{value:card.restorePointId});const g=goal();ck('Actual branch preserves snapshot accepted revision',g&&g.objective===original.objective&&g.revision===original.revision&&g.thread!==tid&&g.projectId===original.projectId);ck('Branch cannot reuse a live execution controller',g.status==='paused'&&!g.activeRunRef&&!g.workRef&&g.lineage.live_controller_reused===false);ck('Source thread retains later objective',G.get(tid).objective==='A later accepted objective');};

 cases.unsupported_objective=async ck=>{seed();act('goal-pause');const g=goal(),original=g.objective,before=clone(T.get());G.edit(G.capture(g),'Email every customer and delete the original input.');act('goal-resume');ck('Unrelated objective is saved but cannot run the old adapter',g.objective.startsWith('Email')&&g.status==='blocked');await sleep(1100);ck('Unsupported rewrite produced no work',same(before,T.get()));G.edit(G.capture(g),original);act('goal-resume');ck('Owner-cleared objective can explicitly resume',g.status==='active');act('goal-cancel');};
 cases.completion_currentness=async ck=>{seed();act('goal-pause');const g=goal(),r=work();for(let i=0;i<6;i++)ck('Actual source-bound step '+i,W.advance(r.id,g).ok);ck('All outcomes computed but paused Goal not completed',W.inspect(r.id,g).complete&&g.status==='paused');act('goal-resume');const e=G.evaluate(g.id),proof=D.artifacts.find(a=>a.id===r.evidence.verify),raw=proof.content;proof.content+=' ';ck('Even whitespace evidence mutation fences an evaluated completion',!G.dispatch(e.ticket.id).ok&&g.status==='active');proof.content=raw;const e2=G.evaluate(g.id),out=G.dispatch(e2.ticket.id),before=clone(state());ck('Current evidence permits exactly one completion',out.ok&&g.status==='completed'&&g.completion.evidenceRefs.length===3);const replay=G.dispatch(e2.ticket.id);ck('Completion replay has no repeated effects',replay.replayed&&same(before,state()));};
 cases.normal_branch=async ck=>{seed();act('goal-pause');const g=clone(goal()),tid=C().thread.id,anchor=C().thread.messages[0].id;act('branch-from-message',{value:anchor});const x=goal();ck('Ordinary branch preserves project and accepted objective',x&&x.projectId===g.projectId&&x.objective===g.objective&&x.revision===g.revision);ck('Branch identity is new and never borrows controller',x.id!==g.id&&x.thread!==tid&&!x.activeRunRef&&!x.workRef&&x.status==='paused');};
 cases.rewind_restore=async ck=>{seed();const g=goal(),t=G.evaluate(g.id),rev=g.revision,text=g.objective,tid=C().thread.id;act('rewind-to-message',{value:C().thread.messages[0].id});const rw=PM56_THREADOPS.rewinds(tid).slice(-1)[0];ck('Rewind preserves accepted objective but pauses live controller',rw&&g.status==='paused'&&g.objective===text&&g.revision===rev);ck('Pre-rewind callback cannot write',!G.dispatch(t.ticket.id).ok);const e=g.stopEpoch;act('restore-rewind',{value:rw.id});ck('Restore unfolds history without resurrecting automation',g.status==='paused'&&g.stopEpoch>e&&g.objective===text&&g.revision===rev&&rw.restored);};
 cases.quota_resume=async ck=>{seed();const g=goal();R.quota.waiting=true;R.quota.resumeAutomatically=true;R.quota.resetSource='provider reported';const consent=S.bindGoalQuotaConsent(true);G.kick(g.id);ck('Quota wait does not change Goal lifecycle',g.status==='active'&&!!consent.goal_token);const first=S.simulateQuotaReset();ck('Matching shared consent admits continuation without new Goal',first.ok&&first.goal_outcomes[0].ok&&goal()===g);act('goal-pause');const before=clone(T.get());R.quota.waiting=true;const old=S.simulateQuotaReset();ck('Quota reset cannot undo a manual pause',!old.ok&&g.status==='paused');await sleep(1150);ck('Late quota delivery produces no side effects',same(before,T.get()));};
 cases.bound_quota_resume=async ck=>{seed('plan');build();const g=goal(),r=plan();R.quota.waiting=true;R.quota.resumeAutomatically=true;R.quota.resetSource='provider reported';S.bindGoalQuotaConsent(true);await sleep(1700);ck('Bound Goal stays active while Plan remains Building',g.status==='active'&&r.status==='building');const result=S.simulateQuotaReset();ck('Quota owner resumes exact run',result.ok&&result.goal_outcomes[0].ok&&r.status==='building'&&!r.attention);act('goal-cancel');};
 cases.bound_recovery_and_revise=async ck=>{seed('plan');build();const g=goal(),r=plan(),before=clone(T.get());act('goal-pause');ck('Plan owner resume cannot bypass Goal pause',P.boundResume(r.plan_id).resumed===false&&g.status==='paused');r.attention.actions.push('reconnect');act('pd-attn',{id:r.plan_id,value:'reconnect'});ck('Reconnect cannot clear Goal stop',g.status==='paused');G.edit(G.capture(g),'A material change, requiring review of the exact Plan.');const hash=P.hash(r.plan_id);act('goal-revise-plan',{id:r.plan_id});ck('Goal conflict opens the ordinary Revise route',R.composer.destination?.kind==='plan-revision'&&R.composer.destination.refId===r.plan_id&&r.status==='ready');ck('Revise routing preserves approved source and stopped To-Dos',P.hash(r.plan_id)===hash&&same(before,T.get())&&g.status!=='active');};
 cases.restored_owner_no_fallback=async ck=>{seed('plan');build();const r=plan(),before=clone(T.get());G.restore();ck('Missing restored Goal refuses a direct Plan resume',P.boundResume(r.plan_id).resumed===false);await sleep(1600);ck('Missing Goal cannot fall back into an agent loop',same(before,T.get())&&r.status==='building'&&r.attention);};
 cases.replay_wrong_scope=async ck=>{seed('plan');const out=build(),r=plan(),ex=P.admissionSnapshot(r.plan_id);ck('An idempotency replay cannot be retargeted across project',!P.build({plan_id:r.plan_id,execution_topology:'goal_driven',expected:{...ex,project_id:'foreign'}}).ok);ck('Original replay returns original admission',build().replayed&&P.runs()[out.plan_run_id]);act('goal-cancel');};
 cases.intervening_scope=async ck=>{seed('plan');const orig=P.commitRun,wt=C().thread.worktreeId;P.commitRun=(...args)=>{const out=orig(...args);C().thread.worktreeId='newer-worktree';return out;};const out=build();P.commitRun=orig;ck('A changed worktree during admission fails closed',!out.ok&&!goal()&&!T.get()&&!Object.keys(P.runs()).length);ck('Newer worktree selection is not rolled back',C().thread.worktreeId==='newer-worktree');};
 cases.transaction_conflict=async ck=>{seed();act('goal-pause');const r=work(),g=goal();W.advance(r.id,g);const orig=T.applyTransition;T.applyTransition=(...args)=>{const out=orig(...args);D.artifacts.push({id:'newer-unrelated-artifact',content:'preserve this independent write'});return {ok:false,error:'injected_after_newer_write'};};const out=W.advance(r.id,g);T.applyTransition=orig;ck('Rollback removes only its own appended artifacts, preserving an intervening unrelated write',!out.ok&&out.rollback.complete&&D.artifacts.some(a=>a.id==='newer-unrelated-artifact')&&!D.artifacts.some(a=>a.id===r.id+'-normalize'));ck('No success or completed To-Do is reported',T.get()[0].status==='in_progress'&&!r.outputs.normalize);};

 cases.transaction_newer_same_record=async ck=>{seed();act('goal-pause');const r=work(),g=goal();W.advance(r.id,g);const orig=T.applyTransition;T.applyTransition=(...args)=>{orig(...args);D.artifacts.find(a=>a.id===r.id+'-normalize').content='newer independent edit';return {ok:false,error:'injected_after_newer_same_record_write'};};const out=W.advance(r.id,g);T.applyTransition=orig;ck('A newer same-record edit survives and is an explicit rollback conflict',!out.ok&&!out.rollback.complete&&out.rollback.conflicts.some(k=>k.includes(r.id+'-normalize'))&&D.artifacts.find(a=>a.id===r.id+'-normalize').content==='newer independent edit');ck('Partial rollback never claims completion',!r.outputs.normalize&&T.get()[0].status==='in_progress');};
 return cases;
})();
