
  /* =====================================================================
     changes[] -- 3 records with no diff content at all -> 12 files with
     real unified-diff hunks.

     Compact authoring form: rows are ['+'|'-'|' '|'\\', text]. The helper
     assigns the 1-based old/new line numbers and derives the @@ header, so
     no renderer ever computes a line number -- computing them in JS is
     exactly what produced the fabricated 18-line CREATE INDEX diff this
     replaces (app.js:424-427 printed the same SQL for every path clicked).

     `add`/`del` are DERIVED from the hunks by countChange() below, so the
     totals can never drift from the diff content the way the old literals
     did. Three files reproduce the correction packet's manifest counts
     exactly: provider-selector.js +92/−18, access-controls.css +61/−39,
     interaction-probes.mjs +31/−10.
     ===================================================================== */
  function hunk(oldStart, newStart, rows) {
    let o = oldStart, n = newStart, oldLines = 0, newLines = 0;
    const lines = rows.map((r) => {
      const sign = r[0], txt = r[1];
      if (sign === '+') { newLines++; return { kind:'add', old:null, new:n++, text:txt }; }
      if (sign === '-') { oldLines++; return { kind:'del', old:o++, new:null, text:txt }; }
      if (sign === '\\') { return { kind:'meta', old:null, new:null, text:txt }; }
      oldLines++; newLines++; return { kind:'ctx', old:o++, new:n++, text:txt };
    });
    return { header:`@@ -${oldStart},${oldLines} +${newStart},${newLines} @@`, oldStart, oldLines, newStart, newLines, lines };
  }
  function countChange(c) {
    let add = 0, del = 0;
    for (const h of c.hunks) for (const l of h.lines) { if (l.kind === 'add') add++; else if (l.kind === 'del') del++; }
    c.add = add; c.del = del;
    c.lineCount = c.hunks.reduce((s, h) => s + h.lines.length, 0);
    return c;
  }

  const changes = [
    countChange({ id:'c1', path:'migrations/0043_tenant_created_index.sql', line:1,
      summary:'Add the tenant_id + created_at composite index as a concurrent, non-transactional migration',
      status:'added', oldPath:null, language:'sql', threadId:'query',
      hunks:[ hunk(0, 1, [
        ['+','-- 0043_tenant_created_index'],
        ['+','-- Leading column is tenant_id: every analytics read is tenant-scoped,'],
        ['+','-- and created_at carries the range predicate plus the ORDER BY.'],
        ['+','--'],
        ['+','-- CONCURRENTLY cannot run inside a transaction block, so this file is'],
        ['+','-- split out of the batch migration and applied on its own.'],
        ['+','-- no-transaction'],
        ['+',''],
        ['+','CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_events_tenant_created'],
        ['+','    ON analytics_events (tenant_id, created_at DESC)'],
        ['+','    INCLUDE (event_kind, actor_id);'],
        ['+',''],
        ['+','ANALYZE analytics_events;'],
        ['+',''],
        ['+','-- rollback:'],
        ['+','--   DROP INDEX CONCURRENTLY IF EXISTS idx_events_tenant_created;'],
        ['+','-- The rollback is rehearsed in tests/analytics_query_test.rs so the'],
        ['+','-- forward migration is never the only tested direction.']
      ]) ] }),

    countChange({ id:'c2', path:'src/analytics/queries.rs', line:128,
      summary:'Replace the per-row event lookup with one batched, tenant-first query',
      status:'modified', oldPath:null, language:'rust', threadId:'query',
      hunks:[
        hunk(122, 122, [
          [' ','use crate::analytics::schema::{EventKind, TenantScope};'],
          ['-','use crate::db::Row;'],
          ['+','use crate::analytics::index_hints::IndexHint;'],
          ['+','use crate::db::{Row, RowBatch};'],
          [' ',''],
          [' ','impl AnalyticsQueries {'],
          ['-','    /// Loads events one tenant at a time. O(n) round trips.'],
          ['-','    pub async fn events_for(&self, scope: &TenantScope) -> Result<Vec<Row>> {'],
          ['-','        let mut out = Vec::new();'],
          ['-','        for tenant in scope.tenants() {'],
          ['-','            out.extend(self.one_tenant(tenant).await?);'],
          ['+','    /// Loads every tenant in one round trip. The index hint keeps the'],
          ['+','    /// planner on idx_events_tenant_created even when the range is wide.'],
          ['+','    pub async fn events_for(&self, scope: &TenantScope) -> Result<RowBatch> {'],
          ['+','        let hint = IndexHint::tenant_created();'],
          ['+','        let batch = self'],
          ['+','            .pool'],
          ['+','            .fetch_batch(hint.apply(EVENTS_BY_TENANT), scope.tenant_ids())'],
          ['+','            .await?;'],
          [' ','        }'],
          [' ','        Ok(out)'],
          [' ','    }']
        ]),
        hunk(196, 199, [
          [' ','const EVENTS_BY_TENANT: &str = r#"'],
          ['-','    SELECT * FROM analytics_events'],
          ['-','     WHERE tenant_id = $1'],
          ['-','     ORDER BY created_at DESC'],
          ['+','    SELECT event_kind, actor_id, created_at, payload'],
          ['+','      FROM analytics_events'],
          ['+','     WHERE tenant_id = ANY($1)'],
          ['+','       AND created_at >= $2'],
          ['+','     ORDER BY tenant_id, created_at DESC'],
          ['+','     LIMIT $3'],
          [' ','"#;'],
          [' ',''],
          ['+','/// Batch size chosen so one page of the composite index is one read.'],
          ['+','pub const EVENT_PAGE: i64 = 512;'],
          ['+',''],
          ['+','#[cfg(test)]'],
          ['+','mod planner_guard {'],
          ['+','    use super::*;'],
          ['+',''],
          ['+','    /// Fails loudly if the planner stops choosing the composite index,'],
          ['+','    /// which is the only way this change silently regresses.'],
          ['+','    #[tokio::test]'],
          ['+','    async fn uses_composite_index() {'],
          ['+','        let plan = explain(EVENTS_BY_TENANT).await;'],
          ['+','        assert!(plan.contains("idx_events_tenant_created"), "{plan}");'],
          ['+','    }'],
          ['+','}'],
          [' ','']
        ])
      ] }),

    countChange({ id:'c3', path:'src/analytics/bench.rs', line:44,
      summary:'Add the tenant-scale benchmark fixture and record the write-amplification cost',
      status:'modified', oldPath:null, language:'rust', threadId:'query',
      hunks:[ hunk(41, 41, [
        [' ','use criterion::{criterion_group, Criterion};'],
        ['-','const TENANTS: usize = 8;'],
        ['-','const EVENTS_PER_TENANT: usize = 400;'],
        ['-',''],
        ['+','/// 128,400 rows across 214 tenants -- the shape production actually has.'],
        ['+','/// The old 8x400 fixture was small enough that a sequential scan won,'],
        ['+','/// which is why the previous benchmark showed no gain from the index.'],
        ['+','const TENANTS: usize = 214;'],
        ['+','const EVENTS_PER_TENANT: usize = 600;'],
        ['+',''],
        ['+','fn write_amplification(c: &mut Criterion) {'],
        ['+','    c.bench_function("insert_with_composite_index", |b| {'],
        ['+','        b.iter(|| insert_batch(EVENTS_PER_TENANT));'],
        ['+','    });'],
        ['+','}'],
        ['+',''],
        [' ','fn read_path(c: &mut Criterion) {'],
        ['+','    let fixture = seed(TENANTS, EVENTS_PER_TENANT);'],
        ['+','    c.bench_function("events_for_tenant_page", |b| {'],
        ['+','        b.iter(|| fixture.events_for(&scope()));'],
        ['+','    });'],
        [' ','}'],
        [' ',''],
        ['+','criterion_group!(benches, read_path, write_amplification);'],
        ['+','// Baseline p95 482 ms -> 71 ms read; writes +4.8%.'],
        [' ','']
      ]) ] }),

    /* Manifest file 1 of 3: +92 / −18, three hunks, 110 changed lines --
       the file that makes the editor scroll. */
    countChange({ id:'c4', path:'threads/provider-selector.js', line:64,
      summary:'Route the selector through configured accounts instead of one account per provider',
      status:'modified', oldPath:null, language:'javascript', threadId:'route',
      hunks:[
        hunk(58, 58, [
          [' ','import { configuredProviders } from \'../providers/registry.js\';'],
          ['-','import { firstAccount } from \'../providers/accounts.js\';'],
          ['+','import { accountsFor, accountState } from \'../providers/accounts.js\';'],
          ['+','import { STATUS_LABEL } from \'../providers/labels.js\';'],
          [' ',''],
          ['-','// One provider used to mean one account, so the selector could key its'],
          ['-','// rows on the provider id -- an assumption that is now wrong.'],
          ['-','export function providerRows() {'],
          ['-','  return configuredProviders().map((p) => ({'],
          ['-','    id: p.id,'],
          ['-','    account: firstAccount(p.id),'],
          ['+','// A provider can expose the same model through several configured'],
          ['+','// accounts, so rows are keyed on `${providerId}:${accountId}` and the'],
          ['+','// model name alone is no longer unique inside the list.'],
          ['+','export function providerRows() {'],
          ['+','  return configuredProviders().flatMap((p) => accountsFor(p.id).map((a) => ({'],
          ['+','    id: `${p.id}:${a.id}`,'],
          ['+','    providerId: p.id,'],
          ['+','    account: a,'],
          ['+','    state: accountState(a),'],
          [' ','  }));'],
          [' ','}']
        ]),
        hunk(96, 100, [
          [' ','export function renderSelector(host, state) {'],
          ['-','  const rows = providerRows();'],
          ['-','  host.innerHTML = rows.map((r) => row(r, r.id === state.provider)).join(\'\');'],
          ['+','  const rows = providerRows();'],
          ['+','  const grouped = groupByProvider(rows);'],
          ['+','  host.innerHTML = grouped'],
          ['+','    .map(([providerId, items]) => section(providerId, items, state))'],
          ['+','    .join(\'\');'],
          ['+','  host.dataset.accountCount = String(rows.length);'],
          ['+','  host.dataset.needsAttention = String(rows.filter(needsAttention).length);'],
          [' ','}'],
          [' ',''],
          ['-','function row(r, active) {'],
          ['-','  return `<button class="row ${active ? \'active\' : \'\'}" data-id="${r.id}">'],
          ['-','    <span class="name">${r.id}</span>'],
          ['-','    <span class="account">${r.account.label}</span>'],
          ['-','  </button>`;'],
          ['-','}'],
          ['+','function groupByProvider(rows) {'],
          ['+','  const map = new Map();'],
          ['+','  for (const r of rows) {'],
          ['+','    if (!map.has(r.providerId)) map.set(r.providerId, []);'],
          ['+','    map.get(r.providerId).push(r);'],
          ['+','  }'],
          ['+','  return [...map.entries()];'],
          ['+','}'],
          ['+',''],
          ['+','function section(providerId, items, state) {'],
          ['+','  const attention = items.filter(needsAttention).length;'],
          ['+','  return ['],
          ['+','    `<div class="provider-group" data-provider="${providerId}">`,'],
          ['+','    `  <div class="group-head">`,'],
          ['+','    `    <span class="group-name">${providerId}</span>`,'],
          ['+','    `    <span class="group-count">${items.length} accounts</span>`,'],
          ['+','    attention ? `    <span class="group-warn">${attention} need attention</span>` : \'\','],
          ['+','    `  </div>`,'],
          ['+','    items.map((r) => row(r, r.id === state.route)).join(\'\'),'],
          ['+','    `</div>`,'],
          ['+','  ].filter(Boolean).join(\'\\n\');'],
          ['+','}'],
          ['+',''],
          ['+','function row(r, active) {'],
          ['+','  const blocked = needsAttention(r);'],
          ['+','  return ['],
          ['+','    `<button class="row ${active ? \'active\' : \'\'} ${blocked ? \'blocked\' : \'\'}"`,'],
          ['+','    `        data-id="${r.id}" ${blocked ? \'aria-disabled="true"\' : \'\'}>`,'],
          ['+','    `  <span class="name">${r.account.model}</span>`,'],
          ['+','    `  <span class="account">${r.account.label}</span>`,'],
          ['+','    `  <span class="state">${STATUS_LABEL[r.state] ?? r.state}</span>`,'],
          ['+','    `</button>`,'],
          ['+','  ].join(\'\\n\');'],
          ['+','}'],
          ['+',''],
          ['+','function needsAttention(r) {'],
          ['+','  return r.state !== \'ready\' && r.state !== \'update-available\';'],
          ['+','}'],
          [' ','']
        ]),
        hunk(168, 200, [
          [' ','export function selectRoute(host, id) {'],
          ['-','  host.dataset.provider = id;'],
          ['-','  emit(host, \'route\', { provider: id });'],
          ['-','}'],
          ['+','  const [providerId, accountId] = id.split(\':\');'],
          ['+','  const row = providerRows().find((r) => r.id === id);'],
          ['+','  if (!row) return false;'],
          ['+','  if (needsAttention(row)) {'],
          ['+','    // Do not silently fall back to another account: the user picked a'],
          ['+','    // specific one, and a quiet substitution is how a thread ends up'],
          ['+','    // billed to an account nobody chose.'],
          ['+','    emit(host, \'route-blocked\', { providerId, accountId, state: row.state });'],
          ['+','    return false;'],
          ['+','  }'],
          ['+','  host.dataset.provider = providerId;'],
          ['+','  host.dataset.account = accountId;'],
          ['+','  host.dataset.route = id;'],
          ['+','  emit(host, \'route\', { providerId, accountId, model: row.account.model });'],
          ['+','  return true;'],
          ['+','}'],
          ['+',''],
          ['+','export function routeLabel(id) {'],
          ['+','  const row = providerRows().find((r) => r.id === id);'],
          ['+','  if (!row) return \'No configured route\';'],
          ['+','  return `${row.account.model} · ${row.account.label}`;'],
          ['+','}'],
          ['+',''],
          ['+','// Two accounts on the same provider can expose the same model, so the'],
          ['+','// thread has to record which one it actually ran on. Reading it back'],
          ['+','// off the model name would silently merge them.'],
          ['+','export function routeState(host) {'],
          ['+','  const id = host.dataset.route;'],
          ['+','  const row = id && providerRows().find((r) => r.id === id);'],
          ['+','  if (!row) {'],
          ['+','    return { ok: false, reason: \'no-configured-route\', label: routeLabel(id) };'],
          ['+','  }'],
          ['+','  const ok = !needsAttention(row);'],
          ['+','  return { ok, reason: row.state, providerId: row.providerId,'],
          ['+','           accountId: row.account.id, label: routeLabel(id) };'],
          ['+','}'],
          [' ','']
        ])
      ] }),

    /* Manifest file 2 of 3: +61 / −39, two hunks. */
    countChange({ id:'c5', path:'threads/access-controls.css', line:12,
      summary:'Replace the colour-only permission accent with a token set that survives all eight themes',
      status:'modified', oldPath:null, language:'css', threadId:'route',
      hunks:[
        hunk(12, 12, [
          [' ','.access-row {'],
          ['-','  border-left: 3px solid #4c8dff;'],
          ['-','  padding: 6px 8px 6px 11px;'],
          ['-','  background: rgba(76, 141, 255, 0.08);'],
          ['-','  color: #e8ecf6;'],
          ['-','}'],
          ['-',''],
          ['-','.access-row.denied { border-left-color: #ff5c5c; }'],
          ['-','.access-row.pending { border-left-color: #ffb648; }'],
          ['-','.access-row.granted { border-left-color: #37d67a; }'],
          ['-',''],
          ['-','.access-row .label { font-size: 11px; opacity: 0.7; }'],
          ['-','.access-row .value { font-size: 12px; }'],
          ['+','  /* A coloured left-edge bar may not carry status: it is invisible to'],
          ['+','     anyone who cannot separate the hues, and it collides with the'],
          ['+','     selection accent. Status is an icon plus a word plus a tone. */'],
          ['+','  display: grid;'],
          ['+','  grid-template-columns: 18px minmax(0, 1fr) auto;'],
          ['+','  align-items: center;'],
          ['+','  gap: 8px;'],
          ['+','  padding: 6px 9px;'],
          ['+','  border: 1px solid var(--border);'],
          ['+','  border-radius: var(--radius-sm);'],
          ['+','  background: var(--surface-raised);'],
          ['+','  color: var(--text);'],
          ['+','}'],
          ['+',''],
          ['+','.access-row > .access-icon {'],
          ['+','  display: grid;'],
          ['+','  place-items: center;'],
          ['+','  inline-size: 18px;'],
          ['+','  block-size: 18px;'],
          ['+','  color: var(--muted);'],
          ['+','}'],
          ['+',''],
          ['+','.access-row.denied  > .access-icon { color: var(--danger); }'],
          ['+','.access-row.pending > .access-icon { color: var(--warning); }'],
          ['+','.access-row.granted > .access-icon { color: var(--positive); }'],
          ['+',''],
          ['+','.access-row .label { font-size: 11px; color: var(--muted); }'],
          ['+','.access-row .value { font-size: 12px; color: var(--text); }'],
          ['+','.access-row .state { font-size: 10px; color: var(--subtle); }'],
          [' ','']
        ]),
        hunk(58, 80, [
          [' ','.access-panel {'],
          ['-','  max-height: 320px;'],
          ['-','  overflow: hidden;'],
          ['-','}'],
          ['-',''],
          ['-','@media (prefers-color-scheme: light) {'],
          ['-','  .access-row { background: rgba(76, 141, 255, 0.06); color: #14181f; }'],
          ['-','  .access-row .label { opacity: 0.6; }'],
          ['-','}'],
          ['-',''],
          ['-','@media (max-width: 700px) {'],
          ['-','  .access-row { border-left-width: 2px; }'],
          ['-','  .access-panel { max-height: 200px; }'],
          ['-','}'],
          ['-',''],
          ['-','.access-row:hover { background: rgba(76, 141, 255, 0.16); }'],
          ['-','.access-row:focus-visible { outline: 2px solid #4c8dff; }'],
          ['-','.access-row[aria-disabled=\'true\'] { opacity: 0.4; }'],
          ['-',''],
          ['-','.access-row .chip { border-radius: 3px; padding: 1px 4px; }'],
          ['-','.access-row .chip.danger { background: #ff5c5c; }'],
          ['-','.access-row .chip.warn { background: #ffb648; }'],
          ['-','.access-row .chip.ok { background: #37d67a; }'],
          ['-',''],
          ['-','.access-note { font-size: 10px; color: #8a93a6; }'],
          ['-',''],
          ['-','.access-panel::-webkit-scrollbar { width: 6px; }'],
          ['-','.access-panel::-webkit-scrollbar-thumb { background: #4c8dff; }'],
          ['+','  max-height: min(320px, 100vh - 24px);'],
          ['+','  overflow: auto;'],
          ['+','  overscroll-behavior: contain;'],
          ['+','  scrollbar-gutter: stable;'],
          ['+','}'],
          ['+',''],
          ['+','/* Theme handling moved to tokens: the eight themes are explicit'],
          ['+','   attribute states, not a light/dark media query, so this block was'],
          ['+','   only ever correct in two of them. */'],
          ['+','.access-row:hover { background: var(--surface-hover); }'],
          ['+','.access-row:focus-visible { outline: 2px solid var(--accent); outline-offset: 1px; }'],
          ['+','.access-row[aria-disabled=\'true\'] { opacity: 0.55; cursor: not-allowed; }'],
          ['+','.access-row[aria-disabled=\'true\'] .state { color: var(--danger); }'],
          ['+',''],
          ['+','.access-row .chip {'],
          ['+','  padding: 1px 5px; font-size: 9px; border-radius: var(--radius-sm);'],
          ['+','  border: 1px solid var(--border); background: var(--surface);'],
          ['+','}'],
          ['+','.access-row .chip.danger { border-color: var(--danger); color: var(--danger); }'],
          ['+','.access-row .chip.warn   { border-color: var(--warning); color: var(--warning); }'],
          ['+','.access-row .chip.ok     { border-color: var(--positive); color: var(--positive); }'],
          ['+',''],
          ['+','.access-note { font-size: 10px; color: var(--subtle); }'],
          ['+',''],
          ['+','@media (max-width: 700px) {'],
          ['+','  .access-row { grid-template-columns: 18px minmax(0, 1fr); }'],
          ['+','  .access-row .state { grid-column: 2; }'],
          ['+','}'],
          ['+',''],
          ['+','@media (prefers-reduced-motion: reduce) {'],
          ['+','  .access-row { transition: none; }'],
          ['+','}'],
          [' ','']
        ])
      ] }),

    /* Manifest file 3 of 3: +31 / −10, two hunks. */
    countChange({ id:'c6', path:'verification/interaction-probes.mjs', line:22,
      summary:'Assert painted pixels instead of bounding boxes in the interaction probes',
      status:'modified', oldPath:null, language:'javascript', threadId:'debug',
      hunks:[
        hunk(22, 22, [
          [' ','export async function probeVisible(page, selector) {'],
          ['-','  // TODO: this does not prove the element is actually painted.'],
          ['-','  const box = await page.locator(selector).boundingBox();'],
          ['-','  return Boolean(box && box.width > 0 && box.height > 0);'],
          ['-','}'],
          ['+','  // A bounding box is reported for elements that are clipped, occluded,'],
          ['+','  // or mid-transition -- which is how three "fixes" passed while invisible.'],
          ['+','  const box = await page.locator(selector).boundingBox();'],
          ['+','  if (!box || box.width <= 0 || box.height <= 0) return false;'],
          ['+','  const [cx, cy] = [box.x + box.width / 2, box.y + box.height / 2];'],
          ['+','  const onTop = await page.evaluate('],
          ['+','    ([x, y, sel]) => document.elementFromPoint(x, y)?.closest(sel) !== null,'],
          ['+','    [cx, cy, selector],'],
          ['+','  );'],
          ['+','  // Distinct colours, not mean luminance: a placeholder box has exactly one.'],
          ['+','  return onTop && distinctColours(await page.screenshot({ clip: box })) > 3;'],
          ['+','}'],
          [' ','']
        ]),
        hunk(70, 91, [
          [' ','export async function probeHoverOnly(page, selector) {'],
          ['-','  await page.hover(selector);'],
          ['-','  const shown = await probeVisible(page, selector);'],
          ['-','  return shown;'],
          ['-','}'],
          ['-',''],
          ['-','export const PROBES = [probeVisible, probeHoverOnly];'],
          ['+','  const atRest = await probeVisible(page, selector);'],
          ['+','  await page.hover(selector);'],
          ['+','  await page.waitForFunction('],
          ['+','    (sel) => getComputedStyle(document.querySelector(sel)).opacity === \'1\','],
          ['+','    selector,'],
          ['+','  );'],
          ['+','  const onHover = await probeVisible(page, selector);'],
          ['+','  // The assertion is the PAIR: absent at rest AND present on hover.'],
          ['+','  return { atRest, onHover, pass: atRest === false && onHover === true };'],
          ['+','}'],
          ['+',''],
          ['+','export async function probeScrolls(page, selector) {'],
          ['+','  const before = await page.locator(selector).evaluate((el) => el.scrollTop);'],
          ['+','  await page.locator(selector).evaluate((el) => { el.scrollTop = 9999; });'],
          ['+','  const after = await page.locator(selector).evaluate((el) => el.scrollTop);'],
          ['+','  return after > before;'],
          ['+','}'],
          ['+',''],
          ['+','export const PROBES = [probeVisible, probeHoverOnly, probeScrolls];'],
          [' ','']
        ])
      ] }),

    /* Pure deletion: add:0. The retired rollup path. */
    countChange({ id:'c7', path:'src/analytics/legacy_rollup.rs', line:1,
      summary:'Delete the hourly rollup table now that the composite index serves the same reads',
      status:'deleted', oldPath:null, language:'rust', threadId:'query',
      hunks:[ hunk(1, 0, [
        ['-','//! Hourly rollup of analytics_events.'],
        ['-','//!'],
        ['-','//! Superseded by idx_events_tenant_created: the rollup existed only to'],
        ['-','//! avoid the sequential scan the index now removes.'],
        ['-',''],
        ['-','use crate::db::Pool;'],
        ['-',''],
        ['-','pub struct LegacyRollup {'],
        ['-','    pool: Pool,'],
        ['-','    window_hours: u32,'],
        ['-','}'],
        ['-',''],
        ['-','impl LegacyRollup {'],
        ['-','    pub fn new(pool: Pool) -> Self {'],
        ['-','        Self { pool, window_hours: 24 }'],
        ['-','    }'],
        ['-',''],
        ['-','    pub async fn refresh(&self) -> Result<u64> {'],
        ['-','        self.pool.execute(REFRESH_ROLLUP).await'],
        ['-','    }'],
        ['-','}'],
        ['-',''],
        ['-','const REFRESH_ROLLUP: &str = "REFRESH MATERIALIZED VIEW events_hourly";'],
        ['\\','\\ No newline at end of file']
      ]) ] }),

    countChange({ id:'c8', path:'src/analytics/index_hints.rs', line:1,
      summary:'New index-hint helper so the planner choice is explicit and testable',
      status:'added', oldPath:null, language:'rust', threadId:'query',
      hunks:[ hunk(0, 1, [
        ['+','//! Explicit planner hints.'],
        ['+','//!'],
        ['+','//! The planner picking the right index by accident is not the same as'],
        ['+','//! the planner picking it on purpose, and only one of those survives a'],
        ['+','//! statistics refresh.'],
        ['+',''],
        ['+','#[derive(Clone, Copy, Debug, PartialEq, Eq)]'],
        ['+','pub struct IndexHint {'],
        ['+','    name: &\'static str,'],
        ['+','}'],
        ['+',''],
        ['+','impl IndexHint {'],
        ['+','    pub const fn tenant_created() -> Self {'],
        ['+','        Self { name: "idx_events_tenant_created" }'],
        ['+','    }'],
        ['+',''],
        ['+','    pub fn apply(&self, sql: &str) -> String {'],
        ['+','        format!("/*+ IndexScan({}) */ {sql}", self.name)'],
        ['+','    }'],
        ['+',''],
        ['+','    pub const fn name(&self) -> &\'static str {'],
        ['+','        self.name'],
        ['+','    }'],
        ['+','}']
      ]) ] }),

    countChange({ id:'c9', path:'docs/query-performance.md', line:1,
      summary:'Rename the perf notes to a durable report and record the rollback rehearsal',
      status:'renamed', oldPath:'docs/perf-notes.md', language:'markdown', threadId:'query',
      hunks:[ hunk(1, 1, [
        ['-','# Perf notes'],
        ['-',''],
        ['-','Scratch notes on the analytics read path. Not authoritative.'],
        ['-',''],
        ['-','- index? maybe'],
        ['+','# Query performance'],
        ['+',''],
        ['+','Authoritative record for the tenant-scoped analytics read path.'],
        ['+',''],
        ['+','| Metric | Before | After |'],
        ['+','| --- | --- | --- |'],
        ['+','| p95 read | 482 ms | 71 ms |'],
        ['+','| p50 read | 118 ms | 24 ms |'],
        ['+','| Write throughput | baseline | +4.8% cost |'],
        ['+',''],
        ['+','The rollback is rehearsed, not assumed: see tests/analytics_query_test.rs.'],
        [' ','']
      ]) ] }),

    countChange({ id:'c10', path:'src/analytics/schema.rs', line:88,
      summary:'Narrow the event payload column and drop the unused rollup foreign key',
      status:'modified', oldPath:null, language:'rust', threadId:'query',
      hunks:[
        hunk(86, 86, [
          [' ','pub struct AnalyticsEvent {'],
          ['-','    pub payload: serde_json::Value,'],
          ['+','    /// Bounded at write time; unbounded payloads were 61% of row width.'],
          ['+','    pub payload: BoundedJson<4096>,'],
          [' ','    pub created_at: DateTime<Utc>,'],
          [' ','}']
        ]),
        hunk(140, 141, [
          [' ','impl Schema for AnalyticsEvent {'],
          ['-','    const FOREIGN_KEYS: &[&str] = &["events_hourly_fk"];'],
          ['-','    const INDEXES: &[&str] = &["events_created_idx"];'],
          ['-','    const PARTITION: Option<&str> = None;'],
          ['+','    const FOREIGN_KEYS: &[&str] = &[];'],
          ['+','    const INDEXES: &[&str] = &["idx_events_tenant_created"];'],
          ['+','    const PARTITION: Option<&str> = Some("created_at");'],
          ['+','    const RETENTION: Duration = Duration::days(9);'],
          [' ','}']
        ])
      ] }),

    countChange({ id:'c11', path:'tests/analytics_query_test.rs', line:31,
      summary:'Rehearse the rollback direction and assert the planner keeps the index',
      status:'modified', oldPath:null, language:'rust', threadId:'query',
      hunks:[
        hunk(29, 29, [
          [' ','#[tokio::test]'],
          ['-','async fn forward_migration_applies() {'],
          ['-','    apply("0043_tenant_created_index").await.unwrap();'],
          ['+','async fn forward_and_rollback_both_apply() {'],
          ['+','    apply("0043_tenant_created_index").await.unwrap();'],
          ['+','    assert!(index_exists("idx_events_tenant_created").await);'],
          ['+','    rollback("0043_tenant_created_index").await.unwrap();'],
          ['+','    assert!(!index_exists("idx_events_tenant_created").await);'],
          ['+','    apply("0043_tenant_created_index").await.unwrap();'],
          [' ','}']
        ]),
        hunk(72, 78, [
          [' ','#[tokio::test]'],
          [' ','async fn tenant_isolation_holds() {'],
          ['+','    // The index reorders rows; isolation must be proven, not inferred.'],
          ['+','    let a = events_for(tenant("a")).await;'],
          ['+','    let b = events_for(tenant("b")).await;'],
          ['+','    assert!(a.iter().all(|e| e.tenant_id == tenant("a")));'],
          ['+','    assert!(b.iter().all(|e| e.tenant_id == tenant("b")));'],
          ['+','    assert_eq!(a.len(), 600);'],
          ['+','    assert_eq!(b.len(), 600);'],
          [' ','}']
        ])
      ] }),

    countChange({ id:'c12', path:'config/observability.toml', line:14,
      summary:'Emit the planner choice and the write-amplification gauge',
      status:'modified', oldPath:null, language:'toml', threadId:'debug',
      hunks:[ hunk(12, 12, [
        [' ','[metrics.analytics]'],
        ['-','histogram_buckets = [50, 100, 250, 500]'],
        ['-','emit_plan_name = false'],
        ['+','histogram_buckets = [10, 25, 50, 100, 250, 500]'],
        ['+','emit_plan_name = true'],
        ['+','emit_write_amplification = true'],
        ['+',''],
        ['+','[metrics.analytics.alert]'],
        ['+','p95_read_ms = 100'],
        [' ','']
      ]) ] })
  ];
