"""Exactly two named GLM warm-stage templates, preserving opaque scientific prefixes."""
import copy,json,pathlib,time
import common as p
ROOT=p.ROOT
TOOLS=p.LAB/'dev/tools/versions/v1.5-clock-telemetry'

def neutral(job,stage):
 text='\n\n## Explicit descriptive failed-parent warm continuation\nThe current stage_id is '+job+'. This overrides inherited transport identity only. The original same-arm research Goal remained FAILED/paused at its cap; its authenticated required research4 and original public captures are supplied as a failed draft, not certified research or a completed Goal. Read inputs/prior_file_index.json with the existing mcp__pm_boundary__read_file tool and use its exact listed paths. Only that named original treatment draft and this new lineage\'s authenticated fresh same-arm outputs are permitted. No original critic/final, other arm, evaluator finding or host-authored answer is supplied. Original scientific duties, brief, criteria, required output paths and tool eligibility remain authoritative.\nThis NEW descriptive warm lineage explicitly adds current clock awareness, failfast infrastructure, tools1.5 and metadata-only own-prior navigation after reuse of the original failed research. It earns no clean matched, causal, fresh, logical-target or original whole-pipeline completion credit. Original failures/costs remain retained; the new critic900/90 and final600/60 are separate charges. Original stage clocks are computed at actual dispatch, never reset from this preparation.\n'
 if stage=='revision':text+='The current final carrier is explicit INLINE_ONLY: inputs/delivery_role_manifest.json is intentionally empty. Author all four current artifact slots as text_utf8 using the same actual mcp__pm_boundary__write_file(path,text) and native-endorsed bundle schema. Ordinary failed-draft and fresh-critic inputs may be read, but no input_id adoption, automatic inherited catalog fallback or relaxed native proof is authorized.\n'
 return text.encode()

def prepare():
 selection,context,cap=p.validate_failed_parent();front=p.checked({'path':str(p.LAB/'ops/dispatcher/ORIGINAL_TRACK_B_I01_I08_UNENTERED_FRONTIER_AUDIT_001.json'),'sha256':'16e4d629b4edc00a795978c3920c85da6b311332d5be57c1a3dd01142c1faaaf'})
 oldreg=p.checked(selection['owner_registration_ref']);card=p.checked(selection['card_ref']);factor=card.get('method_id');assert factor=='V01'
 p.put(ROOT/'CARD.json',{**card,'pair_id':p.PAIR,'original_card_ref':selection['card_ref'],'warm_only':True,'extra_logical_target_credit':False})
 p.put(ROOT/'PAIR_INPUT_FREEZE.json',{'schema':'er9.descriptive-warm-input-freeze.v1','pair_id':p.PAIR,'source_slot':'I-01','original_card_ref':selection['card_ref'],'donor_selection_ref':p.DONOR,'actual_family':'Z','model':'GLM 5.3 Flash','effort':'Max','old_research_status':'FAILED/paused','old_costs_preserved':True,'additional_warm_factors':['clock awareness','readiness failfast','tools1.5','own-prior navigation','explicit failed-parent reuse'],'clean_matched_or_fresh_or_logical_target_credit':False})
 jobs=[];preservation=[]
 for stage,job,seconds,responses,version in [('critique',p.CJOB,900,90,'readiness-failfast-core-v1'),('revision',p.FJOB,600,60,'readiness-failfast-bundle-v1')]:
  oldrow=next(r for r in front['unentered_rows'] if r['job_id']=='I-01-FRESH-DELIVERY-R001-treatment-'+stage+'-a001');old=p.checked(oldrow['prepared_stage_ref']);route=p.LAB/'dev/execution/glm-resource-v1/versions'/version;pin=p.checked(p.ref(route/'PIN.json'));frag=p.module(route/'task_fragment.py').render(seconds);folder=ROOT/'packets'/job;ws=folder/'workspace';(ws/'out').mkdir(parents=True);input_pins={}
  for source,digest in old['input_pins'].items():
   rel=pathlib.Path(source).relative_to(old['workspace']);r=p.clone({'path':source,'sha256':digest},ws/rel);input_pins[r['path']]=r['sha256']
  prefix=pathlib.Path(old['prompt_file']);assert p.sha(prefix)==old['prompt_sha256'];p.clone({'path':str(prefix),'sha256':old['prompt_sha256']},ws/'TASK.inherited.md');task=ws/'TASK.md';task.write_bytes(prefix.read_bytes()+neutral(job,stage)+frag);(folder/'clock_fragment.md').write_bytes(frag)
  assert task.read_bytes().startswith(prefix.read_bytes());preservation.append({'job_id':job,'original_Task_ref':{'path':str(prefix),'sha256':old['prompt_sha256']},'scientific_prefix_bytes_preserved':True,'new_Task_ref':p.ref(task),'common_input_SHA_preserved':True})
  selected=copy.deepcopy(old);selected.update(job_id=job,pair_id=p.PAIR,workspace=str(ws),prompt_file=str(task),prompt_sha256=p.sha(task),input_pins=input_pins,out=str(folder/'native'),freeze_out=str(folder/'OUTPUT_FREEZE.json'),max_seconds=seconds,max_responses=responses,pair_freeze=p.ref(ROOT/'PAIR_INPUT_FREEZE.json'),source_stage_ref=oldrow['prepared_stage_ref'],full_pipeline_linking_rules=p.ref(ROOT/'PAIR_INPUT_FREEZE.json'),declared_native_runner=pin['worker']['path'],declared_native_source_pin=p.ref(route/'PIN.json'),declared_tool_source_pin=pin['tools_source_pins'],native_family='Z',warm_only=True,extra_logical_target_credit=False)
  selected['glm_resource'].update(version=pin['version'],source_pins=pin['runtime_source_pins'],model='builtin:zai-coding-plan/GLM-5.3-Flash',effort='max',capture_dir=str(folder/'public_captures'),evidence_dir=str(folder/'tool-evidence'),tools_config_builder=p.ref(TOOLS/'config.py'),clock_fragment=p.ref(folder/'clock_fragment.md'))
  for k in ('bundle_profile_binding_required','dynamic_role_manifest_binding_required','predecessor_binding_required','runtime_binding_required'):selected[k]=False
  if stage=='revision':
   binding=p.module(TOOLS/'operator_binding.py').binding(stage_id=job,stage_role='final_author',case_id=p.PAIR,arm_id='treatment',method_factors=['V01'],actor_binding={'stage_id':job,'family':'GLM','model':'GLM 5.3 Flash','writer_alias':'write_text'},entries=[],complete_final_role=True)
   manifest=ws/'inputs/delivery_role_manifest.json';manifest.write_bytes(binding['manifest_bytes']);input_pins[str(manifest)]=p.sha(manifest);profile=folder/'BUNDLE_PROFILE.json';profile.write_bytes(binding['profile_bytes']);profile.chmod(0o400);selected['glm_resource']['bundle_profile']=p.ref(profile);selected['required_delivery_role_manifest']='inputs/delivery_role_manifest.json'
  # This sealed permission baseline is not an actual action-clock/config binding. The worker builds the actual resource/clock config before Goal.
  baseline=p.module(TOOLS/'config.py').mcp_configs(ws,capture_dir=selected['glm_resource']['capture_dir'],evidence_dir=selected['glm_resource']['evidence_dir'],execution_enabled=old['glm_resource']['execution_enabled'],public_get=old['glm_resource']['public_get'])
  p.put(folder/'tools-baseline.json',baseline);selected.update(tools_config=str(folder/'tools-baseline.json'),tools_config_sha256=p.sha(folder/'tools-baseline.json'),required_resource_contract=p.ref(route/'RESOURCE_CONTRACT.json'))
  p.put(folder/'prepared-stage.json',selected)
  jobs.append({'job_id':job,'arm':'treatment','stage':stage,'stage_index':0 if stage=='critique' else 1,'max_seconds':seconds,'max_responses':responses,'prerequisite_job_ids':[] if stage=='critique' else [p.CJOB],'all_same_arm_prior_job_ids':[p.RJOB] if stage=='critique' else [p.RJOB,p.CJOB],'stage_json':str(folder/'prepared-stage.json'),'stage_sha256':p.sha(folder/'prepared-stage.json'),'expected_freeze':str(folder/'OUTPUT_FREEZE.json'),'pipeline_final':stage=='revision','execution_enabled':old['glm_resource']['execution_enabled'],'public_get':old['glm_resource']['public_get'],'status':'SOURCE_FROZEN_REQUIRES_AUTHENTIC_PARENT_BINDING','runtime_binding_required':True,'runtime_ref':p.ref(route/'PIN.json'),'resource_definition':{'schema':'er9.glm.complete-resource-definition.v1','version':pin['version'],'source_pin':p.ref(route/'PIN.json'),'resource_contract':p.ref(route/'RESOURCE_CONTRACT.json'),'aggregate_memory_max_bytes':2304*1024*1024,'memory_swap_max_bytes':0,'declared_complete_bound_kb':2359296,'fit':'UNKNOWN'}})
 reg={'schema':'er9.dispatch-registration.v1','request_id':p.PAIR+'-SOURCE001','pair_id':p.PAIR,'source_slot':'I-01','family':'Z','requested_model':'GLM 5.3 Flash','requested_effort':'Max','card_path':str(ROOT/'CARD.json'),'card_sha256':p.sha(ROOT/'CARD.json'),'stage_jobs':jobs,'admission_owner':'ops_recovery','status':'SOURCE_READY_PENDING_CONCRETE_ROOT_REVIEW_NO_ADMISSION','native_starts':0,'warm_only':True,'automatic_retry':False,'source_owned_failed_parent_exception':p.DONOR,'declared_total_new_seconds':1500,'old_costs_and_failed_Goal_preserved':True,'extra_logical_target_credit':False,'clean_matched_causal_fresh_or_original_pipeline_credit':False,'both_stage_source_choices_frozen_before_first_new_Goal':True}
 p.put(ROOT/'registration.json',reg);p.put(ROOT/'TASK_PRESERVATION.json',{'rows':preservation,'source_bodies_not_interpreted':True,'additional_factors_declared':True});return reg
if __name__=='__main__':prepare();print('Prepared exact two-stage descriptive warm source closure; no admission or candidate calls')
