# Proposal — "Fieldbook": a local-first fieldwork observation & map exchange tool
**Stage:** research (brief H2, offline field observations and map exchange) · **Date:** 2026-10-06 · **Status:** proposal with evidence; not a build.

Labels used throughout: **[FACT]** = external primary-source fact with pin (see `sources.json` S#); **[INF]** = engineering inference from facts; **[CHOICE]** = product decision we are free to make otherwise; **[UNCERTAIN]** = open dependency; **[EXECUTED-CANDIDATE]** = tiny check run by me in the admitted isolated sandbox (see `witnesses.json`); **[PROPOSED/UNEXECUTED]** = planned validation not yet run.

---

## 1. Scope and non-goals
Fieldbook is a desktop/tablet application for a small environmental survey group. One **project bundle** = a bounded map area + an observation table; field sessions are fully offline; copies are reconciled by exchanging bundles after returning. Non-goals for v1: real-time collaboration, route guidance, hosted accounts, broad map-source support, automated classification (kept as leads, L5–L8). This is a research tool, not emergency navigation.

## 2. Method and evidence separation
Sources were discovered from the brief alone and fetched as public captures (URL, sha256, capture id, and partial-delivery facts per entry in `sources.json`). Two hosts were unreachable from this environment (`operations.osmfoundation.org`, `wiki.openstreetmap.org`; recorded as attempted, not used). Two independently useful implementation precedents were compared (§3), and one real issue→fix→regression-test chain was followed to source level (§4). Three tiny candidate-authored checks were executed in the admitted isolated Python sandbox (§11, W1–W4); their receipts were produced by the platform, and two of them falsified assumptions I had made — reported as found.

## 3. Precedents investigated (≥2 independently useful mechanisms)

### A. Storage family: SQLite R-Tree + WAL, and OGC GeoPackage as bundle format
- **[FACT S1]** SQLite's R*Tree is a virtual table; "rtree" stores coordinates as 32-bit floats and *silently converts* non-conforming values on insert (§3, §3.1); bounding boxes round outward, so contained-within queries should expand query boxes "slightly (by 0.000012%)" (§3.4); you cannot modify an R-Tree mid-scan (SQLITE_LOCKED, §3.5); auxiliary columns exist since 3.24.0 (§4.1); `rtreecheck()` validates index integrity (§7.2).
- **[FACT S2]** In WAL mode, "a COMMIT occurs when a special record … is appended to the WAL"; readers and writers don't block each other; if the DB file "is separated from its WAL file, then transactions that were previously committed … might be lost" (§4); `journal_mode=WAL` persists across reopen (§3.3); with `synchronous=NORMAL`, committed transactions "might rollback following a power failure" (§2.3); WAL does not work on network filesystems (§1).
- **[FACT S3]** GeoPackage Encoding Standard v1.4 (OGC 12-128r19) is published under OGC's royalty-free license permitting implementers to "use, copy, modify, merge, publish, distribute" the specification.
- **Lessons adopted [INF]:** (i) a single-file SQLite store with an R-Tree index gives bounded viewport reads and table scans on a 4-core/8 GB machine; (ii) the 32-bit silent-conversion and outward-rounding behaviors mean the R-Tree is a *candidate* index only — authoritative coordinates live in a full-precision table, never only in the index; (iii) WAL gives exactly the interrupted-save semantics the brief demands — a crash leaves committed records committed and uncommitted work absent — but only if `synchronous=FULL` at commit and if `-wal`/`-shm` travel with the DB (bundle packing must checkpoint and then re-open cleanly); (iv) GeoPackage-style layout (SQLite + registered SRS table + contents tables) is a defensible bundle format; we use a GeoPackage-*shaped* layout without claiming GeoPackage compliance in v1 (compliance is a lead, L8).

### B. Offline sync family: PouchDB/CouchDB revision-tree conflicts
- **[FACT S7]** PouchDB distinguishes *immediate* conflicts (409 on stale `_rev`) from *eventual* conflicts (two peers committed from the same revision offline). On replication, a deterministic algorithm picks one winner so all peers agree, but the losing revisions remain retrievable; `get(doc, {conflicts:true})` returns `_conflicts: ["2-y"]`; resolution is explicit — delete the losing revision or put a new revision on top. The guide also documents the "accountants don't use erasers" append-only design that makes conflicts impossible by never editing documents.
- **Lessons adopted [INF]:** deterministic winner selection prevents *divergent* views of the same record, but a deterministic winner is still a silent choice; our merge therefore separates "auto-merged" from "needs a human" by *field-level* comparison against the common ancestor (W2 demonstrates the mechanism), keeps every losing value inspectable, and never drops provenance to make a merge look clean. Append-only per-record event history (a bounded version of the ledger trick) gives undo and audit for free.

### C. Projection family: PROJ/pyproj as the reference transformation engine
- **[FACT S4]** pyproj 3.7.2's `Transformer` docs carry a standing warning that "the axis order may be swapped if the source and destination CRS's are defined as having the first coordinate component point in a northerly direction", with `always_xy=True` as the opt-out (added 2.2.0); `Transformer.accuracy` is −1 when accuracy is unknown; `from_crs` exposes `allow_ballpark`, `only_best`, `area_of_interest`. Tied to PROJ v9.6 documentation.
- **[FACT S8]** EPSG:3857 is "Not a recognised geodetic system", valid "between 85.06°S and 85.06°N", unit metre, "Cartesian 2D CS. Axes: easting, northing (X,Y)", projected bounds ±20 037 508.34 x / ±20 048 966.1 y (WKT2 `USAGE … BBOX[-85.06,-180,85.06,180]`).
- **Lessons adopted [INF]:** never hand-roll datum transformations; treat PROJ's CRS definitions (not string order) as authoritative for axis order and units; record the selected transformation and its stated accuracy (−1 = unknown, must display); Web-Mercator display bounds are a hard domain edge that imports must validate against (W3).

**Why these precedents fit (applicability):** each supplies a *mechanism* the brief names — bounded spatial access, crash-recoverable commits, explicit offline conflict semantics, versioned authoritative transformations. None of them proves whole-product correctness: an R-Tree index, a WAL file, and a conflict UI are components; the composition (import validation, merge rules, provenance) is ours and is where the proposed validation (§11) concentrates.

## 4. Real issue → fix → regression-test chain (release/branch applicability)
**[FACT S9, S10]** pyproj issue **#1157** ("+R_A appears to have no effect in Geod()", opened 2022-10-04 against pyproj 3.4.0 / PROJ 9.1.0; state: open, reopened). Fix **PR #1610** ("BUG: Honour PROJ spherification parameters in Geod"): the diff shows the root cause in `pyproj/geod.py` — the old parser line `if kvpair.find("=") == -1: continue` silently discarded every valueless parameter, so `+R_A` was dropped *silently, without error or warning*, while the `geod` CLI honored it. The PR adds `+154/−3` lines to `pyproj/geod.py` (hunks `@@ -56,6 +56,133 @@`, `@@ -198,20 +325,30 @@`, `@@ -229,6 +366,20 @@`) and `+72/−0` regression-test lines to `test/test_geod.py` (hunk `@@ -953,3 +954,74 @@`), including `test_geod__spherification__changes_result` (explicitly citing issue #1157), an 8-case radius table checked against PROJ's resolved ellipsoid, mutual-exclusion and invalid-latitude error tests — 14 new tests, "all failing before the change and passing after" per the PR body. `docs/history.rst` (hunk `@@ -3,6 +3,7 @@`) places the fix under "Latest", *after* the 3.8.0 entry; `merged_at` is null as of capture 2026-10-06.

- **Release applicability:** the fix is in no released pyproj as of capture; pyproj **3.7.2** (the version my docs are pinned to, S4) and 3.8.0 do **not** contain it. The PR body reports it was built against PROJ 9.8.1. If Fieldbook pins pyproj, the pin must be re-verified when 3.8.x ships (lead L10).
- **Lesson adopted [INF/CHOICE]:** this is exactly the brief's "undocumented guess" failure mode — a component silently accepted a partially-understood definition and returned confidently wrong geometry. Fieldbook's import contract therefore requires: unknown *any* parameters (CRS extensions, units, flags) are surfaced as visible import warnings with an explicit bounded choice (accept / correct / reject), never silently dropped; and a companion defect finding, **[FACT S9]** issue **#1548** (open, milestone 3.8.1): two `CRS` objects that compare equal can produce *different hashes* after a WKT round-trip, breaking hash-keyed caches — so our transformation cache keys on the PROJ-serialized definition string we actually passed, plus the pinned PROJ dataset version, and we treat WKT-equality as non-transitive at cache level.
- **Boundary honesty:** a merged PR and passing regression tests fix one function's behavior; they do not establish that any pyproj version is correct for all CRS pairs — whole-product transform validation stays in §11.

## 5. Data and coordinate contract
### 5.1 Identity layers (all UUIDv4, minted on the machine that creates the object)
- **Project identity** `project_id`: immutable; copied bundles keep it, so any two files claiming the same `project_id` are *the same project* and mergeable; different `project_id` = different project, never auto-merged. Re-importing the same external source file creates a `source_id` = `sha256(file bytes)` — identical hash ⇒ identical source ⇒ the import is idempotent (update-in-place of the import batch, originals preserved); a different hash of a same-named file is a *new* source batch, shown as such. **[INF/CHOICE]**
- **Record identity:** `record_id` (observation identity) is separate from `edit_id` (one append-only edit event) and from `geometry_rev` (monotonic per-record counter of accepted geometry states). A displayed pin therefore references `record_id@geometry_rev`; an export states the `geometry_rev` it serialized. **[CHOICE]**
- **[FACT S9 #1548 caveat]** identity of *CRS definitions* is not hash-stable across WKT round-trips in pyproj ≤3.7.2; cache keys use the exact definition string + PROJ/EPSG dataset version, not Python `hash()`.

### 5.2 Stored / displayed / exported coordinates
- **Stored:** every observation keeps `coords_native` (verbatim import values + CRS reference from the project's SRS registry), plus `coords_wgs84` (derived, with the transformation id used). The native values are authoritative; the WGS84 copy is a cache and can be recomputed. Edits made on the map write *both*, tagged with the display CRS at edit time. **[CHOICE]**
- **Displayed:** map pins are computed stored→display (display is always EPSG:3857 or EPSG:4326 per the bundled basemap, S8) at render time. **[FACT S1]** R-Tree boxes are 32-bit and rounded outward — the index returns *candidates*; exact containment uses the stored double-precision values.
- **Exported:** exports re-serialize from `coords_native` (or the user-chosen target CRS via a recorded transformation), and each export carries a header: source CRS, target CRS, transformation id, PROJ/EPSG dataset versions, row count, and per-row `geometry_rev`. A pin on screen is never taken as proof of export correctness — §11 V2 checks stored vs exported coordinates directly. **[INF]**
- **Geometry/edit identity:** every edit event appends `(edit_id, record_id, field deltas, actor device id, wall-clock + optional GPS time, base geometry_rev)`; acceptance advances `geometry_rev`. Undo pops the edit event; history is never rewritten. **[INF from S7 ledger pattern]**

### 5.3 Support boundary for reference systems and geometry (v1)
- **Supported:** any CRS PROJ can name (authority code or WKT) for *import and storage*; transformations only along PROJ-recommended paths between named CRSs and EPSG:4326/EPSG:3857; geometry types: point, line-string track, polygon-free (tracks and points only), with optional per-record altitude and timestamp. **[CHOICE]**
- **Not supported in v1 (visible, not guessed):** user-defined (non-authority) CRS without WKT; datum transformations whose only path is a *ballpark* estimate (PROJ exposes this; S4 `allow_ballpark`/`only_best`) — these import with an "approximate location" flag or are rejected by user choice; 3D/4D grid shifts requiring downloadable grids not present in the bundle — the transformation is refused offline with a named missing-grid error rather than silently degraded. **[INF from S4]**
- **Unknown/ambiguous metadata:** unknown CRS string, unknown units, missing axis order, or unknown altitude/time datum block the batch from auto-commit: the import shows a bounded choice list (detected candidates via PROJ with stated area-of-use/accuracy) and the batch stays in `importing` state until a choice is made or the import is cancelled. Nothing is auto-guessed. **[CHOICE per brief]**
- **Transformation versioning:** each project stores a `transform_registry`: `(from_crs, to_crs, proj_pipeline_or_selector, proj_version, epsg_dataset_version, accuracy_or_-1, created_utc, content_hash)`. Re-derive on open; if PROJ now selects a *different* path for a registry entry, the derived coordinates are marked `stale-transform` (visible badge) and recomputed on confirmation — originals untouched. **[INF]**

### 5.4 Boundary and malformed cases (investigated individually, no universal behavior claimed)
- **Edge-adjacent coordinates:** validated against the target CRS domain (e.g., |lat| ≤ 85.06 for EPSG:3857 display, S8). **[EXECUTED-CANDIDATE W3]** spherical-Mercator math at lat 90° returns y≈2.38e8 m — finite, ~12× the EPSG bound, *without raising* — so validation must be an explicit bound check, not exception handling; round-trip at the 85.05112878° edge reproduces y = 20 037 508.34 m exactly.
- **Antimeridian-crossing tracks:** **[EXECUTED-CANDIDATE W3]** naive segment length across ±180° is 38 961.8 km vs 1 113.2 km unwrapped (35× error). Tracks store an explicit `unwrapped_lon` series; rendering splits at the discontinuity; exports document whether longitudes were re-wrapped. Behaviors at other discontinuities (UTM zone borders, projection seams) are *not* asserted — flagged for phase-2 testing (V5).
- **Incomplete coordinates (NULL/partial lat/lon):** stored as `incomplete` records, excluded from the spatial index (indexes require complete boxes; S1's R-Tree even silently type-coerces, so the application layer, not the index, guards completeness), listed in a "needs location" tray, never auto-placed at (0,0). **[INF]**
- **Conflicting identifiers:** duplicate detection at import = exact `source-local id` match, plus a *provisional* geometric+name key (normalized longitude wrap, 5-decimal rounding, casefolded name) that only ever *flags* candidates for human review. **[EXECUTED-CANDIDATE W2 note]** my first duplicate-key test pair was wrong — 196.3°E correctly wraps to 163.7°W, so the keys legitimately differed and no duplicate was detected; the positive duplicate case remains PROPOSED/UNEXECUTED (V4). The executed witness demonstrates the key mechanics and falsified my wrap intuition; it does not validate duplicate detection.
- **Sample previews do not validate imports:** preview shows N random records *plus* deterministic per-batch aggregates (bounds vs declared area-of-use, NULL counts, CRS-domain violations, transform failures). Full-batch validation (V1) is a bounded background job with cancellation; preview alone is labeled "preview, not validation".

## 6. Revision and merge contract
- **Append/edit/delete semantics:** edits and deletes are edit-events; delete = tombstone event (`deleted=true`), so originals are always recoverable. Two devices editing offline diverge at the record level.
- **Merge (project copy A + colleague copy B):** pair by `record_id`; compute field-level three-way merge against the last common `geometry_rev`/edit set recorded in the bundle exchange history. Disjoint-field changes auto-merge; same-field divergence and edit-vs-delete become **inspectable conflict cards** showing base/ours/theirs (including both coordinate values in their CRSs and a map thumbnail of both) with explicit per-record choices (keep ours / keep theirs / keep both as separate records / hand-merge). No field is dropped; every resolution writes an edit-event citing the conflict. **[EXECUTED-CANDIDATE W2]** demonstrates: disjoint edits auto-merge cleanly; the naive auto-merge of "A moved the point, B deleted the record" silently produces a *deleted, relocated* record — so Fieldbook forces that into a conflict (exit-status 2 pattern in the witness). A practical explicit choice beats a false automatic-perfect-merge promise, per brief.
- **Deterministic ordering only for tie-breaks the user allowed in settings** (e.g., "newest timestamp wins *by default*, always listed in the merge report"); the report lists every auto-decision so "automatic" is never silent.
- **Duplicate records across copies:** flagged by the §5.4 provisional key into a review list; never auto-unified.
- **Interrupted save/import/merge:** writes are WAL transactions (S2): reopen after a crash shows only committed records; a `merge_journal` row per merge step makes merge resumable; an interrupted import leaves its batch in `importing` with a checkpoint, distinguished from committed records in the UI. Media (photos) are content-addressed (`sha256`) inside the bundle with a manifest; **relocating media = moving files + updating the manifest path, never renaming inside the DB**; a missing/broken media file degrades that record to "photo missing" with hash, never to a silently empty record. Bundle copy rules follow S2: checkpoint (`wal_checkpoint(TRUNCATE)`) and clean close before zipping, so no `-wal` separation loss.
- **Recovery limits [UNCERTAIN]:** torn pages or disk-level corruption are *out of scope* beyond SQLite's own integrity mechanisms; `rtreecheck()` (S1 §7.2) and `PRAGMA integrity_check` run on open as a bounded job, with "rebuild index" repair offered — this repairs *indexes*, not lost data.

## 7. Architecture (and the bounded alternative)
- **[CHOICE] Core:** Python 3.12 + SQLite (WAL, `synchronous=FULL`) single-file project store + sidecar media store + JSON manifest, bundled as one `.fieldbook` zip. Layers: `import/validate` → `store (records + rtree index + transform registry)` → `merge engine` → `UI (Leaflet-style canvas over bundled tiles)` → `export`.
- **Renderer:** EPSG:3857 raster/vector tiles from the bundled area only; viewport queries hit the R-Tree with the 0.000012% outward expansion for contained-within correctness (S1 §3.4); index writes never interleave with open scans (S1 §3.5) — the UI batches index updates between query frames.
- **Bounded alternative (equally defensible):** adopt GeoPackage *itself* (S3, royalty-free OGC license) as the native store — gaining ecosystem interop (QGIS opens it directly) at the cost of conforming to its trigger/schema rules and slower iteration; recommended as the v2 decision point once schema stabilizes. A third alternative (embedded map-vector renderer) is rejected for v1: more code, no user-visible gain for a bounded area.

## 8. Performance, resources, and offline envelope (engineering targets, not benchmarks)
Target machine: 4 cores / 8 GB RAM; project up to 250,000 observations. **[INF]**
- **Bounded access:** all browsing/search is R-Tree viewport queries + keyed lookups + paginated table scans; no full-table render paths. **[EXECUTED-CANDIDATE W1]** a toy uniform-grid index over 250,000 synthetic clustered points answered a 0.4°×0.4° viewport by touching 3 of 250,000 points (fraction 1.2e-05, 81-cell window). Scope: this demonstrates the bounded-read *mechanism* on synthetic data only; it is not a measurement of SQLite R-Tree performance.
- **Index/cache invalidation:** the R-Tree is a derived index (rows keyed by `record_id@geometry_rev`); any edit-event application updates it transactionally; `rtreecheck()` + row-count reconciliation on open catches drift; the `coords_wgs84` cache invalidates by `transform_registry` hash (§5.3).
- **Cancellation:** import, full validation, export, and index rebuild are cancellable cooperative jobs (checked every batch); cancellation leaves the job's journal row marked `cancelled`, state distinguishable from `done`/`failed` (§6 recovery).
- **Large export:** streaming writer (constant memory) with the §5.2 header; export of the full table is O(n) I/O, chunked, resumable from its journal entry.
- **Without a network:** everything above works offline — basemap is the bundled area, transformations use bundled PROJ data, photos are local. Only initial bundle assembly and (optional, off-by-default) OSM-derived updates need connectivity.

## 9. Map/source data licensing (actual selected source)
- **[FACT S6]** Bundled basemap: **Natural Earth** — "All versions of Natural Earth raster + vector map data … are in the public domain … No permission is needed to use Natural Earth. Crediting the authors is unnecessary." This legitimately supports offline bundling; no proprietary licensed data is used.
- **[FACT S5]** If the group ever wants OSM-derived detail: OSM is ODbL — credit plus share-alike for derived databases — and the captured OSM copyright page states the OSMF "cannot provide a free-of-charge map API or map tiles for third-parties" (links to the tile/API usage policies). **[FACT: attempted, unreachable S11]** The OSMF tile-usage-policy page itself could not be fetched from this environment; **[INF]** until it is verified, Fieldbook treats *live OSM tile fetching as unsupported*, which also matches the offline-first design. Web-viewer availability ⇒ offline bundling does **not** follow. Higher-detail offline OSM extracts (e.g., Geofabrik) and their license chain are lead L9.

## 10. UX, accessibility, offline state
- **[CHOICE]** Every record view shows a provenance line: CRS (name+code), axis order, units, altitude datum, time source (GPS vs device clock), transformation id + accuracy (or "unknown accuracy", S4 `accuracy = −1`). Errors are per-record and per-batch with counts; failed records are never hidden (brief requirement).
- Full keyboard operation of the record table and conflict cards; visible focus; form labels tied to inputs; conflict and validation language free of jargon; color never the sole signal (offline/conflict/stale badges carry text).
- **Obvious offline state:** persistent header badge (`OFFLINE — bundled map area only` vs `ONLINE`), and any action requiring network is disabled with an explanation, not hidden.
- **Undo:** every edit-event is reversible (§5.2); undo history is per-device and inspectable; merge resolutions are individually reversible until the merge journal is sealed.

## 11. Validation plan
**Executed by candidate (isolated `python_execute` sandbox; receipts in `witnesses.json`; each is an isolated component check, not proof of application behavior):**
- **W2 (exec id exec-9blb5nsp, exit 2):** synthetic three-way field merge. Disjoint edits auto-merged; edit-vs-delete *naively* auto-merged into a contradictory record, then forced into an explicit conflict (nonzero exit). Scope: mechanism demo, not the product merge engine. A first run (exec id exec-iiilc69k, exit 1) crashed on my own NameError — recorded, not hidden.
- **W1 (exec id exec-nfil_n4y, exit 0):** bounded viewport access over 250,000 synthetic clustered points: 3 of 250,000 candidates scanned (1.2e-05) for a 0.4°×0.4° window. Scope: toy grid index, not SQLite R-Tree.
- **W3 (exec id exec-iomyz22c, exit 0):** spherical-Mercator edges: exact round-trip at the EPSG:3857 latitude limit (y = 20 037 508.34 m); lat 90° yields 2.38e8 m with **no exception** (bound-check requirement); antimeridian naive error 38 961.8 km vs 1 113.2 km unwrapped; wrap examples.

**Proposed / UNEXECUTED (planned for the build, each with pass criteria):**
- **V1** Full-import validation on a 250k synthetic project: zero unexplained records; run < 10 min on target-class machine; cancellable mid-run.
- **V2** Export round-trip: export→re-import preserves every `geometry_rev`, coordinate bitwise in native CRS, and provenance header; sampled *and* exhaustive checks (sample alone insufficient per brief).
- **V3** Crash-recovery: `SIGKILL` mid-save/mid-merge on WAL store; reopen shows committed-only + resumable journal; media manifest consistent.
- **V4** Duplicate-key positive case (the W2 follow-up my faulty test data failed to demonstrate) + conflicting-identifier review queue.
- **V5** Discontinuity suite: tracks crossing antimeridian, UTM-zone edges, CRS domain corners — each with expected, user-visible handling or a documented unsupported status.
- **V6** Transform-regression harness: replay stored `transform_registry` across pinned PROJ versions; alert on any differing output before display (version-bound: pyproj 3.7.2/PROJ as bundled; re-pin when #1610's fix ships — §4, L10).

## 12. Opportunities and alternatives
- **Opportunity (useful, later):** bundle-level **schema-locked GeoPackage export** (S3) so survey groups can hand files to QGIS/government partners without Fieldbook present; incremental step from the GeoPackage-shaped layout.
- **Opportunity (later):** CRDT/event-sourced sync (automerge-style) to move from bundle-exchange to near-real-time collaboration — PouchDB's eventual-conflict model (S7) is the conceptual bridge; deferred because bundle exchange satisfies the brief.
- **Plausible alternative (min-viable divergence):** if the team standardizes on QGIS, ship Fieldbook only as an import/merge layer over GeoPackage files and drop the custom store — fewer moving parts, weaker in-app conflict UX. Kept as a bounded alternative to §7, not the recommendation.

## 13. Uncertainty register / critical dependencies
1. **[UNCERTAIN]** pyproj/PROJ pin: docs pinned to pyproj 3.7.2 (PROJ 9.6 docs); PR #1610 fix unreleased (S9/S10); #1548 hash instability open — both affect transformation cache and identity code (L10). Mitigation: transform-regression harness V6.
2. **[UNCERTAIN]** OSM tile-policy page unfetchable here; OSM-derived offline extracts licensing chain unverified (L1, L9). v1 design avoids the dependency (Natural Earth, S6).
3. **[UNCERTAIN]** GeoPackage compliance details beyond the captured first 512 KB of the spec (S3 partial) — L8.
4. **[UNCERTAIN]** Photograph EXIF time/geometry provenance: not investigated this stage (L3); v1 records device-file hash + user-confirmed capture time only.
5. **[INF limits]** 250k-observation performance is an engineering target from mechanism evidence (W1 toy + S1 semantics), not a benchmark; treat §8 numbers as hypotheses until V1/V2 run.
