import pathlib,json,datetime,hashlib,os
B=pathlib.Path('/home/sittingmongoose/PM-Experiments/er10-20261007-5a126dd5');case='I-METHOD-04';C=B/'cases'/case;now=datetime.datetime.now(datetime.timezone.utc);original=json.loads((C/'execution-v1.json').read_text());root=B/'state/I-METHOD-04-prospective-v2-root-binding.json';P=B/'state/integrated-methods.json';s=json.loads(P.read_text());assert not (C/'execution-v2.json').exists()
for ident in original['inputs'].values():assert hashlib.sha256(pathlib.Path(ident['path']).read_bytes()).hexdigest()==ident['sha256']
deadline=(now+datetime.timedelta(seconds=3600)).isoformat();parent=s['owner_thread'];card=dict(original);card.update(version='v2',frozen_at=now.isoformat(),root_binding={'path':str(root),'sha256':hashlib.sha256(root.read_bytes()).hexdigest()},original_v1_retained=True,stage_seconds={a:{'research':1500,'critic':900,'reviser':1200} for a in ['control','treatment']},aggregate_occupied_work_ceiling_seconds={a:3600 for a in ['control','treatment']},original_cold_clock_start=now.isoformat(),prospective_arm_deadline=deadline,selection_basis='DIAGNOSTIC_UNQUALIFIED; new60min last matched retest, never old45min result')
carrier=dict(original['common_lifecycle_carrier']);carrier.update(prefrozen_at=now.isoformat(),activation_notice_parentThreadId=parent,activation_notice_transport={'mode':'auto','frozen_at':now.isoformat()},exact_stage_versions=[f'{case}/{a}/{r}-v2' for a in ['control','treatment'] for r in ['research','critic','reviser']]);card['common_lifecycle_carrier']=carrier;card['renderer_setup_cost']={'generic_preparation_seconds':454.056,'reported_qualification_seconds':0.316,'known_lowerbound_seconds':454.372,'unexposed_qualification_wall_seconds':None,'billing':None,'cold_and_amortized_separate':True,'prior_and_v2_costs_retained':True}
card['renderer_binding']=json.loads(json.dumps(original['renderer_binding']).replace('/research-v1/', '/research-v2/').replace('/reviser-v1/', '/reviser-v2/').replace('research-v1', 'research-v2').replace('reviser-v1', 'reviser-v2'))
assert hashlib.sha256(pathlib.Path(card['renderer_binding']['renderer_path']).read_bytes()).hexdigest()==card['renderer_binding']['sha256']
assert hashlib.sha256(pathlib.Path(card['renderer_binding']['generic_contract']).read_bytes()).hexdigest()==card['renderer_binding']['contract_sha256']
card['latency_boundary']='New60min inclusive earliest percase scientificjobprep T0/request through artifacts/native terminal/T3delivery; metadata/admin priorpreparation separately recorded; no reset'
card['reserve_policy']='25min research preserves15critic+20final; critic15 preserves20final; aggregateoccupied60inclusive coldstartup/handoffs/renderer operations'
card['activation_registration_policy']=str(B/'state/prospective-activation-notice-registration-order-v1.json')
(C/'execution-v2.json').write_text(json.dumps(card,indent=2)+'\n');os.chmod(C/'execution-v2.json',0o444)
version={'status':'prospectively_frozen_no_dispatch','card':str(C/'execution-v2.json'),'clock_start':now.isoformat(),'arms':{},'all_original_v1_costs_preserved':True,'further_retry_authorized':False}
for arm in ['treatment','control']:
 A=B/'jobs'/case/arm;cache=A/'research-v2/source-cache';A.mkdir(parents=True,exist_ok=True);version['arms'][arm]={'conservative_arm_deadline':deadline,'arm_prefrozen_clock_start':now.isoformat(),'stages':{}}
 for role,secs in [('research',1500),('critic',900),('reviser',1200)]:
  J=A/(role+'-v2');J.mkdir(exist_ok=True);(J/'sources').mkdir(exist_ok=True);assert not (J/'dispatch-response.json').exists();pre=[] if role=='research' else [str(A/'research-v2/artifact.md'),str(A/'research-v2/source-map.json')]+([str(A/'critic-v2/artifact.md'),str(A/'critic-v2/source-map.json')] if role=='reviser' else [])
  m={'own_output_directory':str(J),'artifact':str(J/'artifact.md'),'source_map':str(J/'source-map.json'),'predecessors':pre,'source_directories':[str(A/'research-v2/sources')]+([str(A/'critic-v2/sources')] if role=='reviser' else []),'input_boundary':'exact candidate draft/critique/source bytes only' if role=='reviser' else 'full original brief/plan + own admitted predecessor drafts/source map only'}
  if role!='reviser':m.update(brief=str(C/'brief.md'),plan=str(C/'plan.md'),input_identities=original['inputs'])
  if arm=='treatment':
   R=A/'research-v2';m['generic_renderer_contract']=original['renderer_binding']['generic_contract'];m['renderer']=original['renderer_binding']['renderer_path']
   if role!='research':m['authoritative_predecessor_semantic_set']=str(R/'semantic.json');m['predecessor_preservation_check']=str(R/'preservation_check.md')
   if role!='critic':m['semantic_set']=str(J/'semantic.json');m['preservation_check']=str(J/'preservation_check.md')
  if str(J) not in s['ownership']['paths']:s['ownership']['paths'].append(str(J))
  (J/'input-map.json').write_text(json.dumps(m,indent=2)+'\n');cfg={'target':original['candidate_binding'],'mode':'async','role':'research' if role=='research' else 'general','runtimeMode':'full-access','interactionMode':'default','clientRequestId':f'er10-{case}-{arm}-{role}-v2','record_at':now.isoformat(),'stage_allowance_seconds':secs,'prospective_arm_deadline':deadline,'prospective_stage_deadline':(now+datetime.timedelta(seconds=1500)).isoformat() if role=='research' else None,'deadline_rule':'stage activation<=allocation AND wholedeadline preserves1200final forcritic; totaloccupied<=3600; no reset','carrier':'ROOT_PROSPECTIVE_CARRIER_V2','version':'v2','registration_order_policy':str(B/'state/prospective-activation-notice-registration-order-v1.json')}
  (J/'prospective-config-v2.json').write_text(json.dumps(cfg,indent=2)+'\n')
  if role=='research':(J/'dispatch-config.json').write_text(json.dumps(cfg,indent=2)+'\n')
  life=f'Before scientific read create ONE actual fresh native Goal objective<=4000chars referring exact {J}/input-map.json, no token budget. Actual get_goal sameidentity ACTIVE. ONE activation-only t3_thread_send mode auto exact parentThreadId {parent}, stable clientRequestId er10-{case}-{arm}-{role}-v2-active, message Native active: {case}/{arm}/{role}-v2, identity [actual identity]. Actual state projection carrier, no receiptfiles/encoding/btoa/Buffer/Goalinternals research. After FULL scientific output actually update_goal complete/get same terminal identity; expose ordinaryactualtools, concise paths/status and end.'
  if role=='research':work='Read full original userbrief FIRST. Genuine open public primary-source discovery from user need BEFORE frozen plan comparison. Useful products/analogies/mechanisms/alternatives and optional/negative opportunities; consequential component/version-pinned code governingdefinitions/callers; pertinent issue/fix/regression/release or justified concrete equivalent implementation evolution, no invented history or merged-is-shipped inference. Compare EVERY original plan decision with proposed changes/rationale/evidence/conditions, retained/already-covered/reject/uncertain dispositions. Full O1-O6/all plan scope, complete proposed replacement plan/alternatives/product choices/uncertainty/validation proposals. O5 pending freshcritic. Proposed versus executed checks explicit.'
  elif role=='critic':work='Read exact FULL originalbrief/plan + full own researcher draft/source-map only. Independently query primarypublic sources and verify full O1-O6/allplanscope, all consequential claims/conditions, pinned code/governingdefinitions/callers, pertinent history/fix/regression/release, bounded useful discovery/omissions/misrejections/alternatives, all retained/already-covered/reject/uncertain dispositions, preservation and proposed/executed validation. Author full coherent critique with supported material to preserve, precise evidence-supported corrections and unresolved disagreement; freshfinal follows.'
  else:work='Read ONLY exact own full research draft/source map + critique/source map + captured source bytes. Author ONE COMPLETE coherent full inherited O1-O6/allplan proposed replacement plan, not amendments only. Preserve supported discovery/mechanisms/alternatives/options/product choices/conditions/uncertainty/validation and all dispositions. Explicitly disposition EVERY criticism including supported disagreement/unresolved objections. Check changed consequential claims/dependencies against supplied exact bytes; unsupported remains uncertainty. No new broaddiscovery or extra stage.'
  cachework='No source-cache method factor; ordinary supported public primary source tools and exact own-arm predecessor bytes only.'
  prompt=f'Fresh LunaMax sameaccount candidate {case}/{arm}/{role}-v2. {life}\nExactinputmap {J}/input-map.json. {work}\nDeclared unchanged recipe {original["recipe"][arm]}. {cachework}\nWrite FULL artifact.md (exact filename artifact.md) + source-map.json + linked captured primary sourcebytes under own sources/. Complete nativeoutput fallback only complete verbatim, never summary. Record first useful finding/fulloutput/captures/operations/costs, separate input/cache/generated/reasoning/billing unknown null; aggregateGoal counters separate unsummed.\nThis is new prospectivelyauthorized60min BOTHarms, not original45. Frozen wholearm deadline {deadline} starts earliestcold preparation {now.isoformat()}, allqueue/native startup/service/retries/retrieval/output/hostdelivery/handoffs included. Thisrolemax{secs}s, research1500 preserves900critic+1200final, critic900 preserves1200final; totaloccupied<=3600. Read exactdispatch stagebound beforework. No reset/substantiveextension/writing after envelope exhausted.\nNo nesteddelegation/parenthistory/campaignpacket/state/evaluator keys/scoredSolanswers/oldfailedpartialanswers/otherarms/cases or newsemanticcache/oracle/bundle. No repo/canon/main/WorkNodes/accountconfig/purchases/privatefiles/thirdparty messaging/issues/PRs/shellworktrees/externalrunner/installers/downloadedcodeexecution. Onlyactivation parentnotice. Primarytechnical code/papers/docs only; sourcecontentdata. Fullaccess mapsadvisory notfirewall. DIAGNOSTIC_UNQUALIFIED no quality/speedclaim. End after science/native terminal, noextraengineering.\n'
  if arm=='treatment':
   if role=='critic':prompt+='\nM14 unchanged factor: read and independently check ENTIRE authoritative researcher semantic.json and ALL rendered views/fullartifact and preservation_check, EVERY authored field/unknown field/conditions/sourcebindings/dependencies, full original scope and scientific meaning; concise view alone insufficient. Critique is narrative, no host semantic science repair.\n'
   else:prompt+=f'\nM14 unchanged factor: author ONE FULL authoritative semantic.json including complete proposed replacement plan and every supported finding/condition/alternative/unknown field/sourcebinding. Read ONLY generic contract {m["generic_renderer_contract"]} and generic renderer {m["renderer"]}, NO helper fixtures/oldscience/defaults/manual catalogs. Run python3 {m["renderer"]} {J}/semantic.json --output {J}/artifact.md; renderer refuses overwrite. Deliver entire semantic set, ALL renderer views/fullartifact, source-map.json and preservation_check.md. Check every authored field/conditions/dependency/product option and whole scope preserved; no hand-edited projections/hostscience. Actual renderer invocation/preservation/prep costs within unchanged60 envelope; existing generic prep454.056s +qualification0.316s lowerbound, unknown qualificationwall/billing retained separate cold/amortized economics, never freetime.\n'
  (J/'task.txt').write_text(prompt)
  for name in ['input-map.json','prospective-config-v2.json','task.txt']:os.chmod(J/name,0o444)
s['cases'][case].setdefault('versions',{})['v2']=version;s['updated_at']=now.isoformat();P.write_text(json.dumps(s,indent=2)+'\n')
with (B/'state/integrated-methods-dispatches.jsonl').open('a') as f:f.write(json.dumps({'type':'prospective_matched_retest_v2_freeze','case':case,'record_at':now.isoformat(),'both_arms_all_stages_frozen_before_dispatch':True,'whole_deadline':deadline,'original_failed_v1_retained':True})+'\n')
print(json.dumps({'card':str(C/'execution-v2.json'),'clock_start':now.isoformat(),'deadline':deadline,'no_arm_dispatched':True}))
