import pathlib,json,hashlib,datetime
B=pathlib.Path('/home/sittingmongoose/PM-Experiments/er10-20261007-5a126dd5');now=datetime.datetime.now(datetime.timezone.utc).isoformat();L=B/'locks/speed-budget-selection-v1.json';lock=json.loads(L.read_text());assert lock['recipe']['version']=='ER10-LUNA-TWO-STAGE-LOCKED-V1';assert datetime.datetime.fromisoformat(now)>datetime.datetime.fromisoformat(lock['locked_at']);ready=json.loads((B/'helpers/integrated-case-design/ready-cases.json').read_text());s=json.loads((B/'state/integrated-methods.json').read_text());base=json.loads((B/'cases/I-METHOD-06/execution-v1.json').read_text());cards=[]
def ident(p):b=p.read_bytes();return {'path':str(p),'sha256':hashlib.sha256(b).hexdigest(),'bytes':len(b)}
for case in ['I-FAST-01','I-FAST-02','I-FAST-03']:
 C=B/'cases'/case;row=next(x for x in ready['cases'] if x['case_id']==case);assert not (C/'execution-v1.json').exists();inputs={}
 for n,v in row['input_identities'].items():
  x=ident(C/n);assert x['sha256']==v['sha256'] and x['bytes']==v['bytes'];inputs[n]=x
 prepared=ident(C/'prepared.json');assert prepared['sha256']==row['prepared_identity']['sha256'];roles={'control':{'research':1200,'critic':600,'reviser':900},'treatment':{'research':750,'critic-finalizer':600}};overlay=dict(base['common_lifecycle_carrier']);overlay.update(prefrozen_at=now,exact_stage_versions=[case+'/'+a+'/'+r+'-v1' for a,rs in roles.items() for r in rs]);overlay['activation_notice_transport']={'mode':'auto','reason':'one exact activation-only notice to known parent even if idle','frozen_at':now}
 card={'schema':'er10.integrated.speed.execution.v1','case_id':case,'frozen_at':now,'root_lock':ident(L),'locked_recipe':lock['recipe'],'candidate_binding':base['candidate_binding'],'review_binding':base['review_binding'],'inputs':inputs,'prepared_identity':prepared,'same_pair':{'inputs':True,'full_scientific_scope':True,'effort':True,'account':True,'access':True,'family':True},'recipe':{'control':'Competent fresh researcher, independent same-family critic, fresh complete final reviser','treatment':'Fresh full-scope public researcher then fresh same-family critic independently checks governing evidence, repairs conclusions and writes complete final; no scope reduction'},'stage_seconds':roles,'aggregate_occupied_work_ceiling_seconds':{'control':2700,'treatment':1350},'latency_boundary':'earliest actual T3 requestedAt first stage through native terminal/T3 delivery including queue/coldstartup/hostsetup/sourceoperations/retries/output/delivery; control45min treatment22.5min, no clockreset','reserve_policy':'research preserves control600critic+900final or treatment600critic-finalizer; no writing-stage admission after envelopeexhaustion','final_role':{'control':'reviser','treatment':'critic-finalizer'},'launch_order':['control','treatment'] if int(case[-2:])%2 else ['treatment','control'],'common_lifecycle_carrier':overlay,'quality_axes':base['quality_axes'],'output_scope':base['output_scope'],'output_contract':base['output_contract'],'expiry_policy':base['expiry_policy'],'tool_policy':base['tool_policy'],'selection_basis':'DIAGNOSTIC_UNQUALIFIED; no qualified comparative quality/speed/affordability win','no_semantic_cache_or_oracle_or_new_bundle':True,'no_after_outcome_budget_or_recipe_tuning':True,'independent_review_gate':'both exact full finals/native terminal dispositions frozen and all candidate tasks/descendantsquiet before any evaluator key; fresh ordinary Sol6.1xhigh codex_gmail priority full declaredscope, blindinglimits explicit'}
 for a,rs in roles.items():
  for r in rs:
   J=B/'jobs'/case/a/(r+'-v1');J.mkdir(parents=True,exist_ok=True);(J/'sources').mkdir(exist_ok=True);m={'brief':str(C/'brief.md'),'plan':str(C/'plan.md'),'input_identities':inputs,'own_output_directory':str(J),'artifact':str(J/'artifact.md'),'source_map':str(J/'source-map.json'),'predecessors':[]};(J/'input-map.json').write_text(json.dumps(m,indent=2)+'\n')
 p=C/'execution-v1.json';p.write_text(json.dumps(card,indent=2)+'\n');p.chmod(0o444);s['cases'][case]={'card':str(p),'status':'locked_prospectively_frozen_no_dispatch','arms':{a:{'status':'ready','stages':{}} for a in roles}};s['ownership']['paths'] += [str(p),str(B/'jobs'/case)];cards.append(ident(p))
s['speed_lock']['inputs_opened']=True;s['speed_lock']['first_input_binding_after_lock_at']=now;s['speed_hold']='All three locked cards prospectively frozen; admission waits started-method stage/review priority and six Luna capacity';s['updated_at']=now;(B/'state/integrated-methods.json').write_text(json.dumps(s,indent=2)+'\n');c=json.loads((B/'helpers/integrated-execution/COMPARISONS.json').read_text());c['speed_lock']=s['speed_lock'];c['speed_hold']=s['speed_hold'];c['speed_cases']=[{'case_id':x['case_id'],'status':'locked_prospectively_frozen_no_dispatch','source_quality':None,'assessed':False} for x in [json.loads(pathlib.Path(p['path']).read_text()) for p in cards]];c['updated_at']=now;(B/'helpers/integrated-execution/COMPARISONS.json').write_text(json.dumps(c,indent=2)+'\n')
with (B/'state/integrated-methods-dispatches.jsonl').open('a') as f:f.write(json.dumps({'event':'locked_speed_pair_cards_frozen','record_at':now,'root_locked_at':lock['locked_at'],'cards':cards,'before_any_speed_dispatch':True,'scientific_scope_change':False})+'\n')
print(json.dumps({'root_locked_at':lock['locked_at'],'input_binding_at':now,'cards':cards,'workers_dispatched':0}))
