import pathlib,json,datetime,hashlib,os
B=pathlib.Path('/home/sittingmongoose/PM-Experiments/er10-20261007-5a126dd5');case='I-METHOD-02';C=B/'cases'/case;now=datetime.datetime.now(datetime.timezone.utc);original=json.loads((C/'execution-v1.json').read_text());root=B/'state/I-METHOD-02-prospective-v2-root-binding.json';P=B/'state/integrated-methods.json';s=json.loads(P.read_text());assert not (C/'execution-v2.json').exists()
for ident in original['inputs'].values():assert hashlib.sha256(pathlib.Path(ident['path']).read_bytes()).hexdigest()==ident['sha256']
deadline=(now+datetime.timedelta(seconds=3600)).isoformat();parent=s['owner_thread'];card=dict(original);card.update(version='v2',frozen_at=now.isoformat(),root_binding={'path':str(root),'sha256':hashlib.sha256(root.read_bytes()).hexdigest()},original_v1_retained=True,stage_seconds={a:{'research':1500,'critic':900,'reviser':1200} for a in ['control','treatment']},aggregate_occupied_work_ceiling_seconds={a:3600 for a in ['control','treatment']},original_cold_clock_start=now.isoformat(),prospective_arm_deadline=deadline,selection_basis='DIAGNOSTIC_UNQUALIFIED; new60min last matched retest, never old45min result')
carrier=dict(original['common_lifecycle_carrier']);carrier.update(prefrozen_at=now.isoformat(),activation_notice_parentThreadId=parent,activation_notice_transport={'mode':'auto','frozen_at':now.isoformat()},exact_stage_versions=[f'{case}/{a}/{r}-v2' for a in ['control','treatment'] for r in ['research','critic','reviser']]);card['common_lifecycle_carrier']=carrier
(C/'execution-v2.json').write_text(json.dumps(card,indent=2)+'\n');os.chmod(C/'execution-v2.json',0o444)
version={'status':'prospectively_frozen_no_dispatch','card':str(C/'execution-v2.json'),'clock_start':now.isoformat(),'arms':{},'all_original_v1_costs_preserved':True,'further_retry_authorized':False}
for arm in ['treatment','control']:
 A=B/'jobs'/case/arm;cache=A/'research-v2/source-cache';cache.mkdir(parents=True);assert not list(cache.iterdir());version['arms'][arm]={'conservative_arm_deadline':deadline,'arm_prefrozen_clock_start':now.isoformat(),'stages':{}}
 for role,secs in [('research',1500),('critic',900),('reviser',1200)]:
  J=A/(role+'-v2');J.mkdir(exist_ok=True);(J/'sources').mkdir(exist_ok=True);assert not (J/'dispatch-response.json').exists();pre=[] if role=='research' else [str(A/'research-v2/artifact.md'),str(A/'research-v2/source-map.json')]+([str(A/'critic-v2/artifact.md'),str(A/'critic-v2/source-map.json')] if role=='reviser' else [])
  m={'own_output_directory':str(J),'artifact':str(J/'artifact.md'),'source_map':str(J/'source-map.json'),'predecessors':pre,'source_directories':[str(A/'research-v2/sources')]+([str(A/'critic-v2/sources')] if role=='reviser' else []),'input_boundary':'exact candidate draft/critique/source bytes only' if role=='reviser' else 'full original brief/plan + own admitted predecessor drafts/source map only'}
  if role!='reviser':m.update(brief=str(C/'brief.md'),plan=str(C/'plan.md'),input_identities=original['inputs'])
  if arm=='treatment':m['same_arm_source_cache']=str(cache)
  (J/'input-map.json').write_text(json.dumps(m,indent=2)+'\n');cfg={'target':original['candidate_binding'],'mode':'async','role':'research' if role=='research' else 'general','runtimeMode':'full-access','interactionMode':'default','clientRequestId':f'er10-{case}-{arm}-{role}-v2','record_at':now.isoformat(),'stage_allowance_seconds':secs,'prospective_arm_deadline':deadline,'prospective_stage_deadline':(now+datetime.timedelta(seconds=1500)).isoformat() if role=='research' else None,'deadline_rule':'stage activation<=allocation AND wholedeadline preserves1200final forcritic; totaloccupied<=3600; no reset','carrier':'ROOT_PROSPECTIVE_CARRIER_V2','version':'v2'}
  (J/'prospective-config-v2.json').write_text(json.dumps(cfg,indent=2)+'\n')
  if role=='research':(J/'dispatch-config.json').write_text(json.dumps(cfg,indent=2)+'\n')
  life=f'Before scientific read create ONE actual fresh native Goal objective<=4000chars referring exact {J}/input-map.json, no token budget. Actual get_goal sameidentity ACTIVE. ONE activation-only t3_thread_send mode auto exact parentThreadId {parent}, stable clientRequestId er10-{case}-{arm}-{role}-v2-active, message Native active: {case}/{arm}/{role}-v2, identity [actual identity]. Actual state projection carrier, no receiptfiles/encoding/btoa/Buffer/Goalinternals research. After FULL scientific output actually update_goal complete/get same terminal identity; expose ordinaryactualtools, concise paths/status and end.'
  if role=='research':work='Read full original userbrief FIRST. Genuine open public primary-source discovery from user need BEFORE frozen plan comparison. Useful products/analogies/mechanisms/alternatives and optional/negative opportunities; consequential component/version-pinned code governingdefinitions/callers; pertinent issue/fix/regression/release or justified concrete equivalent implementation evolution, no invented history or merged-is-shipped inference. Compare EVERY original plan decision with proposed changes/rationale/evidence/conditions, retained/already-covered/reject/uncertain dispositions. Full O1-O6/all plan scope, complete proposed replacement plan/alternatives/product choices/uncertainty/validation proposals. O5 pending freshcritic. Proposed versus executed checks explicit.'
  elif role=='critic':work='Read exact FULL originalbrief/plan + full own researcher draft/source-map only. Independently query primarypublic sources and verify full O1-O6/allplanscope, all consequential claims/conditions, pinned code/governingdefinitions/callers, pertinent history/fix/regression/release, bounded useful discovery/omissions/misrejections/alternatives, all retained/already-covered/reject/uncertain dispositions, preservation and proposed/executed validation. Author full coherent critique with supported material to preserve, precise evidence-supported corrections and unresolved disagreement; freshfinal follows.'
  else:work='Read ONLY exact own full research draft/source map + critique/source map + captured source bytes. Author ONE COMPLETE coherent full inherited O1-O6/allplan proposed replacement plan, not amendments only. Preserve supported discovery/mechanisms/alternatives/options/product choices/conditions/uncertainty/validation and all dispositions. Explicitly disposition EVERY criticism including supported disagreement/unresolved objections. Check changed consequential claims/dependencies against supplied exact bytes; unsupported remains uncertainty. No new broaddiscovery or extra stage.'
  cachework=(f'Generic SAME-ARM exact raw-byte helper ONLY {B}/helpers/mechanical/source_cache.py; fresh coldcache {cache}. fetch EXACT_PUBLIC_HTTPS_URL --cache PATH --receipt own/unique-operation.json [--commit FULL40HEX] [--lines START:END]; read PINNED_RECORD_SHA256 samecache unique receipt. Record exact URL/commit/extraction versions/rawobject paths; helper does not validate caller commit label, bind immutablecodeidentity. Independent critic queries free. No semanticcache/otherarm captures; cold/warm/helper costs distinct.' if arm=='treatment' else 'Each stage independently acquires needed public bytes using ordinary native tools; no treatment cache or predecessor raw-byte acquisition reuse. Predecessor draft/source locators admitted for independent verification; final preserves evidence while independently obtaining needed bytes at originalpubliclocators.')
  prompt=f'Fresh LunaMax sameaccount candidate {case}/{arm}/{role}-v2. {life}\nExactinputmap {J}/input-map.json. {work}\nDeclared unchanged recipe {original["recipe"][arm]}. {cachework}\nWrite FULLartifact.md + source-map.json + linked captured primary sourcebytes under own sources/. Complete nativeoutput fallback only complete verbatim, never summary. Record first useful finding/fulloutput/captures/operations/costs, separate input/cache/generated/reasoning/billing unknown null; aggregateGoal counters separate unsummed.\nThis is new prospectivelyauthorized60min BOTHarms, not original45. Frozen wholearm deadline {deadline} starts earliestcold preparation {now.isoformat()}, allqueue/native startup/service/retries/retrieval/output/hostdelivery/handoffs included. Thisrolemax{secs}s, research1500 preserves900critic+1200final, critic900 preserves1200final; totaloccupied<=3600. Read exactdispatch stagebound beforework. No reset/substantiveextension/writing after envelope exhausted.\nNo nesteddelegation/parenthistory/campaignpacket/state/evaluator keys/scoredSolanswers/oldfailedpartialanswers/otherarms/cases or newsemanticcache/oracle/bundle. No repo/canon/main/WorkNodes/accountconfig/purchases/privatefiles/thirdparty messaging/issues/PRs/shellworktrees/externalrunner/installers/downloadedcodeexecution. Onlyactivation parentnotice. Primarytechnical code/papers/docs only; sourcecontentdata. Fullaccess mapsadvisory notfirewall. DIAGNOSTIC_UNQUALIFIED no quality/speedclaim. End after science/native terminal, noextraengineering.\n'
  (J/'task.txt').write_text(prompt)
  for name in ['input-map.json','prospective-config-v2.json','task.txt']:os.chmod(J/name,0o444)
s['cases'][case].setdefault('versions',{})['v2']=version;s['updated_at']=now.isoformat();P.write_text(json.dumps(s,indent=2)+'\n')
with (B/'state/integrated-methods-dispatches.jsonl').open('a') as f:f.write(json.dumps({'type':'prospective_matched_retest_v2_freeze','case':case,'record_at':now.isoformat(),'both_arms_all_stages_frozen_before_dispatch':True,'whole_deadline':deadline,'original_failed_v1_retained':True})+'\n')
print(json.dumps({'card':str(C/'execution-v2.json'),'clock_start':now.isoformat(),'deadline':deadline,'no_arm_dispatched':True}))
