import pathlib,json,datetime,os,sys
B=pathlib.Path('/home/sittingmongoose/PM-Experiments/er10-20261007-5a126dd5');case='I-METHOD-05';arm,role=sys.argv[1:];C=B/'cases'/case;A=B/'jobs'/case/arm;J=A/(role+'-v1');card=json.loads((C/'execution-v1.json').read_text());P=B/'state/integrated-methods.json';s=json.loads(P.read_text());row=s['cases'][case]['arms'][arm];now=datetime.datetime.now(datetime.timezone.utc);allow=card['stage_seconds'][arm][role];assert not (J/'dispatch-response.json').exists();J.mkdir(parents=True,exist_ok=True);(J/'sources').mkdir(exist_ok=True)
if 'conservative_arm_deadline' not in row:row['conservative_arm_deadline']=(now+datetime.timedelta(seconds=2700)).isoformat();row['arm_prefrozen_clock_start']=now.isoformat()
whole=datetime.datetime.fromisoformat(row['conservative_arm_deadline']);reserve=1500 if role in ['discovery','research-topic-a','research-topic-b'] else 900 if role=='critic' else 0;end=min(now+datetime.timedelta(seconds=allow),whole-datetime.timedelta(seconds=reserve));assert (end-now).total_seconds()>0
occupied=0
for st in row['stages'].values():
 if st.get('actual_requestedAt') and st.get('t3_completedAt'):occupied+=(datetime.datetime.fromisoformat(st['t3_completedAt'].replace('Z','+00:00'))-datetime.datetime.fromisoformat(st['actual_requestedAt'].replace('Z','+00:00'))).total_seconds()
assert occupied+reserve<2700;end=min(end,now+datetime.timedelta(seconds=max(0,2700-occupied-reserve)));assert (end-now).total_seconds()>0
pre=[]
if role.startswith('research-topic') and arm=='treatment':pre=['discovery']
if role in ['critic','reviser']:pre=(['discovery'] if arm=='treatment' else [])+['research-topic-a','research-topic-b']+(['critic'] if role=='reviser' else [])
paths=[str(A/(r+'-v1')/n) for r in pre for n in ['artifact.md','source-map.json']]
for p in paths:assert os.access(p,os.R_OK)
m={'predecessors':paths,'source_directories':[str(A/(r+'-v1')/'sources') for r in pre],'own_output_directory':str(J),'artifact':str(J/'artifact.md'),'source_map':str(J/'source-map.json'),'input_boundary':'exact drafts/inventory/critique/source bytes only' if role=='reviser' else 'full original brief/plan/source copies and exact admitted same-arm predecessor bytes'}
if role!='reviser':m.update(brief=str(C/'brief.md'),plan=str(C/'plan.md'),source_copies=str(C/'source'),input_identities=card['inputs'])
if role.startswith('research-topic'):m['primary_topic_group']=card['topic_subdivision']['contract']['topic_groups'][0 if role.endswith('-a') else 1]
(J/'input-map.json').write_text(json.dumps(m,indent=2)+'\n');cfg={'target':card['candidate_binding'],'mode':'async','role':'research' if role in ['discovery','research-topic-a','research-topic-b'] else 'general','runtimeMode':'full-access','interactionMode':'default','clientRequestId':'er10-'+case+'-'+arm+'-'+role+'-v1','record_at':now.isoformat(),'prospective_stage_deadline':end.isoformat(),'prospective_arm_deadline':whole.isoformat(),'stage_allowance_seconds':allow,'prior_nonoverlapping_occupied_seconds':occupied,'aggregate_ceiling_seconds':2700,'carrier':'ROOT_PROSPECTIVE_CARRIER_V2'};(J/'dispatch-config.json').write_text(json.dumps(cfg,indent=2)+'\n');P.write_text(json.dumps(s,indent=2)+'\n')
life=f'''Before any scientific read create ONE actual fresh native Goal objective<=4000chars referring exact {J}/input-map.json and bounded stage assignment. No token budget. Actual get_goal verifies same native identity active. Send ONE activation-only t3_thread_send to exact parentThreadId {s['owner_thread']}, mode auto, clientRequestId er10-{case}-{arm}-{role}-v1-active, message Native active: {case}/{arm}/{role}-v1, identity [actualidentity]. Host captures actualstate projection, not rawAPIresponse. No receipt files/btoa/Buffer/Goalinternals engineering. After complete scientific output actually update_goal complete and get_goal same terminalidentity, expose actual tool outputs. Return concise paths/status and end.'''
common='''All public technical evidence primary code/papers/docs only; component/version pinned code with governing definitions and callers; pertinent issue->fix->regression->release or justified equivalent implementation history; mechanisms/alternatives, complete own comparison, opportunities/negative findings, retained/already-covered/reject/uncertain dispositions, constraints/conditions/uncertainty and useful validation proposals explicitly separated from executed checks. Preserve exact Rust+Slint product/owner/safety and absent adjacent-owner boundaries. Genuine public discovery beyond frozen plan defects; no exhaustive opportunity recall claim.'''
if role=='discovery':work='Read full original brief first, then perform broad open public source discovery across ALL original obligations and both topic groups; only after discovery compare entire original frozen plan/source copies. Author one useful complete discovery inventory/source map with code/history/mechanisms/alternatives/conditions/unknowns/full comparison that fresh topic researchers can build on. No Sol findings or prescribed scientific defaults. '+common
elif role.startswith('research-topic'):
 group=m['primary_topic_group'];work='Read full original brief and all source copies first. Primary topic ownership is '+json.dumps(group)+'. Preserve full cross-topic interactions/unknowns; topic division does not remove inputs. '+('Independently perform open public discovery beyond plan defects FIRST, then compare frozen plan/topic with conditions.' if arm=='control' else 'Read exact same-arm candidate-authored discovery inventory/source map and bytes; use its reusable evidence, protect independent unknowns, perform any needed public discovery beyond plan defects then compare topic and cross-topic seams; no other-arm source sharing.')+' Produce complete topic draft and exact source map, every relevant original topic decision dispositioned with proposed changes/alternatives/validation, and explicit cross-topic dependencies. '+common
elif role=='critic':work='Read EXACT full original brief/plan/source copies, and full same-arm candidate inventory (if any), both topic drafts and source maps/bytes. Independently query primary sources and verify consequential claims/full union of original O1-O6 and all F/context decisions, cross-topic interactions, source identity, conditions, useful bounded discovery, omitted/misrejected opportunities and preservation. Author ONE complete full-scope critique with every topic/claim material to preserve, precise supported corrections, contradictions/unknowns and dispositions. Fresh same-family final follows; do not rewrite final. '+common
else:work='Read ONLY exact same-arm candidate inventory (if any), BOTH topic drafts/source maps, full critique/source map and exact captured source bytes; NO original campaign inputs or parent/evaluator history. Author ONE COMPLETE coherent full-scope revised proposal, full inherited O1-O6/all F/context scope and cross-topic seams; preserve all supported discovery/mechanisms/alternatives/product choices/options/conditions/unknowns; disposition every criticism including disagreement/unresolved objections and all retained/already-covered/reject/uncertain comparison decisions. Check changed consequential claims/dependencies against exact supplied sources; unsupported remains uncertainty. Proposed validation distinct from executed; no new broad discovery. No mechanical host science synthesis.'
prompt=f'''Fresh LunaMax same-account scientific candidate stage {case}/{arm}/{role}-v1. {life}\nExact readable input/write map: {J}/input-map.json. {work}\nRecipe: {card['recipe'][arm]}. All predecessors: {json.dumps(paths)}. Save full authored artifact.md, source-map.json and evidence under own sources/ in {J}; original inputs unchanged. Complete native full answer may be saved verbatim if complete, never substitute summary. Record first useful saved finding, fullartifact completion, source operations/capture versions/time, distinct unknown usage/billing null.\nProspective fixed stage deadline {end.isoformat()} (allowance<= {allow}s); wholearm original deadline {whole.isoformat()}; total occupiedwork across ALL paralleltopic/discovery/critic/final <=2700s, researchsubdivision1200total then600critic+900final. All queue/native startup/retries/retrieval/output/delivery costs count. No nesteddelegation or other workers; supervisor owns parallelism. Check clock at source transitions, finish comfortably. At expiry lifecycle-only save/deliver<=60s, no substantive extension/writing after exhausted envelope.\nOnly own exact declared inputs/public sources. No otherarm/cases/campaignpacket/state/scoredSolanswer/evaluator keys/parenthistory/oldcase science. No repo/canon/main/WorkNodes changes, accountconfig/purchases/privatefiles/thirdparty messaging/issues/PRs, shellworktrees/externalrunner/installers/downloadedcode execution. No scientific steers, only one activation parent notice. Full-access map advisory notfirewall. Unqualified diagnostic no SourcePASS/speedassumption. End after science/native terminal, no extra engineering.\n''';(J/'task.txt').write_text(prompt);print(json.dumps(cfg))
