import pathlib,json,datetime,hashlib,sys,os
B=pathlib.Path('/home/sittingmongoose/PM-Experiments/er10-20261007-5a126dd5');case=sys.argv[1];assert case in ['I-FAST-02','I-FAST-03'];C=B/'cases'/case;card=json.loads((C/'execution-v1.json').read_text());P=B/'state/integrated-methods.json';s=json.loads(P.read_text());now=datetime.datetime.now(datetime.timezone.utc);assert not list((B/'jobs'/case).glob('*/*/dispatch-response.json'))
for v in card['inputs'].values():assert hashlib.sha256(pathlib.Path(v['path']).read_bytes()).hexdigest()==v['sha256']
assert hashlib.sha256(pathlib.Path(card['prepared_identity']['path']).read_bytes()).hexdigest()==card['prepared_identity']['sha256'];records=[]
for arm,roles in card['stage_seconds'].items():
 A=B/'jobs'/case/arm;whole=(now+datetime.timedelta(seconds=card['aggregate_occupied_work_ceiling_seconds'][arm])).isoformat();row=s['cases'][case]['arms'][arm];assert not row['stages'];row.update(arm_prefrozen_clock_start=now.isoformat(),conservative_arm_deadline=whole)
 for role,allow in roles.items():
  J=A/(role+'-v1');pre=[] if role=='research' else [str(A/'research-v1/artifact.md'),str(A/'research-v1/source-map.json')]+([str(A/'critic-v1/artifact.md'),str(A/'critic-v1/source-map.json')] if role=='reviser' else []);m={'own_output_directory':str(J),'artifact':str(J/'artifact.md'),'source_map':str(J/'source-map.json'),'predecessors':pre,'source_directories':[] if role=='research' else [str(A/'research-v1/sources')]+([str(A/'critic-v1/sources')] if role=='reviser' else []),'input_boundary':'full originalbrief/plan and own researcher draft/source map/bytes, independent primaryqueries' if role in ['critic','critic-finalizer'] else 'exact own draft/critique/sourcebytes only' if role=='reviser' else 'exact full originalbrief/plan; brief-first openpublicdiscovery'}
  if role!='reviser':m.update(brief=str(C/'brief.md'),plan=str(C/'plan.md'),input_identities=card['inputs'])
  for p in [C/'brief.md',C/'plan.md']:assert os.access(p,os.R_OK)
  (J/'input-map.json').write_text(json.dumps(m,indent=2)+'\n');cfg={'frozen_at':now.isoformat(),'case':case,'arm':arm,'role':role,'seconds':allow,'arm_total_seconds':card['aggregate_occupied_work_ceiling_seconds'][arm],'target':card['candidate_binding'],'carrier':card['common_lifecycle_carrier'],'registration_order_policy':str(B/'state/prospective-activation-notice-registration-order-v1.json'),'input_map':str(J/'input-map.json'),'write_scope':str(J),'scientific_scope':card['output_scope'],'role_procedure':card['recipe'][arm],'whole_deadline':whole,'stage_rule':'earliest casejob prep/request throughcoldstartup/queue/sourceoutput/delivery; perstage<=allocation and whole deadline preserves reserves; no reset','candidate_goal_required':True,'before_either_arm_dispatch':True};p=J/'prospective-config-v1.json';assert not p.exists();p.write_text(json.dumps(cfg,indent=2)+'\n');records.append({'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'map_sha256':hashlib.sha256((J/'input-map.json').read_bytes()).hexdigest()})
  if str(J) not in s['ownership']['paths']:s['ownership']['paths'].append(str(J))
freeze={'case':case,'record_at':now.isoformat(),'both_arm_all_stages_maps_configs_policies_frozen':records,'neither_arm_dispatched':True,'root_recipe_unchanged':True,'full_science_unchanged':True,'registered_write_paths':True,'actual_task_ids_registered_immediately_after_dispatch_before_activation_event':True,'research_reserves':'control600critic+900final; treatment600critic-finalizer','no_old_answers_evaluator_facts':True};p=B/'helpers/integrated-execution'/(case.lower()+'-pair-prospective-freeze-v1.json');assert not p.exists();p.write_text(json.dumps(freeze,indent=2)+'\n');p.chmod(0o444);s['cases'][case]['prospective_pair_freeze']=str(p);s['updated_at']=now.isoformat();P.write_text(json.dumps(s,indent=2)+'\n')
with (B/'state/integrated-methods-dispatches.jsonl').open('a') as f:f.write(json.dumps({'type':'locked_speed_pair_all_stage_prefreeze','case':case,'record_at':now.isoformat(),'path':str(p),'no_recipe_budget_scope_change':True})+'\n')
print(json.dumps({'path':str(p),'T0':now.isoformat(),'launch_order':card['launch_order']}))
