/* Astra onboarding. Draft -> review -> one explicit commit -> providers.
 * Browser concept adapters are labelled and never send real owner commands.
 * No credentials, private keys, device codes, or passwords enter persistence.
 */
(() => {
'use strict';
const KEY='pm.astra.onboarding.v3', $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=v=>JSON.parse(JSON.stringify(v));
const paths={
 arrow:'M4 12h16m-6-6 6 6-6 6',back:'M20 12H4m6-6-6 6 6 6',close:'m6 6 12 12M6 18 18 6',check:'m5 12 4 4L19 6',
 computer:'M4 4h16v12H4zM8 21h8m-4-5v5',link:'m10 13 4-4m-7 6-2 2a4 4 0 0 0 6 5l4-4m2-9 2-2a4 4 0 0 0-6-5L9 5',
 folder:'M3 6h6l2 3h10v11H3z',cloud:'M6 18a4 4 0 0 1-1-8 7 7 0 0 1 13-2 5 5 0 0 1 0 10Z',
 restore:'M3 10a9 9 0 1 1 1 8M3 4v6h6m3-3v6l4 2',globe:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M3 12h18M12 3c5 5 5 13 0 18-5-5-5-13 0-18',
 shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Zm-4 9 3 3 5-6',lock:'M5 10h14v11H5zM8 10V6a4 4 0 0 1 8 0v4',
 spark:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z',plus:'M12 5v14M5 12h14',moon:'M20 14A9 9 0 0 1 10 3a9 9 0 1 0 10 11Z',
 sun:'M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1',
 network:'M4 4h16v5H4zM4 15h16v5H4zM7 6.5h.1M7 17.5h.1M12 9v6',book:'M4 4h7l1 2 1-2h7v16h-7l-1 1-1-1H4ZM12 6v15',
 info:'M12 10v7m0-10h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',mail:'M3 5h18v14H3zm0 0 9 8 9-8',user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 21a8 8 0 0 1 16 0',
 key:'M14 5a5 5 0 1 1-2 8l-8 8H2v-3l8-8a5 5 0 0 1 4-5Z',play:'m8 4 12 8-12 8Z',pause:'M8 4v16M16 4v16',copy:'M8 8h13v13H8zM3 16V3h13',
};
const icon=(name)=>`<svg class="as-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.spark}"/></svg>`;
const mark=`<svg viewBox="0 0 28 28" fill="none" aria-hidden="true"><path d="m14 2 3.5 8.5L26 14l-8.5 3.5L14 26l-3.5-8.5L2 14l8.5-3.5Z" stroke="currentColor" stroke-width="1.5"/><path d="m14 9 1.5 3.5L19 14l-3.5 1.5L14 19l-1.5-3.5L9 14l3.5-1.5Z" fill="currentColor"/></svg>`;
const uid=()=>globalThis.crypto?.randomUUID?.()||`astra-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const draft=host=>({id:uid(),kind:'new',name:'',host:host||'local',location:'local',path:'',protocol:'ssh',address:'',username:'',sshReady:false,online:false,forge:'GitHub',account:null,instance:'',repository:'',sourceVerified:false,backup:'',backupVerified:false,inherit:'fresh',groups:['Appearance','Assistant preferences','Permissions'],remote:'later'});
const defaults=()=>({version:3,stage:'welcome',trail:[],theme:'friendly-light',motion:true,open:true,started:false,draft:draft(),projects:[],committed:null,accounts:[],fixtures:{returning:false,host:'local',free:false},joined:null,completed:false,tour:null});
let savedFocus=null,initialDemoPlaying=null;
let S=defaults(),root,main,viewport,world,caption,stageNode,footer,launcher,generation=0,busy=false,sheet=null,error='',editReturn=false,storeAvailable=true,discoveryCache={},motionStamp=0;
try{const v=JSON.parse(localStorage.getItem(KEY));if(v?.version===3)S={...defaults(),...v};}catch(e){storeAvailable=false;}
const events=[],faults={},pendingTimers=new Set();
const emit=(action,status='applied',extra={})=>{const row={id:uid(),at:new Date().toISOString(),action,status,concept_simulation_only:true,productionMutationDispatched:false,...extra};events.push(row);if(events.length>500)events.shift();window.dispatchEvent(new CustomEvent('astra:change',{detail:row}));return row;};
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(S));storeAvailable=true;}catch(e){storeAvailable=false;}};
const later=(fn,ms)=>{const id=setTimeout(()=>{pendingTimers.delete(id);fn();},ms);pendingTimers.add(id);return id;};
const reduced=()=>!S.motion||matchMedia('(prefers-reduced-motion: reduce)').matches;
const button=(label,action,style='as-primary',attrs='')=>`<button type="button" class="${style}" data-as="${action}" ${attrs}>${label}</button>`;
const choice=(title,copy,ic,action,value,selected=false,compact=false)=>`<button type="button" class="as-choice${compact?' as-compact':''}" data-as="${action}" data-value="${esc(value)}" ${selected?'aria-pressed="true"':''}><span class="as-choice-icon">${icon(ic)}</span><span><strong>${title}</strong>${copy?`<small>${copy}</small>`:''}</span><span class="as-arrow">${selected?'✓':'↗'}</span></button>`;
const field=(label,id,value='',placeholder='',type='text',extra='')=>`<label class="as-field">${label}<input id="${id}" data-field="${id}" type="${type}" value="${esc(value)}" placeholder="${esc(placeholder)}" ${extra}></label>`;
const note=t=>`<div class="as-note">${t}</div>`;
const select=(label,id,options,value)=>`<label class="as-field">${label}<select id="${id}" data-field="${id}">${options.map(v=>`<option${v===value?' selected':''}>${esc(v)}</option>`).join('')}</select></label>`;
const headline=(eyebrow,title,copy='')=>`<header><p class="as-eyebrow">${eyebrow}</p><h1 class="as-heading" id="as-title">${title}</h1>${copy?`<p class="as-copy">${copy}</p>`:''}</header>`;
const forges={GitHub:{sign:'https://github.com/login',join:'https://github.com/signup'},GitLab:{sign:'https://gitlab.com/users/sign_in',join:'https://gitlab.com/users/sign_up'},Bitbucket:{sign:'https://bitbucket.org/account/signin/',join:'https://bitbucket.org/account/signup/'},'Cursor Origin':{sign:'https://cursor.com/dashboard',join:'https://cursor.com/signup'},Gitea:{self:true},Forgejo:{self:true}};
const providers=[
{id:'cursor',name:'Cursor',detail:'Your Cursor account',monogram:'C',kind:'key',link:'https://cursor.com/dashboard',installed:true},
{id:'claude',name:'Claude',detail:'Pro or Max subscription',monogram:'✳',kind:'signin',cli:'Claude Code',installed:false,link:'https://claude.ai/login'},
{id:'antigravity',name:'Antigravity',detail:'Your Google account',monogram:'A',kind:'signin',cli:'Antigravity',installed:true,link:'https://antigravity.google/'},
{id:'qwen',name:'Qwen',detail:'Coding plan',monogram:'Q',kind:'key',link:'https://www.alibabacloud.com/',installed:true},
{id:'anthropic-api',name:'Anthropic API',detail:'Pay per use · separate billing',monogram:'A',kind:'key',link:'https://console.anthropic.com/',installed:true},
{id:'gemini',name:'Gemini API',detail:'API key · free tier available',monogram:'G',kind:'key',link:'https://aistudio.google.com/apikey',installed:true},
{id:'vertex',name:'Vertex AI',detail:'Your Google Cloud project',monogram:'V',kind:'key',link:'https://console.cloud.google.com/',installed:true},
{id:'grok',name:'Grok Build',detail:'Build subscription',monogram:'G',kind:'signin',cli:'Grok Build',installed:false,link:'https://grok.com/'},
{id:'xai',name:'xAI API',detail:'Pay per use · separate billing',monogram:'X',kind:'key',link:'https://console.x.ai/',installed:true},
{id:'zai',name:'Z.AI',detail:'Coding plan',monogram:'Z',kind:'key',link:'https://z.ai/',installed:true},
{id:'kimi',name:'Kimi',detail:'Coding plan',monogram:'K',kind:'key',link:'https://www.kimi.com/',installed:true},
{id:'opencode',name:'OpenCode Go',detail:'Go subscription',monogram:'O',kind:'key',link:'https://opencode.ai/auth',installed:true},
{id:'opencode-zen',name:'OpenCode Zen',detail:'Pay per use · separate billing',monogram:'O',kind:'key',link:'https://opencode.ai/auth',installed:true},
{id:'opencode-runtime',name:'OpenCode runtime',detail:'Optional external runtime',monogram:'O',kind:'signin',cli:'OpenCode',installed:false,link:'https://opencode.ai/'},
{id:'muse',name:'Muse Code',detail:'Coding subscription',monogram:'M',kind:'signin',cli:'Muse Code',installed:false,link:null},
{id:'meta',name:'Meta API',detail:'Your API access',monogram:'M',kind:'key',link:'https://www.meta.ai/',installed:true},
];
const chapter=()=>['welcome'].includes(S.stage)?0:['start','connect','connected','server'].includes(S.stage)?1:['kind','project','inherit','storage','ssh','source','import','restore'].includes(S.stage)?2:['review','committing'].includes(S.stage)?3:['providers','free'].includes(S.stage)?4:5;
function applyTheme(t,animate=true){
 if(!/^(friendly|glass|retro|basic)-(light|dark)$/.test(t))return;
 S.theme=t;const [family,mode]=t.split('-');
 if(root)root.dataset.astraTheme=t;
 // Local preview is the draft; the existing theme owner applies on exit.
 if(!root||!S.open||!animate){if(window.PM_THEME){PM_THEME.set(t,{dispatch:false,persist:false});}else document.documentElement.dataset.theme=t;}
 document.documentElement.dataset.astraMotion=S.motion?'on':'off';
 if(world){const old=world.querySelector('.as-world-layer'),node=document.createElement('div');node.className='as-world-layer';node.innerHTML=ASTRA_ART.render(t);world.prepend(node);const stamp=++motionStamp;
   if(animate&&!reduced()&&old){node.animate([{opacity:0,transform:'scale(1.045) translateX(10px)'},{opacity:1,transform:'scale(1) translateX(0)'}],{duration:980,easing:'cubic-bezier(.22,1,.36,1)'});old.animate([{opacity:1,transform:'scale(1)'},{opacity:0,transform:'scale(.975) translateX(-6px)'}],{duration:730,easing:'ease-in-out'}).finished.catch(()=>{}).then(()=>old.remove());}
   else old?.remove();
   for(const extra of [...world.querySelectorAll('.as-world-layer')].slice(2))extra.remove();
 }
 if(root)for(const b of root.querySelectorAll('[data-as="theme"]')){if(b.dataset.themeFamily){b.dataset.value=b.dataset.themeFamily+'-'+mode;b.setAttribute('aria-pressed',String(b.dataset.themeFamily===family));}else{const m=b.dataset.value.split('-')[1];b.dataset.value=family+'-'+m;b.setAttribute('aria-pressed',String(m===mode));}}
 save();
}
function themes(){const family=S.theme.split('-')[0],mode=S.theme.split('-')[1];return `<div class="as-theme-grid">${['friendly','glass','retro','basic'].map(f=>`<button type="button" class="as-theme" data-as="theme" data-theme-family="${f}" data-value="${f}-${mode}" aria-pressed="${family===f}"><span class="as-theme-art"></span>${f[0].toUpperCase()+f.slice(1)}</button>`).join('')}</div><div class="as-appearance"><span>Make yourself at home.</span><div class="as-segmented" aria-label="Brightness">${['light','dark'].map(m=>button(m[0].toUpperCase()+m.slice(1),'theme','',`data-value="${family}-${m}" aria-pressed="${mode===m}"`)).join('')}</div></div>`;}
function nextStage(stage,push=true){
 if(busy)return;pullFields();if(push&&S.stage!==stage)S.trail.push(S.stage);S.stage=stage;S.open=true;error='';sheet=null;generation++;save();render(true);
}
function back(){if(busy)return;if(sheet){sheet=null;renderSheet();return;}pullFields();const prev=S.trail.pop();if(prev){S.stage=prev;error='';generation++;save();render(true,-1);}}
function nextFromProject(){pullFields();if(!S.draft.name.trim())return fail('Give your project a name first.');if(S.draft.kind==='existing')return nextStage('import');if(S.draft.kind==='restore')return nextStage('restore');if(S.projects.length||S.fixtures.returning)return nextStage('inherit');nextStage('storage');}
function finishEdit(next){if(editReturn){editReturn=false;nextStage('review');}else nextStage(next);}
const projectLabel=()=>S.draft.name.trim()||'My first project';
const hostLabel=()=>S.draft.host==='local'?'This computer':S.joined?.name||'My Puppet Master';
const pathLabel=()=>S.draft.path||(S.draft.location==='network'?'Choose a network folder':`Projects / ${projectLabel()}`);
function pullFields(){if(!root)return;root.querySelectorAll('[data-field]').forEach(el=>{const map={name:'name',path:'path',address:'address',username:'username',protocol:'protocol',instance:'instance',repository:'repository',backup:'backup'};const k=map[el.dataset.field];if(k){const value=el.value.trim();if(k==='protocol')S.draft[k]=value.toLowerCase().split(' ')[0];else S.draft[k]=value;}});save();}
function fail(message){error=message;render(false);$('#as-error')?.focus();emit('ui.onboarding.validation','blocked',{reason:message});}
function bodyFor(){const d=S.draft;switch(S.stage){
case 'welcome':return headline('A space for your ideas','A little setup.<br>A world of possibility.','You bring the idea. Puppet Master helps you make it real.')+`<div class="as-body">${themes()}</div>`;
case 'start':return headline('Your starting point','Where will you<br>make things?','Start here, or join a Puppet Master you already use.')+`<div class="as-choices">${choice('On this computer','The simplest way to begin.','computer','local','local')}${choice('Connect this device','Your projects are on another computer.','link','connect','connect')}</div>`+button('Set up a new always-on computer','server','as-text-btn');
case 'connect':return headline('Bring your workspace with you','Find your<br>Puppet Master.','Use a connection link or a pairing code from your other device.')+`<div class="as-body">${field('Connection link or pairing code','connectAddress','','Paste a link or enter a code')}${button(icon('network')+' Find on this network','discover','as-secondary')}${note('On your other device: <strong>Settings → Devices → Pair a device.</strong>')}</div>`;
case 'connected':return headline('Connected · sample workspace','This device is ready<br>to meet your Puppet Master.','Choose a project, or give your next idea a home.')+`<div class="as-body"><div class="as-status">${esc(S.joined?.name||'My Puppet Master')} · ready</div>${choice('Create a new project','Use this connected computer.','plus','kind','new')}${choice('Open a project','Continue something you already started.','folder','open-existing','sample')}${button('Use a different computer','start','as-text-btn')}</div>`;
case 'server':return headline('An always-on home','Keep work going.<br>Even when you leave.','Set up Puppet Master on a computer that stays on.')+`<div class="as-body">${select('Where will Puppet Master run?','serverType',['Another computer','Docker / NAS'], 'Another computer')}${note('Install Puppet Master there, then connect this device. Advanced network choices stay in Settings.')}${button('Open installation instructions','server-help','as-secondary')}${button('Preview a ready computer','server-preview','as-text-btn')}</div>`;
case 'kind':return headline('A home for your idea','What would you<br>like to start with?')+`<div class="as-choices">${choice('A new project','An idea, a website, an app. Anything.','spark','kind','new')}${choice('A project I already have','From a folder or an online service.','folder','kind','existing')}${choice('A backup','Pick up where you left off.','restore','kind','restore',false,true)}</div>`;
case 'project':return headline(d.kind==='new'?'Your new project':d.kind==='restore'?'Restore your work':'Bring your work','Every idea starts<br>with a name.','A project keeps everything you are making together.')+`<div class="as-body">${field('Project name','name',d.name,'For example, Neighborhood book club','text','maxlength="80" autocomplete="off"')}${note(`Work happens on <strong>${esc(hostLabel())}</strong>.`)}${button('Change computer','edit-host','as-text-btn')}</div>`;
case 'inherit':return headline('A familiar starting point','Start fresh.<br>Or bring your preferences.','Your files and conversations are never copied here.')+`<div class="as-body">${choice('Start fresh','Use the recommended settings.','spark','inherit','fresh',d.inherit==='fresh')}${choice('Copy project preferences','Choose what to bring with you.','copy','inherit','copy',d.inherit!=='fresh')}${d.inherit!=='fresh'?`<label class="as-field">From project<select data-as="inherit-project">${transferSources().map(p=>`<option value="${esc(p.value)}" ${d.inherit===p.value?'selected':''}>${esc(p.label)}</option>`).join('')}</select></label><div class="as-tags">${d.groups.map(g=>`<span>${esc(g)}</span>`).join('')}</div>${button('Review what is copied','copy-settings','as-text-btn')}`:''}</div>`;
case 'storage':return headline('Where your files live','Keep it close.<br>Or keep it elsewhere.','Puppet Master remembers your work. You choose where it lives.')+`<div class="as-body">${choice('On this computer',S.draft.host==='local'?'A folder in your Projects folder.':'A folder on your connected computer.','folder','location','local',d.location==='local')}${choice('Network storage or NAS','A folder on another device.','network','location','network',d.location==='network')}${d.location==='local'?`${field('Folder','path',d.path,`Projects / ${projectLabel()}`)}<p class="as-fine">The new folder is created only after you confirm.</p>`:''}</div>`;
case 'ssh':return headline('Network storage','Let’s find<br>your folder.','SSH makes a secure connection to your storage device.')+`<div class="as-body">${select('Connection method','protocol',['SSH (recommended)','NFS','SMB'],d.protocol==='ssh'?'SSH (recommended)':d.protocol.toUpperCase())}${d.protocol==='ssh'?`${field('Storage address','address',d.address,'nas.local')}<div class="as-two-fields">${field('Username','username',d.username,'Your NAS username')}${field('Folder','path',d.path,'/projects')}</div>${button(d.sshReady?'Connection checked · sample':'Help me connect','ssh-help','as-secondary')}`:`${field('Mounted folder','path',d.path,'Choose an already mounted share')}${note('Connect the share in your computer’s file manager first. Work still runs on your chosen computer.')}`}</div>`;
case 'source':return headline('Your safety net','Your work.<br>With an undo button.','Local history keeps earlier versions so you can go back.')+`<div class="as-body">${choice('Keep it on my computer','Local history is included. No account needed.','shield','online','no',!d.online)}${choice('Also keep a copy online','Useful for sharing or an extra copy.','globe','online','yes',d.online)}${d.online?`${select('Online service','forge',Object.keys(forges),d.forge)}${forges[d.forge]?.self?field('Your service address','instance',d.instance,'https://code.example.com'):''}<div class="as-option-row">${d.account?`<span class="as-status">${esc(d.account.label)} · sample</span>${button('Change account','forge-auth','as-text-btn')}`:button('Sign In / Create Account','forge-auth','as-secondary')}</div>`:''}</div>`;
case 'import':return headline('Use an existing project','Bring your work.<br>Keep its history.','Nothing is copied or opened until you confirm.')+`<div class="as-body">${select('Where is the project?','importType',['A folder on this computer','An online service'],d.online?'An online service':'A folder on this computer')}${d.online?`${select('Online service','forge',Object.keys(forges),d.forge)}${forges[d.forge]?.self?field('Your service address','instance',d.instance,'https://code.example.com'):''}${d.account?`<div class="as-status">${esc(d.account.label)} · sample</div>${field('Repository or project URL','repository',d.repository,'Choose or paste a project URL')}${button('Browse sample projects','browse-repos','as-text-btn')}`:button('Sign In / Create Account','forge-auth','as-secondary')}`:field('Existing folder','path',d.path,'Choose or enter a folder path')}${button(d.sourceVerified?'Source checked · sample':'Check source','check-source','as-secondary')}</div>`;
case 'restore':return headline('Your saved work','A fresh start.<br>Nothing left behind.','Select a Puppet Master backup to preview its contents.')+`<div class="as-body">${field('Backup location','backup',d.backup,'Choose a local file or connected storage')}${button('Browse sample backups','browse-backups','as-secondary')}${d.backupVerified?note('<strong>Backup checked · sample</strong><br>Project files, conversations, preferences, and history. Any missing accounts can be reconnected next.'):''}</div>`;
case 'review':{const verb=d.kind==='new'?'create':d.kind==='restore'?'restore':'add';return headline('One last look',`Ready to ${verb}<br>your project?`,'Check the choices below. Nothing has been created yet.')+`<div class="as-body"><dl class="as-summary">${[['Project',projectLabel(),'project'],['Computer',hostLabel(),'start'],['Files',d.kind==='restore'?d.backup:pathLabel(),d.kind==='existing'?'import':d.kind==='restore'?'restore':'storage'],['Safety net',d.online?`Local history + ${d.forge}`:'Local history',d.kind==='new'?'source':'import'],...(d.inherit!=='fresh'?[['Preferences','Selected project settings','inherit']]:[])].map(r=>`<div><dt>${r[0]}</dt><dd>${esc(r[1])}</dd><button type="button" data-as="edit" data-value="${r[2]}">Edit</button></div>`).join('')}</dl>${d.online?note(`Your ${esc(d.forge)} account is prepared. The ${d.kind==='existing'?'project copy':'online project'} is created only when you confirm.`):note('This creates your project. It does <strong>not</strong> start AI work.')}</div>`;}
case 'committing':return headline('Making a home','Putting everything<br>in its place.')+`<div class="as-loading"><span class="as-spinner"></span>Preparing your sample project…</div>`;
case 'providers':return (S.committed?.transfer&&!S.committed.transfer.ok?note('Your project is ready, but those preferences could not be copied. They can be reviewed in Settings → Settings Transfer.'):S.committed?.transfer?.ok?'<div class="as-status">Preferences copied · '+S.committed.transfer.count+' values · sample</div>':'')+headline('Your project is ready','Choose your<br>AI partner.','Use an account or plan you already have. You can add more later.')+`<div class="as-body">${S.accounts.length?`<div class="as-status">${S.accounts.length} account${S.accounts.length===1?'':'s'} ready · sample</div>`:''}<div class="as-provider-grid">${providers.slice(0,4).map(providerCard).join('')}</div>${button('See all accounts & plans','all-providers','as-text-btn')}${S.accounts.length?button('Add another account','all-providers','as-text-btn'):''}</div>`;
case 'free':return headline('A little room to explore','Try free models,<br>too.','Optional. Free tiers have their own limits and may change.')+`<div class="as-body">${choice('Set Up Free Models','Use eligible models from your connected accounts.','spark','free-setup','free')}${S.fixtures.free?`<div class="as-status">Free-model preferences saved · sample</div>`:''}${note('Free models remain part of their original provider accounts. No extra “Free Models” account is created.')}</div>`;
case 'finish':return `<div class="as-ready-symbol">${icon('check')}</div>`+headline('You are ready',`${esc(S.committed?.name||'Your workspace')}<br>starts here.`,'Let’s turn an idea into a plan. You decide when anything gets built.')+`<div class="as-body">${choice('Take a hands-on tour','Meet Teacher, arrange your space, make a plan.','book','tour','tour')}${button('Go straight to my project','finish','as-text-btn')}</div>`;
default:return headline('Welcome back','Pick up where<br>you left off.')+button('Continue setup','start');
}}
function providerCard(p){const ready=S.accounts.some(a=>a.provider===p.id&&a.host===S.draft.host);return `<button type="button" class="as-provider" data-as="provider" data-value="${p.id}"><span class="as-monogram">${p.id==='claude'?icon('spark'):p.monogram}</span><strong>${p.name}</strong><small>${ready?'Ready · sample':p.detail}</small></button>`;}
function footerAction(){switch(S.stage){
case 'welcome':return ['Make it mine '+icon('arrow'),'start'];
case 'start':case 'kind':case 'connected':case 'server':case 'finish':return null;
case 'connect':return ['Connect device '+icon('arrow'),'pair'];
case 'project':return ['Continue '+icon('arrow'),'project-next'];
case 'inherit':return ['Continue '+icon('arrow'),'inherit-next'];
case 'storage':return ['Continue '+icon('arrow'),'storage-next'];
case 'ssh':return ['Continue '+icon('arrow'),'ssh-next'];
case 'source':return ['Review project '+icon('arrow'),'source-next'];
case 'import':case 'restore':return ['Review project '+icon('arrow'),'import-next'];
case 'review':return [(S.draft.kind==='new'?'Create Project':S.draft.kind==='restore'?'Restore Project':'Add Project')+' '+icon('arrow'),'commit'];
case 'providers':return [S.accounts.length?'Continue '+icon('arrow'):'Skip for now '+icon('arrow'),'providers-next'];
case 'free':return ['Continue '+icon('arrow'),'free-next'];
default:return null;
}}
const captions={welcome:['A WORLD OF YOUR OWN','Small beginnings.<br>Extraordinary possibilities.'],start:['ONE CONNECTED WORKSPACE','Your ideas.<br>Wherever you are.'],connect:['PICK UP THE THREAD','A familiar space.<br>A different device.'],connected:['WELCOME BACK','Right where<br>you belong.'],server:['MADE TO KEEP GOING','A home that stays<br>with your work.'],kind:['BEGIN ANYWHERE','Something new.<br>Something yours.'],project:['THE FIRST CHAPTER','Give your idea<br>a place to grow.'],inherit:['BRING THE GOOD PARTS','Familiar comforts.<br>Fresh possibilities.'],storage:['A PLACE TO KEEP IT','Everything you make.<br>Somewhere you trust.'],ssh:['CLOSER THAN IT SEEMS','A secure path<br>to your work.'],source:['ROOM TO EXPERIMENT','Try things.<br>You can always go back.'],import:['A NEW CHAPTER','Your work comes<br>with you.'],restore:['NOTHING LOST','Pick up<br>the possibility.'],review:['READY WHEN YOU ARE','Your choices.<br>Your next chapter.'],committing:['MAKING A HOME','A place<br>for possibility.'],providers:['A LITTLE HELP','Your imagination.<br>A capable partner.'],free:['ROOM TO PLAY','Explore<br>what is possible.'],finish:['THIS IS THE BEGINNING','From “what if”<br>to what’s next.']};
function render(animate=false,direction=1){
 if(!root)return;root.hidden=!S.open;root.dataset.open=String(S.open);launcher.hidden=S.open;document.documentElement.dataset.astraOnboarding=String(S.open);
 const html=bodyFor();const node=document.createElement('div');node.className='as-content';node.dataset.stage=S.stage;node.innerHTML=html+(error?`<div id="as-error" class="as-error" tabindex="-1">${icon('info')}<span>${esc(error)}</span></div>`:'');
 const old=stageNode;stageNode=node;viewport.replaceChildren(node);
 if(animate&&!reduced()){node.animate([{opacity:0,transform:`translateY(${direction*15}px)`},{opacity:1,transform:'translateY(0)'}],{duration:440,easing:'cubic-bezier(.22,1,.36,1)'});}
 viewport.scrollTop=0;
 const cp=captions[S.stage]||captions.welcome;caption.innerHTML=`<span>${cp[0]}</span><strong>${cp[1]}</strong>`;
 const fa=footerAction();footer.innerHTML=`${button(icon('back'),'back','as-back',`aria-label="Back" ${S.trail.length&&!busy?'':'disabled'}`)}<div class="as-progress" aria-label="Setup stage ${chapter()+1} of 6">${Array.from({length:6},(_,i)=>`<i class="${i===chapter()?'active':i<chapter()?'done':''}"></i>`).join('')}</div>${fa?button(fa[0],fa[1],'as-primary',busy?'disabled':''):'<span></span>'}`;
 root.querySelector('[data-as="close"]').disabled=busy;
 root.querySelector('[data-as="motion"]').innerHTML=icon(S.motion?'pause':'play');root.querySelector('[data-as="motion"]').title=S.motion?'Pause decorative motion':'Play decorative motion';
 renderSheet();save();if(S.open&&!root.contains(document.activeElement)){const focus=root.querySelector('.as-sheet button')||stageNode.querySelector('input,select,textarea')||footer.querySelector('.as-primary')||root.querySelector('button');focus?.focus({preventScroll:true});}
}
function sheetShell(label,title,body,actions=''){return `<section class="as-sheet" role="dialog" aria-modal="true" aria-label="${esc(label)}"><header><span>${label}</span>${button(icon('close'),'sheet-close','as-icon-btn','aria-label="Close details"')}</header><h2>${title}</h2>${body}<div class="as-sheet-footer">${actions}</div></section>`;}
function authLinks(forge){const f=forges[forge];if(f?.self){let url;try{url=new URL(S.draft.instance);if(url.protocol!=='https:')throw Error();}catch(e){return note('Enter your service’s HTTPS address first.');}return `<div class="as-option-row"><a class="as-link" href="${esc(url.origin+'/user/login')}" target="_blank" rel="noopener noreferrer">Sign In</a><a class="as-link" href="${esc(url.origin+'/user/sign_up')}" target="_blank" rel="noopener noreferrer">Create an account</a></div>`;}return `<div class="as-option-row"><a class="as-link" href="${f.sign}" target="_blank" rel="noopener noreferrer">Sign In</a><a class="as-link" href="${f.join}" target="_blank" rel="noopener noreferrer">Create an account</a></div>`;}
function renderSheet(){main?.querySelector('.as-sheet')?.remove();if(!sheet)return;let html='';const d=S.draft;
 switch(sheet.type){
 case 'preview':html=sheetShell('About this concept','A real flow.<br>A safe preview.',`<p>Astra is an interactive design study built on the Puppet Master concept. Project creation, sign-in, device discovery, installations, and storage checks use labelled samples.</p>${note('No real account is connected. No files, repositories, or paid work are created. Never enter a real password or API key here.')}<p>${storeAvailable?'Choices are saved in this browser.':'Browser storage is unavailable here. Choices last for this tab only.'}</p><div class="as-option-row">${button('First-time user','profile-new','as-secondary')}${button('Returning user','profile-returning','as-secondary')}</div>`,button('Back to setup','sheet-close'));break;
 case 'appearance':html=sheetShell('Your surroundings','Make it<br>feel like yours.',themes(),button('Keep this look','sheet-close'));break;
 case 'discover':html=sheetShell('Nearby devices','Choose your<br>Puppet Master.',`<p>Discovery is scoped to this network and runs only when requested.</p>${choice('Studio computer','Puppet Master · sample device','computer','join','Studio computer')}${choice('Home server','Puppet Master · sample device','network','join','Home server')}`,button('Enter a link instead','sheet-close','as-secondary'));break;
 case 'pair':html=sheetShell('Confirm this device','Make sure<br>it is really yours.',`<p>The other computer must approve this request before your projects are shared.</p><div class="as-pair-code">ASTRA · 204</div><p class="as-fine">Demonstration code · not a working pairing secret</p>${note('Compare the name and code on both devices. A matching name alone is not proof.')}`,button('Approve sample pairing','pair-approve')+button('Cancel','sheet-close','as-secondary'));break;
 case 'server-ready':html=sheetShell('Your new computer','Ready to connect<br>another device.',`<div class="as-status">Studio computer · sample installation</div><div class="as-pair-code">ASTRA · 204</div><p class="as-fine">Demonstration pairing code. Production codes are short-lived and approved on this computer.</p>${note('On the other device, choose <strong>Connect this device</strong> and enter the code.')}<p>Private remote access can be added in Settings. No public port is opened by setup.</p>`,button('Create a project here','server-continue'));break;
 case 'server-help':html=sheetShell('Installation','A few steps<br>on the other computer.',`<p>Install the official Puppet Master app or container on that computer. Open it once, then choose Pair a device.</p>${note('This preview does not install software or grant remote access. Existing VPN connections can be used; Internet access is configured separately.')}`,button('Preview the ready screen','server-preview')+button('Back','sheet-close','as-secondary'));break;
 case 'forge-auth':html=sheetShell(d.forge+' account','Your account first.<br>Your project later.',`<p>Sign in or create an account with ${esc(d.forge)}. Return here when you are done.</p>${authLinks(d.forge)}${note('The browser preview cannot receive a real sign-in. Use the sample below to explore the next step.')}<p>No online repository is created at sign-in.</p>`,button('Use a sample sign-in','forge-sample')+button('Back','sheet-close','as-secondary'));break;
 case 'copy':html=sheetShell('Settings Transfer','Only bring<br>what helps.',`<p>Preview the groups before the final project confirmation. Account credentials are never duplicated.</p><div class="as-body">${['Appearance','Assistant preferences','Permissions','Tools','Provider account references'].map(g=>`<label class="as-check-row"><input type="checkbox" data-group="${esc(g)}" ${d.groups.includes(g)?'checked':''}>${esc(g)}</label>`).join('')}</div>${note('Copied references that need permission or sign-in are shown after creation. Your current setup choices win over copied defaults.')}`,button('Keep these groups','copy-done'));break;
 case 'ssh':html=sheetShell('Secure connection','We’ll handle<br>the fiddly parts.',`<p>Reuse a saved SSH connection or let Puppet Master prepare a dedicated key after your approval.</p>${note('First, SSH must be enabled on your storage device. A new or changed device identity still needs your attention.')}<div class="as-choices">${choice('Use an existing connection','A saved host and approved key.','key','ssh-saved','saved',false,true)}${choice('Set up a new connection','Confirm the device, then approve a key.','plus','ssh-new','new',false,true)}</div>`,button('Back','sheet-close','as-secondary'));break;
 case 'ssh-fingerprint':html=sheetShell('Confirm your storage device','The right folder.<br>The right device.',`<p>Compare this identity with the one shown by your storage device’s administrator.</p><div class="as-fingerprint">${esc(d.address||'nas.local')}<br>ED25519 · sample fingerprint<br>SHA256:ASTRA-SAMPLE-DO-NOT-TRUST-AS-REAL</div><label class="as-check-row"><input type="checkbox" id="as-trust">I have checked the identity on the other device.</label>${note('Puppet Master will not ignore a changed host key. Your private key stays on the computer doing the work.')}`,button('Confirm & prepare sample key','ssh-trust')+button('Back','ssh-help','as-secondary'));break;
 case 'ssh-key':html=sheetShell('One-time approval','Give this computer<br>a key of its own.',`<p>In the real app, sign in once through a protected prompt to add only the new public key. The password is not saved.</p>${note('When password access is disabled, an administrator must add the public key instead. No SSH service or firewall setting is silently changed.')}`,button('Approve sample key setup','ssh-ready')+button('I need an administrator','ssh-admin','as-secondary'));break;
 case 'ssh-admin':html=sheetShell('Administrator help','A small handoff.<br>Then you are connected.',`<p>Ask the administrator to enable SSH for your account, check the device fingerprint, and add your dedicated public key.</p><div class="as-fingerprint">Example only — this is not a usable SSH key.</div>${note('Then return to “Help me connect” and use the existing connection. You can also choose a local folder now.')}`,button('Use a local folder instead','storage-local')+button('Back','ssh-help','as-secondary'));break;
 case 'repos':html=sheetShell('Your online projects','Pick up<br>an existing idea.',`${choice('Neighborhood book club','Private · sample repository','book','repo-select','book-club')}${choice('Family recipes','Private · sample repository','folder','repo-select','family-recipes')}`,button('Back','sheet-close','as-secondary'));break;
 case 'backups':html=sheetShell('Available backups','Find your<br>last saved chapter.',`${choice('Neighborhood book club','Yesterday · encrypted · sample','restore','backup-select','book-club.pmbackup')}${choice('Family recipes','Last week · sample','restore','backup-select','family-recipes.pmbackup')}`,button('Back','sheet-close','as-secondary'));break;
 case 'backup-key':html=sheetShell('Encrypted backup','Unlock the backup<br>to inspect it.',`<p>The original recovery key is needed. It is never copied into project settings.</p>${field('Sample recovery key','recovery','','demo-recovery-key','password')}${note('Use “demo-recovery-key” in this preview. Never enter a real recovery key.')}`,button('Inspect sample backup','backup-unlock'));break;
 case 'all-providers':html=sheetShell('Accounts & plans','A partner<br>for every kind of idea.',`<div class="as-provider-grid">${providers.map(providerCard).join('')}</div>`,button('Back','sheet-close','as-secondary'));break;
 case 'provider':case 'provider-new':{const p=providers.find(p=>p.id===sheet.id);const cached=discoverProvider(p);if(sheet.type!=='provider-new'&&S.accounts.some(a=>a.provider===p.id&&a.ready&&a.host===S.draft.host)){html=sheetShell(p.name,'Ready when<br>you are.',`<div class="as-status">${esc(p.name)} · sample account ready</div><p>Already verified on ${esc(hostLabel())}. There is no second connection step.</p>`,button('Continue','provider-done')+button('Add another '+p.name+' account','provider-another','as-secondary','data-value="'+p.id+'"'));break;}html=sheetShell(p.name,p.name+'<br>on '+esc(hostLabel())+'.',`<p>${p.detail}</p>${S.accounts.some(a=>a.provider===p.id&&a.host===S.draft.host)?'<div class="as-status">An account is already ready · sample</div>':''}${p.cli&&!cached.installed?`${note(`${p.cli} is not installed on <strong>${esc(hostLabel())}</strong>. Installing and signing in are separate steps.`)}<label class="as-check-row"><input id="as-install-consent" type="checkbox">Install ${p.cli} from its official provider on this computer.</label><p class="as-fine">Preview only. Nothing is downloaded or installed.</p>`:p.kind==='key'?`${field('Sample API key','sample-key','','demo-key','password','autocomplete="off"')}${note('Use “demo-key” for this preview. Real keys belong in the protected credential store, not in a concept page.')}<a class="as-link" href="${p.link}" target="_blank" rel="noopener noreferrer">Get a key from ${p.name}</a>`:`<p>Continue with your existing account. Signing into an additional account does not sign out your other accounts.</p>${p.link?`<a class="as-link" href="${p.link}" target="_blank" rel="noopener noreferrer">Sign In with ${p.name}</a>`:`<p>Production sign-in opens the configured official provider flow.</p>`}${note('After real sign-in, readiness updates automatically. The preview uses a sample account.')}`}`,button(p.cli&&!cached.installed?'Install sample CLI':p.kind==='key'?'Verify sample key':'Use sample sign-in',p.cli&&!cached.installed?'provider-install':'provider-verify')+button('Back','all-providers','as-secondary'));break;}
 case 'provider-ready':html=sheetShell('Account ready','You have<br>a capable partner.',`<div class="as-ready-symbol">${icon('check')}</div><div class="as-status">${esc(sheet.label)} · sample</div><p>You do not need to “connect” it again. Model choices and usage details are in Settings.</p>`,button('Continue','provider-done')+button('Add another account','all-providers','as-secondary'));break;
 case 'free':{const eligible=S.accounts.filter(a=>['gemini','opencode-zen'].includes(a.provider));html=sheetShell('Free models','A little more<br>room to experiment.',`<p>Free tiers still use the original provider account and its limits.</p>${eligible.length?eligible.map(a=>`<label class="as-check-row"><input type="checkbox" data-free-account="${a.id}" checked>Use eligible models from ${esc(a.label)}</label>`).join(''):`${note('None of the connected sample accounts has an eligible free route yet.')}${button('Set up Gemini API','provider','as-secondary','data-value="gemini"')}${button('Set up OpenCode Zen','provider','as-secondary','data-value="opencode-zen"')}`}`,eligible.length?button('Use selected free models','free-save'):button('Skip','free-skip','as-secondary'));break;}
 }
 if(html){main.insertAdjacentHTML('beforeend',html);const section=main.querySelector('.as-sheet');section.querySelector('[data-as="sheet-close"]')?.focus({preventScroll:true});}
}
function discoverProvider(p){const k=S.draft.host+':'+p.id;if(!discoveryCache[k]){discoveryCache[k]={installed:p.installed,checked:Date.now(),host:S.draft.host};emit('cmd.provider.discover','sample',{provider:p.id,host:S.draft.host,cached:false});}return discoveryCache[k];}
function ensureUrlForForge(){if(!forges[S.draft.forge]?.self)return true;try{const u=new URL(S.draft.instance);return u.protocol==='https:';}catch(e){return false;}}

function bindProject(record){
 const owner=window.PM_DEMO?.actions;
 const slug=record.name.toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-+|-+$/g,'')||'astra-project';
 if(owner&&!document.querySelector('.pm6-proj-card[data-proj="'+CSS.escape(slug)+'"]')){
  const run=(id)=>{const fn=owner.get(id);if(typeof fn==='function')return fn({});if(fn?.run)return fn.run({});};
  run(record.kind==='new'?'proj.new.open':'proj.folder.open');
  const name=document.getElementById('pm6-proj-new-name'),path=document.getElementById('pm6-proj-new-path');
  if(name&&path){name.value=record.name;path.value=record.path||'Projects / '+record.name;run('proj.new.create');}
 }
 const card=document.querySelector('.pm6-proj-card[data-proj="'+CSS.escape(slug)+'"]');
 if(card){const open=owner?.get('proj.open');if(typeof open==='function')open({arg:slug});record.shellId=slug;}
 const menu=document.getElementById('projectMenu');if(menu){let item=[...menu.querySelectorAll('[data-project]')].find(n=>n.dataset.project===record.name);if(!item){item=document.createElement('button');item.type='button';item.className='pm6-tb-menu-item';item.dataset.project=record.name;item.dataset.astraProject=record.id;item.textContent=record.name;menu.prepend(item);}item.click();}
 emit('ui.onboarding.project_owner_projection','applied',{projectId:record.id,projectCard:!!card,projectPicker:document.getElementById('projectMenuLabel')?.textContent===record.name});
 // Re-apply the selected look after the existing owner reloads project-scoped settings.
 later(()=>applyTheme(S.theme,false),100);
}
function autoDetectReady(){
 if(!S.fixtures.returning)return;
 const key=S.draft.host+':cursor';if(!S.accounts.some(a=>a.provider==='cursor'&&a.host===S.draft.host)){S.accounts.unshift({id:uid(),provider:'cursor',label:'Existing Cursor account',host:S.draft.host,ready:true,sample:true});discoveryCache[key]={installed:true,checked:Date.now(),host:S.draft.host};emit('cmd.auth_profile.verify','sample_detected_ready',{provider:'cursor',host:S.draft.host,secretStored:false,cached:true});}
}


const transferCategories=groups=>[...new Set(groups.map(g=>({'Appearance':'Appearance & input','Assistant preferences':'Context & memory behavior','Permissions':'Permissions','Tools':'Testing profiles','Provider account references':'AI providers & accounts'}[g])).filter(Boolean))];
function transferSources(){const list=window.PM12_KIMI?.astraSettingsTransfer?.sources()||[];const current=window.PM7_SETTINGS_TOME?.project();if(current&&window.PM7_SETTINGS_TOME.projectSnapshot(current.id)?.settings&&!list.some(p=>p.value===current.id))list.unshift({value:current.id,label:current.label});return list;}
function applyInheritance(frozen,record){if(frozen.inherit==='fresh')return;const bridge=window.PM12_KIMI?.astraSettingsTransfer;const categories=transferCategories(frozen.groups);const result=bridge?.apply(frozen.inherit,categories,{credentials:'Keep existing destination credential ownership',conflicts:'Use source on conflicts',rollback:true})||{ok:false,reason:'Settings Transfer is unavailable.'};const unchanged=/No canonical transferable values differ/.test(result.reason||'');record.transfer={ok:!!result.ok||unchanged,unchanged,count:result.count||0,receiptId:result.receiptId||null,reason:result.reason||null};emit('cmd.settings.transaction.apply',record.transfer.ok?(unchanged?'sample_owner_unchanged':'sample_owner_applied'):'needs_attention',{source:frozen.inherit,projectId:record.id,...record.transfer});}

function commit(){pullFields();const d=S.draft;if(busy)return;if(S.committed?.draftId===d.id){S.stage='providers';render(true);return;}if(!d.name.trim())return fail('Your project still needs a name.');if(d.online&&!d.account)return fail('Sign in to your online service first, or keep the project local.');
 if(d.kind==='new'&&d.location==='network'&&d.protocol==='ssh'&&!d.sshReady)return fail('Check the SSH connection before creating the project.');
 if(d.kind==='existing'&&!d.sourceVerified)return fail('Check the source before adding the project.');if(d.kind==='restore'&&!d.backupVerified)return fail('Inspect the backup before restoring it.');
 const frozen=clone(d),idempotencyKey=d.id;busy=true;S.stage='committing';render(true);emit('cmd.project.'+(d.kind==='new'?'create':d.kind==='restore'?'restore':'add'),'requested',{draftId:d.id,idempotencyKey});
 later(()=>{busy=false;if(faults.commit){delete faults.commit;S.stage='review';error='The sample could not finish. Your choices are safe. Try again; it will not create a duplicate.';emit('cmd.project.commit','failed',{idempotencyKey});render(true);return;}
 let record=S.projects.find(p=>p.draftId===frozen.id);if(!record){record={id:uid(),draftId:frozen.id,name:frozen.name,host:frozen.host,location:frozen.location,path:frozen.path||'~/Puppet Master/'+frozen.name,online:frozen.online,forge:frozen.forge,kind:frozen.kind,sample:true};S.projects.push(record);}
 S.committed=record;bindProject(record);window.PM12_KIMI?.reloadProject();applyInheritance(frozen,record);window.PM12_KIMI?.setSettingFromHost('general.visual.theme',S.theme,false);applyTheme(S.theme,false);autoDetectReady();S.stage='providers';S.trail=[];emit('cmd.project.commit','sample_committed',{idempotencyKey,projectId:record.id,effects:['sample_project_record','project_owner_projection'],settingsTransfer:frozen.inherit!=='fresh'?'pending_owner_apply':'not_requested'});save();render(true);},720);
}
function close(skip=false){if(busy)return;pullFields();S.open=false;applyTheme(S.theme,false);generation++;sheet=null;save();root.hidden=true;root.dataset.open='false';launcher.hidden=false;document.documentElement.dataset.astraOnboarding='false';if(initialDemoPlaying)window.PM_DEMO?.clock.play();savedFocus?.focus?.({preventScroll:true});emit(skip?'ui.onboarding.skip':'ui.onboarding.close','applied',{draftPreserved:true});}
function open(){savedFocus=document.activeElement;window.PM_DEMO?.clock.pause();S.open=true;applyTheme(S.theme,false);render(true);emit('ui.onboarding.resume');}
function replay(){window.PM_DEMO?.clock.pause();S.open=true;sheet=null;if(S.completed){S.draft=draft(S.joined?'connected':'local');S.committed=null;S.stage='welcome';S.trail=[];S.completed=false;}applyTheme(S.theme,false);render(true);}
function click(action,value,target){if(busy&&action!=='preview')return;switch(action){
case 'theme':pullFields();applyTheme(value,true);break;
case 'motion':S.motion=!S.motion;document.documentElement.dataset.astraMotion=S.motion?'on':'off';save();render(false);break;
case 'appearance':sheet={type:'appearance'};renderSheet();break;
case 'preview':sheet={type:'preview'};renderSheet();break;
case 'profile-new':S.fixtures.returning=false;sheet=null;render(false);break;
case 'profile-returning':S.fixtures.returning=true;window.PM7_SETTINGS_TOME?.save(window.PM12_KIMI?.getState());sheet=null;render(false);break;
case 'close':close();break;case 'skip':close(true);break;case 'back':back();break;
case 'sheet-close':sheet=null;renderSheet();break;
case 'start':S.started=true;nextStage('start');break;
case 'local':S.joined=null;S.draft.host='local';S.draft.sshReady=false;S.draft.sourceVerified=false;S.draft.backupVerified=false;nextStage('kind');break;
case 'connect':nextStage('connect');break;case 'discover':emit('cmd.server.discover','sample',{scope:'explicit_network_request'});sheet={type:'discover'};renderSheet();break;
case 'join':sheet={type:'pair',name:value};renderSheet();break;
case 'pair':{const address=$('#connectAddress')?.value.trim();if(!address)return fail('Enter a connection link or pairing code, or find a device on your network.');sheet={type:'pair',name:'My Puppet Master'};renderSheet();break;}
case 'pair-approve':if(faults.pair){delete faults.pair;sheet=null;return fail('That pairing request expired. Ask the other device for a new code.');}S.joined={name:sheet?.name||'My Puppet Master',sample:true};S.draft.host='connected';S.draft.sshReady=false;S.draft.sourceVerified=false;S.draft.backupVerified=false;emit('cmd.client.pair.approve','sample',{trust:'sample_only'});nextStage('connected');break;
case 'server':nextStage('server');break;
case 'server-help':sheet={type:'server-help'};renderSheet();break;
case 'server-preview':sheet={type:'server-ready'};renderSheet();break;
case 'server-continue':S.joined={name:'Studio computer',sample:true};S.draft.host='connected';nextStage('kind');break;
case 'kind':if(!['new','existing','restore'].includes(value))break;if(S.committed){S.draft=draft(S.draft.host);S.committed=null;}S.draft.kind=value;S.draft.sourceVerified=false;S.draft.backupVerified=false;nextStage('project');break;
case 'open-existing':S.draft.kind='existing';S.draft.name='Neighborhood book club';S.draft.path='Projects / book-club';S.draft.sourceVerified=true;nextStage('review');break;
case 'edit-host':nextStage('start');break;
case 'project-next':nextFromProject();break;
case 'inherit':pullFields();S.draft.inherit=value==='fresh'?'fresh':transferSources()[0]?.value||'unavailable';render(false);break;
case 'copy-settings':sheet={type:'copy'};renderSheet();const preview=window.PM12_KIMI?.astraSettingsTransfer?.preview(S.draft.inherit,transferCategories(S.draft.groups),{credentials:'Keep existing destination credential ownership',conflicts:'Use source on conflicts'});emit('cmd.settings.transaction.preview','owner_preview',{groups:S.draft.groups.slice(),writes:0,ready:preview?.ok||false,reason:preview?.reason||'The destination is not created yet; exact differences are rechecked at confirmation.'});break;
case 'copy-done':S.draft.groups=[...root.querySelectorAll('[data-group]:checked')].map(e=>e.dataset.group);sheet=null;render(false);break;
case 'inherit-next':if(S.draft.inherit!=='fresh'&&!transferSources().some(p=>p.value===S.draft.inherit))return fail('No readable source project is available. Choose Start fresh.');finishEdit('storage');break;
case 'location':pullFields();S.draft.location=value;render(false);break;
case 'storage-next':pullFields();if(S.draft.location==='network')nextStage('ssh');else finishEdit('source');break;
case 'storage-local':S.draft.location='local';S.draft.path='';nextStage('storage');break;
case 'ssh-help':pullFields();if(!S.draft.address||!S.draft.username)return fail('Enter your storage address and username first.');sheet={type:'ssh'};renderSheet();break;
case 'ssh-saved':sheet={type:'ssh-fingerprint',saved:true};renderSheet();break;
case 'ssh-new':sheet={type:'ssh-fingerprint',saved:false};renderSheet();break;
case 'ssh-trust':if(!$('#as-trust')?.checked){const p=root.querySelector('.as-sheet .as-fingerprint');p.insertAdjacentHTML('afterend','<p class="as-fine">Check the device identity before continuing.</p>');return;}if(sheet.saved){click('ssh-ready');}else{sheet={type:'ssh-key'};renderSheet();}break;
case 'ssh-ready':if(faults.ssh){delete faults.ssh;sheet=null;return fail('The storage device could not be verified. Check its identity with your administrator.');}S.draft.sshReady=true;sheet=null;emit('cmd.project.source_location.test','sample',{method:'ssh',hostVerified:true,privateKeyStored:false});render(false);break;
case 'ssh-admin':sheet={type:'ssh-admin'};renderSheet();break;
case 'ssh-next':pullFields();if(!S.draft.path)return fail('Choose the network folder first.');if(S.draft.protocol==='ssh'&&!S.draft.sshReady)return fail('Use “Help me connect” to check the SSH connection.');finishEdit('source');break;
case 'online':pullFields();S.draft.online=value==='yes';render(false);break;
case 'forge-auth':pullFields();if(!ensureUrlForForge())return fail('Enter the HTTPS address of your online service first.');sheet={type:'forge-auth'};renderSheet();break;
case 'forge-sample':S.draft.account={id:'sample-'+S.draft.forge,label:'Sample '+S.draft.forge+' account'};sheet=null;emit('cmd.auth_profile.sign_in','sample',{provider:S.draft.forge,projectCreated:false});render(false);break;
case 'source-next':pullFields();if(S.draft.online&&!S.draft.account)return fail('Sign in or create an account first, or keep the project on this computer.');finishEdit('review');break;
case 'check-source':pullFields();if(faults.source){delete faults.source;return fail('That source could not be reached. Check the location and try again. Nothing was copied.');}if(S.draft.online&&(!S.draft.account||!S.draft.repository))return fail('Sign in and choose the online project first.');if(!S.draft.online&&!S.draft.path)return fail('Choose an existing folder first.');S.draft.sourceVerified=true;emit('cmd.project.source.preflight','sample',{writes:0});render(false);break;
case 'browse-repos':sheet={type:'repos'};renderSheet();break;
case 'repo-select':S.draft.repository=value;S.draft.sourceVerified=true;S.draft.path='Projects / '+value;sheet=null;render(false);break;
case 'browse-backups':sheet={type:'backups'};renderSheet();break;
case 'backup-select':S.draft.backup=value;if(value.includes('book-club')){sheet={type:'backup-key'};renderSheet();}else{S.draft.backupVerified=true;sheet=null;render(false);}break;
case 'backup-unlock':if($('#recovery')?.value!=='demo-recovery-key'){$('#recovery').setCustomValidity('Use demo-recovery-key in this preview.');$('#recovery').reportValidity();return;}S.draft.backupVerified=true;sheet=null;render(false);break;
case 'import-next':pullFields();if(S.draft.kind==='restore'&&!S.draft.backupVerified)return fail('Inspect a backup before continuing.');if(S.draft.kind==='existing'&&!S.draft.sourceVerified)return fail('Check the source before continuing.');finishEdit('review');break;
case 'edit':editReturn=true;nextStage(value);break;
case 'commit':commit();break;
case 'all-providers':sheet={type:'all-providers'};renderSheet();break;
case 'provider':sheet={type:'provider',id:value,returnToFree:S.stage==='free'};renderSheet();break;
case 'provider-install':if(!$('#as-install-consent')?.checked){$('#as-install-consent')?.focus();return;}const p=providers.find(p=>p.id===sheet.id);discoverProvider(p).installed=true;emit('cmd.provider.install','sample',{provider:p.id,explicitConsent:true,host:S.draft.host});renderSheet();break;
case 'provider-another':sheet={type:'provider',id:value,additional:true};const cached=discoverProvider(providers.find(p=>p.id===value));sheet.type='provider-new';renderSheet();break;
case 'provider-verify':{const p=providers.find(p=>p.id===sheet.id);if(p.kind==='key'&&$('#sample-key')?.value!=='demo-key'){$('#sample-key')?.setCustomValidity('Use demo-key here. Never enter a real key in a preview.');$('#sample-key')?.reportValidity();return;}const account={id:uid(),provider:p.id,label:p.name+' account',host:S.draft.host,sample:true,ready:true};S.accounts.push(account);emit('cmd.auth_profile.verify','sample',{provider:p.id,host:S.draft.host,secretStored:false});sheet={type:'provider-ready',label:p.name};save();renderSheet();break;}
case 'provider-done':sheet=S.stage==='free'?{type:'free'}:null;render(false);break;
case 'providers-next':nextStage('free');break;
case 'free-setup':sheet={type:'free'};renderSheet();break;
case 'free-save':S.fixtures.free=true;S.freeAccounts=[...root.querySelectorAll('[data-free-account]:checked')].map(el=>el.dataset.freeAccount);sheet=null;emit('cmd.models.free_routes.configure','sample',{accountReferences:S.freeAccounts});render(false);break;
case 'free-skip':sheet=null;render(false);break;
case 'free-next':nextStage('finish');break;
case 'finish':S.completed=true;save();close();if(window.PM_PAGES)PM_PAGES.go('wizard');emit('ui.onboarding.finish');break;
case 'tour':S.completed=true;save();close();window.PM7_GUIDED_TOUR?.start({project:S.committed});break;
 }
}
function boot(){
 savedFocus=document.activeElement;initialDemoPlaying=!!window.PM_DEMO?.state.clock.playing;if(S.open)window.PM_DEMO?.clock.pause();
 root=document.createElement('div');root.id='pm7-onboarding';root.dataset.open=String(S.open);root.dataset.conceptModel='GPT-6 Pro';root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-labelledby','as-title');
 root.innerHTML=`<div class="as-window"><aside class="as-world"><div class="as-world-brand"><span class="as-brand-icon">${mark}</span>Puppet Master</div><div class="as-world-caption"></div></aside><section class="as-main"><div class="as-topbar"><span class="as-edition">Astra / GPT-6 Pro</span><div class="as-top-actions">${button('Preview','preview','as-preview-pill')}${button(icon('sun'),'appearance','as-icon-btn','aria-label="Change appearance" title="Change appearance"')}${button(icon('pause'),'motion','as-icon-btn','aria-label="Toggle decorative motion"')}${button(icon('close'),'close','as-icon-btn','aria-label="Close setup" title="Close setup — keep my progress"')}</div></div><div class="as-content-viewport"></div><footer class="as-bottom"></footer></section></div>`;
 document.body.append(root);main=root.querySelector('.as-main');world=root.querySelector('.as-world');caption=root.querySelector('.as-world-caption');viewport=root.querySelector('.as-content-viewport');footer=root.querySelector('.as-bottom');
 launcher=document.createElement('div');launcher.id='as-launcher';launcher.innerHTML=`<button type="button" data-launch="setup">${S.completed?'Setup':'Resume setup'}</button><button type="button" data-launch="tour">${S.tour?.active?'Resume tour':'Guided tour'}</button>`;document.body.append(launcher);
 launcher.addEventListener('click',e=>{const b=e.target.closest('[data-launch]');if(!b)return;if(b.dataset.launch==='setup')replay();else window.PM7_GUIDED_TOUR?.start({project:S.committed});});
 root.addEventListener('click',e=>{const b=e.target.closest('[data-as]');if(b&&!b.disabled){e.stopPropagation();click(b.dataset.as,b.dataset.value,b);}});
 root.addEventListener('change',e=>{if(e.target.id==='forge'){pullFields();S.draft.forge=e.target.value;S.draft.account=null;S.draft.sourceVerified=false;render(false);}else if(e.target.id==='protocol'){pullFields();S.draft.sshReady=false;render(false);}else if(e.target.id==='importType'){S.draft.online=e.target.value==='An online service';S.draft.sourceVerified=false;render(false);}else if(e.target.dataset.as==='inherit-project'){S.draft.inherit=e.target.value;save();}});
 root.addEventListener('input',e=>{if(e.target.matches('[data-field]')&&!['sample-key','recovery'].includes(e.target.id)){if(['address','username','path','repository','backup'].includes(e.target.id)){if(['address','username','path'].includes(e.target.id))S.draft.sshReady=false;S.draft.sourceVerified=false;S.draft.backupVerified=false;}pullFields();}e.target.setCustomValidity?.('');});
 root.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();if(sheet){sheet=null;renderSheet();}else close();}if(e.key==='Enter'&&e.target.tagName==='INPUT'&&!sheet){e.preventDefault();const f=footerAction();if(f)click(f[1]);}if(e.key==='Tab'){const focusables=[...(sheet?main.querySelector('.as-sheet'):root).querySelectorAll('button:not(:disabled),input,select,a[href],textarea')].filter(e=>e.getClientRects().length);const first=focusables[0],last=focusables.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
 document.addEventListener('visibilitychange',()=>{document.documentElement.dataset.astraHidden=String(document.hidden);});
 applyTheme(S.theme,false);render();later(()=>{if(S.open)applyTheme(S.theme,false);},80);
}
window.ASTRA={version:3,icon,esc,button,choice,headline,clone,reduced,emit,events,providers,forges,get state(){return clone(S);},get storeAvailable(){return storeAvailable;},saveTour(t){S.tour=t;save();const label=launcher?.querySelector('[data-launch="tour"]');if(label)label.textContent=t?.active?'Resume tour':'Guided tour';},getTour(){return clone(S.tour);},theme:applyTheme,open,close,replay,back,bindProject,go:nextStage,act:click,
 demo:{failNext(name){faults[name]=true;},profile(returning){S.fixtures.returning=!!returning;save();},reset(){S=defaults();discoveryCache={};events.length=0;sheet=null;busy=false;editReturn=false;applyTheme(S.theme,false);render();later(()=>{if(S.open)applyTheme(S.theme,false);},80);},snapshot(){return {state:clone(S),discovery:clone(discoveryCache),events:clone(events),storeAvailable};}}};
window.addEventListener('message',e=>{const m=e.data;if(e.source!==window.parent||m?.source!=='pm-concept-hub'||m.type!=='pm-concept-state')return;const st=m.state||{};if(typeof st.reducedMotion==='boolean'){S.motion=!st.reducedMotion;document.documentElement.dataset.astraMotion=S.motion?'on':'off';}if(st.theme)applyTheme(st.theme,false);save();});
window.PM7_ONBOARDING_CINEMATIC={schema_id:'pm.astra.onboarding.v3',concept_simulation_only:true,open,close,skip:()=>close(true),back,resume:open,replay,snapshot:()=>ASTRA.demo.snapshot()};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
