/* Astra guided practice: real Chat thread, real panel owner, real widget menu,
 * and an explicit local-practice adapter mounted IN the Planning Wizard.
 * No provider, usage, repository, or build operation is dispatched.
 */
(() => {
'use strict';
const $=s=>document.querySelector(s), all=s=>[...document.querySelectorAll(s)];
let draggingMotion=false;
let root,coach,ring,cursor,T=null,epoch=0,timer=null,showing=false,originalSend=null,animations=new Set(),lastRect='',practice=null,lastPosition='',lastStep=-1;
const A=()=>window.ASTRA, ic=n=>A().icon(n), esc=t=>A().esc(t), copy=v=>A().clone(v), reduced=()=>A().reduced();
const prompt='What happens before Puppet Master changes my files?';
const regular='Before work begins, Puppet Master turns your request into a plan. You can review the important choices, correct anything that looks wrong, and decide when to begin. Your Project permissions still control what the work may change.';
const simple='First, Puppet Master writes down what it thinks you want. You can fix the plan before anything starts. It waits for your decision to begin.';
const goal='Make a website for our neighborhood book club. Show the next meeting, the current book, and how to join.';
const steps=[
 {id:'teacher',chapter:'01 / Ask & understand',title:'You can just ask.',text:'Teacher lives in Assistant Chat. Send this question to try a clear, helpful answer.',target:()=>$('#chatPanel .pm6-chat-input'),predicate:()=>T.flags.asked,show:showTeacher},
 {id:'eli5',chapter:'01 / Ask & understand',title:'Same idea. Simpler words.',text:'Turn on ELI5 beneath the message box. Watch Teacher explain the same answer more simply.',target:()=>$('#chatPanel .toggle-eli5'),predicate:()=>T.flags.eli5,show:async()=>tap($('#chatPanel .toggle-eli5'))},
 {id:'dock',chapter:'02 / Make it yours',title:'A workspace that moves.',text:'Drag Chat by its corner grip into the middle of the workspace. Your conversation comes with it.',target:()=>$('#chatPanel .pm-home-surface-grip'),predicate:()=>surface('chat')?.host==='home_main',show:showDock},
 {id:'widget',chapter:'02 / Make it yours',title:'A little more room.',text:'Open this widget’s size menu and choose a different size. The layout remembers your choice.',target:()=>widget()?.querySelector('.pm7-dash-size-btn'),predicate:()=>{const n=widget();return n&&n.dataset.pm7Size!==T.widgetSize;},show:showWidget},
 {id:'wizard',chapter:'03 / Plan before building',title:'The best part starts here.',text:'Open Planning Wizard at the top. This is where an idea becomes a plan you can understand.',target:()=>$('#tab-wizard'),predicate:()=>window.PM_PAGES?.current==='wizard',show:async()=>tap($('#tab-wizard'))},
 {id:'idea',chapter:'03 / Plan before building',title:'Start with an ordinary idea.',text:'Choose the book-club example, then submit it. No coding words are needed.',target:()=>$('#as-practice-goal'),predicate:()=>T.flags.idea,show:showIdea},
 {id:'outcomes',chapter:'03 / Plan before building',title:'Here is what you will get.',text:'The Wizard translates your idea into outcomes. Check them, then continue to the question.',target:()=>$('#as-practice-outcomes'),predicate:()=>T.flags.outcomes,show:async()=>tap($('[data-tour="outcomes-next"]'))},
 {id:'question',chapter:'03 / Plan before building',title:'One choice that matters.',text:'Who can update the site? Choose an answer. Open “Why this matters” to see what it changes.',target:()=>$('#as-practice-question'),predicate:()=>T.flags.answer,show:async()=>{await tap($('[data-tour="why"]'));await wait(1300);await tap($('[data-tour="answer"][data-value="me"]'));}},
 {id:'review',chapter:'03 / Plan before building',title:'Read the plan, not the code.',text:'Open Plan review. It brings together the outcome, your decisions, and anything still undecided.',target:()=>$('#as-practice-review-open'),predicate:()=>T.flags.review,show:async()=>tap($('#as-practice-review-open'))},
 {id:'edit',chapter:'03 / Plan before building',title:'You can change your mind.',text:'Edit who can update the site. Choose a few organizers instead of only you.',target:()=>$('#as-practice-edit'),predicate:()=>T.flags.edited,show:async()=>{await tap($('#as-practice-edit'));await wait(650);await tap($('[data-tour="edit-answer"][data-value="team"]'));}},
 {id:'consequence',chapter:'03 / Plan before building',title:'A choice with a visible effect.',text:'Shared sign-in and organizer permissions were added. The meeting, book, and joining information stay the same.',target:()=>$('#as-plan-consequence'),predicate:()=>T.flags.consequence,show:async()=>tap($('[data-tour="checked-change"]'))},
 {id:'boundary',chapter:'03 / Plan before building',title:'You hold the starting signal.',text:'Review what is still undecided. Approve And Build is the boundary before work begins—not the act of making a plan.',target:()=>$('#as-practice-approval'),predicate:()=>T.flags.boundary,show:async()=>tap($('#as-practice-approval'))},
 {id:'finish',chapter:'03 / Ready for your idea',title:'From an idea to a clear plan.',text:'You have seen the whole path. Your project is ready, and no AI work has started.',target:()=>$('.as-practice'),predicate:()=>true,show:null}
];
const step=()=>steps[T?.step||0];
function persist(){if(T){T.showing=false;A().saveTour(copy(T));}}
function surface(id){return window.PM_HOME_WORKSPACE?.layout.surfaces.find(s=>s.surface_instance_id===id);}
function widget(){return $('#pm6DashGrid [data-widget-id="pm6-dash-orchestrator-progress"]')||$('#pm6DashGrid .pm6-dash-card');}
const log=(action,status='applied',extra={})=>A().emit(action,status,{tourStep:step().id,providerCalls:0,usageDelta:0,...extra});
function wait(ms){const token=epoch;return new Promise(resolve=>setTimeout(()=>resolve(token===epoch&&T?.active),reduced()?Math.min(ms,140):ms));}
async function animate(el,frames,options){if(!el)return false;if(reduced()){const last=frames.at(-1);for(const k of ['opacity','transform'])if(last[k]!=null)el.style[k]=last[k];return true;}const anim=el.animate(frames,options);animations.add(anim);await anim.finished.catch(()=>{});animations.delete(anim);anim.cancel();return !!T?.active;}
function cancelMotion(){draggingMotion=false;all('.as-tour-arrival').forEach(n=>n.classList.remove('as-tour-arrival'));epoch++;showing=false;animations.forEach(a=>a.cancel());animations.clear();if(cursor)cursor.style.opacity='0';window.PM_HOME_WORKSPACE?.cancelDrag();}
function showRing(target){if(draggingMotion){ring.style.opacity='0';return;}if(!target||!target.getClientRects().length){ring.style.opacity='0';return;}const r=target.getBoundingClientRect();const x=Math.max(6,r.left-6),y=Math.max(6,r.top-6),w=Math.min(innerWidth-x-6,r.width+12),h=Math.min(innerHeight-y-30,r.height+12);const rect=[x,y,w,h].map(Math.round).join(',');if(rect!==lastRect){lastRect=rect;ring.style.width=w+'px';ring.style.height=h+'px';ring.style.transform=`translate(${x}px,${y}px)`;}ring.style.opacity='1';}
function positionCoach(target){if(!coach||draggingMotion)return;const w=coach.offsetWidth||326,h=coach.offsetHeight||280;const r=target?.getBoundingClientRect();let x=26,y=innerHeight-h-48;
 if(T.step>=4){x=Math.min(innerWidth-w-22,Math.max(20,innerWidth-w-22));y=innerHeight-h-44;}
 else if(r){x=r.left-w-28;y=Math.min(innerHeight-h-44,Math.max(86,r.top-100));if(x<18){x=Math.min(innerWidth-w-18,r.right+28);}}
 if(innerWidth<900){x=20;y=innerHeight-h-45;}
 x=Math.max(14,Math.min(innerWidth-w-14,x));y=Math.max(55,Math.min(innerHeight-h-36,y));const pos=`${Math.round(x)},${Math.round(y)}`;if(pos!==lastPosition){const before=coach.getBoundingClientRect();coach.style.left=x+'px';coach.style.top=y+'px';if(lastPosition&&!reduced()&&lastStep!==T.step)coach.animate([{transform:`translate(${before.left-x}px,${before.top-y}px)`},{transform:'translate(0,0)'}],{duration:650,easing:'cubic-bezier(.22,1,.36,1)'});lastPosition=pos;}lastStep=T.step;
}
function guide(){if(!T?.active||!coach)return;const st=step(),done=!!st.predicate();const missing=!done&&!st.target()?.getClientRects().length;const b=(txt,action,cls='as-secondary',attrs='')=>`<button type="button" class="${cls}" data-tour="${action}" ${attrs}>${txt}</button>`;
 coach.innerHTML=`<div class="as-coach-top"><span>${st.chapter}</span>${b('Skip Tour','skip','as-text-btn')}</div><h2>${st.title}</h2><p>${st.text}</p>${missing?`<div class="as-note" style="margin-top:12px">This step needs its workspace control. ${b('Bring it back','recover','as-text-btn')}</div>`:''}${T.step===0&&!done?`<button class="as-tour-prompt" data-tour="fill-question">${prompt}</button>`:''}${T.step===12?`<label class="as-check-row" style="margin-top:16px"><input type="checkbox" id="as-keep-layout" ${T.keepLayout?'checked':''}>Keep the layout I tried</label>`:''}<div class="as-coach-bottom">${b(ic('back'),'back','as-back',`aria-label="Back" ${T.step?'':'disabled'}`)}${st.show?b(showing?'Stop demo':'Show Me',showing?'stop-demo':'show','as-secondary',done?'disabled':''):''}${b(T.step===12?'Finish tour':done?'Continue':'Try it above',T.step===12?'finish':'next','as-primary',done&&!showing?'':'disabled')}</div><div class="as-progress" aria-label="Step ${T.step+1} of ${steps.length}">${steps.map((_,i)=>`<i class="${i===T.step?'active':i<T.step?'done':''}"></i>`).join('')}</div>`;
 coach.dataset.done=String(done);coach.dataset.step=st.id;coach.setAttribute('aria-live','polite');const target=st.target();showRing(target);positionCoach(target);persist();
}
function observe(){clearTimeout(timer);if(!T?.active||document.hidden)return;const done=!!step().predicate(),missing=!done&&!step().target()?.getClientRects().length;if(coach.dataset.done!==String(done)||coach.dataset.missing!==String(missing)){coach.dataset.missing=String(missing);guide();}showRing(step().target());positionCoach(step().target());timer=setTimeout(observe,160);}
async function cue(target){if(!T?.active||!target)return false;const token=epoch;target.scrollIntoView({block:'nearest',behavior:'instant'});showRing(target);target.focus?.({preventScroll:true});await wait(450);return token===epoch&&T.active;}
async function point(target,doClick=false){if(!target||!await cue(target))return false;const token=epoch,r=target.getBoundingClientRect(),end={x:r.left+r.width/2,y:r.top+r.height/2};let start={x:Math.max(20,end.x-115),y:Math.min(innerHeight-30,end.y+90)};cursor.style.opacity='1';cursor.style.transform=`translate(${start.x}px,${start.y}px)`;
 await animate(cursor,[{transform:`translate(${start.x}px,${start.y}px)`},{transform:`translate(${end.x-38}px,${end.y+8}px)`,offset:.7},{transform:`translate(${end.x}px,${end.y}px)`}],{duration:940,easing:'cubic-bezier(.35,0,.18,1)',fill:'forwards'});
 if(token!==epoch||!T.active)return false;cursor.style.transform=`translate(${end.x}px,${end.y}px)`;target.classList.add('as-tour-arrival');await wait(260);if(token!==epoch||!T.active)return false;if(doClick)target.click();await wait(600);target.classList.remove('as-tour-arrival');cursor.style.opacity='0';return token===epoch;
}
const tap=t=>point(t,true);
async function showMe(){if(showing||!step().show||step().predicate())return;showing=true;const token=++epoch;guide();log('ui.guided_tour.show_me','started');try{await step().show();}catch(e){window.PM_HOME_WORKSPACE?.cancelDrag();log('ui.guided_tour.show_me','failed',{reason:String(e)});}if(token===epoch&&T?.active){showing=false;guide();log('ui.guided_tour.show_me',step().predicate()?'completed':'needs_action');}}
function mountTeacher(){const d=window.PM_DEMO,api=window.PM_HOME_WORKSPACE;if(!d||!api)return false;api.setSurfaceVisible('chat',true,'cmd.panel.switch');if(surface('chat')?.host!=='dock_right')api.moveSurface('chat','dock_right',{index:0});
 // Use the same owner resize command as the visible panel divider.
 if(surface('chat')?.size.basis_px<480){api.beginResize('chat',{clientX:0,clientY:0});api.updateResize('chat',{clientX:-170,clientY:0});api.commitResize();}
 if(!T.thread||!d.state.chat.threads[T.thread]){const result=d.chat.newThread('teacher');T.thread=result.threadId;d.state.chat.threads[T.thread].title='Teacher · guided example';if(window.PM6_CHAT_THREADS?.[T.thread])PM6_CHAT_THREADS[T.thread].title='Teacher · guided example';}
 all(`.chat-thread-item[data-thread="${T.thread}"] .thread-title`).forEach(n=>n.textContent='Teacher · guided example');const row=$(`.chat-thread-item[data-thread="${T.thread}"]`);row?.click();
 const sidebar=$('#chatPanel .chat-thread-sidebar');if(sidebar){if(!T.original.sidebarStyle)T.original.sidebarStyle=sidebar.getAttribute('style')||'';sidebar.style.width='56px';sidebar.style.flex='0 0 56px';}
 const picker=$('#chatPanel .pm6-chat-personabtn');if(picker){picker.click();let teacher=$('.pm6-chat-persona-popout-portal.is-open [data-persona="Teacher"]');if(!teacher){const list=$('.pm6-chat-persona-popout-portal.is-open .pm6-chat-personalist');if(list){teacher=document.createElement('button');teacher.type='button';teacher.className='pm6-chat-personaitem';teacher.dataset.persona='Teacher';teacher.innerHTML='<span class="pm6-chat-personaname">Teacher</span><span class="pm6-chat-personacheck"></span>';list.prepend(teacher);}}teacher?.click();}
 const input=$('#chatPanel .pm6-chat-input');if(input)input.placeholder='Ask Teacher about Puppet Master…';
 if(!originalSend){originalSend=d.chat.send;d.chat.send=function(id,text){if(!T?.active||id!==T.thread)return originalSend.apply(this,arguments);return teacherSend(id,String(text).trim());};}
 const stream=$('#chatPanel .messageStream');if(stream&&!stream.querySelector('.as-guided-label')){const n=document.createElement('div');n.className='as-guided-label';n.innerHTML='Teacher <span>Guided example · no AI usage</span>';stream.prepend(n);}
 if(T.flags.asked&&!$('[data-astra-answer]'))renderTeacherAnswer(T.flags.eli5?simple:regular,false);
 return true;
}
function teacherSend(id,text){const d=PM_DEMO;if(!text)return {ok:false};if(d.state.chat.busy)return {ok:false};const thread=d.state.chat.threads[id];$('#chatPanel .messageStream')?.querySelectorAll('.pm6-chat-sys').forEach(n=>{if(n.textContent.includes('New thread'))n.remove();});thread.messages.push({role:'user',text});d.emit('chat.stream',{threadId:id,type:'user',text});const stream=$('#chatPanel .messageStream');stream?.querySelectorAll('.runtime-snapshot,.msg-runtime-compact').forEach(n=>n.remove());renderTeacherAnswer(T.flags.eli5?simple:regular,true);log('ui.guided_tour.teacher_example','started',{threadId:id,deterministic:true});return {ok:true,local_deterministic:true,provider_use_count:0};}
async function renderTeacherAnswer(answer,streaming){const token=epoch,d=PM_DEMO,id=T.thread,msg='astra-teacher-'+Date.now();T.answerMessage=msg;d.state.chat.busy=true;d.emit('chat.state',{busy:true,context:d.state.chat.context,queue:d.state.chat.queue});d.emit('chat.stream',{threadId:id,msgId:msg,type:'start',intent:'guided_teacher'});
 const chunks=answer.split(/(?<=\s)/);for(let i=0;i<chunks.length;i+=3){if(token!==epoch||!T?.active){d.state.chat.busy=false;d.emit('chat.stream',{threadId:id,msgId:msg,type:'done'});d.emit('chat.state',{busy:false,context:d.state.chat.context,queue:d.state.chat.queue});return;}d.emit('chat.stream',{threadId:id,msgId:msg,type:'chunk',html:esc(chunks.slice(i,i+3).join(''))});if(streaming&&!reduced())await new Promise(r=>setTimeout(r,58));}
 d.state.chat.threads[id].messages.push({role:'assistant',html:esc(answer),guidedExample:true});d.state.chat.busy=false;d.emit('chat.stream',{threadId:id,msgId:msg,type:'done'});d.emit('chat.state',{busy:false,context:d.state.chat.context,queue:d.state.chat.queue});T.flags.asked=true;
 all(`[data-pm6-mid="${msg}"]`).forEach(el=>{el.dataset.astraAnswer='true';el.querySelectorAll('.runtime-snapshot,.msg-runtime-compact').forEach(n=>n.remove());});guide();log('ui.guided_tour.teacher_example','completed',{threadId:id,deterministic:true});
}
async function showTeacher(){const input=$('#chatPanel .pm6-chat-input');if(!await point(input))return;input.value=prompt;input.dispatchEvent(new Event('input',{bubbles:true}));await wait(850);await tap($('#chatPanel .pm6-chat-send'));await wait(1600);}
function simplify(){if(!T?.active||T.step!==1)return;const toggle=$('#chatPanel .toggle-eli5');if(toggle&&!toggle.classList.contains('active'))return;T.flags.eli5=true;const el=$(`[data-pm6-mid="${T.answerMessage}"] .pm6-chat-sink`);if(el){el.textContent=simple;el.animate([{opacity:.25,transform:'translateY(5px)'},{opacity:1,transform:'none'}],{duration:reduced()?0:420,easing:'ease-out'});}const thread=PM_DEMO.state.chat.threads[T.thread];const message=thread?.messages.filter(m=>m.role==='assistant').at(-1);if(message)message.html=esc(simple);guide();log('ui.guided_tour.eli5','completed');}
async function showDock(){const api=PM_HOME_WORKSPACE,handle=$('#chatPanel .pm-home-surface-grip'),dest=$('[data-pm-home-host="home_main"]');if(!handle||!dest)return;if(!await cue(handle))return;const token=epoch,r=handle.getBoundingClientRect(),d=dest.getBoundingClientRect();const start={x:r.left+r.width/2,y:r.top+r.height/2},end={x:d.left+d.width*.54,y:d.top+Math.min(170,d.height*.4)};cursor.style.opacity='1';cursor.style.transform=`translate(${start.x}px,${start.y}px)`;draggingMotion=true;api.beginDrag('chat',{button:0,pointerId:771,clientX:start.x,clientY:start.y,currentTarget:handle,preventDefault(){},stopPropagation(){}});
 await new Promise(resolve=>{const t0=performance.now(),duration=reduced()?180:1650;function frame(now){if(token!==epoch||!T?.active){api.cancelDrag();resolve();return;}const p=Math.min(1,(now-t0)/duration),u=p*p*(3-2*p),x=start.x+(end.x-start.x)*u,y=start.y+(end.y-start.y)*u-Math.sin(Math.PI*p)*35;api.updateDrag({pointerId:771,clientX:x,clientY:y});cursor.style.transform=`translate(${x}px,${y}px)`;if(p<1)requestAnimationFrame(frame);else resolve();}requestAnimationFrame(frame);});
 if(token!==epoch)return;/* The owner requires two stable hit tests, including at low frame rates. */for(let i=0;i<3;i++){api.updateDrag({pointerId:771,clientX:end.x,clientY:end.y});await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));}await wait(500);api.commitDrop();await wait(900);cursor.style.opacity='0';draggingMotion=false;log('cmd.workspace_layout.move_surface',surface('chat')?.host==='home_main'?'verified':'needs_action',{ownerReceiptCount:api.receipt_log.length});
}
async function showWidget(){const n=widget();if(!n)return;await tap(n.querySelector('.pm7-dash-size-btn'));await wait(450);const current=n.dataset.pm7Size,option=all('.pm7-dash-size-pop.open [data-size]').find(o=>o.dataset.size!==current&&o.dataset.size==='1x1')||all('.pm7-dash-size-pop.open [data-size]').find(o=>o.dataset.size!==current);await tap(option);await wait(700);log('cmd.widget.resize',step().predicate()?'verified':'needs_action',{ownerReceiptCount:PM7_DASH_WIDGETS.receipt_log.length});}
function restoreChatPlacement(){const saved=T.original.chat,api=PM_HOME_WORKSPACE;if(!saved||!api)return;api.moveSurface('chat',saved.host,{index:saved.slot_index,...(saved.floating_bounds?{bounds:saved.floating_bounds}:{})});let now=surface('chat');if(now){const sign=['dock_right','dock_bottom'].includes(now.host)?-1:1;api.beginResize('chat',{clientX:0,clientY:0});api.updateResize('chat',{clientX:(saved.size.basis_px-now.size.basis_px)*sign,clientY:0});api.commitResize();api.setCollapsed('chat',saved.collapsed);api.setSurfaceVisible('chat',saved.visible,'cmd.panel.switch');}}
function setPracticeStage(s){T.practice.stage=s;renderPractice();persist();}
function renderPractice(){let host=$('#panel-wizard');if(!host)return;document.documentElement.dataset.astraTourPractice='true';if(!practice||!practice.isConnected){practice=document.createElement('article');practice.className='as-practice';practice.dataset.conceptModel='GPT-6 Pro';host.append(practice);}
 const p=T.practice, stage=p.stage;const b=(txt,action,cls='as-primary',attrs='')=>`<button type="button" class="${cls}" data-tour="${action}" ${attrs}>${txt}</button>`;
 const option=(label,value,action='answer')=>`<button type="button" class="as-choice as-compact" data-tour="${action}" data-value="${value}" aria-pressed="${p.answer===value}"><span class="as-choice-icon">${ic(value==='team'?'user':value==='me'?'lock':'info')}</span><strong>${label}</strong><span>${p.answer===value?'✓':'↗'}</span></button>`;
 let content='';if(stage==='idea')content=`<p class="as-eyebrow">Brand-new product</p><h1>What would you love to make?</h1><p>Tell us the outcome. The Wizard will help with the details.</p><section><button type="button" class="as-choice" data-tour="choose-goal"><span class="as-choice-icon">${ic('book')}</span><span><strong>A home for your book club</strong><small>A small website for a neighborhood community.</small></span><span>↗</span></button><label class="as-field">Your idea<textarea id="as-practice-goal" placeholder="Describe what you want to make…">${esc(p.goal||'')}</textarea></label></section><div class="as-plan-footer">${b('Plan this idea '+ic('arrow'),'submit-goal')}<span class="as-fine">Guided practice. No provider calls.</span></div>`;
 if(stage==='outcomes')content=`<p class="as-eyebrow">Requirements · your intended outcome</p><h1>A welcoming home<br>for your book club.</h1><p>Three things your neighbors will be able to do.</p><section id="as-practice-outcomes"><div class="as-outcome">Find the next meeting<small>Date, time, and place, all in one spot.</small></div><div class="as-outcome">See what you are reading<small>The current book and a little about it.</small></div><div class="as-outcome">Know how to join<small>A friendly invitation and contact details.</small></div></section><div class="as-plan-footer">${b('Looks right · Continue '+ic('arrow'),'outcomes-next')}</div>`;
 if(stage==='question')content=`<p class="as-eyebrow">Requirements · one meaningful decision</p><h1>Who should be able to update<br>the meeting and book?</h1><section id="as-practice-question">${option('Only me','me')}${option('A few organizers','team')}${option('I’m not sure yet','unsure')}</section>${b('Why this matters','why','as-text-btn')}<p id="as-question-why" ${p.why?'':'hidden'}>This decides whether the site needs shared sign-in and editing. Answering now keeps Puppet Master from planning the wrong kind of site.</p><div class="as-plan-footer">${b('Open Plan review '+ic('arrow'),'review-open','as-primary',`id="as-practice-review-open" ${p.answer?'':'disabled'}`)}</div>`;
 if(stage==='review')content=`<p class="as-eyebrow">Plan review · ready for your eyes</p><h1>Your idea, made clear.</h1><p>The plan changes with your choices. Building waits for your approval.</p><section><div class="as-plan-card"><h3>What stays the same</h3><p>Next meeting · Current book · How to join</p></div><div class="as-plan-card" id="as-plan-consequence"><div style="display:flex;justify-content:space-between;gap:12px"><h3>Who can update the site</h3>${b('Edit answer','edit','as-text-btn','id="as-practice-edit"')}</div><div id="as-plan-answer">${consequence(p.answer)}</div>${p.editing?`<section style="margin-top:15px">${option('Only me','me','edit-answer')}${option('A few organizers','team','edit-answer')}${option('I’m not sure yet','unsure','edit-answer')}</section>`:''}</div><div class="as-plan-card"><h3>Still to decide</h3><p>${p.answer==='unsure'?'Who can edit the site; plus ':''}Your website address and final meeting details.</p><p class="as-fine" style="margin-top:8px">Assumption: the public can read the site without signing in.</p></div></section><div class="as-plan-footer">${T.flags.edited&&!T.flags.consequence?b('I see what changed '+ic('check'),'checked-change','as-secondary'):''}${b('Approve And Build','approval','as-primary','id="as-practice-approval"')}<span class="as-fine">Practice only · no build will start</span></div>${T.flags.boundary?'<div class="as-note" style="margin-top:18px">In your real project, <strong>Approve And Build</strong> starts the approved work. Here, you have only explored a practice plan. Nothing is running.</div>':''}`;
 const phase=stage==='idea'?0:stage==='review'?2:1;practice.innerHTML=`<header><span class="as-edition">Planning Wizard${T.project?' · '+esc(T.project.name):''}</span><span class="as-preview-pill">Guided practice</span></header><div class="as-plan-steps">${['Idea','Requirements','Plan review'].map((s,i)=>`<span class="${i===phase?'current':''}">${String(i+1).padStart(2,'0')} ${s}</span>`).join('')}</div>${content}`;
 if(!reduced())practice.animate([{opacity:.55,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:380,easing:'cubic-bezier(.22,1,.36,1)'});
}
function consequence(answer){return answer==='team'?'<p><strong>A few organizers</strong><br>Shared sign-in, organizer invitations, and editing permissions.</p>':answer==='me'?'<p><strong>Only you</strong><br>One private sign-in. No organizer invitations or shared editing needed.</p>':'<p><strong>Decision still open</strong><br>Editing access will need your answer before that part can be built.</p>';}
async function showIdea(){await tap($('[data-tour="choose-goal"]'));await wait(1000);await tap($('[data-tour="submit-goal"]'));}
function practiceAction(action,value){switch(action){
case 'choose-goal':T.practice.goal=goal;$('#as-practice-goal').value=goal;log('ui.wizard.practice.choose_goal');break;
case 'submit-goal':{const v=$('#as-practice-goal')?.value.trim();if(!v){$('#as-practice-goal')?.focus();return;}if(!/book|meeting|club/i.test(v)){const input=$('#as-practice-goal');input.setCustomValidity('Use the book-club example for this guided practice. Your own idea comes after the tour.');input.reportValidity();return;}T.practice.goal=v;T.flags.idea=true;setPracticeStage('outcomes');log('ui.wizard.practice.submit_goal');break;}
case 'outcomes-next':T.flags.outcomes=true;setPracticeStage('question');log('ui.wizard.practice.confirm_outcomes');break;
case 'why':T.practice.why=!T.practice.why;const why=$('#as-question-why');if(why)why.hidden=!T.practice.why;break;
case 'answer':T.practice.answer=value;T.flags.answer=true;renderPractice();log('ui.wizard.practice.answer',{me:'only_me',team:'organizers',unsure:'unresolved'}[value]);break;
case 'review-open':if(!T.practice.answer)return;T.flags.review=true;setPracticeStage('review');log('ui.wizard.practice.review');break;
case 'edit':{T.practice.editing=!T.practice.editing;const card=$('#as-plan-consequence');if(T.practice.editing&&card&&!card.querySelector('.as-edit-answers')){const labels=[['me','Only me'],['team','A few organizers'],['unsure','I’m not sure yet']];card.insertAdjacentHTML('beforeend','<section class="as-edit-answers" style="margin-top:15px">'+labels.map(([v,l])=>'<button class="as-choice as-compact" data-tour="edit-answer" data-value="'+v+'"><span class="as-choice-icon">'+ic(v==='team'?'user':'lock')+'</span><strong>'+l+'</strong><span>→</span></button>').join('')+'</section>');}else card?.querySelector('.as-edit-answers')?.remove();break;}
case 'edit-answer':{const before=T.practice.answer;T.practice.answer=value;T.practice.editing=false;T.flags.edited=before!==value;const el=$('#as-plan-consequence'),answer=$('#as-plan-answer');if(answer){answer.innerHTML=consequence(value);el.querySelector('.as-edit-answers')?.remove();const next=$('#as-practice-approval');if(next&&!$('[data-tour="checked-change"]'))next.insertAdjacentHTML('beforebegin','<button class="as-secondary" data-tour="checked-change">I see what changed '+ic('check')+'</button>');if(!reduced())answer.animate([{opacity:.15,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:640,easing:'cubic-bezier(.22,1,.36,1)'});}else renderPractice();log('ui.wizard.practice.edit_answer','applied',{before,after:value,unchanged:['next_meeting','current_book','how_to_join']});break;}
case 'checked-change':T.flags.consequence=true;$('[data-tour="checked-change"]')?.remove();break;
case 'approval':T.flags.boundary=true;if(!$('#as-approval-note'))practice.insertAdjacentHTML('beforeend','<div id="as-approval-note" class="as-note" style="margin-top:18px">In your real project, <strong>Approve And Build</strong> starts the approved work. This was a practice plan. Nothing is running.</div>');log('ui.wizard.practice.approval_boundary','explained',{buildStarted:false});break;
 }
 persist();guide();
}
function moveChatHome(host){const moving=all('[data-pm-home-surface]').filter(n=>n.getClientRects().length);const before=moving.map(n=>[n,n.getBoundingClientRect()]);PM_HOME_WORKSPACE.moveSurface('chat',host,{index:0});if(!reduced())for(const [n,r] of before){const q=n.getBoundingClientRect();if(q.width&&q.height)n.animate([{transform:'translate('+(r.x-q.x)+'px,'+(r.y-q.y)+'px) scale('+(r.width/q.width)+','+(r.height/q.height)+')',transformOrigin:'top left'},{transform:'none',transformOrigin:'top left'}],{duration:820,easing:'cubic-bezier(.22,1,.36,1)'});}}
function prepare(){if(!T?.active)return;switch(step().id){
case 'teacher':case 'eli5':PM_PAGES.go('dashboard');mountTeacher();break;
case 'dock':PM_PAGES.go('dashboard');mountTeacher();break;
case 'widget':PM_PAGES.go('dashboard');if(surface('chat')?.host!=='dock_right')moveChatHome('dock_right');widget()?.scrollIntoView({block:'center',behavior:'instant'});if(!T.widgetSize)T.widgetSize=widget()?.dataset.pm7Size;break;
case 'wizard':PM_PAGES.go('dashboard');T.practice.stage='idea';renderPractice();break;
case 'idea':PM_PAGES.go('wizard');T.practice.stage=T.flags.idea?'outcomes':'idea';renderPractice();break;
case 'outcomes':PM_PAGES.go('wizard');T.practice.stage='outcomes';renderPractice();break;
case 'question':case 'review':PM_PAGES.go('wizard');T.practice.stage='question';renderPractice();break;
case 'edit':case 'consequence':case 'boundary':case 'finish':PM_PAGES.go('wizard');T.practice.stage='review';if(!$('#as-plan-consequence'))renderPractice();break;
 }
 guide();observe();
}
function next(){if(!T?.active||showing||!step().predicate())return;T.dwell.push({step:step().id,ms:Math.round(performance.now()-T.entered)});T.step=Math.min(steps.length-1,T.step+1);T.entered=performance.now();cancelMotion();prepare();log('ui.guided_tour.next');}
function back(){if(!T?.active||!T.step)return;cancelMotion();T.step--;T.entered=performance.now();prepare();log('ui.guided_tour.back');}
function start(options={}){if(!root)boot();A().close();cancelMotion();let stored=A().getTour();if(stored?.active&&!options.replay){T=stored;T.active=true;T.entered=performance.now();}
 else{const input=$('#chatPanel .pm6-chat-input');T={version:3,active:true,step:0,flags:{},practice:{stage:'idea',goal:'',answer:null,why:false,editing:false},keepLayout:false,thread:null,original:{layout:copy(PM_HOME_WORKSPACE.layout),chat:copy(surface('chat')),widgetState:copy(window.PM7_DASH_WIDGETS?.state),page:window.PM_PAGES?.current,thread:PM_DEMO.state.chat.activeThread,persona:$('#chatPanel .pm6-chat-personabtn')?.textContent.trim(),eli5:!!$('#chatPanel .toggle-eli5')?.classList.contains('active'),input:input?.value||'',placeholder:input?.placeholder||'',demoPlaying:!!PM_DEMO.state.clock.playing,sidebarStyle:$('#chatPanel .chat-thread-sidebar')?.getAttribute('style')||''},dwell:[],entered:performance.now(),project:options.project||A().state.committed};}
 PM_DEMO.clock.pause();root.hidden=false;root.dataset.open='true';$('#as-launcher').hidden=true;document.documentElement.dataset.astraTour='true';prepare();const chat=$('#chatPanel');if(chat&&!reduced())chat.animate([{opacity:.2,transform:'translateX(26px)'},{opacity:1,transform:'none'}],{duration:720,easing:'cubic-bezier(.22,1,.36,1)'});log('ui.guided_tour.start');
}
function restore(){const errors=[];try{if(T.original.layout&&PM_HOME_WORKSPACE.astraRestoreSnapshot){const result=PM_HOME_WORKSPACE.astraRestoreSnapshot(T.original.layout);if(!result.ok)throw Error(result.reason||'Layout restore failed');}else restoreChatPlacement();const saved=T.original.widgetState;const n=widget();if(n&&saved){const id=n.dataset.widgetId||n.dataset.widgetKind,size=saved.sizes[id];if(size)PM7_SHELL_ADJUSTMENTS.applyDashSize(n,size.w,size.h,'guided_tour_restore');}const sidebar=$('#chatPanel .chat-thread-sidebar');if(sidebar)sidebar.setAttribute('style',T.original.sidebarStyle||'');}catch(e){errors.push(String(e));}return errors;}
function end(finished=false){if(!T?.active)return;T.keepLayout=!!$('#as-keep-layout')?.checked||T.keepLayout;cancelMotion();clearTimeout(timer);T.dwell.push({step:step().id,ms:Math.round(performance.now()-T.entered)});const errors=T.keepLayout?[]:restore();T.active=false;T.finished=finished;T.restoreErrors=errors;persist();root.hidden=true;root.dataset.open='false';document.documentElement.dataset.astraTour='false';
 // Keep the plan in its real owner surface on completion; restore the prior view on Skip.
 if(!finished){document.documentElement.dataset.astraTourPractice='false';practice?.remove();practice=null;PM_PAGES.go(T.original.page||'dashboard');const item=$(`.chat-thread-item[data-thread="${T.original.thread}"]`);item?.click();}else PM_PAGES.go('wizard');
 if(originalSend){PM_DEMO.chat.send=originalSend;originalSend=null;}const et=$('#chatPanel .toggle-eli5');if(et&&et.classList.contains('active')!==!!T.original.eli5)et.click();const pp=$('#chatPanel .pm6-chat-personabtn');if(pp&&T.original.persona){pp.click();const original=all('.pm6-chat-persona-popout-portal.is-open [data-persona]').find(n=>n.dataset.persona===T.original.persona);if(original)original.click();else pp.click();}const input=$('#chatPanel .pm6-chat-input');if(input){input.value=T.original.input||'';input.placeholder=T.original.placeholder||'';}$('#as-launcher').hidden=false;log(finished?'ui.guided_tour.finish':'ui.guided_tour.skip',errors.length?'restore_needs_attention':'completed',{layout:T.keepLayout?'kept':'restored',buildStarted:false,restoreErrors:errors});
 if(T.original.demoPlaying)PM_DEMO.clock.play();
 if(finished&&practice){practice.insertAdjacentHTML('afterbegin',`<div class="as-note" style="margin-bottom:18px">Guided practice complete. <button class="as-text-btn" data-tour="leave-practice">Start my own plan →</button></div>`);}
}
function handle(e){const b=e.target.closest('[data-tour]');if(!b)return;const action=b.dataset.tour;if(action==='leave-practice'){document.documentElement.dataset.astraTourPractice='false';practice?.remove();practice=null;return;}if(!T?.active)return;e.stopPropagation();if(b.disabled)return;switch(action){case 'show':showMe();break;case 'stop-demo':cancelMotion();guide();break;case 'next':next();break;case 'back':back();break;case 'skip':end(false);break;case 'finish':end(true);break;case 'recover':cancelMotion();prepare();break;case 'fill-question':{const input=$('#chatPanel .pm6-chat-input');if(input){input.value=prompt;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();}break;}default:practiceAction(action,b.dataset.value);}}
function boot(){if(root)return;root=document.createElement('div');root.id='pm7-guided-tour';root.hidden=true;root.dataset.open='false';root.innerHTML='<div class="as-tour-focus"></div><div class="as-tour-cursor"><svg viewBox="0 0 31 36"><path d="M3 2v27l7-7 6 12 6-3-6-11h11Z"/></svg></div><aside class="as-coach" role="region" aria-label="Guided tour"></aside>';document.body.append(root);coach=root.querySelector('.as-coach');ring=root.querySelector('.as-tour-focus');cursor=root.querySelector('.as-tour-cursor');document.addEventListener('click',handle);
 document.addEventListener('click',e=>{if(T?.active&&T.step===1&&e.target.closest('#chatPanel .toggle-eli5'))setTimeout(simplify,0);});document.addEventListener('change',e=>{if(e.target.id==='as-keep-layout'){T.keepLayout=e.target.checked;persist();}});
 document.addEventListener('keydown',e=>{if(T?.active&&e.key==='Escape'){e.preventDefault();e.stopPropagation();if(showing){cancelMotion();guide();}else{cancelMotion();T.active=true;persist();root.hidden=true;root.dataset.open='false';document.documentElement.dataset.astraTour='false';clearTimeout(timer);$('#as-launcher').hidden=false;}}},true);
 window.addEventListener('resize',()=>{if(T?.active)guide();});document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelMotion();clearTimeout(timer);}else if(T?.active&&!root.hidden)observe();});
 if(window.PM_DEMO?.wizard)PM_DEMO.wizard.practice={schema_id:'pm.astra.wizard_practice.v1',dispatch:practiceAction,snapshot:()=>T?copy(T.practice):null,productionMutationDispatched:false};
}
window.PM7_GUIDED_TOUR={schema_id:'pm.astra.guided_tour.v3',concept_simulation_only:true,start,replay:options=>start({...options,replay:true}),resume:()=>start(),next,back,skip:()=>end(false),finish:()=>end(true),showMe,snapshot:()=>T?copy(T):null,storyboard:steps.map(s=>({id:s.id,chapter:s.chapter,title:s.title,planning:s.chapter.startsWith('03')})),recover:prepare};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
