#!/usr/bin/env python3
"""Copy PMConcept7's look tokens into src/bridge/pm7-looks.css so the catalog paints every look with PM7's own colours.

Reads Concepts/PMConcept7.html (never writes it). For each look it takes every custom property that the page's
html[data-theme="<look>"] rules define (all rules, in source order, so later rules win as they do in the page), and the
generated NieR blocks html[data-o55-nier][data-theme="basic-<mode>"]. Only colour, shadow and font tokens are kept.
Rerun after PMConcept7's palette changes:  python3 Concepts/glyph-system/opus-5.5/tools/extract_looks.py
"""
from __future__ import annotations
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]                      # Concepts/
PAGE = ROOT / 'PMConcept7.html'
OUT = HERE.parent / 'src' / 'bridge' / 'pm7-looks.css'
LOOKS = [f'{f}-{m}' for f in ('basic', 'friendly', 'glass', 'retro') for m in ('light', 'dark')]
KEEP = re.compile(r'^--(background|bg|surface[\w-]*|text-[\w-]+|border[\w-]*|accent[\w-]*|graph-[\w-]+|cat-[\w-]+|'
                  r'o55-nier-[\w-]+|elev-[\w-]+|shadow|body-font|display-font|mono-font|font-mono|glass-[\w-]+)$')


def blocks(css: str, selector_re: str):
    for m in re.finditer(selector_re + r'\s*\{', css):
        start = m.end(); depth = 1; i = start
        while depth and i < len(css):
            c = css[i]
            depth += (c == '{') - (c == '}')
            i += 1
        yield css[start:i - 1]


def props(body: str) -> dict:
    body = re.sub(r'/\*.*?\*/', '', body, flags=re.S)
    out = {}
    for k, v in re.findall(r'(--[\w-]+)\s*:\s*([^;{}]+);', body):
        if KEEP.match(k):
            out[k] = v.strip()
    return out


def main() -> None:
    text = PAGE.read_text(encoding='utf-8')
    css = '\n'.join(re.findall(r'<style\b[^>]*>(.*?)</style>', text, flags=re.S))
    lines = ['/* GENERATED by tools/extract_looks.py from Concepts/PMConcept7.html: do not edit by hand. */']
    for look in LOOKS:
        t: dict = {}
        sel = r'(?<![\w\]-])(?:html|:root)?\[data-theme="%s"\](?=\s*\{)' % look
        for b in blocks(css, sel):
            t.update(props(b))
        lines.append(f'html[data-theme="{look}"] {{ ' + ' '.join(f'{k}: {v};' for k, v in t.items()) + ' }')
        print(look, len(t))
    for mode in ('light', 'dark'):
        t = {}
        for b in blocks(css, r'html\[data-o55-nier\]\[data-theme="basic-%s"\](?=\s*\{)' % mode):
            t.update(props(b))
        lines.append(f'html[data-o55-nier][data-theme="basic-{mode}"] {{ ' + ' '.join(f'{k}: {v};' for k, v in t.items()) + ' }')
        print('nier', mode, len(t))
    OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print('wrote', OUT.relative_to(ROOT.parent))


if __name__ == '__main__':
    main()
