#!/usr/bin/env python3
"""Build Concepts/HomeTestPMConcept7.html: the published concept with the universal panel system (review copy).

Usage (from the repository root):
  python3 Concepts/home-redesign/tools/build_home.py              # build and write Concepts/HomeTestPMConcept7.html
  python3 Concepts/home-redesign/tools/build_home.py --out PATH   # build to PATH instead (private builds, workers)
  python3 Concepts/home-redesign/tools/build_home.py --check      # rebuild in memory, lint, syntax, byte parity

The input is opus-5.5 build.build_text(): the exact bytes of TestOpus5.5PmConcept.html and PMConcept7.html (base pin
enforced there). The layer is tools/home_layer.py. The output is generated: never hand-edit it. Publishing into
PMConcept7 is not done here (D28: the planning thread says when).
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
PKG = TOOLS.parent
CONCEPTS = PKG.parent
OPUS_TOOLS = CONCEPTS / 'onboarding' / 'opus-5.5' / 'tools'
sys.path.insert(0, str(OPUS_TOOLS))
sys.path.insert(0, str(TOOLS))

import build  # noqa: E402  (opus-5.5 tools/build.py)
import home_layer  # noqa: E402

TARGET = CONCEPTS / 'HomeTestPMConcept7.html'
INPUT_FILE = CONCEPTS / 'PMConcept7.html'
OLD_TITLE = '<title>TestOpus5.5 · Puppet Master</title>'
NEW_TITLE = '<title>Home panels PM7 · Puppet Master</title>'
HEADER = ('<!-- HomeTestPMConcept7: PMConcept7.html with the universal panel system (Home redesign). Generated by '
          'Concepts/home-redesign/tools/build_home.py from Concepts/home-redesign/src; never hand-edit. -->\n')
MARKERS = [home_layer.CSS_START, home_layer.CSS_END, home_layer.JS_START, home_layer.JS_END,
           '<!-- O55:CSS:START -->', '<!-- O55:CSS:END -->', '<!-- O55:BODY:START -->', '<!-- O55:BODY:END -->',
           '<style id="pm-home-css">', '<script id="pm-home-js">']
# the tour's restore snapshot contract: the anchor stays exactly once (BRIEF 3.9)
EXACTLY_ONCE = ['    failNextPersistenceWrite: function () { faults.failNextWrite = true; },']
KEPT = ['id="pm-home-workspace"', 'id="chatPanel"', 'window.PM_HOME_WORKSPACE', 'o55RestoreSnapshot']


def build_page() -> tuple[str, dict, bool]:
    base = build.build_text()
    input_current = INPUT_FILE.exists() and INPUT_FILE.read_bytes() == base.encode('utf-8')
    text, notes = home_layer.apply(base, build.need)
    text = build.replace_once(text, OLD_TITLE, NEW_TITLE, 'home title')
    return HEADER + text, notes, input_current


def problems_for(text: str) -> list[str]:
    problems = home_layer.lint() + home_layer.syntax_check(text) + build.syntax_check(text)
    for marker in MARKERS:
        if text.count(marker) != 1:
            problems.append(f'marker {marker} appears {text.count(marker)} times')
    for needle in EXACTLY_ONCE:
        if text.count(needle) != 1:
            problems.append(f'{needle.strip()[:60]} appears {text.count(needle)} times (need exactly 1)')
    for kept in KEPT:
        if kept not in text:
            problems.append(f'kept reference missing: {kept}')
    head = text[:text.find('</head>')] if '</head>' in text else text
    # only the page's own <head> title counts (a terminal fixture may hold an HTML file with its own <title>)
    if head.count('<title>') != 1 or NEW_TITLE not in head:
        problems.append('title is not exactly one Home panels title')
    return problems


def report(text: str, notes: dict, target: Path) -> dict:
    data = text.encode('utf-8')
    try:
        shown = str(target.relative_to(CONCEPTS.parent))
    except ValueError:
        shown = str(target)
    return {'output': shown, 'bytes': len(data), 'sha256': hashlib.sha256(data).hexdigest()[:16],
            'input_bytes': notes.get('bytes_in'), 'home_css_bytes': notes.get('home_css_bytes'),
            'home_js_bytes': notes.get('home_js_bytes'), 'terminal_present': notes.get('terminal_present'),
            'nier_selector_patches': notes.get('nier selector patches')}


def main() -> int:
    args = sys.argv[1:]
    check = '--check' in args
    target = TARGET
    if '--out' in args:
        i = args.index('--out')
        if i + 1 >= len(args):
            print('--out needs a path', file=sys.stderr)
            return 2
        target = Path(args[i + 1]).expanduser().resolve()
        if target in (INPUT_FILE.resolve(),):
            print('--out must not be PMConcept7.html', file=sys.stderr)
            return 2
    try:
        text, notes, input_current = build_page()
    except (build.BuildError, ValueError) as exc:
        print(f'BUILD FAILED: {exc}', file=sys.stderr)
        return 2
    problems = problems_for(text)
    if not input_current:
        message = 'Concepts/PMConcept7.html differs from a fresh opus-5.5 build (the published concept is stale)'
        if check:
            problems.append(message)
        else:
            print('WARNING:', message, file=sys.stderr)
    if check:
        if not target.exists():
            problems.append(f'{target.name} is missing; run build_home.py')
        elif target.read_bytes() != text.encode('utf-8'):
            problems.append(f'{target.name} is stale or hand-edited; run build_home.py')
        for p in problems:
            print('CHECK:', p)
        print(json.dumps(report(text, notes, target)))
        print('check', 'ok' if not problems else f'failed ({len(problems)})')
        return 0 if not problems else 1
    if problems:
        for p in problems:
            print('LINT:', p)
        return 1
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_name(target.name + '.tmp')
    tmp.write_text(text, encoding='utf-8')
    tmp.replace(target)
    print(json.dumps(report(text, notes, target)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
