#!/usr/bin/env python3
"""Build Concepts/LeftRailPMConcept7.html: the published concept with the left-rail redesign concepts (review copy).

Usage (from the repository root):
  python3 Concepts/leftrail-redesign/tools/build_rail.py              # build and write Concepts/LeftRailPMConcept7.html
  python3 Concepts/leftrail-redesign/tools/build_rail.py --out PATH   # build to PATH instead (private builds)
  python3 Concepts/leftrail-redesign/tools/build_rail.py --out PATH --only a   # core + concept a only
  python3 Concepts/leftrail-redesign/tools/build_rail.py --check      # rebuild in memory, verify guards and the written file

The input is opus-5.5 build.build_text(): the exact bytes of TestOpus5.5PmConcept.html and PMConcept7.html (base pin
enforced there). The layer is tools/rail_layer.py. The output is generated: never hand-edit it.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
PKG = TOOLS.parent
CONCEPTS = PKG.parent
OPUS_TOOLS = CONCEPTS / 'onboarding' / 'opus-5.5' / 'tools'
sys.path.insert(0, str(OPUS_TOOLS))
sys.path.insert(0, str(TOOLS))

import build  # noqa: E402  (opus-5.5 tools/build.py)
import rail_layer  # noqa: E402

TARGET = CONCEPTS / 'LeftRailPMConcept7.html'
INPUT_FILE = CONCEPTS / 'PMConcept7.html'
OLD_TITLE = '<title>TestOpus5.5 · Puppet Master</title>'
NEW_TITLE = '<title>LeftRail PM7 · Puppet Master</title>'
HEADER = ('<!-- LeftRailPMConcept7: PMConcept7.html with three left-rail redesign concepts and a switcher. Generated by '
          'Concepts/leftrail-redesign/tools/build_rail.py from Concepts/leftrail-redesign/src; never hand-edit. -->\n')
MARKERS = [rail_layer.CSS_START, rail_layer.CSS_END, rail_layer.JS_START, rail_layer.JS_END,
           '<!-- O55:CSS:START -->', '<!-- O55:CSS:END -->', '<!-- O55:BODY:START -->', '<!-- O55:BODY:END -->',
           '<style id="pm-rail-css">', '<script id="pm-rail-js">']
KEPT = ['id="activityBar"', 'id="sidePanelSlot"', 'id="panel-files"', 'id="panel-source"', 'id="panel-docker"',
        'id="panel-search"', 'id="panel-run"', 'id="panel-git"', 'id="panel-artifacts"', 'id="panel-testing"',
        'id="panel-agents"', 'window.PM6_SPROUT', '.pmr-cur:not(.active)']


def build_page() -> tuple[str, dict, bool]:
    base = build.build_text()
    input_current = INPUT_FILE.exists() and INPUT_FILE.read_bytes() == base.encode('utf-8')
    text, notes = rail_layer.apply(base, build.need)
    text = build.replace_once(text, OLD_TITLE, NEW_TITLE, 'left rail title')
    return HEADER + text, notes, input_current


def problems_for(text: str) -> list[str]:
    problems = rail_layer.lint() + rail_layer.syntax_check(text) + build.syntax_check(text)
    for marker in MARKERS:
        if text.count(marker) != 1:
            problems.append(f'marker {marker} appears {text.count(marker)} times')
    for kept in KEPT:
        if kept not in text:
            problems.append(f'kept reference missing: {kept}')
    if text.count('<title>') != 1 or NEW_TITLE not in text:
        problems.append('title is not exactly one LeftRail PM7 title')
    return problems


def report(text: str, notes: dict, target: Path) -> dict:
    data = text.encode('utf-8')
    try:
        shown = str(target.relative_to(CONCEPTS.parent))
    except ValueError:
        shown = str(target)
    return {'output': shown, 'bytes': len(data), 'sha256': hashlib.sha256(data).hexdigest()[:16],
            'input_bytes': notes.get('bytes_in'), 'concepts': notes.get('concepts'),
            'rail_css_bytes': notes.get('rail_css_bytes'), 'rail_js_bytes': notes.get('rail_js_bytes'),
            'nier_selector_patches': notes.get('nier selector patches')}


def main() -> int:
    args = sys.argv[1:]
    check = '--check' in args
    target = TARGET
    if '--out' in args:
        i = args.index('--out')
        if i + 1 >= len(args):
            print('--out needs a path', file=sys.stderr)
            return 2
        target = Path(args[i + 1]).expanduser().resolve()
    if '--only' in args:
        i = args.index('--only')
        rail_layer.ONLY = [x for x in (args[i + 1] if i + 1 < len(args) else '').split(',') if x]
        if check:
            print('--only is for private builds; --check always builds every concept', file=sys.stderr)
            return 2
        if target == TARGET:
            print('--only needs --out (the shared review copy always holds every concept)', file=sys.stderr)
            return 2
    try:
        text, notes, input_current = build_page()
    except build.BuildError as exc:
        print(f'BUILD FAILED: {exc}', file=sys.stderr)
        return 2
    problems = problems_for(text)
    if not input_current:
        message = 'Concepts/PMConcept7.html differs from a fresh opus-5.5 build (the published concept is stale)'
        if check:
            problems.append(message)
        else:
            print('WARNING:', message, file=sys.stderr)
    if check:
        if not target.exists():
            problems.append(f'{target.name} is missing; run build_rail.py')
        elif target.read_bytes() != text.encode('utf-8'):
            problems.append(f'{target.name} is stale or hand-edited; run build_rail.py')
        for p in problems:
            print('CHECK:', p)
        print(json.dumps(report(text, notes, target)))
        print('check', 'ok' if not problems else f'failed ({len(problems)})')
        return 0 if not problems else 1
    if problems:
        for p in problems:
            print('LINT:', p)
        return 1
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding='utf-8')
    print(json.dumps(report(text, notes, target)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
