"""Freeze data-only API/release interface; no reservation, admission or native work."""
import ast,copy,datetime,hashlib,json,pathlib
HERE=pathlib.Path(__file__).resolve().parent;LAB=HERE.parents[1];CASES=LAB/'cases/attempt-successors-v1'
SCORING='6efed6cf4763f91b9674ffaaf35b5c9113decf27663fc38961fcfd140b6883af'
def sha(p):return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def rec(p):return {'path':str(p),'sha256':sha(p)}
def write(p,v):p.write_text(json.dumps(v,indent=2)+'\n')
def main():
 if (HERE/'SOURCE_FREEZE.json').exists():raise ValueError('already frozen; no author mutation')
 draft=json.loads((HERE/'PAIR_CLOSURE_DRAFT.json').read_text());release=json.loads((LAB/'ops/execution-resume-v1/root-production-release-v7.json').read_text());proposal=LAB/'dev/tranche-successor-v8/REMAINING_CELLS.json'
 write(HERE/'SCORING_SCOPE_BINDING.json',{'schema':'pm.er8.opaque-scoring-scope-binding.v1','source':'Root message in current authorized task; existing shared scope digest only','existing_scope_path':str(LAB/'cases/tranche-v2/scoring-only/evaluation-scope.json'),'scoring_contract_sha256':SCORING,'contents_read_by_materializer':False,'meaning':'Existing shared criteria scope, unchanged; not a new numeric-weight scoring contract or evaluator answers.'})
 protocol_pairs=[]
 for p in draft['pairs']:
  p['common_binding']['scoring_contract_sha256']=SCORING
  write(CASES/'pairs'/(p['logical_pair_id']+'.json'),p);protocol_pairs.append(p)
 write(CASES/'pairs.json',{'schema':'pm.er8.attempt-successor-pairs.v1','status':'SOURCE_ONLY_NOT_RESERVED','pairs':protocol_pairs,'classification':'DEVELOPMENT_REPEAT_NOT_FRESH_HOLDOUT'})
 closure_pairs=[]
 for p in protocol_pairs:
  b=p['common_binding'];common={k:b[k] for k in ['route','account','model','pins','task_sha256','brief_sha256','thin_plan_sha256','source_access_sha256','scoring_contract_sha256']}
  closure_pairs.append({'logical_pair_id':p['logical_pair_id'],'attempt_pair_id':p['attempt_pair_id'],'common_binding':common,'arms':p['arms']})
 write(HERE/'DECLARATION_CLOSURE.json',{'schema':'pm.er8.attempt-successor-declaration-closure.v1','frozen':True,'root_authority':False,'campaign_id':'external-research-v8-20261001-2140','original_start_epoch':1790905209,'campaign_deadline_epoch':1791013030.8303788,'caps':{'stage_caps':[1200,1200,900],'case_wall':3600,'case_occupied':5400,'outside_native':300,'responses':160},'proposal':rec(proposal),'development_authority':rec(LAB/'ops/recovery-v1/ATTEMPT_SUCCESSOR_DEVELOPMENT_AUTHORITY_V1.json'),'pairs':closure_pairs,'task_sha256_definition':draft['shared_task_digest_definition'],'shared_stage_template_sha256':draft['shared_stage_template_sha256'],'opaque_scoring_scope_binding':rec(HERE/'SCORING_SCOPE_BINDING.json'),'requested_identity_only':{'account':'existing-authorized-zcode-account-v8-A','model':'GLM5.3FlashMax','actual_account_id':'UNKNOWN','new_provider_verification':False},'classification':'DEVELOPMENT_REPEAT_NOT_FRESH_HOLDOUT','not_a_reservation_or_birth':True,'subset_policy':'Root selects only resource-fitting whole pairs; complete12-case declarations do not promise resources or target completion.','protocol_sha256':{str(p):sha(p) for p in CASES.rglob('*') if p.is_file()},'host_input_sha256':{str(p):sha(p) for p in [HERE/'INPUT_MAP.json',HERE/'OBJECTIVES.json',HERE/'LINEAGE.json']}})
 mapping=json.loads((HERE/'INPUT_MAP.json').read_text())['cases'];planning={str(HERE/'INPUT_MAP.json'):sha(HERE/'INPUT_MAP.json')}
 old_map=LAB/'dev/prospective-timing-v3/INPUT_MAP.json';planning[str(old_map)]=sha(old_map)
 for item in mapping.values():
  manifest=pathlib.Path(item['manifest']);m=json.loads(manifest.read_text());root=pathlib.Path(item['root']);d=pathlib.Path(item['case_dir'])
  for p in [pathlib.Path(item['objectives']),manifest,root/m['brief'],root/m['thin_plan'],root/m['source_access'],d/'METHOD.md',d/'TASK.md',*(root/s['task_template'] for s in m['stages'])]:planning[str(p)]=sha(p)
 write(HERE/'ROOT_RELEASE_PATCH.json',{'schema':'pm.er8.attempt-successor-root-release-interface.v1','accepted':False,'root_authority':False,'launch_authority':'NONE_SOURCE_ONLY','declaration_closure':rec(HERE/'DECLARATION_CLOSURE.json'),'fields_for_new_root_release_after_independent_acceptance':{'case_sources':mapping,'case_queue':list(mapping),'allowed_jobs':[s['reservation_id'] for item in mapping.values() for s in json.loads(pathlib.Path(item['manifest']).read_text())['stages']],'planning_input_sha256':planning},'source_pair_declarations':{p['logical_pair_id']:rec(CASES/'pairs'/(p['logical_pair_id']+'.json')) for p in protocol_pairs},'unchanged_existing_controller':release['controller_snapshot'],'production_entry':release['production_entry'],'unchanged_route_and_account':{'route':release['route'],'pins':release['pins'],'config':release['config'],'account':'existing-authorized-zcode-account-v8-A','model':'GLM5.3FlashMax','actual_account_id':'UNKNOWN'},'binding_constraints':['This is interface data, not an accepted root release, API receipt or admission.','Root must select only whole resource-fitting pairs, subset case_sources/case_queue/allowed_jobs consistently, and preserve exact pairs byte-equivalent to DECLARATION_CLOSURE for reserve-attempt-successors.','Root must independently accept API and full declaration closure before a positive append-only reservation preflight; every queued S8 needs native_starts3, occupied5400 and literal S8-final-correction. No old reservation or birth/cap/job/history/usage reset.','Existing controller can consume new root release.case_sources after separately accepted root append API populates new promises. It never calls reserve-attempt-successors; unchanged legacy admission can read new reservation_by_case rows without modifying existing controller or control.','Its CONTROL.planning_map remains old prospective-timing-v3/INPUT_MAP; required original map pin is included alongside new data pins. The frozen old adapter/resolver select new manifests/objectives via assigned_sources.','No second scheduler while V7 is live. Root must positively establish own V7 scheduler/native/actor/parent/cgroup quiet and settled before new launch.','Keep fixed campaign start/deadline144starts172800occupied, twoZ slots, original output warning1200000 and stop1500000. Warning has crossed per root; declarations promise no extra resources or target completion.','New attempts receive only original assigned brief/plan/method/task protocol. No prior candidate output/capture/critic/history, evaluator contents, sibling discoveries, child launch or stronger-model fallback.','All12 declarations are development repeats with original logical comparison/scoring lineage, not fresh holdouts.'], 'numeric_delta':[1200,1200,900,3600,5400,300,160]})
 print('Finalized exact API closure and source-only release interface; no execution')
if __name__=='__main__':main()
