# Research proposal — local biomedical image review workspace (Brief A)

Stage: research (fresh native integrated). Date of captures: 2026-10-06. All pins are release/doc/API pins verified at capture time; catalogs in `sources.json`, checks in `witnesses.json`, open items in `leads.json`. Labels used throughout: **[FACT]** = from captured public sources; **[INFERENCE]** = engineering inference from facts; **[CHOICE]** = product decision this lab could change; **[VALIDATION-EXECUTED]** = executed by candidate in this stage; **[VALIDATION-PROPOSED]** = proposed, UNEXECUTED.

## 0. V10 release/API binding (selected before recommendations)

The consequential component set is bound coherently at these pins:

- **napari v0.9.2** — GitHub release v0.9.2, published 2026-09-29T22:18:39Z, target commit `595639295a153c84bcb127a9e07d801355440a35` (S1). napari.org docs served for version 0.9.2 (`docsearch:version = 0.9.2` in captured page, S2).
- **tifffile v2026.9.20** — GitHub release v2026.9.20, published 2026-09-21T04:01:35Z (S3). Design requires **≥ v2026.9.15**, the release the maintainer states fixes issue #334 (S8).
- **zarr-python v3.4.0** — GitHub release v3.4.0, published 2026-09-15T20:55:52Z (S4). Release notes list PR #4358, so the atomic-write retry fix is present at this pin (S6, S7).
- **OME-NGFF 0.4 spec** — page states "Final Community Group Report, 1 October 2026", revision meta `a4c68004fdb8a8d822367205dc12f9574a32ddf8` (S9). NGFF 0.4 mandates Zarr v2 layout ("Arrays MUST be defined and stored in a hierarchical organization as defined by version 2 of the Zarr specification"), which is the format-generation compatibility point with the whole ecosystem at these pins.

**[FACT]** These four pins are mutually compatible today: napari's stack consumes tifffile/zarr; NGFF 0.4 requires Zarr v2 layout; tifffile v2026.9.20 reads and writes Zarr-backed arrays. **[INFERENCE]** Pinning is load-bearing because two captured issues show regressions arriving between reader releases (tifffile #334 in 2026.5.2; OME shaped-series behavior change in 2024.8.24, S10/S11): upgrades must be gated, not automatic.

## 1. What the brief needs (coverage map)

Import without rewriting originals · metadata/provenance inspection · nD navigation + channel/window-level display · point/polygon/mask annotation with slice/volume/acquisition scope · explicit visible↔stored↔physical coordinate relationship with round-trip precision · 3 GB bounded access (no second full in-memory copy) on 8-core/16 GB · cancellable long ops with progress · recoverable project under partial import / interrupted save / failed export · identity of sources, relocation, bundle-vs-reference trade-off · styles, keyboard navigation, undo/redo, original-vs-derived distinction, honest export description · accessibility · explicit unsupported-format failure that does not destroy the project.

## 2. Independently useful implementation precedents

**P1 — napari v0.9.2 (viewer + annotation + display-transform precedent).**
**[FACT]** (S1, S2) napari is "a fast, interactive, multi-dimensional image viewer … designed for browsing, annotating, and analyzing large multi-dimensional images … built on top of Qt (for the GUI), vispy (for performant GPU-based rendering), and the scientific Python stack (numpy, scipy)." Its layer system separates image data from display state — the image-layer guide documents contrast limits, opacity, colormaps, blending and interpolation as layer properties (S2) — and its docs include dedicated guides for axis names, unit-aware rendering, axis directions/handedness, performance, threading, and events, plus a Dask tutorial for large datasets and point-annotation tutorials (S2). Version 0.9.2 follows "EffVer" with a monthly release policy (S1).
**Mechanism contributed:** the display-state/data separation is exactly the brief's rule that editing window/level must not alter samples; per-layer transforms (translate/scale) are the model for a layered visible↔stored mapping; shapes/points/labels layers are the annotation geometry vocabulary; the axis-name/unit/handedness guides are prior art for our coordinate-frame documentation.
**Independence:** an end-user application (GUI, GPU renderer), not a storage or format component; its mechanisms live at the view layer, complementing P2/P3.

**P2 — tifffile v2026.9.20 (bounded import + vendor-metadata precedent).**
**[FACT]** (S3) tifffile reads "image and metadata from TIFF, BigTIFF, OME-TIFF, … ImageJ hyperstack, Micro-Manager MMStack and NDTiff …" and — decisive for the 3 GB target — "Image data can be read as NumPy arrays **or Zarr arrays/groups** from strips, tiles, pages (IFDs), SubIFDs, higher order series, and pyramidal levels." Captured issues show it parses OME calibration metadata (`PhysicalSizeX/Y/Z`, `…Unit: 'µm'`, plane positions, S9-search item #261) and Micro-Manager Summary calibration (`PixelSize_um`, `z-step_um`, #334).
**Mechanism contributed:** (a) lazy, chunked, Zarr-backed access into a single large file (the bounded-access path); (b) a metadata extraction layer whose per-format parsers are exactly where calibration ambiguity lives (see chain B).
**Independence:** a format-reading library with no GUI and no display model; it contributes the import boundary only.

**P3 — OME-NGFF 0.4 + zarr-python v3.4.0 (storage/coordinate-metadata contract precedent).**
**[FACT]** (S9) NGFF 0.4 defines: on-disk OME-Zarr hierarchies of multiscale arrays with `"multiscales"` and optional sibling `"labels"` groups (label dims same as image or 1, integers only); `"axes"` metadata — each axis **MUST** have a unique `"name"`, **SHOULD** have `"type"` one of `space`/`time`/`channel` (custom strings allowed), **SHOULD** have a UDUNITS-2 `"unit"` (e.g. `micrometer`, `second`); axis list length **MUST** equal array dimensionality; 2–5D images; a formal **transitional** metadata category for in-the-wild layouts (`bioformats2raw.layout` with `OME/METADATA.ome.xml` under `<MetadataOnly/>`); migration scripts promised between numbered versions.
**Mechanism contributed:** a small, implementable, tool-supported metadata vocabulary for axes + calibration + multiscale derived data — the template for our project's image descriptors and export format.
**Independence:** a storage specification plus a store implementation; contributes the persistence contract, not viewing or format parsing.

**[INFERENCE]** The three are independent along the pipeline (format boundary → storage contract → view layer), so each mechanism can be adopted, swapped, or rejected separately; that is what makes them usable precedents rather than one competitor to clone.

## 3. Issue → fix → regression-test chains

### Chain A (complete): zarr atomic-write rename fragility — zarr-python #3522 → PR #4358 → v3.4.0

**[FACT]** (S5, S6, S7, S4)
- **Failure:** v3 `LocalStore._atomic_write` published files with `tmp_path.replace(path)`; on Windows this intermittently raises `PermissionError [WinError 5]` (and sharing violation 32), aborting otherwise ordinary writes — including metadata (`zarr.json`) writes. Issue #3522. This was a **regression against v2**, whose `DirectoryStore` rename carried a retry (introduced for #597 via #698) that was **not ported** when atomic writes arrived in v3 (#3412).
- **Fix:** PR #4358 (merged 2026-09-15T14:57:41Z; merge commit `6947dd8798925bddf1563e48f1478bb9ffa7e650`; head `4bb856d79c2ecc6f9ef695d2fcccb0d80dbe508b`; 3 files, +146/−4) adds `_move_with_retry` in `src/zarr/storage/_local.py` with bounded delays `(0.0, 0.001, 0.005, 0.02, 0.05, 0.2)` s, retrying **only** `winerror` 5 and 32; the exclusive path's `ERROR_ALREADY_EXISTS` (183) is excluded by construction so "node exists" still propagates. The changes file `changes/3522.bugfix.md` documents it.
- **Regression tests (in the same diff):** `tests/test_store/test_local.py` gains `test_move_with_retry_recovers` (parametrized winerror 5/32 × 1–3 failures), `test_move_with_retry_gives_up` (bounded give-up, destination untouched), `test_move_with_retry_does_not_retry_other_errors` (winerror 2, 3, 183, None), and `test_retry_delays_are_bounded` (sum < 1.0 s; first attempt not delayed).
- **Release applicability:** the v3.4.0 release notes (captured, S4) list "fix(store): retry the LocalStore rename when the destination is busy … in #4358" plus its polish #4359 — so the fix is in **zarr-python ≥ 3.4.0**, and does not apply to v2 (different store code path).
- **Limits of the chain:** the mechanism is proven only for `LocalStore` metadata/chunk file publishes, not for any application's save logic; the PR itself notes the retry tail length is "judgement, not measurement", and the reporter's analysis of the Windows root cause (NTFS tunnelling-like transient denial, reproducible single-threaded) is reported evidence, not a vendor-documented behavior.

**Consequential lesson (adopted in §5.4):** temp-file + rename is the right atomicity primitive, but rename-based publish is platform-fragile in ways that resurface across rewrites. Therefore: (1) never write project state in place — always stage-then-publish; (2) treat rename/publish errors as recoverable (retry bounded, then fall back to retaining the previous good file); (3) on load, **validate** project integrity (schema + hash) instead of trusting that the last write succeeded; (4) keep the previous complete version until the new one validates.

### Chain B (partial — honestly limited): calibration metadata typed as strings — tifffile #334

**[FACT]** (S7-items, S8) Issue #334 (opened and closed 2026-09-15): Micro-Manager 1.4 MMStack OME-TIFFs readable up to tifffile 2026.4.11 crash from 2026.5.2 with `TypeError: bad operand type for abs(): 'str'`, because the new MMStack Z-coordinate parser assumed `Summary['z-step_um']` is numeric; Micro-Manager 1.4 writes it as the JSON **string** `'2.9033'` (archival acquisitions since 2014), while `PixelSize_um` is numeric (0.3625). The issue includes a minimal repro file and a suggested `isinstance` guard. Maintainer (owner) comments: "This will be fixed in the next version of tifffile" and then "**Fixed in v2026.9.15**".
**Chain status:** issue + repro + root cause + maintainer fix/release statement are captured; the **fix commit and regression test were not verifiable** within this stage (maintainer lands changes without PRs; `CHANGES.md` at tag `v2026.9.20` 404'd, as did `README.md` on the branch — negative captures S12/S13). Per the brief's honesty rule, this chain is **not** claimed complete; verifying the regression test at tag is lead L1.

**Consequential lesson (adopted in §4/§5.2):** physical calibration arrives typed inconsistently (strings, unit-suffixed fields, per-format conventions), and **reader releases regress on exactly this code**. The import layer must: coerce/validate every calibration value explicitly; retain the original metadata verbatim beside the normalized values; pin reader versions (≥ 2026.9.15) and gate upgrades.

**Supporting ambiguity evidence [FACT]** (S7-items): #277 — a ZYX volume written with `metadata={'axes':'ZYX'}` is displayed by Fiji as `SizeT=32, SizeZ=1` (axis misread across tools), i.e. downstream disagreement about "same image, same axes" is real and metadata-order-sensitive; #322 — writing TZCYX frame-by-frame made ImageJ group 10 T × 2 Z as 20 Z slices (axes must be declared once for a series, not per page); #270 — an OME write behavior change in 2024.8.24 (trailing-1 dimension trimming) broke a previously working call with `ValueError: shape does not match stored shape` (version-pinned reader/writer behavior matters).

## 4. Data contract (the core proposal)

**[CHOICE]** One project = one directory (see §6) containing `project.json` (version, schema URI), per-image descriptors, annotations, view styles, operation log, and a provenance ledger. Source files are **never modified**: imports open sources read-only and record a sidecar descriptor.

**Image descriptor (per imported source):**
- `image_id` (UUID), `content_sha256` of the source file bytes (identity), original absolute path + project-relative path, import timestamp, importing user.
- `axes`: list of `{name, type: space|time|channel|<custom>, unit}` in **array storage order** — modeled directly on NGFF 0.4 axes (unique names, UDUNITS-2 units) (S9). Space axes carry `{origin, spacing}` (float64) along each axis; the mapping stored-index → physical is `physical = origin + index * spacing` (the scale/translation pattern of NGFF coordinateTransformations at the 0.4 level; full affine is NGFF 0.5 territory — lead L3).
- `raw_metadata`: the format's original metadata **verbatim** (e.g. OME-XML fragment, Micro-Manager Summary JSON), kept for audit; `calibration_status`: `ok | corrected | unknown`, with `correction_record` when the user fixed an import-time ambiguity (explicit correction choice, original retained).
- `access`: `{kind: "chunked", backend: "tifffile-zarr" | "zarr-v2", chunk_shape, decoder_version: "tifffile 2026.9.20"}`.

**Coordinate frames and precision.**
- Three named frame kinds per image: `index` (array indices), `physical` (units per axis), `view` (ephemeral, never stored). Annotations store coordinates **in `index` frame by default** with an explicit `frame` field, plus a cached `physical` projection written at save time for export convenience. Any transform that changes indices (resample, crop, permute) is a **recorded data operation** producing a new derived image with `parent_image_id`, `parent_content_sha256`, operation name/parameters, and its own descriptor — this is the mechanism that answers "do exported annotations still refer to the same image?" by comparison of hashes instead of trust.
- **[VALIDATION-EXECUTED]** W1 (executed by candidate, stdlib-only, isolated component check — see witnesses): float64 values round-trip **exactly** through JSON for representative calibration values (0.3625, 2.9033, 1e-3, …); float32 storage is lossy (−6.25e-5 µm at a 1.2e5 µm stage coordinate; +4.7e-8 µm at a 2.9 µm z-step); converting stored physical coordinates through float32 and back yields up to **177 voxels** of index error on a pathological 3 GB single-axis extent, but **0** index error for realistic 3 GB layouts (54,772² 2D slice; 1442³ volume) at 0.3625 µm sampling. **Conclusion:** store all persisted coordinates/scales in float64 (JSON), use float32 nowhere in the persistence path; float32's sub-voxel behavior at realistic extents does **not** justify losing bit-exact round-trip. **Scope limits:** stdlib arithmetic only, no real component tested; does not establish any application's behavior.

**Annotations.** Each annotation: `id`, `image_id`, `frame` + `axes_binding`, `scope` (`slice` with explicit (t,z) indices / `volume` / `acquisition`), `kind` (`point` | `polygon` | `mask`), geometry (float64), `style_id` → reusable style (color, width, label template), author/timestamp, `derived_from` when it annotates a derived image. Undo/redo is a command log over this store (application-level [CHOICE]; napari's event/action machinery is prior art, S2).

**Exports.** (a) Annotation table (CSV/JSON) with columns: annotation id, image_id, **image content_sha256**, frame, scope, geometry in index and physical coordinates, units, style, provenance — the honest-preservation manifest. (b) Overlay/derived small image written as **OME-Zarr NGFF 0.4** (multiscales + labels group per S9) or 2D PNG, always accompanied by a JSON manifest stating exactly what is preserved (pixels resampled? calibration? annotations?) and what is not.

**Unsupported/ambiguous input behavior.** **[CHOICE]** The support boundary is: TIFF/BigTIFF/plain TIFF, OME-TIFF, ImageJ hyperstack, Micro-Manager MMStack — via tifffile v2026.9.20 — and OME-Zarr NGFF 0.4 reads. Explicitly out: DICOM, vendor formats beyond tifffile's tested subset, non-UDUNITS or absent calibration (importable but flagged `unknown`), >5D arrays (NGFF precedent, S9), palette/complex samples. **[INFERENCE]** An unsupported or ambiguous input triggers a **transactional import**: parse metadata → validate axes/calibration → present explicit correction dialog (user picks axis order/unit/type; original values shown and retained) → stage descriptor → commit. A rejected import leaves only a quarantine note in the project; the project file itself is never half-written (§5.4), and the source is untouched by construction. This mirrors NGFF 0.4's own readers-should-surface-multiple-images guidance and the #334 lesson that ambiguity must be coerced explicitly, not silently.

## 5. Architecture (composed from the precedents)

**[CHOICE]** Six components; bounded alternatives noted.

1. **ImportService** — tifffile ≥ 2026.9.15 pinned (chain B); metadata extraction per §4; read-only file access; per-format parsers quarantined behind one interface so a reader regression (S10/S11) is a contained swap. *Alternative:* Bio-Formats — rejected for v1: JVM dependency and far larger support surface than a 6-person lab can test (the brief forbids promising universal format support).
2. **ArraySource + TileCache** — all image access through a chunked Zarr-array abstraction (tifffile `aszarr` path, S3); LRU tile/chunk cache budget ~1–2 GB, leaving headroom under 16 GB; cooperative cancellation tokens on every long read; progress events. **[VALIDATION-PROPOSED]** the 3 GB target (single pass, no second full copy) is UNEXECUTED here — see W2. **[FACT]** the building blocks (Zarr-group reads from strips/tiles/pages/IFDs/pyramid levels) are documented at the pinned release (S3).
3. **ProjectStore** — `project.json` + attachments; atomic save per §5.4; JSON schema version + migration promise like NGFF's ("migration scripts provided between numbered versions", S9).
4. **Viewer** — **embed napari v0.9.2** as the view component (Qt widget; layers as views over our stores), inheriting nD slicing, channel/window-level, keyboard bindings, and the axis/units/handedness documentation tradition (S1, S2). Display settings bind to layer properties only, never to ArraySource. *Alternative (bounded):* custom Qt+vispy viewer reusing napari's model conventions — defensible only if embedding proves too heavy; it would forfeit a large tested surface.
5. **AnnotationStore** — our own model (§4); napari shapes/points/labels layers are projections of it; styles, scope, undo/redo implemented at store level so they survive viewer swaps.
6. **ExportService** — §4 exports; every export writes its manifest first, data second, and publishes atomically (§5.4), so a failed export cannot corrupt a previous good export.

### 5.4 Atomic save / recovery / identity / relocation / bundles

**[FACT]** Chain A shows rename-publish failing transiently on Windows and returning after bounded retry with regression tests pinning that behavior (S5–S7). **[CHOICE]** Project save algorithm: serialize to `project.json.tmp` → fsync → validate (schema + self-hash) → `os.replace` onto `project.json` → keep previous version as `project.json.bak` until next successful save. Load algorithm: try `project.json`, validate; on failure try `.bak`; on both failing, open the project **read-only recovery mode** with the quarantine list — the user's annotations under the last valid save are intact. Interrupted save thus leaves at most an ignored temp file. The same publish pattern is used for exports. **[INFERENCE]** This is directly informed by Chain A: adopt rename-publish **plus** its two lessons — bounded retry and validate-on-load.

**Identity & relocation:** identity is content (`content_sha256`), not path. On open, each referenced source is checked: hash match → ok; missing → offer re-link (user picks new path, hash must match, else flagged broken); hash mismatch → loud "source changed since import" warning, annotations kept but marked suspect. **[CHOICE]** Default storage = reference to external files (they are multi-GB; copying them into bundles is wasteful), with an explicit "make portable bundle" command that copies sources in and rewrites descriptors — the bundle/reference trade-off is a per-project switch, recorded in the project (bundle projects verify by relative path + hash; reference projects tolerate relocation via re-link).

**Accessibility & honesty surface [CHOICE]:** all actions keyboard-operable (napari keybinding system), status panel with full metadata/error text (no icon-only errors), visible ORIGINAL/DERIVED badge on every layer derived from a recorded operation, and export manifests in plain language.

## 6. Minimum workflow, mapped

1. Create project → ProjectStore init (atomic from first write). 2. Import (multi-file) → ImportService; unsupported input quarantined, project survives. 3. Inspect metadata/provenance → descriptor + `raw_metadata` viewer. 4. Navigate/display → Viewer (channels, window/level, slice/time); display edits touch view state only. 5. Annotate → AnnotationStore with scope; styles; undo/redo. 6. Save/close → atomic publish + validation. 7. Reopen elsewhere → hash-checked relocation; bundle option. 8. Export → table/overlay + manifest; atomic. 9. Verify what transformed → derived-image descriptors carry parent hash + operation; annotation table carries content hashes; comparison is mechanical.

## 7. Opportunities and alternatives

- **Opportunity (adopted):** OME-Zarr NGFF 0.4 as both the derived-image format **and** an optional lazy cache for imported sources — one metadata vocabulary everywhere, free interop with the napari/ome-zarr ecosystem (S9), and a clean migration path to NGFF 0.5 affines later (L3).
- **Alternative (bounded, kept open):** custom Qt viewer replacing embedded napari if embedding hits resource limits on 16 GB machines; the architecture isolates this swap to component 4 because stores and annotations do not depend on napari types.
- **Alternatives recorded, deferred:** SQLite single-file project container (stronger transactions, worse diff/merge for shared-storage exchange — the lab exchanges project folders over ordinary shares); QuPath-style project layout (docs URL attempted 404'd — L2); DICOM import (later).

## 8. Assumptions, unsupported cases, and validation backlog

**Critical assumptions [INFERENCE]:** (1) tifffile's Zarr-group read path delivers interactive chunk latency on local disks — plausible from S3 but **UNEXECUTED** at 3 GB scale (W2); (2) embedded napari handles our annotation scopes without modification — partially, per its nD annotation tutorials (S2), but slice-scoped annotations may need a store-side adapter (untested, W5); (3) 16 GB suffices with a 1–2 GB cache because sources stay chunk-mapped, never fully decoded (design constraint enforced in code review, W2); (4) NGFF 0.4 writers/readers across the pinned tool set agree on axes semantics — evidenced by the spec (S9), not by a cross-tool test (W4).

**Unsupported cases declared:** DICOM; formats outside the tifffile subset we test; >5D; non-UDUNITS calibration (import flagged `unknown`, original metadata retained, physical mapping withheld); float32 persistence anywhere; silent axis-order guessing when metadata is absent (must ask).

**Validation backlog (all UNEXECUTED unless noted):** W1 executed above. W2: 3 GB benchmark (open ≤ N seconds, RSS ≤ envelope, cancel responsiveness). W3: kill -9 during save → reopen via `.bak`; partial-import and failed-export drills. W4: write NGFF 0.4 export → read in second tool (napari) → compare axes/hashes. W5: reopen project on a second machine, diff annotation coordinates bit-exactly. W6: verify tifffile #334 regression test at tag v2026.9.15+ (L1). **Component-check scope limit:** W1 exercises arithmetic only; no executed check establishes full-application behavior, and none is claimed.

## 9. Defect list (what we are explicitly not doing)

No cloud services, no real-time co-editing, no automatic segmentation/registration in v1 (recorded as leads); no universal format promise; no in-place source modification; no silent display-state leakage into samples; no feature parity chase with whole-product competitors (napari/QuPath feature lists are precedent pools, not requirements).
