import pathlib,json,datetime,hashlib
r=pathlib.Path('/home/sittingmongoose/PM-Experiments/er10-20261007-5a126dd5');s=json.loads((r/'state/targeted-cohort2.json').read_text());rows=[];pairs_full=arms_full=passes=0
for id,j in s['jobs'].items():
 row={'case_id':id,'method_id':id.split('-')[1],'disposition':j['state'],'terminal_disposition':j.get('terminal_disposition_v2'),'seed_attempt':j.get('seed_freeze_v2'),'arms':{},'quality_comparison':None,'eligibility':{'filesystem_confinement':'HOLD: explicit maps advisory, no enforced firewall established','blindness':'Method labels remain in frozen contents; independent reviewer cost/target/grade blinded','limitations':j.get('limitations',[])},'review':{k:v for k,v in j.get('review_freeze',{}).items() if k!='files'} if j.get('review_freeze') else None,'quota':{'billing':None,'input_tokens':None,'cached_input_tokens':None,'generated_output_tokens':None,'native_counters':'Preserved in per-stage actual receipts; semantics provider dependent, no double-counting/enclosing addition'}}
 rev=None
 if j.get('review_freeze'):
  rev=json.loads((r/'reviews/targeted-cohort2'/id/'REVIEW.json').read_text());rev['outputs']={v['label']:v for v in rev['outputs']} if isinstance(rev['outputs'],list) else rev['outputs'];row['quality_comparison']=rev.get('comparison',rev.get('independent_comparison'));pairs_full+=int(j['review_freeze'].get('complete_scope_assessed_both',False))
 for arm,label in [('control','Output1'),('treatment','Output2')]:
  f=j.get('arms',{}).get(arm);a={'deliverable':'FROZEN' if f else 'NOT_YET_FROZEN','quality':None,'timing':None}
  if f:
   latency=f.get('arm_dispatch_to_terminal_seconds',f.get('whole_arm_dispatch_to_terminal_seconds',f.get('cold_inclusive_seconds')));a['timing']={'dispatch_to_terminal_stage_seconds':f['dispatch_to_terminal_seconds'],'candidate_cold_inclusive_seconds':latency,'seed_seconds':f.get('cold_seed_seconds',0),'intervening_seed_queue_seconds':f.get('intervening_seed_queue_seconds',0),'within900':latency<=900 if latency is not None else None,'scope':'M04 entire research+handoff+critic critical path; M05 coldseed+intervening queue+refresh; physical occupied intervals separately reconstructible from dispatch/native receipts'};a['final']=f['files'].get('final.md');a['native_lifecycle_limit']=f.get('native_lifecycle_limit',f.get('lifecycle_limit'))
  if rev:
   v=rev['outputs'][label];a['quality']={'source_quality':v['source_quality'],'complete_scope_assessed':v['complete_scope_assessed'],'obligations':v.get('obligation_dispositions'),'defects':[{'id':d.get('id'),'kind':d.get('kind'),'materiality':d.get('materiality'),'assessment':d.get('assessment',d.get('finding'))} for d in v.get('defects',[x for x in rev.get('defects',[]) if label in x.get('outputs',[])])],'useful_deliverable':v.get('useful_deliverable'),'unassessed_remainder':v.get('unassessed_remainder')};arms_full+=int(v['complete_scope_assessed']);passes+=int(v['source_quality']=='PASS')
  row['arms'][arm]=a
 rows.append(row)
b={'schema':'er10.targeted-cohort2.comparisons.v1','status':'TERMINAL_OWNED_SIX' if all(j['state'].startswith('TERMINAL_') for j in s['jobs'].values()) else 'PARTIAL_CHECKPOINT','generated_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'owned_slots':6,'not_entire24slot_track':True,'counts':{'fully_assessed_pairs':pairs_full,'fully_assessed_arms':arms_full,'source_pass_arms':passes,'terminal_dispositions':sum(j['state'].startswith('TERMINAL_') for j in s['jobs'].values()),'noncomparable_seed_overrun_slots':sum(j['state']=='TERMINAL_BLOCKED_SEED_OVERRUN' for j in s['jobs'].values()),'held_route_slots':sum(j['state']=='HOLD_ROUTE' for j in s['jobs'].values()),'queued_capacity_slots':sum(j['state']=='QUEUED_CAPACITY' for j in s['jobs'].values())},'comparison_rules':'Quality/time/quota separate. Both FAIL never means equal quality. No source-supported speedup established from output absence or unequal provenance; one pair descriptive. Raw native counters are not generated tokens/billing. No candidate rescue/retest.','cases':rows};(r/'helpers/targeted-cohort2/COMPARISONS.json').write_text(json.dumps(b,indent=2));print(json.dumps(b['counts']))
