/* Lens presentation and command adapter. State/selection/preview semantics live
 * once in lens-protocol.js. The expanded row is an in-flow header sibling. */
(function(){
 'use strict';const E=window.PM56_EXT,K=window.PM56_LENS_ENGINE;
 const engine=new K.Engine(tid=>{const c=E.ctx(),t=c.state.threads.find(t=>t.id===tid);if(!t)return null;const cp=c.state.context.projections?.[tid];return {...t,epoch:JSON.stringify([cp?.contextEpoch??0,t.messages.filter(m=>m.type==='threadops-rewind').map(m=>m.id)])};});
 const disclosures=new Set();
 const labels={mute:'Mute',focus:'Focus',subcompact:'Subcompact',off:'Off'};
 const descriptions={mute:'Omit selected messages from effective context. Keep their history.',focus:'Protect selected messages and prioritize them for context.',subcompact:'Preview a bounded, source-linked summary before applying it.',off:'Release all shaping and restore the canonical messages.'};
 function s(tid){return engine.snapshot(tid);}
 function refresh(c){c.state.capabilities.context=labels[s(c.thread.id).mode];c.renderApp();c.renderOverlays();}
 function b(c,action,label,attrs='',disabled=''){return '<button class="soft-button" data-action="'+action+'" '+attrs+(disabled?' disabled aria-disabled="true" title="'+c.esc(disabled)+'"':'')+'>'+label+'</button>';}
 function sync(c){const snap=s(c.thread.id);c.state.capabilities.context=labels[snap.mode];return snap;}
 function shapedCount(tid){const l=s(tid);return new Set([...l.ops.filter(o=>o.status==='active').flatMap(o=>o.ids),...(['mute','focus'].includes(l.mode)?l.selection:[])]).size;}
 function result(c,r){if(!r.ok)c.toast('Context Lens',r.error.replaceAll('_',' ')+'. No summary was applied.');refresh(c);}
 E.slot('headerLeading',c=>{const l=sync(c),n=shapedCount(c.thread.id);return '<button class="icon-button pm-lens-trigger'+(l.mode!=='off'?' is-on':'')+'" data-k="lensbtn" data-action="lens-open" data-menu-anchor="pm-lens-trigger" data-lens-mode="'+l.mode+'" data-hover-key="lensbtn" data-hover-tip="Context Lens" aria-label="Context Lens">'+c.icon('lens',16)+(n?'<i class="pm-lens-badge">'+n+'</i>':'')+'</button>';});
 E.slot('contextLensMenu',c=>{const l=sync(c);return '<div class="menu-head"><strong>Context Lens</strong></div>'+['mute','focus','subcompact','off'].map(mode=>'<button class="menu-item'+(mode===l.mode&&mode!=='off'?' active':'')+'" data-action="lens-mode" data-value="'+mode+'"><span class="menu-icon">'+c.icon(mode==='mute'?'eyeoff':mode==='focus'?'lens':mode==='subcompact'?'collapse':'close',14)+'</span><span class="menu-copy"><strong>'+(mode==='off'?'Turn Off':labels[mode])+'</strong><span>'+descriptions[mode]+'</span></span></button>').join('');});
 E.slot('contextLensInline',c=>{const tid=c.thread.id,l=sync(c);if(l.mode==='off')return '';const esc=c.esc,n=l.selection.length,p=l.preview;const opCount=l.ops.filter(o=>o.status==='active').length;
  let html='<section class="lens13-controls" data-k="lens13-controls:'+esc(tid)+'" data-thread="'+esc(tid)+'"><div class="lens13-top"><div><strong>'+c.icon('lens',13)+' '+labels[l.mode]+'</strong><span>'+n+' / '+K.MAX_PER_OP+' selected · '+shapedCount(tid)+' shaped</span></div><div class="lens-actions">';
  html+=l.mode==='subcompact'?b(c,'lens-preview',p?'Refresh preview':'Preview','',''+(!n?'Select messages first':'')):b(c,'lens-seal','Seal operation','',!n?'Select messages first':'');
  html+=b(c,'lens-clear','Clear','',!n?'No active selection':'')+b(c,'lens-mode','Turn Off','data-value="off"')+'</div></div>';
  if(p){html+='<div class="lens13-preview" data-k="preview:'+esc(p.id)+'" data-preview="'+esc(p.id)+'" data-state="'+p.status+'"><header><strong>'+(p.status==='ready'?'Review the summary':'Preview is out of date')+'</strong><span>'+p.ids.length+' sources</span></header>'+(p.status==='ready'?'':'<p class="lens13-warning">The source or selection changed. Refresh the preview before applying.</p>')+'<div class="lens13-excerpts">'+p.excerpts.map(e=>'<p><button class="text-button" data-action="lens-source" data-thread="'+esc(tid)+'" data-id="'+esc(e.id)+'">'+esc(e.label)+'</button><span>'+esc(e.text)+'</span></p>').join('')+'</div><p class="lens13-method">Local source excerpts, not a model-generated summary.'+(p.omittedCharacters?' '+p.omittedCharacters+' characters are omitted; check the full sources.':' Full selected text retained.')+'</p><div class="lens-actions">'+b(c,'lens-apply','Apply summary','data-thread="'+esc(tid)+'" data-preview="'+esc(p.id)+'"',p.status!=='ready'?'Refresh stale preview':'')+b(c,'lens-cancel','Cancel preview')+'</div></div>';}
  if(opCount||l.ops.some(o=>o.status==='stale'))html+='<details class="lens13-operations" data-lens-disclosure="'+esc(tid)+'"'+(disclosures.has(tid)?' open':'')+' data-k="lens13-operations"><summary>Operations · '+opCount+' active</summary>'+l.ops.map(o=>'<div><span>'+labels[o.mode]+' · '+o.ids.length+' messages'+(o.status==='stale'?' · source changed, no longer applied':'')+'</span>'+b(c,'lens-release','Release','data-value="'+esc(o.id)+'"')+'</div>').join('')+'</details>';
  return html+'</section>';
 });
 E.slot('messageAffordance',c=>{const m=c.message;if(!m||m.type!=='text')return '';const tid=c.thread.id,l=s(tid),st=engine.stateOf(tid,m.id),op=engine.covers(tid,m.id),selected=l.selection.includes(m.id),esc=c.esc;if(l.mode==='off'&&!st)return '';
  let out='<i class="pm-lens-mark" data-k="pm-lens-mark"'+(st?' data-lens-state="'+st+'"':'')+(selected?' data-lens-sel="1"':'')+(op?.mode==='subcompact'&&op.ids[0]===m.id?' data-lens-head="1"':'')+'></i>';
  if(l.picking){const reason=op?'Release this operation first':!K.eligible(m)?'Source unavailable':!selected&&l.selection.length>=K.MAX_PER_OP?'25-message operation is full; seal it first':'';out+='<button class="pm-lens-check'+(selected?' is-on':'')+'" data-k="pm-lens-check" data-action="lens-toggle" data-id="'+esc(m.id)+'" role="checkbox" aria-checked="'+selected+'"'+(reason?' disabled title="'+esc(reason)+'"':' title="'+(selected?'Remove from':'Add to')+' selection"')+'>'+c.icon('check',12)+'</button>';}
  if(op&&op.mode!=='subcompact')out+='<div class="pm-lens-flag is-'+st+'" data-k="pm-lens-flag"><span>'+labels[op.mode]+'</span><button class="text-button" data-action="lens-release" data-value="'+esc(op.id)+'">Release</button></div>';
  if(op?.mode==='subcompact'&&op.ids[0]===m.id)out+='<div class="pm-lens-card" data-k="pm-lens-card:'+esc(op.id)+'"><div class="pm-lens-card-head">'+c.icon('collapse',14)+'<strong>'+op.ids.length+' messages · source summary</strong></div><p class="lens13-summary-text">'+esc(op.summary)+'</p><div class="pm-lens-card-actions">'+b(c,op.rehydrated?'lens-collapse':'lens-rehydrate',op.rehydrated?'Collapse again':'Rehydrate sources','data-value="'+esc(op.id)+'"')+b(c,'lens-release','Release operation','data-value="'+esc(op.id)+'"')+'</div><small>'+(op.rehydrated?'Canonical sources restored to effective context.':'Original messages stay in history. Local excerpt summary; no model call.')+'</small></div>';
  return out;
 });
 E.action('lens-open',c=>{if(c.state.menu?.type==='lens')c.closeMenu();else c.openMenu('lens','pm-lens-trigger');c.renderOverlays();return true;});
 E.action('lens-mode',(c,btn)=>{const r=engine.setMode(c.thread.id,btn.dataset.value);c.closeMenu();if(btn.dataset.value==='off'&&r.ok)c.addReceipt('context-mute','Context Lens · Turned off',r.ops+' operations released; '+r.messages+' shaped messages restored. Canonical history is unchanged.');result(c,r);return true;});
 E.action('lens-toggle',(c,btn)=>{result(c,engine.toggle(c.thread.id,btn.dataset.id||btn.dataset.value));return true;});
 E.action('lens-seal',c=>{result(c,engine.seal(c.thread.id));return true;});
 E.action('lens-preview',c=>{result(c,engine.preview(c.thread.id));return true;});
 E.action('lens-apply',(c,btn)=>{if(btn.dataset.thread&&btn.dataset.thread!==c.thread.id){c.toast('Different thread','Return to the preview’s source thread. Nothing was applied.');return true;}const r=engine.apply(c.thread.id,btn.dataset.preview||s(c.thread.id).preview?.id);if(r.ok&&!r.reused)c.addReceipt('context-subcompact','Context Lens · Summary applied',r.count+' messages shaped. The local summary preserves source links; canonical history is unchanged.');result(c,r);return true;});
 E.action('lens-cancel',c=>{result(c,engine.cancel(c.thread.id));return true;});
 E.action('lens-clear',c=>{result(c,engine.clear(c.thread.id));return true;});
 E.action('lens-release',(c,btn)=>{result(c,engine.release(c.thread.id,btn.dataset.value));return true;});
 for(const [a,on] of [['lens-rehydrate',true],['lens-collapse',false]])E.action(a,(c,btn)=>{result(c,engine.rehydrate(c.thread.id,btn.dataset.value,on));return true;});
 E.action('lens-source',(c,btn)=>{if(btn.dataset.thread!==c.thread.id)return true;c.openEditor('lens-source:'+c.thread.id+':'+btn.dataset.id);return true;});
 E.slot('editorTabLabel',c=>c.editorId?.startsWith('lens-source:')?'Lens source':'');
 E.slot('editorDocument',c=>{if(!c.editorId?.startsWith('lens-source:'))return '';const rest=c.editorId.slice(12),t=c.state.threads.find(t=>rest.startsWith(t.id+':'));const id=t?rest.slice(t.id.length+1):'',m=t?.messages.find(m=>m.id===id);return '<article class="editor-doc lens13-source"><small>Canonical source · '+c.esc(t?.title||'Unavailable')+'</small><h1>Full source message</h1><pre>'+c.esc(K.eligible(m)?m.body:'Source unavailable or revoked.')+'</pre><p>Read-only source view. Opening it does not change effective context.</p></article>';});
 function overflow(){const R=window.PM56_MSG_OVERFLOW;if(!R?.register)return;R.register((c,m)=>{if(!K.eligible(m))return [];const op=engine.covers(c.thread.id,m.id);if(op)return [{id:'lens-restore',label:'Restore from Context Lens',detail:'Release the operation, keeping canonical history.',icon:'restore',action:'lens-release',value:op.id}];return ['mute','focus','subcompact'].map(mode=>({id:'lens-start-'+mode,label:labels[mode]+' in Context Lens',detail:descriptions[mode],icon:'lens',action:'lens-start-'+mode,value:m.id}));});}
 overflow();for(const mode of ['mute','focus','subcompact'])E.action('lens-start-'+mode,(c,btn)=>{engine.setMode(c.thread.id,mode);const r=engine.toggle(c.thread.id,btn.dataset.value||btn.dataset.id);window.PM56_MSG_OVERFLOW?.close();c.closeMenu();result(c,r);return true;});
 E.action('set-context-cap',(c,btn)=>{result(c,engine.setMode(c.thread.id,({Mute:'mute',Focus:'focus',Subcompact:'subcompact',Off:'off',Auto:'off'})[btn.dataset.value]||'off'));return true;});
 // Retired canned demo actions now route through the real local preview boundary.
 E.action('apply-subcompact',(c,b)=>E._actions['lens-apply'](c,b));E.action('cancel-subcompact',c=>E._actions['lens-cancel'](c));
 E.chainAction('demo-trigger',(c,b)=>{if(!['Subcompact applied','Subcompact cancelled'].includes(b.dataset.trigger))return false;engine.setMode(c.thread.id,'subcompact');c.toast('Context Lens','Select messages and preview their actual content.');refresh(c);return true;});
 document.addEventListener('toggle',e=>{const id=e.target?.dataset?.lensDisclosure;if(id){if(e.target.open)disclosures.add(id);else disclosures.delete(id);}},true);
 E.chainAction('reset-all',()=>{disclosures.clear();engine.reset();return false;});
 window.PM56_LENS={version:2,engine,MAX_PER_OP:K.MAX_PER_OP,modes:['Mute','Focus','Subcompact','Turn Off'],slice:s,stateOf:(tid,id)=>engine.stateOf(tid,id),isSelected:(tid,id)=>s(tid).selection.includes(id),selection:tid=>s(tid).selection,shapedCount,remaining:tid=>K.MAX_PER_OP-s(tid).selection.length,effectiveHistory:tid=>engine.effective(tid),fork:(a,b)=>engine.fork(a,b),reset:()=>engine.reset()};
})();
