#!/usr/bin/env python3
"""NieR Mode scene art for the 5.6 Pro concept: write or check the generated block in nier-scenes.js.

Usage (from this folder):
  python3 nier_scenes_56.py --write   # regenerate the block between the markers in nier-scenes.js
  python3 nier_scenes_56.py --check   # exit 1 if the block is stale
  [--src DIR]                         # PMConcept7's nier/scenes folder, if it is not at its repository place

The source is PMConcept7's NieR Mode scenes, read where they live in the repository:
Concepts/onboarding/opus-5.5/src/settings/nier/scenes/<key>.svg for city, bunker, desert, forest, park and flooded,
the same six original ink-line panoramas PMConcept7's tools/nier_scenes.py embeds. Each is one ink (currentColor) plus
the ground knockout class `k`, plain shapes and groups only, viewBox 0 0 1600 560. The embedded copy drops the <title>
and line breaks, exactly as PMConcept7's does; nier-scenes.js turns a scene into an image at runtime (the ink and the
ground read from the painted look, so no colour is written into the source).
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_SCENES = HERE.parents[1] / 'onboarding' / 'opus-5.5' / 'src' / 'settings' / 'nier' / 'scenes'
JS_PATH = HERE / 'nier-scenes.js'
KEYS = ['city', 'bunker', 'desert', 'forest', 'park', 'flooded']
BEGIN = '/* ---- generated by nier_scenes_56.py from PMConcept7 nier/scenes/*.svg: do not edit by hand ---- */'
END = '/* ---- end of generated block ---- */'


def src_dir() -> Path:
    if '--src' in sys.argv:
        return Path(sys.argv[sys.argv.index('--src') + 1]).resolve()
    return REPO_SCENES


def embed(text: str) -> str:
    text = re.sub(r'<title>.*?</title>', '', text, flags=re.S)
    return re.sub(r'\s*\n\s*', '', text).strip()


def generate() -> str:
    rows = []
    for key in KEYS:
        path = src_dir() / f'{key}.svg'
        if not path.exists():
            raise SystemExit(f'nier_scenes_56.py: missing {path}')
        text = embed(path.read_text(encoding='utf-8'))
        if 'viewBox="0 0 1600 560"' not in text or 'currentColor' not in text:
            raise SystemExit(f'nier_scenes_56.py: {key}.svg is not a PMConcept7 scene (viewBox 0 0 1600 560, one ink)')
        rows.append(f'    {key}: {json.dumps(text, ensure_ascii=False)}')
    return BEGIN + '\n  var SVG = {\n' + ',\n'.join(rows) + '\n  };\n  ' + END


def check() -> list[str]:
    if not JS_PATH.exists():
        return ['nier-scenes.js is missing']
    js = JS_PATH.read_text(encoding='utf-8')
    if js.count(BEGIN) != 1 or js.count(END) != 1:
        return ['nier-scenes.js: generated-block markers missing or repeated']
    i, j = js.index(BEGIN), js.index(END) + len(END)
    return [] if js[i:j] == generate() else ['nier-scenes.js: the generated block differs from PMConcept7 nier/scenes; run nier_scenes_56.py --write']


def write() -> None:
    js = JS_PATH.read_text(encoding='utf-8')
    if js.count(BEGIN) != 1 or js.count(END) != 1:
        raise SystemExit('nier-scenes.js needs exactly one pair of generated-block markers')
    i, j = js.index(BEGIN), js.index(END) + len(END)
    JS_PATH.write_text(js[:i] + generate() + js[j:], encoding='utf-8')


def main() -> int:
    if '--write' in sys.argv:
        write()
        print('wrote nier-scenes.js')
        return 0
    problems = check()
    for p in problems:
        print('CHECK:', p)
    print('nier scenes', 'ok' if not problems else f'failed ({len(problems)})')
    return 1 if problems else 0


if __name__ == '__main__':
    sys.exit(main())
