#!/usr/bin/env python3
"""NieR Mode palette and type for the 5.6 Pro concept: write or check the generated block in nier.css.

Usage (from this folder):
  python3 nier_palette_56.py --write   # regenerate the block between the markers in nier.css
  python3 nier_palette_56.py --check   # exit 1 if the block is stale or a colour literal sits outside it
  [--src DIR]                          # PMConcept7's nier/ folder, if it is not at its repository place

The source of every colour is PMConcept7's NieR Mode theme, read where it lives in the repository:
Concepts/onboarding/opus-5.5/src/settings/nier/nier-automata.json (SunkenInTime's NieR: Automata theme: `colors` is
light, `variants.dark` is dark), the same file PMConcept7's tools/nier_palette.py reads. The two embedded faces come
from the same folder (fonts/: M PLUS 1 as "PM NieR Sans", JetBrains Mono as "PM NieR Mono", both SIL OFL 1.1, licence
texts beside them). Values are hexes from the JSON, the "r,g,b" of such a hex, rgba() tints of such a hex, or the few
derived values the theme does not have, each marked /* derived */: PMConcept7's olive (success, the warning hue
turned 14 degrees toward green), an umber between the error and warning hues (a sixth ink for the context sources
and the pmx seats), a dim ink for the concept's --subtle, and the six seat inks' 16 % fills. Nothing is colour maths
at runtime (pmx-verify forbids color-mix() in pmx styles; canon F3-426).

The block holds, per mode, at html[data-o55-nier="on"] body[data-theme="basic-<mode>"] (0,2,2), one step above the
concept's own body[data-theme] blocks (0,1,1):
  the base tokens of styles.css (--canvas ... --assistant, --on-accent, fonts, shadows);
  the Chat WOW --tx-* / --fam-* tokens of turn-stage.css;
  the pmx literal tokens of module-shell.css (3.3 and the A1-15 precomputed set, seat fills included);
  the six context source inks of context.css (--ctxseg-*, which the pmx seat hues reuse);
  the NieR helpers PMConcept7's parts code against (--o55-nier-ink, -ink-rgb, -on-ink, -paper ... -shadow-rgb).
nier.css's hand-written rules below the block may use only these tokens (rgba(var(--o55-nier-ink-rgb), a) and
var(--...)); --check fails on a colour literal anywhere outside the block.
"""
from __future__ import annotations

import base64
import colorsys
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_NIER = HERE.parents[1] / 'onboarding' / 'opus-5.5' / 'src' / 'settings' / 'nier'
CSS_PATH = HERE / 'nier.css'
BEGIN = '/* ---- generated by nier_palette_56.py from PMConcept7 nier/nier-automata.json and nier/fonts: do not edit by hand ---- */'
END = '/* ---- end of generated block ---- */'
SEL = 'html[data-o55-nier="on"] body[data-theme="basic-{mode}"]'


def src_dir() -> Path:
    if '--src' in sys.argv:
        return Path(sys.argv[sys.argv.index('--src') + 1]).resolve()
    return REPO_NIER


def theme() -> dict:
    data = json.loads((src_dir() / 'nier-automata.json').read_text(encoding='utf-8'))
    return {'light': data['colors'], 'dark': data['variants']['dark']}


def rgb(h: str) -> tuple[int, int, int]:
    h = h.lstrip('#')
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def hexs(c) -> str:
    return '#' + ''.join(f'{max(0, min(255, round(x * 255))):02x}' for x in c)


def trip(h: str) -> str:
    return ','.join(map(str, rgb(h)))


def a(h: str, alpha) -> str:
    return f'rgba({trip(h)},{alpha})'


def mix(h1: str, h2: str, t: float) -> str:
    """t of h1 over h2, in sRGB (a generator-time literal, never runtime colour maths)."""
    c1, c2 = rgb(h1), rgb(h2)
    return '#' + ''.join(f'{round(x * t + y * (1 - t)):02x}' for x, y in zip(c1, c2))


def turn(warning: str, deg: float, lightness: float, sat: float = 0.9) -> str:
    """PMConcept7's olive recipe, generalised: the warning hue turned by deg, sat x its saturation, at a lightness."""
    h, _l, s = colorsys.rgb_to_hls(*(x / 255 for x in rgb(warning)))
    return hexs(colorsys.hls_to_rgb((h * 360 + deg) / 360 % 1, lightness, s * sat))


def roles(mode: str, c: dict, light: dict) -> dict:
    L = mode == 'light'
    ink = c['accent']
    shadow = trip(light['text'])  # the ink; in dark it is darker than the canvas
    ok = turn(c['warning'], 14, 0.30 if L else 0.56)               # PMConcept7's olive (success)
    ok_text = turn(c['warning'], 14, 0.24 if L else 0.62)
    umber = turn(c['warning'], -22, 0.36 if L else 0.58, 0.75)     # between the error and warning hues
    muted = c['secondaryLabel']
    dim = mix(muted, c['canvas'], 0.62 if L else 0.58)             # --subtle: muted ink toward the paper
    surf = {  # the concept's ramp: dark steps up toward the ink, light keeps its lightest paper for panels
        'canvas': c['canvas'],
        'surface': c['surfaceRaised'] if L else c['surface'],
        'surface-2': c['surface'] if L else c['surfaceRaised'],
        'surface-3': c['secondary'] if L else c['surfaceOverlay'],
        'surface-4': c['sidebarRowHover'] if L else c['toolbarControlHover'],
    }
    border = c['sidebarRowSelected'] if L else c['terminalSelection']
    border_strong = c['border']
    accent2 = c['updateForeground'] if L else c['update']           # the secondary ink ("changed")
    warn_text = c['warningForeground']
    seg = {  # six context source inks, also the pmx seats (module-shell.css body: --pmx-seat-N -> --ctxseg-*)
        1: ink, 2: umber + '  /* derived */', 3: ok + '  /* derived */', 4: c['warning'], 5: muted, 6: c['error'],
    }
    seg_hex = {k: v.split('  ')[0] for k, v in seg.items()}
    seat = {1: seg_hex[2], 2: seg_hex[5], 3: seg_hex[3], 4: seg_hex[6], 5: seg_hex[4], 6: seg_hex[1], 7: accent2, 8: seg_hex[5]}
    pmx_card = c['surfaceRaised'] if L else c['surfaceRaised']
    pmx_sheet = c['surfaceOverlay'] if L else c['surface']
    pmx_floor = c['surface'] if L else c['sidebar']
    pmx_line = c['input'] if L else c['border']
    card_warm = c['warningSurface']
    sh = (lambda n: [.10, .12, .16, .14, .22, .28][n]) if L else (lambda n: [.40, .45, .55, .50, .55, .60][n])
    base = {
        'color-scheme': 'light' if L else 'dark',
        '--canvas': surf['canvas'], '--surface': surf['surface'], '--surface-2': surf['surface-2'],
        '--surface-3': surf['surface-3'], '--surface-4': surf['surface-4'],
        '--text': c['text'], '--muted': muted, '--subtle': dim + '  /* derived: muted ink toward the paper */',
        '--border': border, '--border-strong': border_strong,
        '--accent': ink + '  /* the accent is the ink */', '--accent-2': accent2, '--on-accent': c['accentForeground'],
        '--positive': ok_text + '  /* derived: olive */', '--warning': warn_text, '--danger': c['error'],
        '--glass': a(c['surfaceOverlay'] if L else c['surfaceRaised'], .97), '--code': c['codeBackground'],
        '--user': c['secondary'], '--assistant': surf['surface'],
        '--font-ui': '"PM NieR Sans", Inter, system-ui, sans-serif',
        '--font-mono': '"PM NieR Mono", ui-monospace, "SF Mono", "Cascadia Mono", Menlo, Consolas, monospace',
        '--shadow-float': f'0 18px 50px rgba({shadow},{sh(4)}), 0 4px 14px rgba({shadow},{sh(1)})',
        '--shadow-soft': f'0 8px 24px rgba({shadow},{sh(0)})',
    }
    tx = {
        '--tx-sunken': c['sidebar'],
        '--tx-shadow': f'0 12px 26px -20px rgba({shadow},{sh(5)})',
        '--fam-deliverable': ok_text + '  /* derived */', '--fam-people': c['error'], '--fam-time': warn_text,
    }
    pmx = {
        '--pmx-card': pmx_card, '--pmx-card-warm': card_warm, '--pmx-edge-warm': a(c['warning'], .5),
        '--pmx-wash': a(ink, .10 if L else .12), '--pmx-floor': pmx_floor, '--pmx-line': pmx_line,
        '--pmx-hatch': c['border'] if L else c['terminalSelection'],
        '--pmx-scrim': a(c['canvas'], .55) if L else f'rgba({shadow},.58)',
        '--pmx-sheet-ring': '1px solid var(--border-strong)',
        '--pmx-sheet-shadow': f'0 24px 60px -20px rgba({shadow},{sh(5)})',
        '--pmx-sheet-bg': pmx_sheet,
        **{f'--pmx-seat-fill-{k}': a(v, .16) for k, v in seat.items()},
        '--pmx-seat-fill-lead': a(c['text'], .16), '--pmx-seat-fill-you': a(muted, .16),
        '--pmx-seat-fill-accent': a(ink, .16), '--pmx-seat-fill-warning': a(warn_text, .16),
        '--pmx-focus-edge': a(ink, .55), '--pmx-focus-ring': a(ink, .1), '--pmx-focus-outline': ink,
        '--pmx-grid': a(pmx_line, .14), '--pmx-table-fill': a(pmx_line, .12),
        '--pmx-accent-halo': a(ink, .22), '--pmx-accent-pulse': a(ink, .55), '--pmx-soft-fill': a(c['text'], .04),
        '--pmx-sheen-card': a(pmx_card, .68), '--pmx-sheen-warm': a(card_warm, .72), '--pmx-edge-warm-low': a(c['warning'], .226),
        '--pmx-primary-hover': c['messageActionHover'], '--pmx-mdl-icon-bg': c['secondary'], '--pmx-mdl-icon-edge': border_strong,
    }
    ctx = {f'--ctxseg-{k}': v for k, v in seg.items()}
    helpers = {
        '--o55-nier-ink': ink, '--o55-nier-ink-rgb': trip(ink), '--o55-nier-on-ink': c['accentForeground'],
        '--o55-nier-paper': c['canvas'], '--o55-nier-paper-rgb': trip(c['canvas']),
        '--o55-nier-raised': c['surfaceRaised'], '--o55-nier-overlay': c['surfaceOverlay'], '--o55-nier-secondary': c['secondary'],
        '--o55-nier-hover': c['sidebarRowHover'], '--o55-nier-active': c['sidebarRowActive'], '--o55-nier-selected': c['sidebarRowSelected'],
        '--o55-nier-line-strong': c['input'] if L else c['sidebarBorder'],
        '--o55-nier-ok': ok + '  /* derived */', '--o55-nier-ok-text': ok_text + '  /* derived */', '--o55-nier-ok-surface': a(ok, .18),
        '--o55-nier-warn': c['warning'], '--o55-nier-warn-text': warn_text, '--o55-nier-warn-surface': c['warningSurface'],
        '--o55-nier-error': c['error'], '--o55-nier-error-text': c['errorForeground'], '--o55-nier-error-surface': c['errorSurface'],
        '--o55-nier-code-bg': c['codeBackground'], '--o55-nier-code-fg': c['codeForeground'],
        '--o55-nier-shadow-rgb': shadow,
        '--o55-nier-umber': umber + '  /* derived */', '--o55-nier-dim': dim + '  /* derived */',
    }
    return {'base': base, 'tx': tx, 'pmx': pmx, 'ctx': ctx, 'helpers': helpers}


def block(selector: str, groups: list[tuple[str, dict]]) -> str:
    lines = []
    for note, decls in groups:
        lines.append(f'  /* {note} */')
        for k, v in decls.items():
            value, _, cmt = v.partition('  /* ')
            lines.append(f'  {k}: {value};' + (f' /* {cmt}' if cmt else ''))
    return selector + ' {\n' + '\n'.join(lines) + '\n}'


def fonts() -> str:
    d = src_dir() / 'fonts'
    out = []
    for fam, file, wt in (('PM NieR Sans', 'mplus1-latin-var.woff2', '100 900'), ('PM NieR Mono', 'jetbrains-mono-latin-var.woff2', '100 800')):
        b64 = base64.b64encode((d / file).read_bytes()).decode('ascii')
        out.append(f'@font-face {{ font-family: "{fam}"; font-style: normal; font-weight: {wt}; font-display: swap;\n'
                   f'  src: url(data:font/woff2;base64,{b64}) format("woff2"); }}')
    return '\n'.join(out)


def generate() -> str:
    t = theme()
    out = [BEGIN,
           '/* "PM NieR Sans" = M PLUS 1 (Latin, variable 100-900) and "PM NieR Mono" = JetBrains Mono (Latin, variable 100-800),',
           '   both SIL Open Font License 1.1 (PMConcept7 nier/fonts/OFL-MPLUS1.txt, OFL-JetBrainsMono.txt); used only while NieR Mode is on. */',
           fonts()]
    for mode in ('light', 'dark'):
        r = roles(mode, t[mode], t['light'])
        out.append(block(SEL.format(mode=mode), [
            (f'{mode}: base tokens (styles.css)', r['base']), ('Chat WOW (turn-stage.css)', r['tx']),
            ('pmx literal tokens (module-shell.css 3.3, A1-15)', r['pmx']), ('context source inks (context.css), the pmx seats', r['ctx']),
            ('NieR helpers (PMConcept7 contract names)', r['helpers'])]))
    out.append(END)
    return '\n'.join(out)


COLOR_LITERAL = re.compile(r'#[0-9a-fA-F]{3,8}\b|\brgba?\(\s*\d|\bhsla?\(|\b(white|black)\b')


def check() -> list[str]:
    if not CSS_PATH.exists():
        return ['nier.css is missing']
    css = CSS_PATH.read_text(encoding='utf-8')
    if css.count(BEGIN) != 1 or css.count(END) != 1:
        return ['nier.css: generated-block markers missing or repeated']
    i, j = css.index(BEGIN), css.index(END) + len(END)
    problems = []
    if css[i:j] != generate():
        problems.append('nier.css: the generated block differs from PMConcept7 nier/; run nier_palette_56.py --write')
    for n, line in enumerate((css[:i] + css[j:]).split('\n'), 1):
        code = re.sub(r'/\*.*?\*/', '', line)
        if COLOR_LITERAL.search(code):
            problems.append(f'nier.css: colour literal outside the generated block: {line.strip()[:90]}')
    return problems


def write() -> None:
    css = CSS_PATH.read_text(encoding='utf-8')
    if css.count(BEGIN) != 1 or css.count(END) != 1:
        raise SystemExit('nier.css needs exactly one pair of generated-block markers')
    i, j = css.index(BEGIN), css.index(END) + len(END)
    CSS_PATH.write_text(css[:i] + generate() + css[j:], encoding='utf-8')


def main() -> int:
    if '--write' in sys.argv:
        write()
        print('wrote nier.css')
        return 0
    problems = check()
    for p in problems:
        print('CHECK:', p)
    print('nier palette', 'ok' if not problems else f'failed ({len(problems)})')
    return 1 if problems else 0


if __name__ == '__main__':
    sys.exit(main())
