#!/usr/bin/env python3
"""NieR Mode palette and type for the 5.6 Pro concept: write or check the generated block in nier.css and nier-fonts.js.

Usage (from this folder):
  python3 nier_palette_56.py --write   # regenerate the block between the markers in nier.css
  python3 nier_palette_56.py --check   # exit 1 if the block is stale or a colour literal sits outside it
  [--src DIR]                          # PMConcept7's nier/ folder, if it is not at its repository place

The source of every colour is PMConcept7's NieR Mode theme, read where it lives in the repository:
Concepts/onboarding/opus-5.5/src/settings/nier/nier-automata.json (SunkenInTime's NieR: Automata theme: `colors` is
light, `variants.dark` is dark), the same file PMConcept7's tools/nier_palette.py reads. The two embedded faces come
from the same folder (fonts/: M PLUS 1 as "PM NieR Sans", JetBrains Mono as "PM NieR Mono", both SIL OFL 1.1, licence
texts beside them), written whole into nier-fonts.js. Values are hexes from the JSON, the "r,g,b" of such a hex, rgba() tints of such a hex, or the few
derived values the theme does not have, each marked /* derived */: PMConcept7's olive (success, the warning hue
turned 14 degrees toward green), an umber between the error and warning hues (a sixth ink for the context sources
and the pmx seats), a dim ink for the concept's --subtle, and the six seat inks' 16 % fills. Nothing is colour maths
at runtime (pmx-verify forbids color-mix() in pmx styles; canon F3-426).

The block holds, per mode, at html[data-o55-nier="on"] body[data-theme="basic-<mode>"] (0,2,2), one step above the
concept's own body[data-theme] blocks (0,1,1):
  the base tokens of styles.css (--canvas ... --assistant, --on-accent, fonts, shadows);
  the Chat WOW --tx-* / --fam-* tokens of turn-stage.css;
  the pmx literal tokens of module-shell.css (3.3 and the A1-15 precomputed set, seat fills included);
  the six context source inks of context.css (--ctxseg-*, which the pmx seat hues reuse);
  the NieR helpers PMConcept7's parts code against (--o55-nier-ink, -ink-rgb, -on-ink, -paper ... -shadow-rgb), plus
  -on-ink-rgb (the cursor bar's paper as "r,g,b", so a quiet tone on the bar is a tint of it: neon-icons.css);
and the literal-carrying bits of the parts: the Square pointer part's cursor images (data URIs must carry literal
colours; the part's other rules are in nier-parts.css), the Reboot moment cover's ground and ink per tone
(#o55np-reboot --rb-ground / --rb-text: NieR's canvas and text of the covered look, drawn before the palette is
painted) and the World parts' line art (--o55nw-art-pod / machine / flower / glyphs:
PMConcept7's original drawings from kit.d/20-nier-world.js, the glyph strip from the same seeded generator). nier.css's hand-written rules below the block may use only these tokens (rgba(var(--o55-nier-ink-rgb), a) and
var(--...)); --check fails on a colour literal anywhere outside the block.
"""
from __future__ import annotations

import base64
import colorsys
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_NIER = HERE.parents[1] / 'onboarding' / 'opus-5.5' / 'src' / 'settings' / 'nier'
CSS_PATH = HERE / 'nier.css'
BEGIN = '/* ---- generated by nier_palette_56.py from PMConcept7 nier/nier-automata.json and nier/fonts: do not edit by hand ---- */'
END = '/* ---- end of generated block ---- */'
SEL = 'html[data-o55-nier="on"] body[data-theme="basic-{mode}"]'


def src_dir() -> Path:
    if '--src' in sys.argv:
        return Path(sys.argv[sys.argv.index('--src') + 1]).resolve()
    return REPO_NIER


def theme() -> dict:
    data = json.loads((src_dir() / 'nier-automata.json').read_text(encoding='utf-8'))
    return {'light': data['colors'], 'dark': data['variants']['dark']}


def rgb(h: str) -> tuple[int, int, int]:
    h = h.lstrip('#')
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def hexs(c) -> str:
    return '#' + ''.join(f'{max(0, min(255, round(x * 255))):02x}' for x in c)


def trip(h: str) -> str:
    return ','.join(map(str, rgb(h)))


def a(h: str, alpha) -> str:
    return f'rgba({trip(h)},{alpha})'


def mix(h1: str, h2: str, t: float) -> str:
    """t of h1 over h2, in sRGB (a generator-time literal, never runtime colour maths)."""
    c1, c2 = rgb(h1), rgb(h2)
    return '#' + ''.join(f'{round(x * t + y * (1 - t)):02x}' for x, y in zip(c1, c2))


def turn(warning: str, deg: float, lightness: float, sat: float = 0.9) -> str:
    """PMConcept7's olive recipe, generalised: the warning hue turned by deg, sat x its saturation, at a lightness."""
    h, _l, s = colorsys.rgb_to_hls(*(x / 255 for x in rgb(warning)))
    return hexs(colorsys.hls_to_rgb((h * 360 + deg) / 360 % 1, lightness, s * sat))


def roles(mode: str, c: dict, light: dict) -> dict:
    L = mode == 'light'
    ink = c['accent']
    shadow = trip(light['text'])  # the ink; in dark it is darker than the canvas
    ok = turn(c['warning'], 14, 0.30 if L else 0.56)               # PMConcept7's olive (success)
    ok_text = turn(c['warning'], 14, 0.24 if L else 0.62)
    umber = turn(c['warning'], -22, 0.36 if L else 0.58, 0.75)     # between the error and warning hues
    muted = c['secondaryLabel']
    dim = mix(muted, c['canvas'], 0.62 if L else 0.58)             # --subtle: muted ink toward the paper
    surf = {  # the concept's ramp: dark steps up toward the ink, light keeps its lightest paper for panels
        'canvas': c['canvas'],
        'surface': c['surfaceRaised'] if L else c['surface'],
        'surface-2': c['surface'] if L else c['surfaceRaised'],
        'surface-3': c['secondary'] if L else c['surfaceOverlay'],
        'surface-4': c['sidebarRowHover'] if L else c['toolbarControlHover'],
    }
    border = c['sidebarRowSelected'] if L else c['terminalSelection']
    border_strong = c['border']
    accent2 = c['updateForeground'] if L else c['update']           # the secondary ink ("changed")
    warn_text = c['warningForeground']
    seg = {  # six context source inks, also the pmx seats (module-shell.css body: --pmx-seat-N -> --ctxseg-*)
        1: ink, 2: umber + '  /* derived */', 3: ok + '  /* derived */', 4: c['warning'], 5: muted, 6: c['error'],
    }
    seg_hex = {k: v.split('  ')[0] for k, v in seg.items()}
    seat = {1: seg_hex[2], 2: seg_hex[5], 3: seg_hex[3], 4: seg_hex[6], 5: seg_hex[4], 6: seg_hex[1], 7: accent2, 8: seg_hex[5]}
    pmx_card = c['surfaceRaised'] if L else c['surfaceRaised']
    pmx_sheet = c['surfaceOverlay'] if L else c['surface']
    pmx_floor = c['surface'] if L else c['sidebar']
    pmx_line = c['input'] if L else c['border']
    card_warm = c['warningSurface']
    sh = (lambda n: [.10, .12, .16, .14, .22, .28][n]) if L else (lambda n: [.40, .45, .55, .50, .55, .60][n])
    base = {
        'color-scheme': 'light' if L else 'dark',
        '--canvas': surf['canvas'], '--surface': surf['surface'], '--surface-2': surf['surface-2'],
        '--surface-3': surf['surface-3'], '--surface-4': surf['surface-4'],
        '--text': c['text'], '--muted': muted, '--subtle': dim + '  /* derived: muted ink toward the paper */',
        '--border': border, '--border-strong': border_strong,
        '--accent': ink + '  /* the accent is the ink */', '--accent-2': accent2, '--on-accent': c['accentForeground'],
        '--positive': ok_text + '  /* derived: olive */', '--warning': warn_text, '--danger': c['error'],
        '--glass': a(c['surfaceOverlay'] if L else c['surfaceRaised'], .97), '--code': c['codeBackground'],
        '--user': c['secondary'], '--assistant': surf['surface'],
        '--font-ui': '"PM NieR Sans", Inter, system-ui, sans-serif',
        '--font-mono': '"PM NieR Mono", ui-monospace, "SF Mono", "Cascadia Mono", Menlo, Consolas, monospace',
        '--shadow-float': f'0 18px 50px rgba({shadow},{sh(4)}), 0 4px 14px rgba({shadow},{sh(1)})',
        '--shadow-soft': f'0 8px 24px rgba({shadow},{sh(0)})',
    }
    tx = {
        '--tx-sunken': c['sidebar'],
        '--tx-shadow': f'0 12px 26px -20px rgba({shadow},{sh(5)})',
        '--fam-deliverable': ok_text + '  /* derived */', '--fam-people': c['error'], '--fam-time': warn_text,
    }
    pmx = {
        '--pmx-card': pmx_card, '--pmx-card-warm': card_warm, '--pmx-edge-warm': a(c['warning'], .5),
        '--pmx-wash': a(ink, .10 if L else .12), '--pmx-floor': pmx_floor, '--pmx-line': pmx_line,
        '--pmx-hatch': c['border'] if L else c['terminalSelection'],
        '--pmx-scrim': a(c['canvas'], .55) if L else f'rgba({shadow},.58)',
        '--pmx-sheet-ring': '1px solid var(--border-strong)',
        '--pmx-sheet-shadow': f'0 24px 60px -20px rgba({shadow},{sh(5)})',
        '--pmx-sheet-bg': pmx_sheet,
        **{f'--pmx-seat-fill-{k}': a(v, .16) for k, v in seat.items()},
        '--pmx-seat-fill-lead': a(c['text'], .16), '--pmx-seat-fill-you': a(muted, .16),
        '--pmx-seat-fill-accent': a(ink, .16), '--pmx-seat-fill-warning': a(warn_text, .16),
        '--pmx-focus-edge': a(ink, .55), '--pmx-focus-ring': a(ink, .1), '--pmx-focus-outline': ink,
        '--pmx-grid': a(pmx_line, .14), '--pmx-table-fill': a(pmx_line, .12),
        '--pmx-accent-halo': a(ink, .22), '--pmx-accent-pulse': a(ink, .55), '--pmx-soft-fill': a(c['text'], .04),
        '--pmx-sheen-card': a(pmx_card, .68), '--pmx-sheen-warm': a(card_warm, .72), '--pmx-edge-warm-low': a(c['warning'], .226),
        '--pmx-primary-hover': c['messageActionHover'], '--pmx-mdl-icon-bg': c['secondary'], '--pmx-mdl-icon-edge': border_strong,
    }
    ctx = {f'--ctxseg-{k}': v for k, v in seg.items()}
    helpers = {
        '--o55-nier-ink': ink, '--o55-nier-ink-rgb': trip(ink), '--o55-nier-on-ink': c['accentForeground'], '--o55-nier-on-ink-rgb': trip(c['accentForeground']),
        '--o55-nier-paper': c['canvas'], '--o55-nier-paper-rgb': trip(c['canvas']),
        '--o55-nier-raised': c['surfaceRaised'], '--o55-nier-overlay': c['surfaceOverlay'], '--o55-nier-secondary': c['secondary'],
        '--o55-nier-hover': c['sidebarRowHover'], '--o55-nier-active': c['sidebarRowActive'], '--o55-nier-selected': c['sidebarRowSelected'],
        '--o55-nier-line-strong': c['input'] if L else c['sidebarBorder'],
        '--o55-nier-ok': ok + '  /* derived */', '--o55-nier-ok-text': ok_text + '  /* derived */', '--o55-nier-ok-surface': a(ok, .18),
        '--o55-nier-warn': c['warning'], '--o55-nier-warn-text': warn_text, '--o55-nier-warn-surface': c['warningSurface'],
        '--o55-nier-error': c['error'], '--o55-nier-error-text': c['errorForeground'], '--o55-nier-error-surface': c['errorSurface'],
        '--o55-nier-code-bg': c['codeBackground'], '--o55-nier-code-fg': c['codeForeground'],
        '--o55-nier-shadow-rgb': shadow,
        '--o55-nier-umber': umber + '  /* derived */', '--o55-nier-dim': dim + '  /* derived */',
    }
    return {'base': base, 'tx': tx, 'pmx': pmx, 'ctx': ctx, 'helpers': helpers}


def block(selector: str, groups: list[tuple[str, dict]]) -> str:
    lines = []
    for note, decls in groups:
        lines.append(f'  /* {note} */')
        for k, v in decls.items():
            value, _, cmt = v.partition('  /* ')
            lines.append(f'  {k}: {value};' + (f' /* {cmt}' if cmt else ''))
    return selector + ' {\n' + '\n'.join(lines) + '\n}'


FONTS_PATH = HERE / 'nier-fonts.js'
FACES = (('PM NieR Sans', 'mplus1-latin-var.woff2', '100 900'), ('PM NieR Mono', 'jetbrains-mono-latin-var.woff2', '100 800'))


def fonts_js() -> str:
    """nier-fonts.js, written whole: the two faces as data: URIs for nier.js to add to document.fonts (FontFace) while
    NieR Mode is painted and delete when it is not, so the default themes' font set never contains them (pmx-verify's
    theme-font check lists every face the document carries)."""
    d = src_dir() / 'fonts'
    rows = []
    for fam, file, wt in FACES:
        b64 = base64.b64encode((d / file).read_bytes()).decode('ascii')
        rows.append(f"  {{ family: '{fam}', weight: '{wt}', src: 'url(data:font/woff2;base64,{b64}) format(\"woff2\")' }}")
    return ('/* nier-fonts.js — GENERATED by nier_palette_56.py from PMConcept7 nier/fonts: do not edit by hand.\n'
            ' * OWNER: NieR Mode, step N-A (2026-10-02). The two NieR faces, embedded offline: "PM NieR Sans" is M PLUS 1 (Latin,\n'
            ' * variable 100-900), a free stand-in for the game\'s Fontworks Rodin; "PM NieR Mono" is JetBrains Mono (Latin, variable\n'
            ' * 100-800). Both are under the SIL Open Font License 1.1 (PMConcept7 nier/fonts/OFL-MPLUS1.txt and\n'
            ' * OFL-JetBrainsMono.txt). nier.js adds them to document.fonts only while NieR Mode is painted. */\n'
            'window.PM56_NIER_FACES = [\n' + ',\n'.join(rows) + '\n];\n')


PRESS = ('button', 'a[href]', 'summary', 'select', 'label[for]', '[role="button"]', '[role="tab"]', '[role="menuitem"]',
         '[role="option"]', '[role="switch"]', '[data-action]', 'input[type="checkbox"]', 'input[type="radio"]',
         'input[type="range"]', 'input[type="button"]', 'input[type="submit"]')
TYPE = ('textarea', 'input:not([type])', 'input[type="text"]', 'input[type="search"]', '[contenteditable="true"]')


def pointer(mode: str, c: dict) -> str:
    """The Square pointer part [pointer] (PMConcept7 styles.d/14-nier-parts.css): a small ink square with a notch, a
    hollow one over things you can press; the images are data URIs, so their colours are written out here. One selector
    per pressable kind (shell-selfcheck: no rightmost :is() list); text fields keep the text cursor."""
    ink, rim = c['text'], c['accentForeground']
    enc = lambda h: h.replace('#', '%23')
    head = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 16 16'%3E"
    square = f"%3Cpath d='M1.5 1.5H12.5V8.5H8.5V12.5H1.5Z' fill='{enc(ink)}' stroke='{enc(rim)}' stroke-width='1'/%3E"
    notch = f"%3Cpath d='M4 4H8V8H4Z' fill='{enc(rim)}'/%3E"
    base = f'html[data-o55-nier-parts~="pointer"] body[data-theme="basic-{mode}"]'
    out = [f'{base} {{ cursor: url("{head}{square}%3C/svg%3E") 1 1, auto; }}',
           ',\n'.join(f'{base} {x}' for x in PRESS) + f' {{ cursor: url("{head}{square}{notch}%3C/svg%3E") 1 1, pointer; }}',
           ', '.join(f'{base} {x}' for x in TYPE) + ' { cursor: text; }']
    return '\n'.join(out)


def reboot(t: dict) -> str:
    """The Reboot moment cover (nier-parts.css). It is drawn before the palette is painted, so its ground and ink are
    written here per tone of the look it covers: NieR's canvas (--rb-ground) and NieR's text (--rb-text). The ink's
    r,g,b (--rb-text-rgb) paints the map grid, the hairline and the brackets without color-mix(). tone() in
    nier-parts.js sets data-tone from the covered look."""
    L, D = t['light'], t['dark']
    return '\n'.join([
        f'#o55np-reboot {{ --rb-ground: {L["canvas"]}; --rb-text: {L["text"]}; --rb-text-rgb: {trip(L["text"])}; }}',
        f'#o55np-reboot[data-tone="dark"] {{ --rb-ground: {D["canvas"]}; --rb-text: {D["text"]}; --rb-text-rgb: {trip(D["text"])}; }}'])


def _js_num(n: float) -> str:
    return str(int(n)) if float(n).is_integer() else repr(round(n, 4))


def glyph_strip() -> str:
    """PMConcept7's machine glyphs (kit.d/20-nier-world.js glyphStrip): twenty-one cells of 4 x 4 strokes with small word
    gaps, from the same fixed seed and the same 32-bit generator, so the strip is the same drawing in both apps."""
    def to32(x):
        x &= 0xffffffff
        return x - (1 << 32) if x & 0x80000000 else x
    def imul(a, b):
        return to32((a & 0xffffffff) * (b & 0xffffffff))
    def urs(x, n):
        return (x & 0xffffffff) >> n
    st = {'s': 0x5eed042}
    def rnd():
        st['s'] = to32(st['s'] + 0x6d2b79f5)
        s_ = st['s']
        t_ = imul(s_ ^ urs(s_, 15), 1 | s_)
        t_ = to32(to32(t_ + imul(t_ ^ urs(t_, 7), 61 | t_)) ^ t_)
        return ((t_ ^ urs(t_, 14)) & 0xffffffff) / 4294967296
    d = ''
    for k in range(21):
        if k % 5 == 4:
            continue
        x = k * 6 + 0.5
        j = _js_num
        strokes = [f'M{j(x)} .5V4.5', f'M{j(x + 3)} .5V4.5', f'M{j(x + 1.5)} .5V4.5', f'M{j(x)} .5H{j(x + 3)}', f'M{j(x)} 2.5H{j(x + 3)}',
                   f'M{j(x)} 4.5H{j(x + 3)}', f'M{j(x + 1)} 1.5H{j(x + 2)}V2.5H{j(x + 1)}Z', f'M{j(x)} 4.5L{j(x + 3)} .5']
        n = 2 + int(rnd() * 2)
        used = []
        while len(used) < n:
            i = int(rnd() * len(strokes))
            if i not in used:
                used.append(i)
        d += ''.join(strokes[i] for i in used)
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 126 5" fill="none" stroke="INK" stroke-width="1" stroke-opacity=".42" '
            f'stroke-linecap="square"><path d="{d}"/></svg>')


def art(mode: str, c: dict) -> str:
    """The World parts' line art (nier-world.css: Machine glyphs under the YoRHa headers, Ink empty states), PMConcept7's
    original drawings (kit.d/20-nier-world.js ART) as data: SVG custom properties per mode: an image cannot read a CSS
    variable, so the ink (the theme's text colour) is written into each."""
    from urllib.parse import quote
    open_ = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" stroke="INK" stroke-width="1.6" '
             'stroke-linecap="square" stroke-linejoin="miter">')
    petals = ''.join(f'<path transform="rotate({r} 32 22)" d="M32 22C28.5 17 28.5 11 32 6C35.5 11 35.5 17 32 22Z"/>' for r in (0, 72, 144, 216, 288))
    drawings = {
        'pod': open_ + '<path d="M22 12H42L46 16V40L41 45H23L18 40V16Z M20 19.5H44 M22 36H42 M22 39.5H42 M25 45L27 50H37L39 45"/>'
        + '<path d="M10 20H16V38H10Z M48 20H54V38H48Z M16 25H18 M46 25H48 M13 15V20 M51 15V20"/>'
        + '<path d="M25 25H39V29H25Z" fill="INK" stroke="none"/><path d="M24 57H40" stroke-opacity=".4"/></svg>',
        'machine': open_ + '<path d="M20 11H44V28H20Z M32 11V6 M29 6H35 M28 28V31 M36 28V31 M18 31H46V49H18Z M24 36H40V44H24Z M24 40H40"/>'
        + '<circle cx="27" cy="19.5" r="3"/><circle cx="37" cy="19.5" r="3"/><path d="M26.5 19.5H27.5 M36.5 19.5H37.5"/>'
        + '<path d="M18 35H12V46 M46 35H52V46 M10 46H14 M50 46H54 M23 49V56H29V49 M35 49V56H41V49 M20 56H31 M33 56H44"/></svg>',
        'flower': open_ + '<g>' + petals + '</g><circle cx="32" cy="22" r="2.2" fill="INK" stroke="none"/><path d="M32 25C31 35 33 46 32 58 M22 58H42"/>'
        + '<path d="M31.8 44C26 42.5 22 38 21 33.5C27 34.5 30.5 38.5 31.8 44Z M32.2 50.5C38 49 42 44.5 43 40C37 41 33.5 45 32.2 50.5Z"/></svg>',
        'glyphs': glyph_strip(),
    }
    ink = c['text']
    rows = [f'  --o55nw-art-{k}: url("data:image/svg+xml,{quote(v.replace("INK", ink), safe=chr(45) + "_.!~*()")}");' for k, v in drawings.items()]
    return SEL.format(mode=mode) + ' {\n  /* the World parts\' line art, ' + mode + ' (PMConcept7 kit.d/20-nier-world.js ART) */\n' + '\n'.join(rows) + '\n}'


def generate() -> str:
    t = theme()
    out = [BEGIN,
           '/* The faces ("PM NieR Sans" = M PLUS 1, "PM NieR Mono" = JetBrains Mono, SIL OFL 1.1) are in nier-fonts.js, which',
           '   nier.js adds to document.fonts only while NieR Mode is painted. */']
    for mode in ('light', 'dark'):
        r = roles(mode, t[mode], t['light'])
        out.append(block(SEL.format(mode=mode), [
            (f'{mode}: base tokens (styles.css)', r['base']), ('Chat WOW (turn-stage.css)', r['tx']),
            ('pmx literal tokens (module-shell.css 3.3, A1-15)', r['pmx']), ('context source inks (context.css), the pmx seats', r['ctx']),
            ('NieR helpers (PMConcept7 contract names)', r['helpers'])]))
    for mode in ('light', 'dark'):
        out.append(f'/* the Square pointer part, {mode} */')
        out.append(pointer(mode, t[mode]))
    out.append("/* the Reboot moment cover's ground and ink, per tone (it is drawn before the palette is painted) */")
    out.append(reboot(t))
    for mode in ('light', 'dark'):
        out.append(art(mode, t[mode]))
    out.append(END)
    return '\n'.join(out)


COLOR_LITERAL = re.compile(r'#[0-9a-fA-F]{3,8}\b|\brgba?\(\s*\d|\bhsla?\(|(?<![-\w])(white|black)(?![-\w])')  # not white-space


def check() -> list[str]:
    if not CSS_PATH.exists():
        return ['nier.css is missing']
    css = CSS_PATH.read_text(encoding='utf-8')
    if css.count(BEGIN) != 1 or css.count(END) != 1:
        return ['nier.css: generated-block markers missing or repeated']
    i, j = css.index(BEGIN), css.index(END) + len(END)
    problems = []
    if not FONTS_PATH.exists() or FONTS_PATH.read_text(encoding='utf-8') != fonts_js():
        problems.append('nier-fonts.js differs from PMConcept7 nier/fonts; run nier_palette_56.py --write')
    if css[i:j] != generate():
        problems.append('nier.css: the generated block differs from PMConcept7 nier/; run nier_palette_56.py --write')
    for n, line in enumerate((css[:i] + css[j:]).split('\n'), 1):
        code = re.sub(r'/\*.*?\*/', '', line)
        if COLOR_LITERAL.search(code):
            problems.append(f'nier.css: colour literal outside the generated block: {line.strip()[:90]}')
    return problems


def write() -> None:
    css = CSS_PATH.read_text(encoding='utf-8')
    if css.count(BEGIN) != 1 or css.count(END) != 1:
        raise SystemExit('nier.css needs exactly one pair of generated-block markers')
    i, j = css.index(BEGIN), css.index(END) + len(END)
    CSS_PATH.write_text(css[:i] + generate() + css[j:], encoding='utf-8')
    FONTS_PATH.write_text(fonts_js(), encoding='utf-8')


def main() -> int:
    if '--write' in sys.argv:
        write()
        print('wrote nier.css and nier-fonts.js')
        return 0
    problems = check()
    for p in problems:
        print('CHECK:', p)
    print('nier palette', 'ok' if not problems else f'failed ({len(problems)})')
    return 1 if problems else 0


if __name__ == '__main__':
    sys.exit(main())
