/* Runs real independent protocol modules. No browser, network or production code. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {Engine,MAX_PER_OP}=require('../../lens-protocol.js');
const {Protocol}=require('../../wonderer-protocol.js');
const tests=[];function test(name,fn){try{fn();tests.push({name,status:'pass'});}catch(e){tests.push({name,status:'fail',error:e.stack});}}
const cp=x=>JSON.parse(JSON.stringify(x));
function lens(n=6){const threads={t:{id:'t',projectId:'p',epoch:1,messages:Array.from({length:n},(_,i)=>({id:'m'+i,type:'text',role:i%2?'assistant':'user',body:'Actual source '+i+' with exact constraint.',revision:1}))}};return {threads,e:new Engine(id=>threads[id]),t:threads.t};}
function prep(x){x.e.setMode('t','subcompact');x.e.toggle('t','m0');x.e.toggle('t','m1');return x.e.preview('t').preview;}
function op(x){const p=prep(x);return x.e.apply('t',p.id);}
test('Canonical reader required',()=>assert.throws(()=>new Engine(null)));
test('Unknown mode and thread rejected',()=>{const {e}=lens();assert.equal(e.setMode('t','wrong').ok,false);assert.equal(e.setMode('z','mute').error,'thread_missing');});
test('Off cannot select',()=>assert.equal(lens().e.toggle('t','m0').error,'off'));
test('Selection toggle is reversible',()=>{const {e}=lens();e.setMode('t','mute');e.toggle('t','m1');e.toggle('t','m1');assert.deepEqual(e.snapshot('t').selection,[]);});
test('Mute changes effective context, not source history',()=>{const x=lens(),before=cp(x.t);x.e.setMode('t','mute');x.e.toggle('t','m1');assert(!x.e.effective('t').some(m=>m.id==='m1'));assert.deepEqual(x.t,before);});
test('Focus protects priority but preserves order',()=>{const {e}=lens();e.setMode('t','focus');e.toggle('t','m3');assert.equal(e.effective('t')[3].priority,'high');assert(e.effective('t')[3].protected);assert.deepEqual(e.effective('t').map(m=>m.id),['m0','m1','m2','m3','m4','m5']);});
test('Clear does not release sealed operation',()=>{const {e}=lens();e.setMode('t','mute');e.toggle('t','m1');const x=e.seal('t');e.clear('t');assert.equal(e.operation('t',x.operationId).status,'active');});
test('25-message cap enforced while deselection stays available',()=>{const {e}=lens(27);e.setMode('t','mute');for(let i=0;i<25;i++)assert(e.toggle('t','m'+i).ok);assert.equal(e.toggle('t','m25').error,'cap');assert(e.toggle('t','m0').ok);assert(e.toggle('t','m25').ok);});
test('Sealed sources cannot silently move into another operation',()=>{const x=lens();op(x);x.e.setMode('t','mute');assert.equal(x.e.toggle('t','m0').error,'sealed');});
test('Preview includes actual content and stable source links',()=>{const x=lens(),p=prep(x);assert(p.summary.includes(x.t.messages[0].body));assert.deepEqual(p.ids,['m0','m1']);assert.equal(p.method,'bounded_source_excerpts_not_model_summary');});
test('Preview order follows canonical source not click order',()=>{const {e}=lens();e.setMode('t','subcompact');e.toggle('t','m3');e.toggle('t','m1');assert.deepEqual(e.preview('t').preview.ids,['m1','m3']);});
test('Preview itself does not change effective context',()=>{const x=lens(),before=x.e.effective('t');prep(x);assert.deepEqual(x.e.effective('t'),before);});
test('Cancel has no summary effect',()=>{const x=lens(),p=prep(x);x.e.cancel('t');assert.equal(x.e.apply('t',p.id).error,'preview_missing');assert.equal(x.e.effective('t').length,6);});
test('Apply replaces selected sources only',()=>{const x=lens();op(x);const f=x.e.effective('t');assert.equal(f.length,5);assert.equal(f[0].kind,'summary');assert.equal(f[1].id,'m2');});
test('Repeated Apply reuses original operation and receipt',()=>{const x=lens(),p=prep(x),a=x.e.apply('t',p.id),n=x.e.receipts.length;assert(x.e.apply('t',p.id).reused);assert.equal(x.e.snapshot('t').ops.length,1);assert.equal(x.e.receipts.length,n);assert.equal(x.e.snapshot('t').ops[0].id,a.operationId);});
test('Same-length body change rejects stale Apply',()=>{const x=lens(),p=prep(x);x.t.messages[0].body=x.t.messages[0].body.replace('Actual','actual');assert.equal(x.e.apply('t',p.id).error,'stale_preview');assert.equal(x.e.snapshot('t').ops.length,0);});
for(const [name,change] of [['revision',x=>x.t.messages[0].revision++],['attachments',x=>x.t.messages[0].attachments=['new']],['source references',x=>x.t.messages[0].sourceRefs=['new']],['epoch',x=>x.t.epoch++],['project',x=>x.t.projectId='other'],['selection',x=>x.e.toggle('t','m2')],['mode',x=>x.e.setMode('t','focus')]])test(name+' drift rejects stale Apply',()=>{const x=lens(),p=prep(x);change(x);assert.equal(x.e.apply('t',p.id).ok,false);});
test('Revoked source redacts pending excerpts',()=>{const x=lens();prep(x);x.t.messages[0].revoked=true;const p=x.e.snapshot('t').preview;assert(p.redacted);assert.deepEqual(p.excerpts,[]);assert(!p.summary.includes('Actual'));});
test('Revoked applied source disables stale operation',()=>{const x=lens();op(x);x.t.messages[0].revoked=true;assert(!x.e.effective('t').some(m=>m.kind==='summary'||m.id==='m0'));assert(x.e.snapshot('t').ops[0].redacted);});
test('Deleted thread invalidates and redacts source view',()=>{const x=lens();prep(x);delete x.threads.t;assert.deepEqual(x.e.snapshot('t').preview.excerpts,[]);assert.equal(x.e.snapshot('t').mode,'off');});
test('Duplicate canonical source identity is rejected',()=>{const x=lens();x.t.messages.push(cp(x.t.messages[0]));x.e.setMode('t','subcompact');assert.equal(x.e.toggle('t','m0').ok,false);});
test('Long summary discloses bounded truncation',()=>{const x=lens(25);x.t.messages.forEach(m=>m.body='long source '.repeat(1500));x.e.setMode('t','subcompact');x.t.messages.forEach(m=>x.e.toggle('t',m.id));const p=x.e.preview('t').preview;assert(p.summary.length<=6000);assert(p.omittedCharacters>0);assert(p.excerpts.every(x=>x.omittedCharacters>0));});
test('Rehydrate restores full text without changing source',()=>{const x=lens(),before=cp(x.t),r=op(x);x.e.rehydrate('t',r.operationId,true);assert.equal(x.e.effective('t').length,6);assert.equal(x.e.effective('t')[0].body,x.t.messages[0].body);assert.deepEqual(x.t,before);});
test('Collapse re-applies current summary',()=>{const x=lens(),r=op(x);x.e.rehydrate('t',r.operationId,true);x.e.rehydrate('t',r.operationId,false);assert.equal(x.e.effective('t')[0].kind,'summary');});
test('Release restores sources but leaves mode available',()=>{const x=lens(),r=op(x);x.e.release('t',r.operationId);assert.equal(x.e.effective('t').length,6);assert.equal(x.e.snapshot('t').mode,'subcompact');});
test('Turn Off clears every operation and reports unique affected messages',()=>{const x=lens();op(x);x.e.setMode('t','mute');x.e.toggle('t','m3');const r=x.e.releaseAll('t');assert.equal(r.messages,3);assert.equal(r.ops,1);assert.equal(x.e.snapshot('t').mode,'off');assert.equal(x.e.effective('t').length,6);});
test('Refresh stale preview requires new identity',()=>{const x=lens(),p=prep(x);x.t.messages[0].body+=' revised';const q=x.e.preview('t').preview;assert.notEqual(q.id,p.id);assert.equal(x.e.apply('t',p.id).ok,false);assert(x.e.apply('t',q.id).ok);});
test('Partial branch omits incomplete summary and never copies preview',()=>{const x=lens();op(x);x.e.setMode('t','subcompact');x.e.toggle('t','m2');x.e.preview('t');x.threads.b={...cp(x.t),id:'b',messages:[cp(x.t.messages[0])]};x.e.fork('t','b');assert.equal(x.e.snapshot('b').ops.length,0);assert.equal(x.e.snapshot('b').preview,null);});
test('Full branch copies source-bound operations not mutable identities',()=>{const x=lens();op(x);x.threads.b={...cp(x.t),id:'b'};x.e.fork('t','b');const a=x.e.snapshot('t').ops[0],b=x.e.snapshot('b').ops[0];assert.notEqual(a.id,b.id);assert.equal(b.origin.operationId,a.id);x.e.releaseAll('b');assert.equal(x.e.snapshot('t').ops.length,1);});
test('Thread state isolation',()=>{const x=lens();x.threads.b={...cp(x.t),id:'b'};op(x);assert.equal(x.e.snapshot('b').ops.length,0);});
test('Reset never reuses preview identities',()=>{const x=lens(),p=prep(x);x.e.reset();assert.notEqual(prep(x).id,p.id);});
function wonder(){const a={id:'a',projectId:'p',threadId:'t',version:1,status:'active',content:'source'};const r={id:'r',projectId:'p',threadId:'t',status:'running',definitionRevision:1,stopEpoch:0,participants:[{id:'core',additiveRoleKind:'none'},{id:'w',additiveRoleKind:'wonderer',assignmentRevision:1}],brainstorm:{votes:[{id:'vote'}],dissent:[{id:'dissent'}]}};const q=new Protocol(id=>id==='a'?a:null);q.attach(r,{seed:'seed',seedId:'s',projectId:'p'});q.add(r,{id:'lead',claim:'claim',tether:'connection',dimension:'adjacent',seedId:'s'});return {q,r,a};}
function completed(x,outcome='supports'){const b=x.q.begin(x.r,'lead','a');assert(b.ok);const v={artifactId:'a',outcome,summary:'Observed supplied local sample.'};const result=x.q.complete(x.r,b.ticket.id,v);return {result,b,v};}
test('Wonderer requires additive slot',()=>{const {q,r}=wonder();delete r.wonderer;r.participants=r.participants.slice(0,1);assert.equal(q.attach(r,{seed:'x',seedId:'s'}).error,'wonderer_not_configured');});
test('Wonderer reuses run and never changes core votes or dissent',()=>{const x=wonder(),before=cp(x.r.brainstorm);completed(x);x.q.decide(x.r,'lead','include','supported');assert.deepEqual(x.r.brainstorm,before);assert.equal(x.r.wonderer.defaultVote,'abstain');});
test('Untethered and wrong-seed leads rejected',()=>{const {q,r}=wonder();assert.equal(q.add(r,{id:'b',claim:'x',tether:'',dimension:'x',seedId:'s'}).error,'untethered_lead');assert.equal(q.add(r,{id:'b',claim:'x',tether:'x',dimension:'x',seedId:'wrong'}).ok,false);});
test('Duplicate lead rejected',()=>{const {q,r}=wonder();assert.equal(q.add(r,{id:'lead',claim:'x',tether:'x',dimension:'x',seedId:'s'}).error,'duplicate_lead');});
test('Five-lead budget enforced',()=>{const {q,r}=wonder();for(let i=0;i<4;i++)assert(q.add(r,{id:'l'+i,claim:'c',tether:'t',dimension:'d',seedId:'s'}).ok);assert.equal(q.add(r,{id:'over',claim:'c',tether:'t',dimension:'d',seedId:'s'}).error,'lead_budget');});
test('Hypothesis cannot be included as researched',()=>{const {q,r}=wonder();assert.equal(q.decide(r,'lead','include','because').error,'lead_not_substantiated');assert(!q.convergence(r).ok);});
test('Research records evidence but does not include lead',()=>{const x=wonder();assert(completed(x).result.ok);assert.equal(x.r.wonderer.leads[0].included,false);assert.equal(x.r.wonderer.leads[0].state,'researched');assert(!x.q.convergence(x.r).ok);});
test('Explicit inclusion requires reason',()=>{const x=wonder();completed(x);assert.equal(x.q.decide(x.r,'lead','include','').error,'explicit_reason_required');assert(x.q.decide(x.r,'lead','include','Observed this source').ok);assert(x.q.convergence(x.r).ok);});
test('User decision remains epistemically distinct',()=>{const x=wonder();assert(x.q.decide(x.r,'lead','user_decided','I accept this tradeoff').ok);assert.equal(x.q.convergence(x.r).additions[0].state,'user_decided');assert.equal(x.r.wonderer.leads[0].evidence,null);});
for(const outcome of ['refutes','inconclusive'])test(outcome+' evidence cannot be included as researched',()=>{const x=wonder();completed(x,outcome);assert.equal(x.q.decide(x.r,'lead','include','try').error,'lead_not_substantiated');assert(x.q.decide(x.r,'lead','exclude','Not supported').ok);assert.deepEqual(x.q.convergence(x.r).additions,[]);});
test('Wrong-thread evidence refused',()=>{const x=wonder();x.a.threadId='other';assert.equal(x.q.begin(x.r,'lead','a').error,'evidence_unavailable');});
test('Wrong-project evidence refused',()=>{const x=wonder();x.a.projectId='other';assert.equal(x.q.begin(x.r,'lead','a').error,'evidence_unavailable');});
test('Unknown/revoked source refused',()=>{const x=wonder();assert.equal(x.q.begin(x.r,'lead','missing').ok,false);x.a.status='revoked';assert.equal(x.q.begin(x.r,'lead','a').ok,false);});
test('Pending research cannot double-start or be included',()=>{const x=wonder();x.q.begin(x.r,'lead','a');assert.equal(x.q.begin(x.r,'lead','a').error,'research_pending');assert.equal(x.q.decide(x.r,'lead','user_decided','x').error,'research_pending');});
test('Unknown ticket is never admitted',()=>{const x=wonder();assert.equal(x.q.complete(x.r,'forged',{artifactId:'a',outcome:'supports',summary:'x'}).error,'ticket_missing');});
for(const [name,change] of [['evidence version',x=>x.a.version++],['same-length evidence bytes',x=>x.a.content='Source'],['run epoch',x=>x.r.stopEpoch++],['assignment revision',x=>x.r.participants[1].assignmentRevision++],['seed revision',x=>x.q.seed(x.r,'new seed')],['definition revision',x=>x.r.definitionRevision++],['cancelled run',x=>x.r.status='canceled'],['paused run',x=>x.r.status='paused'],['revoked evidence',x=>x.a.status='revoked']])test(name+' rejects stale callback',()=>{const x=wonder(),b=x.q.begin(x.r,'lead','a');change(x);assert.equal(x.q.complete(x.r,b.ticket.id,{artifactId:'a',outcome:'supports',summary:'x'}).ok,false);assert.equal(x.r.wonderer.leads[0].included,false);assert.equal(x.r.wonderer.rejected.length,1);});
test('Duplicate completion reuses, changed completion rejected',()=>{const x=wonder(),{b,v}=completed(x),n=x.r.wonderer.receipts.length;assert(x.q.complete(x.r,b.ticket.id,v).reused);assert.equal(x.r.wonderer.receipts.length,n);assert.equal(x.q.complete(x.r,b.ticket.id,{...v,summary:'other'}).error,'ticket_consumed');});
test('Evidence change removes earlier inclusion without mutating core',()=>{const x=wonder();completed(x);x.q.decide(x.r,'lead','include','yes');x.a.version++;assert(!x.q.convergence(x.r).ok);assert.equal(x.r.wonderer.leads[0].state,'stale');assert.equal(x.r.wonderer.leads[0].included,false);});
test('Explicit exclusion can dispose stale evidence',()=>{const x=wonder();completed(x);x.a.version++;x.q.refresh(x.r);assert(x.q.decide(x.r,'lead','exclude','Source has changed').ok);assert(x.q.convergence(x.r).ok);});
test('Research again uses current source version',()=>{const x=wonder();completed(x);x.a.version++;x.q.refresh(x.r);assert(completed(x).result.ok);assert.equal(x.r.wonderer.leads[0].evidence.version,2);});
test('Seed change requires retethering and does not relabel prior hypothesis',()=>{const x=wonder();x.q.seed(x.r,'new seed');assert.equal(x.q.begin(x.r,'lead','a').error,'retether_to_current_seed');assert.equal(x.q.decide(x.r,'lead','user_decided','x').ok,false);assert(x.q.retether(x.r,'lead','new claim','new connection').ok);assert(completed(x).result.ok);});
test('Invalid result rejected with pending original ticket retained',()=>{const x=wonder(),b=x.q.begin(x.r,'lead','a');assert.equal(x.q.complete(x.r,b.ticket.id,{artifactId:'a',outcome:'magic',summary:'x'}).error,'invalid_research_result');assert.equal(x.r.wonderer.pending[0].finished,false);});
test('No research implies no provider cost',()=>{const {r}=wonder();assert.equal(r.wonderer.providerCalls,0);assert.equal(r.wonderer.costUsd,null);});
const report={status:tests.every(t=>t.status==='pass')?'pass':'fail',test_count:tests.length,tests};
if(process.argv[2])fs.writeFileSync(process.argv[2],JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report,null,2));process.exitCode=report.status==='pass'?0:1;
