#!/usr/bin/env python3
"""Prospectively bind two matched repository investigations; preparation never dispatches."""
import argparse,hashlib,importlib.util,json
from pathlib import Path
HERE=Path(__file__).resolve().parent
LAB=HERE.parent
CASE=LAB/'evaluation/exports/jj-repo-dev-v1'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(p,v):p.write_text(json.dumps(v,indent=2)+'\n')
def harness():
 p=LAB/'dev/harness-v1-frozen/workspaces.py';s=importlib.util.spec_from_file_location('repo_workspaces',p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
COMMON='''Read inputs/brief.md and inputs/TASK.md and investigate both question families. Select relevant evidence yourself. Deliver a complete current report of approximately five to eight material findings; state exact source versions/locators, supporting mechanism, conditions, counterevidence, integration implications, limitations and unresolved areas. Propose validation as UNEXECUTED. Also write acquisition.json (actual URLs/files/versions/queries/reads and finding links), navigation.json (chronological actual navigation events, elapsed times when known, effort or missing measurements honestly unknown, unresolved/unvisited areas), evidence-chains.json (any chains actually followed, with issue status/capture date, fix commit, code and test paths/lines, version fit, missing links; empty chains are allowed if none followed), and repository-map.json (a built map when the assigned method calls for one; otherwise a JSON record saying not built). The same five output filenames and substantive obligations apply to both arms. Do not execute/build/install third-party source/tests. Use only this Goal's model; no semantic helpers. Do not invent measured timing or test execution.'''
ACCESS='Same frozen public JJ tree at 67c2ae0a9e3e445f034a456b299e3f37c4dc4b93, all 68 issue bodies created 2024-08-01..2024-10-02, all 624 reachable commit patches dated since 2024-07-01, plus read-only official jj-vcs/jj repository/docs/issues/PR/commit/API URLs for missing links. No other repositories or Puppet-Master answer reports. No third-party execution.'
POLICY={
 'T11':{'control':'Use documentation and issue-text summaries as your primary investigation approach. Choose relevant issues yourself, read their descriptions and summarize source-supported lessons with version/status qualifications. You may inspect implementation or tests when you judge necessary; there is no required chain workflow.',
        'treatment':'Choose relevant issues yourself, then explicitly trace each selected material failure claim from issue/report to an actual implementation or fix commit and related test source. Record exact links and missing/unconfirmed links. Distinguish current pinned behavior from fixed historical behavior and open/unconfirmed reports; an issue title or closed status alone does not prove a behavior or resolution. Where no complete chain exists, retain the useful lead as qualified/unresolved.'},
 'T12':{'control':'Start with the official documentation in inputs/repository/docs and navigate from its explanations to implementation paths as needed, using ordinary text searches and ad-hoc source reads. Use your usual documentation-led navigation. Do not build or use a generated repository map in this arm.',
        'treatment':'First run python3 inputs/repo_map_tool.py --tree inputs/repository --pin inputs/PIN.json --output out/repository-map.json. Use the resulting deterministic lexical module/symbol/test map to navigate to implementation paths that answer your independently derived questions, then inspect actual code, documentation and integration neighbors. The map is navigation metadata, never semantic proof. Include its actual first-use indexing cost and omissions in navigation.json.'}}
def prepare(method,family):
 frozen=json.loads((CASE/'MANIFEST.sha256.json').read_text());inputs=[]
 for rel,pin in sorted(frozen.items()):
  p=CASE/rel
  if sha(p)!=pin or p.is_symlink():raise ValueError('freeze changed')
  inputs.append({'source':str(p),'target':rel,'sha256':pin})
 inputs.append({'source':str(CASE/'MANIFEST.sha256.json'),'target':'MANIFEST.sha256.json','sha256':sha(CASE/'MANIFEST.sha256.json')})
 # Same exact input bytes for BOTH arms. Tool use, not tool availability, is the T12 variable.
 if method=='T12':inputs.append({'source':str(HERE/'repo_map_tool.py'),'target':'repo_map_tool.py','sha256':sha(HERE/'repo_map_tool.py')})
 pair=f'{method.lower()}-{family.lower()}-jj-repo-screen-v1';dest=HERE/'pairs'/pair;dest.mkdir(parents=True,exist_ok=False)
 attempts=[];specs=[]
 for arm in ['control','treatment']:
  spec={'job_id':pair+'-'+arm,'method':method,'arm':arm,'family':family,'case_id':CASE.name,'kind':'component','scope':'Both question families in the complete admitted brief and bounded official public source universe. Independent evidence selection.','inputs':[{'source':i['source'],'target':i['target']} for i in inputs],'admitted_inputs':[{'source':i['source'],'sha256':i['sha256']} for i in inputs],'caps':{'seconds':900,'responses':96},'output_files':['report.md','acquisition.json','navigation.json','evidence-chains.json','repository-map.json'],'source_access':ACCESS,'plan_visibility':'Plan-blind integration product brief only; no canon, historical union, keys or other outputs.','evaluation_obligations':'Independent evaluator checks every material current assertion and omission against frozen primary sources; version fit, unsupported claims, useful novel findings, counterevidence, mechanism/integration constraints, full assigned scope and unfinished leads. Grade current report before acquired/history artifacts. Include all cold setup and within-Goal map build costs separately.','zcode_tools':['Read','Write','Bash','WebFetch','WebSearch'],'method_instruction':POLICY[method][arm]+' '+COMMON,'feedback_contract':'No case-specific semantic hints or evaluator answers; ordinary self-correction in this same bounded Goal only.'}
  write(dest/(arm+'.spec.json'),spec);harness().prepare(spec,dest/arm);specs.append(spec)
  attempts.append({'job_id':spec['job_id'],'arm':arm,'attempt':str(dest/arm),'spec':str(dest/(arm+'.spec.json'))})
 assert specs[0]['inputs']==specs[1]['inputs'] and specs[0]['output_files']==specs[1]['output_files']
 held=['Exact shared source bytes/access','Full brief/task obligations','Model family/front end/Max effort','900 seconds/96 responses per arm including retries/self-correction','Equal final artifacts/evaluation','No tests or third-party source execution','No case answer list or plan exposure']
 card={'schema':'er7.method_pair.v1','pair_id':pair,'method':method,'family':family,'case_id':CASE.name,'status':'prepared-not-reviewed-not-started','changed_variables':['Issue-summary-first policy versus issue→implementation/fix→test chaining' if method=='T11' else 'Documentation-led navigation versus deterministic local module/symbol/test-map navigation'],'held_fixed':held,'caps_per_arm':{'seconds':900,'responses':96},'attempts':attempts,'input_sha256':{i['target']:i['sha256'] for i in inputs},'source_unique_bytes':sum(Path(i['source']).stat().st_size for i in inputs),'versions':{p.name:sha(p) for p in [HERE/'prepare_pairs.py',HERE/'repo_map_tool.py']},'review_required':'Independent review of exact mechanics/cards/tool and paired boundary before dispatch. Author cannot grade this method.','order':'Operator chooses reproducible randomized/counterbalanced launch order, records simultaneous family/account/sibling occupancy.','setup_accounting':str(LAB/'evaluation/private/jj-repo-dev-v1-acquisition'),'interpretability':'One bounded development comparison per method; no unit/offline check counted as a comparison.'}
 write(dest/'pair.json',card);return {'pair':str(dest/'pair.json'),'pair_sha256':sha(dest/'pair.json'),'attempts':attempts}
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--family',choices=['M','Z','L'],default='Z');a=p.parse_args();print(json.dumps([prepare(x,a.family) for x in ['T11','T12']],indent=2))
