window.B17_CASES=(()=>{
 const P=PM56_PLANS,E=PM56_EXT,W=PM56_B16_WORK,TX=PM56_TX;
 function setup(){E._actions['b16-start'](E.ctx(),{dataset:{flow:'parallel'}});document.querySelector('[data-action="send"]').click();const w=W.snapshot(),p=P.get(w.planId);const out=P.build({plan_id:p.plan_id,expected:P.admissionSnapshot(p.plan_id),paused:true});if(!out.ok)throw Error(out.error);return {p,w};}
 const cases={
  missing_recovery_owner_is_not_success:ck=>{const {p}=setup();p.attention={kind:'failed',reason:'Test owner has no retry implementation',actions:['retry','details','cancel']};const before=JSON.stringify(p),out=P.recoveryCommand({expected:P.recoverySnapshot(p.plan_id),action:'retry',idempotency_key:'no-owner'});ck('Retry without owner implementation is refused',!out.ok&&out.error==='owner_recovery_unavailable');ck('No fake attempt counter or state change',JSON.stringify(p)===before);},
  stale_attention_request:ck=>{const {p}=setup(),expected=P.recoverySnapshot(p.plan_id);p.attention.reason='New owner condition';const before=JSON.stringify(p),out=P.recoveryCommand({expected,action:'resume',idempotency_key:'stale'});ck('Older rendered request is fenced',!out.ok&&out.error==='stale_recovery_request');ck('Newer condition survives',JSON.stringify(p)===before);},
  same_binding_resume:ck=>{const {p}=setup(),run=p.approved.plan_run_id,req={expected:P.recoverySnapshot(p.plan_id),action:'resume',idempotency_key:'resume-one'},out=P.recoveryCommand(req);ck('Resume uses the current owner',out.ok);ck('No duplicate PlanRun',p.approved.plan_run_id===run);ck('Callback fence advances',p.runEpoch===req.expected.epoch+1);ck('Primary control stays Building',P.buildLabel(p.plan_id)==='Building…');ck('Replay returns original receipt',P.recoveryCommand(req).replayed===true);},
  quota_secondary_truth:ck=>{const {p}=setup();p.attention={kind:'quota_wait',reason:'Provider reset unavailable',actions:['details','cancel']};ck('Quota owner spelling is not silently hidden',P.attention(p.plan_id).line==='Waiting for Usage');ck('No fifth primary label',P.buildLabel(p.plan_id)==='Building…');}
 };
 const A=PM56_ARTIFACTS,D=PM56_DATA;
 function pub(id='test-art',v=1,extra={}){const q={artifact_id:id,artifact_version:v,project_id:'test-project',thread_id:'test-thread',title:'Exact test revision',renderer_kind:'code',content:'version '+v,...extra};const out=A.publish(q);if(!out.ok)throw Error(out.error);return q;}
 Object.assign(cases,{
  document_shared_immutable_tree:ck=>{const {p}=setup(),ref=P.documentRef(p.plan_id),x=A.resolve(ref,{document:true}),md=P.markdown(p.plan_id);ck('Plan revision is one shared artifact tree',x.ok&&x.revision.record.blocks===p.revisions[p.version]);let denied=false;try{p.revisions[p.version].push({t:'paragraph',text:'Not allowed'});}catch(e){denied=true;}ck('Approved structured bytes reject mutation',denied&&P.markdown(p.plan_id)===md);ck('Stable block identities are present and unique',new Set(p.revisions[p.version].map(b=>b.block_id)).size===p.revisions[p.version].length);ck('Thread reference prevents artifact purge',A.purge(ref).error==='artifact_still_referenced');},
  immutable_artifact_collision:ck=>{const q=pub(),before=JSON.stringify(D.artifacts),out=A.publish({...q,content:'replacement'});ck('Same-version replacement rejected',!out.ok&&out.error==='immutable_revision_conflict');ck('Rejected publication writes nothing',JSON.stringify(D.artifacts)===before);ck('Identical publication is idempotent',A.publish(q).replayed===true);},
  exact_artifact_open:ck=>{const q=pub();pub('test-art',2);const ref={artifact_id:q.artifact_id,artifact_version:1,project_id:q.project_id,thread_id:q.thread_id};ck('V1 resolves after V2 exists',A.resolve(ref).revision.record.content==='version 1');ck('Unknown V3 never resolves latest',A.resolve({...ref,artifact_version:3}).error==='missing');ck('Wrong thread refused',A.resolve({...ref,thread_id:'different'}).error==='denied');ck('Wrong renderer refused',A.resolve({...ref,renderer_kind:'chart'}).error==='renderer_kind_mismatch');ck('Exact navigation round trip',JSON.stringify(A.fromRoute(A.route(ref)))===JSON.stringify(ref));},
  untrusted_content_is_text:ck=>{const q=pub('hostile',1,{content:'<script>window.parent.compromised=true</script><img onerror=alert(1)>'});const html=A.render(q);ck('Arbitrary HTML is escaped',html.includes('&lt;script&gt;')&&!html.includes('<script>'));const unsupported=pub('cad',1,{renderer_kind:'cad'});ck('Unknown renderer has explicit unavailable block',A.render(unsupported).includes('No registered renderer'));const interactive=pub('bad-interactive',1,{renderer_kind:'interactive',payload:{columns:['Item'],rows:[['one']]},origin:'untrusted',capabilities:['filter_table']});ck('Data cannot grant an untrusted origin execution',A.render(interactive).includes('renderer_capability_denied'));},
  frozen_static_fallback:ck=>{const base=pub('static-table',1,{renderer_kind:'table',payload:{columns:['Version'],rows:[['ONE']]}});pub('static-table',2,{renderer_kind:'table',payload:{columns:['Version'],rows:[['TWO']]}});const q=pub('interactive-table',1,{renderer_kind:'interactive',payload:{columns:['Version'],rows:[['ONE']]},origin:'pm-local-renderer',capabilities:['filter_table'],static_fallback_ref:{artifact_id:'static-table',artifact_version:1}}),html=A.render(q,{print:true});ck('Print has static data from exact fallback',html.includes('ONE')&&!html.includes('TWO'));ck('Print contains no iframe or executable script',!html.includes('<iframe')&&!html.includes('<script'));ck('Static fallback kind is stated',html.includes('Interactive table · static fallback'));},
  availability_is_owner_derived:ck=>{const q=pub(),a=D.artifacts.find(a=>a.id===q.artifact_id);a.revisionAvailability={1:'denied'};ck('Permission denial is not overridden by saved bytes',A.resolve(q).error==='denied');a.revisionAvailability={1:'stale'};ck('Stale input is explicitly disclosed',A.render(q).includes('Unavailable · stale'));a.revisionAvailability={1:'available'};ck('Restored access returns exact retained revision',A.resolve(q).revision.record.content==='version 1');}
 });return cases;
})();
// Further checks exercise the actual Batch 17 execution adapter and shared owners.
(()=>{
 const W=PM56_B17_WORK,P=PM56_PLANS,T=PM56_TODOS,E=PM56_EXT,A=PM56_ARTIFACTS,D=PM56_DATA;
 const clone=x=>JSON.parse(JSON.stringify(x));
 const action=(name,data)=>E._actions[name](E.ctx(),{dataset:data});
 const wait=async fn=>{for(let n=0;n<500;n++){if(fn())return;await new Promise(r=>setTimeout(r,40));}throw Error('Timed out waiting for actual owner');};
 function setup(flow='recovery',build=true){W.start(flow);document.querySelector('[data-action="send"]').click();const r=W.records()[W.snapshot().id],p=P.get(r.planId);if(build){const o=P.build({plan_id:p.plan_id,expected:P.admissionSnapshot(p.plan_id)});if(!o.ok)throw Error(o.error);}return {r,p};}
 const saved=(r,p)=>JSON.stringify({r,p,todos:T.get(r.threadId),bindings:T.bindings(r.threadId),artifacts:D.artifacts,runs:P.runs()});
 Object.assign(B17_CASES,{
  actual_failed_lookup_and_retry:async ck=>{const {r,p}=setup();await wait(()=>p.attention?.kind==='failed');
   const originalRun=p.approved.plan_run_id,done=clone(r.outputs.normalize),doneBinding=clone(T.bindings(r.threadId).find(b=>b.work_id.endsWith(':normalize'))),failed=clone(r.failure),before=saved(r,p),expected=P.recoverySnapshot(p.plan_id);
   const denied=P.recoveryCommand({expected,action:'retry',idempotency_key:'missing-input'});
   ck('Actual missing-input Retry is refused',!denied.ok&&denied.error==='rate_input_disconnected');ck('Failed Retry publishes no speculative artifacts, run or To-Do changes',saved(r,p)===before);
   action('b17-reconnect',{work:r.id});const request={expected:P.recoverySnapshot(p.plan_id),action:'retry',idempotency_key:'actual-retry'},out=P.recoveryCommand(request);
   ck('Actual new attempt admission succeeds',out.ok);ck('Same PlanRun and original completed output retained',p.approved.plan_run_id===originalRun&&JSON.stringify(r.outputs.normalize)===JSON.stringify(done));
   ck('Completed work binding is byte-exact',JSON.stringify(T.bindings(r.threadId).find(b=>b.work_id.endsWith(':normalize')))===JSON.stringify(doneBinding));
   const now=T.bindings(r.threadId).filter(b=>b.work_id.endsWith(':total'));ck('Failed attempt retained, attempt 2 newly bound to the same work identity',now.length===2&&now[0].binding_id===failed.binding_id&&now[0].state==='failed'&&now[1].attempt_id==='attempt2'&&now[0].work_id===now[1].work_id);
   const replay=P.recoveryCommand(request);ck('Identical retry replay returns receipt without third attempt',replay.replayed&&T.bindings(r.threadId).filter(b=>b.work_id.endsWith(':total')).length===2);
   await wait(()=>p.status==='completed');const total=A.resolve(r.outputs.total).revision.record.payload,validation=A.resolve(r.outputs.validate).revision.record.payload;
   ck('Independent test oracle: exact grand total is 9532 cents',total.total_cents==='9532'&&validation.total_cents==='9532'&&validation.passed===true);
   ck('All required To-Dos completed from accepted item evidence',T.outcomeSummary(r.threadId,p.requiredTodoIds).ok);ck('One normalization attempt only',r.attempts.filter(x=>x.stage==='normalize').length===1);
   ck('No Goal, phase tree, WorkNodes or Orchestrator entry',PM56_GOAL.get()===null&&P.worknodes().length===0&&!P.orchestrator().entered);
  },
  cancel_rejects_old_callback:async ck=>{const {r,p}=setup('documents');await wait(()=>T.get(r.threadId).some(t=>t.status==='in_progress'));const t=T.get(r.threadId).find(t=>t.status==='in_progress'),binding=T.bindingsFor(r.threadId,t.todo_id).at(-1),ticket=T.capture(r.threadId,t.todo_id),data=W.compute(r,t.plan_step_ids[0]),hash=P.hash(p.plan_id);
   action('pd-cancel',{id:p.plan_id});const before=saved(r,p),out=W.acceptResult(r.id,ticket,binding.binding_id,data);ck('Old admitted callback is refused after Cancel',out.error==='stale_work_callback');ck('No output/To-Do/run changes after cancellation',saved(r,p)===before);ck('Control is Canceled, approved bytes unchanged',P.buildLabel(p.plan_id)==='Canceled'&&P.hash(p.plan_id)===hash&&P.runs()[p.approved.plan_run_id].state==='cancelled'&&P.runs()[p.approved.plan_run_id].epoch===p.runEpoch);
   const denied=P.recoveryCommand({expected:P.recoverySnapshot(p.plan_id),action:'retry',idempotency_key:'cancel-no-restart'});ck('Cancel cannot be turned into Retry',!denied.ok);await new Promise(x=>setTimeout(x,1200));ck('Former timer cannot restart work',saved(r,p)===before);
  },
  recovery_rechecks_original_scope_and_permissions:ck=>{const {r,p}=setup('documents',false);P.build({plan_id:p.plan_id,expected:P.admissionSnapshot(p.plan_id),paused:true});const permissions=E.ctx().state.permissions;
   E.ctx().state.permissions='different-permission';let before=saved(r,p),out=P.recoveryCommand({expected:P.recoverySnapshot(p.plan_id),action:'resume',idempotency_key:'permissions'});ck('Even fresh UI snapshot cannot widen original run permissions',!out.ok&&out.error==='permissions_changed');ck('Permission refusal is atomic',saved(r,p)===before);E.ctx().state.permissions=permissions;
   const thread=E.ctx().thread,original=thread.worktreeId;thread.worktreeId='different-worktree';before=saved(r,p);out=P.recoveryCommand({expected:P.recoverySnapshot(p.plan_id),action:'resume',idempotency_key:'scope'});ck('Fresh snapshot cannot rebind original execution scope',!out.ok&&out.error==='scope_changed');ck('Scope refusal is atomic',saved(r,p)===before);thread.worktreeId=original;
  },
  wrong_computation_rolls_back_artifacts:ck=>{const {r,p}=setup('documents',false);P.build({plan_id:p.plan_id,expected:P.admissionSnapshot(p.plan_id),paused:true});P.boundResume(p.plan_id);const admitted=W.advance(r.id);if(!admitted.ok)throw Error(admitted.error);const t=T.get(r.threadId).find(t=>t.status==='in_progress'),binding=T.bindingsFor(r.threadId,t.todo_id).at(-1),before=saved(r,p);const out=W.acceptResult(r.id,T.capture(r.threadId,t.todo_id),binding.binding_id,[{id:'fabricated',subtotal_cents:'1'}]);ck('Successful callback with wrong outcome does not complete item',!out.ok);ck('Rejected output and evidence artifacts are fully rolled back',saved(r,p)===before);},
  revision_is_atomic_and_preserves_original:ck=>{const {r,p}=setup('documents',false),v1=P.documentRef(p.plan_id),bytes=JSON.stringify(A.resolve(v1).revision.record),before=saved(r,p),publish=A.publish;A.publish=q=>q.artifact_version===2?{ok:false,error:'injected_publication_failure'}:publish(q);const bad=P.revise(p.plan_id,'Add a delivery note');A.publish=publish;ck('Publication failure is a typed refusal',!bad.ok&&bad.error==='injected_publication_failure');ck('Failed revision moves no state or artifact',saved(r,p)===before);const good=P.revise(p.plan_id,'Add a delivery note');ck('Successful revise creates exactly V2',good.ok&&p.version===2);ck('Original shared V1 is unchanged and still opens',JSON.stringify(A.resolve(v1).revision.record)===bytes&&A.render(v1).includes('Read rows'));ck('Current and historical bodies are separate immutable revisions',p.revisions[1]!==p.revisions[2]&&Object.isFrozen(p.revisions[2]));ck('Historical reference prevents purge',A.purge(v1).error==='artifact_still_referenced');},
  live_revision_requires_safe_stop:ck=>{const {r,p}=setup('documents'),before=saved(r,p),out=P.revise(p.plan_id,'Hot swap');ck('Cannot revise underneath active work',out.error==='safe_stop_required');ck('Refusal leaves all owners unchanged',saved(r,p)===before);},
  frozen_fallback_mismatch_refused:ck=>{const {r,p}=setup('documents',false),before=saved(r,p),n=p.version+1;const original=p.revisions;p.revisions={...original,[n]:clone(original[p.version]).map(b=>b.renderer_kind==='interactive'?{...b,static_fallback_ref:{artifact_id:'different',artifact_version:2}}:b)};let refused=false;try{P.publishDocument(p.plan_id);}catch(e){refused=e.message==='frozen_fallback_mismatch';}p.revisions=original;ck('Mismatched Plan fallback cannot publish',refused);ck('Partially published later version is rolled back',saved(r,p)===before);},
  fallback_cycles_and_retention:ck=>{const f=(id)=>({artifact_id:id,artifact_version:1,project_id:'cycle-p',thread_id:'cycle-t'});A.publish({...f('cycle-a'),title:'A',renderer_kind:'mermaid',content:'A',static_fallback_ref:f('cycle-b')});A.publish({...f('cycle-b'),title:'B',renderer_kind:'mermaid',content:'B',static_fallback_ref:f('cycle-a')});const html=A.render(f('cycle-a'),{print:true});ck('Multi-hop cycle produces explicit unavailable block, not recursion',html.includes('recursive_fallback'));const out=A.retain(f('cycle-a'),{kind:'plan_revision',id:'retained'});ck('Cyclic retention traversal terminates and retains both exact versions',out.ok&&A.purge(f('cycle-a')).error==='artifact_still_referenced'&&A.purge(f('cycle-b')).error==='artifact_still_referenced');ck('Wrong-scope purge denied',A.purge({...f('cycle-a'),thread_id:'other'}).error==='denied');},
  graph_renders_actual_edges:ck=>{const {r,p}=setup('documents',false),ref=r.embeds.find(b=>b.renderer_kind==='graph'),html=A.render(ref),box=document.createElement('div');box.innerHTML=html;const titles=[...box.querySelectorAll('path title')].map(x=>x.textContent);ck('Only actual a→c and b→c edges rendered',JSON.stringify(titles)===JSON.stringify(['a → c','b → c']));ck('Display adjacency never creates a→b edge',!titles.includes('a → b'));},
  source_v2_does_not_change_approved_views:ck=>{const {r,p}=setup('documents',false),md=P.markdown(p.plan_id),hash=P.hash(p.plan_id),html=P.printDocument(p.plan_id),ref=r.embeds.find(b=>b.renderer_kind==='table');action('b17-source-v2',{work:r.id});ck('V2 publication does not modify Plan hash or Markdown',P.markdown(p.plan_id)===md&&P.hash(p.plan_id)===hash);ck('Printed document remains byte-exact after source update',P.printDocument(p.plan_id)===html);ck('Old embed resolves V1 rather than latest V2',A.render(ref).includes('A-001')&&!A.render(ref).includes('NEW-V2'));ck('Missing and unsupported embeds are named rather than dropped',html.includes('Unavailable research attachment')&&html.includes('exact artifact revision is missing'));},
  stale_export_invocation_refused:ck=>{const {r,p}=setup('documents',false),old={id:p.plan_id,version:String(p.version),hash:P.hash(p.plan_id),kind:'plan_document',format:'markdown'};P.revise(p.plan_id,'A newer document');const n=p.exports.length;action('pd-export-do',old);ck('Export action from stale version does not export a newer body',p.exports.length===n);},
  print_pipeline_is_inert:ck=>{const {r,p}=setup('documents',false),html=P.printDocument(p.plan_id);ck('Print contains shared static fallbacks, no iframe or script',html.includes('Interactive table · static fallback')&&html.includes('Video · static fallback')&&!html.includes('<iframe')&&!html.includes('<script'));ck('Every frozen embed has an exact identity in print',r.embeds.every(b=>html.includes(b.artifact_id+' @ V1')));ck('Plan rendering and exports add no live percentage or status source text',!P.markdown(p.plan_id).includes('[x]')&&!html.includes('data-step-state='));}
 });
})();
Object.assign(B17_CASES,{
 revision_rejection_preserves_composer:ck=>{
  const E=PM56_EXT,P=PM56_PLANS,A=PM56_ARTIFACTS;PM56_B17_WORK.start('documents');document.querySelector('[data-action="send"]').click();const p=P.get(PM56_B17_WORK.snapshot().planId);
  E._actions['pd-revise'](E.ctx(),{dataset:{id:p.plan_id}});const publish=A.publish,initial=JSON.stringify(p),messages=JSON.stringify(E.ctx().thread.messages);A.publish=q=>q.artifact_version===2?{ok:false,error:'publication_refused'}:publish(q);E.ctx().state.composer='Keep the exact original source.';document.querySelector('[data-input="composer"]').value=E.ctx().state.composer;document.querySelector('[data-action="send"]').click();A.publish=publish;
  ck('Failed revision retains instructions and original destination',E.ctx().state.composer==='Keep the exact original source.'&&PM56_RUNTIME.composer.destination.kind==='plan-revision');ck('No new user/receipt message or Plan revision on failure',JSON.stringify(p)===initial&&JSON.stringify(E.ctx().thread.messages)===messages);
 },
 stale_revision_target_refused:ck=>{
  const E=PM56_EXT,P=PM56_PLANS;PM56_B17_WORK.start('documents');document.querySelector('[data-action="send"]').click();const p=P.get(PM56_B17_WORK.snapshot().planId);E._actions['pd-revise'](E.ctx(),{dataset:{id:p.plan_id}});const target=JSON.parse(JSON.stringify(PM56_RUNTIME.composer.destination));P.revise(p.plan_id,'Intervening new version');PM56_RUNTIME.composer.destination=target;E.ctx().state.composer='Instructions based on V1';document.querySelector('[data-input="composer"]').value=E.ctx().state.composer;document.querySelector('[data-action="send"]').click();ck('Stale V1 target never mutates V2',p.version===2);ck('User text retained for explicit retargeting',E.ctx().state.composer==='Instructions based on V1');
 }
});
