#!/usr/bin/env python3
"""Fableicon generator — sole author of every generated artifact in this folder.

Reads source/pm-logo-source.svg and emits:
  icons/static/pm-<theme>.svg            (8 theme recolors, literal hex fills)
  icons/animated/pm-<theme>-loading.svg  (8; each theme paired with one of 8 motions)
  icons/template/pm-tray-Template.svg    (black marks on transparent, macOS template)
  icons/template/pm-tray-white.svg       (white twin for dark taskbars)
  slint/pm_loading_<motion>.slint        (7 native Slint components; bardraw is web-only)
  slint/layers/pm-layer-*.svg            (white layer SVGs for Image.colorize)
  manifest.json                          (deterministic metadata, no timestamps)
  index.html                             (splices the JSON data region between markers)

Modes:
  python3 generate.py            build everything
  python3 generate.py --check    rebuild in memory, diff against disk, exit 1 on drift

Concept work (same status as Concepts/PMConcept7.html); canonical spec stays in Plans/**.
"""

import hashlib
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE / "source" / "pm-logo-source.svg"
INDEX = HERE / "index.html"
MARK_BEGIN = "<!-- FABLEICON:DATA:BEGIN (generated by generate.py - do not hand-edit this block) -->"
MARK_END = "<!-- FABLEICON:DATA:END -->"

# ---------------------------------------------------------------- source parts

# The source artwork is matched by stable path-data prefixes; if the logo file
# is ever swapped for different artwork, these lookups fail loudly.
D_PREFIX_TO_PART = {
    "M9.34,28.55": "bracketL",
    "M26.38,32.54": "glyphM",
    "M12.93,36.25": "glyphPFill",
    "M16.15,22.88": "glyphPKeyline",
    "M16.87,14.44": "barTipL",
    "M37.76,7.6": "barTipR",
    "M36.83,21.63": "barMain",
    "M34.64,29.01": "bracketR",
}

STRING_R = dict(x="28.85", y="16.28", w=".97", h="12.18", rx=".48")
STRING_L = dict(x="14.42", y="15.6", w=".97", h="8.59", rx=".48")

# Geometry facts (derived from the source; used for pivots and overlays).
PIVOT_BAR = (21.9, 14.5)          # control-bar crossing
PIVOT_STR_L = (14.905, 15.6)      # string L top center
PIVOT_STR_R = (29.335, 16.28)     # string R top center
# Stroke twin of barMain, measured from the path data: cap-chord midpoints
# (7.15, 7.60) and (36.83, 20.19), perpendicular thickness ~3.1, length 32.3.
BAR_LINE = dict(x1=7.15, y1=7.6, x2=36.83, y2=20.19, length=32.3, width=3.1)
CANVAS = 43.2


def parse_source():
    text = SOURCE.read_text(encoding="utf-8")
    parts = {}
    for d in re.findall(r'd="([^"]+)"', text):
        for prefix, name in D_PREFIX_TO_PART.items():
            if d.startswith(prefix):
                parts[name] = d
    missing = set(D_PREFIX_TO_PART.values()) - set(parts)
    if missing:
        raise SystemExit(f"source svg does not contain expected paths: {sorted(missing)} "
                         "- was source/pm-logo-source.svg replaced with different artwork?")
    for rect in (STRING_L, STRING_R):
        if f'x="{rect["x"]}"' not in text:
            raise SystemExit(f"source svg missing string rect x={rect['x']}")
    return parts


# ------------------------------------------------------------------- palettes

PALETTES = [
    dict(slug="retro-dark", label="Retro Dark", family="retro", mode="dark",
         page_bg="#1A1A1A", surface="#252525", text="#E0E0E0", muted="#909090",
         tile="#1A1A1A", rx=0.0, mark="#00FF41", string="#FF1493",
         tile_desc="#1A1A1A + lime border", treatments=["retro_dark_border"]),
    dict(slug="retro-light", label="Retro Light", family="retro", mode="light",
         page_bg="#F5F0E8", surface="#FAF7F2", text="#1A1A1A", muted="#524F49",
         tile="#0047AB", rx=0.0, mark="#F5F0E8", string="#F5F0E8",
         tile_desc="#0047AB + hard offset shadow", treatments=["retro_light_shadow"]),
    dict(slug="basic-light", label="Basic Light", family="basic", mode="light",
         page_bg="#EAECEF", surface="#FFFFFF", text="#1A1A1A", muted="#5C6470",
         tile="#0056B3", rx=3.0, mark="#FFFFFF", string="#FFFFFF",
         tile_desc="#0056B3 flat", treatments=[]),
    dict(slug="basic-dark", label="Basic Dark", family="basic", mode="dark",
         page_bg="#121212", surface="#1E1E1E", text="#E8E8E8", muted="#6B7280",
         tile="#2D2D2D", rx=3.0, mark="#64B5F6", string="#64B5F6",
         tile_desc="#2D2D2D + hairline", treatments=["hairline:rgba(255,255,255,.14)"]),
    dict(slug="glass-dark", label="Glass Dark", family="glass", mode="dark",
         page_bg="#241B36", surface="#2E2244", text="#EDE7F8", muted="#9A8FB8",
         tile=("#2E2344", "#241B36"), rx=10.0, mark="#B79CFF", string="#E58BC8",
         tile_desc="violet gradient + glass edge", treatments=["glass_edge_gradient"]),
    dict(slug="glass-light", label="Glass Light", family="glass", mode="light",
         page_bg="#E4CDE4", surface="#F6F0FF", text="#453A5C", muted="#6C6480",
         tile=("#F6F0FF", "#E9DCF2"), rx=10.0, mark="#8B6ED9", string="#C167B4",
         tile_desc="frosted gradient + bright rim", treatments=["glass_edge_solid"]),
    dict(slug="friendly-dark", label="Friendly Dark", family="friendly", mode="dark",
         page_bg="#211E26", surface="#2A2731", text="#F0EDF4", muted="#8A8494",
         tile="#322E3A", rx=8.0, mark="#C3B1E4", string="#6FC6E8",
         tile_desc="#322E3A cozy plum + hairline", treatments=["hairline:rgba(240,237,244,.10)"]),
    dict(slug="friendly-light", label="Friendly Light", family="friendly", mode="light",
         page_bg="#FBF7F3", surface="#FFFFFF", text="#4A4550", muted="#9A93A0",
         tile="#3F9CC7", rx=8.0, mark="#FFFFFF", string="#FFD166",
         tile_desc="#3F9CC7 teal flat", treatments=[]),
]

# theme -> paired motion for the on-disk animated files (Mix Lab covers all combos)
PAIRING = {
    "friendly-dark": "spin", "glass-dark": "shimmer", "retro-dark": "bardraw",
    "retro-light": "typingwave", "basic-light": "drawin", "glass-light": "stringpulse",
    "basic-dark": "seesaw", "friendly-light": "bob",
}

# family -> (duration multiplier, discrete-move easing)
FAMILY_MOTION = {
    "retro": (0.85, "cubic-bezier(.2,0,0,1)"),
    "basic": (1.0, "cubic-bezier(.4,0,.2,1)"),
    "glass": (1.25, "cubic-bezier(.22,1,.36,1)"),
    "friendly": (1.0, "cubic-bezier(.34,1.56,.64,1)"),
}
EASE_INOUT = "cubic-bezier(.45,0,.55,1)"

# retro-light art inset: tile shrinks to 40.7 and art scales so the 2.5-unit
# hard offset shadow stays inside the shared 43.2 canvas
RL_SCALE = 0.942
RL_TILE = 40.7
RL_SHADOW = 2.5


# --------------------------------------------------------------- svg building

def fnum(v):
    s = f"{v:.2f}".rstrip("0").rstrip(".")
    return s if s else "0"


def tile_markup(pal, uid):
    """Tile + treatments. Returns (defs, pre_art, tile_ref_for_keyline)."""
    defs, pre = [], []
    rx = fnum(pal["rx"])
    if isinstance(pal["tile"], tuple):
        top, bottom = pal["tile"]
        gid = f"gradTile-{uid}"
        defs.append(
            f'<linearGradient id="{gid}" x1="0" y1="0" x2="0" y2="{CANVAS}" gradientUnits="userSpaceOnUse">'
            f'<stop offset="0" stop-color="{top}"/><stop offset="1" stop-color="{bottom}"/></linearGradient>')
        tile_fill = f"url(#{gid})"
    else:
        tile_fill = pal["tile"]

    if "retro_light_shadow" in pal["treatments"]:
        pre.append(f'<rect x="{RL_SHADOW}" y="{RL_SHADOW}" width="{RL_TILE}" height="{RL_TILE}" rx="{rx}" fill="#1A1A1A"/>')
        pre.append(f'<rect id="tile-{uid}" width="{RL_TILE}" height="{RL_TILE}" rx="{rx}" fill="{tile_fill}"/>')
    else:
        pre.append(f'<rect id="tile-{uid}" width="{CANVAS}" height="{CANVAS}" rx="{rx}" fill="{tile_fill}"/>')

    for t in pal["treatments"]:
        if t == "retro_dark_border":
            pre.append(f'<rect x=".6" y=".6" width="42" height="42" fill="none" stroke="{pal["mark"]}" stroke-width="1.2"/>')
        elif t.startswith("hairline:"):
            color = t.split(":", 1)[1]
            hrx = fnum(max(pal["rx"] - 0.4, 0))
            pre.append(f'<rect x=".5" y=".5" width="42.2" height="42.2" rx="{hrx}" fill="none" stroke="{color}" stroke-width="1"/>')
        elif t == "glass_edge_gradient":
            gid = f"gradEdge-{uid}"
            defs.append(
                f'<linearGradient id="{gid}" x1="0" y1="0" x2="0" y2="{CANVAS}" gradientUnits="userSpaceOnUse">'
                f'<stop offset="0" stop-color="#FFFFFF" stop-opacity=".55"/>'
                f'<stop offset="1" stop-color="#FFFFFF" stop-opacity=".10"/></linearGradient>')
            pre.append(f'<rect x=".5" y=".5" width="42.2" height="42.2" rx="9.6" fill="none" stroke="url(#{gid})" stroke-width="1"/>')
        elif t == "glass_edge_solid":
            pre.append('<rect x=".5" y=".5" width="42.2" height="42.2" rx="9.6" fill="none" stroke="rgba(255,255,255,.95)" stroke-width="1"/>')
    return defs, pre, tile_fill


def build_static(parts, pal):
    """Instrumented master for one palette. Every animation hook is present but
    inert (identity sandwiches, display="none" overlays), so any motion's CSS can
    be appended onto this exact markup."""
    uid = pal["slug"]
    rx = fnum(pal["rx"])
    mark, string = pal["mark"], pal["string"]
    defs, pre, tile_fill = tile_markup(pal, uid)

    defs.append(f'<clipPath id="tileClip-{uid}"><rect width="{CANVAS}" height="{CANVAS}" rx="{rx}"/></clipPath>')
    shim_alpha = ".35" if pal["mode"] == "dark" else ".55"
    defs.append(
        f'<linearGradient id="shimGrad-{uid}" x1="0" y1="0" x2="1" y2="0">'
        f'<stop offset="0" stop-color="#FFFFFF" stop-opacity="0"/>'
        f'<stop offset=".5" stop-color="#FFFFFF" stop-opacity="{shim_alpha}"/>'
        f'<stop offset="1" stop-color="#FFFFFF" stop-opacity="0"/></linearGradient>')

    bx, by = PIVOT_BAR
    lx, ly = PIVOT_STR_L
    rx_, ry_ = PIVOT_STR_R
    bl = BAR_LINE

    art = []
    art.append(f'<g id="puppets-{uid}" class="a-puppets">')
    art.append(f'  <path id="bracketL-{uid}" class="a-brkL" fill="{mark}" d="{parts["bracketL"]}"/>')
    art.append(f'  <path id="bracketR-{uid}" class="a-brkR" fill="{mark}" d="{parts["bracketR"]}"/>')
    art.append(f'  <g id="glyphM-{uid}" class="a-m"><path fill="{mark}" d="{parts["glyphM"]}"/></g>')
    art.append(f'  <g id="glyphP-{uid}" class="a-p">')
    art.append(f'    <path id="glyphPFill-{uid}" fill="{mark}" d="{parts["glyphPFill"]}"/>')
    art.append(f'    <path id="glyphPKeyline-{uid}" fill="{tile_fill}" d="{parts["glyphPKeyline"]}"/>')
    art.append('  </g>')
    art.append('</g>')
    art.append(f'<g class="a-barclip">')
    art.append(f'  <g transform="translate({fnum(bx)} {fnum(by)})"><g class="a-bar"><g transform="translate(-{fnum(bx)} -{fnum(by)})">')
    art.append(f'    <g id="bar-{uid}">')
    art.append(f'      <path id="barTipL-{uid}" class="a-barTipL" fill="{mark}" d="{parts["barTipL"]}"/>')
    art.append(f'      <path id="barTipR-{uid}" class="a-barTipR" fill="{mark}" d="{parts["barTipR"]}"/>')
    art.append(f'      <path id="barMain-{uid}" class="a-barMain" fill="{mark}" d="{parts["barMain"]}"/>')
    art.append(f'      <line id="barLine-{uid}" x1="{bl["x1"]}" y1="{bl["y1"]}" x2="{bl["x2"]}" y2="{bl["y2"]}" '
               f'stroke="{mark}" stroke-width="{bl["width"]}" stroke-linecap="round" display="none"/>')
    art.append('    </g>')
    art.append('  </g></g></g>')
    art.append('</g>')
    art.append(f'<g id="strings-{uid}" class="a-strings">')
    art.append(f'  <g transform="translate({fnum(lx)} {fnum(ly)})"><g class="a-strL"><g transform="translate(-{fnum(lx)} -{fnum(ly)})">')
    art.append(f'    <rect id="stringL-{uid}" x="{STRING_L["x"]}" y="{STRING_L["y"]}" width="{STRING_L["w"]}" height="{STRING_L["h"]}" rx="{STRING_L["rx"]}" fill="{string}"/>')
    art.append('  </g></g></g>')
    art.append(f'  <g transform="translate({fnum(rx_)} {fnum(ry_)})"><g class="a-strR"><g transform="translate(-{fnum(rx_)} -{fnum(ry_)})">')
    art.append(f'    <rect id="stringR-{uid}" x="{STRING_R["x"]}" y="{STRING_R["y"]}" width="{STRING_R["w"]}" height="{STRING_R["h"]}" rx="{STRING_R["rx"]}" fill="{string}"/>')
    art.append('  </g></g></g>')
    art.append('</g>')
    art.append(f'<g id="pulses-{uid}" display="none">')
    art.append(f'  <line id="pulseL-{uid}" x1="{fnum(lx)}" y1="15.6" x2="{fnum(lx)}" y2="24.19" stroke="{string}" stroke-width=".97" stroke-linecap="round"/>')
    art.append(f'  <line id="pulseR-{uid}" x1="{fnum(rx_)}" y1="16.28" x2="{fnum(rx_)}" y2="28.46" stroke="{string}" stroke-width=".97" stroke-linecap="round"/>')
    art.append('</g>')
    art.append(f'<g id="shimmer-{uid}" display="none" clip-path="url(#tileClip-{uid})">')
    art.append('  <g transform="rotate(20 21.6 21.6)">')
    art.append(f'    <rect class="band" x="-9" y="-26" width="18" height="95" fill="url(#shimGrad-{uid})"/>')
    art.append('  </g>')
    art.append('</g>')

    scale = f' transform="scale({RL_SCALE})"' if "retro_light_shadow" in pal["treatments"] else ""
    lines = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {CANVAS} {CANVAS}" id="pmx-{uid}">']
    lines.append('<defs>' + "".join(defs) + '</defs>')
    lines.extend(pre)
    lines.append(f'<g id="artwrap-{uid}"{scale}>')
    lines.extend(art)
    lines.append('</g>')
    lines.append('</svg>')
    return "\n".join(lines) + "\n"


def build_template(parts, color, name):
    """Monochrome tray variant: no tile; the P keyline becomes transparency via mask."""
    thick = dict(w=1.6)
    lx = 14.42 + 0.97 / 2 - thick["w"] / 2
    rxp = 28.85 + 0.97 / 2 - thick["w"] / 2
    lines = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {CANVAS} {CANVAS}" id="pmx-{name}">']
    lines.append('<defs>')
    lines.append(f'<mask id="pmask-{name}"><rect width="{CANVAS}" height="{CANVAS}" fill="#fff"/>'
                 f'<path d="{parts["glyphPKeyline"]}" fill="#000"/></mask>')
    lines.append('</defs>')
    lines.append(f'<g fill="{color}" mask="url(#pmask-{name})">')
    lines.append(f'  <path d="{parts["bracketL"]}"/>')
    lines.append(f'  <path d="{parts["bracketR"]}"/>')
    lines.append(f'  <path d="{parts["glyphM"]}"/>')
    lines.append(f'  <path d="{parts["glyphPFill"]}"/>')
    lines.append('</g>')
    lines.append(f'<g fill="{color}">')
    lines.append(f'  <path d="{parts["barTipL"]}"/>')
    lines.append(f'  <path d="{parts["barTipR"]}"/>')
    lines.append(f'  <path d="{parts["barMain"]}"/>')
    lines.append(f'  <rect x="{fnum(lx)}" y="15.6" width="1.6" height="8.59" rx=".8"/>')
    lines.append(f'  <rect x="{fnum(rxp)}" y="16.28" width="1.6" height="12.18" rx=".8"/>')
    lines.append('</g>')
    lines.append('</svg>')
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ animations

ANIMS = [
    dict(slug="spin", name="Crossbar Spin", rank=1,
         desc="The control bar rotates about its crossing like a propeller; the rest of the mark dims.",
         slint="native"),
    dict(slug="shimmer", name="Shimmer Sweep", rank=2,
         desc="A diagonal highlight band sweeps across the tile, then rests. The artwork never moves.",
         slint="rebuild"),
    dict(slug="bardraw", name="Bar Draw", rank=3,
         desc="The long bar continuously redraws itself tip-to-tip as a traveling stroke; the tips blink as it passes.",
         slint="web-only"),
    dict(slug="typingwave", name="Typing Wave", rank=4,
         desc="Bracket, P, M, bracket dip in sequence with the typing-dots rhythm.",
         slint="native"),
    dict(slug="drawin", name="String Draw-In", rank=5,
         desc="The puppet assembles: strings grow down, letters pop in, brackets fade up; hold; fade; repeat.",
         slint="native"),
    dict(slug="stringpulse", name="String Pulse", rank=6,
         desc="Accent pulses travel down each string and the receiving letter brightens.",
         slint="rebuild"),
    dict(slug="seesaw", name="Control-Bar Seesaw", rank=7,
         desc="The bar rocks about its crossing while the hanging letters rise and fall in opposition.",
         slint="native"),
    dict(slug="bob", name="Marionette Bob", rank=8,
         desc="P and M bob gently out of phase, strings stretching to stay attached.",
         slint="native"),
]


def anim_css(anim_slug, pal, root_uid):
    """CSS for one motion x one palette. Selectors are scoped to #pmx-{root_uid};
    markup id references use the palette uid (the static markup's ids)."""
    u = pal["slug"]
    r = root_uid
    s = f"#pmx-{r}"
    mult, ease = FAMILY_MOTION[pal["family"]]

    def d(base):
        return str(int(round(base * mult)))

    if anim_slug == "spin":
        body = f"""
  {s} .a-puppets, {s} .a-strings {{ opacity: .3; }}
  {s} .a-barclip {{ clip-path: url(#tileClip-{u}); }}
  {s} .a-bar {{ animation: pmSpin-{r} 900ms linear infinite; }}
  @keyframes pmSpin-{r} {{ to {{ transform: rotate(360deg); }} }}"""
    elif anim_slug == "shimmer":
        body = f"""
  {s} #shimmer-{u} {{ display: inline; }}
  {s} .band {{ animation: pmShim-{r} {d(1700)}ms {ease} infinite; }}
  @keyframes pmShim-{r} {{ 0% {{ transform: translateX(-34px); }} 55%, 100% {{ transform: translateX(64px); }} }}"""
    elif anim_slug == "bardraw":
        L = BAR_LINE["length"]
        body = f"""
  {s} #barLine-{u} {{ display: inline; stroke-dasharray: {L} {L}; animation: pmDraw-{r} 1800ms linear infinite; }}
  {s} .a-barMain {{ opacity: 0; }}
  {s} .a-puppets, {s} .a-strings {{ opacity: .4; }}
  {s} .a-barTipL {{ animation: pmTipL-{r} 1800ms linear infinite; }}
  {s} .a-barTipR {{ animation: pmTipR-{r} 1800ms linear infinite; }}
  @keyframes pmDraw-{r} {{ 0% {{ stroke-dashoffset: {L}; }} 50% {{ stroke-dashoffset: 0; }} 100% {{ stroke-dashoffset: -{L}; }} }}
  @keyframes pmTipL-{r} {{ 0%, 18% {{ opacity: .4; }} 24%, 34% {{ opacity: 1; }} 42%, 100% {{ opacity: .4; }} }}
  @keyframes pmTipR-{r} {{ 0%, 30% {{ opacity: .4; }} 36%, 46% {{ opacity: 1; }} 54%, 100% {{ opacity: .4; }} }}"""
    elif anim_slug == "typingwave":
        wave_ease = "steps(2, end)" if pal["family"] == "retro" else ease
        body = f"""
  {s} .a-brkL {{ animation: pmDip-{r} {d(900)}ms {wave_ease} infinite; }}
  {s} .a-p   {{ animation: pmDip-{r} {d(900)}ms {wave_ease} infinite; animation-delay: {d(150)}ms; }}
  {s} .a-m   {{ animation: pmDip-{r} {d(900)}ms {wave_ease} infinite; animation-delay: {d(300)}ms; }}
  {s} .a-brkR {{ animation: pmDip-{r} {d(900)}ms {wave_ease} infinite; animation-delay: {d(450)}ms; }}
  @keyframes pmDip-{r} {{ 0%, 30%, 100% {{ transform: translateY(0); }} 15% {{ transform: translateY(1.5px); }} }}"""
    elif anim_slug == "drawin":
        body = f"""
  {s} .a-strL {{ animation: pmGrowL-{r} {d(2600)}ms {ease} infinite; }}
  {s} .a-strR {{ animation: pmGrowR-{r} {d(2600)}ms {ease} infinite; }}
  {s} .a-p {{ animation: pmPopP-{r} {d(2600)}ms {ease} infinite; transform-box: fill-box; transform-origin: 50% 50%; }}
  {s} .a-m {{ animation: pmPopM-{r} {d(2600)}ms {ease} infinite; transform-box: fill-box; transform-origin: 50% 50%; }}
  {s} .a-brkL, {s} .a-brkR {{ animation: pmFadeBrk-{r} {d(2600)}ms {ease} infinite; }}
  @keyframes pmGrowL-{r} {{ 0% {{ transform: scaleY(0); opacity: 1; }} 22% {{ transform: scaleY(1); }} 80% {{ transform: scaleY(1); opacity: 1; }} 96%, 100% {{ transform: scaleY(1); opacity: 0; }} }}
  @keyframes pmGrowR-{r} {{ 0%, 4% {{ transform: scaleY(0); opacity: 1; }} 26% {{ transform: scaleY(1); }} 80% {{ transform: scaleY(1); opacity: 1; }} 96%, 100% {{ transform: scaleY(1); opacity: 0; }} }}
  @keyframes pmPopP-{r} {{ 0%, 16% {{ transform: scale(.85); opacity: 0; }} 38% {{ transform: scale(1); opacity: 1; }} 80% {{ transform: scale(1); opacity: 1; }} 94%, 100% {{ transform: scale(1); opacity: 0; }} }}
  @keyframes pmPopM-{r} {{ 0%, 26% {{ transform: scale(.85); opacity: 0; }} 48% {{ transform: scale(1); opacity: 1; }} 82% {{ transform: scale(1); opacity: 1; }} 96%, 100% {{ transform: scale(1); opacity: 0; }} }}
  @keyframes pmFadeBrk-{r} {{ 0%, 36% {{ opacity: 0; }} 54% {{ opacity: 1; }} 84% {{ opacity: 1; }} 98%, 100% {{ opacity: 0; }} }}"""
    elif anim_slug == "stringpulse":
        body = f"""
  {s} #pulses-{u} {{ display: inline; }}
  {s} .a-strings {{ opacity: .6; }}
  {s} #pulseL-{u} {{ stroke-dasharray: 2.2 6.39; animation: pmPulL-{r} 1600ms linear infinite; }}
  {s} #pulseR-{u} {{ stroke-dasharray: 2.6 9.58; animation: pmPulR-{r} 1600ms linear infinite; animation-delay: -800ms; }}
  {s} .a-p {{ animation: pmGlow-{r} 1600ms linear infinite; }}
  {s} .a-m {{ animation: pmGlow-{r} 1600ms linear infinite; animation-delay: -800ms; }}
  @keyframes pmPulL-{r} {{ from {{ stroke-dashoffset: 8.59; }} to {{ stroke-dashoffset: 0; }} }}
  @keyframes pmPulR-{r} {{ from {{ stroke-dashoffset: 12.18; }} to {{ stroke-dashoffset: 0; }} }}
  @keyframes pmGlow-{r} {{ 0%, 55% {{ opacity: .75; }} 78% {{ opacity: 1; }} 100% {{ opacity: .75; }} }}"""
    elif anim_slug == "seesaw":
        rock_ease = "steps(3, end)" if pal["family"] == "retro" else (ease if pal["family"] == "friendly" else EASE_INOUT)
        body = f"""
  {s} .a-bar {{ animation: pmRock-{r} {d(1400)}ms {rock_ease} infinite; }}
  {s} .a-strL, {s} .a-p {{ animation: pmSideL-{r} {d(1400)}ms {rock_ease} infinite; }}
  {s} .a-strR, {s} .a-m {{ animation: pmSideR-{r} {d(1400)}ms {rock_ease} infinite; }}
  @keyframes pmRock-{r} {{ 0%, 100% {{ transform: rotate(-5deg); }} 50% {{ transform: rotate(5deg); }} }}
  @keyframes pmSideL-{r} {{ 0%, 100% {{ transform: translateY(.61px); }} 50% {{ transform: translateY(-.61px); }} }}
  @keyframes pmSideR-{r} {{ 0%, 100% {{ transform: translateY(-.65px); }} 50% {{ transform: translateY(.65px); }} }}"""
    elif anim_slug == "bob":
        body = f"""
  {s} .a-p {{ animation: pmBobP-{r} {d(1200)}ms {EASE_INOUT} infinite; }}
  {s} .a-strL {{ animation: pmStrL-{r} {d(1200)}ms {EASE_INOUT} infinite; }}
  {s} .a-m {{ animation: pmBobP-{r} {d(1200)}ms {EASE_INOUT} infinite; animation-delay: -{d(600)}ms; }}
  {s} .a-strR {{ animation: pmStrR-{r} {d(1200)}ms {EASE_INOUT} infinite; animation-delay: -{d(600)}ms; }}
  @keyframes pmBobP-{r} {{ 0%, 100% {{ transform: translateY(-1.2px); }} 50% {{ transform: translateY(1.2px); }} }}
  @keyframes pmStrL-{r} {{ 0%, 100% {{ transform: scaleY(.86); }} 50% {{ transform: scaleY(1.14); }} }}
  @keyframes pmStrR-{r} {{ 0%, 100% {{ transform: scaleY(.9); }} 50% {{ transform: scaleY(1.1); }} }}"""
    else:
        raise SystemExit(f"unknown animation {anim_slug}")

    return (f"/* {anim_slug} x {u} */\n"
            f"@media (prefers-reduced-motion: no-preference) {{{body}\n}}\n"
            + reduced_kill_block(anim_slug, s, u))


def reduced_kill_block(anim_slug, s, u):
    """App-level reduced-motion kill-path (PM7 sets data-motion="reduced" / data-reduced-motion="1"
    on <html> independently of the OS preference, which leaves the media block active). Killing the
    animations alone is not enough for motions whose setup lives in static declarations (dims,
    display'd overlays) — those need explicit reverts so the frozen state is the pristine logo.
    Standalone files are unaffected (their :root is the svg itself, so these selectors never match;
    the media query is their only path)."""
    roots = (':root[data-motion="reduced"]', ':root[data-reduced-motion="1"]')
    rules = [("*", "animation: none !important;")]
    rules += {
        "spin": [(".a-puppets, .a-strings", "opacity: 1 !important;")],
        "shimmer": [(f"#shimmer-{u}", "display: none !important;")],
        "bardraw": [(f"#barLine-{u}", "display: none !important;"),
                    (".a-barMain, .a-puppets, .a-strings", "opacity: 1 !important;")],
        "stringpulse": [(f"#pulses-{u}", "display: none !important;"),
                        (".a-strings", "opacity: 1 !important;")],
    }.get(anim_slug, [])
    out = []
    for targets, decl in rules:
        sels = [f"{r} {s} {t.strip()}" for r in roots for t in targets.split(",")]
        out.append(", ".join(sels) + f" {{ {decl} }}")
    return "\n".join(out) + "\n"


def build_animated(static_svg, pal, anim_slug):
    """Animated file = static markup with a new root id + embedded stylesheet."""
    root = f"{pal['slug']}-ld"
    svg = static_svg.replace(f'id="pmx-{pal["slug"]}"', f'id="pmx-{root}"', 1)
    css = anim_css(anim_slug, pal, root)
    if "prefers-reduced-motion" not in css:
        raise SystemExit(f"reduced-motion gate: {anim_slug} css lacks prefers-reduced-motion")
    style = f"<style>\n{css}</style>\n"
    if svg.count("</svg>") != 1:
        raise SystemExit("unexpected svg structure")
    return svg.replace("</svg>", style + "</svg>")


# ----------------------------------------------------------------- slint files

def layer_svg(paths):
    body = "".join(f'<path fill="#FFFFFF" d="{d}"/>' for d in paths)
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {CANVAS} {CANVAS}">'
            f'{body}</svg>\n')


def build_slint_layers(parts):
    return {
        "pm-layer-bar.svg": layer_svg([parts["barTipL"], parts["barTipR"], parts["barMain"]]),
        "pm-layer-glyphP.svg": layer_svg([parts["glyphPFill"]]),
        "pm-layer-pkeyline.svg": layer_svg([parts["glyphPKeyline"]]),
        "pm-layer-glyphM.svg": layer_svg([parts["glyphM"]]),
        "pm-layer-bracketL.svg": layer_svg([parts["bracketL"]]),
        "pm-layer-bracketR.svg": layer_svg([parts["bracketR"]]),
    }


SLINT_HEADER = """// {name} - PuppetMaster loading indicator ("{title}")
// Generated by Concepts/Fableicon/generate.py - do not hand-edit.
// Slint 1.17: SVGs render statically via resvg (CSS-in-SVG animation is ignored),
// so this component re-creates the motion natively with layered images.
// Defaults are the friendly-dark palette; override the color properties per theme.
// The browser reference implementation is icons/animated/ + the dashboard Mix Lab.
"""

SLINT_COMMON_PROPS = """    in property <length> size: 44px;
    in property <color> tile-color: #322E3A;
    in property <color> mark-color: #C3B1E4;
    in property <color> string-color: #6FC6E8;
    in property <length> tile-radius: self.size * 8 / 43.2;
    width: size; height: size;
"""


def slint_static_layers(indent="        ", dim=None, skip=()):
    """Standard stack of the non-animated layers (brackets, M, P, keyline, strings)."""
    op = f" opacity: {dim};" if dim else ""
    out = []
    for img in ("bracketL", "bracketR", "glyphM", "glyphP"):
        if img in skip:
            continue
        out.append(f'{indent}Image {{ source: @image-url("layers/pm-layer-{img}.svg"); '
                   f'colorize: root.mark-color; width: 100%; height: 100%;{op} }}')
    if "pkeyline" not in skip:
        out.append(f'{indent}Image {{ source: @image-url("layers/pm-layer-pkeyline.svg"); '
                   f'colorize: root.tile-color; width: 100%; height: 100%;{op} }}')
    if "strings" not in skip:
        out.append(f'{indent}// puppet strings as native rectangles (height-animatable)')
        out.append(f'{indent}Rectangle {{ x: root.size * 14.42/43.2; y: root.size * 15.6/43.2; '
                   f'width: root.size * 0.97/43.2; height: root.size * 8.59/43.2; '
                   f'border-radius: self.width/2; background: root.string-color;{op} }}')
        out.append(f'{indent}Rectangle {{ x: root.size * 28.85/43.2; y: root.size * 16.28/43.2; '
                   f'width: root.size * 0.97/43.2; height: root.size * 12.18/43.2; '
                   f'border-radius: self.width/2; background: root.string-color;{op} }}')
    return "\n".join(out)


def build_slint_components():
    comps = {}

    comps["pm_loading_spin.slint"] = SLINT_HEADER.format(name="pm_loading_spin.slint", title="Crossbar Spin") + f"""
export component PmLoadingSpin {{
{SLINT_COMMON_PROPS}    in property <duration> period: 900ms;

    Rectangle {{
        width: 100%; height: 100%;
        background: root.tile-color;
        border-radius: root.tile-radius;
        clip: true;

{slint_static_layers(dim="0.3")}

        // spinning control bar; pivot (21.9, 14.5) on the 43.2-unit canvas
        Image {{
            source: @image-url("layers/pm-layer-bar.svg");
            colorize: root.mark-color;
            width: 100%; height: 100%;
            rotation-angle: 360deg * (animation-tick() / root.period);
            rotation-origin-x: self.width * 21.9/43.2;
            rotation-origin-y: self.height * 14.5/43.2;
        }}
    }}
}}
"""

    comps["pm_loading_shimmer.slint"] = SLINT_HEADER.format(name="pm_loading_shimmer.slint", title="Shimmer Sweep") + f"""
// Note: the browser version sweeps a 20-degree diagonal band; this native
// re-creation sweeps a vertical band (a redesign, not a 1:1 port).
export component PmLoadingShimmer {{
{SLINT_COMMON_PROPS}    in property <duration> period: 1700ms;
    in property <float> band-alpha: 0.35; // 0.55 on light themes
    property <float> t: Math.mod(animation-tick() / 1ms, root.period / 1ms) / (root.period / 1ms);
    // sweep during the first 55% of the cycle, rest for the remainder
    property <float> sweep: Math.min(root.t / 0.55, 1.0);

    Rectangle {{
        width: 100%; height: 100%;
        background: root.tile-color;
        border-radius: root.tile-radius;
        clip: true;

{slint_static_layers()}

        Rectangle {{
            width: root.size * 0.42;
            height: 100%;
            x: -self.width + (root.size + 2 * self.width) * root.sweep;
            background: @linear-gradient(90deg,
                rgba(255,255,255,0) 0%,
                rgba(255,255,255,root.band-alpha) 50%,
                rgba(255,255,255,0) 100%);
        }}
    }}
}}
"""

    comps["pm_loading_typingwave.slint"] = SLINT_HEADER.format(name="pm_loading_typingwave.slint", title="Typing Wave") + f"""
export component PmLoadingTypingwave {{
{SLINT_COMMON_PROPS}    in property <duration> period: 900ms;
    property <float> t: Math.mod(animation-tick() / 1ms, root.period / 1ms) / (root.period / 1ms);
    // triangular dip occupying the first 30% of the cycle
    pure function dip(phase: float) -> float {{
        Math.mod(phase, 1.0) < 0.15 ? Math.mod(phase, 1.0) / 0.15
        : Math.mod(phase, 1.0) < 0.30 ? 1.0 - (Math.mod(phase, 1.0) - 0.15) / 0.15
        : 0.0
    }}
    property <length> amp: root.size * 1.5/43.2;

    Rectangle {{
        width: 100%; height: 100%;
        background: root.tile-color;
        border-radius: root.tile-radius;
        clip: true;

        Image {{ source: @image-url("layers/pm-layer-bar.svg"); colorize: root.mark-color; width: 100%; height: 100%; }}
{slint_static_layers(skip=("bracketL", "bracketR", "glyphM", "glyphP", "pkeyline"))}

        Image {{ source: @image-url("layers/pm-layer-bracketL.svg"); colorize: root.mark-color; width: 100%; height: 100%;
                y: root.dip(root.t) * root.amp; }}
        Image {{ source: @image-url("layers/pm-layer-glyphM.svg"); colorize: root.mark-color; width: 100%; height: 100%;
                y: root.dip(root.t - 0.333) * root.amp; }}
        Image {{ source: @image-url("layers/pm-layer-glyphP.svg"); colorize: root.mark-color; width: 100%; height: 100%;
                y: root.dip(root.t - 0.166) * root.amp; }}
        Image {{ source: @image-url("layers/pm-layer-pkeyline.svg"); colorize: root.tile-color; width: 100%; height: 100%;
                y: root.dip(root.t - 0.166) * root.amp; }}
        Image {{ source: @image-url("layers/pm-layer-bracketR.svg"); colorize: root.mark-color; width: 100%; height: 100%;
                y: root.dip(root.t - 0.5) * root.amp; }}
    }}
}}
"""

    comps["pm_loading_drawin.slint"] = SLINT_HEADER.format(name="pm_loading_drawin.slint", title="String Draw-In") + f"""
export component PmLoadingDrawin {{
{SLINT_COMMON_PROPS}    in property <duration> period: 2600ms;
    property <float> t: Math.mod(animation-tick() / 1ms, root.period / 1ms) / (root.period / 1ms);
    pure function ramp(t: float, a: float, b: float) -> float {{
        t <= a ? 0.0 : t >= b ? 1.0 : (t - a) / (b - a)
    }}
    // global fade-out during the last 6% returns everything to the start state
    property <float> fade: 1.0 - root.ramp(root.t, 0.94, 1.0);

    Rectangle {{
        width: 100%; height: 100%;
        background: root.tile-color;
        border-radius: root.tile-radius;
        clip: true;

        Image {{ source: @image-url("layers/pm-layer-bar.svg"); colorize: root.mark-color; width: 100%; height: 100%; }}

        Rectangle {{ x: root.size * 14.42/43.2; y: root.size * 15.6/43.2;
            width: root.size * 0.97/43.2;
            height: root.size * 8.59/43.2 * root.ramp(root.t, 0.0, 0.22);
            border-radius: self.width/2; background: root.string-color; opacity: root.fade; }}
        Rectangle {{ x: root.size * 28.85/43.2; y: root.size * 16.28/43.2;
            width: root.size * 0.97/43.2;
            height: root.size * 12.18/43.2 * root.ramp(root.t, 0.04, 0.26);
            border-radius: self.width/2; background: root.string-color; opacity: root.fade; }}

        Image {{ source: @image-url("layers/pm-layer-glyphM.svg"); colorize: root.mark-color; width: 100%; height: 100%;
                opacity: root.ramp(root.t, 0.26, 0.48) * root.fade; }}
        Image {{ source: @image-url("layers/pm-layer-glyphP.svg"); colorize: root.mark-color; width: 100%; height: 100%;
                opacity: root.ramp(root.t, 0.16, 0.38) * root.fade; }}
        Image {{ source: @image-url("layers/pm-layer-pkeyline.svg"); colorize: root.tile-color; width: 100%; height: 100%;
                opacity: root.ramp(root.t, 0.16, 0.38) * root.fade; }}
        Image {{ source: @image-url("layers/pm-layer-bracketL.svg"); colorize: root.mark-color; width: 100%; height: 100%;
                opacity: root.ramp(root.t, 0.36, 0.54) * root.fade; }}
        Image {{ source: @image-url("layers/pm-layer-bracketR.svg"); colorize: root.mark-color; width: 100%; height: 100%;
                opacity: root.ramp(root.t, 0.36, 0.54) * root.fade; }}
    }}
}}
"""

    comps["pm_loading_stringpulse.slint"] = SLINT_HEADER.format(name="pm_loading_stringpulse.slint", title="String Pulse") + f"""
// Note: the browser version flows dash pulses along the strings; this native
// re-creation slides a small accent dot down each string instead (a redesign).
export component PmLoadingStringpulse {{
{SLINT_COMMON_PROPS}    in property <duration> period: 1600ms;
    property <float> t: Math.mod(animation-tick() / 1ms, root.period / 1ms) / (root.period / 1ms);
    property <float> t2: Math.mod(root.t + 0.5, 1.0);

    Rectangle {{
        width: 100%; height: 100%;
        background: root.tile-color;
        border-radius: root.tile-radius;
        clip: true;

        Image {{ source: @image-url("layers/pm-layer-bar.svg"); colorize: root.mark-color; width: 100%; height: 100%; }}
{slint_static_layers(dim="0.75", skip=("strings",))}
        Rectangle {{ x: root.size * 14.42/43.2; y: root.size * 15.6/43.2; width: root.size * 0.97/43.2;
            height: root.size * 8.59/43.2; border-radius: self.width/2; background: root.string-color; opacity: 0.6; }}
        Rectangle {{ x: root.size * 28.85/43.2; y: root.size * 16.28/43.2; width: root.size * 0.97/43.2;
            height: root.size * 12.18/43.2; border-radius: self.width/2; background: root.string-color; opacity: 0.6; }}

        // sliding pulse dots
        Rectangle {{ x: root.size * 14.16/43.2; width: root.size * 1.5/43.2; height: self.width;
            y: root.size * (15.6 + 7.0 * root.t) / 43.2;
            border-radius: self.width/2; background: root.string-color; }}
        Rectangle {{ x: root.size * 28.59/43.2; width: root.size * 1.5/43.2; height: self.width;
            y: root.size * (16.28 + 10.6 * root.t2) / 43.2;
            border-radius: self.width/2; background: root.string-color; }}
    }}
}}
"""

    comps["pm_loading_seesaw.slint"] = SLINT_HEADER.format(name="pm_loading_seesaw.slint", title="Control-Bar Seesaw") + f"""
export component PmLoadingSeesaw {{
{SLINT_COMMON_PROPS}    in property <duration> period: 1400ms;
    property <angle> phase: 360deg * (animation-tick() / root.period);
    property <float> osc: Math.sin(root.phase);

    Rectangle {{
        width: 100%; height: 100%;
        background: root.tile-color;
        border-radius: root.tile-radius;
        clip: true;

        Image {{ source: @image-url("layers/pm-layer-bracketL.svg"); colorize: root.mark-color; width: 100%; height: 100%; }}
        Image {{ source: @image-url("layers/pm-layer-bracketR.svg"); colorize: root.mark-color; width: 100%; height: 100%; }}

        // left assembly (P + string) and right assembly (M + string) move in opposition
        Image {{ source: @image-url("layers/pm-layer-glyphM.svg"); colorize: root.mark-color; width: 100%; height: 100%;
                y: -root.osc * root.size * 0.65/43.2; }}
        Image {{ source: @image-url("layers/pm-layer-glyphP.svg"); colorize: root.mark-color; width: 100%; height: 100%;
                y: root.osc * root.size * 0.61/43.2; }}
        Image {{ source: @image-url("layers/pm-layer-pkeyline.svg"); colorize: root.tile-color; width: 100%; height: 100%;
                y: root.osc * root.size * 0.61/43.2; }}
        Rectangle {{ x: root.size * 14.42/43.2; y: root.size * 15.6/43.2 + root.osc * root.size * 0.61/43.2;
            width: root.size * 0.97/43.2; height: root.size * 8.59/43.2;
            border-radius: self.width/2; background: root.string-color; }}
        Rectangle {{ x: root.size * 28.85/43.2; y: root.size * 16.28/43.2 - root.osc * root.size * 0.65/43.2;
            width: root.size * 0.97/43.2; height: root.size * 12.18/43.2;
            border-radius: self.width/2; background: root.string-color; }}

        Image {{
            source: @image-url("layers/pm-layer-bar.svg");
            colorize: root.mark-color;
            width: 100%; height: 100%;
            rotation-angle: -5deg * root.osc;
            rotation-origin-x: self.width * 21.9/43.2;
            rotation-origin-y: self.height * 14.5/43.2;
        }}
    }}
}}
"""

    comps["pm_loading_bob.slint"] = SLINT_HEADER.format(name="pm_loading_bob.slint", title="Marionette Bob") + f"""
export component PmLoadingBob {{
{SLINT_COMMON_PROPS}    in property <duration> period: 1200ms;
    property <angle> phase: 360deg * (animation-tick() / root.period);
    property <float> oscP: Math.sin(root.phase);
    property <float> oscM: Math.sin(root.phase + 180deg);

    Rectangle {{
        width: 100%; height: 100%;
        background: root.tile-color;
        border-radius: root.tile-radius;
        clip: true;

        Image {{ source: @image-url("layers/pm-layer-bar.svg"); colorize: root.mark-color; width: 100%; height: 100%; }}
        Image {{ source: @image-url("layers/pm-layer-bracketL.svg"); colorize: root.mark-color; width: 100%; height: 100%; }}
        Image {{ source: @image-url("layers/pm-layer-bracketR.svg"); colorize: root.mark-color; width: 100%; height: 100%; }}

        Image {{ source: @image-url("layers/pm-layer-glyphM.svg"); colorize: root.mark-color; width: 100%; height: 100%;
                y: root.oscM * root.size * 1.2/43.2; }}
        Image {{ source: @image-url("layers/pm-layer-glyphP.svg"); colorize: root.mark-color; width: 100%; height: 100%;
                y: root.oscP * root.size * 1.2/43.2; }}
        Image {{ source: @image-url("layers/pm-layer-pkeyline.svg"); colorize: root.tile-color; width: 100%; height: 100%;
                y: root.oscP * root.size * 1.2/43.2; }}

        // strings stretch from their tops to stay attached to the letters
        Rectangle {{ x: root.size * 14.42/43.2; y: root.size * 15.6/43.2;
            width: root.size * 0.97/43.2;
            height: root.size * 8.59/43.2 + root.oscP * root.size * 1.2/43.2;
            border-radius: self.width/2; background: root.string-color; }}
        Rectangle {{ x: root.size * 28.85/43.2; y: root.size * 16.28/43.2;
            width: root.size * 0.97/43.2;
            height: root.size * 12.18/43.2 + root.oscM * root.size * 1.2/43.2;
            border-radius: self.width/2; background: root.string-color; }}
    }}
}}
"""
    return comps


# ------------------------------------------------------------------- assembly

def build_all():
    parts = parse_source()
    source_sha = hashlib.sha256(SOURCE.read_bytes()).hexdigest()

    files = {}
    themes_meta = []
    mix_css = {a["slug"]: {} for a in ANIMS}

    for pal in PALETTES:
        static = build_static(parts, pal)
        anim_slug = PAIRING[pal["slug"]]
        animated = build_animated(static, pal, anim_slug)
        files[f"icons/static/pm-{pal['slug']}.svg"] = static
        files[f"icons/animated/pm-{pal['slug']}-loading.svg"] = animated
        for anim in ANIMS:
            mix_css[anim["slug"]][pal["slug"]] = anim_css(anim["slug"], pal, "mix")
        themes_meta.append(dict(
            slug=pal["slug"], label=pal["label"], family=pal["family"], mode=pal["mode"],
            pageBg=pal["page_bg"], surface=pal["surface"], text=pal["text"], muted=pal["muted"],
            mark=pal["mark"], string=pal["string"], tileDesc=pal["tile_desc"],
            rx=pal["rx"], motion=anim_slug, staticSvg=static, animatedSvg=animated,
        ))

    files["icons/template/pm-tray-Template.svg"] = build_template(parts, "#000000", "template")
    files["icons/template/pm-tray-white.svg"] = build_template(parts, "#FFFFFF", "template-w")

    layers = build_slint_layers(parts)
    for name, text in layers.items():
        files[f"slint/layers/{name}"] = text
    slint_comps = build_slint_components()
    for name, text in slint_comps.items():
        files[f"slint/{name}"] = text

    data_blob = dict(
        sourceSha=source_sha,
        themes=themes_meta,
        anims=[dict(a) for a in ANIMS],
        mixCss=mix_css,
        template=dict(black=files["icons/template/pm-tray-Template.svg"],
                      white=files["icons/template/pm-tray-white.svg"]),
        slintFiles={n.replace("pm_loading_", "").replace(".slint", ""): t for n, t in slint_comps.items()},
        slintFileNames=sorted(slint_comps.keys()),
        slintLayers=layers,
    )

    manifest = dict(
        generator="generate.py",
        sourceSha256=source_sha,
        themes=[{k: v for k, v in t.items() if k not in ("staticSvg", "animatedSvg")} for t in themes_meta],
        anims=[dict(a) for a in ANIMS],
        pairing=PAIRING,
        files=sorted(files.keys()) + ["manifest.json"],
    )
    files["manifest.json"] = json.dumps(manifest, indent=2, sort_keys=False) + "\n"

    return files, data_blob


def splice_index(data_blob):
    html = INDEX.read_text(encoding="utf-8")
    begin = html.find(MARK_BEGIN)
    end = html.find(MARK_END)
    if begin == -1 or end == -1 or end < begin:
        raise SystemExit("index.html is missing the FABLEICON:DATA markers")
    payload = json.dumps(data_blob, separators=(",", ":")).replace("</", "<\\/")
    block = (MARK_BEGIN + "\n<script id=\"fableicon-data\" type=\"application/json\">"
             + payload + "</script>\n")
    return html[:begin] + block + html[end:]


def main():
    check = "--check" in sys.argv
    files, data_blob = build_all()

    drift = []
    for rel, content in sorted(files.items()):
        path = HERE / rel
        if check:
            on_disk = path.read_text(encoding="utf-8") if path.exists() else None
            if on_disk != content:
                drift.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    spliced = splice_index(data_blob)
    if check:
        if spliced != INDEX.read_text(encoding="utf-8"):
            drift.append("index.html (data region)")
        if drift:
            print("DRIFT detected in:\n  " + "\n  ".join(drift))
            sys.exit(1)
        print(f"--check OK: {len(files)} files + index.html data region match")
    else:
        INDEX.write_text(spliced, encoding="utf-8")
        print(f"wrote {len(files)} files + spliced index.html data region")


if __name__ == "__main__":
    main()
