#!/usr/bin/env python3
"""Cursoricon generator — sole author of every generated artifact in this folder.

Emits theme statics, chrome opticals, 64 film-level animated loaders, tray/app
masters, baked PNG/ICO/ICNS rasters, manifest.json, and the index.html data region.

Modes:
  python3 generate.py            build everything
  python3 generate.py --check    rebuild in memory, diff against disk, exit 1 on drift
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE / "source" / "pm-logo-source.svg"
INDEX = HERE / "index.html"
MARK_BEGIN = "<!-- CURSORICON:DATA:BEGIN (generated by generate.py - do not hand-edit this block) -->"
MARK_END = "<!-- CURSORICON:DATA:END -->"
RESVG = Path("/opt/homebrew/bin/resvg")

D_PREFIX_TO_PART = {
    "M9.34,28.55": "bracketL",
    "M26.38,32.54": "glyphM",
    "M12.93,36.25": "glyphPFill",
    "M16.15,22.88": "glyphPKeyline",
    "M16.87,14.44": "barTipL",
    "M37.76,7.6": "barTipR",
    "M36.83,21.63": "barMain",
    "M34.64,29.01": "bracketR",
}

STRING_R = dict(x="28.85", y="16.28", w=".97", h="12.18", rx=".48")
STRING_L = dict(x="14.42", y="15.6", w=".97", h="8.59", rx=".48")

PIVOT_BAR = (21.99, 13.895)
PIVOT_STR_L = (14.905, 15.6)
PIVOT_STR_R = (29.335, 16.28)
BAR_LINE = dict(x1=6.6, y1=7.0, x2=36.6, y2=21.3, length=33.2)
CANVAS = 43.2
# Measured brace gap center for caret (between P counter and M stem)
CARET = dict(x=21.35, y=24.4, w=1.05, h=7.8, rx=0.45)

EASE_SINE = "cubic-bezier(.37,0,.63,1)"
EASE_OUT = "cubic-bezier(.22,1,.36,1)"
EASE_INOUT = EASE_SINE

FAMILY_MOTION = {
    "retro": (0.88, "cubic-bezier(.2,0,0,1)"),
    "basic": (1.0, EASE_SINE),
    "glass": (1.22, EASE_OUT),
    "friendly": (1.05, "cubic-bezier(.34,1.4,.64,1)"),
}

RL_SCALE = 0.942
RL_TILE = 40.7
RL_SHADOW = 2.5

APP_PNG_SIZES = [16, 24, 32, 48, 64, 128, 256, 512, 1024]
ICO_SIZES = [16, 24, 32, 48, 64, 128, 256]


def parse_source():
    text = SOURCE.read_text(encoding="utf-8")
    parts = {}
    for d in re.findall(r'd="([^"]+)"', text):
        for prefix, name in D_PREFIX_TO_PART.items():
            if d.startswith(prefix):
                parts[name] = d
    missing = set(D_PREFIX_TO_PART.values()) - set(parts)
    if missing:
        raise SystemExit(
            f"source svg does not contain expected paths: {sorted(missing)} "
            "- was source/pm-logo-source.svg replaced with different artwork?"
        )
    for rect in (STRING_L, STRING_R):
        if f'x="{rect["x"]}"' not in text:
            raise SystemExit(f"source svg missing string rect x={rect['x']}")
    return parts


PALETTES = [
    dict(
        slug="friendly-dark", label="Friendly Dark", family="friendly", mode="dark",
        page_bg="#211E26", surface="#2A2731", text="#F0EDF4", muted="#8A8494",
        tile="#322E3A", rx=8.0, mark="#C3B1E4", string="#6FC6E8",
        tile_desc="#322E3A cozy plum + hairline",
        treatments=["hairline:rgba(240,237,244,.10)"],
    ),
    dict(
        slug="friendly-light", label="Friendly Light", family="friendly", mode="light",
        page_bg="#FBF7F3", surface="#FFFFFF", text="#4A4550", muted="#9A93A0",
        tile="#2E8BB5", rx=8.0, mark="#FFFFFF", string="#FFD166",
        tile_desc="#2E8BB5 deepened teal flood",
        treatments=[],
    ),
    dict(
        slug="glass-dark", label="Glass Dark", family="glass", mode="dark",
        page_bg="#241B36", surface="#2E2244", text="#EDE7F8", muted="#9A8FB8",
        tile=("#2E2248", "#241B36"), rx=10.0, mark="#B79CFF", string="#E58BC8",
        tile_desc="violet gradient + glass edge",
        treatments=["glass_edge_gradient"],
    ),
    dict(
        slug="glass-light", label="Glass Light", family="glass", mode="light",
        page_bg="#E4CDE4", surface="#F6F0FF", text="#453A5C", muted="#6C6480",
        tile="#8166C6", rx=10.0, mark="#F6F0FF", string="#C167B4",
        tile_desc="#8166C6 deepened violet + bright rim",
        treatments=["glass_edge_solid"],
    ),
    dict(
        slug="retro-dark", label="Retro Dark", family="retro", mode="dark",
        page_bg="#1A1A1A", surface="#252525", text="#E0E0E0", muted="#909090",
        tile="#1A1A1A", rx=0.0, mark="#00FF41", string="#FF1493",
        tile_desc="#1A1A1A + lime border",
        treatments=["retro_dark_border"],
    ),
    dict(
        slug="retro-light", label="Retro Light", family="retro", mode="light",
        page_bg="#F5F0E8", surface="#FAF7F2", text="#1A1A1A", muted="#524F49",
        tile="#0047AB", rx=0.0, mark="#F5F0E8", string="#F5F0E8",
        tile_desc="#0047AB + hard offset shadow",
        treatments=["retro_light_shadow"],
    ),
    dict(
        slug="basic-dark", label="Basic Dark", family="basic", mode="dark",
        page_bg="#121212", surface="#1E1E1E", text="#E8E8E8", muted="#6B7280",
        tile="#2D2D2D", rx=3.0, mark="#64B5F6", string="#64B5F6",
        tile_desc="#2D2D2D + hairline",
        treatments=["hairline:rgba(255,255,255,.14)"],
    ),
    dict(
        slug="basic-light", label="Basic Light", family="basic", mode="light",
        page_bg="#EAECEF", surface="#FFFFFF", text="#1A1A1A", muted="#5C6470",
        tile="#0056B3", rx=3.0, mark="#FFFFFF", string="#FFFFFF",
        tile_desc="#0056B3 flat",
        treatments=[],
    ),
]

ANIMS = [
    dict(slug="caret", name="Caret Conductor", rank=1,
         desc="Conductor baton with ease into extremes; film-blink caret in the brace gap; strings lag the bar."),
    dict(slug="pluck", name="Cozy Pluck", rank=2,
         desc="Pluck impulse with overshoot decay; traveling highlight down each stem; L/R phase opposition."),
    dict(slug="caustic", name="Caustic Sweep", rank=3,
         desc="Soft caustic band with ease-out sweep, rest hold, and brief mark brighten as it crosses."),
    dict(slug="float", name="Depth Float", rank=4,
         desc="Slow parallax layers with unequal amplitudes; strings breathe without dipping contrast."),
    dict(slug="phosphor", name="Phosphor Trace", rank=5,
         desc="Bar redraws with phosphor bloom, full-logo hold, then elegant unit fade-reset."),
    dict(slug="shadowkick", name="Hard Shadow Kick", rank=6,
         desc="Intentional stepped hard-shadow kicks with art counter-nudge and settle frames."),
    dict(slug="metronome", name="Metronome Bar", rank=7,
         desc="Precise linear ±3.5° rock; measured string opposition; zero bounce."),
    dict(slug="assemble", name="Assemble Loop", rank=8,
         desc="Staggered reveal with soft holds, long complete pose, then dissolve as one unit."),
]


# ---------------------------------------------------------------- contrast

def _hex_to_rgb(h: str):
    h = h.lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    return tuple(int(h[i : i + 2], 16) / 255.0 for i in (0, 2, 4))


def _chan(c: float) -> float:
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def rel_lum(hex_color: str) -> float:
    r, g, b = _hex_to_rgb(hex_color)
    return 0.2126 * _chan(r) + 0.7152 * _chan(g) + 0.0722 * _chan(b)


def contrast_ratio(fg: str, bg) -> float:
    if isinstance(bg, tuple):
        bg = min(bg, key=rel_lum)
    L1, L2 = rel_lum(fg), rel_lum(bg)
    hi, lo = max(L1, L2), min(L1, L2)
    return (hi + 0.05) / (lo + 0.05)


def fnum(v):
    s = f"{v:.2f}".rstrip("0").rstrip(".")
    return s if s else "0"


def tile_markup(pal, uid):
    defs, pre = [], []
    rx = fnum(pal["rx"])
    if isinstance(pal["tile"], tuple):
        top, bottom = pal["tile"]
        gid = f"gradTile-{uid}"
        defs.append(
            f'<linearGradient id="{gid}" x1="0" y1="0" x2="0" y2="{CANVAS}" gradientUnits="userSpaceOnUse">'
            f'<stop offset="0" stop-color="{top}"/><stop offset="1" stop-color="{bottom}"/></linearGradient>'
        )
        tile_fill = f"url(#{gid})"
    else:
        tile_fill = pal["tile"]

    if "retro_light_shadow" in pal["treatments"]:
        pre.append(
            f'<rect x="{RL_SHADOW}" y="{RL_SHADOW}" width="{RL_TILE}" height="{RL_TILE}" rx="{rx}" fill="#1A1A1A"/>'
        )
        pre.append(
            f'<rect id="tile-{uid}" width="{RL_TILE}" height="{RL_TILE}" rx="{rx}" fill="{tile_fill}"/>'
        )
    else:
        pre.append(
            f'<rect id="tile-{uid}" width="{CANVAS}" height="{CANVAS}" rx="{rx}" fill="{tile_fill}"/>'
        )

    for t in pal["treatments"]:
        if t == "retro_dark_border":
            pre.append(
                f'<rect x=".6" y=".6" width="42" height="42" fill="none" stroke="{pal["mark"]}" stroke-width="1.2"/>'
            )
        elif t.startswith("hairline:"):
            color = t.split(":", 1)[1]
            hrx = fnum(max(pal["rx"] - 0.4, 0))
            pre.append(
                f'<rect x=".5" y=".5" width="42.2" height="42.2" rx="{hrx}" fill="none" stroke="{color}" stroke-width="1"/>'
            )
        elif t == "glass_edge_gradient":
            gid = f"gradEdge-{uid}"
            defs.append(
                f'<linearGradient id="{gid}" x1="0" y1="0" x2="0" y2="{CANVAS}" gradientUnits="userSpaceOnUse">'
                f'<stop offset="0" stop-color="#FFFFFF" stop-opacity=".55"/>'
                f'<stop offset="1" stop-color="#FFFFFF" stop-opacity=".10"/></linearGradient>'
            )
            pre.append(
                f'<rect x=".5" y=".5" width="42.2" height="42.2" rx="9.6" fill="none" stroke="url(#{gid})" stroke-width="1"/>'
            )
        elif t == "glass_edge_solid":
            pre.append(
                '<rect x=".5" y=".5" width="42.2" height="42.2" rx="9.6" fill="none" stroke="rgba(255,255,255,.95)" stroke-width="1"/>'
            )
    return defs, pre, tile_fill


def build_static(parts, pal):
    """Instrumented full-size master: animation hooks present but inert."""
    uid = pal["slug"]
    rx = fnum(pal["rx"])
    mark, string = pal["mark"], pal["string"]
    defs, pre, tile_fill = tile_markup(pal, uid)

    defs.append(
        f'<clipPath id="tileClip-{uid}"><rect width="{CANVAS}" height="{CANVAS}" rx="{rx}"/></clipPath>'
    )
    shim_alpha = ".32" if pal["mode"] == "dark" else ".5"
    defs.append(
        f'<linearGradient id="shimGrad-{uid}" x1="0" y1="0" x2="1" y2="0">'
        f'<stop offset="0" stop-color="#FFFFFF" stop-opacity="0"/>'
        f'<stop offset=".45" stop-color="#FFFFFF" stop-opacity="{shim_alpha}"/>'
        f'<stop offset=".55" stop-color="#FFFFFF" stop-opacity="{shim_alpha}"/>'
        f'<stop offset="1" stop-color="#FFFFFF" stop-opacity="0"/></linearGradient>'
    )
    # Phosphor bloom filter
    defs.append(
        f'<filter id="bloom-{uid}" x="-40%" y="-40%" width="180%" height="180%">'
        f'<feGaussianBlur in="SourceGraphic" stdDeviation="1.1" result="b"/>'
        f'<feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>'
    )

    bx, by = PIVOT_BAR
    lx, ly = PIVOT_STR_L
    rx_, ry_ = PIVOT_STR_R
    bl = BAR_LINE
    dim_floor = ".82" if pal["mode"] == "light" else ".4"

    art = []
    art.append(f'<g id="shadowDup-{uid}" class="a-shadow" display="none" opacity=".5">')
    art.append('  <g transform="translate(1.6 1.6)">')
    for k in ("barTipL", "barTipR", "barMain", "bracketL", "bracketR", "glyphM", "glyphPFill"):
        art.append(f'    <path fill="{mark}" d="{parts[k]}"/>')
    art.append("  </g></g>")

    # Puppets: braces + glyphs + caret (marionette hangers)
    art.append(f'<g id="puppets-{uid}" class="a-puppets">')
    art.append(f'  <path id="bracketL-{uid}" class="a-brkL" fill="{mark}" d="{parts["bracketL"]}"/>')
    art.append(f'  <path id="bracketR-{uid}" class="a-brkR" fill="{mark}" d="{parts["bracketR"]}"/>')
    art.append(f'  <g id="glyphM-{uid}" class="a-m a-followR"><path fill="{mark}" d="{parts["glyphM"]}"/></g>')
    art.append(f'  <g id="glyphP-{uid}" class="a-p a-followL">')
    art.append(f'    <path id="glyphPFill-{uid}" fill="{mark}" d="{parts["glyphPFill"]}"/>')
    art.append(f'    <path id="glyphPKeyline-{uid}" fill="{tile_fill}" d="{parts["glyphPKeyline"]}"/>')
    art.append("  </g>")
    art.append(
        f'  <rect id="caret-{uid}" class="a-caret" x="{CARET["x"]}" y="{CARET["y"]}" '
        f'width="{CARET["w"]}" height="{CARET["h"]}" rx="{CARET["rx"]}" fill="{mark}" display="none"/>'
    )
    art.append("</g>")

    art.append('<g class="a-barclip">')
    art.append(
        f'  <g transform="translate({fnum(bx)} {fnum(by)})"><g class="a-bar"><g transform="translate(-{fnum(bx)} -{fnum(by)})">'
    )
    art.append(f'    <g id="bar-{uid}">')
    art.append(f'      <path id="barTipL-{uid}" class="a-barTipL" fill="{mark}" d="{parts["barTipL"]}"/>')
    art.append(f'      <path id="barTipR-{uid}" class="a-barTipR" fill="{mark}" d="{parts["barTipR"]}"/>')
    art.append(f'      <path id="barMain-{uid}" class="a-barMain" fill="{mark}" d="{parts["barMain"]}"/>')
    art.append(
        f'      <line id="barLine-{uid}" class="a-barLine" x1="{bl["x1"]}" y1="{bl["y1"]}" '
        f'x2="{bl["x2"]}" y2="{bl["y2"]}" stroke="{mark}" stroke-width="1.9" '
        f'stroke-linecap="round" display="none"/>'
    )
    art.append("    </g>")
    art.append("  </g></g></g></g>")

    art.append(f'<g id="strings-{uid}" class="a-strings">')
    art.append(
        f'  <g transform="translate({fnum(lx)} {fnum(ly)})"><g class="a-strL"><g transform="translate(-{fnum(lx)} -{fnum(ly)})">'
    )
    art.append(
        f'    <rect id="stringL-{uid}" x="{STRING_L["x"]}" y="{STRING_L["y"]}" width="{STRING_L["w"]}" '
        f'height="{STRING_L["h"]}" rx="{STRING_L["rx"]}" fill="{string}"/>'
    )
    art.append("  </g></g></g>")
    art.append(
        f'  <g transform="translate({fnum(rx_)} {fnum(ry_)})"><g class="a-strR"><g transform="translate(-{fnum(rx_)} -{fnum(ry_)})">'
    )
    art.append(
        f'    <rect id="stringR-{uid}" x="{STRING_R["x"]}" y="{STRING_R["y"]}" width="{STRING_R["w"]}" '
        f'height="{STRING_R["h"]}" rx="{STRING_R["rx"]}" fill="{string}"/>'
    )
    art.append("  </g></g></g></g>")

    art.append(f'<g id="pulses-{uid}" display="none">')
    art.append(
        f'  <line id="pulseL-{uid}" x1="{fnum(lx)}" y1="15.6" x2="{fnum(lx)}" y2="24.19" '
        f'stroke="{string}" stroke-width="1.35" stroke-linecap="round" opacity=".95"/>'
    )
    art.append(
        f'  <line id="pulseR-{uid}" x1="{fnum(rx_)}" y1="16.28" x2="{fnum(rx_)}" y2="28.46" '
        f'stroke="{string}" stroke-width="1.35" stroke-linecap="round" opacity=".95"/>'
    )
    art.append("</g>")

    art.append(f'<g id="shimmer-{uid}" display="none" clip-path="url(#tileClip-{uid})">')
    art.append('  <g transform="rotate(18 21.6 21.6)">')
    art.append(f'    <rect class="band" x="-10" y="-28" width="16" height="100" fill="url(#shimGrad-{uid})"/>')
    art.append("  </g></g>")

    # Unit dissolve group target for assemble
    art.append(f'<!-- dim-floor marker {dim_floor} -->')

    scale = f' transform="scale({RL_SCALE})"' if "retro_light_shadow" in pal["treatments"] else ""
    lines = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {CANVAS} {CANVAS}" id="pmx-{uid}">']
    lines.append("<defs>" + "".join(defs) + "</defs>")
    lines.extend(pre)
    lines.append(f'<g id="artwrap-{uid}" class="a-unit"{scale}>')
    lines.extend(art)
    lines.append("</g></svg>")
    return "\n".join(lines) + "\n"


def build_chrome(parts, pal):
    """Optical tier for ~20–24px title-bar: thicker strings, narrowed cross, heavier brackets."""
    uid = f"chrome-{pal['slug']}"
    mark, string = pal["mark"], pal["string"]
    defs, pre, tile_fill = tile_markup(pal, uid)
    bx, by = PIVOT_BAR
    thick = 1.45
    lx = 14.42 + 0.97 / 2 - thick / 2
    rxp = 28.85 + 0.97 / 2 - thick / 2

    art = []
    art.append(f'<g transform="translate({fnum(bx)} {fnum(by)}) scale(1.06) translate(-{fnum(bx)} -{fnum(by)})">')
    art.append(f'  <path fill="{mark}" d="{parts["bracketL"]}"/>')
    art.append(f'  <path fill="{mark}" d="{parts["bracketR"]}"/>')
    art.append(f'  <path fill="{mark}" d="{parts["glyphM"]}"/>')
    art.append(f'  <path fill="{mark}" d="{parts["glyphPFill"]}"/>')
    art.append(f'  <path fill="{tile_fill}" d="{parts["glyphPKeyline"]}"/>')
    art.append("</g>")
    art.append(
        f'<g transform="translate({fnum(bx)} {fnum(by)}) scale(.90) translate(-{fnum(bx)} -{fnum(by)})">'
    )
    art.append(f'  <path fill="{mark}" d="{parts["barTipL"]}"/>')
    art.append(f'  <path fill="{mark}" d="{parts["barTipR"]}"/>')
    art.append(f'  <path fill="{mark}" d="{parts["barMain"]}"/>')
    art.append("</g>")
    art.append(f'<rect x="{fnum(lx)}" y="14.9" width="{thick}" height="9.2" rx="{thick/2}" fill="{string}"/>')
    art.append(f'<rect x="{fnum(rxp)}" y="15.5" width="{thick}" height="12.6" rx="{thick/2}" fill="{string}"/>')

    scale = f' transform="scale({RL_SCALE})"' if "retro_light_shadow" in pal["treatments"] else ""
    lines = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {CANVAS} {CANVAS}" id="pmx-{uid}">']
    lines.append("<defs>" + "".join(defs) + "</defs>")
    lines.extend(pre)
    lines.append(f"<g{scale}>")
    lines.extend(art)
    lines.append("</g></svg>")
    return "\n".join(lines) + "\n"


def build_tray(parts, color: str, name: str):
    """Monochrome tray: no tile; punched P keyline; chrome proportions + thick strings."""
    thick_w = 1.7
    lx = 14.42 + 0.97 / 2 - thick_w / 2
    rxp = 28.85 + 0.97 / 2 - thick_w / 2
    bx, by = PIVOT_BAR
    lines = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {CANVAS} {CANVAS}" id="pmx-{name}">']
    lines.append("<defs>")
    lines.append(
        f'<mask id="pmask-{name}"><rect width="{CANVAS}" height="{CANVAS}" fill="#fff"/>'
        f'<path d="{parts["glyphPKeyline"]}" fill="#000"/></mask>'
    )
    lines.append("</defs>")
    lines.append(
        f'<g fill="{color}" mask="url(#pmask-{name})" '
        f'transform="translate({fnum(bx)} {fnum(by)}) scale(1.08) translate(-{fnum(bx)} -{fnum(by)})">'
    )
    lines.append(f'  <path d="{parts["bracketL"]}"/>')
    lines.append(f'  <path d="{parts["bracketR"]}"/>')
    lines.append(f'  <path d="{parts["glyphM"]}"/>')
    lines.append(f'  <path d="{parts["glyphPFill"]}"/>')
    lines.append("</g>")
    lines.append(
        f'<g fill="{color}" transform="translate({fnum(bx)} {fnum(by)}) scale(.88) translate(-{fnum(bx)} -{fnum(by)})">'
    )
    lines.append(f'  <path d="{parts["barTipL"]}"/>')
    lines.append(f'  <path d="{parts["barTipR"]}"/>')
    lines.append(f'  <path d="{parts["barMain"]}"/>')
    lines.append("</g>")
    lines.append(f'<g fill="{color}">')
    lines.append(f'  <rect x="{fnum(lx)}" y="14.6" width="{thick_w}" height="9.6" rx="{thick_w/2}"/>')
    lines.append(f'  <rect x="{fnum(rxp)}" y="15.2" width="{thick_w}" height="13.2" rx="{thick_w/2}"/>')
    lines.append("</g></svg>")
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ film animations

def anim_css(anim_slug, pal, root_uid):
    u = pal["slug"]
    r = root_uid
    s = f"#pmx-{r}"
    mult, fam_ease = FAMILY_MOTION[pal["family"]]
    light = pal["mode"] == "light"
    lo = ".82" if light else ".42"

    def d(base):
        return str(int(round(base * mult)))

    lag = d(int(120 * (1 if mult >= 1 else 0.9)))  # ~1/12 of a 1400ms cycle scaled

    if anim_slug == "caret":
        # Conductor: ease into extremes, soft settle at ends; strings lag bar; film blink 2-open/1-closed
        body = f"""
  {s} .a-bar {{ animation: pmCaretBar-{r} {d(1600)}ms {EASE_SINE} infinite; }}
  {s} .a-caret {{ display: inline; animation: pmCaretBlink-{r} 720ms steps(1, end) infinite; }}
  {s} .a-strL {{ animation: pmCaretL-{r} {d(1600)}ms {EASE_SINE} infinite; animation-delay: {lag}ms; }}
  {s} .a-followL {{ animation: pmCaretL-{r} {d(1600)}ms {EASE_SINE} infinite; animation-delay: {lag}ms; }}
  {s} .a-strR {{ animation: pmCaretR-{r} {d(1600)}ms {EASE_SINE} infinite; animation-delay: {lag}ms; }}
  {s} .a-followR {{ animation: pmCaretR-{r} {d(1600)}ms {EASE_SINE} infinite; animation-delay: {lag}ms; }}
  @keyframes pmCaretBar-{r} {{
    0%, 100% {{ transform: rotate(-5.5deg); }}
    12% {{ transform: rotate(-6.2deg); }}
    50% {{ transform: rotate(5.5deg); }}
    62% {{ transform: rotate(6.2deg); }}
  }}
  @keyframes pmCaretBlink-{r} {{
    0%, 55% {{ opacity: 1; }}
    56%, 88% {{ opacity: 0; }}
    89%, 100% {{ opacity: 1; }}
  }}
  @keyframes pmCaretL-{r} {{
    0%, 100% {{ transform: translateY(.55px); }}
    12% {{ transform: translateY(.72px); }}
    50% {{ transform: translateY(-.55px); }}
    62% {{ transform: translateY(-.72px); }}
  }}
  @keyframes pmCaretR-{r} {{
    0%, 100% {{ transform: translateY(-.58px); }}
    12% {{ transform: translateY(-.75px); }}
    50% {{ transform: translateY(.58px); }}
    62% {{ transform: translateY(.75px); }}
  }}"""
    elif anim_slug == "pluck":
        body = f"""
  {s} #pulses-{u} {{ display: inline; }}
  {s} .a-strings {{ opacity: .62; }}
  {s} .a-strL {{
    animation: pmPluckL-{r} {d(1400)}ms {EASE_OUT} infinite;
    transform-origin: 50% 0%; transform-box: fill-box;
  }}
  {s} .a-strR {{
    animation: pmPluckR-{r} {d(1400)}ms {EASE_OUT} infinite; animation-delay: -{d(700)}ms;
    transform-origin: 50% 0%; transform-box: fill-box;
  }}
  {s} #pulseL-{u} {{
    stroke-dasharray: 1.8 7.0; stroke-dashoffset: 8.59;
    animation: pmTravL-{r} {d(1400)}ms {EASE_SINE} infinite;
  }}
  {s} #pulseR-{u} {{
    stroke-dasharray: 2.0 10.2; stroke-dashoffset: 12.18;
    animation: pmTravR-{r} {d(1400)}ms {EASE_SINE} infinite; animation-delay: -{d(700)}ms;
  }}
  {s} .a-p {{ animation: pmGlowP-{r} {d(1400)}ms {EASE_SINE} infinite; }}
  {s} .a-m {{ animation: pmGlowP-{r} {d(1400)}ms {EASE_SINE} infinite; animation-delay: -{d(700)}ms; }}
  @keyframes pmPluckL-{r} {{
    0%, 100% {{ transform: scaleX(1) scaleY(1); }}
    8% {{ transform: scaleX(1.55) scaleY(.86); }}
    18% {{ transform: scaleX(.92) scaleY(1.04); }}
    28% {{ transform: scaleX(1.08) scaleY(.98); }}
    40% {{ transform: scaleX(1) scaleY(1); }}
  }}
  @keyframes pmPluckR-{r} {{
    0%, 100% {{ transform: scaleX(1) scaleY(1); }}
    8% {{ transform: scaleX(1.55) scaleY(.86); }}
    18% {{ transform: scaleX(.92) scaleY(1.04); }}
    28% {{ transform: scaleX(1.08) scaleY(.98); }}
    40% {{ transform: scaleX(1) scaleY(1); }}
  }}
  @keyframes pmTravL-{r} {{
    0% {{ stroke-dashoffset: 8.59; opacity: 0; }}
    12% {{ opacity: 1; }}
    55% {{ stroke-dashoffset: 0; opacity: 1; }}
    70%, 100% {{ stroke-dashoffset: 0; opacity: 0; }}
  }}
  @keyframes pmTravR-{r} {{
    0% {{ stroke-dashoffset: 12.18; opacity: 0; }}
    12% {{ opacity: 1; }}
    55% {{ stroke-dashoffset: 0; opacity: 1; }}
    70%, 100% {{ stroke-dashoffset: 0; opacity: 0; }}
  }}
  @keyframes pmGlowP-{r} {{
    0%, 45% {{ opacity: {lo if light else '.78'}; }}
    58% {{ opacity: 1; }}
    72%, 100% {{ opacity: {lo if light else '.78'}; }}
  }}"""
    elif anim_slug == "caustic":
        body = f"""
  {s} #shimmer-{u} {{ display: inline; }}
  {s} .band {{ animation: pmCaustic-{r} {d(2200)}ms {EASE_OUT} infinite; }}
  {s} .a-unit {{ animation: pmCausticBright-{r} {d(2200)}ms {EASE_SINE} infinite; }}
  @keyframes pmCaustic-{r} {{
    0% {{ transform: translateX(-38px); }}
    48% {{ transform: translateX(62px); }}
    70%, 100% {{ transform: translateX(62px); }}
  }}
  @keyframes pmCausticBright-{r} {{
    0%, 12% {{ filter: brightness(1); }}
    28% {{ filter: brightness(1.08); }}
    48% {{ filter: brightness(1.04); }}
    60%, 100% {{ filter: brightness(1); }}
  }}"""
    elif anim_slug == "float":
        body = f"""
  {s} .a-bar {{ animation: pmFloatBar-{r} {d(2800)}ms {EASE_SINE} infinite; }}
  {s} .a-strings {{ animation: pmFloatStr-{r} {d(2800)}ms {EASE_SINE} infinite; animation-delay: -{d(350)}ms; }}
  {s} .a-puppets {{ animation: pmFloatPup-{r} {d(2800)}ms {EASE_SINE} infinite; animation-delay: -{d(700)}ms; }}
  @keyframes pmFloatBar-{r} {{
    0%, 100% {{ transform: translateY(-1.05px); }}
    50% {{ transform: translateY(1.05px); }}
  }}
  @keyframes pmFloatPup-{r} {{
    0%, 100% {{ transform: translateY(.7px); }}
    50% {{ transform: translateY(-.7px); }}
  }}
  @keyframes pmFloatStr-{r} {{
    0%, 100% {{ opacity: .88; transform: translateY(.25px); }}
    50% {{ opacity: 1; transform: translateY(-.25px); }}
  }}"""
    elif anim_slug == "phosphor":
        L = BAR_LINE["length"]
        step = "steps(8, end)" if pal["family"] == "retro" else fam_ease
        body = f"""
  {s} #barLine-{u} {{
    display: inline; stroke-dasharray: {L} {L};
    filter: url(#bloom-{u});
    animation: pmPhosDraw-{r} {d(2200)}ms {step} infinite;
  }}
  {s} .a-barMain {{ opacity: 0; }}
  {s} .a-barTipL, {s} .a-barTipR {{
    animation: pmPhosTips-{r} {d(2200)}ms {step} infinite;
  }}
  {s} .a-puppets, {s} .a-strings {{
    animation: pmPhosReveal-{r} {d(2200)}ms {EASE_SINE} infinite;
  }}
  {s} .a-unit {{
    animation: pmPhosUnit-{r} {d(2200)}ms {EASE_SINE} infinite;
  }}
  @keyframes pmPhosDraw-{r} {{
    0% {{ stroke-dashoffset: {L}; opacity: .6; }}
    38% {{ stroke-dashoffset: 0; opacity: 1; }}
    62% {{ stroke-dashoffset: 0; opacity: 1; }}
    78% {{ stroke-dashoffset: 0; opacity: 0; }}
    100% {{ stroke-dashoffset: -{L}; opacity: 0; }}
  }}
  @keyframes pmPhosTips-{r} {{
    0%, 8% {{ opacity: {lo}; }}
    18%, 55% {{ opacity: 1; }}
    70%, 100% {{ opacity: {lo}; }}
  }}
  @keyframes pmPhosReveal-{r} {{
    0%, 32% {{ opacity: {lo}; }}
    42%, 62% {{ opacity: 1; }}
    78%, 100% {{ opacity: {lo}; }}
  }}
  @keyframes pmPhosUnit-{r} {{
    0%, 70% {{ opacity: 1; }}
    88%, 100% {{ opacity: 0; }}
  }}"""
    elif anim_slug == "shadowkick":
        body = f"""
  {s} #shadowDup-{u} {{ display: inline; animation: pmKick-{r} {d(1100)}ms steps(1, end) infinite; }}
  {s} .a-bar, {s} .a-puppets, {s} .a-strings {{
    animation: pmKickArt-{r} {d(1100)}ms steps(1, end) infinite;
  }}
  @keyframes pmKick-{r} {{
    0%, 8% {{ transform: translate(0, 0); opacity: .15; }}
    9%, 22% {{ transform: translate(2.4px, 2.4px); opacity: .55; }}
    23%, 36% {{ transform: translate(1.0px, 1.8px); opacity: .42; }}
    37%, 50% {{ transform: translate(2.8px, 1.2px); opacity: .5; }}
    51%, 64% {{ transform: translate(1.6px, 2.6px); opacity: .48; }}
    65%, 78% {{ transform: translate(.6px, .6px); opacity: .28; }}
    79%, 100% {{ transform: translate(0, 0); opacity: .15; }}
  }}
  @keyframes pmKickArt-{r} {{
    0%, 8% {{ transform: translate(0, 0); }}
    9%, 22% {{ transform: translate(-.45px, -.45px); }}
    23%, 36% {{ transform: translate(-.2px, -.35px); }}
    37%, 50% {{ transform: translate(-.5px, -.2px); }}
    51%, 64% {{ transform: translate(-.3px, -.5px); }}
    65%, 78% {{ transform: translate(-.1px, -.1px); }}
    79%, 100% {{ transform: translate(0, 0); }}
  }}"""
    elif anim_slug == "metronome":
        body = f"""
  {s} .a-bar {{ animation: pmMetro-{r} {d(1200)}ms linear infinite; }}
  {s} .a-strL {{ animation: pmMetroL-{r} {d(1200)}ms linear infinite; animation-delay: {lag}ms; }}
  {s} .a-followL {{ animation: pmMetroL-{r} {d(1200)}ms linear infinite; animation-delay: {lag}ms; }}
  {s} .a-strR {{ animation: pmMetroR-{r} {d(1200)}ms linear infinite; animation-delay: {lag}ms; }}
  {s} .a-followR {{ animation: pmMetroR-{r} {d(1200)}ms linear infinite; animation-delay: {lag}ms; }}
  @keyframes pmMetro-{r} {{
    0%, 100% {{ transform: rotate(-3.5deg); }}
    50% {{ transform: rotate(3.5deg); }}
  }}
  @keyframes pmMetroL-{r} {{
    0%, 100% {{ transform: translateY(.42px); }}
    50% {{ transform: translateY(-.42px); }}
  }}
  @keyframes pmMetroR-{r} {{
    0%, 100% {{ transform: translateY(-.45px); }}
    50% {{ transform: translateY(.45px); }}
  }}"""
    elif anim_slug == "assemble":
        body = f"""
  {s} .a-bar {{ animation: pmAsmBar-{r} {d(3200)}ms {EASE_OUT} infinite; }}
  {s} .a-strL {{
    animation: pmAsmStrL-{r} {d(3200)}ms {EASE_OUT} infinite;
    transform-origin: 50% 0%;
  }}
  {s} .a-strR {{
    animation: pmAsmStrR-{r} {d(3200)}ms {EASE_OUT} infinite;
    transform-origin: 50% 0%;
  }}
  {s} .a-brkL, {s} .a-brkR {{ animation: pmAsmBrk-{r} {d(3200)}ms {EASE_SINE} infinite; }}
  {s} .a-p, {s} .a-m {{
    animation: pmAsmGlyph-{r} {d(3200)}ms {EASE_OUT} infinite;
    transform-box: fill-box; transform-origin: 50% 50%;
  }}
  {s} .a-unit {{ animation: pmAsmUnit-{r} {d(3200)}ms {EASE_SINE} infinite; }}
  @keyframes pmAsmBar-{r} {{
    0% {{ opacity: 0; transform: scale(.94); }}
    10% {{ opacity: 1; transform: scale(1); }}
    72% {{ opacity: 1; transform: scale(1); }}
    100% {{ opacity: 1; transform: scale(1); }}
  }}
  @keyframes pmAsmStrL-{r} {{
    0%, 8% {{ transform: scaleY(0); opacity: 1; }}
    22% {{ transform: scaleY(1); opacity: 1; }}
    100% {{ transform: scaleY(1); opacity: 1; }}
  }}
  @keyframes pmAsmStrR-{r} {{
    0%, 12% {{ transform: scaleY(0); opacity: 1; }}
    26% {{ transform: scaleY(1); opacity: 1; }}
    100% {{ transform: scaleY(1); opacity: 1; }}
  }}
  @keyframes pmAsmBrk-{r} {{
    0%, 24% {{ opacity: 0; }}
    36% {{ opacity: 1; }}
    100% {{ opacity: 1; }}
  }}
  @keyframes pmAsmGlyph-{r} {{
    0%, 34% {{ opacity: 0; transform: scale(.88); }}
    48% {{ opacity: 1; transform: scale(1.02); }}
    54% {{ opacity: 1; transform: scale(1); }}
    100% {{ opacity: 1; transform: scale(1); }}
  }}
  @keyframes pmAsmUnit-{r} {{
    0%, 72% {{ opacity: 1; }}
    88%, 100% {{ opacity: 0; }}
  }}"""
    else:
        raise SystemExit(f"unknown animation {anim_slug}")

    return (
        f"/* {anim_slug} x {u} — film */\n"
        f"@media (prefers-reduced-motion: no-preference) {{{body}\n}}\n"
        + reduced_kill_block(anim_slug, s, u)
    )


def reduced_kill_block(anim_slug, s, u):
    roots = (':root[data-motion="reduced"]', ':root[data-reduced-motion="1"]')
    rules = [("*", "animation: none !important; filter: none !important;")]
    rules += {
        "caret": [(".a-caret", "display: none !important;")],
        "pluck": [
            (f"#pulses-{u}", "display: none !important;"),
            (".a-strings, .a-p, .a-m", "opacity: 1 !important;"),
        ],
        "caustic": [(f"#shimmer-{u}", "display: none !important;")],
        "phosphor": [
            (f"#barLine-{u}", "display: none !important;"),
            (".a-barMain, .a-puppets, .a-strings, .a-unit", "opacity: 1 !important;"),
        ],
        "shadowkick": [(f"#shadowDup-{u}", "display: none !important;")],
        "assemble": [
            (
                ".a-bar, .a-strL, .a-strR, .a-brkL, .a-brkR, .a-p, .a-m, .a-unit",
                "opacity: 1 !important; transform: none !important;",
            )
        ],
    }.get(anim_slug, [])
    out = []
    for targets, decl in rules:
        sels = [f"{r} {s} {t.strip()}" for r in roots for t in targets.split(",")]
        out.append(", ".join(sels) + f" {{ {decl} }}")
    return "\n".join(out) + "\n"


def build_animated(static_svg, pal, anim_slug):
    root = f"{anim_slug}-{pal['slug']}"
    svg = static_svg.replace(f'id="pmx-{pal["slug"]}"', f'id="pmx-{root}"', 1)
    css = anim_css(anim_slug, pal, root)
    if "prefers-reduced-motion" not in css:
        raise SystemExit(f"reduced-motion gate: {anim_slug} css lacks prefers-reduced-motion")
    style = f"<style>\n{css}</style>\n"
    if svg.count("</svg>") != 1:
        raise SystemExit("unexpected svg structure")
    return svg.replace("</svg>", style + "</svg>")


# ------------------------------------------------------------------- rasters

def require_resvg():
    if not RESVG.is_file():
        raise SystemExit(
            f"resvg not found at {RESVG} — install with Homebrew (brew install resvg) "
            "to bake app/tray PNG packs"
        )


def resvg_png(svg_text: str, size: int) -> bytes:
    require_resvg()
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        src = td / "in.svg"
        out = td / "out.png"
        src.write_text(svg_text, encoding="utf-8")
        subprocess.run(
            [str(RESVG), str(src), str(out), "-w", str(size), "-h", str(size)],
            check=True,
            capture_output=True,
        )
        return out.read_bytes()


def build_ico(png_by_size: dict[int, bytes]) -> bytes:
    sizes = [s for s in ICO_SIZES if s in png_by_size]
    count = len(sizes)
    header = bytearray(6 + count * 16)
    struct.pack_into("<HHH", header, 0, 0, 1, count)
    offset = 6 + count * 16
    blobs = []
    for i, sz in enumerate(sizes):
        data = png_by_size[sz]
        o = 6 + i * 16
        dim = 0 if sz >= 256 else sz
        header[o] = dim
        header[o + 1] = dim
        header[o + 2] = 0
        header[o + 3] = 0
        struct.pack_into("<HHII", header, o + 4, 1, 32, len(data), offset)
        offset += len(data)
        blobs.append(data)
    return bytes(header) + b"".join(blobs)


def build_icns(png_by_size: dict[int, bytes]) -> bytes:
    """Build ICNS via iconutil (macOS) for correctness."""
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        iconset = td / "pm.iconset"
        iconset.mkdir()
        mapping = {
            16: ["icon_16x16.png"],
            32: ["diana.k@example.org", "icon_32x32.png"],
            64: ["ivan.p@example.net"],
            128: ["icon_128x128.png"],
            256: ["wendy.h@example.net", "icon_256x256.png"],
            512: ["wendy.h@example.net", "icon_512x512.png"],
            1024: ["walt.e@example.net"],
        }
        for sz, names in mapping.items():
            if sz not in png_by_size:
                continue
            for name in names:
                (iconset / name).write_bytes(png_by_size[sz])
        out = td / "pm.icns"
        subprocess.run(["iconutil", "-c", "icns", str(iconset), "-o", str(out)], check=True)
        return out.read_bytes()


# ------------------------------------------------------------------- assembly

def build_all():
    parts = parse_source()
    source_sha = hashlib.sha256(SOURCE.read_bytes()).hexdigest()

    files: dict[str, str | bytes] = {}
    themes_meta = []
    animated_svgs: dict[str, dict[str, str]] = {a["slug"]: {} for a in ANIMS}
    chrome_svgs: dict[str, str] = {}
    warnings = []

    for pal in PALETTES:
        ratio = round(contrast_ratio(pal["mark"], pal["tile"]), 2)
        if ratio < 3.0:
            raise SystemExit(
                f"WCAG graphics floor failed for {pal['slug']}: mark on tile = {ratio}:1 (need >= 3:1)"
            )
        if ratio < 3.5:
            warnings.append(f"contrast soft for {pal['slug']}: {ratio}:1 (< 3.5)")

        static = build_static(parts, pal)
        chrome = build_chrome(parts, pal)
        files[f"icons/static/pm-{pal['slug']}.svg"] = static
        files[f"icons/chrome/pm-{pal['slug']}.svg"] = chrome
        chrome_svgs[pal["slug"]] = chrome

        for anim in ANIMS:
            animated = build_animated(static, pal, anim["slug"])
            rel = f"icons/animated/pm-{anim['slug']}-{pal['slug']}.svg"
            files[rel] = animated
            animated_svgs[anim["slug"]][pal["slug"]] = animated

        themes_meta.append(
            dict(
                slug=pal["slug"],
                label=pal["label"],
                family=pal["family"],
                mode=pal["mode"],
                pageBg=pal["page_bg"],
                surface=pal["surface"],
                text=pal["text"],
                muted=pal["muted"],
                mark=pal["mark"],
                string=pal["string"],
                tile=pal["tile"] if not isinstance(pal["tile"], tuple) else list(pal["tile"]),
                tileDesc=pal["tile_desc"],
                rx=pal["rx"],
                contrast=ratio,
                staticSvg=static,
                chromeSvg=chrome,
            )
        )

    tray_black = build_tray(parts, "#000000", "tray-template")
    tray_white = build_tray(parts, "#FFFFFF", "tray-white")
    files["icons/tray/pm-tray-Template.svg"] = tray_black
    files["icons/tray/pm-tray-white.svg"] = tray_white

    app_master = files["icons/static/pm-friendly-dark.svg"]
    files["icons/app/pm-app-master.svg"] = app_master

    # Bake rasters
    require_resvg()
    png_by_size = {}
    for sz in APP_PNG_SIZES:
        png = resvg_png(app_master, sz)
        files[f"icons/app/png/pm-app-{sz}.png"] = png
        png_by_size[sz] = png

    files["icons/app/pm-app.ico"] = build_ico(png_by_size)
    files["icons/app/pm-app.icns"] = build_icns(png_by_size)
    files["icons/app/tray/pmTemplate.png"] = resvg_png(tray_black, 16)
    files["icons/app/tray/pmTemplate@2x.png"] = resvg_png(tray_black, 32)
    files["icons/app/tray/pm-tray-white-16.png"] = resvg_png(tray_white, 16)
    files["icons/app/tray/pm-tray-white-32.png"] = resvg_png(tray_white, 32)

    data_blob = dict(
        sourceSha=source_sha,
        themes=themes_meta,
        anims=[dict(a) for a in ANIMS],
        animatedSvgs=animated_svgs,
        chromeSvgs=chrome_svgs,
        template=dict(black=tray_black, white=tray_white),
        appMaster=app_master,
        agentLabel="Cursor",
    )

    text_rels = sorted(k for k, v in files.items() if isinstance(v, str))
    bin_rels = sorted(k for k, v in files.items() if isinstance(v, bytes))
    manifest = dict(
        generator="generate.py",
        pack="Cursoricon",
        agentLabel="Cursor",
        sourceSha256=source_sha,
        themes=[{k: v for k, v in t.items() if k not in ("staticSvg", "chromeSvg")} for t in themes_meta],
        anims=[dict(a) for a in ANIMS],
        files=sorted(files.keys()) + ["manifest.json"],
        binaryFiles=bin_rels,
        warnings=warnings,
    )
    files["manifest.json"] = json.dumps(manifest, indent=2, sort_keys=False) + "\n"
    _ = text_rels
    return files, data_blob, warnings


def splice_index(data_blob):
    if not INDEX.exists():
        raise SystemExit("index.html missing — create the dashboard shell first")
    html = INDEX.read_text(encoding="utf-8")
    begin = html.find(MARK_BEGIN)
    end = html.find(MARK_END)
    if begin == -1 or end == -1 or end < begin:
        raise SystemExit("index.html is missing the CURSORICON:DATA markers")
    payload = json.dumps(data_blob, separators=(",", ":")).replace("</", "<\\/")
    block = (
        MARK_BEGIN
        + '\n<script id="cursoricon-data" type="application/json">'
        + payload
        + "</script>\n"
    )
    return html[:begin] + block + html[end:]


def write_file(path: Path, content: str | bytes):
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, bytes):
        path.write_bytes(content)
    else:
        path.write_text(content, encoding="utf-8")


def read_file(path: Path, as_bytes: bool):
    if not path.exists():
        return None
    return path.read_bytes() if as_bytes else path.read_text(encoding="utf-8")


def main():
    check = "--check" in sys.argv
    files, data_blob, warnings = build_all()
    for w in warnings:
        print("WARN:", w)

    drift = []
    for rel, content in sorted(files.items(), key=lambda x: x[0]):
        path = HERE / rel
        is_bin = isinstance(content, bytes)
        if check:
            on_disk = read_file(path, is_bin)
            if on_disk != content:
                drift.append(rel)
        else:
            write_file(path, content)

    spliced = splice_index(data_blob)
    if check:
        if spliced != INDEX.read_text(encoding="utf-8"):
            drift.append("index.html (data region)")
        if drift:
            print("DRIFT detected in:\n  " + "\n  ".join(drift))
            sys.exit(1)
        print(f"--check OK: {len(files)} files + index.html data region match")
    else:
        INDEX.write_text(spliced, encoding="utf-8")
        n_bin = sum(1 for v in files.values() if isinstance(v, bytes))
        print(f"wrote {len(files)} files ({n_bin} binary) + spliced index.html data region")


if __name__ == "__main__":
    main()
