#!/usr/bin/env python3
"""Closeout reporting only: never edits candidate science or evaluator grades."""
from pathlib import Path
import json,csv,collections,datetime,statistics
R=Path(__file__).resolve().parents[1];T=R/"final/tables";T.mkdir(exist_ok=True)
v=json.loads((R/"accounting/v2/TIMING.json").read_text());q=json.loads((R/"control/queue.json").read_text());original=json.loads((R/"control/QUEUE_ORIGINAL.json").read_text());original=original if isinstance(original,list) else original.get("queue",original.get("blocks",[]));original={x["block_id"]:x for x in original};rows=[];coverage=[]
for x in v["rows"]:
 b=next(y for y in q if y["block_id"]==x["block"]);started=x["requested_at"] is not None;delivered=x["final_delivered"];grade=x["grade"] if delivered else None
 timing=[x["delivery_within_whole_deadline"],x["occupied_within_90min"]]+[s["delivery_within_stage_deadline"] for s in x["stages"]]
 eligible=(all(timing) if all(y is not None for y in timing) and started else None)
 disposition="NOT_PROMOTED_UNSTARTED" if not started else "NO_COMPLETE_FINAL" if not delivered else "SOURCE_PASS_WITH_LIMITATIONS" if str(grade).startswith("PASS") else "SOURCE_FAIL" if grade=="FAIL" else "SOURCE_REVIEW_PENDING"
 rows.append({"block":x["block"],"arm":x["arm"],"original_phase":original.get(x["block"],{}).get("phase"),"actual_phase":x["phase"],"phase_scope":"reallocated development, not confirmation" if x["method"]=="M16" else x["phase"],"method":x["method"],"method_version":x["method_version"],"case":x["case"],"route":x["route"],"provider_role_overrides":x["provider_role_overrides"],"original_attempt_status":x["status"],"final_disposition":disposition,"complete_final_delivered":delivered,"full_final_source_quality":grade,"original_assessor_grade":x["grade"],"assessment_path":"evaluations/"+x["block"]+"/assessment.json" if (R/"evaluations"/x["block"]/"task-result.json").exists() else None,"time_eligible":eligible,"candidate_delivery_s":x["candidate_delivery_s"],"occupied_agent_s":x["occupied_agent_s"],"independently_qualified_result_s":x["qualified_result_s"],"native_activation_observed_contexts":sum(s["native_activation_observed"] is True for s in x["stages"]),"native_complete_observed_contexts":sum(s["native_complete_observed"] is True for s in x["stages"]),"native_unknown_contexts":sum(s["native_activation_observed"] is None or s["native_complete_observed"] is None for s in x["stages"]),"declared_product_contexts":len(x["stages"]),"actual_product_contexts":x.get("actual_product_contexts",len(x["stages"])),"extra_product_occupied_s":x.get("extra_product_occupied_s",0),"undeclared_product_contexts":len(x.get("extra_product_contexts",[])),"product_contexts":len(x["stages"]),"native_exact_terminal_times":"UNKNOWN","billing":None,"unstarted_reason":b.get("reason") if not started else None})
for d in sorted((R/"evaluations").iterdir()):
 p=d/"assessment.json"
 if not p.exists() or not (d/"task-result.json").exists():continue
 a=json.loads(p.read_text());coverage.append({"block":d.name,"assessment_path":"evaluations/"+d.name+"/assessment.json","scope_limits":a.get("scope_limits"),"comparative_quality_eligible":a.get("comparative_quality_eligible"),"arms":{k:{"actual_arm":y.get("actual_arm"),"axes":y.get("axes"),"primary_coverage":y.get("primary_coverage"),"preservation_coverage":y.get("preservation_coverage"),"grade_limits":y.get("grade_limits"),"remaining_review_scope":y.get("remaining_review_scope"),"unresolved":y.get("unresolved")} for k,y in a.get("arms",{}).items()}})
summary={"frozen_at":datetime.datetime.now(datetime.timezone.utc).isoformat(),"original_arms":len(rows),"started":sum(x["requested_at"] is not None for x in v["rows"]),"delivered":sum(x["complete_final_delivered"] for x in rows),"dispositions":dict(collections.Counter(x["final_disposition"] for x in rows)),"full_final_quality_counts":dict(collections.Counter(x["full_final_source_quality"] for x in rows if x["complete_final_delivered"])),"terminal_paired_assessments":len(coverage),"source_pass_and_all_time_limits":sum(str(x["full_final_source_quality"]).startswith("PASS") and x["time_eligible"] is True for x in rows),"experiment_occupied_agent_hours_partial":v["experiment_additive_occupied_agent_s_so_far"]/3600,"experiment_observed_distinct_runs":v["experiment_observed_distinct_runs"],"root_and_shared_setup_occupation_included":False,"billing":None,"confirmation_executed":False}
(T/"ALL_80_ARMS.json").write_text(json.dumps({"summary":summary,"rows":rows},indent=2)+"\n")
with (T/"ALL_80_ARMS.csv").open("w") as f:
 w=csv.DictWriter(f,fieldnames=list(rows[0]),lineterminator="\n");w.writeheader();w.writerows(rows)
(T/"ASSESSMENT_COVERAGE.json").write_text(json.dumps(coverage,indent=2)+"\n")
(R/"final/SUMMARY.json").write_text(json.dumps(summary,indent=2)+"\n")
print(json.dumps(summary))
