#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {fileURLToPath} from 'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const OUT=path.join(ROOT,'evidence','final-certification','video');fs.mkdirSync(OUT,{recursive:true});
async function pw(){for(const x of ['playwright','playwright-core','/usr/lib/node_modules/playwright/index.js','/usr/local/lib/node_modules/playwright/index.js'])try{return await import(x)}catch{}throw Error('Playwright unavailable')}
const ex=['/usr/bin/chromium','/usr/bin/chromium-browser','/usr/bin/google-chrome','/usr/bin/google-chrome-stable'].find(fs.existsSync);
function serve(){return new Promise(ok=>{const s=http.createServer((q,r)=>{let rel=decodeURIComponent((q.url||'/').split('?')[0]);if(rel==='/')rel='/index.html';const p=path.resolve(ROOT,'.'+rel);if(!p.startsWith(ROOT)){r.writeHead(403);return r.end()}fs.readFile(p,(e,b)=>{if(e){r.writeHead(404);return r.end()}r.end(b)})});s.listen(0,'127.0.0.1',()=>ok({s,port:s.address().port}))})}
const choose=(list,re)=>list.find(x=>re.test(x));
let b,s;const status=[];
try{const P=await pw();const sv=await serve();s=sv.s;const url=`http://127.0.0.1:${sv.port}/`;b=await P.chromium.launch({headless:true,executablePath:ex,args:['--no-sandbox','--disable-dev-shm-usage']});
 const scenarios=[
  ['working-animation',async p=>{const ids=await p.evaluate(()=>window.PM56_DEMO.listTriggers());const patterns=[/working.*think|think/i,/working.*explor|explor/i,/web.*search/i,/web.*fetch/i,/browser.*control/i,/bash/i,/subagent.*work|agent.*work/i,/edit/i,/browser.*test|test.*browser/i,/render/i,/valid/i,/working.*complete|complete.*work/i];for(const re of patterns){const id=choose(ids,re);if(id){await p.evaluate(id=>window.PM56_DEMO.trigger(id),id);await p.waitForTimeout(520)}}}],
  ['questionnaire-morph',async p=>{const ids=await p.evaluate(()=>window.PM56_DEMO.listTriggers());for(const re of [/question.*prepar/i,/question.*open|questionnaire/i]){const id=choose(ids,re);if(id){await p.evaluate(id=>window.PM56_DEMO.trigger(id),id);await p.waitForTimeout(850)}}const next=p.locator('#overlay-root [data-action*="next" i]:visible,#overlay-root button:has-text("Next"):visible').first();if(await next.isVisible().catch(()=>false)){await next.click({force:true});await p.waitForTimeout(700)}const submit=p.locator('#overlay-root [data-action*="submit" i]:visible,#overlay-root button:has-text("Submit"):visible').first();if(await submit.isVisible().catch(()=>false)){await submit.click({force:true});await p.waitForTimeout(900)}}],
  ['menu-and-sidecar-springs',async p=>{for(const key of ['model','mode','wand']){const a=p.locator(`[data-selector="${key}"]`).first();if(!await a.isVisible().catch(()=>false))continue;await a.click({force:true});await p.waitForTimeout(650);const sub=p.locator('#overlay-root [data-action*="effort" i]:visible,#overlay-root [data-action*="thorough" i]:visible,#overlay-root [data-submenu]:visible').first();if(await sub.isVisible().catch(()=>false)){await sub.hover();await p.waitForTimeout(650)}await p.evaluate(()=>window.PM56_DEMO.closeAll());await p.waitForTimeout(400)}}],
  ['history-and-panel-continuity',async p=>{const row=p.locator('.thread-row').nth(2);await row.hover();await p.waitForTimeout(550);await row.click({force:true});await p.waitForTimeout(650);const act=p.locator('.activity-bar button:visible,[data-activity]:visible').first();if(await act.isVisible().catch(()=>false)){await act.click({force:true});await p.waitForTimeout(650);const pin=p.locator('#overlay-root [data-action*="pin" i]:visible,#overlay-root button:has-text("Pin"):visible').first();if(await pin.isVisible().catch(()=>false)){await pin.click({force:true});await p.waitForTimeout(850)}}}],
 ];
 for(const [name,run] of scenarios){const tmp=path.join(OUT,'tmp-'+name);fs.mkdirSync(tmp,{recursive:true});const c=await b.newContext({viewport:{width:1440,height:900},recordVideo:{dir:tmp,size:{width:1440,height:900}},reducedMotion:'no-preference'});const p=await c.newPage();await p.goto(url,{waitUntil:'networkidle'});await p.waitForFunction(()=>!!window.PM56_DEMO);await p.waitForTimeout(400);await run(p);await p.waitForTimeout(500);const v=p.video();await c.close();const src=await v.path();const dst=path.join(OUT,name+'.webm');fs.copyFileSync(src,dst);status.push({name,bytes:fs.statSync(dst).size,pass:fs.statSync(dst).size>10000})}
}catch(e){status.push({name:'runner',pass:false,error:String(e.stack||e)})}finally{try{await b?.close()}catch{}try{s?.close()}catch{}}
fs.writeFileSync(path.join(ROOT,'reports','motion-recording-status.json'),JSON.stringify(status,null,2));if(!status.length||status.some(x=>!x.pass))process.exitCode=1;
