#!/usr/bin/env python3
"""Build Concepts/UsageTestPMConcept7.html: TestOpus5.5PmConcept.html with the redesigned Usage page (review copy).

Usage:
  python3 Concepts/usage-redesign/tools/build_usage.py          # build and write Concepts/UsageTestPMConcept7.html
  python3 Concepts/usage-redesign/tools/build_usage.py --check  # rebuild in memory and verify the written file and guards

The input is opus-5.5 build.build_text() (the exact bytes of TestOpus5.5PmConcept.html, base pin enforced there), so
this review copy and a later publish through build.py (Proposal B) apply the same layer to the same text. The layer
itself is tools/usage_layer.py. The output is generated: never hand-edit it.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
PKG = TOOLS.parent
CONCEPTS = PKG.parent
OPUS_TOOLS = CONCEPTS / 'onboarding' / 'opus-5.5' / 'tools'
sys.path.insert(0, str(OPUS_TOOLS))
sys.path.insert(0, str(TOOLS))

import build  # noqa: E402  (opus-5.5 tools/build.py)
import usage_layer  # noqa: E402

TARGET = CONCEPTS / 'UsageTestPMConcept7.html'
INPUT_FILE = CONCEPTS / 'Onboarding concepts' / 'TestOpus5.5PmConcept.html'
OLD_TITLE = '<title>TestOpus5.5 · Puppet Master</title>'
NEW_TITLE = '<title>UsageTest PM7 · Puppet Master</title>'
HEADER = ('<!-- UsageTestPMConcept7: TestOpus5.5PmConcept.html with the redesigned Usage page. Generated by '
          'Concepts/usage-redesign/tools/build_usage.py from Concepts/usage-redesign/src; never hand-edit. -->\n')
REMOVED = ['id="pm7UsageApp"', 'id="pm7uBoard"', 'pm7-t24-usage-readability-and-fit', 'pm7-t31-usage-final',
           'PM7 SECTION 15/32: usage-prism-js']
KEPT = ['window.PM7_CONTEXT =', '<script id="pm6-js-usage">', '.pm7-statusbar', '<style id="pm7-t32-final">',
        '<style id="pm7-t29-usage-final">', '<style id="pm-usage-ctx-css">', '<style id="pm-usage-css">',
        '<script id="pm-usage-js">', 'id="pmuApp"', '[data-theme="retro-light"]{--accent-lime:#2f7a3d']
MARKERS = [usage_layer.BODY_START, usage_layer.BODY_END,
           '<!-- O55:CSS:START -->', '<!-- O55:CSS:END -->', '<!-- O55:BODY:START -->', '<!-- O55:BODY:END -->']


def build_page() -> tuple[str, dict, bool]:
    base = build.build_text()
    input_current = INPUT_FILE.exists() and INPUT_FILE.read_bytes() == base.encode('utf-8')
    text, notes = usage_layer.apply(base, build.need)
    text = build.replace_once(text, OLD_TITLE, NEW_TITLE, 'usage test title')
    return HEADER + text, notes, input_current


def problems_for(text: str) -> list[str]:
    problems = usage_layer.lint() + usage_layer.syntax_check(text) + build.syntax_check(text)
    for marker in MARKERS:
        if text.count(marker) != 1:
            problems.append(f'marker {marker} appears {text.count(marker)} times')
    for removed in REMOVED:
        if removed in text:
            problems.append(f'removed reference still present: {removed}')
    for kept in KEPT:
        if kept not in text:
            problems.append(f'kept reference missing: {kept}')
    if text.count('<title>') != 1 or NEW_TITLE not in text:
        problems.append('title is not exactly one UsageTest PM7 title')
    return problems


def report(text: str, notes: dict) -> dict:
    data = text.encode('utf-8')
    rules = {k: {'kept': v['kept_rules'], 'rewritten': v['rewritten_rules'], 'dropped': v['dropped_rules']}
             for k, v in notes.items() if isinstance(v, dict) and 'kept_rules' in v}
    return {'output': str(TARGET.relative_to(CONCEPTS.parent)), 'bytes': len(data),
            'sha256': hashlib.sha256(data).hexdigest()[:16], 'input_bytes': notes.get('bytes_in'),
            'rules': rules, 'context_module': notes.get('context module'), 'band': notes.get('band'),
            'dropped_whole': notes.get('dropped whole'), 'nier_selector_patches': notes.get('nier selector patches'),
            'roster': notes.get('roster'), 'app_patches': notes.get('app patches')}


def main() -> int:
    check = '--check' in sys.argv
    try:
        text, notes, input_current = build_page()
    except build.BuildError as exc:
        print(f'BUILD FAILED: {exc}', file=sys.stderr)
        return 2
    problems = problems_for(text)
    if not input_current:
        message = 'Concepts/Onboarding concepts/TestOpus5.5PmConcept.html differs from a fresh opus-5.5 build (run its build.py)'
        if check:
            problems.append(message)
        else:
            print('WARNING:', message, file=sys.stderr)
    if check:
        if not TARGET.exists():
            problems.append('Concepts/UsageTestPMConcept7.html is missing; run build_usage.py')
        elif TARGET.read_bytes() != text.encode('utf-8'):
            problems.append('Concepts/UsageTestPMConcept7.html is stale or hand-edited; run build_usage.py')
        for p in problems:
            print('CHECK:', p)
        print(json.dumps(report(text, notes)))
        print('check', 'ok' if not problems else f'failed ({len(problems)})')
        return 0 if not problems else 1
    if problems:
        for p in problems:
            print('LINT:', p)
        return 1
    TARGET.write_text(text, encoding='utf-8')
    print(json.dumps(report(text, notes)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
