#!/usr/bin/env python3
"""Build the Usage page: the review copy Concepts/UsageTestPMConcept7.html while it exists, opus-5.5 build.py afterwards.

Usage:
  python3 Concepts/usage-redesign/tools/build_usage.py              # review mode: write Concepts/UsageTestPMConcept7.html
                                                                    # published mode: build.py --out <tmp>/usage-pm7/PMConcept7.html
  python3 Concepts/usage-redesign/tools/build_usage.py --out PATH   # published mode only: build.py --out PATH
  python3 Concepts/usage-redesign/tools/build_usage.py --check      # review mode: rebuild in memory, verify the review copy
                                                                    # and guards; published mode: build.py --check

Two modes, chosen by whether the review copy exists (usage_boot.mjs chooses the same way):
- Review mode (until the publish): the input is opus-5.5 build.build_text(usage=False), the exact bytes of
  TestOpus5.5PmConcept.html before the publish (base pin enforced there). build.py applies the same layer to the same
  text at its step 2b, so the review copy's Usage band equals the published page's. --check accepts the committed
  TestOpus5.5PmConcept.html either without Usage (before the publish) or with it (a working tree where
  build.py --publish-pm7 ran), as long as it equals a fresh build of that kind.
- Published mode (the review copy is gone: Jared, 2026-10-09, "the UsageTestPMConcept7.html will go away"): a thin
  wrapper around opus-5.5 build.py, the one publish path. It never writes the review copy again.
The layer itself is tools/usage_layer.py. Every output is generated: never hand-edit it.
"""
from __future__ import annotations

import hashlib
import json
import subprocess
import sys
import tempfile
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
PKG = TOOLS.parent
CONCEPTS = PKG.parent
OPUS_TOOLS = CONCEPTS / 'onboarding' / 'opus-5.5' / 'tools'
sys.path.insert(0, str(OPUS_TOOLS))
sys.path.insert(0, str(TOOLS))

import build  # noqa: E402  (opus-5.5 tools/build.py)
import usage_layer  # noqa: E402

TARGET = CONCEPTS / 'UsageTestPMConcept7.html'
INPUT_FILE = CONCEPTS / 'Onboarding concepts' / 'TestOpus5.5PmConcept.html'
OLD_TITLE = '<title>TestOpus5.5 · Puppet Master</title>'
NEW_TITLE = '<title>UsageTest PM7 · Puppet Master</title>'
HEADER = ('<!-- UsageTestPMConcept7: TestOpus5.5PmConcept.html with the redesigned Usage page. Generated by '
          'Concepts/usage-redesign/tools/build_usage.py from Concepts/usage-redesign/src; never hand-edit. -->\n')
REMOVED = usage_layer.REMOVED
KEPT = usage_layer.KEPT
MARKERS = [usage_layer.BODY_START, usage_layer.BODY_END,
           '<!-- O55:CSS:START -->', '<!-- O55:CSS:END -->', '<!-- O55:BODY:START -->', '<!-- O55:BODY:END -->']


def build_page() -> tuple[str, dict, bool]:
    # build.py applies the usage layer itself (step 2b); the review copy starts from the build without it and applies
    # the same layer here, so until the publish its input is still the committed TestOpus5.5PmConcept.html
    base = build.build_text(usage=False)
    input_current = INPUT_FILE.exists() and INPUT_FILE.read_bytes() == base.encode('utf-8')
    if not input_current and INPUT_FILE.exists() and usage_layer.BODY_START.encode('utf-8') in INPUT_FILE.read_bytes():
        # a working tree where build.py --publish-pm7 ran: the published page carries Usage, and is current when it
        # equals a fresh full build (build.py --check compares PMConcept7.html with the same bytes)
        input_current = INPUT_FILE.read_bytes() == build.build_text().encode('utf-8')
    text, notes = usage_layer.apply(base, build.need)
    text = build.replace_once(text, OLD_TITLE, NEW_TITLE, 'usage test title')
    return HEADER + text, notes, input_current


def problems_for(text: str) -> list[str]:
    problems = usage_layer.lint() + usage_layer.syntax_check(text) + build.syntax_check(text)
    for marker in MARKERS:
        if text.count(marker) != 1:
            problems.append(f'marker {marker} appears {text.count(marker)} times')
    for removed in REMOVED:
        if removed in text:
            problems.append(f'removed reference still present: {removed}')
    for kept in KEPT:
        if kept not in text:
            problems.append(f'kept reference missing: {kept}')
    if text.count('<title>') != 1 or NEW_TITLE not in text:
        problems.append('title is not exactly one UsageTest PM7 title')
    return problems


def report(text: str, notes: dict) -> dict:
    data = text.encode('utf-8')
    rules = {k: {'kept': v['kept_rules'], 'rewritten': v['rewritten_rules'], 'dropped': v['dropped_rules']}
             for k, v in notes.items() if isinstance(v, dict) and 'kept_rules' in v}
    return {'output': str(TARGET.relative_to(CONCEPTS.parent)), 'bytes': len(data),
            'sha256': hashlib.sha256(data).hexdigest()[:16], 'input_bytes': notes.get('bytes_in'),
            'rules': rules, 'context_module': notes.get('context module'), 'band': notes.get('band'),
            'dropped_whole': notes.get('dropped whole'), 'nier_selector_patches': notes.get('nier selector patches'),
            'roster': notes.get('roster'), 'app_patches': notes.get('app patches')}


def published_mode() -> int:
    """The review copy is gone: delegate to opus-5.5 build.py (--check, or a private --out build). Never write the review
    copy or either published page from here."""
    build_py = OPUS_TOOLS / 'build.py'
    if '--check' in sys.argv:
        args = ['--check']
    else:
        out = Path(tempfile.gettempdir()) / 'usage-pm7' / 'PMConcept7.html'
        if '--out' in sys.argv:
            i = sys.argv.index('--out')
            if i + 1 >= len(sys.argv):
                print('--out needs a path', file=sys.stderr)
                return 2
            out = Path(sys.argv[i + 1]).expanduser()
        out.resolve().parent.mkdir(parents=True, exist_ok=True)
        args = ['--out', str(out)]
    print(f'build_usage: {TARGET.name} is retired (published mode); running opus-5.5 build.py {" ".join(args)}',
          file=sys.stderr)
    return subprocess.run([sys.executable, str(build_py), *args]).returncode


def main() -> int:
    if not TARGET.exists():
        return published_mode()
    if '--out' in sys.argv:
        print('--out is for published mode (after the review copy is retired); in review mode use opus-5.5 '
              'build.py --out PATH for a private build of the publish candidate', file=sys.stderr)
        return 2
    check = '--check' in sys.argv
    try:
        text, notes, input_current = build_page()
    except build.BuildError as exc:
        print(f'BUILD FAILED: {exc}', file=sys.stderr)
        return 2
    problems = problems_for(text)
    if not input_current:
        message = ('Concepts/Onboarding concepts/TestOpus5.5PmConcept.html differs from a fresh opus-5.5 build, with or '
                   'without Usage: run opus-5.5 build.py --publish-pm7, or restore both published pages with git checkout')
        if check:
            problems.append(message)
        else:
            print('WARNING:', message, file=sys.stderr)
    if check:
        if TARGET.read_bytes() != text.encode('utf-8'):
            problems.append('Concepts/UsageTestPMConcept7.html is stale or hand-edited; run build_usage.py')
        for p in problems:
            print('CHECK:', p)
        print(json.dumps(report(text, notes)))
        print('check', 'ok' if not problems else f'failed ({len(problems)})')
        return 0 if not problems else 1
    if problems:
        for p in problems:
            print('LINT:', p)
        return 1
    TARGET.write_text(text, encoding='utf-8')
    print(json.dumps(report(text, notes)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
