#!/usr/bin/env python3
"""Generate _shared2/pm2-inventory.js from the canonical Plans/settings_inventory.json.

Read-only with respect to Plans. Emits the full 828-record registry verbatim
(ids, labels, descriptions, types, options, defaults, tiers, search terms,
badges, related features) plus the 12-category / 36-subgroup taxonomy.

The legacy `scope` metadata is carried through as `legacyScope` for candidate
impact reporting only — concept UIs project every record onto the current
Project and never expose scope controls (packet 04_PROJECT_ONLY_SETTINGS).

Usage: python3 tools/gen-inventory.py   (from the fable folder root)
"""
from __future__ import annotations
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
FABLE = HERE.parent
REPO = FABLE.parents[2]
SRC = REPO / "Plans" / "settings_inventory.json"
OUT = FABLE / "_shared2" / "pm2-inventory.js"


def main() -> None:
    d = json.loads(SRC.read_text())
    cats = []
    for c in d["categories"]:
        cats.append({
            "id": c["id"], "title": c["title"], "icon": c.get("icon", "gear"),
            "desc": c.get("description", ""),
            "subgroups": [
                {"id": s["id"], "title": s["title"], "desc": s.get("description", "")}
                for s in c["subgroups"]
            ],
        })
    settings = []
    for s in d["settings"]:
        cat, sub = s["id"].split(".")[0:2]
        rec = {
            "id": s["id"], "cat": cat, "sub": sub,
            "label": s["label"], "desc": s["desc"], "type": s["type"],
            "tier": s["tier"], "search": s.get("search", []),
            "legacyScope": s.get("scope", []),
        }
        for k in ("options", "default", "recommended", "badges", "curated", "related_features"):
            if k in s:
                rec[k] = s[k]
        settings.append(rec)
    payload = {
        "schema": "pm2.inventory.v1",
        "source": "Plans/settings_inventory.json",
        "sourceSchema": d.get("schema_id"),
        "sourceVersion": d.get("schema_version"),
        "generatedAt": d.get("generated_at_utc"),
        "settingsCount": len(settings),
        "categories": cats,
        "settings": settings,
    }
    js = (
        "// GENERATED by tools/gen-inventory.py — do not hand-edit.\n"
        "// Full canonical Settings inventory (828 records, 12 categories) for concepts 05-11.\n"
        "// legacyScope is candidate-impact metadata only; UIs are current-Project-only.\n"
        "window.PM2_INVENTORY = " + json.dumps(payload, separators=(",", ":")) + ";\n"
    )
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(js)
    print(f"wrote {OUT} ({len(js)} bytes, {len(settings)} settings, {len(cats)} categories)")


if __name__ == "__main__":
    main()
