import pathlib,json,datetime,hashlib,sys
B=pathlib.Path('/home/sittingmongoose/PM-Experiments/er10-20261007-5a126dd5')
case,arm,role=sys.argv[1:4];version=sys.argv[4] if len(sys.argv)>4 else "v1";J=B/'jobs'/case/arm/(role+'-'+version);P=B/'state/integrated-methods.json';s=json.loads(P.read_text());status=json.loads((J/'terminal-task-status.json').read_text())['structuredContent'];run=json.loads((J/'terminal-t3-observation.json').read_text())['structuredContent']['recentRuns'][0]
assert not status['hasPendingChildRuns'];assert status['status'] in ['completed','failed','cancelled','interrupted']
files={}
for p in [J/'artifact.md',J/'source-map.json',J/'semantic.json',J/'preservation_check.md',*sorted(J.glob('semantic-*.json')),*sorted(J.glob('projection-*.md')),*sorted((J/'sources').rglob('*'))]:
 if p.is_file():
  b=p.read_bytes();files[str(p)]={'sha256':hashlib.sha256(b).hexdigest(),'bytes':len(b)};p.chmod(0o444)
tri={'record_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'scope':'mechanical delivery triage only, not SourcePASS','files':files,'t3_run':run,'descendants_quiet':True,'settled':True,'source_quality':None}
rp=J/'native-receipts.jsonl'
if rp.exists():
 raw=[json.loads(x) for x in rp.read_text().splitlines()];rs=[x.get('response',x) for x in raw];tri['actual_native_responses']=rs;tri['native_identity']=rs[-1]['goal']['threadId'];tri['native_terminal']=rs[-1]['goal']['status'];tri['native_terminal_unix_seconds']=rs[-1]['goal']['updatedAt'];tri['same_identity']=all(x['goal']['threadId']==rs[0]['goal']['threadId'] for x in rs);tri['raw_response_count']=len(rs);tri['native_goal_aggregate_tokens']=rs[-1]['goal']['tokensUsed'];tri['native_elapsed_seconds']=rs[-1]['goal']['timeUsedSeconds'];tri['native_start_unix_seconds']=rs[0]['goal']['createdAt'];tri['native_active_observed']=rs[1]['goal']['status']=='active'
else:
 idx=json.loads((J/'terminal-passive-export-index.json').read_text());entry=next(e for e in idx['entries'] if e['stage']==case+'/'+arm+'/'+role+'-'+version);d=json.loads(pathlib.Path(entry['path']).read_text());obs=[o for o in d['observations'] if o['source']['type']=='t3_native_goal_projection'];row=(s['cases'][case]['arms'] if version=='v1' else s['cases'][case]['versions'][version]['arms'])[arm]['stages'][role];expected=row.get('native_goal_identity');matches=[(o,b) for o in obs for b in d['binding'] if b['id']==o['source']['record_id'] and (b.get('nativeThreadRef')or{}).get('nativeId')==expected];tri['passive_terminal_export']=entry;tri['native_state_projections']=[o['native_response'] for o in obs];tri['native_binding']=d['binding'];tri['raw_response_capture']=d['capture'];tri['native_identity']=expected if matches else None;tri['native_terminal']=matches[0][0]['native_response'].get('status') if matches else None;tri['same_identity']=bool(matches);tri['native_createdAt']=None;tri['native_carrier']='actual projection NOT raw response';tri['native_timestamp_limit']='createdAt/update epoch absent from selected Codex projection; exact observation time kept';tri['native_goal_aggregate_tokens']=matches[0][0]['native_response'].get('tokensUsed') if matches else None;tri['native_elapsed_seconds']=matches[0][0]['native_response'].get('timeUsedSeconds') if matches else None
tri['stage_envelope']=json.loads((J/'dispatch-config.json').read_text());tri['t3_delivery_in_prefrozen_deadline']=bool(run.get('completedAt')) and datetime.datetime.fromisoformat(run['completedAt'].replace('Z','+00:00'))<=datetime.datetime.fromisoformat(tri['stage_envelope']['prospective_stage_deadline'])
# Earlier first-preparation boundary, if explicitly linked, never replaces actual dispatched config.
linked_row=(s['cases'][case]['arms'] if version=='v1' else s['cases'][case]['versions'][version]['arms'])[arm]['stages'][role]
if linked_row.get('effective_stage_deadline'):
 tri['effective_stage_deadline']=linked_row['effective_stage_deadline'];tri['earlier_stage_deadline_annotation']=linked_row.get('earlier_stage_deadline_annotation');tri['t3_delivery_in_actual_dispatched_deadline']=tri['t3_delivery_in_prefrozen_deadline'];tri['t3_delivery_in_prefrozen_deadline']=bool(run.get('completedAt')) and datetime.datetime.fromisoformat(run['completedAt'].replace('Z','+00:00'))<=datetime.datetime.fromisoformat(linked_row['effective_stage_deadline'])
tri['distinct_counters']={k:None for k in ['input','cached_input','generated_output','reasoning','billing']};(J/'frozen-delivery.json').write_text(json.dumps(tri,indent=2)+'\n')
row=(s['cases'][case]['arms'] if version=='v1' else s['cases'][case]['versions'][version]['arms'])[arm]['stages'][role];row.update(status);row['delivery_freeze']=str(J/'frozen-delivery.json');row['actual_requestedAt']=run['requestedAt'];row['actual_t3_startedAt']=run['startedAt'];row['t3_completedAt']=run['completedAt'];row['native_goal_identity']=tri.get('native_identity');row['native_terminal']=tri.get('native_terminal');s['tasks'][row['taskId']]=row;(s['cases'][case]['arms'] if version=='v1' else s['cases'][case]['versions'][version]['arms'])[arm]['status']=role+'_frozen';s['updated_at']=tri['record_at'];P.write_text(json.dumps(s,indent=2)+'\n')
with (B/'state/integrated-methods-dispatches.jsonl').open('a') as f:f.write(json.dumps({'type':'stage_terminal_freeze','linked_taskId':row['taskId'],'path':str(J/'frozen-delivery.json'),'record_at':tri['record_at'],'t3_completedAt':run['completedAt'],'native_terminal':tri.get('native_terminal'),'t3_delivery_in_deadline':tri['t3_delivery_in_prefrozen_deadline']})+'\n')
print(json.dumps({'stage':case+'/'+arm+'/'+role,'files':len(files),'native_terminal':tri.get('native_terminal'),'native_same_identity':tri.get('same_identity'),'t3_delivery_in_deadline':tri['t3_delivery_in_prefrozen_deadline']}))
