import pathlib,json,datetime,sys,os,re
B=pathlib.Path('/home/sittingmongoose/PM-Experiments/er10-20261007-5a126dd5');case,arm=sys.argv[1:3];version=sys.argv[3] if len(sys.argv)>3 else 'v1';card=json.loads((B/'cases'/case/('execution-'+version+'.json')).read_text());final_role=card.get('final_role',{}).get(arm,'reviser');J=B/'reviews/integrated-methods'/case/arm/('review-'+version);J.mkdir(parents=True,exist_ok=True);(J/'sources').mkdir(exist_ok=True);assert not (J/'dispatch-response.json').exists();s=json.loads((B/'state/integrated-methods.json').read_text());view=s['cases'][case] if version=='v1' else s['cases'][case]['versions'][version];assert view.get('pair_freeze');gate=json.loads(pathlib.Path(view['pair_freeze']).read_text());assert gate['both_finals_frozen'] and gate['all_tasks_quiet']
now=datetime.datetime.now(datetime.timezone.utc);cfg={'target':{'providerInstanceId':'codex_gmail','driverKind':'codex','model':'gpt-6.1-sol','options':[{'id':'reasoningEffort','value':'xhigh'},{'id':'serviceTier','value':'priority'}]},'mode':'async','role':'review','runtimeMode':'full-access','interactionMode':'default','clientRequestId':'er10-'+case+'-'+arm+'-independent-review-'+version,'record_at':now.isoformat(),'review_max_seconds':1800,'prospective_review_deadline':(now+datetime.timedelta(seconds=1800)).isoformat(),'native_goal_required':False,'carrier':'prospective_review_v2','pair_gate':view['pair_freeze']};(J/'dispatch-config.json').write_text(json.dumps(cfg,indent=2)+'\n')
template=(B/'reviews/integrated-methods/I-METHOD-01/control/review-v1/task.txt').read_text();prompt=template.replace('I-METHOD-01',case).replace('/control/','/'+arm+'/').replace('all six tasks','all owned candidate stage tasks').replace('P1-P6','in-scope plan/owner decisions');prompt=re.sub(r'fixed deadline [^,]+, finish', 'fixed deadline '+cfg['prospective_review_deadline']+', finish',prompt)
prompt=prompt.replace('/research-v1/', '/research-'+version+'/').replace('/critic-v1/', '/critic-'+version+'/').replace('/reviser-v1/', '/'+final_role+'-'+version+'/').replace('/review-v1/', '/review-'+version+'/')
if final_role=='critic-finalizer':prompt=prompt.replace('/critic-'+version+'/', '/critic-finalizer-'+version+'/')
prompt+='\nVisible artifact/procedure structure may reveal method differences: record that blinding limit; no other-arm scores, costs, speed targets or parent analysis supplied. Entire final full scope must be assessed for full PASS; localized decisive failure leaves remaining scope explicitly unassessed.\n'
src=B/'cases'/case/'source'
if src.is_dir():prompt+='\nOriginal frozen plan source copies (ALL admitted comparison inputs, original bytes, not scientific discoveries): '+str(src)+'; read every in-scope copied unit/context and preserve Rust+Slint/product/negative/proof boundaries, absent adjacent owners as limits not assumed defects.\n'
if case=='I-METHOD-04' and arm=='treatment':prompt+='\nAssess entire final authoritative semantic.json and complete rendered artifact.md plus preservation_check.md, all authored record/document/unknown fields, full governing conditions, optional leads/views and exact semantic input. Concise decision view alone is NOT full assessment. Compare researcher semantic set and critique for preservation. Renderer structural exit is not source or scope proof.\n'
(J/'task.txt').write_text(prompt)
paths=[B/'cases'/case/'brief.md',B/'cases'/case/'plan.md',B/'jobs'/case/arm/(final_role+'-'+version)/'artifact.md',B/'jobs'/case/arm/(final_role+'-'+version)/'source-map.json']
for p in paths:assert os.access(p,os.R_OK)
(J/'input-map.json').write_text(json.dumps({'original_brief':str(paths[0]),'original_plan':str(paths[1]),'final_artifact':str(paths[2]),'final_source_map':str(paths[3]),'own_outputs':str(J),'scope':'full original declared scope and own-arm frozen preservation predecessors; no other arm/review/parentanalysis'},indent=2)+'\n');print(json.dumps(cfg))
