/* B16: execute the shipped ToDoController against a deterministic test work owner.
 * This is controlled owner-contract testing, not evidence of native execution. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),c={console};c.window=c;c.PM56_DATA={};c.PM56_EXT={slot(){},action(){},chainAction(){}};
vm.createContext(c);for(const name of ['command-transaction','todos'])vm.runInContext(fs.readFileSync(path.join(root,name+'.js'),'utf8'),c);
const T=c.PM56_TODOS,TX=c.PM56_TX,clone=x=>JSON.parse(JSON.stringify(x)),equal=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
let assertions=0,seq=0;const cases=[],ok=(v,n)=>{assert.ok(v,n);assertions++;};
const fixtures=new Map();
T.registerOutcomeOwner('test16',(ref,t,receipt,b)=>{const f=fixtures.get(ref),p=f?.proofs.get(receipt);return {ok:!!p&&p.binding===b.binding_id&&p.source===f.source&&p.output===f.source.toUpperCase()&&p.expected===t.expected_outcome};},{
 admit:(ref,t,b,cause)=>({ok:fixtures.has(ref)&&b.expected_outcome===t.expected_outcome&&b.work_id===b.binding_id&&cause===ref+':admit'}),
 fence:(ref,t)=>({run_id:t.run_id,run_epoch:fixtures.get(ref)?.epoch}),
 cancel:(ref,b,receipt)=>({ok:fixtures.get(ref)?.cancels.has(receipt+':'+b.binding_id)}),
 retry:(ref,b,receipt)=>({ok:fixtures.get(ref)?.retries.has(receipt+':'+b.binding_id)}),
 condition:(ref,t,reason,state)=>({ok:state==='blocked'?fixtures.get(ref)?.block===reason:fixtures.get(ref)?.block===null}),
 wait:(ref,t,w)=>({ok:equal(fixtures.get(ref)?.wait,w)}),
 open:(ref,b)=>({ok:fixtures.has(ref),binding:clone(b),source:fixtures.get(ref)?.source})
});
function seed(){const thread='c16-'+(++seq),f={epoch:1,source:'value-'+seq,proofs:new Map(),cancels:new Set(),retries:new Set(),block:null,wait:null};fixtures.set(thread,f);
 const out=T.materializeForWork({run_id:thread,thread_id:thread,project_id:'pm',epoch:1,owner:'test16',ref:thread,steps:[{id:'p',title:'Outputs'},{id:'a',title:'First displayed',parent:'p',outcome:'Uppercase source'},{id:'b',title:'Later displayed',parent:'p',outcome:'Uppercase source'},{id:'z',title:'Dependent validation',deps:['a','b'],outcome:'Uppercase source'}]});ok(out.ok,'materialization');return {thread,f,ids:out.ids,a:out.ids[1],b:out.ids[2],p:out.ids[0],z:out.ids[3]};}
const item=(x,id)=>T.get(x.thread).find(t=>t.todo_id===id);
function admission(x,id){const t=item(x,id),n=T.bindingsFor(x.thread,id).length+1,b={binding_id:x.thread+':'+id+':'+n,todo_id:id,work_id:x.thread+':'+id+':'+n,attempt_id:'attempt-'+n,work_kind:'artifact_generation',expected_outcome:t.expected_outcome};return {...T.capture(x.thread,id),to_status:'in_progress',cause_kind:'work_admitted',cause_ref:x.thread+':admit',work_binding:b.binding_id,binding:b};}
function start(x,id){const e=admission(x,id),r=T.applyTransition(x.thread,e);ok(r.ok,'admitted '+id+': '+JSON.stringify(r));return r;}
function outcome(x,id,make=true){const b=T.bindingsFor(x.thread,id).find(b=>b.state==='running'||b.state==='recovery_required'),ref=x.thread+':proof:'+b.binding_id;if(make)x.f.proofs.set(ref,{binding:b.binding_id,source:x.f.source,output:x.f.source.toUpperCase(),expected:item(x,id).expected_outcome});return {...T.capture(x.thread,id),work_binding:b.binding_id,to_status:'completed',cause_kind:'outcome_satisfied',cause_ref:ref};}
function test(n,fn){const before=assertions;fn();cases.push({name:n,assertions:assertions-before,status:'pass'});}
test('concurrent-out-of-order-parent-rollup',()=>{const x=seed();start(x,x.b);start(x,x.a);ok(item(x,x.p).status==='in_progress'&&item(x,x.z).status==='pending','parent running; dependency wait pending');ok(T.get(x.thread).filter(t=>t.status==='in_progress').length===3,'two leaves plus rollup');ok(T.applyTransition(x.thread,outcome(x,x.b)).ok,'later leaf first');ok(item(x,x.a).status==='in_progress','other leaf still running');ok(T.applyTransition(x.thread,outcome(x,x.a)).ok,'first leaf finishes');ok(item(x,x.p).status==='completed'&&T.runnable(x.thread,x.z),'derived parent and dependencies ready');ok(!T.bindingsFor(x.thread,x.p).length,'parent has no work');start(x,x.z);ok(T.applyTransition(x.thread,outcome(x,x.z)).ok,'validation own result');ok(T.outcomeSummary(x.thread,x.ids).ok,'all required leaves have accepted proofs');for(const t of T.get(x.thread))for(const tr of t.transitions)ok(tr.committed_revision===tr.expected_revision+1,'per-item revision receipt');});
test('tool-success-and-bulk-assertion-refused',()=>{const x=seed();start(x,x.a);start(x,x.b);const a=outcome(x,x.a),b=outcome(x,x.b,false),before=clone(T.snapshot(x.thread));ok(!T.applyTransitions(x.thread,[a,b]).ok,'unsupported bulk refused');ok(equal(before,T.snapshot(x.thread)),'bulk failure has zero writes');ok(!T.applyTransition(x.thread,{...outcome(x,x.b,false),cause_kind:'tool_succeeded'}).ok,'tool success not outcome');ok(item(x,x.a).status==='in_progress','neither leaf completed');});
test('currentness-exact-all-keys',()=>{const x=seed();start(x,x.a);const e=outcome(x,x.a);for(const [key,bad] of [['project_id','other'],['thread_id','other'],['expected_list_revision',999],['expected_revision',999],['plan_id','wrong'],['plan_version',99],['plan_hash','wrong'],['run_id','other'],['run_epoch',0],['work_binding','wrong']]){const before=clone(T.get(x.thread));ok(!T.applyTransition(x.thread,{...e,[key]:bad}).ok,'reject '+key);ok(equal(before,T.get(x.thread)),'no graph write '+key);}ok(T.rejectedEvents(x.thread).length>=9,'stale rejected evidence retained');});
test('receipt-replay-is-idempotent',()=>{const x=seed(),e=admission(x,x.a);ok(T.applyTransition(x.thread,e).ok,'first receipt');const before=clone(T.snapshot(x.thread));ok(T.applyTransition(x.thread,e).replayed,'same receipt replay');ok(equal(before,T.snapshot(x.thread)),'replay zero effects');const tr=item(x,x.a).transitions[0];ok(!T.applyTransition(x.thread,{...e,transition_id:tr.transition_id,cause_ref:'other'}).ok,'conflicting receipt refused');});
test('provider-proposal-preserves-omissions',()=>{const x=seed();start(x,x.a);const beforeBinding=clone(T.bindings(x.thread));ok(T.propose(x.thread,{items:[{todo_id:x.b,title:'Reworded display only'}]},T.revisionOf(x.thread)).ok,'proposal validated');ok(T.get(x.thread).length===4&&item(x,x.a).status==='in_progress','omitted work retained');ok(equal(beforeBinding,T.bindings(x.thread)),'binding exact');for(const fields of [{status:'completed'},{verification_state:'passed'},{source_group_label:'Plan'},{unknown_authority:true}]){const before=clone(T.snapshot(x.thread));ok(!T.propose(x.thread,{items:[{todo_id:x.a,...fields}]},T.revisionOf(x.thread)).ok,'unsupported field/status refused');ok(equal(before,T.snapshot(x.thread)),'proposal refusal atomic');}});
test('restructure-retain-rebind-old-child-fencing',()=>{const x=seed();start(x,x.a);start(x,x.b);const oldEvent=outcome(x,x.a),bindings=clone(T.bindings(x.thread)),candidate=clone(T.get(x.thread)),newid=x.a+'-rebound';candidate.splice(candidate.findIndex(t=>t.todo_id===x.a),1);candidate.find(t=>t.todo_id===x.z).depends_on=[newid,x.b];candidate.push({todo_id:newid,thread_id:x.thread,project_id:'pm',parent_todo_id:x.p,depends_on:[],title:'Same work, clearer boundary',expected_outcome:'Uppercase source'});const out=T.replaceThreadList(x.thread,{items:candidate},{mode:'restructure',expected_revision:T.revisionOf(x.thread),rebind:{[x.a]:newid}});ok(out.ok,JSON.stringify(out));ok(equal(bindings,T.bindings(x.thread)),'all binding bytes preserved');ok(T.bindingsFor(x.thread,newid)[0].todo_id===x.a,'admission identity preserved');const before=clone(T.get(x.thread));ok(!T.applyTransition(x.thread,oldEvent).ok,'removed child callback refused');ok(equal(before,T.get(x.thread)),'removed child cannot roll up');ok(T.applyTransition(x.thread,outcome(x,newid)).ok,'current rebound callback accepted');ok(T.openWork(x.thread,newid).work_id===bindings[0].work_id,'exact navigation');});
test('replacement-refusal-no-orphans',()=>{const x=seed();start(x,x.a);const candidate=clone(T.get(x.thread)).filter(t=>t.todo_id!==x.a);candidate.find(t=>t.todo_id===x.z).depends_on=[x.b];const before=clone(T.snapshot(x.thread));ok(!T.replaceThreadList(x.thread,{items:candidate},{mode:'restructure',expected_revision:T.revisionOf(x.thread)}).ok,'active work refuses removal');ok(equal(before,T.snapshot(x.thread)),'no partial graph/binding write');const b=T.bindingsFor(x.thread,x.a)[0];x.f.cancels.add('safe-stop:'+b.binding_id);ok(T.replaceThreadList(x.thread,{items:candidate},{mode:'restructure',expected_revision:T.revisionOf(x.thread),cancellations:{[b.binding_id]:'safe-stop'}}).ok,'safe stop receipted');ok(b.state==='cancelled'&&b.terminal_result_ref==='safe-stop','cancelled binding retained in history');});
test('pause-fence-not-admitted-identity',()=>{const x=seed();start(x,x.a);const old=outcome(x,x.a),before=clone(T.bindings(x.thread));x.f.epoch+=2;ok(!T.applyTransition(x.thread,old).ok,'pre-pause callback rejected');ok(equal(before,T.bindings(x.thread)),'binding not reminted');ok(T.applyTransition(x.thread,outcome(x,x.a)).ok,'resumed current callback accepted');ok(T.bindings(x.thread).length===1,'one work admission only');});
test('skip-reopen-retry-closed-causes',()=>{const x=seed();ok(!T.applyTransition(x.thread,{...T.capture(x.thread,x.a),to_status:'skipped',cause_kind:'explicit_skip',cause_ref:'skip'}).ok,'skip needs accepted reason');ok(T.applyTransition(x.thread,{...T.capture(x.thread,x.a),to_status:'skipped',cause_kind:'explicit_skip',cause_ref:'skip',skip_disposition:{user_approved:true,reason:'User explicitly removes requirement'}}).ok,'explicit skip');ok(T.applyTransition(x.thread,{...T.capture(x.thread,x.a),to_status:'pending',cause_kind:'reopen',cause_ref:'reopen',user_approved:true}).ok,'explicit reopen');const b=start(x,x.a).binding;x.f.retries.add('failed:'+b.binding_id);ok(T.applyTransition(x.thread,{...T.capture(x.thread,x.a),to_status:'pending',cause_kind:'retry',cause_ref:'failed',work_binding:b.binding_id}).ok,'owner-receipted retry');ok(b.state==='failed','failed attempt retained');start(x,x.a);ok(T.bindingsFor(x.thread,x.a).length===2,'retry creates next attempt, not overwritten identity');});
test('owner-waits-not-blockers-or-status-transitions',()=>{const x=seed();start(x,x.a);const before=item(x,x.a).transitions.length,binding=T.bindingsFor(x.thread,x.a)[0];for(const kind of ['quota','window','recovery_required']){x.f.wait={kind,reason:'Owner condition'};ok(T.setOwnerWait(x.thread,x.a,x.f.wait).ok,'owner wait '+kind);ok(item(x,x.a).status==='in_progress'&&item(x,x.a).transitions.length===before,'wait does not change status');}ok(binding.state==='recovery_required','recovery condition retained');x.f.wait=null;ok(T.setOwnerWait(x.thread,x.a,null).ok,'owner clears wait');ok(item(x,x.a).status==='in_progress','clear does not complete or reset');});
test('failed-outer-transaction-preserves-all-state',()=>{const x=seed(),before=clone(T.snapshot(x.thread));const out=TX.run(()=>{const a=T.applyTransition(x.thread,admission(x,x.a));if(!a.ok)return a;return {ok:false,error:'fault_after_admission'};});ok(!out.ok&&out.rollback.complete,'rollback complete');ok(equal(before,T.snapshot(x.thread)),'bindings, target, graph, receipts all restored');});

test('rebind-keeps-all-prior-attempt-identities',()=>{const x=seed(),first=start(x,x.a).binding;x.f.retries.add('failed:'+first.binding_id);ok(T.applyTransition(x.thread,{...T.capture(x.thread,x.a),to_status:'pending',cause_kind:'retry',cause_ref:'failed',work_binding:first.binding_id}).ok,'retry disposition');start(x,x.a);const bindings=clone(T.bindings(x.thread)),newid=x.a+'-after-retry',candidate=clone(T.get(x.thread)).filter(t=>t.todo_id!==x.a);candidate.find(t=>t.todo_id===x.z).depends_on=[newid,x.b];candidate.push({todo_id:newid,thread_id:x.thread,project_id:'pm',parent_todo_id:x.p,depends_on:[],title:'Retained retry history',expected_outcome:'Uppercase source'});const out=T.replaceThreadList(x.thread,{items:candidate},{mode:'restructure',expected_revision:T.revisionOf(x.thread),rebind:{[x.a]:newid}});ok(out.ok,'atomic rebind with prior and active attempt');ok(equal(bindings,T.bindings(x.thread)),'all exact historical/active bindings unchanged');ok(T.bindingsFor(x.thread,newid).length===2,'both attempts still addressable through current item');ok(T.applyTransition(x.thread,outcome(x,newid)).ok,'current active binding completes new target');});
console.log(JSON.stringify({suite:'b16-controller',status:'pass',assertions,cases,source_sha256:require('node:crypto').createHash('sha256').update(fs.readFileSync(path.join(root,'todos.js'))).digest('hex')},null,2));
