/* Actual application handlers. This driver is test-only, never a runtime module. */
window.B16_CASES=(()=>{
 const E=PM56_EXT,P=PM56_PLANS,T=PM56_TODOS,W=PM56_B16_WORK,G=PM56_GOAL,R=PM56_RUNTIME,D=PM56_DATA,S=PM56_SCHED,TX=PM56_TX;
 const C=()=>E.ctx(),clone=x=>JSON.parse(JSON.stringify(x)),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),act=(name,d={})=>E.run(name,{dataset:d},new Event('click'));
 function seed(flow='parallel'){act('b16-start',{flow});document.querySelector('[data-action="send"]').click();return W.get(W.snapshot().id);}
 function build(r,goal=false){return P.build({plan_id:r.planId,expected:P.admissionSnapshot(r.planId),execution_topology:goal?'goal_driven':'agent',paused:false});}
 function state(){G.get('query');return clone({plans:P.all(),runs:P.runs(),goals:R.goals,bound:R.boundGoals,todos:R.todos,schedules:S.list(),work:R.todoGraphWork,artifacts:D.artifacts,messages:C().thread.messages});}
 const cases={};
 cases.parallel_outputs=ck=>{const r=seed(),p=P.get(r.planId),source=D.artifacts.find(a=>a.id===r.source.id).content,md=P.markdown(r.planId),hash=P.hash(r.planId);ck('Ordinary Plan creates no Goal or To-Dos',!G.get()&&!T.get());ck('Explicit ordinary Build remains non-Goal',build(r).ok&&!G.get());
 ck('Actual shared materialization creates parent and three bounded leaves',T.get().length===4);ck('Both independent outputs admitted together',W.advance(r.id,p).admitted===2);const current=P.progress(p.plan_id);ck('Projection preserves concurrency',current.step_states.csv.state==='in_progress'&&current.step_states.summary.state==='in_progress');ck('Dependency wait is pending, not blocked',current.step_states.validate.state==='pending');
 ck('Later displayed summary computes first',W.advance(r.id,p).ok&&P.progress(p.plan_id).step_states.summary.state==='completed'&&P.progress(p.plan_id).step_states.csv.state==='in_progress');
 const report=P.executionReport(p.plan_id);ck('Execution report has actual scoped attempts and To-Dos',report.plan_run_id===p.approved.plan_run_id&&report.todo_refs.length===4&&report.attempts.length===2);ck('Source and Plan bytes immutable during execution',P.markdown(p.plan_id)===md&&P.hash(p.plan_id)===hash&&D.artifacts.find(a=>a.id===r.source.id).content===source);
 for(let i=0;i<3;i++)ck('Accepted source-bound work effect '+i,W.advance(r.id,p).ok);
 ck('Both files independently checked',W.inspect(r.id,p).complete&&JSON.parse(D.artifacts.find(a=>a.id===r.outputs.validate).content).checks.length===3);ck('Required leaf outcome evidence accepted',T.outcomeSummary(r.threadId,p.requiredTodoIds).ok);
 ck('Parent is derived without admitted work',T.bindingsFor(r.threadId,T.get()[0].todo_id).length===0&&T.get()[0].status==='completed');ck('All Plan leaf states reflect accepted outcomes',Object.values(P.progress(p.plan_id).step_states).every(s=>s.state==='completed'));ck('All final Plan and source bytes unchanged',P.markdown(p.plan_id)===md&&P.hash(p.plan_id)===hash&&D.artifacts.find(a=>a.id===r.source.id).content===source);};
 cases.projection_is_observation=ck=>{const r=seed(),p=P.get(r.planId),before=state();for(let n=0;n<50;n++)P.progress(p.plan_id);ck('Pre-admission reads write no owner state',same(before,state()));ck('Build admitted',build(r).ok);ck('Parallel admission',W.advance(r.id,p).ok);const snapshot=state(),projection=P.progress(p.plan_id);for(let n=0;n<50;n++)P.progress(p.plan_id);ck('In-flight reads write no owner state',same(snapshot,state()));ck('Unchanged inputs produce same projection',same(projection,P.progress(p.plan_id)));const original=clone(R.todos);R.todos=clone(original);ck('In-memory owner snapshot replay reconstructs exact projection',same(projection,P.progress(p.plan_id)));R.todos=original;};
 for(const seam of ['materializeForPlan','createBound','commitRun','bindRun','invalidateForExecution'])cases['projection_rollback_'+seam]=ck=>{const r=seed(),p=P.get(r.planId),before=state(),owner=seam==='materializeForPlan'?T:seam==='createBound'?G:seam==='invalidateForExecution'?S:P,original=owner[seam];owner[seam]=(...a)=>{original(...a);P.progress(p.plan_id);P.executionReport(p.plan_id);return {ok:false,error:'fault_after_write_and_projection'};};const out=build(r,true);owner[seam]=original;ck('Actual admission seam refused',!out.ok);ck('Rollback complete',out.rollback?.complete);ck('Projection reads leave no speculative stamp or other write',same(before,state()));};
 cases.restructure_and_fencing=ck=>{const r=seed('restructure'),p=P.get(r.planId),md=P.markdown(p.plan_id),hash=P.hash(p.plan_id);ck('Goal-driven admission',build(r,true).ok);ck('Concurrent work admission',W.advance(r.id,p).admitted===2);const csv=T.get().find(t=>t.plan_step_ids.includes('csv')),old=T.capture(r.threadId,csv.todo_id),binding=T.bindingsFor(r.threadId,csv.todo_id)[0],bindings=clone(T.bindings(r.threadId));act('goal-pause');ck('Pause keeps the same work identities',same(bindings,T.bindings(r.threadId)));ck('Pre-pause callback is fenced',!T.applyTransition(r.threadId,{...old,work_binding:binding.binding_id,to_status:'completed',cause_kind:'outcome_satisfied',cause_ref:'unreceived'}).ok);
 const expected={version:p.version,hash,plan_run_id:p.approved.plan_run_id,list_revision:T.revisionOf(r.threadId)},out=W.restructure(r.id,expected);ck('Actual multi-owner restructure commits',out.ok);ck('Exact binding bytes preserved',same(bindings,T.bindings(r.threadId)));const target=T.get().find(t=>t.plan_step_ids.includes('csv'));ck('Stable admission id distinct from new current target',target.todo_id!==csv.todo_id&&T.bindingsFor(r.threadId,target.todo_id)[0].todo_id===csv.todo_id);ck('Current Plan mapping uses new identity',p.requiredTodoIds.includes(target.todo_id)&&!p.requiredTodoIds.includes(csv.todo_id));const before=clone(T.get());ck('Removed-child callback refused',!T.applyTransition(r.threadId,{...old,work_binding:binding.binding_id,to_status:'completed',cause_kind:'outcome_satisfied',cause_ref:'late'}).ok);ck('Removed child cannot affect rollup',same(before,T.get()));
 act('goal-resume');ck('Explicit resume keeps bindings',same(bindings,T.bindings(r.threadId)));for(let n=0;n<4;n++)ck('Resumed exact attempt completes effect '+n,W.advance(r.id,p).ok);ck('Plan completion predicate is satisfied',P.inspectGoalPlan(p.plan_id).complete);const token=G.evaluate(G.get().id),result=G.dispatch(token.ticket.id);ck('One completion closes bound Goal and Plan',result.ok&&G.get().status==='completed'&&p.status==='completed');ck('No duplicate admission after resume',T.bindings(r.threadId).length===3);ck('Approved prose unchanged by restructuring and resume',P.markdown(p.plan_id)===md&&P.hash(p.plan_id)===hash);};
 cases.restructure_atomic_failure=ck=>{const r=seed(),p=P.get(r.planId);ck('Build',build(r).ok);ck('Admitted',W.advance(r.id,p).ok);const expected={version:p.version,hash:P.hash(p.plan_id),plan_run_id:p.approved.plan_run_id,list_revision:T.revisionOf(r.threadId)},before=state(),original=P.rebindTodoMapping;P.rebindTodoMapping=(...args)=>{original(...args);P.progress(p.plan_id);return {ok:false,error:'fault_after_plan_mapping'};};const out=W.restructure(r.id,expected);P.rebindTodoMapping=original;ck('Actual mapping fault rejects',!out.ok&&out.rollback.complete);ck('Graph, bindings and Plan mapping rolled back together',same(before,state()));};
 cases.real_effect_failure=ck=>{const r=seed(),p=P.get(r.planId);ck('Build',build(r).ok);ck('Admitted',W.advance(r.id,p).ok);const before=state(),original=T.applyTransition;T.applyTransition=(...args)=>{const out=original(...args);P.progress(p.plan_id);return out.ok?{ok:false,error:'fault_after_todo_effect'}:out;};const out=W.advance(r.id,p);T.applyTransition=original;ck('Failure rejected real computed output',!out.ok&&out.rollback.complete);ck('Output, proof, attempts and To-Do changes all roll back',same(before,state()));};
 cases.stale_progress_and_evidence=ck=>{const r=seed(),p=P.get(r.planId);ck('Build',build(r).ok);ck('Parallel work',W.advance(r.id,p).ok);ck('One actual output',W.advance(r.id,p).ok);const a=D.artifacts.find(a=>a.id===r.outputs.summary),raw=a.content;a.content='[]';const pr=P.progress(p.plan_id);ck('Invalidated outcome does not show completed/current progress',pr.stale&&pr.step_states.summary.state!=='completed');ck('Report states currentness',P.executionReport(p.plan_id).stale===true);a.content=raw;ck('Restored exact evidence produces current projection',!P.progress(p.plan_id).stale);const t=T.get().find(t=>t.plan_step_ids.includes('csv')),event=T.capture(r.threadId,t.todo_id);p.revisions[1].push({t:'paragraph',text:'Intervening source edit'});ck('Wrong Plan hash rejects even otherwise-current item callback',!T.applyTransition(r.threadId,{...event,to_status:'completed',cause_kind:'outcome_satisfied',work_binding:T.bindingsFor(r.threadId,t.todo_id)[0].binding_id,cause_ref:'old'}).ok);};
 cases.large_identity=ck=>{const r=seed('large');ck('No fake Plan or Goal for a rendering fixture',!r.planId&&!G.get());ck('All 5,050 items preserved',T.get().length===5050&&T.visibleTree(r.threadId).length===5050);const id=r.todoIds[0];ck('Last item exact stable id',id.endsWith('catalog-05000'));ck('Actual final lookup admitted',W.advance(r.id,null,id).ok);ck('Actual final lookup computed',W.advance(r.id,null,id).ok);const open=T.openWork(r.threadId,id);ck('Exact binding navigation reaches work and source',open.ok&&open.todo_id===id&&open.work_id===T.bindingsFor(r.threadId,id)[0].work_id);ck('Only one leaf executed; the others remain fixtures',T.bindings(r.threadId).length===1&&T.get().filter(t=>t.status==='completed').length===1);};
 cases.conversational_outcome=ck=>{const r=seed('large'),tid=r.threadId,ref='conversation:'+tid,message={id:ref,role:'assistant',type:'text',body:'The accepted convention is UTF-8, with LF line endings.'};C().thread.messages.push(message);T.registerOutcomeOwner('b16_conversation_test',(owner,t,receipt,b)=>({ok:owner===ref&&receipt===message.id&&C().thread.messages.find(m=>m.id===receipt)?.body===t.expected_outcome&&b.work_kind==='primary_segment'}),{admit:(owner,t,b,cause)=>({ok:owner===ref&&cause===message.id&&b.expected_outcome===message.body})});const made=T.materializeForWork({run_id:ref,thread_id:tid,project_id:C().thread.projectId,owner:'b16_conversation_test',ref,steps:[{id:'decision',title:'Record the text convention',outcome:message.body}]});ck('Conversation work uses existing list',made.ok);const id=made.ids[0],binding={binding_id:ref+':binding',todo_id:id,work_id:ref,attempt_id:'attempt1',work_kind:'primary_segment',expected_outcome:message.body};ck('Conversational work admitted',T.applyTransition(tid,{...T.capture(tid,id),to_status:'in_progress',cause_kind:'work_admitted',cause_ref:message.id,work_binding:binding.binding_id,binding}).ok);ck('Message evidence completes without a tool receipt',T.applyTransition(tid,{...T.capture(tid,id),to_status:'completed',cause_kind:'outcome_satisfied',cause_ref:message.id,work_binding:binding.binding_id}).ok);ck('Controller completion proof accepts current conversational evidence',T.outcomeSummary(tid,[id]).ok);};

 const until=async(fn)=>{const start=performance.now();while(!fn()){if(performance.now()-start>12000)throw Error('Timed out waiting for actual handler result');await new Promise(r=>setTimeout(r,20));}};
 async function workerPlan(){act('brainstorm-demo-start',{flow:'synthesis'});act('collab-modal-commit');PM56_BRAINSTORM_DEMOS.play();const origin=PM56_COLLAB.run(PM56_BRAINSTORM_DEMOS.snapshot().runId);await until(()=>origin.brainstorm.phase==='synthesis');act('collab-brainstorm-synthesize',{run:origin.id});const p=P.get(origin.brainstorm.synthesis.planId),r=W.get(p.workRef.ref);return {p,r};}
 cases.worker_pause_callback_fence=async ck=>{
  const {p,r}=await workerPlan(),md=P.markdown(p.plan_id);ck('Explicit Goal Build of exact BrainStorm Plan',build(r,true).ok);
  for(let n=0;n<3;n++)ck('Actual search work admission/effect '+n,W.advance(r.id,p).ok);
  const before=clone(T.bindings(r.threadId));ck('Actual Worker dispatched',W.advance(r.id,p).pending===true);act('goal-pause');await until(()=>!r.pendingWorker);
  ck('Pre-pause Worker callback is rejected without output',!r.outputs.query&&r.rejectedCallbacks.some(e=>e.reason==='stale_worker_callback'));ck('No work binding reminted by Pause',same(before,T.bindings(r.threadId)));
  act('goal-resume');ck('Same admitted work resumes with a new callback fence',W.advance(r.id,p).pending===true);await until(()=>!!r.outputs.query);
  ck('One query work admission, despite callback fence replacement',T.bindings(r.threadId).length===2);ck('Real older query result discarded',same(r.workerTrace.discarded_request_ids,[1])&&same(r.workerTrace.accepted_ids,['z']));
  ck('Measurement work admitted',W.advance(r.id,p).ok);ck('Measured local fallback checked',W.advance(r.id,p).ok&&r.measurement.local_samples_ms.length===5);
  ck('Deep Plan uses the same scoped units, To-Dos and accepted outcomes',P.inspectGoalPlan(p.plan_id).complete);const out=G.dispatch(G.evaluate(G.get().id).ticket.id);ck('Goal and Plan complete together',out.ok&&p.status==='completed'&&G.get().status==='completed');ck('Approved Markdown unchanged',md===P.markdown(p.plan_id));
 };
 cases.worker_failed_outcome_rolls_back=async ck=>{
  const {p,r}=await workerPlan();ck('Build',build(r).ok);for(let n=0;n<3;n++)ck('Work ready '+n,W.advance(r.id,p).ok);
  const original=T.applyTransition,outputs=clone(r.outputs),evidence=clone(r.evidence),artifacts=D.artifacts.length,todos=clone(T.get());
  T.applyTransition=(...args)=>{const x=original(...args);P.progress(p.plan_id);return x.ok?{ok:false,error:'fault_after_worker_outcome'}:x;};ck('Worker actually dispatched',W.advance(r.id,p).pending===true);await until(()=>!r.pendingWorker);T.applyTransition=original;
  ck('Worker failure is surfaced',r.workerError==='fault_after_worker_outcome');ck('No speculative output/evidence remains',same(r.outputs,outputs)&&same(r.evidence,evidence)&&D.artifacts.length===artifacts&&!r.workerTrace);ck('Item and parent transition rollback is complete',same(T.get(),todos));
 };
 return cases;
})();
