import { chromium } from 'playwright';
import { pathToFileURL } from 'url';
const S='/tmp/claude-1000/-mnt-Cursor-PuppetMaster/6b56d129-8eab-4a4f-bf02-133b45afc809/scratchpad/w5v2';
const b = await chromium.launch({ headless:true, args:['--disable-gpu','--allow-file-access-from-files','--no-sandbox']});
const p = await b.newPage({ viewport:{width:1440,height:900}});
await p.goto(pathToFileURL(S+'/snap/index.html').href,{waitUntil:'load'});
await p.waitForFunction(()=>window.__PM56_BOOT_OK===true);
console.log('initial', await p.evaluate(()=>document.body.dataset.phDrawer));
console.log('triggers', await p.evaluate(()=>[...document.querySelectorAll('[data-action*="histor"]')].map(e=>e.dataset.action+'|'+e.tagName+'|'+(e.className||'')+'|'+JSON.stringify(e.getBoundingClientRect().width))));
await p.evaluate(()=>document.querySelector('[data-action="toggle-history"]').click());
await p.waitForTimeout(800);
console.log('after toggle', await p.evaluate(()=>document.body.dataset.phDrawer));
console.log('EXT actions', await p.evaluate(()=>Object.keys(window.PM56_EXT._actions).filter(k=>/hist|pin/.test(k))));
await p.evaluate(()=>window.PM56_EXT._actions['toggle-history']({},null,null));
await p.waitForTimeout(800);
console.log('after direct action', await p.evaluate(()=>document.body.dataset.phDrawer));
console.log('flyout', await p.evaluate(()=>{const f=document.querySelector('.history-flyout'); if(!f) return 'none'; const r=f.getBoundingClientRect(); const cs=getComputedStyle(f); return {x:r.x,w:r.width,h:r.height,clip:cs.clipPath,shadow:cs.boxShadow};}));
await b.close();
