#!/usr/bin/env python3
"""Mechanical comparison using original frozen review grades; no answer/review prose analysis."""
import datetime,hashlib,json,sys
from pathlib import Path
ROOT=Path('/home/sittingmongoose/PM-Experiments/er10-20261007-5a126dd5')
case=sys.argv[1];assert case in ['C-01','C-02','C-03','C-04']
state=ROOT/'state/confirmation-supervisor.json';s=json.loads(state.read_text());pair=s['pairs'][case];d=ROOT/'reviews/confirmation'/case
assert not (d/'COMPARISON.json').exists(), 'Original comparison immutable'
def stamp(x):return datetime.datetime.fromisoformat(x.replace('Z','+00:00'))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
arms={}
for arm in ['control','treatment']:
    t=next(t for t in s['owned_reviews'] if t['case']==case and t['arm']==arm);assert t['status']=='completed' and t['quiet']
    review_task=t
    host=json.loads(Path(t['host_review_freeze']).read_text())
    for f in host['files']:assert sha(f['path'])==f['sha256']
    grade_path=Path(t['directory'])/'REVIEW_FREEZE.json';grade=json.loads(grade_path.read_text())
    tasks=[t for t in s['owned_tasks'] if t['case']==case and t['arm']==arm];assert all(t['quiet'] and t['status']=='completed' for t in tasks)
    stages=[]
    for t in tasks:
        freeze=json.loads(Path(t['terminal_freeze']).read_text());rv=freeze['actual_run_projection'];receipt=json.loads(Path(freeze['native_terminal_receipt']['path']).read_text())
        counters=[o['native_response'] for o in receipt['observations']]
        budget=json.loads((Path(t['directory'])/'runtime-budget.json').read_text())
        files=freeze['files'];sourcebytes=sum(f['bytes'] for f in files if '/sources/' in f['path']);artifactbytes=sum(f['bytes'] for f in files if Path(f['path']).name in ['artifact.md','source-map.json','preservation_check.md'])
        stages.append({'stage':t['stage'],'taskId':t['taskId'],'childThreadId':t['childThreadId'],'childRunId':t['childRunId'],'nativeThreadRefs':t['nativeThreadRefs'],'actual_binding':t['actual_binding'],'native_terminal_statuses':t['native_terminal_statuses'],'requestedAt':rv['requestedAt'],'startedAt':rv['startedAt'],'completedAt':rv['completedAt'],'stage_occupied_seconds':(stamp(rv['completedAt'])-stamp(rv['requestedAt'])).total_seconds(),'queue_startup_seconds':(stamp(rv['startedAt'])-stamp(rv['requestedAt'])).total_seconds() if rv['startedAt'] else None,'deadline':budget['stage_deadline'],'stage_within_allowance':stamp(rv['completedAt'])<=stamp(budget['stage_deadline']),'native_counters_original_not_generated_or_billing':counters,'output_bytes':freeze['output_bytes'],'scientific_artifact_bytes':artifactbytes,'source_capture_bytes':sourcebytes,'observable_dynamic_tool_counts':freeze['observable_dynamic_tool_counts'],'source_operations':None,'raw_usage':freeze['usage'],'terminal_freeze_path':t['terminal_freeze']})
    start=stamp(pair['arms'][arm]['cold_predispatch_at']);serviceend=max(stamp(x['completedAt']) for x in stages);release=max(stamp(json.loads(Path(t['terminal_freeze']).read_text())['at']) for t in tasks)
    arms[arm]={'original_scientific_grade':grade['original_scientific_grade'],'full_declared_scope_assessed':grade['full_declared_scope_assessed'],'source6_axes_original':grade['axes'],'obligations_original':grade['obligations'],'material_defect_count':len(grade.get('material_defects',[])),'limitations_original_reference':str(grade_path),'review_freeze':{'path':str(grade_path),'sha256':sha(grade_path)},'host_review_freeze':{'path':review_task['host_review_freeze'],'sha256':sha(review_task['host_review_freeze'])},'cold_predispatch_at':start.isoformat(),'candidate_service_terminal_at':serviceend.isoformat(),'resource_release_observed_upper_bound':release.isoformat(),'failure_inclusive_service_latency_seconds':(serviceend-start).total_seconds(),'failure_inclusive_host_closeout_latency_seconds':(release-start).total_seconds(),'aggregate_stage_occupied_seconds':sum(x['stage_occupied_seconds'] for x in stages),'host_and_between_stage_elapsed_seconds':(release-start).total_seconds()-sum(x['stage_occupied_seconds'] for x in stages),'whole_arm_deadline':pair['arms'][arm]['whole_arm_deadline'],'service_terminal_within45min':serviceend<=stamp(pair['arms'][arm]['whole_arm_deadline']),'closeout_within45min':release<=stamp(pair['arms'][arm]['whole_arm_deadline']),'stages':stages,'review_time_separate':review_task['actual_run_terminal_projection'],'usage':{'input':None,'cached_input':None,'generated_output':None,'reasoning_subset':None,'billing':None},'source_operations':None,'scope_audit':'incomplete_unknown; advisory maps not filesystem firewall','native_raw_API_bodies':'missing; actual active and terminal projection evidence distinct','affordability_claim':False}
now=datetime.datetime.now(datetime.timezone.utc).isoformat();out={'schema':'pm.er10.confirmation-comparison.v1','case':case,'domain':pair['domain_id'],'repetition':pair['repetition'],'frozen_at':now,'qualification':'DIAGNOSTIC_UNQUALIFIED','original_grades_preserved':True,'assessed_pair':True,'arms':arms,'service_latency_ratio_control_over_treatment':arms['control']['failure_inclusive_service_latency_seconds']/arms['treatment']['failure_inclusive_service_latency_seconds'],'host_closeout_latency_ratio_control_over_treatment':arms['control']['failure_inclusive_host_closeout_latency_seconds']/arms['treatment']['failure_inclusive_host_closeout_latency_seconds'],'repeat_median_range':'Deferred until all four original comparisons frozen; no best-of','quota_economics':'Unknown usage/billing; no affordability claim','source_operations_limitation':'Tool projection incomplete; file/capture counts are not source operations','native_counters_policy':'Original cumulative counters retained per stage; no nested/enclosing/cumulative sum','single_account_context':'First two matched pairs overlapped four candidates; account/sibling contention not fully attributable; not serialized single-project estimate','candidate_feedback_sent':False,'outcome_tuning':False}
(d/'COMPARISON.json').write_text(json.dumps(out,indent=2)+'\n');pair.update(status='ASSESSED_ORIGINAL_COMPARISON_FROZEN',comparison_path=str(d/'COMPARISON.json'),comparison_sha256=sha(d/'COMPARISON.json'));s['comparisons_complete']=sum('comparison_path' in x for x in s['pairs'].values());s['updated_at']=now;state.write_text(json.dumps(s,indent=2)+'\n')
with (ROOT/'state/confirmation-supervisor-log.jsonl').open('a') as f:f.write(json.dumps({'at':now,'event':'original_pair_comparison_frozen','case':case,'path':str(d/'COMPARISON.json'),'sha256':sha(d/'COMPARISON.json')})+'\n')
print(json.dumps({'comparison_path':str(d/'COMPARISON.json'),'sha256':sha(d/'COMPARISON.json'),'comparisons_complete':s['comparisons_complete'],'original_scientific_review_prose_not_read':True}))
