/* B18 continuation verification. Injected test driver, never loaded by the app.
 * Uses the real owners; controlled corruption/failure injection is not a UI proof. */
window.B18_CASES={};
(()=>{
'use strict';const tests=B18_CASES,E=PM56_EXT,S=PM56_SCHED,P=PM56_PLANS,C=PM56_COLLAB,T=PM56_TODOS,A=PM56_ARTIFACTS,AT=PM56_ATTACHMENTS,CS=PM56_COMPOSER_STATE;
const clone=x=>JSON.parse(JSON.stringify(x)),act=(name,data={})=>E.run(name,{dataset:data},new Event('click')),sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){for(let i=0;i<150;i++){if(fn())return;await sleep(100);}throw Error('Timed out awaiting actual work');}
function fresh(){const c=E.ctx(),t=clone(c.state.threads.find(t=>t.id==='query'));Object.assign(t,{id:'b18c-test',title:'Snapshot scheduling',projectId:'b18c',worktreeId:'b18c',archived:false,messages:[]});c.state.threads.push(t);c.switchThread(t.id);c.state.model=PM56_DATA.models.find(m=>m.status==='ready').id;c.state.composer=' Keep these exact bytes. ';CS.bufferFor(t.id).text=c.state.composer;CS.bufferFor(t.id).attachments=[];CS.bufferFor(t.id).destination=null;PM56_RUNTIME.composer.destination=null;PM56_RUNTIME.quota.waiting=false;S.restore();return E.ctx();}
function draft(){const d=S.messageDraft();Object.assign(d,{date:'2027-05-10',time:'22:00',timezone:'America/New_York'});return d;}
const artifacts=()=>JSON.stringify(PM56_DATA.artifacts);
function file(bytes,name='binary.dat',relative){const f=new File([bytes],name,{type:'application/octet-stream'});if(relative)Object.defineProperty(f,'webkitRelativePath',{value:relative});return f;}
async function addFile(c,bytes,name){AT.admitFiles(c.thread.id,[file(bytes,name)]);await until(()=>CS.bufferFor(c.thread.id).attachments.every(a=>a.process_state==='ready'));return CS.bufferFor(c.thread.id).attachments.at(-1);}
function folder(c,files){const result=AT.admitFolder(c.thread.id,files);if(!result.ok)throw Error(result.error);return result.attachment;}
function room(pid=false){S.restore();PM56_RUNTIME.quota.waiting=false;PM56_ROOM_DEMOS.start('discussion');const d=C.draft(),model=PM56_DATA.models.find(m=>m.status==='ready');d.rows.forEach(q=>q.requestedModelId=model.id);act('collab-modal-commit');const c=E.ctx(),r=C.runsForThread(c.thread.id).at(-1);if(!r)throw Error('Room did not start');act('collab-message',{run:r.id,...(pid?{participant:r.participants[1].id}:{})});c.state.composer=' Preserve this scheduled question. ';CS.bufferFor(r.threadId).text=c.state.composer;return {c,r};}
function create(){const out=S.saveMessage(draft());if(!out.ok)throw Error(JSON.stringify(out));return out.record;}
function dispatch(m){return S.dispatchMessageAt(m.scheduled_dispatch_id,Date.parse(m.scheduled_at_utc));}
function crew(){S.restore();PM56_RUNTIME.quota.waiting=false;PM56_B18.start('windows');document.querySelector('[data-action="send"]').click();const p=P.get(PM56_B17_WORK.snapshot().planId);C.openConfigure('crew');const config=C.draft(),model=PM56_DATA.models.find(m=>m.status==='ready');config.rows=config.rows.slice(0,2);config.rows.forEach((q,i)=>{q.requestedModelId=model.id;q.role=['Prepare inputs','Compute and validate'][i];});config.config.parallelism=2;const prepared=C.preparePlanCrew(p.plan_id,config);if(!prepared.ok)throw Error(JSON.stringify(prepared));const d=S.buildDraft(p.plan_id,p.version);Object.assign(d,{executionTopology:'crew',crewDefinition:prepared.snapshot,timezone:'America/New_York',startTime:'22:00',pauseTime:'23:00',days:[0,1,2,3,4,5,6],windDown:10});return {p,d,config};}
function saveCrew(d){const out=S.saveBuild(d);if(!out.ok)throw Error(JSON.stringify(out));return out.record;}
function open(b){const at=Date.parse(b.next_occurrence_at),out=S.windowTick(b.schedule_id,at,S.captureBuild(b.schedule_id));if(!out.ok)throw Error(JSON.stringify(out));return {at,out};}
function ownerState(p){return JSON.stringify({p,runs:P.runs(),crews:C.runs(),todos:T.get(p.thread_id),bindings:T.bindings(p.thread_id),effects:C.effects(),messages:E.ctx().thread.messages});}

tests.sha256_independent_vectors=ck=>{for(const [data,hash] of [['','e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'],['abc','ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'],['a'.repeat(1000),'41edece42d63e8d9bf515a9ba6932e1c20cbc9f5a5d134645adb5db1b9737ea3']])ck('Known SHA-256 vector length '+data.length,AT.sha256(data)===hash);};
tests.file_actual_bytes_retained=async ck=>{const c=fresh(),bytes=new Uint8Array([0,1,13,10,255,128,60,115,99,114,105,112,116,62]);await addFile(c,bytes,'original.bin');const out=await S.saveMessageWithSnapshots(draft());ck('Real selected file committed',out.ok);const ref=out.record.attachment_refs[0].snapshot_ref;ck('Exact binary bytes and hash preserved',JSON.stringify([...AT.snapshotBytes(ref)])===JSON.stringify([...bytes])&&AT.inspectScheduleSnapshot(ref).ok);ck('No scan fabricated',A.resolve(ref).revision.record.scan_status==='not_scanned');ck('Scheduling consumed composer only at commit',!c.state.composer&&!CS.bufferFor(c.thread.id).attachments.length);ck('Actual message dispatch uses retained file',dispatch(out.record).ok&&c.thread.messages.at(-1).attachments[0].snapshot_ref.artifact_id===ref.artifact_id);};
tests.folder_full_manifest_and_children=async ck=>{const c=fresh();folder(c,[file('z\r\n','z.txt','Project/z.txt'),file('a\n','a.txt','Project/nested/a.txt')]);const out=await S.saveMessageWithSnapshots(draft());ck('Folder snapshot committed',out.ok);const ref=out.record.attachment_refs[0].snapshot_ref,v=AT.inspectScheduleSnapshot(ref),root=A.resolve(ref).revision.record;ck('Every selected path retained in exact UTF-8 order',v.ok&&v.count===2&&root.payload.files.map(f=>f.path).join('|')==='Project/nested/a.txt|Project/z.txt');ck('Children held through folder reachability',root.payload.files.every(f=>A.purge(f.ref).error==='artifact_still_referenced'));ck('Manifest hash bound in schedule',out.record.attachment_refs[0].folder_manifest_hash===root.payload.manifest_sha256);};
tests.folder_missing_child_holds=async ck=>{const c=fresh();folder(c,[file('keep','a.txt','Project/a.txt')]);const out=await S.saveMessageWithSnapshots(draft());if(!out.ok)throw Error(out.error);const root=A.resolve(out.record.attachment_refs[0].snapshot_ref).revision.record,child=PM56_DATA.artifacts.find(x=>x.id===root.payload.files[0].ref.artifact_id);child.revisionAvailability={1:'missing'};const result=dispatch(out.record);ck('Missing retained child holds entire message',result.held&&!c.thread.messages.some(m=>m.viaSchedule));ck('Missing child named instead of newer replacement',String(result.error).includes('retained_file'));};
tests.folder_traversal_and_duplicate_rejected=async ck=>{const c=fresh();folder(c,[file('unsafe','x','Project/../x')]);const before=artifacts(),out=await S.saveMessageWithSnapshots(draft());ck('Traversal rejected before publication',!out.ok&&out.error==='invalid_or_duplicate_snapshot_path'&&artifacts()===before);CS.bufferFor(c.thread.id).attachments=[];folder(c,[file('a','x','Project/x'),file('b','x','Project/x')]);const again=await S.saveMessageWithSnapshots(draft());ck('Duplicate manifest path rejected without overwrite',again.error==='invalid_or_duplicate_snapshot_path'&&artifacts()===before);};
tests.file_snapshot_rollback_no_orphans=async ck=>{const c=fresh();await addFile(c,'hello','hello.txt');const d=draft(),before=artifacts(),buffer=JSON.stringify(CS.captureForSchedule(c,c.thread.id)),old=A.retain;A.retain=()=>({ok:false,error:'injected_retention_failure'});let out;try{out=await S.saveMessageWithSnapshots(d);}finally{A.retain=old;}ck('Snapshot and schedule transaction refused',out.error==='injected_retention_failure');ck('No orphan artifact, message or consumed composer',before===artifacts()&&buffer===JSON.stringify(CS.captureForSchedule(c,c.thread.id))&&!c.thread.messages.length);};
tests.snapshot_cancelled_form_no_publish=async ck=>{const c=fresh();await addFile(c,'keep','keep.txt');const before=artifacts(),text=c.state.composer;const out=await S.saveMessageWithSnapshots(draft(),null,()=>false);ck('Cancelled form cannot publish bytes or clear text',out.error==='schedule_form_changed'&&artifacts()===before&&c.state.composer===text);};
tests.snapshot_changed_composer_during_read=async ck=>{const c=fresh(),record=await addFile(c,'first','first.txt'),f=record._file,read=f.arrayBuffer.bind(f);f.arrayBuffer=async()=>{const bytes=await read();c.state.composer='NEW composer text';return bytes;};const before=artifacts(),out=await S.saveMessageWithSnapshots(draft());ck('Async source currentness revalidated',!out.ok&&artifacts()===before&&c.state.composer==='NEW composer text');};
tests.snapshot_partial_read_refuses=async ck=>{const c=fresh(),record=await addFile(c,'complete','source.txt');record._file.arrayBuffer=async()=>new ArrayBuffer(1);const before=artifacts(),out=await S.saveMessageWithSnapshots(draft());ck('Partial read refuses without partial artifacts',out.error==='file_read_incomplete'&&artifacts()===before&&c.state.composer.length>0);};
tests.live_path_without_selected_bytes_refuses=async ck=>{const c=fresh();CS.bufferFor(c.thread.id).attachments=[{id:'live-missing',kind:'file',path:'/private/source.txt',name:'source.txt'}];const before=artifacts(),out=await S.saveMessageWithSnapshots(draft());ck('A path is not substituted for retained bytes',!out.ok&&artifacts()===before&&c.state.composer.length>0);};

tests.collaborative_message_shared_identity=ck=>{const {c,r}=room(),m=create(),before=C.effects(),out=dispatch(m);ck('Scheduled room message delivered',out.ok);const a=c.thread.messages.find(x=>x.id===out.message_id),b=r.messages.find(x=>x.id===out.message_id);ck('One message object referenced by both surfaces',a===b&&a.body===m.text&&a.createdAt===a.time);ck('Exactly one inbox delivery to each member',r.scheduledDeliveries.length===1&&b.recipientIds.length===r.participants.length&&r.chatRoom.deliveries.filter(x=>x.messageId===b.id).length===1);ck('No fabricated provider or Usage effects',JSON.stringify(C.effects())===JSON.stringify(before));};
tests.collaborative_participant_exact_and_replay=ck=>{const {c,r}=room(true),m=create(),out=dispatch(m),again=dispatch(m),message=r.messages.find(x=>x.id===out.message_id);ck('Only the selected participant receives it',out.ok&&message.recipientIds.length===1&&message.recipientIds[0]===r.participants[1].id);ck('Replay creates no duplicate inbox or thread record',again.duplicate&&again.message_id===out.message_id&&r.scheduledDeliveries.length===1&&c.thread.messages.filter(x=>x.id===out.message_id).length===1);};
tests.collaboration_ended_target_holds=ck=>{const {c,r}=room(),m=create();act('collab-cancel',{run:r.id});const out=dispatch(m);ck('Ended room held without Assistant fallback',out.held&&out.error==='destination_ended'&&!c.thread.messages.some(x=>x.viaSchedule));};
tests.collaboration_generation_mismatch_holds=ck=>{const {c,r}=room(),m=create();r.definitionRevision++;const out=dispatch(m);ck('Reconfigured room cannot silently take old scheduled input',out.held&&out.error==='destination_generation_changed'&&!c.thread.messages.some(x=>x.viaSchedule));};
tests.collaboration_pause_holds_then_explicit_resume=ck=>{const {r}=room(),m=create();act('collab-pause',{run:r.id});const out=dispatch(m);ck('Paused destination holds',out.held&&out.error==='destination_not_accepting');act('collab-resume',{run:r.id});ck('Explicit destination resume permits exact same snapshot',dispatch(m).ok&&r.scheduledDeliveries.length===1);};
tests.collaboration_two_surface_rollback=ck=>{const {c,r}=room(),m=create(),before=JSON.stringify(r),old=PM56_TX.append;PM56_TX.append=(o,k,v)=>{if(o===c.thread&&v?.viaSchedule)throw Error('injected_thread_append');return old(o,k,v);};let out;try{out=dispatch(m);}finally{PM56_TX.append=old;}ck('Thread failure refuses delivery',out.error==='injected_thread_append');ck('Collaboration message/inbox rolled back',JSON.stringify(r)===before&&!c.thread.messages.some(x=>x.viaSchedule));};
tests.collaboration_stop_during_owner_delivery=ck=>{const {c,r}=room(),m=create(),before=JSON.stringify(r),old=C.deliverScheduledMessage;C.deliverScheduledMessage=(message,d)=>{const out=old(message,d);S.latchStop('User stopped during owner return');return out;};let out;try{out=dispatch(m);}finally{C.deliverScheduledMessage=old;}ck('Post-helper Stop is enforced',!out.ok&&!c.thread.messages.some(x=>x.viaSchedule));ck('No partial collaboration message survives',JSON.stringify(r)===before);};

tests.crew_schedule_no_execution=ck=>{const {p,d}=crew(),before=C.runs().length,b=saveCrew(d);ck('Schedule freezes configuration without a CrewRun or PlanRun',C.runs().length===before&&!p.approved&&p.status==='ready'&&!PM56_GOAL.get());ck('Complete frozen roster and effective concurrency disclosed',b.topology_snapshot.collaboration_definition_ref.participants.length===2&&b.topology_snapshot.collaboration_definition_ref.effective_concurrency===1&&Object.isFrozen(b.topology_snapshot.collaboration_definition_ref));};
tests.crew_admission_atomic_identity=ck=>{const {p,d}=crew(),b=saveCrew(d),{out}=open(b),run=P.runs()[p.approved.plan_run_id],c=C.run(run.crew_run_id);ck('CrewRun, PlanRun and To-Dos share exact binding',out.ok&&c.crew.planBinding.plan_run_id===run.plan_run_id&&c.crew.assignments.every(a=>run.required_todo_ids.includes(a.todo_id)));ck('Specialized Plan command and scheduler receipt carry Crew identity',p.buildAdmission.command==='cmd.chat.plan.build_with_crew'&&b.dispatchReceipt.crew_run_id===c.id&&p.topology==='crew');};
tests.crew_commit_failure_rolls_all_owners_back=ck=>{const {p,d}=crew(),b=saveCrew(d),before=ownerState(p),old=P.commitRun;P.commitRun=()=>({ok:false,error:'injected_plan_commit'});let out;try{out=S.dispatchBuildAt(b.schedule_id,Date.parse(b.next_occurrence_at),b.revision);}finally{P.commitRun=old;}ck('Failed PlanRun commit reported',out.error==='injected_plan_commit');ck('Crew, To-Do and Plan owners all roll back',ownerState(p)===before&&!b.dispatchReceipt&&!b.runtime_created);};
tests.crew_owner_failure_leaves_no_orphans=ck=>{const {p,d}=crew(),b=saveCrew(d),before=ownerState(p),old=C.admitPlanCrew;C.admitPlanCrew=()=>({ok:false,error:'injected_crew_commit'});let out;try{out=S.dispatchBuildAt(b.schedule_id,Date.parse(b.next_occurrence_at),b.revision);}finally{C.admitPlanCrew=old;}ck('Crew refusal rolls back earlier To-Do materialization',out.error==='injected_crew_commit'&&ownerState(p)===before&&!b.runtime_created);};
tests.crew_defaults_cannot_retarget=ck=>{const {p,d}=crew(),b=saveCrew(d),snapshot=b.topology_snapshot.collaboration_definition_ref;C.definitions().crew.memberCount=8;C.definitions().crew.parallelism=8;open(b);const c=C.run(b.dispatchReceipt.crew_run_id);ck('Dispatch uses saved roster, not later defaults',c.participants.length===2&&c.crew.definition===snapshot&&c.crew.definition.requested_concurrency===2);};
tests.crew_frozen_account_unavailable=ck=>{const {p,d}=crew(),b=saveCrew(d),q=b.topology_snapshot.collaboration_definition_ref.participants[0];PM56_DATA.models.find(m=>m.id===q.model_id).status='unavailable';const out=S.dispatchBuildAt(b.schedule_id,Date.parse(b.next_occurrence_at),b.revision);ck('Missing participant route refuses all execution',!out.ok&&!p.approved&&!C.runs().some(r=>r.crew?.planBinding?.plan_id===p.plan_id)&&!b.runtime_created);};
tests.crew_schedule_and_dispatch_replay=ck=>{const {p,d}=crew(),b=saveCrew(d),again=S.saveBuild(d);ck('Schedule replay preserves one definition and one schedule',again.ok&&again.replayed!==false&&again.record===b);open(b);const run=p.approved.plan_run_id,n=C.runs().length,out=S.dispatchBuildAt(b.schedule_id,Date.parse(b.next_occurrence_at),b.revision);ck('Duplicate timer admits no second CrewRun',out.duplicate&&out.receipt.plan_run_id===run&&C.runs().length===n);};
tests.crew_pause_blocks_auto_resume=ck=>{const {p,d}=crew(),b=saveCrew(d),{at}=open(b),id=b.dispatchReceipt.crew_run_id;act('collab-pause',{run:id});const out=S.windowTick(b.schedule_id,at,S.captureBuild(b.schedule_id));ck('Manual Crew pause reaches Plan and outranks timer',p.attention?.kind==='paused'&&out.error==='manual_pause_or_owner_block'&&C.run(id).status==='paused');};
tests.crew_attributed_actual_completion=async ck=>{const {p,d}=crew(),b=saveCrew(d);open(b);await until(()=>p.status==='completed');C.refreshPlanCrew(p.plan_id);const c=C.run(b.dispatchReceipt.crew_run_id),bindings=T.bindings(p.thread_id).filter(x=>x.run_id===p.approved.plan_run_id);ck('Actual local work completed under one Crew/Plan run',c.status==='completed'&&bindings.length===3&&bindings.every(x=>x.state==='succeeded'));ck('Every admitted operation carries a frozen participant identity',bindings.every(x=>x.collaboration_run_id===c.id&&c.participants.some(q=>q.id===x.participant_id)&&x.collaboration_definition_key===c.crew.definition.content_key));ck('Required participants complete from To-Do evidence, not prose',c.participants.every(q=>q.outcome==='completed')&&T.outcomeSummary(p.thread_id,p.requiredTodoIds).ok);};
tests.crew_window_same_run_and_outputs=async ck=>{const {p,d}=crew(),b=saveCrew(d),{at}=open(b),id=b.dispatchReceipt.crew_run_id;await until(()=>!!PM56_B17_WORK.snapshot().outputs.normalize);const preserved=JSON.stringify(PM56_B17_WORK.snapshot().outputs.normalize),w=S.buildWindow(b,at);const paused=S.windowTick(b.schedule_id,w.wind_down_at,S.captureBuild(b.schedule_id));ck('Crew pauses safely at wind-down',paused.paused&&p.attention.kind==='window');const next=PM56_SCHEDULE_TIME.next(b.timezone,b.days_of_week,22,0,w.end+1);const resumed=S.windowTick(b.schedule_id,next,S.captureBuild(b.schedule_id));ck('Same Crew and Plan resume next occurrence',resumed.resumed&&b.dispatchReceipt.crew_run_id===id&&C.run(id).crew.planBinding.plan_run_id===p.approved.plan_run_id);await until(()=>p.status==='completed');ck('Prior completed output not re-executed',JSON.stringify(PM56_B17_WORK.snapshot().outputs.normalize)===preserved&&PM56_B17_WORK.snapshot().attempts.filter(a=>a.stage==='normalize').length<=1);};
tests.selected_snapshot_idempotency_after_composer_consumed=async ck=>{const c=fresh();await addFile(c,'original','replay.txt');const d=draft(),one=await S.saveMessageWithSnapshots(d),before=artifacts(),two=await S.saveMessageWithSnapshots(d);ck('Original snapshot and schedule returned after input consumed',one.ok&&two.ok&&two.replayed&&one.record===two.record&&artifacts()===before);const conflict=await S.saveMessageWithSnapshots({...d,text:'different'});ck('Same selection key cannot bind different input',conflict.error==='idempotency_conflict'&&artifacts()===before);};
tests.file_read_failure_keeps_all_inputs=async ck=>{const c=fresh();const a=folder(c,[file('good','good.txt','Root/good.txt'),file('bad','bad.txt','Root/bad.txt')]);a._files[1].arrayBuffer=async()=>{throw Error('device disappeared');};const before=artifacts(),out=await S.saveMessageWithSnapshots(draft());ck('Read failure keeps full selection and publishes nothing',!out.ok&&out.error==='snapshot_read_failed'&&artifacts()===before&&CS.bufferFor(c.thread.id).attachments.length===1&&!!c.state.composer);};
tests.file_owner_block_not_bypassed=async ck=>{const c=fresh(),a=await addFile(c,'blocked','blocked.txt');a.filesafe={status:'blocked'};const before=artifacts(),out=await S.saveMessageWithSnapshots(draft());ck('Blocked owner refuses snapshot instead of pretending scan passed',out.error==='attachment_owner_blocked'&&artifacts()===before&&!!c.state.composer);};
tests.crew_review_reopens_exact_roster=ck=>{const {p,d}=crew(),snapshot=d.crewDefinition;C.definitions().crew.memberCount=8;const out=C.openScheduledCrew(P.admissionSnapshot(p.plan_id),snapshot),review=C.draft(),again=C.preparePlanCrew(p.plan_id,review);ck('Review opens saved slots instead of new defaults',out.ok&&review.rows.length===2&&review.rows[0].rowId===snapshot.participants[0].id&&review.rows[0].role===snapshot.participants[0].role);ck('Unchanged review reproduces original definition key',again.ok&&again.snapshot.content_key===snapshot.content_key);};
tests.crew_configuration_stale_form_refuses=ck=>{const {p,d}=crew();C.openScheduledCrew(P.admissionSnapshot(p.plan_id),d.crewDefinition);const config=C.draft();config.scheduleIntent.expected.hash='stale';const out=C.preparePlanCrew(p.plan_id,config);ck('Stale configuration creates no executable work',out.error==='plan_changed_during_crew_configuration'&&!p.approved&&!C.runs().some(r=>r.crew?.planBinding?.plan_id===p.plan_id));};
tests.crew_generic_writers_cannot_fake_completion=ck=>{const {p,d}=crew(),b=saveCrew(d);open(b);const r=C.run(b.dispatchReceipt.crew_run_id),q=r.participants[0],before=JSON.stringify(r);const values=[C.setOutcome(r.id,q.id,'completed',{}),C.retryParticipant(r.id,q.id),C.replaceParticipant(r.id,q.id,q.requestedModelId,'test'),C.acceptCallback(r.id,q.id,{epoch:r.stopEpoch,assignmentRevision:q.assignmentRevision,outcome:'completed'})];ck('Every generic participant writer routes to Plan owner',values.every(v=>v.error==='plan_work_owner_required')&&JSON.stringify(r)===before&&p.status==='building');};
tests.crew_unknown_config_refuses=ck=>{const {p,d,config}=crew();config.config.assignmentStrategy='adaptive';const adaptive=C.preparePlanCrew(p.plan_id,config);config.config.assignmentStrategy='manager_directed';config.wonderer=true;const specialist=C.preparePlanCrew(p.plan_id,config);ck('Unavailable execution options are refusals, not simulated results',adaptive.error==='scheduled_adaptive_adapter_unavailable'&&specialist.error==='scheduled_specialist_adapter_unavailable'&&!p.approved);};
tests.crew_altered_helper_result_rolls_back=ck=>{const {p,d}=crew(),b=saveCrew(d),before=ownerState(p),original=C.admitPlanCrew;C.admitPlanCrew=(snapshot,run)=>{const out=original(snapshot,run);return {...out,run:{...out.run,id:'forged-return'}};};let out;try{out=S.dispatchBuildAt(b.schedule_id,Date.parse(b.next_occurrence_at),b.revision);}finally{C.admitPlanCrew=original;}ck('Final original-identity check rejects altered helper result',!out.ok&&out.error==='crew_admission_binding_changed');ck('Earlier Crew and To-Do writes roll back with no orphan',ownerState(p)===before&&!b.runtime_created&&!b.dispatchReceipt);};
tests.crew_cancel_preserves_unrelated_message=ck=>{const {p,d}=crew(),b=saveCrew(d);open(b);const ctx=E.ctx();PM56_RUNTIME.composer.destination=null;CS.bufferFor(ctx.thread.id).destination=null;ctx.state.composer='Unrelated future prompt';CS.bufferFor(ctx.thread.id).text=ctx.state.composer;const m=create(),before=JSON.stringify(m),id=b.dispatchReceipt.crew_run_id;act('collab-cancel',{run:id});ck('Crew cancellation fences bound Plan',p.status==='canceled'&&C.run(id).status==='canceled');ck('Unrelated scheduled user message retained whole',JSON.stringify(m)===before&&m.state==='scheduled');};
tests.collaboration_selected_file_same_ref_both_surfaces=async ck=>{const {c,r}=room(true);await addFile(c,new Uint8Array([0,255,128]),'selected.bin');const out=await S.saveMessageWithSnapshots(draft());ck('File schedule commits exact destination and bytes',out.ok);const delivered=dispatch(out.record),main=c.thread.messages.find(m=>m.id===delivered.message_id),other=r.messages.find(m=>m.id===delivered.message_id);ck('Both surfaces reference original immutable file snapshot',delivered.ok&&main===other&&AT.snapshotBytes(main.attachments[0].snapshot_ref)[1]===255&&main.recipientIds.length===1);};

tests.pending_room_message_not_overwritten=ck=>{const {c,r}=room(),first=create();act('collab-message',{run:r.id});c.state.composer='Second independent input';CS.bufferFor(c.thread.id).text=c.state.composer;const second=create(),one=dispatch(first),two=dispatch(second);ck('A second independent schedule holds behind undiscussed input',one.ok&&two.held&&two.error==='finish_pending_delivery'&&r.chatRoom.lastUserMessageId===one.message_id&&r.scheduledDeliveries.length===1);const W=PM56_ROOM;W.beginRound(r.id,W.envelope(r.id));for(const p of r.participants){const req=W.request(r.id,p.id);if(req)W.submit(r.id,{...req,body:'Recorded bounded reply for first input.'});}const resumed=dispatch(second);ck('Second input delivers after original addressed round, without duplicate first',resumed.ok&&r.chatRoom.lastUserMessageId===resumed.message_id&&r.scheduledDeliveries.length===2&&r.messages.filter(m=>m.replyTo===one.message_id).length===3);};
})();
