"""dead_selectors.py -- FROZEN human-reviewed dead-selector list (PM7 T01).

GENERATED by css_audit.py --freeze and then human-reviewed. Do not hand-edit
casually; re-derive with the recipe in README.md when the base changes.
"""

BASE_SHA = "bbfbee10485ddc0dad27777106e6bcaa12a4233189e9d4ec1309e22e6ed64965"

# Per-family byte tallies (audit-time estimates, rule bytes split across
# selector lists):
FAMILY_BYTES = {
    "artifact-": 932,  # 8 selectors
    "bento-": 2283,  # 21 selectors
    "inspector-": 1097,  # 7 selectors
    "interview-": 2749,  # 18 selectors
    "msg-": 1313,  # 8 selectors
    "orch-": 16053,  # 133 selectors
    "plan-": 659,  # 6 selectors
    "pm6-": 17798,  # 163 selectors
    "sc-": 3106,  # 28 selectors
    "terminal-": 2766,  # 22 selectors
    "widget-": 1679,  # 14 selectors
}

# Harvested dynamic prefixes at freeze time (protection set):
HARVESTED_PREFIXES = ['ac-', 'ann-', 'art-', 'bento-card-', 'cl-mode-', 'diff-', 'edtp-', 'g-new-', 'hs-', 'is-', 'kind-', 'led-', 'm-', 'n-', 'n-sev-', 'new-key-', 'op-debug-', 'op-webrun-', 'page-', 'pane-accent-', 'pill-', 'pm-ledger-', 'pm6-conf-', 'pm6-dash-', 'proj-', 'pu-', 'rn-', 'role-', 's-', 'st-', 'tcb-', 'tp-fresh-', 'tp-new-', 'tp-split-', 'ts-fresh-', 'ts-new-', 'ts-sess-split-', 'ue-47-', 'webrun-', 'wt-']

# ---- 2026-07-28 human review (Cozy Shelves integration wave) ----
# Reviewed against the cozy-shelves-integrated base (31 blocks). Verdicts:
#  * 137 newly approved families are the retired PM6 panel markup
#    (pm6-sp/pm6-fm/pm6-search/pm6-dm/sc-accordion/pm6-gh/pm6-sc/pm6-wt/
#    sc-wt/pm6-agent/pm6-art) -- their views were replaced or deleted.
#  * Cozy Shelves selectors (sh-*, fm-*, rd-*, pm-segtab, pill-fit,
#    pm-panel-enter, --cat-*) verified ABSENT from the frozen list.
#  * .pm6-chip conflicts resolved: only dead scoped rows frozen.
#  * .pm6-sp-btn base family kept frozen; the new Debug tab empty state was
#    restyled onto .rd-startbtn instead of resurrecting the dead family.
#  * .pm6-sp-btn-primary appended below (its last markup usage removed).
# APPROVED 2026-07-29 (Jared) per the port-back contract: family diffs above.
# The 11 retired PM6 panel families (+ appended .pm6-sp-btn-primary) stay
# frozen; the EXCLUDED candidates below stay kept in the corpus.
# Dead candidates EXCLUDED by review (kept in the file), with reasons:
#   EXCLUDED .chat-dropdown-search                                        family not in approved set: chat-
#   EXCLUDED .chat-dropdown-search input                                  family not in approved set: chat-
#   EXCLUDED .chat-dropdown-list                                          family not in approved set: chat-
#   EXCLUDED .dashboard-grid                                              family not in approved set: dashboard-
#   EXCLUDED .wizard-activity-log                                         family not in approved set: wizard-
#   EXCLUDED .pm-inspector-drawer                                         family not in approved set: pm-
#   EXCLUDED .pm-debug-cell                                               family not in approved set: pm-
#   EXCLUDED [data-theme^="glass"] .files-panel                           family not in approved set: files-
#   EXCLUDED [data-theme^="glass"] .files-panel-header                    family not in approved set: files-
#   EXCLUDED [data-theme^="glass"] .questionnaire-ui                      family not in approved set: questionnaire-
#   EXCLUDED [data-theme^="glass"] .panel-header                          family not in approved set: panel-
#   EXCLUDED [data-theme^="glass"] .sticky-plan-tracker                   family not in approved set: sticky-
#   EXCLUDED [data-theme^="glass"] .progress-bar                          family not in approved set: progress-
#   EXCLUDED [data-theme^="glass"] .progress-bar .fill                    family not in approved set: progress-
#   EXCLUDED [data-theme^="glass"] .chat-modes                            family not in approved set: chat-
#   EXCLUDED [data-theme^="glass"] .chat-modes .mode                      family not in approved set: chat-
#   EXCLUDED [data-theme^="glass"] .chat-modes .mode.active               family not in approved set: chat-
#   EXCLUDED [data-theme^="glass"] .chat-footer                           family not in approved set: chat-
#   EXCLUDED [data-theme^="glass"] .chat-footer select                    family not in approved set: chat-
#   EXCLUDED [data-theme^="glass"] .psm-tab:hover                         family not in approved set: psm-
#   EXCLUDED [data-theme^="glass"] .psm-tab.active                        family not in approved set: psm-
#   EXCLUDED [data-theme^="glass"] .psm-pane                              family not in approved set: psm-
#   EXCLUDED [data-theme^="glass"] .psm-btn                               family not in approved set: psm-
#   EXCLUDED [data-theme^="glass"] .psm-btn.primary                       family not in approved set: psm-
#   EXCLUDED [data-theme^="glass"] .wizard-input                          family not in approved set: wizard-
#   EXCLUDED [data-theme^="glass"] .wizard-select                         family not in approved set: wizard-
#   EXCLUDED [data-theme^="glass"] .wizard-input:focus                    family not in approved set: wizard-
#   EXCLUDED [data-theme^="glass"] .wizard-select:focus                   family not in approved set: wizard-
#   EXCLUDED [data-theme^="glass"] .action-btn:hover                      family not in approved set: action-
#   EXCLUDED .title-bar .title-spacer                                     family not in approved set: title-
#   EXCLUDED .stub-page                                                   family not in approved set: stub-
#   EXCLUDED .stub-title                                                  family not in approved set: stub-
#   EXCLUDED .stub-desc                                                   family not in approved set: stub-
#   EXCLUDED [data-theme^="retro"] .files-panel-header                    family not in approved set: files-
#   EXCLUDED .files-panel                                                 family not in approved set: files-
#   EXCLUDED [data-theme="basic-light"] .files-panel                      family not in approved set: files-
#   EXCLUDED [data-theme="basic-dark"] .files-panel                       family not in approved set: files-
#   EXCLUDED .files-panel.hidden                                          family not in approved set: files-
#   EXCLUDED .files-panel-header                                          family not in approved set: files-
#   EXCLUDED .widget-card .drag-handle                                    family not in approved set: drag-
#   EXCLUDED .widget-card.cta-card                                        family not in approved set: cta-
#   EXCLUDED .widget-card.error-card                                      family not in approved set: error-
#   EXCLUDED .orchestrator-buttons                                        family not in approved set: orchestrator-
#   EXCLUDED .orchestrator-buttons button                                 family not in approved set: orchestrator-
#   EXCLUDED .orchestrator-buttons button.primary                         family not in approved set: orchestrator-
#   EXCLUDED [data-theme="retro-dark"] .orchestrator-buttons button.prima family not in approved set: orchestrator-
#   EXCLUDED .orchestrator-buttons button.kill-btn                        family not in approved set: kill-+orchestrator-
#   EXCLUDED .preview-build-strip                                         family not in approved set: preview-
#   EXCLUDED .preview-build-strip a                                       family not in approved set: preview-
#   EXCLUDED [data-theme="basic-light"] .preview-build-strip a            family not in approved set: preview-
#   EXCLUDED [data-theme="basic-dark"] .preview-build-strip a             family not in approved set: preview-
#   EXCLUDED .widget-card .subagent-indicator                             family not in approved set: subagent-
#   EXCLUDED .progress-bar                                                family not in approved set: progress-
#   EXCLUDED .progress-bar .fill                                          family not in approved set: progress-
#   EXCLUDED [data-theme="basic-light"] .progress-bar .fill               family not in approved set: progress-
#   EXCLUDED [data-theme="basic-dark"] .progress-bar .fill                family not in approved set: progress-
#   EXCLUDED .donut-row                                                   family not in approved set: donut-
#   EXCLUDED .chat-modes                                                  family not in approved set: chat-
#   EXCLUDED .chat-modes .mode                                            family not in approved set: chat-
#   EXCLUDED .chat-modes .mode.active                                     family not in approved set: chat-
#   EXCLUDED [data-theme="retro-dark"] .chat-modes .mode.active           family not in approved set: chat-
#   EXCLUDED .chat-header-workflow                                        family not in approved set: chat-
#   EXCLUDED .state-badge                                                 family not in approved set: state-
#   EXCLUDED .state-badge.ready                                           family not in approved set: state-
#   EXCLUDED .state-badge.needs-setup                                     family not in approved set: state-
#   EXCLUDED .state-badge.logged-in                                       family not in approved set: state-
#   EXCLUDED .state-badge.validating                                      family not in approved set: state-
#   EXCLUDED .state-badge.auth-expired                                    family not in approved set: auth-+state-
#   EXCLUDED .state-badge.disconnected                                    family not in approved set: state-
#   EXCLUDED .confidence-badge                                            family not in approved set: confidence-
#   EXCLUDED .confidence-badge.authoritative                              family not in approved set: (no-dash)+confidence-
#   EXCLUDED .confidence-badge.estimated                                  family not in approved set: confidence-
#   EXCLUDED .confidence-badge.inferred                                   family not in approved set: confidence-
#   EXCLUDED .pressure-bar                                                family not in approved set: pressure-
#   EXCLUDED .pressure-bar-fill                                           family not in approved set: pressure-
#   EXCLUDED .pressure-bar-fill.healthy                                   family not in approved set: pressure-
#   EXCLUDED .pressure-bar-fill.warning                                   family not in approved set: pressure-
#   EXCLUDED .pressure-bar-fill.critical                                  family not in approved set: pressure-
#   EXCLUDED [data-theme^="retro"] .state-badge                           family not in approved set: state-
#   EXCLUDED .chat-new-thread-btn                                         family not in approved set: chat-
#   EXCLUDED .chat-input-area .input-row                                  family not in approved set: input-
#   EXCLUDED .chat-input-area .input-row button                           family not in approved set: input-
#   EXCLUDED .chat-input-area .input-row .at-btn                          family not in approved set: at-+input-
#   EXCLUDED .chat-input-area .input-row .attach-btn                      family not in approved set: attach-+input-
#   EXCLUDED .chat-queue-area                                             family not in approved set: chat-
#   EXCLUDED .chat-queue-area .queue-item                                 family not in approved set: chat-+queue-
#   EXCLUDED .chat-queue-area .queue-item .truncate                       family not in approved set: chat-+queue-
#   EXCLUDED .chat-queue-area .queue-item .actions                        family not in approved set: chat-+queue-
#   EXCLUDED .chat-queue-area .queue-item .actions a                      family not in approved set: chat-+queue-
#   EXCLUDED [data-theme="basic-light"] .chat-queue-area .queue-item .act family not in approved set: chat-+queue-
#   EXCLUDED [data-theme="basic-dark"] .chat-queue-area .queue-item .acti family not in approved set: chat-+queue-
#   EXCLUDED .chat-footer                                                 family not in approved set: chat-
#   EXCLUDED .chat-footer select                                          family not in approved set: chat-
#   EXCLUDED .chat-footer .context-usage                                  family not in approved set: chat-
#   EXCLUDED .chat-footer .context-progress                               family not in approved set: chat-+context-
#   EXCLUDED .chat-footer .context-progress.filled                        family not in approved set: chat-+context-
#   EXCLUDED [data-theme="basic-light"] .chat-footer .context-progress.fi family not in approved set: chat-+context-
#   EXCLUDED [data-theme="basic-dark"] .chat-footer .context-progress.fil family not in approved set: chat-+context-
#   EXCLUDED .chat-footer a                                               family not in approved set: chat-
#   EXCLUDED .chat-footer a:hover                                         family not in approved set: chat-
#   EXCLUDED .message-block                                               family not in approved set: message-
#   EXCLUDED .message-block.collapsed .block-body                         family not in approved set: block-+message-
#   EXCLUDED .message-block .block-header                                 family not in approved set: block-+message-
#   EXCLUDED .message-block .block-header:hover                           family not in approved set: block-+message-
#   EXCLUDED .message-block.collapsed .block-header::before               family not in approved set: block-+message-
#   EXCLUDED .message-block:not(.collapsed) .block-header::before         family not in approved set: block-+message-
#   EXCLUDED .message-block .block-body                                   family not in approved set: block-+message-
#   EXCLUDED .message-block .block-body pre                               family not in approved set: block-+message-
#   EXCLUDED .message-files-touched                                       family not in approved set: message-
#   EXCLUDED .message-files-touched a                                     family not in approved set: message-
#   EXCLUDED [data-theme="basic-light"] .message-files-touched a          family not in approved set: message-
#   EXCLUDED [data-theme="basic-dark"] .message-files-touched a           family not in approved set: message-
#   EXCLUDED .message-revert                                              family not in approved set: message-
#   EXCLUDED .message-revert:hover                                        family not in approved set: message-
#   EXCLUDED .steer-queue-toggle                                          family not in approved set: steer-
#   EXCLUDED .steer-queue-toggle span.active                              family not in approved set: steer-
#   EXCLUDED [data-theme="basic-light"] .steer-queue-toggle span.active   family not in approved set: steer-
#   EXCLUDED [data-theme="basic-dark"] .steer-queue-toggle span.active    family not in approved set: steer-
#   EXCLUDED .subagent-indicator                                          family not in approved set: subagent-
#   EXCLUDED .files-panel .files-search                                   family not in approved set: files-
#   EXCLUDED .files-search input                                          family not in approved set: files-
#   EXCLUDED [data-theme^="retro"] .files-search input                    family not in approved set: files-
#   EXCLUDED .files-status                                                family not in approved set: files-
#   EXCLUDED .pm-dock-pill                                                family not in approved set: pm-
#   EXCLUDED .pm-dock-pill.detached                                       family not in approved set: pm-
#   EXCLUDED .pm-identity-chip                                            family not in approved set: pm-
#   EXCLUDED .pm-identity-chip.copied                                     family not in approved set: pm-
#   EXCLUDED .pm-inspector-drawer.open                                    family not in approved set: pm-
#   EXCLUDED .pm-inspector-kv                                             family not in approved set: pm-
#   EXCLUDED .pm-inspector-kv span:first-child                            family not in approved set: pm-
#   EXCLUDED .pm-debug-grid                                               family not in approved set: pm-
#   EXCLUDED .pm-debug-cell h4                                            family not in approved set: pm-
#   EXCLUDED .pm-toast                                                    family not in approved set: pm-
#   EXCLUDED .status-bar .status-sep                                      family not in approved set: status-
#   EXCLUDED .status-bar .status-root                                     family not in approved set: status-
#   EXCLUDED .status-bar .status-git                                      family not in approved set: status-
#   EXCLUDED .status-bar .status-commit                                   family not in approved set: status-
#   EXCLUDED .status-bar .status-root:hover                               family not in approved set: status-
#   EXCLUDED .status-bar .status-git:hover                                family not in approved set: status-
#   EXCLUDED .status-bar .status-commit:hover                             family not in approved set: status-
#   EXCLUDED .floating-chat .float-title                                  family not in approved set: float-
#   EXCLUDED .floating-chat .float-title .close-float                     family not in approved set: close-+float-
#   EXCLUDED .wizard-global-nav                                           family not in approved set: wizard-
#   EXCLUDED .wizard-content-area                                         family not in approved set: wizard-
#   EXCLUDED .wizard-step-panel.exit-left                                 family not in approved set: exit-
#   EXCLUDED .wizard-fields                                               family not in approved set: wizard-
#   EXCLUDED .wizard-fields label                                         family not in approved set: wizard-
#   EXCLUDED .wizard-input                                                family not in approved set: wizard-
#   EXCLUDED .wizard-select                                               family not in approved set: wizard-
#   EXCLUDED [data-theme^="retro"] .wizard-input                          family not in approved set: wizard-
#   EXCLUDED [data-theme^="retro"] .wizard-select                         family not in approved set: wizard-
#   EXCLUDED .wizard-input:focus                                          family not in approved set: wizard-
#   EXCLUDED .wizard-select:focus                                         family not in approved set: wizard-
#   EXCLUDED [data-theme^="retro"] .wizard-input:focus                    family not in approved set: wizard-
#   EXCLUDED [data-theme^="retro"] .wizard-select:focus                   family not in approved set: wizard-
#   EXCLUDED .wizard-doc-status                                           family not in approved set: wizard-
#   EXCLUDED .wizard-doc-status.approved                                  family not in approved set: wizard-
#   EXCLUDED .wizard-doc-status.review                                    family not in approved set: wizard-
#   EXCLUDED .mock-md h1                                                  family not in approved set: mock-
#   EXCLUDED .mock-md h2                                                  family not in approved set: mock-
#   EXCLUDED .mock-md p                                                   family not in approved set: mock-
#   EXCLUDED .mock-md ul                                                  family not in approved set: mock-
#   EXCLUDED .mock-md li                                                  family not in approved set: mock-
#   EXCLUDED .annotation-drawer-header                                    family not in approved set: annotation-
#   EXCLUDED .context-menu-mock                                           family not in approved set: context-
#   EXCLUDED [data-theme^="retro"] .context-menu-mock                     family not in approved set: context-
#   EXCLUDED [data-theme^="glass"] .context-menu-mock                     family not in approved set: context-
#   EXCLUDED .ctx-item.submenu-label                                      family not in approved set: submenu-
#   EXCLUDED .ctx-item.submenu-label:hover                                family not in approved set: submenu-
#   EXCLUDED .ctx-item.indented                                           family not in approved set: (no-dash)
#   EXCLUDED .ctx-sep                                                     family not in approved set: ctx-
#   EXCLUDED .ctx-sep-label                                               family not in approved set: ctx-
#   EXCLUDED .remote-badge                                                family not in approved set: remote-
#   EXCLUDED .remote-badge.current                                        family not in approved set: remote-
#   EXCLUDED .remote-badge.stale                                          family not in approved set: remote-
#   EXCLUDED .remote-badge.refreshing                                     family not in approved set: remote-
#   EXCLUDED .remote-badge.healthy                                        family not in approved set: remote-
#   EXCLUDED .remote-badge.degraded                                       family not in approved set: remote-
#   EXCLUDED .remote-badge.unavailable                                    family not in approved set: remote-
#   EXCLUDED .remote-badge.writable                                       family not in approved set: (no-dash)+remote-
#   EXCLUDED .remote-badge.pending-write                                  family not in approved set: pending-+remote-
#   EXCLUDED .remote-badge.blocked                                        family not in approved set: remote-
#   EXCLUDED .remote-badge.read-only                                      family not in approved set: remote-
#   EXCLUDED [data-theme^="retro"] .remote-badge                          family not in approved set: remote-
#   EXCLUDED .search-match                                                family not in approved set: search-
#   EXCLUDED [data-theme$="light"] .search-match                          family not in approved set: search-
#   EXCLUDED .highlight-selection                                         family not in approved set: highlight-
#   EXCLUDED .browser-action-btn.active-tool                              family not in approved set: active-
#   EXCLUDED .screenshot-thumb                                            family not in approved set: screenshot-
#   EXCLUDED .screenshot-thumb .thumb-preview                             family not in approved set: screenshot-+thumb-
#   EXCLUDED .wizard-activity-floating                                    family not in approved set: wizard-
#   EXCLUDED [data-theme^="retro"] .wizard-activity-floating              family not in approved set: wizard-
#   EXCLUDED .wizard-activity-header                                      family not in approved set: wizard-
#   EXCLUDED .wizard-activity-item                                        family not in approved set: wizard-
#   EXCLUDED .wizard-activity-item .time                                  family not in approved set: wizard-
#   EXCLUDED .wizard-activity-controls                                    family not in approved set: wizard-
#   EXCLUDED .wizard-btn-row                                              family not in approved set: wizard-
#   EXCLUDED .wizard-btn-group                                            family not in approved set: wizard-
#   EXCLUDED .btn-icon                                                    family not in approved set: btn-
#   EXCLUDED .terminal-output .line-info                                  family not in approved set: line-
#   EXCLUDED .terminal-output .line-ok                                    family not in approved set: line-
#   EXCLUDED .terminal-output .line-muted                                 family not in approved set: line-
#   EXCLUDED [data-theme="basic-light"] .terminal-output .line-ok         family not in approved set: line-
#   EXCLUDED [data-theme="basic-dark"] .terminal-output .line-ok          family not in approved set: line-
#   EXCLUDED .settings-inspector-panel .details-content                   family not in approved set: details-
#   EXCLUDED .settings-inspector-panel .details-content label             family not in approved set: details-
#   EXCLUDED .settings-inspector-panel .details-content label input[type= family not in approved set: details-
#   EXCLUDED .settings-inspector-panel .details-content label:not(:has(in family not in approved set: details-
#   EXCLUDED .inspector-body .details-content                             family not in approved set: details-
#   EXCLUDED .inspector-body .details-content label                       family not in approved set: details-
#   EXCLUDED .inspector-body .details-content input[type="text"]          family not in approved set: details-
#   EXCLUDED .inspector-body .details-content input[type="password"]      family not in approved set: details-
#   EXCLUDED .inspector-body .details-content input[type="number"]        family not in approved set: details-
#   EXCLUDED .inspector-body .details-content select                      family not in approved set: details-
#   EXCLUDED .wizard-interview-container                                  family not in approved set: wizard-
#   EXCLUDED [data-theme^="retro"] .wizard-interview-container            family not in approved set: wizard-
#   EXCLUDED .panel-header                                                family not in approved set: panel-
#   EXCLUDED .files-search                                                family not in approved set: files-
#   EXCLUDED .search-input-wrap                                           family not in approved set: search-
#   EXCLUDED .search-input-wrap input                                     family not in approved set: search-
#   EXCLUDED .adv-search-btn                                              family not in approved set: adv-
#   EXCLUDED .adv-search-btn:hover                                        family not in approved set: adv-
#   EXCLUDED .advanced-search-panel                                       family not in approved set: advanced-
#   EXCLUDED .advanced-search-panel.open                                  family not in approved set: advanced-
#   EXCLUDED .adv-input-row                                               family not in approved set: adv-
#   EXCLUDED .adv-input-row input                                         family not in approved set: adv-
#   EXCLUDED .search-toggles                                              family not in approved set: search-
#   EXCLUDED .search-toggle                                               family not in approved set: search-
#   EXCLUDED .search-toggle.on                                            family not in approved set: search-
#   EXCLUDED [data-theme^="retro"] .search-toggle.on                      family not in approved set: search-
#   EXCLUDED .git-branch-select                                           family not in approved set: git-
#   EXCLUDED .unraid-select                                               family not in approved set: unraid-
#   EXCLUDED .commit-box                                                  family not in approved set: commit-
#   EXCLUDED .commit-box textarea                                         family not in approved set: commit-
#   EXCLUDED .ai-btn                                                      family not in approved set: ai-
#   EXCLUDED [data-theme^="retro"] .ai-btn                                family not in approved set: ai-
#   EXCLUDED .ai-btn:hover                                                family not in approved set: ai-
#   EXCLUDED [data-theme^="retro"] .ai-btn:hover                          family not in approved set: ai-
#   EXCLUDED .action-btn                                                  family not in approved set: action-
#   EXCLUDED .action-btn:hover                                            family not in approved set: action-
#   EXCLUDED [data-theme^="retro"] .action-btn:hover                      family not in approved set: action-
#   EXCLUDED .docker-container                                            family not in approved set: docker-
#   EXCLUDED .docker-status                                               family not in approved set: docker-
#   EXCLUDED .docker-status.stopped                                       family not in approved set: docker-
#   EXCLUDED .questionnaire-ui                                            family not in approved set: questionnaire-
#   EXCLUDED [data-theme^="retro"] .questionnaire-ui                      family not in approved set: questionnaire-
#   EXCLUDED .q-item                                                      family not in approved set: q-
#   EXCLUDED .q-item label                                                family not in approved set: q-
#   EXCLUDED .q-input                                                     family not in approved set: q-
#   EXCLUDED .q-actions                                                   family not in approved set: q-
#   EXCLUDED .chm-compact-btn.revealed                                    family not in approved set: (no-dash)
#   EXCLUDED .sa-work-stream .tool-call                                   family not in approved set: tool-
#   EXCLUDED .sa-work-stream .tool-result                                 family not in approved set: tool-
#   EXCLUDED .sa-state-block .state-label                                 family not in approved set: state-
#   EXCLUDED .sa-state-block.blocked-state .state-label                   family not in approved set: blocked-+state-
#   EXCLUDED .sa-result-block                                             family not in approved set: sa-
#   EXCLUDED .sa-elapsed                                                  family not in approved set: sa-
#   EXCLUDED .sa-batch-group-header .bg-chevron                           family not in approved set: bg-
#   EXCLUDED .sa-batch-group.expanded .bg-chevron                         family not in approved set: bg-
#   EXCLUDED .sa-batch-footer                                             family not in approved set: sa-
#   EXCLUDED .sa-crew-member-chip .member-dot                             family not in approved set: member-
#   EXCLUDED .sa-crew-member-chip .member-model                           family not in approved set: member-
#   EXCLUDED .sa-crew-msg .crew-author                                    family not in approved set: crew-
#   EXCLUDED .sa-crew-msg.from-architect .crew-author                     family not in approved set: crew-
#   EXCLUDED .sa-crew-msg.from-security .crew-author                      family not in approved set: crew-
#   EXCLUDED .sa-crew-msg.from-api .crew-author                           family not in approved set: crew-
#   EXCLUDED .sa-crew-msg.from-lead                                       family not in approved set: from-
#   EXCLUDED .sa-crew-msg.from-lead .crew-author                          family not in approved set: crew-+from-
#   EXCLUDED .sa-crew-synthesis .synth-title                              family not in approved set: synth-
#   EXCLUDED .sa-crew-confirmation .conf-title                            family not in approved set: conf-
#   EXCLUDED .sa-crew-member-row                                          family not in approved set: sa-
#   EXCLUDED .sa-crew-member-row:last-child                               family not in approved set: sa-
#   EXCLUDED .sa-crew-member-row .role-label                              family not in approved set: sa-
#   EXCLUDED .sa-crew-member-row .model-label                             family not in approved set: sa-
#   EXCLUDED .sc-wt-detail-field .field-label                             family not in approved set: field-
#   EXCLUDED .sc-wt-detail-field .field-value                             family not in approved set: field-
#   EXCLUDED .fm-wt-breadcrumb .fm-wt-icon                                family not in approved set: fm-
#   EXCLUDED .fm-wt-breadcrumb .fm-wt-branch                              family not in approved set: fm-
#   EXCLUDED .fm-wt-breadcrumb .fm-wt-swap                                family not in approved set: fm-
#   EXCLUDED .fm-wt-breadcrumb .fm-wt-swap:hover                          family not in approved set: fm-
#   EXCLUDED [data-theme^="retro"] .panel-header                          family not in approved set: panel-
#   EXCLUDED [data-theme^="retro"] .search-input-wrap input               family not in approved set: search-
#   EXCLUDED [data-theme^="retro"] .adv-search-btn                        family not in approved set: adv-
#   EXCLUDED [data-theme^="retro"] .git-branch-select                     family not in approved set: git-
#   EXCLUDED [data-theme^="retro"] .unraid-select                         family not in approved set: unraid-
#   EXCLUDED [data-theme^="retro"] .action-btn                            family not in approved set: action-
#   EXCLUDED [data-theme^="retro"] .adv-input-row input                   family not in approved set: adv-
#   EXCLUDED [data-theme^="retro"] .q-input                               family not in approved set: q-
#   EXCLUDED [data-theme^="retro"] .commit-box textarea                   family not in approved set: commit-
#   EXCLUDED [data-theme^="retro"] .files-panel .files-search             family not in approved set: files-
#   EXCLUDED .sticky-plan-tracker                                         family not in approved set: sticky-
#   EXCLUDED [data-theme^="retro"] .sticky-plan-tracker                   family not in approved set: sticky-
#   EXCLUDED .todo-status                                                 family not in approved set: todo-
#   EXCLUDED .todo-status.done                                            family not in approved set: todo-
#   EXCLUDED .todo-status.working                                         family not in approved set: todo-
#   EXCLUDED .gl-shimmer-overlay                                          family not in approved set: gl-
#   EXCLUDED .pm-page-in                                                  family not in approved set: pm-
#   EXCLUDED .pm-shake-subtle                                             family not in approved set: pm-
#   EXCLUDED .pm-celebrate                                                family not in approved set: pm-
#   EXCLUDED .pm-celebrate::after                                         family not in approved set: pm-
#   EXCLUDED [data-theme^="friendly"] .files-panel                        family not in approved set: files-
#   EXCLUDED [data-theme^="friendly"] .files-panel-header                 family not in approved set: files-
#   EXCLUDED [data-theme^="friendly"] .files-status                       family not in approved set: files-
#   EXCLUDED [data-theme^="friendly"] .chat-dropdown-search input         family not in approved set: chat-
#   EXCLUDED [data-theme^="retro"] .pm-toast                              family not in approved set: pm-
#   EXCLUDED [data-theme^="glass"] .pm-toast                              family not in approved set: pm-
#   EXCLUDED [data-theme^="basic"] .pm-toast                              family not in approved set: pm-
#   EXCLUDED [data-theme^="friendly"] .fm-wt-breadcrumb .fm-wt-branch     family not in approved set: fm-
#   EXCLUDED [data-theme^="friendly"] .fm-wt-breadcrumb .fm-wt-icon       family not in approved set: fm-
#   EXCLUDED [data-theme^="friendly"] .pm-toast                           family not in approved set: pm-
#   EXCLUDED .pm-toast.pm6-toast-out                                      family not in approved set: pm-
#   EXCLUDED [data-motion="reduced"] .pm-toast                            family not in approved set: pm-
#   EXCLUDED [data-motion="reduced"] .pm-toast.pm6-toast-out              family not in approved set: pm-
#   EXCLUDED .pm6-fm-search .wizard-input                                 family not in approved set: wizard-
#   EXCLUDED .pm6-search-qrow .wizard-input                               family not in approved set: wizard-
#   EXCLUDED .pm6-search-replacerow .wizard-input                         family not in approved set: wizard-
#   EXCLUDED .pm6-search-hit .search-match                                family not in approved set: search-
#   EXCLUDED .pm6-run-launchrow .wizard-select                            family not in approved set: wizard-
#   EXCLUDED .pm6-sc-commitrow .wizard-input                              family not in approved set: wizard-
#   EXCLUDED .pm-ico.lg                                                   family not in approved set: (no-dash)
#   EXCLUDED .dot-idle                                                    family not in approved set: dot-
#   EXCLUDED .pm-input-ico                                                family not in approved set: pm-
#   EXCLUDED .side-panel-slot[data-wtier="mid"] .cr-fam                   family not in approved set: cr-
#   EXCLUDED .side-panel-slot[data-wtier="mid"] .pt-fam                   family not in approved set: pt-
#   EXCLUDED .side-panel-slot[data-wtier="mid"] .sr-fam                   family not in approved set: sr-
#   EXCLUDED .side-panel-slot[data-wtier="mid"] .cr-r1 > .pm-chip         family not in approved set: cr-
#   EXCLUDED .ad-cttl                                                     family not in approved set: ad-
#   EXCLUDED .ad-rname                                                    family not in approved set: ad-
#   EXCLUDED .fm-regrow                                                   family not in approved set: fm-
#   EXCLUDED .fm-regrow:last-of-type                                      family not in approved set: fm-
#   EXCLUDED .fm-regname                                                  family not in approved set: fm-
#   EXCLUDED .fm-regstat                                                  family not in approved set: fm-
#   EXCLUDED .fm-regnote                                                  family not in approved set: fm-
#   EXCLUDED .sh-hstatus                                                  family not in approved set: sh-
#   EXCLUDED .sh-hstatus .dot                                             family not in approved set: sh-
#   EXCLUDED .sh-rowact                                                   family not in approved set: sh-
#   EXCLUDED .fm-emptytree                                                family not in approved set: fm-

DEAD_SELECTORS = [
    ".pm6-sp-btn-primary",
    '.artifact-actions',
    '.artifact-btn',
    '.artifact-btn:hover',
    '.artifact-item',
    '.artifact-item:hover',
    '.artifact-meta',
    '.bento-desc',
    '.bento-grid',
    '.bento-header',
    '.bento-icon',
    '.bento-surface',
    '.bento-surface input[type="number"]',
    '.bento-surface input[type="password"]',
    '.bento-surface input[type="text"]',
    '.bento-surface label',
    '.bento-surface select',
    '.bento-surface.row',
    '.bento-widget:hover .widget-settings',
    '.chat-dropdown-popover.active .pm6-has-pt.active > .pm6-chat-pt-flyout',
    '.chat-dropdown-popover.active .pm6-has-pt:hover > .pm6-chat-pt-flyout',
    '.inspector-body details',
    '.inspector-body summary',
    '.inspector-layout-masonry details',
    '.inspector-layout-masonry summary',
    '.interview-chat-area',
    '.interview-chat-header',
    '.interview-chip',
    '.interview-chip:hover',
    '.interview-chips',
    '.interview-input-area',
    '.interview-messages',
    '.interview-sidebar',
    '.interview-sidebar-title',
    '.interview-text-input',
    '.interview-text-input input',
    '.message.msg-focused .msg-body',
    '.msg-ai',
    '.msg-bubble',
    '.msg-user',
    '.orch-cta-item',
    '.orch-cta-list',
    '.orch-cta-muted',
    '.orch-dag',
    '.orch-dag-edge',
    '.orch-dag-node',
    '.orch-dag-preview',
    '.orch-dag-row',
    '.orch-dag-title',
    '.orch-evidence-detail',
    '.orch-evidence-detail-actions',
    '.orch-evidence-detail-body',
    '.orch-evidence-layout',
    '.orch-evidence-main',
    '.orch-evidence-row',
    '.orch-evidence-row.selected',
    '.orch-evidence-row:hover',
    '.orch-filter',
    '.orch-history-row',
    '.orch-history-row:hover',
    '.orch-history-toolbar span',
    '.orch-ledger-footer',
    '.orch-ledger-footer td',
    '.orch-ledger-toolbar span',
    '.orch-ledger-usage-link',
    '.orch-node-graph-wrap',
    '.orch-progress-grid',
    '.orch-progress-label',
    '.orch-progress-row',
    '.orch-progress-row:last-child',
    '.orch-prose-badge',
    '.orch-prose-block',
    '.orch-prose-block-body',
    '.orch-prose-block-head',
    '.orch-prose-block-head::before',
    '.orch-prose-block.collapsed .orch-prose-block-body',
    '.orch-prose-block.collapsed .orch-prose-block-head::before',
    '.orch-prose-dur',
    '.orch-prose-failed',
    '.orch-prose-list',
    '.orch-prose-meta',
    '.orch-prose-passed',
    '.orch-prose-toggle',
    '.orch-prose-toggle.active',
    '.orch-prose-toggle[aria-pressed="true"]',
    '.orch-prose-toolbar',
    '.orch-rungraph-body',
    '.orch-rungraph-canvas',
    '.orch-rungraph-counts',
    '.orch-rungraph-date',
    '.orch-rungraph-detail',
    '.orch-rungraph-detail-body',
    '.orch-rungraph-detail-section',
    '.orch-rungraph-detail-section-body',
    '.orch-rungraph-detail-section-body p',
    '.orch-rungraph-detail-section-head',
    '.orch-rungraph-detail-section-head::before',
    '.orch-rungraph-detail-section.collapsed .orch-rungraph-detail-section-body',
    '.orch-rungraph-detail-section.collapsed .orch-rungraph-detail-section-head::before',
    '.orch-rungraph-detail-title',
    '.orch-rungraph-edges',
    '.orch-rungraph-elapsed',
    '.orch-rungraph-empty',
    '.orch-rungraph-filter',
    '.orch-rungraph-fit',
    '.orch-rungraph-graph-content',
    '.orch-rungraph-layout',
    '.orch-rungraph-left',
    '.orch-rungraph-minimap',
    '.orch-rungraph-minimap-dot',
    '.orch-rungraph-minimap-dot.graph-failed',
    '.orch-rungraph-minimap-dot.graph-passed',
    '.orch-rungraph-minimap-dot.graph-pending',
    '.orch-rungraph-minimap-dot.graph-running',
    '.orch-rungraph-minimap-nodes',
    '.orch-rungraph-minimap-viewport',
    '.orch-rungraph-node-attempt',
    '.orch-rungraph-node-badge',
    '.orch-rungraph-node-blocked',
    '.orch-rungraph-node-hitl',
    '.orch-rungraph-node-line1',
    '.orch-rungraph-node-line2',
    '.orch-rungraph-node-line3',
    '.orch-rungraph-node-meta',
    '.orch-rungraph-node-state',
    '.orch-rungraph-node-state-icon',
    '.orch-rungraph-node-title',
    '.orch-rungraph-node-type',
    '.orch-rungraph-qf',
    '.orch-rungraph-qf:hover',
    '.orch-rungraph-quickfilters',
    '.orch-rungraph-right',
    '.orch-rungraph-runid',
    '.orch-rungraph-search',
    '.orch-rungraph-status-badge',
    '.orch-rungraph-table',
    '.orch-rungraph-table td',
    '.orch-rungraph-table th',
    '.orch-rungraph-table-wrap',
    '.orch-rungraph-times',
    '.orch-rungraph-toggle',
    '.orch-rungraph-toggle:hover',
    '.orch-rungraph-toggles',
    '.orch-rungraph-topbar',
    '.orch-rungraph-topbar-footer',
    '.orch-rungraph-usage-link',
    '.orch-rungraph-zoom',
    '.orch-rungraph-zoom-indicator',
    '.orch-rungraph-zoom-pct',
    '.orch-search',
    '.orch-state-failed',
    '.orch-state-passed',
    '.orch-state-pending',
    '.orch-state-running',
    '.orch-table',
    '.orch-table td',
    '.orch-table th',
    '.orch-terminal-clear',
    '.orch-terminal-clear:hover',
    '.orch-toolbar',
    '.page-settings .bento-grid',
    '.plan-card',
    '.plan-card .plan-outline',
    '.plan-card .plan-outline li',
    '.plan-card .plan-title',
    '.plan-todo-item',
    '.plan-todo-item:last-child',
    '.pm6-ab-bell',
    '.pm6-ab-dot',
    '.pm6-ab-dot.pm6-hidden',
    '.pm6-acc-meta',
    '.pm6-agent-name',
    '.pm6-agent-row',
    '.pm6-agent-row .pm6-chip',
    '.pm6-agent-row:last-of-type',
    '.pm6-ai-spin',
    '.pm6-ai-spin.active',
    '.pm6-art-bundle-chips',
    '.pm6-art-filters',
    '.pm6-bp-dot',
    '.pm6-chat-headstats',
    '.pm6-chat-modesearch',
    '.pm6-chat-modesearch input',
    '.pm6-chat-modesearch input::placeholder',
    '.pm6-chat-modesearch svg',
    '.pm6-chat-notice-error',
    '.pm6-chat-pt-flyout',
    '.pm6-cyclable',
    '.pm6-dim',
    '.pm6-dm-chain',
    '.pm6-dm-runtime',
    '.pm6-dm-stage',
    '.pm6-dm-stage + .pm6-dm-stage::before',
    '.pm6-dm-stage .pm6-chip',
    '.pm6-dm-stage-dot',
    '.pm6-dm-stage-label',
    '.pm6-dm-stage.done .pm6-dm-stage-dot',
    '.pm6-flagbtn',
    '.pm6-flex1',
    '.pm6-fm-chev',
    '.pm6-fm-crumb',
    '.pm6-fm-rootbtn',
    '.pm6-fm-rootdd',
    '.pm6-fm-rootdd.active',
    '.pm6-fm-rootitem',
    '.pm6-fm-rootitem:hover',
    '.pm6-fm-rootmeta',
    '.pm6-fm-rootname',
    '.pm6-fm-search',
    '.pm6-fm-sep',
    '.pm6-fm-tree',
    '.pm6-focus-ring:focus-visible',
    '.pm6-g-lane',
    '.pm6-g-main',
    '.pm6-g-thread',
    '.pm6-gh-device',
    '.pm6-gh-device .pm6-gh-code',
    '.pm6-gh-device.active',
    '.pm6-gh-log',
    '.pm6-gh-triage',
    '.pm6-gh-triage-head',
    '.pm6-graph-dot',
    '.pm6-graph-line',
    '.pm6-ind1',
    '.pm6-ind2',
    '.pm6-kv',
    '.pm6-kv-k',
    '.pm6-kv-v',
    '.pm6-mb-sm',
    '.pm6-mode-pt-hint',
    '.pm6-mt-sm',
    '.pm6-orch-gsvg .pm6-orch-gpulse',
    '.pm6-run-launchrow',
    '.pm6-sc-commit',
    '.pm6-sc-commit-top',
    '.pm6-sc-commit:hover',
    '.pm6-sc-commitrow',
    '.pm6-sc-graph',
    '.pm6-search-count',
    '.pm6-search-file',
    '.pm6-search-file:hover',
    '.pm6-search-flags',
    '.pm6-search-indent',
    '.pm6-search-index .pm6-kv',
    '.pm6-search-ln',
    '.pm6-search-note',
    '.pm6-search-qrow',
    '.pm6-search-replacerow',
    '.pm6-search-results',
    '.pm6-search-scope',
    '.pm6-sha',
    '.pm6-sp-btn',
    '.pm6-sp-btn:active',
    '.pm6-sp-btn:hover',
    '.pm6-sp-btn[aria-disabled="true"]',
    '.pm6-sp-btn[aria-disabled="true"]:hover',
    '.pm6-sp-btn[data-demo-disabled]',
    '.pm6-sp-btn[disabled]',
    '.pm6-sp-card',
    '.pm6-sp-card-head',
    '.pm6-sp-card-meta',
    '.pm6-sp-content',
    '.pm6-sp-header',
    '.pm6-sp-iconbtn',
    '.pm6-sp-iconbtn:hover',
    '.pm6-status-caret',
    '.pm6-status-ctx',
    '.pm6-status-ctx-bar',
    '.pm6-status-ctx-fill',
    '.pm6-status-ctx-fill.pm6-ctx-warn',
    '.pm6-status-ctx-label',
    '.pm6-status-mode',
    '.pm6-status-pop-item',
    '.pm6-status-pop-item.active',
    '.pm6-status-pop-item:hover',
    '.pm6-status-pop-note',
    '.pm6-subagent-status-done',
    '.pm6-subagent-status-failed',
    '.pm6-subagent-status-waiting',
    '.pm6-w100',
    '.pm6-warn-note',
    '.pm6-wiz-draftchip',
    '.pm6-wiz-freeform',
    '.pm6-wiz-freeform:focus',
    '.pm6-wiz-msg',
    '.pm6-wiz-msg-av',
    '.pm6-wiz-msg-body',
    '.pm6-wiz-msg-note',
    '.pm6-wiz-msg-note .pm6-wiz-glyph',
    '.pm6-wiz-msg.agent',
    '.pm6-wiz-msg.user',
    '.pm6-wiz-msg.user .pm6-wiz-msg-body',
    '.pm6-wiz-q',
    '.pm6-wiz-q-flags',
    '.pm6-wiz-q-help',
    '.pm6-wiz-q-num',
    '.pm6-wiz-q-text',
    '.pm6-wiz-q-toprow',
    '.pm6-wt-branch',
    '.pm6-wt-chev',
    '.pm6-wt-detail .pm6-kv',
    '.pm6-wt-head',
    '.pm6-wt-owner',
    '.sc-accordion',
    '.sc-accordion-header',
    '.sc-accordion-header .sc-badge-count',
    '.sc-accordion-header .sc-chevron',
    '.sc-accordion-header:hover',
    '.sc-accordion-section',
    '.sc-accordion-section.open > .sc-accordion-body',
    '.sc-accordion-section.open > .sc-accordion-header .sa-chevron',
    '.sc-accordion-section.sc-open > .sc-accordion-body',
    '.sc-accordion-section.sc-open > .sc-accordion-header .sc-chevron',
    '.sc-graph-view',
    '.sc-history-entry',
    '.sc-history-entry:hover',
    '.sc-history-hash',
    '.sc-history-meta',
    '.sc-history-msg',
    '.sc-wt-action-btns',
    '.sc-wt-action-btns button',
    '.sc-wt-branch',
    '.sc-wt-detail',
    '.sc-wt-detail-field',
    '.sc-wt-line1',
    '.sc-wt-line2',
    '.sc-wt-owner',
    '.sc-wt-row.expanded .pm6-wt-chev',
    '.sc-wt-row.expanded .sc-wt-detail',
    '.sc-wt-row.sc-wt-expanded .pm6-wt-chev',
    '.sc-wt-row.sc-wt-expanded .sc-wt-detail',
    '.settings-inspector-panel .inspector-body',
    '.settings-inspector-panel .inspector-header',
    '.terminal-output',
    '.terminal-output .line',
    '.terminal-output .line.info',
    '.terminal-output .line.stderr',
    # DROPPED rev 9: the rule this named ('.terminal-output,
    # .terminal-pane-body { ::-webkit-scrollbar { display:none } }') was
    # deleted upstream when the terminal was given the standard scrollbar --
    # it is gone from the base, so T01 can no longer find it to remove.
    '.terminal-pane-toolbar',
    '.terminal-pane-wrap',
    '.terminal-section',
    '.terminal-section-header',
    '.terminal-section-title',
    '.terminal-tab',
    '.terminal-tab.active',
    '.terminal-tab.pinned::after',
    '.terminal-tab:hover',
    '.terminal-tabbar-actions',
    '.terminal-tabstrip',
    '.terminal-tabstrip::-webkit-scrollbar',
    '.widget-card',
    '.widget-card .widget-title',
    '.widget-header',
    '.widget-settings',
    '.widget-settings:hover',
    '.widget-title',
    '[data-motion="reduced"] .pm6-ai-spin',
    '[data-motion="reduced"] .pm6-status-ctx-fill',
    '[data-theme="basic-dark"] .widget-card',
    '[data-theme="basic-light"] .widget-card',
    '[data-theme="retro-dark"] .orch-ledger-usage-link',
    '[data-theme="retro-light"] .orch-ledger-usage-link',
    '[data-theme^="basic"] .message.msg-focused .msg-body',
    '[data-theme^="friendly"] .pm6-chat-modesearch',
    '[data-theme^="friendly"] .pm6-chat-modesearch input',
    '[data-theme^="friendly"] .pm6-focus-ring:focus-visible',
    '[data-theme^="friendly"] .pm6-sp-btn',
    '[data-theme^="friendly"] .pm6-sp-card',
    '[data-theme^="friendly"] .pm6-wt-branch',
    '[data-theme^="friendly"] .sc-wt-branch',
    '[data-theme^="friendly"] .widget-card',
    '[data-theme^="glass"] .interview-chip',
    '[data-theme^="glass"] .interview-chip:hover',
    '[data-theme^="glass"] .message.msg-focused .msg-body',
    '[data-theme^="glass"] .pm6-fm-rootdd',
    '[data-theme^="glass"] .pm6-sp-card',
    '[data-theme^="glass"] .pm6-wiz-msg-body',
    '[data-theme^="glass"] .pm6-wiz-q',
    '[data-theme^="glass"] .terminal-pane-toolbar',
    '[data-theme^="retro"] .artifact-btn:hover',
    '[data-theme^="retro"] .artifact-item:hover',
    '[data-theme^="retro"] .bento-surface input[type="number"]',
    '[data-theme^="retro"] .bento-surface input[type="password"]',
    '[data-theme^="retro"] .bento-surface input[type="text"]',
    '[data-theme^="retro"] .bento-surface select',
    '[data-theme^="retro"] .interview-chip',
    '[data-theme^="retro"] .interview-chip:hover',
    '[data-theme^="retro"] .interview-text-input input',
    '[data-theme^="retro"] .msg-bubble',
    '[data-theme^="retro"] .msg-user',
    '[data-theme^="retro"] .pm6-fm-rootdd',
    '[data-theme^="retro"] .pm6-sp-btn',
    '[data-theme^="retro"] .pm6-sp-card',
    '[data-theme^="retro"] .pm6-status-ctx-bar',
    '[data-theme^="retro"] .pm6-status-ctx-fill',
    '[data-theme^="retro"] .pm6-wiz-msg-body',
    '[data-theme^="retro"] .pm6-wiz-q',
    '[data-theme^="retro"] .sc-accordion-header',
    '[data-theme^="retro"] .terminal-section-title',
    '[data-theme^="retro"] .widget-title',
]
