#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json,os,sys
from pathlib import Path
BASE=Path(__file__).resolve().parent;NS=BASE.parents[1];sys.path.insert(0,str(NS/'tools'));sys.path.insert(0,str(BASE))
import common,result_validator_v7_2 as RV
ACT={'core':'043488cb83d6064068a887d484f22d19d6c158a2bc1d424798ed9611c9f58c83','ER-0003':'a0cf53b81fe654c3cc460682da7ae6ae28dc6cca90d8e0f338258d596bc4e5c8','ER-0008':'34b9261297844b43aba855bed802a56f06f68596f81fc51295322a6bfd9e31f1','envelope':'3dab3e76f915889be2c65710477ab1c860f42d57d34d836a3311bd93255ab406'}
EMB={'core':'a12b9b867532f5ed887fe44fbdabfd530a603cdef2ddae1a53cb74f8e99b0b88','ER-0003':'455b640d680f85b0d0d23622f87ca79ecfa34d49b8728bf549656b80a52f833b','ER-0008':'d8d8a035f4f8f6b0951993de39aa0511396e412ec15932f46defeec6c54bce40'}
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(p,v):
 raw=(json.dumps(v,indent=2,sort_keys=True)+'\n').encode();fd=os.open(p,os.O_WRONLY|os.O_CREAT|os.O_EXCL,0o444)
 with os.fdopen(fd,'wb') as f:f.write(raw)
def main():
 old=json.loads((NS/'validation/receipt-closure-v7_1/external_research_dispatch_receipt_v7_1.schema.json').read_text());old['properties']['schema_version']={'const':'external-research-dispatch-receipt-v7.2'}
 additions=['activation_core_file_sha256','activation_core_object_canonical_sha256','activation_core_historical_embedded_pre_final_canonical_sha256','leaf_dispatch_authorization_file_sha256','leaf_dispatch_authorization_object_canonical_sha256','leaf_dispatch_authorization_historical_embedded_pre_final_canonical_sha256','activation_envelope_file_sha256','activation_envelope_object_canonical_sha256','isolated_result_validator_sha256']
 for k in additions:old['properties'][k]={'type':'string','pattern':'^[0-9a-f]{64}$'}
 old['properties']['digest_semantics_version']={'const':'raw-file-and-canonical-object-explicit-v7.2'};old['properties']['stale_common_result_errors_called']={'const':False};old['required']+=additions+['digest_semantics_version','stale_common_result_errors_called'];write(BASE/'external_research_dispatch_receipt_v7_2.schema.json',old)
 leaf={'type':'object','additionalProperties':False,'required':['assignment_id','agent_path','native_child_thread_id','native_child_turn_id','terminal_response_exact','result_file_sha256','result_object_canonical_sha256','receipt_file_sha256','receipt_object_canonical_sha256','output_tree_sha256','activation_core_file_sha256','activation_core_object_canonical_sha256','leaf_dispatch_authorization_file_sha256','leaf_dispatch_authorization_object_canonical_sha256'],'properties':{k:{'type':'string'} for k in ['assignment_id','agent_path','native_child_thread_id','native_child_turn_id','terminal_response_exact','result_file_sha256','result_object_canonical_sha256','receipt_file_sha256','receipt_object_canonical_sha256','output_tree_sha256','activation_core_file_sha256','activation_core_object_canonical_sha256','leaf_dispatch_authorization_file_sha256','leaf_dispatch_authorization_object_canonical_sha256']}}
 cap={'$schema':'https://json-schema.org/draft/2020-12/schema','type':'object','additionalProperties':False,'required':['schema_version','attempt_id','controller_thread_id','assignment_count','native_state_path','native_state_file_sha256','digest_semantics_version','leaves','coverage_credit','research_credit','promotion_credit','spec_credit','merge_credit'],'properties':{'schema_version':{'const':'external-research-native-capture-v7.2'},'attempt_id':{'const':'attempt-0007'},'controller_thread_id':{'type':'string'},'assignment_count':{'const':2},'native_state_path':{'type':'string'},'native_state_file_sha256':{'type':'string'},'digest_semantics_version':{'const':'raw-file-and-canonical-object-explicit-v7.2'},'leaves':{'type':'array','minItems':2,'maxItems':2,'items':leaf},'coverage_credit':{'const':0},'research_credit':{'const':0},'promotion_credit':{'const':0},'spec_credit':{'const':0},'merge_credit':{'const':0}}};write(BASE/'external_research_native_capture_v7_2.schema.json',cap)
 manifest=common.load(NS/'manifest.json');repro={}
 for row in manifest['assignments']:
  aid=row['assignment_id'];core=common.load(common.core_path());auth=common.load(common.authorization_path(aid));raw=common.result_path(aid).read_bytes();_,_,_,old_errors=common.validate_result_buffer(raw,row,core,auth);_,_,_,new_errors=RV.validate_result_buffer_v7_2(raw,row,core,auth,ACT['core'],ACT[aid]);repro[aid]={'old_common_errors':old_errors,'new_isolated_errors':new_errors,'result_file_sha256':common.sha_bytes(raw)}
 authority={'schema_version':'external-research-receipt-closure-authority-v7.2','status':'PREPARED_AWAITING_TESTS','actual_file_sha256':ACT,'historical_embedded_pre_final_canonical_sha256':EMB,'prior_v7_1_terminal_report_sha256':'e860585f7d5a296e39dffd3192d7982a46c903d7f411b83c4ba59f90efc14689','prior_failures_preserved':True,'failure_reproduction':repro,'result_validator_sha256':sha(BASE/'result_validator_v7_2.py'),'receipt_writer_sha256':sha(BASE/'write_positive_receipt_v7_2.py'),'capture_writer_sha256':sha(BASE/'write_native_capture_v7_2.py'),'receipt_schema_sha256':sha(BASE/'external_research_dispatch_receipt_v7_2.schema.json'),'capture_schema_sha256':sha(BASE/'external_research_native_capture_v7_2.schema.json'),'production_receipts':0,'production_capture_rows':0,'credits':0};write(BASE/'authority-v7_2.json',authority);print(json.dumps({'authority_sha256':sha(BASE/'authority-v7_2.json'),'failure_reproduction':repro},indent=2,sort_keys=True))
if __name__=='__main__':main()
