async function advance(slot,arm,previous,next){
const R="ER12_RUNTIME",q=s=>"'"+s.replaceAll("'","'\\''")+"'",un=eval("("+load("unpackSource")+")"),list=load("candidateTasks");
const t=list.find(t=>t.slot===slot&&t.arm===arm&&t.stage===previous);if(!t)throw new Error("missing original task");
const raw=await tools.mcp__t3_code__task_status({taskId:t.taskId});Object.assign(t,un(raw));text({slot,arm,stage:previous,status:t.status,summary:t.summary});store("candidateTasks",list);
if(t.status!=="completed"||t.hasPendingChildRuns)return;await tools.mcp__t3_code__t3_thread_organize({action:"settle",threadId:t.childThreadId});
const H=t.helper||load("screenHelper"),config=R+"/configs/"+slot+"-"+arm+".json";
const rec=await tools.exec_command({cmd:"python3 -B "+H+"/prepare.py record-status --config "+config+" --stage "+previous+" --json "+q(JSON.stringify(un(raw))),max_output_tokens:30});if(rec.exit_code!==0){text(rec);return}
const res=await tools.exec_command({cmd:"python3 - "+q(slot)+" "+q(arm)+" "+q(next)+" <<'PY'\nimport pathlib,json,sys,datetime\np=pathlib.Path('"+R+"/mechanics/QUEUE.json');q=json.loads(p.read_text());s=next(x for x in q['slots'] if x['slot_id']==sys.argv[1]);a=next(x for x in s['arms'] if x['arm_id']==sys.argv[1]+'/'+sys.argv[2]);a['state']='RESERVED';a['reservation']={'at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'stage':sys.argv[3],'route':'authorized_codex','model':'gpt-6-luna','effort':'max','tier':'default'};p.write_text(json.dumps(q,indent=2)+'\\n')\nPY",max_output_tokens:100});if(res.exit_code!==0){text(res);return}
const p=await tools.exec_command({cmd:"python3 -B "+H+"/prepare.py prepare --config "+config+" --stage "+next,max_output_tokens:9500});if(p.exit_code!==0){text({slot,arm,error:p.output});return}let spec=await eval("("+load("clarifySpecJS")+")")(await eval("("+load("standardSpecJS")+")")(JSON.parse(p.output)));spec=await eval("("+load("exactSpecJS")+")")(spec,slot);if(spec.alreadyDispatched){text({slot,arm,alreadyDispatched:true});return}
const mem=await tools.exec_command({cmd:"free -g",max_output_tokens:200});const avail=Number(mem.output.split("\n").find(x=>/^Mem:/.test(x))?.trim().split(/\s+/).at(-1));if(avail<6){text({blockedMemory:avail,slot,arm});return}
const dispatched=await tools.mcp__t3_code__delegate_task(spec.args),u=un(dispatched);list.push({slot,arm,stage:next,helper:H,...u});store("candidateTasks",list);text({slot,arm,stage:next,taskId:u.taskId,status:u.status});const rr=await tools.exec_command({cmd:"python3 -B "+H+"/prepare.py record --config "+config+" --stage "+next+" --json "+q(JSON.stringify(dispatched)),max_output_tokens:30});if(rr.exit_code!==0)text(rr);
}
