async function startRole(slot){
const R="ER12_RUNTIME",H=R+"/helpers/role-v2",q=s=>"'"+s.replaceAll("'","'\\''")+"'",un=eval("("+load("unpackSource")+")"),list=load("candidateTasks"),start=new Date().toISOString();
const res=await tools.exec_command({cmd:"python3 - "+q(slot)+" "+q(start)+" <<'PY'\nfrom pathlib import Path\nimport json,sys\nr=Path('"+R+"');p=r/'mechanics/QUEUE.json';Q=json.loads(p.read_text());s=next(x for x in Q['slots'] if x['slot_id']==sys.argv[1]);f=json.loads((r/'role-cases-v2'/sys.argv[1]/'fixture.json').read_text())\nfor arm in ['control','treatment']:\n a=next(a for a in s['arms'] if a['arm_id']==sys.argv[1]+'/'+arm);assert not a.get('task_id');a.update(state='RESERVED',reservation={'at':sys.argv[2],'stage':'role','route':'authorized_codex' if arm=='control' else f[arm]['provider'],'effort':'max','tier':'default' if arm=='control' else 'vendor_unspecified'})\ns['state']='ACTIVE';p.write_text(json.dumps(Q,indent=2)+'\\n')\nPY",max_output_tokens:100});if(res.exit_code!==0)throw Error(res.output);
const order=slot.endsWith("02")?["treatment","control"]:["control","treatment"];
for(const arm of order){const p=await tools.exec_command({cmd:"python3 -B "+H+"/prepare-role.py prepare --slot "+slot+" --arm "+arm+" --fixture "+R+"/role-cases-v2/"+slot+"/fixture.json --started-at-utc "+q(start),max_output_tokens:10000});if(p.exit_code!==0){text(p);continue}const spec=await eval("("+load("clarifySpecJS")+")")(await eval("("+load("standardSpecJS")+")")(JSON.parse(p.output)));if(spec.alreadyDispatched){text({already:slot,arm});continue}
const mem=await tools.exec_command({cmd:"free -g",max_output_tokens:100});if(Number(mem.output.split("\n").find(x=>/^Mem:/.test(x)).trim().split(/\s+/).at(-1))<6)throw Error("memory under6");
const raw=await tools.mcp__t3_code__delegate_task(spec.args),u=un(raw);list.push({slot,arm,stage:"role",helper:H,...u});store("candidateTasks",list);text({slot,arm,taskId:u.taskId,status:u.status});
await tools.exec_command({cmd:"python3 - "+q(JSON.stringify(raw))+" "+q(spec.stageDir)+" <<'PY'\nfrom pathlib import Path\nimport sys,json\n(Path(sys.argv[2])/'raw-dispatch.json').write_text(json.dumps(json.loads(sys.argv[1]),indent=2)+'\\n')\nPY",max_output_tokens:80});
const rec=await tools.exec_command({cmd:"python3 -B "+H+"/prepare-role.py record --slot "+slot+" --arm "+arm+" --json-file "+spec.stageDir+"/raw-dispatch.json",max_output_tokens:80});if(rec.exit_code!==0)text(rec)
}
}
