"""Compose kit.d/21-nier-scenes.js from the NieR Mode scene SVGs and the hand-written layer logic.

Sources (the truth): src/settings/nier/scenes/<key>.svg for key in city, bunker, desert, forest, park, flooded, and
src/settings/nier/scenes/layer.js. Output: src/settings/kit.d/21-nier-scenes.js, which the Settings build composes
with every other kit.d file (tools/settings_layer.py). Never edit the output; edit a source and run --write.

  python3 tools/nier_scenes.py --write   # validate the SVGs and write the kit file
  python3 tools/nier_scenes.py --check   # validate, and fail when the kit file is stale

Each SVG is checked for what the layer and Slint 1.18.1 can carry: one ink (currentColor) plus the ground knockout
class, plain shapes and groups only (no filter, mask, clip path, gradient, pattern, image, text, style or script), no
blend modes, the shared viewBox, and at most MAX_KB. The embedded copy drops the <title> and line breaks.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

PKG = Path(__file__).resolve().parent.parent
SRC = PKG / 'src' / 'settings' / 'nier' / 'scenes'
OUT = PKG / 'src' / 'settings' / 'kit.d' / '21-nier-scenes.js'
KEYS = ['city', 'bunker', 'desert', 'forest', 'park', 'flooded']
VIEWBOX = '0 0 1600 560'
MAX_KB = 40
ALLOWED_TAGS = {'svg', 'title', 'path', 'g', 'rect', 'circle', 'ellipse', 'line', 'polyline', 'polygon'}
FORBIDDEN_ATTRS = re.compile(r'\b(filter|mask|clip-path|mix-blend-mode|style|href|xlink:href)\s*=', re.I)
COLOR_ATTR = re.compile(r'\b(fill|stroke)="([^"]*)"')


def problems(key: str, text: str) -> list[str]:
    out = []
    size = len(text.encode('utf-8'))
    if size > MAX_KB * 1024:
        out.append(f'{key}.svg is {size / 1024:.1f} KB (limit {MAX_KB} KB)')
    for tag in set(re.findall(r'<([a-zA-Z][\w:-]*)', text)):
        if tag not in ALLOWED_TAGS:
            out.append(f'{key}.svg uses <{tag}> (plain shapes and groups only)')
    if FORBIDDEN_ATTRS.search(text):
        out.append(f'{key}.svg uses {FORBIDDEN_ATTRS.search(text).group(1)} (not portable to Slint 1.18.1)')
    for attr, val in COLOR_ATTR.findall(text):
        if val not in ('none', 'currentColor'):
            out.append(f'{key}.svg sets {attr}="{val}" (one ink: currentColor, or the ground knockout class k)')
            break
    cls = set(re.findall(r'class="([^"]*)"', text)) - {'o55-nier-art', 'k'}
    anim = {c for c in cls if re.fullmatch(r'a-[a-z0-9-]+', c)}
    if cls - anim:
        out.append(f'{key}.svg uses class {sorted(cls - anim)} (only o55-nier-art, k and a-* motion hooks)')
    if f'viewBox="{VIEWBOX}"' not in text:
        out.append(f'{key}.svg must use viewBox="{VIEWBOX}"')
    if f'data-scene="{key}"' not in text:
        out.append(f'{key}.svg must carry data-scene="{key}"')
    return out


def embed(text: str) -> str:
    text = re.sub(r'<title>.*?</title>', '', text, flags=re.S)
    return re.sub(r'\s*\n\s*', '', text).strip()


def compose() -> tuple[str, list[str]]:
    errs, table = [], {}
    for key in KEYS:
        path = SRC / f'{key}.svg'
        if not path.exists():
            continue
        text = path.read_text(encoding='utf-8')
        errs += problems(key, text)
        table[key] = embed(text)
    if not table:
        errs.append('no scene SVGs found in src/settings/nier/scenes')
    layer = (SRC / 'layer.js').read_text(encoding='utf-8')
    head = ('/* GENERATED by tools/nier_scenes.py from src/settings/nier/scenes/*.svg and layer.js. Do not edit; edit a '
            'source and run\n   python3 Concepts/onboarding/opus-5.5/tools/nier_scenes.py --write */\n')
    rows = ',\n'.join(f'  {k}: {json.dumps(v, ensure_ascii=False)}' for k, v in table.items())
    return head + 'const O55_NIER_SCENE_SVG = {\n' + rows + '\n};\n' + layer, errs


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument('--write', action='store_true')
    g.add_argument('--check', action='store_true')
    a = ap.parse_args(argv)
    text, errs = compose()
    for e in errs:
        print('nier_scenes:', e)
    if errs:
        return 1
    if a.check:
        have = OUT.read_text(encoding='utf-8') if OUT.exists() else ''
        if have != text:
            print(f'nier_scenes: {OUT.relative_to(PKG)} is stale; run tools/nier_scenes.py --write')
            return 1
        print(f'nier_scenes: ok ({len(text.encode()) / 1024:.1f} KB)')
        return 0
    OUT.write_text(text, encoding='utf-8')
    print(f'nier_scenes: wrote {OUT.relative_to(PKG)} ({len(text.encode()) / 1024:.1f} KB)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
