import json,hashlib,sys
from pathlib import Path
from datetime import datetime,timezone,timedelta
P=Path('/home/sittingmongoose/PM-Experiments/er10-20261007-5a126dd5');cid=sys.argv[1];h=P/'helpers/targeted-cohort4'/cid;ov=json.loads((h/'execution-overlay-v3.json').read_text());c=json.loads((P/'cases'/cid/'case-card.json').read_text());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();now=datetime.now(timezone.utc);pair={'case_id':cid,'version':'v3','at':now.isoformat(),'stages':{},'finals':{}}
for arm,stages in ov['stages'].items():
 for st in stages:
  j=Path(st['job']);f=json.loads((j/'freeze.json').read_text());t=json.loads((j/'task-terminal.json').read_text());t=t.get('structuredContent',t);assert f['native_disposition']=='complete' and t['status']=='completed' and not t['hasPendingChildRuns'];pair['stages'][arm+'/'+st['stage']]={'freeze':str(j/'freeze.json'),'sha256':sha(j/'freeze.json'),'task_id':t['taskId'],'children_quiet':True,'native_receipt':str(j/'passive-terminal.json')}
 final=Path(ov['final_by_arm'][arm]);assert final.exists();pair['finals'][arm]={'path':str(final),'sha256':sha(final),'bytes':final.stat().st_size}
(h/'pair-freeze-v3.json').write_text(json.dumps(pair,indent=2)+'\n')
for arm in ([sys.argv[2]] if len(sys.argv)>2 else ['control','treatment']):
 j=P/'reviews/targeted-cohort4'/cid/(arm+'-v3');j.mkdir(parents=True,exist_ok=True);assert not (j/'dispatch-request.json').exists();sources=list(ov.get('sources',[]));indices=[]
 for st in ov['stages'][arm]:
  sj=Path(st['job'])/'sources';idx=sj/'index.json'
  if idx.exists():
   index=json.loads(idx.read_text());indices.append({'path':str(idx),'sha256':sha(idx)})
   rows=index if isinstance(index,list) else index.get('sources',index.get('entries',[]))
   for row in rows:
    path=Path(row.get('path') or sj/row['file']);expected=(row.get('sha256') or row.get('hash','')).removeprefix('sha256:') or None
    if not path.exists():
     matches=[q for q in sj.rglob(Path(row['file']).name) if q.is_file() and (not expected or sha(q)==expected)];assert len(matches)==1;path=matches[0]
    assert not expected or sha(path)==expected;record=dict(row,path=str(path),sha256=sha(path));sources.append(record)
 if cid=='D-M14-A':
  for st in ov['stages'][arm]:
   for raw in sorted((Path(st['job'])/'sources').rglob('*')):
    if raw.is_file() and not any(v['path']==str(raw) for v in sources):sources.append({'path':str(raw),'sha256':sha(raw),'kind':'Frozen candidate source capture; source identity/provenance untrusted, independently check against authored bindings','url':None})
 final=pair['finals'][arm];m={'original_brief':str(P/'cases'/cid/'inputs/brief.md'),'original_source_manifest':str(P/'cases'/cid/'inputs/sources.json'),'required_sources':sources,'arm_source_indices':indices,'frozen_output':final['path'],'frozen_output_sha256':final['sha256'],'obligations':c['material_obligations'],'scope_limit':'Only originalbrief, sources/captureindices, THIS exactfrozenfinal; no candidatesdrafts/timing/otherarm/history/reviews/campaign/helpers. Method/path visible blindinglimit; advisory scope not filesystemfirewall.'}
 if cid=='D-M14-A':
  files=ov['stages'][arm][0]['files'];m['required_complete_arm_artifacts']=[{'path':files[n],'sha256':sha(files[n])} for n in (['semantic_findings.md','mechanical_projection.md','preservation_check.md'] if arm=='treatment' else ['report.md'])]
 (j/'INPUT_MAP.json').write_text(json.dumps(m,indent=2)+'\n');end=(now+timedelta(minutes=20)).isoformat();req={'clientRequestId':f'er10-cohort4-{cid}-{arm}-source-review-v3','title':f'ER10 COHORT4 {cid} {arm} independent fullscope review v3','role':'review','mode':'async','runtimeMode':'full-access','interactionMode':'default','target':{'providerInstanceId':'codex_gmail','driverKind':'codex','model':'gpt-6.1-sol','options':{'reasoningEffort':'xhigh','serviceTier':'priority'}},'task':f'''Independently assess full declaredsource/science scope at {j}/INPUT_MAP.json, originalbrief+mappedprimarysourcebytes+THIS frozenfinal {final['path']} SHA256 {final['sha256']}. Verify exacthash before assessment. Candidate-selected captureindices/sourceidentities are untrusted claims to check, not answers or SourcePASS. For M14 if applicable also assess ALL mappedsemantic/projection/preservationviews against authoredset; retain sourceconditions/order/IDs/bindings/uncertainties/options/leads.
No cost/winner/speedtarget/otherarm/grades/parentanalysis/priorfindings supplied. Read only originalbrief/manifest, mapped sources/indices, THIS exactfrozenarm artifactset; no drafts, timings, predecessors, otherarms/cases/helpers/campaign/history or reviews. Method/arm visible in path/content: disclose blinding limits. Advisory map not filesystemfirewall. Firstreview this version, no priorfindings/unresolvedobjections; no bestof/regrade/rescue/feedbacktocandidates. Ordinary fresh reviewer under rootreviewcarrier-v2, notscoredcandidate, no ownGoal/receiptengineering. No delegation.
Sixaxes: all requiredobligations; consequentialclaims+full release/default/type/unit/path/authority conditions; bounded usefuldiscovery/negative/optional yield; wrongreject/correction/unjustifiedabstention; preservation/traceability/uncertainties/options; proposedvsexecuted checks. All6obligations: {json.dumps(c['material_obligations'])}. Independently check EVERY material recommendation/fact/condition with exact primarylocators, statedsourcefacts, inference labels, defectidentity/materiality. Verify versions/capturelimits. FullPASS requires FULL declaredscope primarychecking, not citations/manifests/exits or unchangedbytes. Localizeddecisivedefect without fullcheck DIAGNOSTIC_FAIL remainderUNASSESSED. No forceddefect/rejection/presetadoptiontruth or exhaustive unknownanswerkey. Additional publicprimarychecks allowed in boundedmodule, retain URL/version/hash/locator/limits under {j}/sources. No downloadedcode/testexecution/installers/purchases/accounts/globalconfig/repo/canon/WorkNodes/thirdpartywrites.
Write review.md/review.json with sixaxisdispositions, obligationcoverage, allconsequentialclaimchecks and sourceevidence, defects/materiality, assessmentextent/unassessedremainder, overallgrade(PASSonlyfullscope), blinding/scope/provenance limits. Preserve immutable candidate bytes/grades. No cost or winnerjudgment. timings.json actualsourceops/checks/elapsed/unknowninput/cache/generated/billing null; nativecounters separate. Reviewdeadline {end},20min includingstartup/tool/service/retries/sourcechecking/writing/requiredT3delivery. Upperboundnotinstructiontospend, finishearly; actualearlierT3requestedAt governs. At expiry stopsubstance lifecycleonlysave/deliver<=60sec afterfirstactualnotice, markpartial extent; no reset. Finalconcise artifactpaths/status, nopendingchildren.'''};(j/'dispatch-request.json').write_text(json.dumps(req,indent=2)+'\n');(j/'prospective-timing.json').write_text(json.dumps({'prepared_at':now.isoformat(),'deadline':end,'minutes':20,'native_goal_required':False},indent=2)+'\n')
 with (P/'state/targeted-cohort4-dispatches.jsonl').open('a') as z:z.write(json.dumps({'event':'before_review_dispatch','case_id':cid,'arm':arm,'version':'v3','request_id':req['clientRequestId'],'request_sha256':sha(j/'dispatch-request.json'),'input_map_sha256':sha(j/'INPUT_MAP.json'),'case_hashes':ov['hashes'],'pair_freeze_sha256':sha(h/'pair-freeze-v3.json'),'prepared_at':now.isoformat()})+'\n')
f=P/'state/targeted-cohort4.json';s=json.loads(f.read_text());s['cases'][cid].update(status='PAIR_FROZEN_PENDING_V3_INDEPENDENT_REVIEWS',pair_freeze=str(h/'pair-freeze-v3.json'));f.write_text(json.dumps(s,indent=2)+'\n');print(json.dumps(pair['finals']))
