#!/usr/bin/env python3
"""Immutable metadata joins only. No Git, native calls, candidate/evaluator bodies or ModelIO."""
import pathlib,json,hashlib,collections,datetime
LAB=pathlib.Path('/home/sittingmongoose/PM-Experiments/external-research-v9-20261005-203005');D=LAB/'consolidation/publication-resolution-001';sources=[]
def read(p,expected=None):
 p=pathlib.Path(p);raw=p.read_bytes();h=hashlib.sha256(raw).hexdigest()
 if expected:assert h==expected,(str(p),h,expected)
 sources.append({'path':str(p),'sha256':h,'bytes':len(raw)});return json.loads(raw)
inv=read(LAB/'consolidation/publication-inventory-001/ARM_INVENTORY.json','0ca13bd84503b1e138f5d9b0b22a677b30254abf6c38ad1fdb8d259ca3612cb5')
cur=read(LAB/'consolidation/publication-curation-001/editions/004-final-producer-correction/CURATION_MANIFEST.json','002a746476ef2b97d6a431dd3024b9cd835a5ef98658d9be8f654d3a3a9f240c')
p39=read(LAB/'ops/publication/commit039-authenticated-assets-and-aliases.json','92974a2f1730f727bc8b367ba2d2ec31688c45d9b503ba6b82ba264a9571ef91');v39=read(LAB/'ops/publication/cohort039-verification.json','b1a8faad0a319415d7a1fb511bf106f6cbad657a676628dd050f93ecfab3b0e7');p36=read(LAB/'ops/publication/commit036-tree-sha256.json','ece7224917655a7a69cad92d288fd5a0593b2fad7aaee14a9522435ccc4a2608');v36=read(LAB/'ops/publication/cohort036-verification.json','94c3a5623ad3182432228e5c623ba9bd37f29080b26f061d8118bf0201faa43a')
clock=read(LAB/'supervision/CURATION-001-FINAL-HANDOFF-CLOCK-QUALIFICATION.json','93944ce797291566b7a86e5d74f623aabe1a4ee2bd4a09ff151ae7ec724dc385');incident=read(LAB/'consolidation/publication-inventory-001/BOUNDARY_INCIDENT.json')
assert p39['commit']=='4ac5d0c67bb0d096b55671b9df94c9f1a8efb136' and p39['verified_direct_GitHub_head_at_publication'] is True and p39['asset_count']==937 and p39['eligible_pin_alias_count']==1130
assert v39['head']==p39['commit'] and v36['head']==p36['commit']
archives=[('/mnt/Cursor/PuppetMaster-Evidence/tests/external-research-v9-20261005-203005/positive-archive/publication128-009/4236bf807e999e962a3e18e6d53af3b20587c263127ebdf8fe394162ff9ad5ae/MANIFEST.json','0beac5c957457f01b7a2e94be411e26e49978800626432a81467040fc110c885'),('/mnt/Cursor/PuppetMaster-Evidence/tests/external-research-v9-20261005-203005/positive-archive/curation16-010/78c7decc61129f4618be2f224dcf211ea6b091fceb290ed26137cdba95a2796b/MANIFEST.json','36de696d685df8447540ab969c6d2179bfd39e555a063de4bf4290041901dadf'),('/mnt/Cursor/PuppetMaster-Evidence/tests/external-research-v9-20261005-203005/positive-archive/newpublic15-011/6437457abc881854f817c5994860bbab1943522b8f983b45e3320fc5e832a189/MANIFEST.json','5a24825f1f7bab9858f84131a7bd0575ecdc9ab2156f9f709be75b1020ec4e53')]
external={}
for path,h in archives:
 a=read(path,h)
 for f in a['files']:
  pid=f.get('pin_ref');src=f.get('path',f.get('source_path',f.get('source_locator')))
  if not pid:
   pid=next((k for k,p in inv['pin_table'].items() if p['path']==src and p['sha256']==f['sha256']),None)
  assert pid and pid in inv['pin_table'],f
  external[pid]={'archive_file':f,'archive_manifest_pin':sources[-1],'verified_scope':'Exact owner independent NAS reread SHA/length assertion; resolution reads manifestmetadata only, never rawbody'}
assets={a['path']:a for a in p39['assets']};aliases={a['pin_ref']:a for a in p39['eligible_pin_aliases']};old=collections.defaultdict(list)
for f in p36['files']:old[f['sha256']].append(f)
rows=[]
for r in cur['rows']:
 pid=r['pin_ref'];p=inv['pin_table'][pid];q={'pin_ref':pid,'source_path':p['path'],'source_sha256':p['sha256'],'source_bytes':p['bytes'],'original_publication_state_at_inventory':p['publication_state'],'typed_disposition':r['classification'],'uses':r['uses'],'scope':'Publication/content/body disposition only; no inferred scientific grade/native COMPLETE/current-versus-history credit'}
 if pid in aliases:
  a=aliases[pid];body=assets[a['asset_path']];assert a['source_pin_sha256']==p['sha256'] and a['asset_sha256']==body['sha256'] and a['asset_bytes']==body['bytes'];assert a['source_equals_asset']==(p['sha256']==body['sha256'])
  q.update(status='VERIFIED_COMMIT',commit=p39['commit'],public_asset=body,source_equals_asset=a['source_equals_asset'],source_expected_sha256=a['source_expected_sha256'],verification=a['verification'],lineage_credit_inherited=False)
 elif r['classification']=='EXISTING_VERIFIED_CONTENT_ALIAS':
  matches=[f for f in old[p['sha256']] if f['bytes']==p['bytes']];assert matches
  q.update(status='VERIFIED_COMMIT',commit=p36['commit'],public_content_alias_paths=matches,source_equals_asset=True,lineage_credit_inherited=False)
 elif r['classification']=='EXTERNAL_RAW_PUBLIC_SOURCE_CAPTURE':
  e=external[pid];f=e['archive_file'];assert f['sha256']==p['sha256'] and f['bytes']==p['bytes']
  q.update(status='VERIFIED_EXTERNAL_NAS_RAW_BODY_EXCLUDED_GIT',external=e,reason=r['reason'],rawbody_in_Git=False)
 elif r['classification'].startswith('SAFE_NEUTRAL_'):
  q.update(status='SAFE_PROJECTION_ONLY_ORIGINAL_MIXED_BODY_EXCLUDED',reason=r['reason'],original_body_publication=False,safe_projection={'commit':p39['commit'],'path':'reports/external-research-v9-20261005-203005/consolidation/publication-curation-001/editions/004-final-producer-correction/CURATION_MANIFEST.json','sha256':p39['curation_manifest_sha256'],'scope':'Verified safe curationmetadata contains originalpin/uses/disposition; existing SAFE_STAGE_FREEZE_PROJECTIONS retains neutral stage/artifact contract view; does not reconstruct original private config'})
 elif r['classification'].startswith('EXCLUDED_'):q.update(status='PRIVATE_NATIVE_AUTH_VENDOR_BODY_EXCLUDED',reason=r['reason'],original_body_publication=False)
 elif r['classification']=='QUARANTINED_OWNER_TYPED_PRODUCER_OR_SOURCE_BOUNDARY_UNKNOWN':q.update(status='UNKNOWN_PRODUCER_SOURCE_BOUNDARY_QUARANTINED',reason=r['reason'],source_original_exists_at_curation=True,original_body_publication=False,owner_type_proof=r.get('owner_approval'))
 else:raise AssertionError(('UNRESOLVED_CLASS',pid,r['classification']))
 rows.append(q)
lookup={r['pin_ref']:r for r in rows};stages={s['job_id']:s for s in inv['stages']};arms=[];stageviews={}
for arm in inv['current_selected_arms']:
 arm=dict(arm);arm['publication_scope']='Exact original currentselection/sourcecutoff; publication resolution cannot improve original OP/scientific/Goal state';arms.append(arm)
 for jid in arm['stage_ids']:
  s=stages[jid];keys=['job_id','pair_id','arm','stage','status','family','requested_family','requested_model','requested_effort','observed_family','observed_effort','actual_receipt_requested_model','actual_receipt_requested_effort','actual_receipt_observed_model','actual_receipt_observed_effort','scalar_only_observed_model_projection','scalar_only_observed_effort_projection','observed_identity_scope','owner_selected_observer_identity_and_Goal_status_metadata','Goal_proof_scope','positive_Goal_proofs','direct_native_goal_status','direct_native_goal_status_scope','stage_binding_scope','actual_stage','actual_Task','actual_tool_config','output_freeze','required_outputs','opaque_authored_artifact_inventory','runtime_and_tool_source_refs','physical_provider','billing_account','scientific_grade']
  stageviews[jid]={k:s[k] for k in keys if k in s};stageviews[jid]['publication_pin_refs_resolve_in']='pin_resolution_rows; missing/unentered/blocked/UNASSESSED original outputmarkers remain dated unchanged'
checks={'all2882_original_pins_accounted':len(rows)==2882 and set(lookup)==set(inv['pin_table']),'all96_current_arm_rows_preserved':len(arms)==96,'64_24_8_tracks_preserved':dict(collections.Counter(a['track'] for a in arms))=={'targeted':64,'fresh_integrated':24,'confirmation':8},'1130_eligible_pins_verified039':sum(r['status']=='VERIFIED_COMMIT' and r['commit']==p39['commit'] for r in rows)==1130,'502_existing_aliases_verified036':sum(r['status']=='VERIFIED_COMMIT' and r['commit']==p36['commit'] for r in rows)==502,'all53_raw_NAS_lineages_resolved':len(external)==53 and sum(r['status']=='VERIFIED_EXTERNAL_NAS_RAW_BODY_EXCLUDED_GIT' for r in rows)==53,'exact8_unknown_producer_rows':sum(r['status']=='UNKNOWN_PRODUCER_SOURCE_BOUNDARY_QUARANTINED' for r in rows)==8,'no_generic_pending_for_known_eligible':all(r['status']=='VERIFIED_COMMIT' for r in rows if r['typed_disposition'].startswith('ELIGIBLE_')),'no_science_or_native_credit':True,'oldcuration_overrun_not_hidden':clock['reported_inclusive_elapsed_seconds']==1819 and clock['reported_overrun_seconds']==19}
assert all(checks.values()),checks
out={'schema':'er9.final-publication-resolution.v1','actual_start_utc':'2026-10-06T13:25:44+00:00','prepared_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'inclusive_deadline_utc':'2026-10-06T13:35:44+00:00','source_matrix_immutable':True,'source_selection_cutoff':inv['selected_lineage_cutoff'],'source_matrix_capture_cutoff':inv['capture_end_utc'],'campaign_finished':False,'scientific_findings':'NONE_METADATA_ONLY','source_goal_grade_and_model_projections_unchanged':True,'model_unknown_scope':'Exactly unavailable fields in originaldated registry/selectedcapsule projection; never blanket campaign or all native models unknown','current_selected_arms':arms,'selected_stage_views':stageviews,'retained_history_and_warm_donor_reference':{'source_inventory_pin':sources[0],'retained_history_arms':inv['retained_history_arms'],'separate_nonlogical_strata':inv['separate_nonlogical_strata']},'pin_resolution_rows':rows,'counts':dict(collections.Counter(r['status'] for r in rows)),'known_eligible_committed_assets':{'count':937,'bytes':12828741,'typed_alias_pin_count':1130,'commit':p39['commit']},'source_metadata_pins':sources,'checks':checks,'prior_clock_qualification':clock,'prior_boundary_incident':incident,'no_perfect_blinding_or_all_drafts_retained_claim':True,'negative_constraints':'No Git, native/Goal/controller/SDK/auth/ModelIO/candidate/evaluator body read, sourcebody inspection, scientific regrade, activeworkspace write or oldmatrix/edition edit. Publiccontent equality never inherits job lineage/outputcredit. Raw53NAS datedlineages are not unique scientific evidence count.'}
(D/'PUBLICATION_RESOLUTION.json').write_text(json.dumps(out,separators=(',',':'),sort_keys=True)+'\n');(D/'CHECKS.json').write_text(json.dumps({'schema':'er9.publication-resolution-checks.v1','checks':checks,'pass':all(checks.values()),'resolution_sha256':hashlib.sha256((D/'PUBLICATION_RESOLUTION.json').read_bytes()).hexdigest(),'scope':'Metadata/provenance/count/publisherobject/NASmanifest joins only, no science or bodyvalidation'},indent=2,sort_keys=True)+'\n')
md=['# Final publication resolution','','All 96 original selected arms and 2,882 pins retain their original dated lineage, model, Goal and scientific projections.','','- 1,130 eligible pin aliases resolve to 937 exact GitHub-verified assets at commit `'+p39['commit']+'` (12,828,741 bytes).','- 502 existing content aliases resolve to exact commit036 objects.','- All 53 excluded raw-source lineages resolve to verified external NAS locators. These are lineage counts, not unique scientific sources.','- 279 private/native bodies remain excluded; 910 mixed original stage/freeze bodies have labeled safe projections and original opaque hashes.','- Eight producer/source boundaries remain UNKNOWN with exact source locators and hashes. No extant known eligible asset remains generically pending.','','Publication resolution adds no native completion, scientific grade, fresh/current pipeline credit or campaign completion. Original current fresh OP5/current confirmation OP0/historical original C03 treatment OP1 remain separate.','','The earlier inventory whole-file Luna parse and lost overwritten drafts remain disclosed. Curation final handoffs consumed 1,819 seconds, 19 over the original bound; that failure remains explicit. This resolution has a separate 600-second clock. No perfect firewall, all-draft retention, or full private-runtime reproducibility claim is made.']
(D/'README.md').write_text('\n'.join(md)+'\n');print(json.dumps({'checks_pass':all(checks.values()),'counts':out['counts'],'source_meta_count':len(sources),'resolution_sha256':hashlib.sha256((D/'PUBLICATION_RESOLUTION.json').read_bytes()).hexdigest()}))
