#!/usr/bin/env bash
set -euo pipefail

# Cleanup large, generated directories inside the dev repo checkout.
# Safe: removes only build outputs / caches that are regenerated by CI or local builds.
#
# Usage:
#   scripts/cleanup-dev-tree.sh
#   scripts/cleanup-dev-tree.sh --with-node-modules   # also removes node_modules

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

WITH_NODE_MODULES=0
if [[ "${1:-}" == "--with-node-modules" ]]; then
  WITH_NODE_MODULES=1
fi

cd "$ROOT_DIR"

echo "[cleanup] repo: $ROOT_DIR"

safe_rm_rf() {
  local p="$1"
  if [[ -e "$p" ]]; then
    echo "[cleanup] rm -rf $p"
    # Best-effort: some build artifacts can be read-only or left in odd states.
    chmod -R u+rwX "$p" 2>/dev/null || true
    rm -rf -- "$p" 2>/dev/null || true
    for _ in 1 2 3; do
      [[ -e "$p" ]] || break
      sleep 0.2
      rm -rf -- "$p" 2>/dev/null || true
    done
    if [[ -e "$p" ]]; then
      echo "[cleanup] WARN: could not fully remove: $p"
    fi
  fi
}

paths=(
  "installer-work"
  "dist"
  "coverage"
  ".test-cache"
)

# Test init dirs are large + numerous.
while IFS= read -r -d '' d; do
  paths+=("$d")
done < <(find . -maxdepth 1 -type d -name ".test-*" -print0 2>/dev/null || true)

# Optional huge directories.
if [[ "$WITH_NODE_MODULES" == "1" ]]; then
  paths+=("node_modules")
fi

for p in "${paths[@]}"; do
  safe_rm_rf "$p"
done

echo "[cleanup] done"
