#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CATALOG_FILE="$ROOT_DIR/docs/gui-widget-catalog.md"
WIDGET_DIR="$ROOT_DIR/puppet-master-rs/src/widgets"

if [[ ! -f "$CATALOG_FILE" ]]; then
  mkdir -p "$(dirname "$CATALOG_FILE")"
  cat > "$CATALOG_FILE" <<'CATALOG'
# GUI Widget Catalog

Use this catalog before adding new Rust/Iced UI components. Prefer shared widgets first; add bespoke UI only when needed.

<!-- GENERATED:START -->
<!-- GENERATED:END -->

## Curated Guidance

- `selectable_text_field`: Use for read-only/selectable values that need right-click copy/paste.
- `context_menu_actions`: Use for any context menu that maps to copy/paste/select-all/close actions.
- `auth_status_chip`: Use for authenticated/not-authenticated badges.
- `page_header` + `refresh_button`: Use for top-of-page title + refresh/action rows.

### Exception Rule

If you must bypass shared widgets, add:

```rust
// UI-DRY-EXCEPTION: <short reason>
```
CATALOG
fi

tmp_generated="$(mktemp)"
{
  echo "<!-- GENERATED:START -->"
  echo '_Auto-generated by `scripts/generate-widget-catalog.sh`._'
  echo

  mapfile -t widget_files < <(find "$WIDGET_DIR" -maxdepth 1 -name '*.rs' | sort)
  for file in "${widget_files[@]}"; do
    rel="${file#"$ROOT_DIR/puppet-master-rs/"}"
    mapfile -t symbols < <(
      rg -n "^pub (fn|struct|enum|type|trait) " "$file" \
        | sed -E 's/^.*pub (fn|struct|enum|type|trait) ([A-Za-z0-9_]+).*/\2/'
    )

    if [[ ${#symbols[@]} -eq 0 ]]; then
      printf -- '- `%s`: _(no public items)_\n' "$rel"
      continue
    fi

    joined="$(printf '%s\n' "${symbols[@]}" | awk 'NR == 1 { printf "%s", $0; next } { printf ", %s", $0 } END { print "" }')"
    joined="${joined%$'\n'}"
    printf -- '- `%s`: `%s`\n' "$rel" "$joined"
  done

  echo
  echo "<!-- GENERATED:END -->"
} > "$tmp_generated"

tmp_output="$(mktemp)"
awk -v generated_file="$tmp_generated" '
BEGIN {
  while ((getline line < generated_file) > 0) {
    generated = generated line "\n"
  }
  close(generated_file)
  skipping = 0
  inserted = 0
}
$0 == "<!-- GENERATED:START -->" {
  if (!inserted) {
    printf "%s", generated
    inserted = 1
  }
  skipping = 1
  next
}
$0 == "<!-- GENERATED:END -->" {
  skipping = 0
  next
}
!skipping {
  print
}
END {
  if (!inserted) {
    print ""
    printf "%s", generated
  }
}
' "$CATALOG_FILE" > "$tmp_output"

mv "$tmp_output" "$CATALOG_FILE"
rm -f "$tmp_generated"

echo "Updated $CATALOG_FILE"
