#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEFAULT_OUTPUT="$REPO_ROOT/docs/slint-widget-catalog.md"

MODE="write"
OUTPUT="$DEFAULT_OUTPUT"

usage() {
  cat <<'USAGE'
Usage: bash scripts/generate-widget-catalog.sh [--check] [--stdout] [--output PATH]

Generate docs/slint-widget-catalog.md from real .slint source files.

Options:
  --check          Compare generated content with the output file and fail on drift.
  --stdout         Print generated content to stdout instead of writing a file.
  --output PATH    Catalog output path. Defaults to docs/slint-widget-catalog.md.
  -h, --help       Show this help.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --check)
      MODE="check"
      shift
      ;;
    --stdout)
      MODE="stdout"
      shift
      ;;
    --output|-o)
      if [ "$#" -lt 2 ]; then
        echo "Missing value for $1" >&2
        exit 2
      fi
      OUTPUT="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

case "$OUTPUT" in
  /*) ;;
  *) OUTPUT="$PWD/$OUTPUT" ;;
esac

TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/pm-widget-catalog.XXXXXX")"
trap 'rm -rf "$TMP_DIR"' EXIT

SOURCES="$TMP_DIR/sources.txt"
COMPONENTS="$TMP_DIR/components.txt"
TAGS="$TMP_DIR/tags.txt"
GENERATED="$TMP_DIR/generated.md"

: > "$SOURCES"
: > "$COMPONENTS"
: > "$TAGS"

repo_relative() {
  case "$1" in
    "$REPO_ROOT"/*) printf '%s\n' "${1#$REPO_ROOT/}" ;;
    *) printf '%s\n' "$1" ;;
  esac
}

find "$REPO_ROOT" \
  \( \
    -path "$REPO_ROOT/.git" -o \
    -path "$REPO_ROOT/Plans" -o \
    -path "$REPO_ROOT/docs" -o \
    -path "$REPO_ROOT/target" -o \
    -path "$REPO_ROOT/node_modules" -o \
    -path "$REPO_ROOT/vendor" -o \
    -path "$REPO_ROOT/dist" -o \
    -path "$REPO_ROOT/build" \
  \) -prune -o \
  -type f -name '*.slint' -print |
  awk -v prefix="$REPO_ROOT/" 'index($0, prefix) == 1 { print substr($0, length(prefix) + 1); next } { print }' |
  LC_ALL=C sort > "$SOURCES"

while IFS= read -r rel_path; do
  abs_path="$REPO_ROOT/$rel_path"

  awk -v file="$rel_path" '
    {
      code = $0
      sub(/[[:space:]]*\/\/.*/, "", code)
      if (code !~ /^[[:space:]]*(export[[:space:]]+)?component[[:space:]]+/) {
        next
      }

      declaration = code
      sub(/^[[:space:]]*/, "", declaration)
      exported = "no"
      if (declaration ~ /^export[[:space:]]+/) {
        exported = "yes"
        sub(/^export[[:space:]]+/, "", declaration)
      }

      sub(/^component[[:space:]]+/, "", declaration)
      name = declaration
      sub(/[[:space:]:={].*$/, "", name)

      base = "-"
      base_text = declaration
      if (base_text ~ /[[:space:]]inherits[[:space:]]+/) {
        sub(/^.*[[:space:]]inherits[[:space:]]+/, "", base_text)
        sub(/[[:space:]{].*$/, "", base_text)
        base = base_text
      } else if (base_text ~ /[[:space:]]*:=[[:space:]]*/) {
        sub(/^.*[[:space:]]*:=[[:space:]]*/, "", base_text)
        sub(/[[:space:]{].*$/, "", base_text)
        base = base_text
      }

      if (name ~ /^[A-Za-z_][A-Za-z0-9_]*$/) {
        print file "|" FNR "|" name "|" exported "|" base
      }
    }
  ' "$abs_path" >> "$COMPONENTS"

  awk -v file="$rel_path" '
    /DRY:WIDGET/ {
      tag = $0
      sub(/^.*DRY:WIDGET[[:space:]]*:?[[:space:]]*/, "", tag)
      sub(/[[:space:];,)}\]]+$/, "", tag)
      sub(/[[:space:]].*$/, "", tag)
      if (tag == "" || tag ~ /^</) {
        tag = "-"
      }
      print file "|" FNR "|" tag
    }
  ' "$abs_path" >> "$TAGS"
done < "$SOURCES"

source_count="$(wc -l < "$SOURCES" | tr -d ' ')"
component_count="$(wc -l < "$COMPONENTS" | tr -d ' ')"
tag_count="$(wc -l < "$TAGS" | tr -d ' ')"

{
  cat <<'HEADER'
# Slint Widget Catalog

Generated by `scripts/generate-widget-catalog.sh`.

This catalog is derived from repository `.slint` source files. It excludes Plans prose, docs, build output, VCS metadata, and dependency directories so future Rust + Slint implementation work can verify widget reuse without treating specification text as source.
HEADER

  printf '\n## Summary\n\n'
  printf -- '- Slint source files: %s\n' "$source_count"
  printf -- '- Component declarations: %s\n' "$component_count"
  printf -- '- DRY widget tags: %s\n' "$tag_count"

  printf '\n## Source Files\n\n'
  if [ "$source_count" -eq 0 ]; then
    printf 'No `.slint` source files found.\n'
  else
    while IFS= read -r rel_path; do
      printf -- '- `%s`\n' "$rel_path"
    done < "$SOURCES"
  fi

  printf '\n## Components\n\n'
  if [ "$component_count" -eq 0 ]; then
    printf 'No Slint component declarations found.\n'
  else
    printf '| Component | Exported | Base | Source |\n'
    printf '| --- | --- | --- | --- |\n'
    while IFS='|' read -r file line name exported base; do
      printf '| `%s` | %s | `%s` | `%s:%s` |\n' "$name" "$exported" "$base" "$file" "$line"
    done < "$COMPONENTS"
  fi

  printf '\n## DRY Widget Tags\n\n'
  if [ "$tag_count" -eq 0 ]; then
    printf 'No `DRY:WIDGET` tags found.\n'
  else
    printf '| Tag | Source |\n'
    printf '| --- | --- |\n'
    while IFS='|' read -r file line tag; do
      printf '| `%s` | `%s:%s` |\n' "$tag" "$file" "$line"
    done < "$TAGS"
  fi
} > "$GENERATED"

case "$MODE" in
  stdout)
    cat "$GENERATED"
    ;;
  check)
    if [ ! -f "$OUTPUT" ]; then
      echo "Widget catalog output is missing: $(repo_relative "$OUTPUT")" >&2
      exit 1
    fi

    if diff -u "$OUTPUT" "$GENERATED" >/dev/null; then
      echo "Widget catalog is up to date: $(repo_relative "$OUTPUT")"
      exit 0
    fi

    echo "Widget catalog drift detected: $(repo_relative "$OUTPUT")" >&2
    echo "Run: bash scripts/generate-widget-catalog.sh" >&2
    diff -u "$OUTPUT" "$GENERATED" >&2 || true
    exit 1
    ;;
  write)
    mkdir -p "$(dirname "$OUTPUT")"
    if [ -f "$OUTPUT" ] && cmp -s "$OUTPUT" "$GENERATED"; then
      echo "Widget catalog already up to date: $(repo_relative "$OUTPUT")"
    else
      cp "$GENERATED" "$OUTPUT"
      echo "Wrote widget catalog: $(repo_relative "$OUTPUT")"
    fi
    ;;
  *)
    echo "Internal error: unknown mode $MODE" >&2
    exit 2
    ;;
esac
