"""Freeze the exact prospective source closure after mechanical checks; no admission."""
import datetime,hashlib,json,pathlib,sys
HERE=pathlib.Path(__file__).resolve().parent
sys.path.insert(0,str(HERE));import profile

def sha(path):return hashlib.sha256(pathlib.Path(path).read_bytes()).hexdigest()
def ref(path):return {'path':str(pathlib.Path(path)),'sha256':sha(path)}
def put(name,value):(HERE/name).write_text(json.dumps(value,indent=2,sort_keys=True)+'\n')
start=json.loads((HERE/'START.json').read_text());OLD=pathlib.Path(start['predecessor_path']);old=json.loads((OLD/'PIN.json').read_text());pres=json.loads((HERE/'SOURCE_PRESERVATION.json').read_text());now=datetime.datetime.now(datetime.timezone.utc).isoformat()
assert all(pres['all_original_pinned_files_unchanged'].values())
required=profile.required_source_paths();assert str(HERE/'readiness.py') in required
runtime={path:sha(path) for path in sorted(required)}
for path,digest in old['runtime_source_pins'].items():
 if not pathlib.Path(path).is_relative_to(OLD):assert sha(path)==digest
worker=ref(HERE/'stage_worker.py');contract={'schema':'er9.glm.readiness-failfast-runtime-contract.v1','created_utc':now,'version':start['version'],'worker':worker,'predecessor':ref(OLD/'PIN.json'),'model':old.get('model','builtin:zai-coding-plan/GLM-5.3-Flash'),'effort':'max','family':'Z','tools_config_builder':ref(profile.TOOLS/'config.py'),'tools_source_pins':ref(profile.TOOLS/'SOURCE_PINS.json'),'tools_release_pin':ref(profile.TOOLS/'PIN.json'),'resource_allocator':ref(profile.API),'aggregate_memory_max_bytes':2304*1024*1024,'memory_swap_max_bytes':0,'component_memory_max_bytes':{'outer_worker':768*1024*1024,'native':768*1024*1024,'pm_boundary':256*1024*1024,'pm_execution':256*1024*1024,'sandbox':256*1024*1024},'clocks':'original birth+original allocation; action total-30seconds; guardian total-5seconds; outer total; no reset/extension','readiness':'existing verified_before_command_exec true across exact owned records, then unchanged preactivation kernel/placement proof before session/goal set','new_failfast':'only fully joined prelaunch owned intent + exact guard PID from parent-created process + original profile/hash/birth/stop + final false readiness + positive closure/exit + terminal MainPID0/emptyControlGroup/owned quiet','new_private_records':['native-host.ownership.json','pm_boundary-resource.ownership.json','pm_execution-resource.ownership.json when admitted'],'failure_class':'OwnedComponentReadinessTerminated','failure_receipt_field':'pre_goal_readiness_failure','exception_scope':'positive owned readiness closure only; no actual Goal-start/zero-cost/billing inference','backend_immediate_termination_cause':'UNKNOWN','candidate_Task_tools_source_factors_permissions_changed':False,'unchanged_runtime_files':pres['unchanged_runtime_files'],'unchanged_enforcement_functions':pres['unchanged_enforcement_functions'],'modified_runtime_files':['glm_stage.py','component_guard.py','profile.py'],'new_runtime_files':['readiness.py'],'clock_and_Task_constructor':ref(HERE/'task_fragment.py'),'prospective_only':True,'admission_owner':'ops_recovery'}
put('RESOURCE_CONTRACT.json',contract)
verification={'schema':'er9.glm.readiness-failfast-verification.v1','observed_utc':now,'result':'PASS','tests':16,'test_command':['/usr/bin/python3',str(HERE/'test_readiness.py')],'coverage':['positive owned termination immediate no poll','foreign-unit/component/guardPID/original-stop/profile/birth rejected','missing terminal/quiet/exit/ownership evidence UNKNOWN retains original wait','unknown/live state or nonempty cgroup/nonzero PID rejected','future closure rejected','original deadline precedes late failure classification','pending record can become ready','exclusive bounded ownership intent and alias rejection','actual Protocol parent-created PID mapping','production g.run with synthetic Protocol stops before Goal set and runs unchanged cleanup'],'actual_native_model_Goal_calls':0,'synthetic_Protocol_fixture':'no native CLI subprocess, no account/auth reads, no provider/model/Goal RPC','source_preservation':ref(HERE/'SOURCE_PRESERVATION.json'),'source_scope':'new successor only; 9 runtime files and5 enforcement functions byte-identical;3 files differ only by declared additions/version source closure','actual_kernel_placement_retested':False,'kernel_cap_placement_basis':'unchanged previously pinned and verified enforcement code; no new kernel/cap behavior','current_live_or_old_files_changed':False}
put('VERIFICATION.json',verification)
(HERE/'README.md').write_text('This is a prospective actual runner release. Select the exact PIN worker and glm_resource version; use its full runtime_source_pins. The same actual GLM5.3Flash/max/native Goal, tools1.5 builder, whole2304MiB private envelope, component caps, Swap0, Task/input/factor/permissions and original birth/action/cleanup clocks are retained.\n\nA private immutable ownership intent is written by each component guard before its existing unit launch. The driver uses guard PIDs from the native Popen and MCP Bridge.proc to join exact unit/component/profile SHA/birth/stop. The existing readiness loop now raises OwnedComponentReadinessTerminated promptly only for a positive final unready terminal-and-quiet component record. Missing/foreign/unknown/future facts retain the original wait and stop behavior. The unchanged preactivation kernel and placement proof still runs before Goal submission.\n\nThe exception exposes safe pre_goal_readiness_failure metadata and UNKNOWN backend cause/billing. This class, goal_activated:false, a missing submission or an empty usage export alone do not establish historical actual Goal-start0 or free execution. Existing cleanup, settlement, original caps and external release remain unchanged.\n\n16 zero-inference tests pass for this actual directory, including a production g.run fixture with a synthetic Protocol, no native CLI/provider/account access and no Goal set reached. The kernel enforcement functions were not re-probed: their source identity to the previously verified predecessor is proved. Nine runtime files and five enforcement functions are byte-identical; exact inverse additions restore the other three modified runtime files. Old and live files remain unchanged.\n\nOps alone may integrate this frozen successor into explicitly unentered future stages with complete prospective closures. This release neither admits jobs nor authorizes an automatic candidate retry.\n')
files={n:sha(HERE/n) for n in ('stage_worker.py','glm_stage.py','native_support.py','component_guard.py','component_gate.py','native_guard.py','pipe_bridge.py','pipe_proxy.py','external_release.py','profile.py','clock_binding.py','task_fragment.py','readiness.py','test_readiness.py','verify_preservation.py','freeze_release.py','README.md','RESOURCE_CONTRACT.json','VERIFICATION.json','SOURCE_PRESERVATION.json','START.json')}
pin={'schema':'er9.glm.complete-resource-source-pins.v1','created_utc':now,'version':start['version'],'status':'READY_ZERO_INFERENCE_PROSPECTIVE_ONLY','worker':worker,'predecessor':ref(OLD/'PIN.json'),'files':files,'runtime_source_pins':runtime,'tools_source_pins':ref(profile.TOOLS/'SOURCE_PINS.json'),'tools_release_pin':ref(profile.TOOLS/'PIN.json'),'resource_allocator':ref(profile.API),'task_fragment_constructor':ref(HERE/'task_fragment.py'),'verification':ref(HERE/'VERIFICATION.json'),'no_original_or_live_edits':True,'model_calls':0,'native_goal_starts':0,'prospective_only':True}
put('PIN.json',pin)
put('OUTBOX.json',{'schema':'er9.glm.readiness-failfast-integration-outbox.v1','status':'READY_ZERO_INFERENCE_PROSPECTIVE_ONLY','source_pin':ref(HERE/'PIN.json'),'version':start['version'],'worker':worker,'entrypoint':['/usr/bin/python3',str(HERE/'stage_worker.py'),'--stage-json','FROZEN_NEW_STAGE_JSON','--stage-sha256','FROZEN_NEW_STAGE_SHA','--birth-monotonic-ns','ORIGINAL_ROLE_BIRTH','--resource-profile','FRESH_ORIGINAL_RESOURCE_PROFILE','--resource-profile-sha256','EXACT_PROFILE_SHA'],'descriptor_binding':{'glm_resource.version':start['version'],'glm_resource.source_pins':'exact PIN.runtime_source_pins map, including readiness.py','glm_resource.tools_config_builder':ref(profile.TOOLS/'config.py'),'glm_resource.model':'builtin:zai-coding-plan/GLM-5.3-Flash','glm_resource.effort':'max','other_fields':'retain exact current admitted per-role factor/tools/profile/Task/input/artifact/model/caps and original clock choices; no template inference/fallback'},'private_record_binding':'guard writes ownership intent before unit start; no ops-populated or label-derived unit fallback','failure_metadata_schema':'pre_goal_readiness_failure typed fields with UNKNOWN actual status/billing/cause; accounting must retain direct native status proof requirements','eligibility':'explicit future unentered stage versions only; ops owns source/closure seal and actual import. No mutation of old/live/frozen stage JSON. No automatic candidate retry. Respect complete source-choice prospectivity for each owning lineage.','native_model_Goal_calls':0})
selection=[{'path':str(HERE/n),'sha256':sha(HERE/n),'bytes':(HERE/n).stat().st_size} for n in (*files,'PIN.json','OUTBOX.json')]
put('PUBLIC_SELECTION.json',{'schema':'er9.positive-public-selection.v1','files':selection,'scope':'source and synthetic control-only checks; no raw runtime, Task/objective/auth/candidate/evaluator contents','prospective_only':True})
print(json.dumps({'version':start['version'],'PIN_sha256':sha(HERE/'PIN.json'),'OUTBOX_sha256':sha(HERE/'OUTBOX.json'),'selector_sha256':sha(HERE/'PUBLIC_SELECTION.json'),'worker_sha256':worker['sha256'],'runtime_paths':len(runtime)}))
