from pathlib import Path
from datetime import datetime, timezone
import hashlib, json, re

OUT=Path(__file__).resolve().parent.parent
BASE=Path('ER12_RUNTIME')
RUN=BASE/'runs/A7-01/treatment'
FINAL=RUN/'stages/critic-finalizer/final.md'
DISC=RUN/'stages/investigator/discovery.md'
DRAFT=RUN/'stages/investigator/draft.md'
CRIT=RUN/'stages/critic-finalizer/critique.md'
def dump(path,obj): path.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
def sha(path): return hashlib.sha256(path.read_bytes()).hexdigest()
def loc(path,needle):
 lines=path.read_text().splitlines()
 return {'path':str(path),'line':next(i+1 for i,s in enumerate(lines) if needle in s),'anchor_text':needle}
def link(l,label=None): return '['+(label or l['anchor_text'])+']('+l['path']+':'+str(l['line'])+')'

SOURCES=[
('P01','3MF Core specification','https://github.com/3MFConsortium/spec_core/blob/373e91d0665d4671cdc3bb44fc5603c561c8d388/3MF%20Core%20Specification.md','Core 1.4.0; file revision 373e91d0665d4671cdc3bb44fc5603c561c8d388', ['P01-core.md','P18-core-commit.json'], '§§1.1, 2.1.1–2.1.5, 2.2.1–2.2.2, 2.3.1, 3.4, 3.4.1, 4, 4.2, 5.1; raw lines 150–234, 249–286, 316–327, 400–469, 530–562, 742–813', 'Normative format conditions support explicit units, composition and design intent, optional thumbnail/Description, and consumer-specific PrintTicket. Filename suffixes are recommendations. Required unsupported extensions block editing/manufacturing; recommended unsupported extensions call for warning/input. Format capability does not prove application preservation.'),
('P02','3MF Materials and Properties extension','https://github.com/3MFConsortium/spec_materials/blob/d4d42dd75ca07da40284dc87e3204b2993d2f862/3MF%20Materials%20Extension.md','M&P 1.2.1; file revision d4d42dd75ca07da40284dc87e3204b2993d2f862',['P02-materials.md','P19-materials-commit.json'],'Preface; raw lines 5–7, 64–96','The extension preface restricts use to Core 1.2. The final identifies this exact condition and declines to infer Core 1.4 compatibility. Its optional exclusion from the baseline leaves Core labels and the authorized preview/note intact.'),
('P03','3MF current specification index','https://3mf.io/spec/','Access-date inventory: latest Core 1.4.0; ISO Core 1.3.0; M&P 1.2.1',['P03-index.html','web-additional-primary.json'],'Specification Suite table; web lines 41–50','The index distinguishes the ISO edition from the latest revision. It independently corroborates the versions cited in the final; it does not override the extension preface or establish receiver support.'),
('P04','Fusion Save As Mesh','https://help.autodesk.com/view/fusion360/ENU/?contextId=MESH-SAVE-AS-MESH','Live help; exact executable build UNKNOWN',['web-official-docs.json'],'Save As Mesh steps 3–5; web lines 30–45','Supports the proposed mesh-export route, selectable output unit and all-bodies/one-body file structure. The help does not prove object hierarchy, material, thumbnail or Description preservation. HTTP shell capture is not the rendered article; the independent web capture supplies the article evidence.'),
('P05','Fusion Export designs','https://help.autodesk.com/view/fusion360/ENU/?contextId=ASM-EXPORT-DESIGN','Live help; exact executable build UNKNOWN',['web-official-docs.json'],'Format list and Tips; web lines 35–60','Supports 3MF and STEP export and the loss-of-associativity boundary. STEP protocol-specific fidelity and receiving behavior are not established by this help page.'),
('P06','Prusa supported file formats','https://help.prusa3d.com/article/supported-file-formats_1772?product=cw1','PrusaSlicer 2.9 legacy help context; exact build UNKNOWN',['P06-prusa-formats.html','web-official-docs.json','web-additional-primary.json'],'3MF/STL/STEP/OBJ/AMF sections; web lines 359–376','Confirms STEP triangulation, the preferred 3MF format, STL ASCII/binary support and the OBJ material/texture exception. These are product-specific documentation facts, not an executed import test.'),
('P07','Prusa saving projects as 3MF','https://help.prusa3d.com/article/saving-projects-as-3mf_1773?product=sl1','PrusaSlicer 2.9 legacy help context; exact build UNKNOWN',['P07-prusa-project.html','web-official-docs.json','web-additional-primary.json'],'Save Project and format sections; web lines 350–366','Supports the distinction between geometry and a Prusa project snapshot with settings/modifiers. The same-G-code sharing claim is documentation, not workshop machine approval. The geometry-only STL description supports rejection of STL as the complete project record.'),
('P08','PrusaSlicer 2.5.0 release','https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.5.0','Released 2.5.0; published 2022-09-07; candidate short commit ec2f533',['P08-prusa250.json','P08-prusa250.txt'],'Release body Summary','Independently confirms the release introduced STEP import. Neither the release nor the final claims universal STEP fidelity.'),
('P09','Cura 5.7.0 release','https://github.com/Ultimaker/Cura/releases/tag/5.7.0','Released 5.7.0; published 2024-04-03; candidate short commit 04ddb8e',['P09-cura570.json','P09-cura570.txt'],'Universal Cura Project; Bug fixes; Bugs resolved since Beta; UCP tips','Supports UCP models/settings, project-open versus Import Models positions, and New Project reset advice. Also contains a relevant original-name loading improvement omitted from the candidate history. Its cross-printer language never approves settings for a workshop machine.'),
('P10','Cura 5.14.0-alpha.0 release','https://github.com/Ultimaker/Cura/releases/tag/5.14.0-alpha.0','Prerelease 5.14.0-alpha.0; published 2026-06-25; candidate short commit 17e7b05',['P10-cura514alpha.json','P10-cura514alpha.txt'],'New features and improvements, non-project multi-model 3MF bullet','Confirms the critic addition concerns non-project 3MF positioning and is a prerelease. The final correctly does not equate it with stable acceptance or the exact #19456 correction.'),
('P11','Cura release inventory','https://github.com/Ultimaker/Cura/releases','At review: latest stable 5.13.0; next entry 5.14.0-alpha.0 prerelease',['P11-cura-releases.json'],'First two release objects and prerelease/published_at fields; independent web index','The version snapshot is supported. Exact pilot versions and modes remain legitimate owner decisions; the final requires rechecking the inventory at selection.'),
('P12','PrusaSlicer release inventory','https://github.com/prusa3d/PrusaSlicer/releases','At review: stable 2.9.6; 3.0.0-alpha11/alpha12 prereleases',['P12-prusa-releases.json'],'First three release objects and prerelease/published_at fields; independent web index','Supports separation of stable 2.9.6 from alpha-specific name reports and the unknown Flathub beta build.'),
('P13','Prusa STEP issue #8998 and complete comments','https://github.com/prusa3d/PrusaSlicer/issues/8998','Original 2.5.0 report; September 2026 Flathub beta exact build UNKNOWN',['P13-step-issue.json','P13-step-comments.json','P13-step-issue.txt','P13-step-comments.txt'],'Issue description; comments 1267796232, 1267802168, 1268566562, 1359148435, 1368024449, 5731454045','Supports missing STEP detail/open-edge history, maintainer OpenCASCADE attribution and the later unpinned Owl report. The Owl follow-up is a different named example in the same thread, not proof the original hinge defect persists. The final keeps both reports bounded and proposes actual selected-build shape checks.'),
('P14','Prusa unit/transform issue #15545 and comments','https://github.com/prusa3d/PrusaSlicer/issues/15545','Reported 2.9.6 Windows x64 portable; closed 2026-09-29 for inactivity',['P14-unit-issue.json','P14-unit-comments.json','P14-unit-issue.txt','P14-unit-comments.txt'],'Description; control matrix; expected/actual bounds; tested build; comment 5890111762','The error boundary is non-mm translation terms, not rotation or scale alone. Expected inch-case X bounds are 25.4–50.8 mm versus reported -23.4–2.0 mm. The closure comment establishes housekeeping, irrespective of the API completed status. No candidate or reviewer product reproduction occurred.'),
('P15','Prusa Bambu-name issue #15662','https://github.com/prusa3d/PrusaSlicer/issues/15662','Reported 3.0.0-alpha11; vendor-private metadata',['P15-bambu-issue.json','P15-bambu-issue.txt','web-other-primary.json'],'Description, core XML versus Metadata/model_settings.config; version; issue activity','Supports the private-name versus Core object.name distinction. The final does not transfer alpha/vendor-private evidence to stable Core-name behavior.'),
('P16','Cura position issue #19456 and complete comments','https://github.com/Ultimaker/Cura/issues/19456','Original 5.7.2; later 5.8/5.9 reports; sample success in 5.10.0 on 2025-03-26',['P16-cura-position.json','P16-cura-position-comments.json','P16-cura-position.txt','P16-cura-position-comments.txt'],'Comments 2260860726, 2268913792, 2492018540, 2753377279; issue closed_at/state_reason','Confirms C01 chronology correction and mode sensitivity. A comment explicitly links Cura PR #19375 as a possible fix. Thus the final absolute no-linked-PR statement is inaccurate, although the exact cause of the sample success remains unproven.'),
('P17','Cura object-name issue #17110 and complete comments','https://github.com/Ultimaker/Cura/issues/17110','2023 issue; author later says using Cura 5.4; no separately formalized tested-build block',['P17-cura-names.json','P17-cura-names-comments.json','P17-cura-names.txt','P17-cura-names-comments.txt'],'Description; comments 1826125504, 1832857900, 1835054338','The final safely presents an older report, but its no-exact-release-stated wording overlooks the author’s 5.4 context. The thread links Uranium #898; the 5.7.0 release and 5.13.0 reader source provide later name-handling context. They do not guarantee every round trip.'),
('P20','PrusaSlicer released 3MF importer source','https://github.com/prusa3d/PrusaSlicer/blob/version_2.9.6/src/libslic3r/Format/3mf.cpp','Source at released version_2.9.6 tag',['P20-prusa3mf-code.txt'],'get_unit_factor lines 301–317; model handler 1959–1962; vertex handler 2103–2111; component handler 2183–2201; item handler 2224–2239','Static source inspection corroborates the reported asymmetry: vertex factors are applied, while the inspected component/item handlers pass parsed transforms through. This is implementation evidence, not a locally executed witness or a guarantee about all binaries/platforms.'),
('P21','PrusaSlicer released STEP import source','https://github.com/prusa3d/PrusaSlicer/blob/version_2.9.6/src/libslic3r/Format/STEP.cpp','Source at released version_2.9.6 tag',['P21-prusa-step-code.txt'],'get_load_step_fn and load_step, lines 36–123','Confirms the OCCT-wrapper path and creation of TriangleMesh facets. The candidate’s STEP triangulation/kernel boundary is supported; source reading does not independently reproduce either issue example.'),
('P22','Cura released 3MF reader source','https://github.com/Ultimaker/Cura/blob/5.13.0/plugins/3MFReader/ThreeMFReader.py','Source at released 5.13.0 tag',['P22-cura-reader-code.txt'],'_convertSavitarNodeToUMNode lines 101–135; _read lines 260–328; _getScaleFromUnit 339–364','The current reader asks Savitar for a node name and uses a fallback only when empty. It reads scene metadata and transforms/units. This limits extrapolation from the 2023 name issue, but the dependency/parser/UI/export chain still needs end-to-end tests.'),
('P23','Cura transformation-writer fix PR #19375','https://github.com/Ultimaker/Cura/pull/19375','Merged 2024-08-05; merge 4a5aecc1e4e62e3cf4cd8e0b6002c503881d3078',['P23-cura-pr19375.json','P23-cura-pr19375-files.json'],'PR body; files patch plugins/3MFWriter/ThreeMFWriter.py around line 114','The linked implementation fix changes center compensation and matrix multiplication. It is a real lead omitted by the candidate, but the issue continues reporting failures after the merge and the final sample result does not attribute its cause. It cannot be promoted to a proven #19456 repair.'),
('P24','Uranium object reload/name change PR #898','https://github.com/Ultimaker/Uranium/pull/898','Merged 2023-11-01; merge d6a63ca2837bf934fa01aa0d41f235323e8ebc9e',['P24-uranium-pr898.json','P24-uranium-pr898-files.json'],'Body test record; UM/Scene/Scene.py patch; dependency on Cura PR #16610','Useful implementation/history lead linked by the names issue. Its author reports multi-model name and reload checks, with explicit limitations for added/removed models. These are external executed checks, not candidate or reviewer validation.'),
]

retrieved=json.loads((OUT/'evidence/retrieval-record.json').read_text())
source_rows=[]
for ident,title,url,version,files,locator,judgment in SOURCES:
 captures=[]
 for name in files:
  p=OUT/'evidence'/name
  captures.append({'path':str(p),'relative_path':'evidence/'+name,'sha256':sha(p),'bytes':p.stat().st_size})
 stamps=[x['accessed_at_utc'] for x in retrieved if any(Path(x.get('path','')).name==f for f in files)]
 row={'source_id':ident,'title':title,'primary_url':url,'version_or_commit':version,'locator':locator,'accessed_at_utc':stamps or ['2026-10-10 reviewer web access; see saved tool captures'],'observed_operation':'Independent read-only primary retrieval and semantic reading; no fetched implementation executed','governing_conditions_and_applicability':judgment,'captures':captures}
 source_rows.append(row)
 note=['# '+ident+' — '+title,'', '[Governing primary source]('+url+')','', '**Version:** '+version,'','**Locator:** '+locator,'','**Independent assessment:** '+judgment,'','**Evidence captures:**','']
 note += ['- ['+Path(x['path']).name+']('+x['relative_path'].removeprefix('evidence/')+') — SHA-256 `'+x['sha256']+'`' for x in captures]
 (OUT/'evidence'/(ident+'-review.md')).write_text('\n'.join(note)+'\n')

AXES=[
{'axis':1,'name':'Original obligations and negative constraints','coverage':'FULL','judgment':'PASS','final_locators':[loc(FINAL,'Released plan review'),loc(FINAL,'Owner decisions, covered scope'),loc(FINAL,'Product checks')],'assessment':'All eight original numbered obligations are substantively fulfilled. The final compares two exchange routes plus UCP and a ZIP analogy, separates units/composition/material intent/settings, retains optional preview/note with conditions, includes released history, preserves fixed owners and all four exclusions, and delivers one standalone proposal with separate execution status. No installs or prototype are required by the brief; unselected receiver versions, tolerances and per-project values are honest owner inputs.'},
{'axis':2,'name':'Consequential source claims and exact applicability','coverage':'FULL','judgment':'PASS_WITH_LIMITATIONS','final_locators':[loc(FINAL,'Units and geometry'),loc(FINAL,'Material intent, display and extensions'),loc(FINAL,'Compatibility history and version')],'assessment':'The governing Core, Autodesk and Prusa documentation, versioned release records and complete issue comments support the consequential route decisions and conditions. Core default/unit domain, composition versus CAD constraints, design-intent versus printed color, PrintTicket defaults, STEP triangulation, Cura operation/version exceptions, private versus Core names and M&P version restriction were checked separately. Remaining PR-link/name-version wording defects do not alter the conditional matrix or exclude a supported capability. No remaining material source error or unsupported decision was established.'},
{'axis':3,'name':'Useful unfamiliar discovery, alternatives, implementation/history and opportunity breadth','coverage':'FULL','judgment':'PASS_WITH_LIMITATIONS','final_locators':[loc(FINAL,'Handoff routes and package tradeoffs'),loc(FINAL,'Optional preview and readable project note'),loc(FINAL,'Compatibility history and version')],'assessment':'Useful mechanisms include Core/OPC packaging, component instances/transforms, portable material intent, optional Description/thumbnail with a human-readable fallback, direct STEP tessellation, purpose-bearing filenames and Cura UCP settings/project modes. Competing alternatives have distinct tradeoffs and STL is retained as a limited fallback. The frozen discovery precedes plan reveal and discovers Fusion/3MF/STEP from the brief; UCP arrives in the draft after reveal. Implementation history is weaker than opportunity/history coverage: the candidate relies on specs, releases, embedded issue XML and kernel discussion, while missing real linked fixes. Independent static source inspection corroborates its main recommendations but does not retroactively credit the candidate with that work.'},
{'axis':4,'name':'Wrong criticism, corrections, rejections and exact plan dispositions','coverage':'FULL','judgment':'PASS_WITH_LIMITATIONS','final_locators':[loc(FINAL,'Released plan review'),loc(FINAL,'Rejected draft assumptions')],'assessment':'All exact numbered plan clauses and treatments were assessed independently and every indexed criticism C01–C06 has a saved disposition reflected in final prose. The stale Cura outcome and M&P version precondition are corrected; no authorized option or owner authority is wrongly removed. Several criticisms call useful optional additions material omissions without showing decision-changing harm in the already bounded draft. Their implemented additions are harmless and preserve scope. The critic’s no-linked-PR claim is itself a minor wrong correction.'},
{'axis':5,'name':'Supported discovery/draft/critique/final meaning preserved','coverage':'FULL','judgment':'PASS','final_locators':[loc(FINAL,'Recommendation'),loc(FINAL,'Handoff routes and package tradeoffs'),loc(FINAL,'Owner decisions, covered scope')],'assessment':'The final preserves the supported default, conditional STEP route, UCP analogy, separate reviewer wrapper, restricted STL route, optional preview/note, author/technician/lead roles, uncertainty and unrun checks. Later history is added without turning reports into product validation. The M&P restriction affects only rich optional extension data; Core intent labels and the explicitly authorized reviewer image/note remain. Omitted detailed required/recommended extension rules are retained in investigator evidence and not contradicted by the final baseline, which keeps extension data optional.'},
{'axis':6,'name':'Meaningful proposed versus executed validation and oracle applicability','coverage':'FULL','judgment':'PASS','final_locators':[loc(FINAL,'Validation plan and execution record'),loc(FINAL,'Research and stage-control status')],'assessment':'The candidate claims research/intake reading/manual hashing/native observations, not CAD export, package inspection, slicer import, geometry checks or printing. Proposed tests use exporter/receiver/mode cells, author-declared bounds and units, transform/part/shape sentinels, displayed/preserved labels and reviewer readability. A preview or file-open is explicitly not a geometry oracle. Tolerances legitimately belong to the lead. The mm/non-mm paired test is applicable to the reported translation defect; geometric sentinels are more discriminating than opening one file. Official missing gate claims are protocol failures, not completed validation. No nonexistent deployment or local product test was required.'},
]

PLAN_DISPOSITIONS=[
('Corrected; STL-as-complete-record rejected','Two independent CAD-to-slicer routes, Cura UCP analogy and separate ZIP wrapper are compared; explicit units and material intent replace filename/verbal reconstruction. Limited STL fallback is preserved.', ['P01','P04','P05','P06','P07','P09']),
('Corrected and expanded','Receiver boundaries are stated: 3MF triangle/composition/intent data differs from CAD history and machine setup; STEP is triangulated. Cura and Prusa are candidates whose exact versions/modes need lead selection.', ['P01','P05','P06','P07','P09','P21']),
('Authorized option retained; universal settings portability rejected','Conditional standard thumbnail/Description plus sidecar fallback are retained. The final records ignored/warned extension data in proposed tests and keeps rich M&P outside baseline pending the spec pairing.', ['P01','P02','P03','P07','P09']),
('Unresearched assumptions replaced; one-open acceptance rejected','Released Cura 5.7 and Prusa 2.5 changes plus bounded issues and later results yield mode/shape/unit/name sentinels. Source history is research, not successful pilot validation.', ['P08','P09','P10','P13','P14','P15','P16']),
('Retained as authorized optional scope','Package image and readable note are supported format opportunities with exporter/receiver conditions, optional sidecar fallback and no unjustified exclusion or promotion to mandatory.', ['P01','P04','P07']),
('Fixed owner authority retained; unresolved values separated','The author owns intended units/materials, technician printer settings and lead tested receiving matrix. Remaining values, versions and tolerances do not reopen authority.', ['ORIGINAL_BRIEF']),
('All binding exclusions retained','No printers operated, safety-critical parts designed, STL completeness presumed or saved settings universally approved. Later review tests explicitly do not slice or send instructions.', ['ORIGINAL_BRIEF','P07','P09']),
('Replaced by coherent full proposal','Recommendation, compact comparison, applicability/history, useful discovery, explicit decisions/uncertainty and validation tables are present. No prototype, deployment or product operation is claimed.', ['P01','P04','P06','P09','P13','P14','P16']),
]

plan=(BASE/'frozen-inputs/A7-01/plan.md').read_text()
brief=(BASE/'frozen-inputs/A7-01/brief.md').read_text()
matches=list(re.finditer(r'^### (\d+)\. (.+)\n',plan,re.M))
clauses=[]
for i,m in enumerate(matches):
 end=matches[i+1].start() if i+1<len(matches) else plan.index('## Validation status at handoff')
 body=plan[m.end():end].strip()
 disposition,assessment,ids=PLAN_DISPOSITIONS[i]
 bmatch=re.search(r'^'+str(i+1)+r'\. (.+)$',brief,re.M)
 clauses.append({'clause':i+1,'exact_plan_clause':m.group(2),'exact_original_brief_obligation':bmatch.group(1),'exact_plan_draft_treatment':body,'disposition':disposition,'reviewer_assessment':assessment,'source_ids':ids,'final_locator':loc(FINAL,'| **'+str(i+1)+'.') ,'judgment':'PASS'})

original_critic=json.loads((RUN/'stages/critic-finalizer/critique-dispositions.json').read_text())
comments=[
('SUPPORTED_CORRECTION_WITH_MINOR_WRONG_LOCATOR','The 5.10.0 sample success and completed closure are verified. Amendment in final is appropriately bounded. The critic and final nevertheless overlook a comment linking PR #19375; no causal link to the later success is proven.','P16,P23'),
('SUPPORTED_ADDITION_SEVERITY_OVERSTATED','The alpha improvement is real, non-project-specific and correctly not promoted to a stable fix. Absence from the draft was a useful opportunity gap, not shown to invalidate its existing conditional recommendation.','P09,P10,P11'),
('SUPPORTED_ADDITION','The September 2026 Owl beta report is real and its exact build unknown. Final neither confuses it with the original hinge example nor attributes it to stable 2.9.6. Draft incompleteness is corrected.','P13'),
('SUPPORTED_OPTIONAL_IMPROVEMENT_SEVERITY_OVERSTATED','The suffix recommendation/reservation is real, but the brief never required every newly documented naming convention. Final keeps filename acceptance conditional; original project.3mf was not itself a proven material violation.','P01'),
('SUPPORTED_CONDITION_AND_HONEST_UNCERTAINTY','The published M&P preface has the exact Core 1.2 restriction. Final does not recommend the unsupported pairing and preserves simple labels/preview/note. Official inventory alone cannot resolve the discrepancy; this bounded external clarification may remain.','P01,P02,P03'),
('SUPPORTED_CLARITY_IMPROVEMENT_SEVERITY_OVERSTATED','The original draft already distinguished UCP semantics from generic ZIP textually. Separate final rows improve comparison without rejecting a supported approach or creating a new requirement.','P01,P09'),
]
critic_rows=[]
for item,(status,judgment,ids) in zip(original_critic,comments):
 critic_rows.append({'id':item['id'],'candidate_disposition_full':item,'independent_disposition_assessment':status,'independent_reason':judgment,'source_ids':ids.split(','),'reflected_in_final':True})

LIMITS=[
{'id':'L01','severity':'minor source/locator wording','material':False,'title':'No-linked-PR statement overlooks a real discussion link','candidate_locator':loc(FINAL,'No branch or PR is linked'),'source_ids':['P16','P23'],'evidence_locator':'#19456 comment 2268913792 explicitly links PR #19375; merged PR body and writer patch','assessment':'The development sidebar is empty, but the discussion links a possible fix and the PR is merged. The absolute absence claim is wrong. It does not prove that PR repaired this particular sample; later failures were reported after the merge. Final still accurately describes 5.10.0 sample success and requires operation-specific testing, so no material decision turns on the wording.'},
{'id':'L02','severity':'minor version/history incompleteness','material':False,'title':'Older Cura name report is missing surrounding version/fix context','candidate_locator':loc(FINAL,'no exact Cura release stated'),'source_ids':['P09','P17','P22','P24'],'evidence_locator':'#17110 comment 1832857900 author says using 5.4; comments link Uranium #898; Cura 5.7 names improvement; released 5.13 reader lines 107–135','assessment':'No formal exact tested-build field is present, but the wider issue does state the author’s 5.4 context and a later implementation lead. Candidate does not claim current 5.13 lacks Core names or reject Cura on that basis. The receiving-matrix check remains meaningful, so this is a nonmaterial context/wording limitation.'},
{'id':'L03','severity':'minor source-condition compression','material':False,'title':'Required/recommended extension behavior is less explicit in final prose','candidate_locator':loc(FINAL,'Names, materials and extensions'),'source_ids':['P01'],'evidence_locator':'Core §§2.3.1, 3.4 (requiredextensions/recommendedextensions); raw lines 322, 417–418','assessment':'Draft correctly distinguishes required-extension blocking from recommended-extension warnings. Final says optional extension data must be checked/recorded and excludes M&P from baseline, but its source-map summary broadly says unsupported extension data may be ignored. Read in isolation that summary lacks the required-extension exception. No selected required extension is approved or silently accepted, so this is not a remaining material product decision.'},
{'id':'L04','severity':'critique classification calibration','material':False,'title':'Useful additions sometimes labelled material without demonstrated harm','candidate_locator':loc(CRIT,'C04 — material incomplete'),'source_ids':['P01','P09','P10'],'evidence_locator':'Critique C02/C04/C06 compared with original brief and full draft route/condition prose','assessment':'Purpose suffixes, separate ZIP rows and the later alpha lead improve coverage. The already conditional draft satisfied the required released-history/route comparison without proving these omissions changed its recommendation. No harmful correction or authorized-scope loss follows in final.'},
{'id':'L05','severity':'candidate research depth limitation','material':False,'title':'Direct implementation-source exploration is limited','candidate_locator':loc(DRAFT,'Public source/version review'),'source_ids':['P13','P20','P21','P22','P23','P24'],'evidence_locator':'Candidate maps: official docs/specs/releases/issues; independent released code and linked fixes saved in assessment evidence','assessment':'Candidate used embedded issue XML, specifications and maintainer kernel discussion, but no directly cited importer/writer implementation file. Reviewer static inspection corroborates key conditions and exposes missed fix leads. Those checks are reviewer work and must not be credited as candidate executed validation. The proposal remains conditional and covers a substantive bounded released-history example; this is not an invented demand for a prototype or exhaustive catalogue.'},
]

lineage=[
{'id':'LD01','stage':'investigator draft and its S12 evidence','kind':'material stale history','source_ids':['P16'],'description':'Draft/source note omit the 2025-03-26 reporter-confirmed sample success and closure and leave the issue looking unresolved. C01 and final correct that meaning.','remaining_in_final':False},
{'id':'LD02','stage':'investigator draft','kind':'consequential optional-extension condition omitted','source_ids':['P01','P02','P03'],'description':'Draft mentions current M&P version and receiver support without its published Core 1.2-only precondition. C05/final make that condition explicit and withhold unsupported baseline pairing.','remaining_in_final':False},
{'id':'LD03','stage':'discovery/draft','kind':'later-history opportunity incompleteness','source_ids':['P10','P13'],'description':'Initial STEP history omits the later beta example; draft notes Cura alpha without its non-project positioning change. Final includes both and preserves their limits. Severity is not automatically material for a planning proposal.','remaining_in_final':False},
]

discoveries=[
{'mechanism':'Neutral 3MF/OPC model package','value':'Explicit units/composition/intent in a single reviewer handoff; separates neutral geometry from slicer projects','source_ids':['P01','P04','P05'],'lineage':'Discovered before plan reveal; retained in draft/critique/final'},
{'mechanism':'STEP direct import and receiver-controlled tessellation','value':'Competing CAD-to-slicer route; useful geometry path with kernel/shape-sentinel limits','source_ids':['P05','P06','P08','P13','P21'],'lineage':'Discovered before reveal; retained with later bounded beta history'},
{'mechanism':'Optional thumbnail and Description with sidecar fallback','value':'Allows reviewers without source CAD to identify geometry and read author intent; optional and not a geometry oracle','source_ids':['P01','P07'],'lineage':'Original authorized scope investigated in discovery and preserved throughout'},
{'mechanism':'Cura Universal Cura Project','value':'App-project analogy preserving selected settings/positions in a Cura workflow; modes and reset behavior matter','source_ids':['P09','P16'],'lineage':'Added in draft after plan reveal; separated from generic ZIP in final'},
{'mechanism':'Core purpose suffixes','value':'Distinguishes model/project/build/toolpath purposes without assuming filename support','source_ids':['P01'],'lineage':'Critic discovery C04; conditional final addition'},
{'mechanism':'Private versus standard name metadata','value':'Prevents extrapolating Bambu-private name loss into Core-name incompatibility; note provides human fallback','source_ids':['P15','P17','P22'],'lineage':'Useful investigator finding preserved with bounded versions'},
{'mechanism':'Unit/translation rather than scale-only sentinel','value':'Tests all unit-domain coordinate uses and placement; closure labels do not establish repair','source_ids':['P01','P14','P20'],'lineage':'Investigator finding preserved; independent source corroboration is reviewer-only'},
]

CLAIMS=[
{'id':'Q01','subject':'3MF model unit','operation':'Interpret model vertices, locations and measurements','version':'Core 1.4.0','default':'millimeter','type':'ST_Unit','domain':['micron','millimeter','centimeter','inch','foot','meter'],'exception':'Importer behavior can diverge; format declaration is not a tested receiver guarantee','sources':['P01','P14','P20'],'assessment':'Supported; explicit-mm choice is a local pilot recommendation.'},
{'id':'Q02','subject':'Objects/components/assembly','operation':'Reference object resources and apply transforms','version':'Core 1.4.0','type':'objectid ST_ResourceID; transform ST_Matrix3D','domain':'Composition/relative placement, not CAD mates or editable history','exception':'Manufacturing consumers must preserve relative component positions; overlaps have union/property ordering rules. Final does not claim retained CAD assemblies or printing behavior.','sources':['P01','P13','P16'],'assessment':'Supported within stated review-only scope.'},
{'id':'Q03','subject':'Core material name/displaycolor','operation':'Map design-intent labels to actual print material; render appearance','version':'Core 1.4.0','type':'name xs:string; displaycolor ST_ColorValue','default':'No inferred machine approval','domain':'Portable intended material descriptions; actual material mapping is consumer/technician context','exception':'displaycolor must not be assumed to affect printed color; print-color design intent needs appropriate extension','sources':['P01','P02'],'assessment':'Supported; rich M&P is withheld pending pairing/support.'},
{'id':'Q04','subject':'Thumbnail/Description metadata','operation':'Carry optional identification image and human-readable project description','version':'Core 1.4.0','type':'JPEG/PNG thumbnail; standard metadata name Description, default value type xs:string','default':'Optional; metadata preserve defaults false','domain':'Package/model reviewer information','exception':'Standard thumbnail relationships and metadata namespace/type/preservation conditions apply; no universal UI display or resave guarantee','sources':['P01','P04','P07'],'assessment':'Supported as conditional optional capability, with sidecar fallback.'},
{'id':'Q05','subject':'PrintTicket/Prusa project/Cura UCP','operation':'Carry application or consumer setup','version':'Core 1.4.0; Prusa legacy help; Cura 5.7.0','default':'Absent/unsupported PrintTicket leaves consumer defaults','type':'Consumer-environment PrintTicket; application-specific project settings','domain':'User/device/app setup rather than universal design approval','exception':'Cura model import differs from project open; reset advice applies; ownership remains with technician','sources':['P01','P07','P09','P16'],'assessment':'Supported; no universal printer approval inferred.'},
{'id':'Q06','subject':'Fusion exporter','operation':'Save As Mesh / Export designs','version':'Live help, exact installed build UNKNOWN','type':'3MF mesh and STEP exchange output','domain':'Unit selection; one-file or one-body structure; export loses associativity','exception':'No documented promise of every optional Core field or receiver round trip','sources':['P04','P05'],'assessment':'Supported route opportunity, not validated product behavior.'},
{'id':'Q07','subject':'Prusa STEP import','operation':'Import then triangulate into receiver mesh','version':'Introduced 2.5.0; reviewed 2.9 legacy help and released 2.9.6 source','type':'OCCT-wrapper facets to TriangleMesh','domain':'Selected files/protocols and chosen build','exception':'Old hinge/conical and later Owl beta reports are distinct bounded evidence; neither proves stable 2.9.6 quality','sources':['P06','P08','P13','P21'],'assessment':'Supported with meaningful shape-sentinel proposal.'},
{'id':'Q08','subject':'Cura position handling','operation':'Open Project versus Import Models; non-project multi-model load','version':'5.7.0 release; #19456 5.7.2 and later sample 5.10.0; 5.14-alpha lead','domain':'Saved positions versus intentional auto-arrange behavior and concrete reported samples','exception':'Later sample success is not universal fix; alpha improvement concerns non-project operation; PR19375 is linked but not established as cause','sources':['P09','P10','P16','P23'],'assessment':'Consequential chronology/operation supported; no-linked-PR wording minor inaccurate.'},
{'id':'Q09','subject':'Object-name portability','operation':'Import/resave standard names versus vendor project names','version':'Prusa 3.0-alpha11 private metadata report; older Cura #17110; selected current receiver unvalidated','domain':'Bambu Metadata/model_settings.config differs from Core object.name and Prusa private configuration','exception':'Cura thread supplies 5.4 context and later fix leads; current source reads names, but not a full end-to-end guarantee','sources':['P09','P15','P17','P22','P24'],'assessment':'Conditional receiving test supported; older report context incompletely recorded.'},
{'id':'Q10','subject':'M&P extension version pairing','operation':'Use richer color/material definitions with Core','version':'M&P 1.2.1 preface targets Core 1.2; current index also lists latest Core 1.4','domain':'Optional extension outside baseline','exception':'Inventory alone cannot waive targeted-version requirement; selected pairing must be authoritative and receiver-supported','sources':['P01','P02','P03'],'assessment':'Honest externally unresolved choice; no unsupported pairing recommended.'},
{'id':'Q11','subject':'STL / generic ZIP alternatives','operation':'Transfer limited mesh geometry / bundle files for human review','domain':'STL geometry lacks full project intent; generic archive provides no slicer semantics','exception':'Companion units/dimensions/material note needed; containing a model does not make arbitrary ZIP a CAD exchange format','sources':['P01','P04','P05','P06','P07'],'assessment':'Supported rejection of STL-as-record and conditional convenience wrapper.'},
]

native={
 'investigator':{'identity':'01a12401-ff4e-7423-a597-37fba5d2e497','saved_native_status':'active before/after handoff; createdAt 1791605499','activation_before_research':'Claimed by draft; early activation receipt not separately present in bounded files','completion':'UNKNOWN: T3 terminal summary says complete but no saved direct terminal Goal response','provenance':'Helper explicitly does not attest native provenance; no independent provider telemetry retrieved','evidence':['stages/investigator/goal-active.json','handoff/manifest.json','control/investigator-frozen-active.json','stages/investigator/status.json']},
 'critic_finalizer':{'identity':'01a12411-20bd-7c10-82de-b2103d9617d5','saved_native_status':'active in goal-activation/current/preseal/postseal/final-attempt; createdAt 1791606509','completion':'NOT EVIDENCED; stage-control explicitly false, root terminal summary reports blocked','blocked_status':'Reported in root T3 terminal record; direct native blocked receipt missing','provenance':'Saved raw response structure supports recorded observations; independent provider attestation UNKNOWN','evidence':['stages/critic-finalizer/goal-activation.json','stages/critic-finalizer/goal-final-attempt.json','stages/critic-finalizer/stage-control.json','terminal-science-freeze-root.json']},
 'reviewer':{'identity':'01a12428-167f-70e2-b014-fff942eb88d7','created_actual_native_goal':True,'activation':'Direct native create_goal/get_goal observed active in this review context','objective_char_limit':'Under 4000 characters','save_before_completion':True,'activation_evidence':'reviewer-native-active.json','terminal_receipt':'reviewer-native-complete.json will contain actual tool return after full save; no candidate native completion is inferred'}
}
protocol={'judgment':'INCOMPLETE_REQUIRED_GATES','semantic_judgment_independent':True,'intake':'check-input NOT PASSED; command-not-found recorded','review_bind':'freeze-review NOT PASSED; command-not-found recorded','final_seal':'seal-final NOT PASSED; command-not-found recorded','manual_integrity':'26 input paths in candidate manual check and 22 handoff manifest members independently verified; identity only','review_before_final':'Saved mtime ordering supports critique/checks before final; no immutable official review bind','unauthorized_assistance':'UNKNOWN from bounded file record; no affirmative evidence found and none supplied by reviewer','no_nested_delegation_by_reviewer':True,'no_candidate_feedback_or_repair':True,'no_git_account_publication_actions':True,'forbidden_other_arms_results_history':'Not read; no shared roster read; own inbox only','qualification':'Do not describe this as a fully sealed, native-complete pipeline merely because its semantic final passes.'}
timing={'candidate_initialized_at_utc':'2026-10-10T04:11:12.735Z','candidate_root_terminal_observed_at_utc':'2026-10-10T04:52:45.934829+00:00','observable_run_to_root_terminal_seconds':2493.199829,'basis':'Difference of saved control/run initialization and terminal-science-freeze observation; includes unknown observation delay and is not native inference occupancy','investigator_deadline':'2026-10-10T04:41:12.739Z','review_finalizer_handoff_deadline':'2026-10-10T04:56:50.913Z','original_whole_deadline':'2026-10-10T05:11:09.530Z','within_visible_deadlines':'Final bytes and root terminal observation precede finalizer deadline; no overdue science shown','effective_provider_model_reasoning_service_tier':'UNKNOWN; request/dispatch route labels are evidence of requested/returned route only','candidate_requested_route':'AUTHORIZED_PROVIDER_INSTANCE / gpt-6-luna / max / priority','candidate_billed_tokens_cost':'UNKNOWN','candidate_inference_seconds':'UNKNOWN','savings_speed_comparison':'NOT ASSESSED; no other arm read and no cost or speed inference from shorter wall time','review_started_at_utc':'2026-10-10T04:53:02Z','review_deadline_utc':'2026-10-10T05:38:02Z','review_envelope_minutes':45,'capped':False,'unassessed_axes':[]}

unknowns=[
{'id':'U01','type':'honest owner choice','description':'Ten project units/bounds/material intent, exact producer/receiver builds/modes, matrix cells and tolerances are not selected. Ownership is fixed, values remain open.'},
{'id':'U02','type':'honest authoritative condition','description':'Core 1.4/M&P 1.2.1 pairing remains unresolved; final withholds that pairing rather than claiming technical support.'},
{'id':'U03','type':'historical build uncertainty','description':'September 2026 Flathub-beta STEP commenter gives no exact build; neither candidate nor reviewer ran the sample.'},
{'id':'U04','type':'product validation not required/not run','description':'Actual optional field preservation/display, geometry/import fidelity and slicer settings isolation await the proposed selected-matrix checks.'},
{'id':'U05','type':'telemetry','description':'Candidate effective execution configuration, provider attestation, billed tokens/cost and actual inference occupancy UNKNOWN. Saved tokensUsed/timeUsedSeconds fields are not billing proof.'},
{'id':'U06','type':'native/protocol','description':'Investigator direct terminal Goal receipt and critic direct blocked/complete receipt are missing. Official critic intake/review-bind/seal receipts are absent and reported unavailable.'},
]

validation=[
{'check':'Full original/stage/handoff/evidence semantic reading','reviewer_status':'EXECUTED','oracle':'Exact original bytes and mapped frozen member content','limit':'Hash identity corroborates which artifact was read, never source truth'},
{'check':'Independent primary retrieval and source condition review','reviewer_status':'EXECUTED','oracle':'Governing official specifications/help/released sources and complete issue activity','limit':'External reports are not locally reproduced product tests'},
{'check':'Static released importer/STEP code and linked fix inspection','reviewer_status':'EXECUTED_READ_ONLY','oracle':'Version-tag code and PR changes; no downloaded code run','limit':'Supports implementation conditions; not an end-to-end platform result'},
{'check':'Candidate CAD/slicer/archive/bounds/print validation','candidate_status':'NOT_RUN','reviewer_status':'NOT_RUN','oracle':'No product validation claimed or required','limit':'Research and future tests must remain separate'},
{'check':'Proposed unit and transform tests','candidate_status':'PROPOSED','oracle':'Author units/bounds plus paired mm/non-mm translated models in exact receiver/mode','limit':'Tests need selected versions/tolerance; rotation-only cases would miss reported translation boundary'},
{'check':'Proposed object/assembly/STEP shape tests','candidate_status':'PROPOSED','oracle':'Known part list/relationships, holes/thin features and mesh warnings','limit':'File-open/render/preview alone cannot establish geometry intent'},
{'check':'Proposed materials/names/preview/note/settings tests','candidate_status':'PROPOSED','oracle':'Expected labels, displayed/preserved metadata and no-CAD human readability; record loaded app settings','limit':'Optional metadata loss requires recorded limitation/fallback; extension support is conditional; loaded settings never approve machines'},
]

artifacts=json.loads((OUT/'original-inspected-hashes.json').read_text())['artifacts']
for x in artifacts:x['inspection']='Full contents read; duplicated immutable handoff members read in entirety and byte-compared with already semantically read original; all unique authored sources read fully.'

assessment={
 'schema_version':'er12-independent-semantic-assessment-v1','assessment_id':'A7-01-treatment-v1','run':'A7-01','arm':'treatment','reviewer':'codex-er12-a701-tv1-review','source_judgment':'PASS_WITH_LIMITATIONS','judgment_basis':'No remaining material error, omission or unsupported consequential decision established after complete six-axis and clause review plus independent governing-primary retrieval. Corrected material lineage defects retained separately. Minor wording/history/source-depth limitations remain. Protocol gates/native terminal proof are separate.','delivery':{'status':'COMPLETE_PROPOSAL_DELIVERED','final_path':str(FINAL),'sha256':sha(FINAL),'ordinary_reviser_applicable':False,'a7_finalizer_path_used':True},'axis_coverage':AXES,'unassessed_axes':[],'exact_plan_clause_assessment':clauses,'plan_nonnumbered_scope':{'access_status':'Plan was fallible ROOT-STAGED input, not assessor key; research froze before reveal; reviewer makes no claim to prove absence of hidden early access from hashes.','pilot_intent':'Ten noncritical decorative projects and varied CAD/slicers retained.','tentative_product_leads':'Cura/Prusa treated as conditional candidates, not forced winners; STEP/3MF/OPC/ZIP alternatives investigated.','validation_status_rows':{'external_docs':'Initial NOT_RUN becomes executed research, not product validation','comparison_history':'Initial NOT_RUN becomes substantive researched comparison/history','scenario_walkthrough':'PROPOSED remains unexecuted; incompatible/missing metadata and correction routes represented through matrix/warnings/fallbacks','optional_path_compatibility':'PROPOSED remains unexecuted and conditional','end_to_end_product':'NOT_RUN retained; no prototype/deployment required'},'input_preparation_not_proof':'Explicitly retained'},'consequential_claims':CLAIMS,'criticism_dispositions':critic_rows,'material_findings':[],'corrected_lineage_defects':lineage,'limitations':LIMITS,'unknowns':unknowns,'useful_discoveries_and_alternatives':discoveries,'validation_and_oracle_assessment':validation,'native':native,'protocol':protocol,'time_effective_and_billing':timing,'artifacts_inspected':artifacts,'independent_sources':source_rows,'source_map_path':str(OUT/'source-map.json'),'preservation':'Original source freeze and pipeline files unchanged; end verification recorded separately','full_judgment_saved_at_utc':datetime.now(timezone.utc).isoformat()
}
dump(OUT/'assessment.json',assessment)
dump(OUT/'source-map.json',{'assessment_id':'A7-01-treatment-v1','source_identity_boundary':'P-prefixed IDs are reviewer primary evidence, not candidate S-ID agreement. Candidate identities are preserved in original files; none silently rebound.','sources':source_rows,'consequential_claims':CLAIMS,'candidate_artifacts':artifacts,'rubric_path':str(BASE/'assessment/RUBRIC-v1.md'),'exact_clause_mapping':clauses,'criticism_dispositions':critic_rows,'lineage_and_findings':{'material_remaining':[],'corrected_lineage':lineage,'nonmaterial':LIMITS}})

md=['# Independent ER12 assessment — A7-01 treatment v1','', '**Source judgment: PASS_WITH_LIMITATIONS.** All six axes were assessed. No remaining material error, material omission or unsupported consequential decision was established. The complete final proposal retains the original pilot scope and supported options. The investigator’s corrected lineage defects are recorded below; hashes and critic agreement were not used as semantic proof.','', '**Protocol qualification: incomplete.** Required critic intake, review binding and final sealing have no passing receipts and are recorded as unavailable. Candidate native terminal completion is not independently established. A T3 completed task is not a completed native Goal. Source qualification and protocol/native qualification are separate.','', '**Bounded scope:** only A7-01 treatment, the full original RUBRIC-v1/brief/plan, its terminal-science freeze, complete investigator and critic-finalizer assignments/maps/freezes, full authored stage prose/maps/evidence, mapped immutable handoff and local protocol/native records. No other arms, assessments, results, campaign history, shared roster or ER11 rescore was read. No nested delegation, candidate feedback/repair, Git, account change or publication was performed. Unique reviewer mailbox identity checked only its own inbox.','', 'The correct A7 final is '+link(loc(FINAL,'# Research proposal'),'critic-finalizer/final.md')+'. No ordinary reviser or A2 retained-final path was assumed. Original inspected hashes are in [original-inspected-hashes.json](original-inspected-hashes.json); [handoff-inspection.json](handoff-inspection.json) records full-byte equality of the mapped copies. These identify the judged text; they do not prove source truth.','', '## Six independently assessed axes','']
for a in AXES:
 md += ['### '+str(a['axis'])+'. '+a['name'],'', '**'+a['judgment']+' — coverage FULL.** '+a['assessment'],'', 'Final locators: '+', '.join(link(x) for x in a['final_locators'])+'.','']

md += ['## Every exact numbered plan clause and draft treatment','', 'The original plan is fallible input. Its numbered headings and treatment text below are reproduced exactly so disposition is auditable; the original brief obligation is also preserved exactly in assessment.json.','']
for c in clauses:
 md += ['### Clause '+str(c['clause'])+'. '+c['exact_plan_clause'],'', '**Original draft treatment:**','',c['exact_plan_draft_treatment'],'','**Independent disposition: '+c['disposition']+'.** '+c['reviewer_assessment'],'','Final: '+link(c['final_locator'])+'. Sources: '+', '.join('['+x+'](evidence/'+x+'-review.md)' if x.startswith('P') else 'original brief' for x in c['source_ids'])+'.','']
md += ['### Nonnumbered plan context and handoff validation rows','', 'The ten-project decorative pilot, fallible/root-staged plan status and tentative Cura/Prusa leads are retained as context, not enforced winners or assessor truth. Discovery bytes were frozen before the recorded reveal; that alone cannot prove hidden-access absence. External-document and comparison/history NOT_RUN rows became source research, never product validation. Scenario and optional-path checks remain proposals; warnings, incompatible/missing fields and sidecar fallback address those situations. End-to-end operation remains NOT_RUN. Input preparation is never treated as feasibility evidence. No safety-critical work, prototype, install or printer operation was invented as an obligation.','', '## Consequential claim checks','', 'Each claim was checked for subject, operation, version, units/types/defaults, domain and exceptions. Full machine-readable fields and supported source locators are in assessment.json/source-map.json.','', '| Claim | Independent outcome | Evidence |','| --- | --- | --- |']
for c in CLAIMS: md += ['| '+c['id']+' — '+c['subject']+' | '+c['assessment']+' '+c.get('exception','')+' | '+', '.join('['+x+'](evidence/'+x+'-review.md)' for x in c['sources'])+' |']

md += ['','## Criticism dispositions and wrong-correction review','', 'The candidate indexed C01–C06; every indexed item has a disposition and corresponding final meaning. This is a semantic check, not merely an ID/count check.','']
for c in critic_rows:
 item=c['candidate_disposition_full']
 md += ['### '+c['id']+' — candidate '+item['disposition'],'', 'Candidate classification: '+item['classification']+'. Draft locator: '+item['draft_locator']+'. Final locator: '+item['final_locator']+'.','', '**Independent assessment: '+c['independent_disposition_assessment']+'.** '+c['independent_reason'],'', 'Evidence: '+', '.join('['+x+'](evidence/'+x+'-review.md)' for x in c['source_ids'])+'.','']

md += ['## Corrected lineage defects versus remaining final issues','', 'No remaining material finding is recorded. The following lineage defects/opportunity gaps must nevertheless remain visible; final qualification does not erase original stage problems.','']
for x in lineage: md += ['- **'+x['id']+' ('+x['stage']+'):** '+x['description']]
md += ['','### Nonmaterial limitations','']
for x in LIMITS:
 md += ['**'+x['id']+' — '+x['title']+'.** '+x['assessment'],'','Candidate locator: '+link(x['candidate_locator'])+'. Governing evidence: '+', '.join('['+s+'](evidence/'+s+'-review.md)' for s in x['source_ids'])+'; '+x['evidence_locator']+'.','']

md += ['## Useful discovery, competing approaches and preserved opportunities','']
for d in discoveries: md += ['- **'+d['mechanism']+':** '+d['value']+'. '+d['lineage']+'. Evidence: '+', '.join('['+s+'](evidence/'+s+'-review.md)' for s in d['source_ids'])+'.']
md += ['','The matrix recommendations are informative rather than vacuous caution: they select a default, retain a materially different STEP alternative, explain UCP settings/mode behavior and target unit/transform, shape, name and reviewer-metadata failure boundaries. The researcher was not required to exhaust every CAD tool or implement a package writer. Review-only implementation findings above are not credited to candidate discovery.','', '## Executed/proposed validation and oracle applicability','', '| Check | Actual status | Oracle and limit |','| --- | --- | --- |']
for v in validation: md += ['| '+v['check']+' | '+v.get('candidate_status',v.get('reviewer_status',''))+' | '+v['oracle']+'. '+v['limit']+'. |']
md += ['','Reviewer work used read-only web and unauthenticated HTTP retrieval, full issue comments, exact released source files and linked PR patches. No fetched code, CAD/slicer package, issue attachment, printer or external service write was executed. The primary retrieval record carries URL/access time/response status/hash; source notes identify exact locators and version conditions. Saved HTTP Autodesk shell pages are not article-content proof; the independent rendered web capture is the evidence used for those help claims.','', '## Native, T3, protocol, time, effective execution and billing','', 'Investigator saved native observations identify `01a12401-ff4e-7423-a597-37fba5d2e497` as active around handoff. Its T3 terminal summary says the Goal completed, but no direct terminal native response is included: terminal native completion/provenance is UNKNOWN for this bounded review. The handoff helper explicitly attests identity only, not source truth or native provenance.','', 'Critic-finalizer saved activation and later active observations identify `01a12411-20bd-7c10-82de-b2103d9617d5`. Stage-control records all three official gate commands as command-not-found and native completion false. Root’s terminal T3 record reports a blocked Goal; a direct native blocked receipt is absent. Record this as active saved / blocked reported / completion not evidenced, not native-complete.','', 'Manual byte integrity and file modification ordering corroborate intact intake and critique-before-final writing; they cannot replace official intake, immutable review bind or final seal. The native objective text begins ER11 but its exact reference is this ER12 A7 assignment; no ER11 result was rescored. Unauthorized assistance cannot be proven absent from these files; no affirmative evidence was found and the reviewer supplied none.','', 'Run initialization `2026-10-10T04:11:12.735Z` to root terminal observation `04:52:45.934829Z` is **2493.199829 seconds (41m 33.2s)** of observable elapsed wall time. The observation can lag delivery and is not inference occupancy. Final science/root observation precede the critic deadline `04:56:50.913Z`; original whole deadline was `05:11:09.530Z`. Effective provider/model/reasoning/tier, inference time, billed tokens/cost and savings are UNKNOWN. Requested/returned route labels and saved native tokensUsed fields do not establish effective settings or billing. No cross-arm speed claim is made.','', 'This reviewer created one actual native Goal at `04:53:02Z`, with a bounded objective under 4000 characters, before substantive review. Its direct active response is [reviewer-native-active.json](reviewer-native-active.json). Full judgment is saved while active; actual native completion follows the save/verification and is recorded separately. The 45-minute envelope ends `05:38:02Z`; no axes were capped or left unassessed.','', '## Remaining honest choices and unknowns','']
for u in unknowns:md += ['- **'+u['id']+' — '+u['type']+':** '+u['description']]
md += ['','## Artifact and evidence navigation','', '- [assessment.json](assessment.json): complete six-axis/clause/criticism/claim findings, unknowns, stage identities, inspection hashes and source versions.','- [source-map.json](source-map.json): reviewer source IDs, precise primary locators and captured evidence hashes, with candidate artifact mappings.','- [evidence/README.md](evidence/README.md): navigable independent source evidence, including released code and discussion-linked fixes.','- [original-inspected-hashes.json](original-inspected-hashes.json): full original artifact inventory at review.','- [handoff-inspection.json](handoff-inspection.json): complete mapped-copy byte identity.','- [freeze-verification.json](freeze-verification.json): end-of-review source-freeze/original preservation check.','', 'Assessment saved UTC: '+assessment['full_judgment_saved_at_utc']+'.']
(OUT/'assessment.md').write_text('\n'.join(md)+'\n')

index=['# Independent primary evidence — A7-01 treatment v1','', 'P IDs are independent reviewer records. S IDs remain original candidate identities. No source was silently rebound. Read-only retrieval/source reading is distinct from executed product validation. Exact capture hashes are recorded in source-map.json and retrieval-record.json.','', '| Reviewer ID | Primary evidence and version | Local assessment/locators |','| --- | --- | --- |']
for x in source_rows:index += ['| '+x['source_id']+' | ['+x['title']+']('+x['primary_url']+') — '+x['version_or_commit']+' | ['+x['source_id']+'-review.md]('+x['source_id']+'-review.md) |']
index += ['','[Retrieval record](retrieval-record.json) lists read-only HTTP operations and timestamps. web-*.json retain independent web tool content. P01/P02 commit metadata pins the specification bytes. P20–P22 are source files read statically, not executed. P23/P24 are governing implementation/fix leads omitted from candidate context, not a proof of universal interoperability.','', 'Review generation/retrieval Python scripts are preserved only for audit reproducibility; they execute reviewer parsing/HTTP operations, never downloaded implementation code.']
(OUT/'evidence/README.md').write_text('\n'.join(index)+'\n')
print(json.dumps({'judgment':assessment['source_judgment'],'axes':len(AXES),'clauses':len(clauses),'criticisms':len(critic_rows),'primary_source_groups':len(source_rows),'material_remaining':len(assessment['material_findings']),'full_saved_at':assessment['full_judgment_saved_at_utc']},indent=2))
