"""Prove narrowly declared additions and all original frozen/runtime byte identities."""
import ast,hashlib,json,pathlib,datetime
HERE=pathlib.Path(__file__).resolve().parent
start=json.loads((HERE/'START.json').read_text());OLD=pathlib.Path(start['predecessor_path']);pin=json.loads((OLD/'PIN.json').read_text())
def sha(b):return hashlib.sha256(b).hexdigest()
oldfiles={name:sha((OLD/name).read_bytes())==digest for name,digest in pin['files'].items()};assert all(oldfiles.values())
g=(HERE/'glm_stage.py').read_text();g=g.replace('import readiness\n','',1)
addition="    def resource_gate_owners(self):\n        return [{'component':'native','guard_pid':self.process.pid,'record_path':str(self.output/'native-host.json')},\n                *[{'component':b.server['name'],'guard_pid':b.proc.pid,\n                   'record_path':str(self.output/(b.server['name']+'-resource.json'))} for b in self.bridges]]\n\n"
assert addition in g;g=g.replace(addition,'',1)
new="            owners=client.resource_gate_owners()\n            readiness.wait_for_resource_gates(owners,profile.load(args.resource_profile),\n                profile.sha(args.resource_profile),deadline-30,client.poll)"
old="            resource_records=[out/'native-host.json',*[out/(server['name']+'-resource.json') for server in servers]]\n            while not all(path.exists() and json.loads(path.read_text()).get('verified_before_command_exec') is True for path in resource_records):\n                if time.monotonic()>=deadline-30: raise TimeoutError('Original native stop before resource gates')\n                client.poll(.1)"
assert new in g;g=g.replace(new,old,1);addition="\n        if isinstance(exc,readiness.OwnedComponentReadinessTerminated):\n            receipt['pre_goal_readiness_failure']=exc.evidence";assert addition in g;g=g.replace(addition,'',1);assert g==(OLD/'glm_stage.py').read_text()
c=(HERE/'component_guard.py').read_text().replace('import readiness\n','',1);addition="    readiness.write_owner_intent(resource,a.resource_profile,record,unit,a.component,os.getpid(),outer['unit_observation']['ControlGroup'],a.stop_ns)\n";assert addition in c;c=c.replace(addition,'',1);assert c==(OLD/'component_guard.py').read_text()
p=(HERE/'profile.py').read_text();p=p.replace(start['version'],pin['version']).replace("'task_fragment.py','readiness.py')","'task_fragment.py')");assert p==(OLD/'profile.py').read_text()
unchanged={n:sha((HERE/n).read_bytes()) for n in ('stage_worker.py','native_support.py','component_gate.py','native_guard.py','pipe_bridge.py','pipe_proxy.py','external_release.py','clock_binding.py','task_fragment.py')};assert all(pin['files'][n]==digest for n,digest in unchanged.items())
functions={}
for name in ('original_clock','tool_profile','preactivation_proof','component_records_quiet','close_components'):
 text=(HERE/'profile.py').read_text();original=(OLD/'profile.py').read_text();get=lambda s:next(ast.get_source_segment(s,n) for n in ast.parse(s).body if isinstance(n,ast.FunctionDef) and n.name==name);assert get(text)==get(original);functions[name]=sha(get(text).encode())
out={'schema':'er9.glm.readiness-source-preservation.v1','observed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'predecessor_pin':{'path':str(OLD/'PIN.json'),'sha256':sha((OLD/'PIN.json').read_bytes())},'all_original_pinned_files_unchanged':oldfiles,'unchanged_runtime_files':unchanged,'exact_inverse_additions_restore_predecessor_files':['glm_stage.py','component_guard.py','profile.py'],'unchanged_enforcement_functions':functions,'component_guard_preservation':'original caps, placement, RuntimeMax, owner EOF, signal handling and finally/recursive quiet code identical after removing ownership-intent addition','native_driver_preservation':'all RPC/model/Goal/response/clock/cleanup logic identical after removing declared readiness additions','no_model_or_native_Goal_calls':0}
(HERE/'SOURCE_PRESERVATION.json').write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps({'result':'PASS','old_pins_checked':len(oldfiles),'unchanged_runtime_files':len(unchanged),'enforcement_functions':len(functions),'only_modified_runtime_files':['glm_stage.py','component_guard.py','profile.py']}))
