/**
 * Login command - Platform authentication wizard (P0-G25)
 *
 * Implements the `puppet-master login [platform]` command that:
 * - Guides users through credential setup for each platform
 * - Saves environment variables to .env file
 * - Warns about .gitignore for security
 *
 * Per BUILD_QUEUE_GAPS.md P0-G25 (No Login/Authentication Wizard).
 */

import { Command } from 'commander';
import * as readline from 'node:readline';
import { readFile, writeFile } from 'fs/promises';
import { join } from 'path';
import type { Platform } from '../../types/config.js';
import { getPlatformAuthStatus } from '../../platforms/auth-status.js';
import type { CommandModule } from './index.js';

const PLATFORMS: Platform[] = ['cursor', 'codex', 'claude', 'gemini', 'copilot'];

/**
 * Platform authentication configuration
 */
interface PlatformAuthConfig {
  envVar: string;
  description: string;
  getUrl: string;
  format: string;
  altEnvVar?: string;
  needsCli?: boolean;
  cliAuthCommand?: string;
}

/**
 * Configuration for each platform's authentication
 */
const PLATFORM_AUTH_CONFIG: Record<Platform, PlatformAuthConfig> = {
  cursor: {
    envVar: 'CURSOR_API_KEY',
    description: 'Cursor Agent supports interactive login (`agent login`) or CURSOR_API_KEY for headless usage.',
    getUrl: 'https://cursor.com',
    format: '(varies)',
    needsCli: true,
    cliAuthCommand: 'agent login',
  },
  codex: {
    envVar: 'OPENAI_API_KEY',
    description: 'OpenAI API key for Codex CLI.',
    getUrl: 'https://platform.openai.com/api-keys',
    format: 'sk-...',
  },
  claude: {
    envVar: 'ANTHROPIC_API_KEY',
    description: 'Anthropic API key for Claude Code.',
    getUrl: 'https://console.anthropic.com/settings/keys',
    format: 'sk-ant-...',
  },
  gemini: {
    envVar: 'GEMINI_API_KEY',
    altEnvVar: 'GOOGLE_API_KEY',
    description: 'Gemini CLI credentials (API keys or Google credentials depending on setup).',
    getUrl: 'https://github.com/google-gemini/gemini-cli',
    format: 'AIza...',
  },
  copilot: {
    envVar: 'GH_TOKEN',
    altEnvVar: 'GITHUB_TOKEN',
    description: 'GitHub token with Copilot permission.',
    getUrl: 'https://github.com/settings/tokens',
    format: 'ghp_... or gho_...',
    needsCli: true,
    cliAuthCommand: 'copilot login',
  },
};

/**
 * Options for the login command
 */
export interface LoginOptions {
  all?: boolean;
  envFile?: string;
}

/**
 * Create a readline interface for user input
 */
function createReadline(): readline.Interface {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
}

/**
 * Prompt user for input
 */
async function prompt(rl: readline.Interface, question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer.trim());
    });
  });
}

/**
 * Prompt user for yes/no confirmation
 */
async function confirm(rl: readline.Interface, question: string): Promise<boolean> {
  const answer = await prompt(rl, `${question} (y/N): `);
  return answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes';
}

/**
 * Read .env file and parse it into key-value pairs
 */
async function readEnvFile(envPath: string): Promise<Map<string, string>> {
  const envMap = new Map<string, string>();
  try {
    const content = await readFile(envPath, 'utf-8');
    const lines = content.split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith('#')) {
        const eqIndex = trimmed.indexOf('=');
        if (eqIndex > 0) {
          const key = trimmed.slice(0, eqIndex).trim();
          let value = trimmed.slice(eqIndex + 1).trim();
          // Remove quotes if present
          if ((value.startsWith('"') && value.endsWith('"')) ||
              (value.startsWith("'") && value.endsWith("'"))) {
            value = value.slice(1, -1);
          }
          envMap.set(key, value);
        }
      }
    }
  } catch {
    // File doesn't exist, return empty map
  }
  return envMap;
}

/**
 * Write .env file from key-value pairs
 */
async function writeEnvFile(envPath: string, envMap: Map<string, string>): Promise<void> {
  const lines: string[] = [];
  lines.push('# RWM Puppet Master environment variables');
  lines.push('# Generated by: puppet-master login');
  lines.push('# WARNING: Do not commit this file to version control!');
  lines.push('');
  
  for (const [key, value] of envMap) {
    // Quote values with spaces or special characters
    if (value.includes(' ') || value.includes('#') || value.includes('$')) {
      lines.push(`${key}="${value}"`);
    } else {
      lines.push(`${key}=${value}`);
    }
  }
  lines.push('');
  
  await writeFile(envPath, lines.join('\n'), 'utf-8');
}

/**
 * Check if .gitignore contains .env
 */
async function isEnvInGitignore(): Promise<boolean> {
  try {
    const gitignorePath = join(process.cwd(), '.gitignore');
    const content = await readFile(gitignorePath, 'utf-8');
    const lines = content.split('\n').map(l => l.trim());
    return lines.some(line => 
      line === '.env' || 
      line === '.env*' || 
      line === '*.env' ||
      line === '.env.local'
    );
  } catch {
    return false;
  }
}

/**
 * Add .env to .gitignore if not present
 */
async function addEnvToGitignore(): Promise<void> {
  const gitignorePath = join(process.cwd(), '.gitignore');
  let content = '';
  try {
    content = await readFile(gitignorePath, 'utf-8');
    if (!content.endsWith('\n')) {
      content += '\n';
    }
  } catch {
    // File doesn't exist
  }
  
  content += '\n# RWM Puppet Master credentials\n.env\n';
  await writeFile(gitignorePath, content, 'utf-8');
}

/**
 * Setup authentication for a single platform
 */
async function setupPlatform(
  rl: readline.Interface,
  platform: Platform,
  envMap: Map<string, string>
): Promise<boolean> {
  const config = PLATFORM_AUTH_CONFIG[platform];
  const authStatus = getPlatformAuthStatus(platform);
  
  console.log(`\n${'='.repeat(50)}`);
  console.log(`  ${platform.toUpperCase()} Authentication`);
  console.log(`${'='.repeat(50)}`);
  console.log(`\nDescription: ${config.description}`);
  
  // Show current status
  if (authStatus.status === 'authenticated') {
    console.log(`\n✅ Status: Already authenticated`);
    console.log(`   ${authStatus.details}`);
    const proceed = await confirm(rl, '\nUpdate credentials anyway?');
    if (!proceed) {
      return false;
    }
  } else if (authStatus.status === 'skipped') {
    console.log(`\nℹ️  ${authStatus.details}`);
    if (config.cliAuthCommand) {
      console.log(`   ${config.cliAuthCommand}`);
    }
    return false;
  } else {
    console.log(`\n❌ Status: Not authenticated`);
    if (authStatus.fixSuggestion) {
      console.log(`   ${authStatus.fixSuggestion}`);
    }
  }
  
  // Platforms that use CLI auth instead of API keys
  if (config.needsCli && !config.envVar) {
    console.log(`\nThis platform uses CLI-based authentication.`);
    if (config.cliAuthCommand) {
      console.log(`To authenticate: ${config.cliAuthCommand}`);
    }
    return false;
  }
  
  // Show how to get credentials
  console.log(`\nTo get your API key:`);
  console.log(`  1. Visit: ${config.getUrl}`);
  console.log(`  2. Create or copy your API key`);
  if (config.format) {
    console.log(`  3. Expected format: ${config.format}`);
  }
  
  // Prompt for API key
  const apiKey = await prompt(rl, `\nEnter your ${config.envVar} (or press Enter to skip): `);
  
  if (!apiKey) {
    console.log('Skipped.');
    return false;
  }
  
  // Basic validation
  if (platform === 'codex' && !apiKey.startsWith('sk-')) {
    console.log('⚠️  Warning: OpenAI API keys typically start with "sk-"');
  } else if (platform === 'claude' && !apiKey.startsWith('sk-ant-')) {
    console.log('⚠️  Warning: Anthropic API keys typically start with "sk-ant-"');
  } else if (platform === 'gemini' && !apiKey.startsWith('AIza')) {
    console.log('⚠️  Warning: Google API keys typically start with "AIza"');
  }
  
  // Save to env map
  envMap.set(config.envVar, apiKey);
  console.log(`\n✓ ${config.envVar} saved to .env`);
  
  return true;
}

/**
 * Main login action
 */
export async function loginAction(
  platform: string | undefined,
  options: LoginOptions
): Promise<void> {
  const rl = createReadline();
  const envPath = options.envFile ?? join(process.cwd(), '.env');
  
  try {
    console.log('╔════════════════════════════════════════════════════════════╗');
    console.log('║      RWM Puppet Master - Platform Authentication Wizard    ║');
    console.log('╚════════════════════════════════════════════════════════════╝');
    
    // Check .gitignore first
    const envInGitignore = await isEnvInGitignore();
    if (!envInGitignore) {
      console.log('\n⚠️  SECURITY WARNING: .env is not in your .gitignore file!');
      console.log('   This could expose your API keys if committed to git.');
      const addToGitignore = await confirm(rl, '\nAdd .env to .gitignore now?');
      if (addToGitignore) {
        await addEnvToGitignore();
        console.log('✓ Added .env to .gitignore');
      } else {
        console.log('\n⚠️  Proceeding without adding to .gitignore. Be careful!');
      }
    }
    
    // Load existing .env
    const envMap = await readEnvFile(envPath);
    
    // Determine which platforms to configure
    let platformsToSetup: Platform[];
    
    if (options.all) {
      platformsToSetup = PLATFORMS;
    } else if (platform) {
      const normalizedPlatform = platform.toLowerCase() as Platform;
      if (!PLATFORMS.includes(normalizedPlatform)) {
        console.error(`\n❌ Unknown platform: ${platform}`);
        console.error(`   Valid platforms: ${PLATFORMS.join(', ')}`);
        process.exit(1);
      }
      platformsToSetup = [normalizedPlatform];
    } else {
      // Interactive platform selection
      console.log('\n📋 Available platforms:');
      PLATFORMS.forEach((p, i) => {
        const status = getPlatformAuthStatus(p);
        const statusIcon = status.status === 'authenticated' ? '✅' : 
                          status.status === 'skipped' ? '⏭️' : '❌';
        console.log(`  ${i + 1}. ${p} ${statusIcon}`);
      });
      
      console.log('\nEnter platform numbers to configure (comma-separated),');
      console.log('or press Enter to configure all unauthenticated platforms:');
      const selection = await prompt(rl, '\nSelection: ');
      
      if (!selection) {
        // Configure all unauthenticated platforms
        platformsToSetup = PLATFORMS.filter(p => {
          const status = getPlatformAuthStatus(p);
          return status.status !== 'authenticated' && status.status !== 'skipped';
        });
        if (platformsToSetup.length === 0) {
          console.log('\n✅ All platforms are already authenticated!');
          rl.close();
          return;
        }
      } else {
        // Parse selection
        const indices = selection.split(',').map(s => parseInt(s.trim(), 10) - 1);
        platformsToSetup = indices
          .filter(i => i >= 0 && i < PLATFORMS.length)
          .map(i => PLATFORMS[i]);
        
        if (platformsToSetup.length === 0) {
          console.error('\n❌ No valid platforms selected.');
          rl.close();
          process.exit(1);
        }
      }
    }
    
    // Setup each platform
    let anyChanges = false;
    for (const p of platformsToSetup) {
      const changed = await setupPlatform(rl, p, envMap);
      anyChanges = anyChanges || changed;
    }
    
    // Save .env if there were changes
    if (anyChanges) {
      await writeEnvFile(envPath, envMap);
      console.log(`\n${'='.repeat(50)}`);
      console.log('✅ Credentials saved to .env');
      console.log('');
      console.log('To load these credentials, either:');
      console.log('  1. Source the file: source .env');
      console.log('  2. Use dotenv: npm install dotenv');
      console.log('  3. Set them in your shell profile');
      console.log('');
      console.log('Run "puppet-master doctor" to verify authentication.');
    } else {
      console.log('\n✅ No changes made.');
    }
    
  } finally {
    rl.close();
  }
}

/**
 * LoginCommand class implementing CommandModule interface
 */
export class LoginCommand implements CommandModule {
  /**
   * Register the login command with the Commander.js program
   */
  register(program: Command): void {
    program
      .command('login [platform]')
      .description('Configure platform authentication credentials')
      .option('--all', 'Configure all platforms')
      .option('--env-file <path>', 'Path to .env file (default: ./.env)')
      .addHelpText('after', `
Platforms:
  cursor    - Cursor IDE (uses app authentication)
  codex     - OpenAI Codex CLI (OPENAI_API_KEY)
  claude    - Anthropic Claude Code (ANTHROPIC_API_KEY)
  gemini    - Google Gemini CLI (GEMINI_API_KEY)
  copilot   - GitHub Copilot CLI (GH_TOKEN)

Examples:
  $ puppet-master login              # Interactive wizard
  $ puppet-master login codex        # Configure Codex only
  $ puppet-master login --all        # Configure all platforms
      `)
      .action(async (platform: string | undefined, options: LoginOptions) => {
        await loginAction(platform, options);
      });
  }
}

/**
 * Export singleton instance for registration
 */
export const loginCommand = new LoginCommand();
