/* Exercises shipped protocol modules, not substitute algorithms. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
require('../../question-budget-protocol.js');require('../../deep-plan-protocol.js');
const Q=globalThis.PM56_QUESTION_BUDGET,F=globalThis.PM56_DEEP_CORE,cp=x=>JSON.parse(JSON.stringify(x)),tests=[];
function test(name,f){try{f();tests.push({name,status:'pass'});}catch(e){tests.push({name,status:'fail',error:e.stack});}}
function budget(){const store={runs:{},seq:0};return {store,b:Q.factory(()=>store)};}
function fresh(strategy='deep_thorough',n=2){const x=budget(),sources={a:{id:'a',version:1,projectId:'p',threadId:'t',status:'active',content:JSON.stringify({kind:'export_inventory',fields:[{name:'title',sensitive:false},{name:'token',sensitive:true}]})},prior:{id:'prior',version:1,projectId:'p',threadId:'t',status:'active',content:JSON.stringify({answers:[{key:'offline',answer:'No network'}]})}},scopes={t:{projectId:'p',worktreeId:'w'}};const e=F.factory({budget:x.b,source:id=>sources[id],scope:id=>scopes[id]});const input={id:'r',planId:'pl',threadId:'t',projectId:'p',worktreeId:'w',strategy,objective:'Plan an offline export',grillMe:false,sourceIds:['a','prior'],scenario:'thorough',questions:Array.from({length:n},(_,i)=>({key:'q'+i,prompt:'Decision '+i,kind:'decision',dependsOn:[],build_blocker:false,options:['Option A','Option B'],participant:'Planner'}))};return {...x,sources,scopes,e,input};}
function start(x){const o=x.e.start(x.input);assert(o.ok,JSON.stringify(o));return o.run;}
function answer(x){const o=x.e.present('r');assert(o.ok,JSON.stringify(o));const a=Object.fromEntries(o.round.questionIds.map(id=>[id,'Option A']));assert(x.e.submit('r',o.round.id,a).ok);return o;}
function researchInput(){const x=fresh();x.input.questions=[{key:'fact',prompt:'Inspect fields',kind:'fact',dependsOn:[],build_blocker:true,sourceId:'a'},x.input.questions[0]];return x;}
function research(x){const o=x.e.beginResearch('r','fact');assert(o.ok);return x.e.completeResearch('r',o.ticket.id);}
for(const [strategy,base] of Object.entries(Q.bases()))test('Factory ceiling and derived Grill total: '+strategy,()=>{const {b}=budget();assert(b.ensure('r',strategy,false).ok);assert.equal(b.projection('r').effective_limit,base);b.setGrill('r',true);assert.equal(b.projection('r').effective_limit,base+25);for(let i=0;i<base+25;i++)assert(b.admit('r',{question_item_id:'q'+i}).ok);assert.equal(b.admit('r',{question_item_id:'overflow'}).error,'question_budget_exhausted');assert.equal(b.projection('r').questions_asked,base+25);});
for(const workflow of ['plan','deep_plan'])for(const value of ['quick','standard','thorough','exhaustive','brainstorm'])test('Exact strategy pairing '+workflow+'/'+value,()=>{const valid=workflow==='plan'?['quick','standard','thorough']:['thorough','exhaustive','brainstorm'];assert.equal(!!F.strategy(workflow,value),valid.includes(value));});
test('Unknown strategy never silently coerced',()=>{assert.equal(F.strategy('plan','balanced'),null);assert.equal(F.strategy('ask','thorough'),null);assert.equal(budget().b.ensure('r','toString',false).ok,false);});
test('Malformed policy fails before allocating a counter',()=>{const {b,store}=budget();const p=Q.defaults();delete p.plan_limits.quick;assert.equal(b.ensure('r','quick',false,p).error,'invalid_question_budget_policy');assert.deepEqual(store.runs,{});});
test('Explicit numeric policy overrides are preserved and totals derived',()=>{const {b}=budget(),p=Q.defaults();p.deep_plan_limits.brainstorm=15;p.grill_me_extension=10;assert(b.ensure('r','brainstorm',true,p).ok);assert.equal(b.projection('r').effective_limit,25);p.deep_plan_limits.brainstorm=99;assert.equal(b.projection('r').base_limit,15);});
test('Invalid scalar policy values rejected',()=>{for(const v of [-1,101,1.5,'10',NaN]){const p=Q.defaults();p.grill_me_extension=v;assert.equal(Q.validatePolicy(p),null);}});
test('Opening and projection are pure budget reads',()=>{const {b,store}=budget();b.ensure('r','quick',false);const before=cp(store);for(let i=0;i<10;i++)b.projection('r');assert.deepEqual(store,before);});
test('Presentation charged once across participants',()=>{const {b}=budget();b.ensure('r','quick',false);assert.equal(b.admitMany('r',[{question_item_id:'q',semantic_key:'k',contributors:['A']},{question_item_id:'q',semantic_key:'k',contributors:['B']}]).charged_count,1);assert.equal(b.admit('r',{question_item_id:'q',semantic_key:'k'}).charged_count,0);assert.equal(b.projection('r').questions_asked,1);});
test('Question identity cannot bind different semantics',()=>{const {b}=budget();b.ensure('r','quick',false);b.admit('r',{question_item_id:'q',semantic_key:'a',prompt:'First'});assert.equal(b.admit('r',{question_item_id:'q',semantic_key:'b',prompt:'First'}).error,'question_identity_conflict');assert.equal(b.admit('r',{question_item_id:'q',semantic_key:'a',prompt:'Different'}).ok,false);});
test('Batch admission is atomic at the ceiling',()=>{const {b}=budget();b.ensure('r','quick',false);b.admitMany('r',[{question_item_id:'1'},{question_item_id:'2'}]);assert.equal(b.admitMany('r',[{question_item_id:'3'},{question_item_id:'4'}]).error,'question_budget_exhausted');assert.equal(b.projection('r').questions_asked,2);});
test('Zero allowance exhausts without run failure or extra record',()=>{const {b}=budget(),p=Q.defaults();p.plan_limits.quick=0;b.ensure('r','quick',false,p);const o=b.admit('r',{question_item_id:'q'});assert.equal(o.error,'question_budget_exhausted');assert.equal(o.run_failed,false);assert.deepEqual(b.get('r').order,[]);});
test('Lowering Grill retains over-base history and reenabling restores allowance',()=>{const {b}=budget();b.ensure('r','quick',true);for(let i=0;i<4;i++)b.admit('r',{question_item_id:'q'+i});b.setGrill('r',false);assert.equal(b.projection('r').questions_remaining,0);assert.equal(b.projection('r').questions_asked,4);b.setGrill('r',true);assert.equal(b.projection('r').questions_remaining,24);});
test('Source evidence is required for free resolution',()=>{const {b}=budget();b.ensure('r','quick',false);assert.equal(b.resolve('r',{question_item_id:'q',kind:'research_resolved',answer:'guess'}).error,'resolution_evidence_required');});
for(const kind of ['reused_answer','research_resolved'])test('Idempotent evidenced resolution: '+kind,()=>{const {b}=budget();b.ensure('r','quick',false);const x={question_item_id:'q',kind,source_ref:'a:v1',source_binding:'exact bytes',answer:'yes'};assert(b.resolve('r',x).ok);assert(b.resolve('r',x).reused);assert.equal(b.resolve('r',{...x,answer:'no'}).ok,false);assert.equal(b.admit('r',{question_item_id:'q'}).charged_count,0);assert.equal(b.projection('r').questions_asked,0);assert.equal(b.projection('r')[kind==='reused_answer'?'reused_answer_count':'research_resolved_count'],1);});
test('Presented item cannot later be relabelled as free research',()=>{const {b}=budget();b.ensure('r','quick',false);b.admit('r',{question_item_id:'q'});assert.equal(b.resolve('r',{question_item_id:'q',kind:'research_resolved',source_ref:'a',source_binding:'x',answer:'yes'}).error,'already_presented_not_free_resolution');});
test('Plan identity—not version—retains count; new identity gets zero',()=>{const {b}=budget();b.ensure('plan:p','deep_thorough',false);b.admit('plan:p',{question_item_id:'q'});b.ensure('plan:p','deep_thorough',false);assert.equal(b.projection('plan:p').questions_asked,1);b.ensure('plan:p2','deep_thorough',false);assert.equal(b.projection('plan:p2').questions_asked,0);});
test('Serialized in-memory records reconstruct counts, not visible cards',()=>{const {b,store}=budget();b.ensure('r','quick',false);b.admit('r',{question_item_id:'q'});const restored=Q.factory(cp(store));assert.deepEqual(restored.projection('r'),b.projection('r'));});
test('Prototype-like IDs cannot escape dictionary ownership',()=>{const {b}=budget();assert.equal(b.ensure('__proto__','quick',false).ok,false);b.ensure('r','quick',false);assert(b.admit('r',{question_item_id:'toString'}).ok);assert.equal(b.projection('r').questions_asked,1);});
test('Changing strategy on an existing budget is rejected',()=>{const {b}=budget();b.ensure('r','quick',false);assert.equal(b.ensure('r','brainstorm',false).error,'strategy_frozen');});
test('Start itself creates proposed questions, not asked items',()=>{const x=fresh();const r=start(x);assert.equal(r.status,'collecting');assert.equal(x.e.view('r').budget.questions_asked,0);assert(r.questions.every(q=>q.state==='proposed'));});
test('Start replay retains one run; changed request conflicts',()=>{const x=fresh();start(x);assert(x.e.start(x.input).reused);assert.equal(x.e.start({...x.input,objective:'new'}).error,'start_identity_conflict');assert.equal(x.e.all().length,1);});
test('Two discovery sessions cannot share a Plan identity',()=>{const x=fresh();start(x);assert.equal(x.e.start({...x.input,id:'r2'}).error,'plan_identity_already_bound');});
test('A second collecting discovery in the same thread is rejected',()=>{const x=fresh();start(x);assert.equal(x.e.start({...x.input,id:'r2',planId:'p2'}).error,'planning_already_active');});
test('Invalid question options are rejected before host admission',()=>{const x=fresh();delete x.input.questions[0].options;assert.equal(x.e.start(x.input).error,'invalid_question_spec');assert.equal(x.e.all().length,0);});
test('Undeclared fact source rejected',()=>{const x=researchInput();x.input.sourceIds=[];assert.equal(x.e.start(x.input).error,'invalid_question_spec');});
test('Question dependency cycle rejected',()=>{const x=fresh();x.input.questions[0].dependsOn=['q1'];x.input.questions[1].dependsOn=['q0'];assert.equal(x.e.start(x.input).error,'question_dependency_cycle');});
test('Equivalent proposals merge before presentation',()=>{const x=fresh();x.input.questions.push({...cp(x.input.questions[0]),prompt:'A paraphrase',participant:'Other'});const r=start(x);assert.equal(r.questions.length,2);assert.equal(r.questions[0].contributors.length,2);assert(x.e.present('r').ok);assert.equal(x.e.view('r').budget.questions_asked,2);});
test('Duplicate semantic key cannot contradict dependency or blocker',()=>{const x=fresh();x.input.questions.push({...cp(x.input.questions[0]),build_blocker:true});assert.equal(x.e.start(x.input).error,'semantic_key_conflict');});
test('Dependencies wait for resolved predecessor',()=>{const x=fresh();x.input.questions[1].dependsOn=['q0'];start(x);assert.equal(x.e.frontier('r').length,1);answer(x);assert.equal(x.e.frontier('r')[0].key,'q1');});
test('Closing/reopening an active round returns same IDs without charge',()=>{const x=fresh();start(x);const a=x.e.present('r'),b=x.e.present('r');assert(b.reused);assert.deepEqual(a.round,b.round);assert.equal(x.e.view('r').budget.questions_asked,2);});
test('Missing and extra answers cause zero partial commit',()=>{const x=fresh();start(x);const o=x.e.present('r');assert.equal(x.e.submit('r',o.round.id,{}).error,'answers_required');assert.equal(x.e.submit('r',o.round.id,{forged:'A'}).error,'invalid_answers');assert(x.e.get('r').questions.every(q=>q.state==='presented'));});
test('Answer replay is idempotent but different historical answer rejected',()=>{const x=fresh();start(x);const o=answer(x),r=x.e.get('r').rounds[0];assert(x.e.submit('r',o.round.id,r.answers).reused);assert.equal(x.e.submit('r',o.round.id,{...r.answers,[r.questionIds[0]]:'B'}).error,'answer_replay_conflict');assert.equal(x.e.view('r').budget.questions_asked,2);});
test('Pending questionnaire prevents synthesis',()=>{const x=fresh();start(x);x.e.present('r');assert.equal(x.e.payload('r').error,'questionnaire_open');});
test('Unasked nonblockers remain explicit but do not prevent synthesis',()=>{const x=fresh();start(x);const p=x.e.payload('r');assert(p.ok);assert.equal(p.value.blockers.length,0);assert(p.value.blocks.some(b=>b.text?.includes('Open, non-blocking:')));});
test('Explicit unresolved blocker persists into Plan handoff',()=>{const x=fresh();x.input.questions[0].build_blocker=true;start(x);const p=x.e.payload('r');assert(p.ok);assert.equal(p.value.blockers.length,1);assert(p.value.blocks.some(b=>b.text?.includes('Build blocker:')));});
test('Exhaustion never erases open decisions or fails discovery',()=>{const x=fresh('deep_thorough',12);start(x);while(x.e.view('r').budget.questions_remaining>0)answer(x);assert.equal(x.e.present('r').error,'question_budget_exhausted');assert.equal(x.e.get('r').status,'collecting');assert.equal(x.e.readiness('r').openItems.length,2);assert(x.e.payload('r').ok);});
test('Changing Grill invalidates a reviewed synthesis snapshot',()=>{const x=fresh();start(x);const p=x.e.payload('r');x.e.setGrill('r',true);let calls=0;assert.equal(x.e.finish('r',F.fingerprint(p.value),()=>{calls++;return {ok:true}}).error,'stale_synthesis_preview');assert.equal(calls,0);});
test('Synthesis delegates to Plan owner and does not bypass its rejection',()=>{const x=fresh();start(x);const p=x.e.payload('r');assert.equal(x.e.finish('r',F.fingerprint(p.value),()=>({ok:false,error:'owner_refused'})).error,'owner_refused');assert.equal(x.e.get('r').status,'collecting');});
test('Successful synthesis keeps exact receipt and checks replay binding',()=>{const x=fresh();start(x);const key=F.fingerprint(x.e.payload('r').value);let calls=0;const create=()=>{calls++;return {ok:true,planId:'pl'}};assert(x.e.finish('r',key,create).ok);assert(x.e.finish('r',key,create).reused);assert.equal(x.e.finish('r','wrong',create).error,'synthesis_replay_conflict');assert.equal(calls,1);});
test('Research computes supplied field flags, not an authored success',()=>{const x=researchInput();start(x);const o=research(x);assert(o.ok);assert.deepEqual(o.evidence.facts,{included:['title'],excluded:['token']});assert.equal(x.e.view('r').budget.questions_asked,0);assert.equal(x.e.view('r').budget.research_resolved_count,1);});
test('Malformed source cannot be treated as success',()=>{const x=researchInput();x.sources.a.content='not json';start(x);assert.equal(research(x).error,'source_not_valid_json');assert.equal(x.e.view('r').budget.research_resolved_count,0);});
test('Unsupported source shape remains an unresolved blocker',()=>{const x=researchInput();x.sources.a.content='{"kind":"magic","success":true}';start(x);assert.equal(research(x).error,'unsupported_source');assert.equal(x.e.payload('r').value.blockers.length,1);});
test('A second pending research ticket cannot duplicate work',()=>{const x=researchInput();start(x);x.e.beginResearch('r','fact');assert.equal(x.e.beginResearch('r','fact').error,'research_already_pending');assert.equal(x.e.payload('r').error,'research_pending');});
for(const [name,change] of [['source revision',x=>x.sources.a.version++],['same-length bytes',x=>x.sources.a.content=x.sources.a.content.replace('title','Title')],['source revoked',x=>x.sources.a.status='revoked'],['source project',x=>x.sources.a.projectId='other'],['source thread',x=>x.sources.a.threadId='other'],['project scope',x=>x.scopes.t.projectId='other'],['worktree scope',x=>x.scopes.t.worktreeId='other'],['source removed',x=>delete x.sources.a],['cancelled discovery',x=>x.e.cancel('r')]])test('Pending result fenced after '+name,()=>{const x=researchInput();start(x);const o=x.e.beginResearch('r','fact');change(x);assert.equal(x.e.completeResearch('r',o.ticket.id).ok,false);assert.equal(x.e.view('r').budget.research_resolved_count,0);});
test('Completed ticket cannot be consumed twice',()=>{const x=researchInput();start(x);const o=x.e.beginResearch('r','fact');assert(x.e.completeResearch('r',o.ticket.id).ok);assert.equal(x.e.completeResearch('r',o.ticket.id).error,'research_ticket_consumed');});
test('Changed checked source invalidates preview; recheck retains one fact count',()=>{const x=researchInput();start(x);research(x);x.sources.a.version++;assert.equal(x.e.payload('r').error,'stale_sources');assert(research(x).ok);assert.equal(x.e.view('r').budget.research_resolved_count,1);assert.equal(x.e.get('r').evidence.length,2);assert(x.e.payload('r').ok);});
test('Reuse requires the exact prior answer, scope and source bytes',()=>{const x=fresh();x.input.questions[0].key='offline';start(x);assert.equal(x.e.reuse('r','offline',{key:'offline',sourceId:'prior',answer:'Guess'}).error,'reuse_source_mismatch');assert(x.e.reuse('r','offline',{key:'offline',sourceId:'prior',answer:'No network'}).ok);assert.equal(x.e.view('r').budget.reused_answer_count,1);assert.equal(x.e.view('r').budget.questions_asked,0);x.sources.prior.version++;assert.equal(x.e.payload('r').error,'stale_sources');});
test('Generic request never receives fabricated export findings',()=>{const x=fresh();x.input.scenario='custom';x.input.objective='Investigate image decoding';start(x);const text=JSON.stringify(x.e.payload('r').value);assert(text.includes('Investigate image decoding'));assert(!text.includes('export contract'));assert(!text.includes('exportable fields'));});
test('Exhaustive keeps Thorough dimensions and adds explicit deeper work',()=>{const x=fresh('deep_exhaustive');start(x);const p=x.e.payload('r').value;assert(p.blocks.some(b=>b.text==='Risks and rollback'));assert(p.blocks.some(b=>b.text==='Exhaustive impact review'));assert(p.blocks.some(b=>b.t==='table'&&b.rows.length===6));});
test('Reset fences all discarded run identities',()=>{const x=researchInput();start(x);const o=x.e.beginResearch('r','fact');x.e.reset();assert.equal(x.e.completeResearch('r',o.ticket.id).error,'planning_run_missing');assert.equal(x.e.all().length,0);});
test('Automatic admission reuses a prior answer without a demo shortcut',()=>{const x=fresh();x.input.questions[0].key='offline';start(x);const o=x.e.present('r');assert(o.ok);assert.equal(o.round.questionIds.length,1);assert.equal(x.e.view('r').budget.questions_asked,1);assert.equal(x.e.view('r').budget.reused_answer_count,1);});
test('Rechecking a changed prior answer does not count it twice',()=>{const x=fresh();x.input.questions[0].key='offline';start(x);assert(x.e.reuse('r','offline',{key:'offline',sourceId:'prior',answer:'No network'}).ok);x.sources.prior.version++;x.sources.prior.content=JSON.stringify({answers:[{key:'offline',answer:'Network optional'}]});assert.equal(x.e.payload('r').error,'stale_sources');assert(x.e.reuse('r','offline',{key:'offline',sourceId:'prior',answer:'Network optional'}).ok);assert.equal(x.e.get('r').questions[0].answer,'Network optional');assert.equal(x.e.view('r').budget.reused_answer_count,1);});
test('Projection derives resolution totals from records, not cached totals',()=>{const {b,store}=budget();b.ensure('r','quick',false);b.admit('r',{question_item_id:'one'});b.resolve('r',{question_item_id:'two',kind:'research_resolved',source_ref:'src',source_binding:'bytes',answer:'Observed'});store.runs.r.reused=999;store.runs.r.research=999;store.runs.r.order.push('not-an-asked-record');const restored=Q.factory(cp(store));assert.equal(restored.projection('r').questions_asked,1);assert.equal(restored.projection('r').research_resolved_count,1);assert.equal(restored.projection('r').reused_answer_count,0);});
test('Conflicting duplicate choices cannot hide under a semantic key',()=>{const x=fresh();x.input.questions.push({...cp(x.input.questions[0]),options:['Different decision']});assert.equal(x.e.start(x.input).error,'semantic_key_conflict');});
test('Negative source version is never admitted as current',()=>{const x=researchInput();x.sources.a.version=-1;start(x);assert.equal(x.e.beginResearch('r','fact').error,'research_source_unavailable');});
test('Grill Me presents the complete eligible frontier, not a per-agent pool',()=>{const x=fresh('deep_thorough',8);x.input.grillMe=true;x.input.questions[7].dependsOn=['q0'];start(x);const o=x.e.present('r');assert(o.ok);assert.equal(o.round.questionIds.length,7);assert.equal(x.e.view('r').budget.questions_asked,7);assert.equal(x.e.get('r').questions[7].state,'proposed');});
const report={status:tests.every(t=>t.status==='pass')?'pass':'fail',test_count:tests.length,tests};
if(process.argv[2])fs.writeFileSync(process.argv[2],JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));process.exitCode=report.status==='pass'?0:1;
