import {chromium} from 'playwright';import {pathToFileURL} from 'url';
const b=await chromium.launch({headless:true,args:['--disable-gpu','--allow-file-access-from-files','--no-sandbox']});
const p=await b.newPage({viewport:{width:1440,height:900}});
const errs=[];p.on('console',m=>{if(m.type()==='error'||m.type()==='warning')errs.push(m.type()+':'+m.text())});p.on('pageerror',e=>errs.push('PE '+e));
await p.goto(pathToFileURL("/mnt/Cursor/PuppetMaster/Concepts/chat-assistant-concepts/5.6 Pro/PM_Chat_Assistant_5.6_Pro_Standalone.html").href,{waitUntil:'load'});
await p.waitForFunction(()=>window.__PM56_BOOT_OK===true&&window.PM56_DEMO);
const R={};
R.before=await p.evaluate(()=>!!document.querySelector('[data-action="restore-draft"]'));
await p.evaluate(()=>{const t=document.querySelector('[data-input="composer"]');t.value='a saved draft';t.dispatchEvent(new Event('input',{bubbles:true}));});
R.whileTyping=await p.evaluate(()=>!!document.querySelector('[data-action="restore-draft"]'));
await p.locator('[data-action="send"]').click(); await p.waitForTimeout(400);
const bx=await p.evaluate(()=>{const e=document.querySelector('[data-action="restore-draft"]');if(!e)return null;const r=e.getBoundingClientRect();const t=document.elementFromPoint(r.left+r.width/2,r.top+r.height/2);return {w:+r.width.toFixed(1),h:+r.height.toFixed(1),isSelf:!!(t&&e.contains(t))};});
R.afterSend=bx;
await p.locator('[data-action="restore-draft"]').click(); await p.waitForTimeout(300);
R.restored=await p.evaluate(()=>document.querySelector('[data-input="composer"]').value);
R.hiddenAgain=await p.evaluate(()=>!!document.querySelector('[data-action="restore-draft"]'));
R.errors=errs;
console.log(JSON.stringify(R));
await b.close();
