import {chromium} from 'playwright';import {pathToFileURL} from 'url';
const FILE="/mnt/Cursor/PuppetMaster/Concepts/chat-assistant-concepts/5.6 Pro/PM_Chat_Assistant_5.6_Pro_Standalone.html";
const b=await chromium.launch({headless:true,args:['--disable-gpu','--allow-file-access-from-files','--no-sandbox']});
const p=await b.newPage({viewport:{width:1440,height:900}});
p.on('pageerror',e=>console.log('PE',String(e)));
await p.goto(pathToFileURL(FILE).href,{waitUntil:'load'});
await p.waitForFunction(()=>window.__PM56_BOOT_OK===true&&window.PM56_DEMO);
await p.waitForTimeout(600);
console.log('themes', await p.evaluate(()=>window.PM56_DATA?window.PM56_DATA.themes.map(t=>t.id):null));
const id=await p.evaluate(()=>document.querySelector('.history-flyout .thread-row[data-id]').dataset.id);
await p.locator(`.history-flyout .thread-row[data-id="${id}"] [data-action="thread-menu"]`).click();
await p.waitForTimeout(300);
console.log('menu open before', await p.evaluate(()=>({m:!!document.querySelector('.overlay-menu'),st:PM56_DEMO.getState().menu})));
await p.locator('[data-action="toggle-thread-pin"]').click();
await p.waitForTimeout(80);
console.log('after 80ms', await p.evaluate(()=>({m:!!document.querySelector('.overlay-menu'),st:PM56_DEMO.getState().menu, overlayKids:[...document.getElementById('pmOverlayRoot').children].map(c=>c.className)})));
await p.waitForTimeout(900);
console.log('after 1s', await p.evaluate(()=>({m:!!document.querySelector('.overlay-menu'),st:PM56_DEMO.getState().menu})));
await b.close();
