import pw from '/mnt/Cursor/PuppetMaster/Concepts/chat-assistant-concepts/5.6 Pro/node_modules/playwright-core/index.js';
const { chromium } = pw; import path from 'path';
const ROOT='/mnt/Cursor/PuppetMaster/Concepts/chat-assistant-concepts/5.6 Pro';
const b=await chromium.launch({headless:true,executablePath:process.env.HOME+'/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox','--allow-file-access-from-files','--disable-gpu']});
const p=await b.newPage({viewport:{width:1440,height:1200}});
await p.goto('file://'+path.join(ROOT,'PM_Chat_Assistant_5.6_Pro_Standalone.html'),{waitUntil:'load'});
await p.waitForFunction(()=>window.__PM56_BOOT_OK===true&&window.PM56_DEMO);
await p.evaluate(()=>PM56_DEMO.selectThread('route')); await p.waitForTimeout(200);
const uid=await p.evaluate(()=>window.PM56_DATA.threads.find(t=>t.id==='route').messages.find(m=>m.role==='user'&&m.type==='text').id);
await p.evaluate(i=>{const b=document.querySelector(`.message[data-message-id="${i}"] [data-action="message-details"]`); if(b)b.click();},uid);
await p.waitForTimeout(200);
const panel=await p.evaluate(i=>{const el=document.querySelector(`.message[data-message-id="${i}"] .message-details`); if(!el)return null;
  const o={}; for(const d of el.querySelectorAll('.detail-kv')) o[d.querySelector('label').innerText.trim()]=d.querySelector('strong').innerText.trim(); return o;},uid);
const keys=await p.evaluate(()=>[...Object.keys(PM56_DATA.labels.terminal),...Object.keys(PM56_DATA.labels.mode),...Object.keys(PM56_DATA.labels.effort)]);
console.log('user message',uid,'panel:');
for(const [k,v] of Object.entries(panel||{})) console.log('  ',k.padEnd(18),v);
const raw=Object.entries(panel||{}).filter(([,v])=>keys.includes(String(v)));
console.log('\nRAW ENUM KEYS RENDERED AS VALUES:', raw.length?JSON.stringify(raw):'none');
await b.close();
