//! Generates comprehensive autonomous test strategy from interview.
//!
//! Creates a detailed test plan that AI agents can execute without manual
//! intervention, with emphasis on Playwright for E2E testing.
//!
//! Implements Part 2.10 and Part 7.1 of interviewupdates.md specification.

use anyhow::{Context, Result};
use log::info;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;

use super::document_writer::CompletedPhase;

// DRY:DATA:CoverageLevel
/// Test coverage levels.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CoverageLevel {
    /// Basic coverage of critical paths only.
    Basic,
    /// Standard coverage including error cases.
    Standard,
    /// Comprehensive coverage of all scenarios.
    Comprehensive,
}

impl std::fmt::Display for CoverageLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CoverageLevel::Basic => write!(f, "Basic"),
            CoverageLevel::Standard => write!(f, "Standard"),
            CoverageLevel::Comprehensive => write!(f, "Comprehensive"),
        }
    }
}

// DRY:DATA:TestStrategyConfig
/// Configuration for test strategy generation.
#[derive(Debug, Clone)]
pub struct TestStrategyConfig {
    /// Desired coverage level.
    pub coverage_level: CoverageLevel,
    /// Whether to include Playwright E2E tests.
    pub include_playwright: bool,
    /// Whether to include performance tests.
    pub include_performance: bool,
    /// Whether to include security tests.
    pub include_security: bool,
}

impl Default for TestStrategyConfig {
    fn default() -> Self {
        Self {
            coverage_level: CoverageLevel::Standard,
            include_playwright: true,
            include_performance: false,
            include_security: true,
        }
    }
}

// DRY:DATA:TestStrategyJson
/// Machine-readable test strategy schema (Part 7.1 spec).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TestStrategyJson {
    /// Project name.
    pub project: String,
    /// Timestamp when this strategy was generated.
    pub generated_at: String,
    /// Coverage level target.
    pub coverage_level: String,
    /// Array of test items with verification commands.
    pub items: Vec<TestItem>,
}

// DRY:DATA:TestItem
/// A single test item with verification details (Part 7.1 spec).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TestItem {
    /// Unique test item ID.
    pub id: String,
    /// Phase ID this test originated from.
    pub source_phase_id: String,
    /// Acceptance criterion being tested.
    pub criterion: String,
    /// Type of test (unit, integration, playwright, performance, security).
    pub test_type: String,
    /// Path to the test file.
    pub test_file: String,
    /// Test name/identifier.
    pub test_name: String,
    /// Command to run this specific test.
    pub verification_command: String,
}

// DRY:FN:generate_test_strategy_markdown
/// Generates a test strategy document from interview results.
pub fn generate_test_strategy_markdown(
    project_name: &str,
    completed_phases: &[CompletedPhase],
    config: &TestStrategyConfig,
) -> Result<String> {
    let mut content = String::new();

    // Header
    content.push_str(&format!(
        "# Test Strategy: {project_name}\n\n\
         **Generated on {}**\n\n\
         **Coverage Level:** {}\n\n",
        chrono::Utc::now().format("%Y-%m-%d"),
        config.coverage_level
    ));

    // Overview
    content.push_str(
        "## Overview\n\n\
         This document defines the comprehensive automated testing strategy for the project.\n\
         All tests are designed to be executed by AI agents without manual intervention.\n\
         Generated by Puppet Master.\n\n",
    );

    // Test types
    content.push_str("## Test Types\n\n");

    // Unit tests
    content.push_str(
        "### Unit Tests\n\n\
         - Test individual functions and modules in isolation\n\
         - Mock external dependencies\n\
         - Aim for fast execution (< 1s per test)\n\
         - Run on every commit\n\n",
    );

    // Integration tests
    content.push_str(
        "### Integration Tests\n\n\
         - Test interactions between modules\n\
         - Test database operations\n\
         - Test API endpoints\n\
         - Run before merge\n\n",
    );

    // E2E tests
    if config.include_playwright {
        content.push_str(
            "### End-to-End Tests (Playwright)\n\n\
             - Test complete user workflows\n\
             - Run in real browser environments\n\
             - Test across multiple browsers if applicable\n\
             - Include accessibility checks\n\
             - Run nightly or before release\n\n",
        );
    }

    // Performance tests
    if config.include_performance {
        content.push_str(
            "### Performance Tests\n\n\
             - Measure response times\n\
             - Test under load\n\
             - Check memory usage\n\
             - Run weekly or before release\n\n",
        );
    }

    // Security tests
    if config.include_security {
        content.push_str(
            "### Security Tests\n\n\
             - Test authentication and authorization\n\
             - Check for common vulnerabilities (SQL injection, XSS, etc.)\n\
             - Verify secrets are not exposed\n\
             - Run before merge\n\n",
        );
    }

    // Test scenarios by phase
    content.push_str("## Test Scenarios by Domain\n\n");
    for phase in completed_phases {
        content.push_str(&format!("### {}\n\n", phase.definition.name));

        // Generate test scenarios based on Q&A
        if !phase.qa_history.is_empty() {
            content.push_str("**Test scenarios derived from requirements:**\n\n");
            for (i, qa) in phase.qa_history.iter().enumerate().take(3) {
                content.push_str(&format!(
                    "{}. Test scenario related to: {}\n",
                    i + 1,
                    qa.question
                ));
            }
            content.push('\n');
        }

        content.push_str("(Detailed test cases to be generated during implementation)\n\n");
    }

    // Acceptance criteria
    content.push_str(
        "## Acceptance Criteria\n\n\
         The project is ready for release when:\n\
         - All unit tests pass (100%)\n\
         - All integration tests pass (100%)\n",
    );

    if config.include_playwright {
        content.push_str("- All E2E tests pass (100%)\n");
    }

    if config.include_performance {
        content.push_str("- Performance tests meet target thresholds\n");
    }

    if config.include_security {
        content.push_str("- Security tests show no critical vulnerabilities\n");
    }

    content.push_str(&format!(
        "- Code coverage is at least {}%\n\n",
        match config.coverage_level {
            CoverageLevel::Basic => 70,
            CoverageLevel::Standard => 80,
            CoverageLevel::Comprehensive => 90,
        }
    ));

    // CI/CD integration
    content.push_str(
        "## CI/CD Integration\n\n\
         - Run unit tests on every push\n\
         - Run integration tests on pull request\n\
         - Run full test suite nightly\n\
         - Block merge if tests fail\n\
         - Generate coverage reports\n\n",
    );

    Ok(content)
}

// DRY:FN:generate_test_strategy_json
/// Generates machine-readable test strategy JSON (Part 7.1 spec).
pub fn generate_test_strategy_json(
    project_name: &str,
    completed_phases: &[CompletedPhase],
    config: &TestStrategyConfig,
) -> Result<TestStrategyJson> {
    let mut items = Vec::new();
    let mut item_counter = 1;

    // Generate test items from each phase's Q&A and decisions
    for phase in completed_phases {
        // Generate test items from Q&A
        for (idx, qa) in phase.qa_history.iter().enumerate() {
            let item_id = format!("TEST-{:03}", item_counter);
            item_counter += 1;

            // Determine test type based on phase and content
            let test_type = determine_test_type(&phase.definition.id, &qa.question);

            items.push(TestItem {
                id: item_id.clone(),
                source_phase_id: phase.definition.id.clone(),
                criterion: format!("Verify: {}", qa.question),
                test_type: test_type.clone(),
                test_file: generate_test_file_path(&test_type, &phase.definition.id, idx),
                test_name: generate_test_name(&qa.question),
                verification_command: generate_verification_command(
                    &test_type,
                    &phase.definition.id,
                ),
            });
        }

        // Generate test items from decisions
        for (idx, decision) in phase.decisions.iter().enumerate() {
            let item_id = format!("TEST-{:03}", item_counter);
            item_counter += 1;

            let test_type = determine_test_type(&phase.definition.id, &decision.summary);

            items.push(TestItem {
                id: item_id.clone(),
                source_phase_id: phase.definition.id.clone(),
                criterion: decision.summary.clone(),
                test_type: test_type.clone(),
                test_file: generate_test_file_path(&test_type, &phase.definition.id, idx),
                test_name: generate_test_name(&decision.summary),
                verification_command: generate_verification_command(
                    &test_type,
                    &phase.definition.id,
                ),
            });
        }
    }

    Ok(TestStrategyJson {
        project: project_name.to_string(),
        generated_at: chrono::Utc::now().to_rfc3339(),
        coverage_level: config.coverage_level.to_string(),
        items,
    })
}

/// Determines appropriate test type based on phase and content.
fn determine_test_type(phase_id: &str, content: &str) -> String {
    let content_lower = content.to_lowercase();

    // GUI/UX → Playwright
    if phase_id == "product_ux"
        || content_lower.contains("ui")
        || content_lower.contains("gui")
        || content_lower.contains("user interface")
    {
        return "playwright".to_string();
    }

    // Security → Security tests
    if phase_id == "security_secrets"
        || content_lower.contains("security")
        || content_lower.contains("auth")
    {
        return "security".to_string();
    }

    // Performance → Performance tests
    if phase_id == "performance_reliability"
        || content_lower.contains("performance")
        || content_lower.contains("load")
    {
        return "performance".to_string();
    }

    // API/Integration keywords
    if content_lower.contains("api")
        || content_lower.contains("database")
        || content_lower.contains("integration")
    {
        return "integration".to_string();
    }

    // Default to unit tests
    "unit".to_string()
}

/// Generates test file path based on test type and phase.
fn generate_test_file_path(test_type: &str, phase_id: &str, index: usize) -> String {
    match test_type {
        "playwright" => format!("tests/e2e/{}.spec.ts", phase_id.replace('_', "-")),
        "integration" => format!("tests/integration/{}_test_{}.rs", phase_id, index),
        "security" => format!("tests/security/{}_security_test.rs", phase_id),
        "performance" => format!("tests/performance/{}_perf_test.rs", phase_id),
        _ => format!("tests/unit/{}_test_{}.rs", phase_id, index),
    }
}

/// Generates a test name from a question or decision.
fn generate_test_name(text: &str) -> String {
    // Convert to snake_case test name
    text.to_lowercase()
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect::<String>()
        .split('_')
        .filter(|s| !s.is_empty())
        .take(8) // Limit length
        .collect::<Vec<_>>()
        .join("_")
}

/// Generates verification command for a test type.
fn generate_verification_command(test_type: &str, phase_id: &str) -> String {
    match test_type {
        "playwright" => format!("npx playwright test {}.spec.ts", phase_id.replace('_', "-")),
        "integration" => "cargo test --test integration".to_string(),
        "security" => "cargo test --test security".to_string(),
        "performance" => "cargo test --test performance --release".to_string(),
        _ => "cargo test".to_string(),
    }
}

// DRY:FN:generate_playwright_config
/// Generates a basic Playwright configuration template (Part 2.10 spec).
pub fn generate_playwright_config() -> String {
    r#"import { defineConfig, devices } from '@playwright/test';

/**
 * Playwright configuration for autonomous E2E testing.
 * Auto-generated by Puppet Master interview.
 */
export default defineConfig({
  testDir: './tests/e2e',
  
  /* Run tests in files in parallel */
  fullyParallel: true,
  
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  
  /* Reporter to use. */
  reporter: [
    ['html'],
    ['json', { outputFile: 'test-results/results.json' }],
  ],
  
  /* Shared settings for all the projects below. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: process.env.BASE_URL || 'http://localhost:3000',
    
    /* Collect trace when retrying the failed test. */
    trace: 'on-first-retry',
    
    /* Screenshot on failure */
    screenshot: 'only-on-failure',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },

    /* Test against mobile viewports. */
    {
      name: 'Mobile Chrome',
      use: { ...devices['Pixel 5'] },
    },
    {
      name: 'Mobile Safari',
      use: { ...devices['iPhone 12'] },
    },
  ],

  /* Run your local dev server before starting the tests */
  webServer: {
    command: 'npm run dev',
    url: 'http://localhost:3000',
    reuseExistingServer: !process.env.CI,
  },
});
"#
    .to_string()
}

// DRY:FN:write_test_strategy
/// Writes the test strategy documents to disk.
///
/// This generates three files as per Part 2.10 spec:
/// 1. `test-strategy.md` - Human-readable markdown
/// 2. `test-strategy.json` - Machine-readable JSON with stable schema
/// 3. `playwright.config.ts` - Playwright config (if include_playwright is true)
pub fn write_test_strategy(
    project_name: &str,
    completed_phases: &[CompletedPhase],
    config: &TestStrategyConfig,
    output_dir: &Path,
) -> Result<Vec<std::path::PathBuf>> {
    fs::create_dir_all(output_dir)
        .with_context(|| format!("Failed to create output dir {}", output_dir.display()))?;

    let mut written_paths = Vec::new();

    // 1. Write markdown file (test-strategy.md - lowercase with hyphen)
    let md_content = generate_test_strategy_markdown(project_name, completed_phases, config)?;
    let md_path = output_dir.join("test-strategy.md");
    fs::write(&md_path, &md_content)
        .with_context(|| format!("Failed to write test strategy to {}", md_path.display()))?;
    info!("Wrote test-strategy.md to {}", md_path.display());
    written_paths.push(md_path);

    // 2. Write JSON file (test-strategy.json)
    let json_data = generate_test_strategy_json(project_name, completed_phases, config)?;
    let json_content = serde_json::to_string_pretty(&json_data)
        .context("Failed to serialize test strategy JSON")?;
    let json_path = output_dir.join("test-strategy.json");
    fs::write(&json_path, &json_content).with_context(|| {
        format!(
            "Failed to write test strategy JSON to {}",
            json_path.display()
        )
    })?;
    info!("Wrote test-strategy.json to {}", json_path.display());
    written_paths.push(json_path);

    // 3. Write Playwright config if requested
    if config.include_playwright {
        let playwright_config = generate_playwright_config();
        let playwright_path = output_dir.join("playwright.config.ts");
        fs::write(&playwright_path, &playwright_config).with_context(|| {
            format!(
                "Failed to write Playwright config to {}",
                playwright_path.display()
            )
        })?;
        info!(
            "Wrote playwright.config.ts to {}",
            playwright_path.display()
        );
        written_paths.push(playwright_path);
    }

    Ok(written_paths)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::interview::phase_manager::InterviewPhaseDefinition;
    use crate::interview::state::InterviewQA;
    use tempfile::TempDir;

    fn sample_phase() -> CompletedPhase {
        CompletedPhase {
            definition: InterviewPhaseDefinition {
                id: "testing_verification".to_string(),
                domain: "Testing & Verification".to_string(),
                name: "Testing & Verification".to_string(),
                description: "Test strategy".to_string(),
                min_questions: 3,
                max_questions: 8,
            },
            decisions: vec![],
            qa_history: vec![
                InterviewQA {
                    question: "What test types?".to_string(),
                    answer: "Unit, integration, E2E".to_string(),
                    timestamp: chrono::Utc::now().to_rfc3339(),
                },
                InterviewQA {
                    question: "Use Playwright?".to_string(),
                    answer: "Yes".to_string(),
                    timestamp: chrono::Utc::now().to_rfc3339(),
                },
            ],
            document_path: std::path::PathBuf::from("phase-08-testing-verification.md"),
        }
    }

    #[test]
    fn test_generate_test_strategy_markdown() {
        let phases = vec![sample_phase()];
        let config = TestStrategyConfig::default();
        let content = generate_test_strategy_markdown("TestProject", &phases, &config).unwrap();
        assert!(content.contains("# Test Strategy: TestProject"));
        assert!(content.contains("Puppet Master"));
        assert!(content.contains("Playwright"));
        assert!(content.contains("Unit Tests"));
    }

    #[test]
    fn test_generate_test_strategy_json() {
        let phases = vec![sample_phase()];
        let config = TestStrategyConfig::default();
        let json = generate_test_strategy_json("TestProject", &phases, &config).unwrap();

        assert_eq!(json.project, "TestProject");
        assert_eq!(json.coverage_level, "Standard");
        assert!(!json.items.is_empty());

        // Check that items have required fields
        for item in &json.items {
            assert!(!item.id.is_empty());
            assert!(!item.source_phase_id.is_empty());
            assert!(!item.criterion.is_empty());
            assert!(!item.test_type.is_empty());
            assert!(!item.test_file.is_empty());
            assert!(!item.test_name.is_empty());
            assert!(!item.verification_command.is_empty());
        }
    }

    #[test]
    fn test_playwright_config_generation() {
        let config = generate_playwright_config();
        assert!(config.contains("Puppet Master"));
        assert!(config.contains("@playwright/test"));
        assert!(config.contains("testDir"));
        assert!(config.contains("chromium"));
        assert!(config.contains("firefox"));
        assert!(config.contains("webkit"));
    }

    #[test]
    fn test_coverage_levels() {
        assert_eq!(CoverageLevel::Basic.to_string(), "Basic");
        assert_eq!(CoverageLevel::Standard.to_string(), "Standard");
        assert_eq!(CoverageLevel::Comprehensive.to_string(), "Comprehensive");
    }

    #[test]
    fn test_write_test_strategy() {
        let dir = TempDir::new().unwrap();
        let phases = vec![sample_phase()];
        let config = TestStrategyConfig::default();
        let paths = write_test_strategy("TestProject", &phases, &config, dir.path()).unwrap();

        // Should write 3 files: .md, .json, playwright.config.ts
        assert_eq!(paths.len(), 3);

        // Check markdown file
        let md_path = paths
            .iter()
            .find(|p| p.to_str().unwrap().ends_with("test-strategy.md"))
            .unwrap();
        assert!(md_path.exists());
        let md_content = fs::read_to_string(md_path).unwrap();
        assert!(md_content.contains("# Test Strategy"));

        // Check JSON file
        let json_path = paths
            .iter()
            .find(|p| p.to_str().unwrap().ends_with("test-strategy.json"))
            .unwrap();
        assert!(json_path.exists());
        let json_content = fs::read_to_string(json_path).unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&json_content).unwrap();
        assert_eq!(parsed["project"], "TestProject");
        assert!(parsed["items"].is_array());

        // Check Playwright config
        let pw_path = paths
            .iter()
            .find(|p| p.to_str().unwrap().ends_with("playwright.config.ts"))
            .unwrap();
        assert!(pw_path.exists());
        let pw_content = fs::read_to_string(pw_path).unwrap();
        assert!(pw_content.contains("@playwright/test"));
    }

    #[test]
    fn test_write_test_strategy_without_playwright() {
        let dir = TempDir::new().unwrap();
        let phases = vec![sample_phase()];
        let config = TestStrategyConfig {
            include_playwright: false,
            ..Default::default()
        };
        let paths = write_test_strategy("TestProject", &phases, &config, dir.path()).unwrap();

        // Should write only 2 files: .md and .json (no playwright.config.ts)
        assert_eq!(paths.len(), 2);
        assert!(
            paths
                .iter()
                .any(|p| p.to_str().unwrap().ends_with("test-strategy.md"))
        );
        assert!(
            paths
                .iter()
                .any(|p| p.to_str().unwrap().ends_with("test-strategy.json"))
        );
        assert!(
            !paths
                .iter()
                .any(|p| p.to_str().unwrap().ends_with("playwright.config.ts"))
        );
    }

    #[test]
    fn test_determine_test_type() {
        assert_eq!(
            determine_test_type("product_ux", "Button layout"),
            "playwright"
        );
        assert_eq!(
            determine_test_type("security_secrets", "Auth flow"),
            "security"
        );
        assert_eq!(
            determine_test_type("performance_reliability", "Load test"),
            "performance"
        );
        assert_eq!(
            determine_test_type("data_persistence", "Database query"),
            "integration"
        );
        assert_eq!(determine_test_type("scope_goals", "Core logic"), "unit");
    }

    #[test]
    fn test_generate_test_name() {
        assert_eq!(
            generate_test_name("Should login with valid credentials"),
            "should_login_with_valid_credentials"
        );
        assert_eq!(
            generate_test_name("What is the authentication mechanism?"),
            "what_is_the_authentication_mechanism"
        );
    }
}
