//! PR manager - handles GitHub PR creation via gh CLI

use anyhow::{Context, Result};
use log::info;
use std::path::PathBuf;

/// Manages pull request creation
pub struct PrManager {
    repo_path: PathBuf,
}

impl PrManager {
    /// Create a new PR manager
    pub fn new(repo_path: PathBuf) -> Self {
        Self { repo_path }
    }

    /// Create a pull request using gh CLI
    ///
    /// # Arguments
    /// * `title` - PR title
    /// * `body` - PR description
    /// * `base` - Base branch (e.g., "main")
    /// * `head` - Head branch (e.g., "tk-001-002")
    pub async fn create_pr(
        &self,
        title: &str,
        body: &str,
        base: &str,
        head: &str,
    ) -> Result<PrResult> {
        info!("Creating PR: {} -> {}", head, base);

        // Run preflight checks
        match self.preflight_check().await {
            Ok(()) => {
                info!("Preflight checks passed for PR creation");
            }
            Err(e) => {
                let message = format!("Preflight check failed: {}", e);
                log::warn!("{}", message);
                return Ok(PrResult {
                    success: false,
                    pr_url: None,
                    message,
                });
            }
        }

        // Create PR using gh CLI
        let output = tokio::process::Command::new("gh")
            .current_dir(&self.repo_path)
            .args(&[
                "pr", "create", "--title", title, "--body", body, "--base", base, "--head", head,
            ])
            .output()
            .await
            .context("Failed to execute gh pr create")?;

        let success = output.status.success();
        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();

        if success {
            // Extract PR URL from output
            let pr_url = stdout
                .lines()
                .find(|line| line.contains("https://github.com"))
                .map(|line| line.trim().to_string());

            Ok(PrResult {
                success: true,
                pr_url,
                message: "Pull request created successfully".to_string(),
            })
        } else {
            Ok(PrResult {
                success: false,
                pr_url: None,
                message: format!("Failed to create PR: {}", stderr),
            })
        }
    }

    /// Generate PR title from tier information
    pub fn generate_pr_title(tier_type: &str, tier_id: &str, title: &str) -> String {
        format!("[{}] {}: {}", tier_type.to_uppercase(), tier_id, title)
    }

    /// Generate PR body from tier information
    pub fn generate_pr_body(
        description: &str,
        acceptance_criteria: &[String],
        files_changed: &[String],
    ) -> String {
        let mut body = String::new();

        // Description
        body.push_str("## Description\n\n");
        body.push_str(description);
        body.push_str("\n\n");

        // Acceptance Criteria
        if !acceptance_criteria.is_empty() {
            body.push_str("## Acceptance Criteria\n\n");
            for criterion in acceptance_criteria {
                body.push_str(&format!("- [ ] {}\n", criterion));
            }
            body.push_str("\n");
        }

        // Files Changed
        if !files_changed.is_empty() {
            body.push_str("## Files Changed\n\n");
            for file in files_changed {
                body.push_str(&format!("- `{}`\n", file));
            }
            body.push_str("\n");
        }

        body.push_str("---\n");
        body.push_str("*Generated by RWM Puppet Master*\n");

        body
    }

    /// Check if gh CLI is available
    async fn is_gh_available(&self) -> Result<bool> {
        let output = tokio::process::Command::new("which")
            .arg("gh")
            .output()
            .await?;

        Ok(output.status.success())
    }

    /// Run preflight checks before attempting PR creation
    ///
    /// Verifies:
    /// - gh CLI is installed
    /// - gh is authenticated to GitHub
    ///
    /// Returns Ok(()) if all checks pass, Err with actionable message if any fail
    pub async fn preflight_check(&self) -> Result<()> {
        // Check if gh CLI exists
        if !self.is_gh_available().await? {
            return Err(anyhow::anyhow!(
                "gh CLI not found. Install from https://cli.github.com/ and run 'gh auth login'"
            ));
        }

        // Check if gh is authenticated
        let auth_output = tokio::process::Command::new("gh")
            .args(&["auth", "status"])
            .output()
            .await
            .context("Failed to check gh authentication status")?;

        // gh auth status returns exit code 0 if authenticated
        if !auth_output.status.success() {
            let stderr = String::from_utf8_lossy(&auth_output.stderr);
            return Err(anyhow::anyhow!(
                "gh CLI not authenticated. Run 'gh auth login' to authenticate with GitHub. Details: {}",
                stderr.trim()
            ));
        }

        // Additional check: parse output for authentication confirmation
        let stdout = String::from_utf8_lossy(&auth_output.stdout);
        let stderr = String::from_utf8_lossy(&auth_output.stderr);
        let combined = format!("{}{}", stdout, stderr).to_lowercase();

        if !combined.contains("logged in") && !combined.contains("authenticated") {
            return Err(anyhow::anyhow!(
                "gh CLI authentication unclear. Please verify with 'gh auth status' and run 'gh auth login' if needed"
            ));
        }

        Ok(())
    }

    /// Build gh pr create command arguments (for testing and validation)
    pub fn build_pr_create_args(title: &str, body: &str, base: &str, head: &str) -> Vec<String> {
        vec![
            "pr".to_string(),
            "create".to_string(),
            "--title".to_string(),
            title.to_string(),
            "--body".to_string(),
            body.to_string(),
            "--base".to_string(),
            base.to_string(),
            "--head".to_string(),
            head.to_string(),
        ]
    }

    /// List open PRs
    pub async fn list_prs(&self) -> Result<Vec<PrInfo>> {
        let output = tokio::process::Command::new("gh")
            .current_dir(&self.repo_path)
            .args(&["pr", "list", "--json", "number,title,url,state"])
            .output()
            .await
            .context("Failed to list PRs")?;

        if !output.status.success() {
            return Ok(vec![]);
        }

        let stdout = String::from_utf8_lossy(&output.stdout);
        let prs: Vec<PrInfo> = serde_json::from_str(&stdout)?;

        Ok(prs)
    }

    /// Close a PR
    pub async fn close_pr(&self, pr_number: u32) -> Result<bool> {
        let output = tokio::process::Command::new("gh")
            .current_dir(&self.repo_path)
            .args(&["pr", "close", &pr_number.to_string()])
            .output()
            .await
            .context("Failed to close PR")?;

        Ok(output.status.success())
    }
}

/// Result of PR creation
#[derive(Debug, Clone)]
pub struct PrResult {
    pub success: bool,
    pub pr_url: Option<String>,
    pub message: String,
}

/// PR information
#[derive(Debug, Clone, serde::Deserialize)]
pub struct PrInfo {
    pub number: u32,
    pub title: String,
    pub url: String,
    pub state: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_pr_title() {
        let title = PrManager::generate_pr_title("task", "TK-001-002", "Add authentication");
        assert_eq!(title, "[TASK] TK-001-002: Add authentication");
    }

    #[test]
    fn test_generate_pr_body() {
        let body = PrManager::generate_pr_body(
            "Implement JWT authentication",
            &[
                "Login works".to_string(),
                "Token validation works".to_string(),
            ],
            &["src/auth.rs".to_string()],
        );

        assert!(body.contains("## Description"));
        assert!(body.contains("Implement JWT authentication"));
        assert!(body.contains("## Acceptance Criteria"));
        assert!(body.contains("Login works"));
        assert!(body.contains("## Files Changed"));
        assert!(body.contains("src/auth.rs"));
    }

    #[test]
    fn test_build_pr_create_args() {
        let args =
            PrManager::build_pr_create_args("Test PR", "This is a test", "main", "feature-branch");

        assert_eq!(args.len(), 10);
        assert_eq!(args[0], "pr");
        assert_eq!(args[1], "create");
        assert_eq!(args[2], "--title");
        assert_eq!(args[3], "Test PR");
        assert_eq!(args[4], "--body");
        assert_eq!(args[5], "This is a test");
        assert_eq!(args[6], "--base");
        assert_eq!(args[7], "main");
        assert_eq!(args[8], "--head");
        assert_eq!(args[9], "feature-branch");
    }

    #[test]
    fn test_build_pr_create_args_with_special_chars() {
        let args = PrManager::build_pr_create_args(
            "[TASK] TK-001: Feature",
            "Description with\nnewlines",
            "main",
            "rwm/task/tk-001",
        );

        assert_eq!(args[3], "[TASK] TK-001: Feature");
        assert_eq!(args[5], "Description with\nnewlines");
        assert_eq!(args[9], "rwm/task/tk-001");
    }

    #[test]
    fn test_generate_pr_body_empty_criteria() {
        let body = PrManager::generate_pr_body("Simple fix", &[], &[]);

        assert!(body.contains("## Description"));
        assert!(body.contains("Simple fix"));
        assert!(!body.contains("## Acceptance Criteria"));
        assert!(!body.contains("## Files Changed"));
        assert!(body.contains("*Generated by RWM Puppet Master*"));
    }

    #[test]
    fn test_generate_pr_body_with_markdown() {
        let body = PrManager::generate_pr_body(
            "Fix bug with **bold** text",
            &["- [ ] Test passes".to_string()],
            &["src/main.rs".to_string()],
        );

        assert!(body.contains("Fix bug with **bold** text"));
        assert!(body.contains("- [ ] - [ ] Test passes")); // Note: double checkbox due to adding another
    }

    #[test]
    fn test_pr_result_creation() {
        let result = PrResult {
            success: true,
            pr_url: Some("https://github.com/owner/repo/pull/42".to_string()),
            message: "Success".to_string(),
        };

        assert!(result.success);
        assert_eq!(
            result.pr_url.unwrap(),
            "https://github.com/owner/repo/pull/42"
        );
    }

    #[test]
    fn test_pr_result_failure() {
        let result = PrResult {
            success: false,
            pr_url: None,
            message: "Authentication failed".to_string(),
        };

        assert!(!result.success);
        assert!(result.pr_url.is_none());
        assert!(result.message.contains("Authentication failed"));
    }

    #[test]
    fn test_generate_pr_title_various_tiers() {
        assert_eq!(
            PrManager::generate_pr_title("phase", "P1", "Phase 1"),
            "[PHASE] P1: Phase 1"
        );
        assert_eq!(
            PrManager::generate_pr_title("subtask", "ST-001", "Fix bug"),
            "[SUBTASK] ST-001: Fix bug"
        );
    }
}
