//! PR manager - handles GitHub PR creation via gh CLI

use anyhow::{Context, Result};
use log::info;
use std::path::PathBuf;

/// Manages pull request creation
pub struct PrManager {
    repo_path: PathBuf,
}

impl PrManager {
    /// Create a new PR manager
    pub fn new(repo_path: PathBuf) -> Self {
        Self { repo_path }
    }

    /// Create a pull request using gh CLI
    ///
    /// # Arguments
    /// * `title` - PR title
    /// * `body` - PR description
    /// * `base` - Base branch (e.g., "main")
    /// * `head` - Head branch (e.g., "tk-001-002")
    pub async fn create_pr(
        &self,
        title: &str,
        body: &str,
        base: &str,
        head: &str,
    ) -> Result<PrResult> {
        info!("Creating PR: {} -> {}", head, base);

        // Check if gh CLI is available
        if !self.is_gh_available().await? {
            return Err(anyhow::anyhow!("gh CLI not found. Please install it from https://cli.github.com/"));
        }

        // Create PR using gh CLI
        let output = tokio::process::Command::new("gh")
            .current_dir(&self.repo_path)
            .args(&[
                "pr",
                "create",
                "--title",
                title,
                "--body",
                body,
                "--base",
                base,
                "--head",
                head,
            ])
            .output()
            .await
            .context("Failed to execute gh pr create")?;

        let success = output.status.success();
        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();

        if success {
            // Extract PR URL from output
            let pr_url = stdout
                .lines()
                .find(|line| line.contains("https://github.com"))
                .map(|line| line.trim().to_string());

            Ok(PrResult {
                success: true,
                pr_url,
                message: "Pull request created successfully".to_string(),
            })
        } else {
            Ok(PrResult {
                success: false,
                pr_url: None,
                message: format!("Failed to create PR: {}", stderr),
            })
        }
    }

    /// Generate PR title from tier information
    pub fn generate_pr_title(tier_type: &str, tier_id: &str, title: &str) -> String {
        format!("[{}] {}: {}", tier_type.to_uppercase(), tier_id, title)
    }

    /// Generate PR body from tier information
    pub fn generate_pr_body(
        description: &str,
        acceptance_criteria: &[String],
        files_changed: &[String],
    ) -> String {
        let mut body = String::new();

        // Description
        body.push_str("## Description\n\n");
        body.push_str(description);
        body.push_str("\n\n");

        // Acceptance Criteria
        if !acceptance_criteria.is_empty() {
            body.push_str("## Acceptance Criteria\n\n");
            for criterion in acceptance_criteria {
                body.push_str(&format!("- [ ] {}\n", criterion));
            }
            body.push_str("\n");
        }

        // Files Changed
        if !files_changed.is_empty() {
            body.push_str("## Files Changed\n\n");
            for file in files_changed {
                body.push_str(&format!("- `{}`\n", file));
            }
            body.push_str("\n");
        }

        body.push_str("---\n");
        body.push_str("*Generated by RWM Puppet Master*\n");

        body
    }

    /// Check if gh CLI is available
    async fn is_gh_available(&self) -> Result<bool> {
        let output = tokio::process::Command::new("which")
            .arg("gh")
            .output()
            .await?;

        Ok(output.status.success())
    }

    /// List open PRs
    pub async fn list_prs(&self) -> Result<Vec<PrInfo>> {
        let output = tokio::process::Command::new("gh")
            .current_dir(&self.repo_path)
            .args(&["pr", "list", "--json", "number,title,url,state"])
            .output()
            .await
            .context("Failed to list PRs")?;

        if !output.status.success() {
            return Ok(vec![]);
        }

        let stdout = String::from_utf8_lossy(&output.stdout);
        let prs: Vec<PrInfo> = serde_json::from_str(&stdout)?;

        Ok(prs)
    }

    /// Close a PR
    pub async fn close_pr(&self, pr_number: u32) -> Result<bool> {
        let output = tokio::process::Command::new("gh")
            .current_dir(&self.repo_path)
            .args(&["pr", "close", &pr_number.to_string()])
            .output()
            .await
            .context("Failed to close PR")?;

        Ok(output.status.success())
    }
}

/// Result of PR creation
#[derive(Debug, Clone)]
pub struct PrResult {
    pub success: bool,
    pub pr_url: Option<String>,
    pub message: String,
}

/// PR information
#[derive(Debug, Clone, serde::Deserialize)]
pub struct PrInfo {
    pub number: u32,
    pub title: String,
    pub url: String,
    pub state: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_pr_title() {
        let title = PrManager::generate_pr_title("task", "TK-001-002", "Add authentication");
        assert_eq!(title, "[TASK] TK-001-002: Add authentication");
    }

    #[test]
    fn test_generate_pr_body() {
        let body = PrManager::generate_pr_body(
            "Implement JWT authentication",
            &["Login works".to_string(), "Token validation works".to_string()],
            &["src/auth.rs".to_string()],
        );

        assert!(body.contains("## Description"));
        assert!(body.contains("Implement JWT authentication"));
        assert!(body.contains("## Acceptance Criteria"));
        assert!(body.contains("Login works"));
        assert!(body.contains("## Files Changed"));
        assert!(body.contains("src/auth.rs"));
    }
}
