/* Injected verification only. Uses real owner commands on complete HTML. */
window.B18_CASES={};
(()=>{
const tests=B18_CASES,clone=x=>JSON.parse(JSON.stringify(x)),S=PM56_SCHED,C=PM56_COMPOSER_STATE,A=PM56_ARTIFACTS;
function setup(){const ctx=PM56_EXT.ctx(),t=clone(ctx.state.threads.find(t=>t.id==='query'));Object.assign(t,{id:'b18-test',title:'B18 verification',messages:[],projectId:'b18',worktreeId:'b18',archived:false});ctx.state.threads.push(t);ctx.switchThread(t.id);ctx.state.model=PM56_DATA.models.find(m=>m.status==='ready').id;ctx.state.composer='  Keep whitespace\nexactly.  ';const b=C.bufferFor(t.id);b.text=ctx.state.composer;b.attachments=[];b.destination=null;PM56_RUNTIME.composer.destination=null;PM56_RUNTIME.quota.waiting=false;S.restore();return PM56_EXT.ctx();}
function draft(){const d=S.messageDraft();d.date='2027-05-10';d.time='22:00';d.timezone='America/New_York';return d;}
function create(){const out=S.saveMessage(draft());if(!out.ok)throw Error(JSON.stringify(out));return out.record;}
function count(){return PM56_EXT.ctx().thread.messages.filter(m=>m.viaSchedule).length;}
function attach(ctx){const q={artifact_id:'b18-input',artifact_version:1,project_id:'b18',thread_id:ctx.thread.id,renderer_kind:'json',title:'Supplied values',payload:{values:[3,7,11]}};const out=A.publish(q);if(!out.ok)throw Error(out.error);const ref={artifact_id:q.artifact_id,artifact_version:1,project_id:'b18',thread_id:ctx.thread.id};C.bufferFor(ctx.thread.id).attachments=[{id:'a1',name:'values.json',kind:'file',snapshot_ref:ref}];return {q,ref};}
tests.exact_text_and_composer_commit=check=>{const ctx=setup(),before=ctx.state.composer,m=create();check('Whitespace preserved',m.text===before);check('Composer cleared only after successful local commit',ctx.state.composer===''&&C.bufferFor(ctx.thread.id).text==='');check('Exactly one lifecycle card, no sent message',ctx.thread.messages.filter(m=>m.type==='sched-message').length===1&&count()===0);};
tests.future_delivery_and_replay=check=>{setup();const m=create(),at=Date.parse(m.scheduled_at_utc),early=S.dispatchMessageAt(m.scheduled_dispatch_id,at-1);check('No early dispatch',early.error==='not_due'&&count()===0&&m.state==='scheduled');const t=S.messageTicket(m.scheduled_dispatch_id,at).ticket,r=S.deliverMessage(t),again=S.deliverMessage(t);check('One actual user message at dispatch time',r.ok&&count()===1&&PM56_EXT.ctx().thread.messages.at(-1).time===new Date(at).toISOString());check('Replay returns same ID',again.duplicate&&again.message_id===r.message_id&&count()===1);};
tests.exact_artifact_version=check=>{const ctx=setup(),{q,ref}=attach(ctx),m=create();A.publish({...q,artifact_version:2,payload:{values:[999]}});const out=S.dispatchMessageAt(m.scheduled_dispatch_id,Date.parse(m.scheduled_at_utc));check('Delivered original V1 reference',out.ok&&ctx.thread.messages.at(-1).attachments[0].artifact_version===1);check('Retained original bytes',A.resolve(ctx.thread.messages.at(-1).attachments[0].snapshot_ref).revision.record.payload.values.join(',')==='3,7,11');check('Schedule reachability holds V1',A.purge(ref).error==='artifact_still_referenced');};
tests.unavailable_attachment_holds=check=>{const ctx=setup(),{q}=attach(ctx),m=create();PM56_DATA.artifacts.find(a=>a.id===q.artifact_id).revisionAvailability={1:'missing'};const r=S.dispatchMessageAt(m.scheduled_dispatch_id,Date.parse(m.scheduled_at_utc));check('Unavailable exact V1 holds',r.held&&m.state==='held'&&count()===0);check('Attempt records named missing reason',m.dispatch_attempts.length===1&&m.heldReason.includes('unavailable'));};
tests.composer_changed_during_modal=check=>{const ctx=setup(),d=draft();ctx.state.composer='New text must survive';const before=clone(C.captureForSchedule(ctx,ctx.thread.id)),r=S.saveMessage(d);check('Stale modal refused',r.error==='composer_changed');check('Composer and schedules unchanged',JSON.stringify(before)===JSON.stringify(C.captureForSchedule(ctx,ctx.thread.id))&&S.list().messages.every(m=>m.thread_id!==ctx.thread.id));};
tests.failed_retention_rolls_back=check=>{const ctx=setup();attach(ctx);const d=draft(),before=clone(C.captureForSchedule(ctx,ctx.thread.id)),original=A.retain;A.retain=()=>({ok:false,error:'injected_retention_failure'});let r;try{r=S.saveMessage(d);}finally{A.retain=original;}check('Failed owner helper refused',r.error==='injected_retention_failure');check('No partial schedule/card/composer consumption',JSON.stringify(before)===JSON.stringify(C.captureForSchedule(ctx,ctx.thread.id))&&!ctx.thread.messages.length&&!S.list().messages.some(m=>m.thread_id===ctx.thread.id));};
tests.stale_edit_and_cancel=check=>{setup();const m=create(),token=S.captureMessage(m.scheduled_dispatch_id),d=S.editMessageDraft(m.scheduled_dispatch_id),stale=S.editMessageDraft(m.scheduled_dispatch_id);d.text='Revised exact message';const r=S.saveMessage(d,m.scheduled_dispatch_id);check('Edit retains identity and advances revision',r.ok&&r.record===m&&m.revision===2&&m.history[0].snapshot.text.startsWith('  '));stale.text='Stale overwrite';check('Concurrent stale edit refused',S.saveMessage(stale,m.scheduled_dispatch_id).error==='stale_schedule_revision');check('Stale cancel refused',S.cancelMessageExact(m.scheduled_dispatch_id,token).error==='stale_schedule_revision');};
tests.cancel_fences_decided_delivery=check=>{setup();const m=create(),t=S.messageTicket(m.scheduled_dispatch_id,Date.parse(m.scheduled_at_utc)).ticket;check('Cancel succeeds',S.cancelMessageExact(m.scheduled_dispatch_id,S.captureMessage(m.scheduled_dispatch_id)).ok);check('Old ticket refused',S.deliverMessage(t).error==='stale_schedule_revision'&&count()===0&&m.state==='canceled');};
tests.stop_between_decision_and_delivery=check=>{setup();const m=create(),t=S.messageTicket(m.scheduled_dispatch_id,Date.parse(m.scheduled_at_utc)).ticket;S.latchStop('Manual Stop');const r=S.deliverMessage(t);check('Stop wins',r.error==='manual_stop_latched'&&count()===0);check('Held record names stop',m.state==='held'&&m.heldReason.includes('epoch'));};
tests.explicit_route_unavailable=check=>{setup();const m=create(),model=PM56_DATA.models.find(x=>x.id===m.requested_runtime.modelId);model.status='unavailable';const r=S.dispatchMessageAt(m.scheduled_dispatch_id,Date.parse(m.scheduled_at_utc));check('No model/account fallback',r.held&&r.error==='route_unavailable'&&count()===0);};
tests.unknown_destination_preserves_source=check=>{const ctx=setup(),d=draft(),before=ctx.state.composer;d.destination={kind:'ended-room',refId:'room-closed',label:'Old room'};const r=S.saveMessage(d);check('No fallback to assistant',r.error==='destination_owner_unavailable'&&ctx.state.composer===before&&count()===0);};
tests.live_browser_context_refuses=check=>{const ctx=setup(),d=draft();d.browser_context_refs=[{kind:'BrowserElementContext',selector:'#live'}];const r=S.saveMessage(d);check('Live selector never scheduled',r.error==='live_browser_context_not_schedulable'&&ctx.state.composer.length>0);};
tests.same_time_same_text_independent=check=>{const ctx=setup(),a=create();ctx.state.composer=a.text;C.bufferFor(ctx.thread.id).text=a.text;const b=create();check('Distinct independent identities',a.scheduled_dispatch_id!==b.scheduled_dispatch_id);const at=Date.parse(a.scheduled_at_utc);check('Each dispatched once',S.dispatchMessageAt(a.scheduled_dispatch_id,at).ok&&S.dispatchMessageAt(b.scheduled_dispatch_id,at).ok&&count()===2);};
tests.missed_policy_hold=check=>{setup();const m=create(),r=S.dispatchMessageAt(m.scheduled_dispatch_id,Date.parse(m.scheduled_at_utc)+31*60000);check('Missed time held',r.error==='missed_time_held'&&m.state==='held'&&count()===0);};
tests.missed_policy_expire=check=>{setup();const d=draft();d.missed='cancel_after_grace';d.grace=5;const m=S.saveMessage(d).record,r=S.dispatchMessageAt(m.scheduled_dispatch_id,Date.parse(m.scheduled_at_utc)+6*60000);check('Expired after grace',r.expired&&m.state==='expired'&&count()===0);};
tests.missed_policy_next_available=check=>{setup();const d=draft();d.missed='next_available';const m=S.saveMessage(d).record,r=S.dispatchMessageAt(m.scheduled_dispatch_id,Date.parse(m.scheduled_at_utc)+86400000);check('Only one late send, not backlog burst',r.ok&&count()===1&&S.dispatchMessageAt(m.scheduled_dispatch_id,Date.parse(m.scheduled_at_utc)+2*86400000).duplicate&&count()===1);};
tests.sent_is_immutable=check=>{setup();const m=create(),d=S.editMessageDraft(m.scheduled_dispatch_id);S.dispatchMessageAt(m.scheduled_dispatch_id,Date.parse(m.scheduled_at_utc));d.text='Overwrite sent';check('Sent edit refuses',S.saveMessage(d,m.scheduled_dispatch_id).error==='dispatch_already_started');check('Sent cancel refuses',S.cancelMessageExact(m.scheduled_dispatch_id,S.captureMessage(m.scheduled_dispatch_id)).error==='dispatch_already_started');};
tests.scope_and_permission_revalidation=check=>{const ctx=setup(),m=create();ctx.state.permissions='changed-test-policy';const r=S.dispatchMessageAt(m.scheduled_dispatch_id,Date.parse(m.scheduled_at_utc));check('Permission change held',r.error==='permission_snapshot_changed'&&count()===0);};
tests.create_idempotency_domain=check=>{setup();const d=draft(),a=S.saveMessage(d),b=S.saveMessage(d);check('Create replay returns original schedule',a.ok&&b.ok&&b.replayed&&a.record===b.record);d.text='Different binding';check('Same key/different binding refuses',S.saveMessage(d).error==='idempotency_conflict');};
tests.mutation_of_snapshot_refuses=check=>{setup();const m=create();m.text='corrupted';const r=S.dispatchMessageAt(m.scheduled_dispatch_id,Date.parse(m.scheduled_at_utc));check('Corrupt binding refused',r.error==='snapshot_changed'&&count()===0);};
tests.failed_delivery_retains_attempt=check=>{const ctx=setup(),m=create(),original=PM56_TX.append;PM56_TX.append=(object,key,value)=>{if(key==='messages'&&value?.viaSchedule)throw Error('injected_delivery_failure');return original(object,key,value);};let r;try{r=S.dispatchMessageAt(m.scheduled_dispatch_id,Date.parse(m.scheduled_at_utc));}finally{PM56_TX.append=original;}check('Failed dispatch has no user message',!r.ok&&count()===0);check('Failed attempt stays inspectable',m.state==='failed'&&m.dispatch_attempts.length===1&&!!m.failureReason);};
tests.changed_route_during_publication_rolls_back=check=>{const ctx=setup(),m=create(),model=PM56_DATA.models.find(x=>x.id===m.requested_runtime.modelId),original=PM56_TX.append;PM56_TX.append=(object,key,value)=>{const x=original(object,key,value);if(key==='messages'&&value?.viaSchedule)model.status='unavailable';return x;};let out;try{out=S.dispatchMessageAt(m.scheduled_dispatch_id,Date.parse(m.scheduled_at_utc));}finally{PM56_TX.append=original;}check('Returning append helper cannot evade route revalidation',!out.ok&&out.error==='route_unavailable'&&count()===0);check('No success receipt after failed transaction',!m.dispatch_receipt&&m.state==='failed');};
tests.message_timezone_requires_name=check=>{const ctx=setup(),d=draft(),before=ctx.state.composer;for(const zone of ['+03:00','-05:00',null]){const out=S.saveMessage({...clone(d),timezone:zone});check('Unnamed timezone refused '+zone,!out.ok&&ctx.state.composer===before&&!S.list().messages.some(m=>m.thread_id===ctx.thread.id));}};
})();
