/* Injected tests; real schedule/Plan/To-Do owners and local work adapter. */
(()=>{
const S=PM56_SCHED,P=PM56_PLANS,T=PM56_TODOS,E=PM56_EXT,W=PM56_B17_WORK,tests=B18_CASES,copy=x=>JSON.parse(JSON.stringify(x));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){for(let i=0;i<120;i++){if(fn())return;await sleep(100);}throw Error('Local work did not reach expected boundary');}
function setup(){S.restore();PM56_RUNTIME.quota.waiting=false;PM56_B18.start('windows');document.querySelector('[data-action="send"]').click();const w=W.snapshot(),p=P.get(w.planId);if(!p)throw Error('Plan request did not commit');const d=S.buildDraft(p.plan_id,p.version);Object.assign(d,{timezone:'America/New_York',startTime:'22:00',pauseTime:'23:00',days:[0,1,2,3,4,5,6],windDown:10});return {p,d};}
function schedule(d){const out=S.saveBuild(d);if(!out.ok)throw Error(JSON.stringify(out));return out.record;}
function open(b){const at=Date.parse(b.next_occurrence_at||b.scheduled_at_utc),out=S.windowTick(b.schedule_id,at,S.captureBuild(b.schedule_id));if(!out.ok)throw Error(JSON.stringify(out));return {at,out};}
function tick(b,at){return S.windowTick(b.schedule_id,at,S.captureBuild(b.schedule_id));}
function next(b,at){return PM56_SCHEDULE_TIME.next(b.timezone,b.days_of_week,22,0,at+1);}
function bindingCount(p){return T.get(p.thread_id).filter(t=>t.run_id===p.approved?.plan_run_id).length;}
tests.window_create_is_not_execution=check=>{const {p,d}=setup(),b=schedule(d);check('No run/Goal/admitted To-Dos at schedule commit',p.status==='ready'&&!p.approved&&!b.dispatchReceipt&&!PM56_GOAL.get()&&(T.get(p.thread_id)||[]).every(t=>!t.run_id));check('Frozen requested topology',b.execution_topology==='agent'&&b.topology_snapshot.execution_topology==='agent');};
tests.window_first_admission_calendar=check=>{const {p,d}=setup(),b=schedule(d),at=Date.parse(b.next_occurrence_at);check('Before opening refuses',tick(b,at-1).error==='window_not_open'&&!p.approved);const w=S.buildWindow(b,at);check('First admission during wind-down refuses',tick(b,w.wind_down_at).error==='window_inactive'&&!p.approved);check('First admission after end refuses',tick(b,w.end).error==='window_inactive'&&!p.approved);check('Next actual opening admits',tick(b,next(b,w.end)).ok&&p.status==='building'&&bindingCount(p)===3);};
tests.window_pause_resume_same_run=async check=>{const {p,d}=setup(),b=schedule(d),{at}=open(b),run=p.approved.plan_run_id;await until(()=>!!W.snapshot().outputs.normalize);const output=copy(W.snapshot().outputs.normalize),ids=T.get(p.thread_id).map(t=>t.todo_id),w=S.buildWindow(b,at);const wind=tick(b,w.wind_down_at);check('Wind-down reaches real safe boundary',wind.paused&&p.attention?.kind==='window'&&P.buildLabel(p.plan_id)==='Building…');await sleep(1700);check('No next work during wind-down',Object.keys(W.snapshot().outputs).join(',')==='normalize');tick(b,w.end);const resume=tick(b,next(b,w.end));check('Same run/To-Do identity resumed',resume.resumed&&p.approved.plan_run_id===run&&JSON.stringify(T.get(p.thread_id).map(t=>t.todo_id))===JSON.stringify(ids));await until(()=>p.status==='completed');check('Original output preserved and exact total completed',JSON.stringify(W.snapshot().outputs.normalize)===JSON.stringify(output)&&W.snapshot().outputs.total&&bindingCount(p)===3);const again=tick(b,next(b,b.clock_ms+86400000));check('Completion prevents another nightly build',again.completed&&p.approved.plan_run_id===run&&P.buildLabel(p.plan_id)==='Completed');};
tests.window_inflight_winddown=async check=>{const {p,d}=setup(),b=schedule(d),{at}=open(b);await until(()=>T.get(p.thread_id).some(t=>t.status==='in_progress'));const w=S.buildWindow(b,at),out=tick(b,w.wind_down_at);check('Bounded in-flight operation allowed to finish',out.winding_down);await until(()=>!!W.snapshot().outputs.normalize);await sleep(1600);check('No new work admitted after bounded operation',Object.keys(W.snapshot().outputs).join(',')==='normalize'&&p.attention?.kind==='window');};
tests.window_quota_and_window_conjunction=async check=>{const {p,d}=setup(),b=schedule(d),{at}=open(b);PM56_RUNTIME.quota.waiting=true;let r=tick(b,at);check('Quota pauses the same run',r.error==='quota_unavailable'&&p.attention.kind==='quota_wait');const w=S.buildWindow(b,at);tick(b,w.end);PM56_RUNTIME.quota.waiting=false;r=tick(b,w.end);check('Usage becoming available outside window cannot resume',r.paused&&p.attention.kind==='window');r=tick(b,next(b,w.end));check('Next window does not bypass missing run-scoped consent',r.error==='quota_resume_consent_required');check('Explicit exact run consent succeeds',S.setPlanQuotaConsent(p.plan_id,true).ok);r=tick(b,b.clock_ms);check('Both predicates and consent resume original run',r.resumed&&b.plan_run_id===p.approved.plan_run_id);};
tests.window_manual_stop_wins=check=>{const {p,d}=setup(),b=schedule(d),{at}=open(b),token=S.captureBuild(b.schedule_id);S.latchStop('Stop from user');check('Earlier window decision is fenced',S.windowTick(b.schedule_id,at,token).error==='stale_window_decision');check('Fresh token cannot bypass latched Stop',tick(b,next(b,at+86400000)).error==='manual_stop_latched');};
tests.window_manual_plan_pause_wins=check=>{const {p,d}=setup(),b=schedule(d),{at}=open(b);P.boundPause(p.plan_id);check('Window opening never clears manual Plan Pause',tick(b,at).error==='manual_pause_or_owner_block'&&p.attention.kind==='paused');};
tests.window_cancel_does_not_stop_run=check=>{const {p,d}=setup(),b=schedule(d);open(b);const run=p.approved.plan_run_id;check('Window cancel succeeds',S.cancelBuildExact(b.schedule_id,S.captureBuild(b.schedule_id)));check('Admitted run remains owned by Plan',p.status==='building'&&p.approved.plan_run_id===run&&S.workEligibility(p.plan_id).ok);};
tests.window_stale_edit_and_cancel=check=>{const {d}=setup(),b=schedule(d),token=S.captureBuild(b.schedule_id),one=S.editBuildDraft(b.schedule_id),two=S.editBuildDraft(b.schedule_id);one.pauseTime='23:30';const result=S.saveBuild(one,b.schedule_id);check('One record revised atomically',result.ok&&result.record===b&&b.revision===2&&b.local_pause==='23:30');two.pauseTime='23:15';check('Stale draft refused',S.saveBuild(two,b.schedule_id).error==='stale_schedule_revision');check('Stale cancel refused',!S.cancelBuildExact(b.schedule_id,token)&&b.state==='active');};
tests.window_create_and_dispatch_idempotency=check=>{const {p,d}=setup(),a=S.saveBuild(d),b=a.record,again=S.saveBuild(d);check('Commit replay returns one schedule',again.ok&&again.record===b&&S.list().builds.filter(x=>x.target_id===p.plan_id).length===1);const {at}=open(b),run=p.approved.plan_run_id,r=S.dispatchBuildAt(b.schedule_id,at,b.revision);check('First-dispatch replay returns original PlanRun',r.duplicate&&r.receipt.plan_run_id===run&&bindingCount(p)===3);d.pauseTime='23:30';check('Same request key cannot change binding',S.saveBuild(d).error==='idempotency_conflict');};
tests.window_route_and_scope_revalidation=check=>{const {p,d}=setup(),b=schedule(d),old=E.ctx().thread.worktreeId;E.ctx().thread.worktreeId='different';let r=tick(b,Date.parse(b.next_occurrence_at));check('Moved worktree refuses before any run',r.error==='worktree_snapshot_changed'&&!p.approved);E.ctx().thread.worktreeId=old;PM56_DATA.models.find(m=>m.id===b.runtime_snapshot.modelId).status='unavailable';r=tick(b,Date.parse(b.next_occurrence_at));check('Unavailable exact model has no fallback',r.error==='route_unavailable'&&!p.approved);};
tests.window_goal_created_only_at_dispatch=check=>{const {p,d}=setup();d.executionTopology='goal_driven';const b=schedule(d);check('Future schedule creates no Goal',!PM56_GOAL.get()&&!p.approved);open(b);check('Dispatch creates bound Goal with one PlanRun',!!PM56_GOAL.get()&&b.goal_id===p.goalBinding.goal_id&&b.plan_run_id===p.approved.plan_run_id);};
tests.window_topology_mismatch_refuses=check=>{const {p,d}=setup(),b=schedule(d);b.topology_snapshot={execution_topology:'crew'};const r=tick(b,Date.parse(b.next_occurrence_at));check('No topology substitution',r.error==='topology_snapshot_changed'&&!p.approved&&!PM56_GOAL.get());};
tests.window_unknown_crew_owner_refuses=check=>{const {p,d}=setup();d.executionTopology='crew';const r=S.saveBuild(d);check('Missing atomic Crew adapter is not simulated success',!r.ok&&!p.approved&&!S.list().builds.some(x=>x.target_id===p.plan_id));};
tests.window_invalid_clock_and_days_refuse=check=>{const {d}=setup();d.startTime='25:00';check('Invalid time refused',!S.saveBuild(d).ok);d.startTime='22:00';d.days=[9];check('Invalid weekdays refused',!S.saveBuild(d).ok);};
tests.window_edit_after_dispatch_refuses=check=>{const {d}=setup(),b=schedule(d),edit=S.editBuildDraft(b.schedule_id);open(b);edit.pauseTime='23:30';check('Dispatch wins race against old edit',!S.saveBuild(edit,b.schedule_id).ok&&b.local_pause==='23:00');};
tests.window_invalid_command_payload_is_atomic=check=>{const {p,d}=setup();for(const change of [{kind:'unknown'},{kind:'one_time',date:'not-a-date'},{kind:'one_time',date:'2020-01-01',time:'22:00'},{windDown:'bad'},{windDown:-1},{autoResumeNext:'yes'},{missed:'burst'}]){const out=S.saveBuild({...copy(d),...change});check('Invalid command refused '+JSON.stringify(change),!out.ok&&!p.approved&&!S.list().builds.some(b=>b.target_id===p.plan_id));}};
tests.window_timezone_requires_name=check=>{const {p,d}=setup();for(const timezone of ['+03:00','-05:00',null]){const out=S.saveBuild({...copy(d),timezone});check('Window offset cannot replace named zone '+timezone,!out.ok&&!p.approved&&!S.list().builds.some(b=>b.target_id===p.plan_id));}};
})();
